// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Air.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Air` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// Air Helmholtz equation of state (from CoolProp).
pub static AIR: FluidEos = FluidEos {
    name: "Air",
    molar_mass: 0.02896546,
    gas_constant: 8.31451,
    t_reducing: 132.6312,
    rho_reducing: 10447.7,
    t_critical: 132.5306,
    rho_critical: 11830.800000000001,
    p_critical: 3786000.0,
    t_triple: 59.75,
    t_max: 2000.0,
    p_max: 2000000000.0,
    acentric: 0.0335,
    residual: &[
    ResidualTerm::Power { n: &[0.118160747229, 0.713116392079, -1.61824192067, 0.0714140178971, -0.0865421396646, 0.134211176704, 0.0112626704218, -0.0420533228842, 0.0349008431982, 0.000164957183186, -0.101365037912, -0.17381369097, -0.0472103183731, -0.0122523554253, -0.146629609713, -0.0316055879821, 0.000233594806142, 0.0148287891978, -0.00938782884667], t: &[0.0, 0.33, 1.01, 0.0, 0.0, 0.15, 0.0, 0.2, 0.35, 1.35, 1.6, 0.8, 0.95, 1.25, 3.6, 6.0, 3.25, 3.5, 15.0], d: &[1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 4.0, 4.0, 4.0, 6.0, 1.0, 3.0, 5.0, 6.0, 1.0, 3.0, 11.0, 1.0, 3.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::Power { n: &[6.057194e-08, -2.10274769e-05, -0.000158860716, -13.841928076, 17.275266575, -0.00019536342], t: &[-3.0, -2.0, -1.0, 0.0, 1.0, 1.5] },
    IdealTerm::LogTau { a: 2.490888032 },
    IdealTerm::PlanckEinstein { n: &[0.791309509, 0.212236768], t: &[25.36365, 16.90741] },
    IdealTerm::PlanckEinsteinGeneralized { n: &[-0.197938904], theta: &[87.31279], c: &[0.6666666666666666], d: &[1.0] },
    IdealTerm::EnthalpyEntropyOffset { a1: 10.3753039487406, a2: 3.31112445645577 },
    ],
};

