// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Ammonia.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Ammonia` Helmholtz EOS, as hardcoded `const` data.

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// Ammonia Helmholtz equation of state (from CoolProp).
pub static AMMONIA: FluidEos = FluidEos {
    name: "Ammonia",
    molar_mass: 0.01703052,
    gas_constant: 8.3144598,
    t_reducing: 405.56,
    rho_reducing: 13696.0,
    t_critical: 405.56,
    rho_critical: 13696.0,
    p_critical: 11363391.162815327,
    t_triple: 195.49,
    t_max: 725.0,
    p_max: 1000000000.0,
    acentric: 0.2556905229865023,
    residual: &[
    ResidualTerm::Power { n: &[0.006132232, 1.7395866, -2.2261792, -0.30127553, 0.08967023, -0.076387037, -0.84063963, -0.27026327], t: &[1.0, 0.382, 1.0, 1.0, 0.677, 2.915, 3.51, 1.063], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 3.0, 2.0, 3.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[6.212578, -5.7844357, 2.4817542, -2.3739168, 0.01493697, -3.7749264, 0.0006254348, -1.7359e-05, -0.13462033, 0.07749072839], t: &[0.655, 1.3, 3.1, 1.4395, 1.623, 0.643, 1.13, 4.5, 1.0, 4.0], d: &[1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 1.0, 1.0], eta: &[0.42776, 0.6424, 0.8175, 0.7995, 0.91, 0.3574, 1.21, 4.14, 22.56, 22.68], epsilon: &[-0.0726, -0.1274, 0.7527, 0.57, 2.2, -0.243, 2.96, 3.02, 0.9574, 0.9576], beta: &[1.708, 1.4865, 2.0915, 2.43, 0.488, 1.1, 0.85, 1.14, 945.64, 993.85], gamma: &[1.036, 1.2777, 1.083, 1.2906, 0.928, 0.934, 0.919, 1.852, 1.05897, 1.05277] },
    ResidualTerm::GaoB { n: &[-1.6909858, 0.93739074], t: &[4.3315, 4.015], d: &[1.0, 1.0], eta: &[-2.8452, -2.8342], beta: &[0.3696, 0.2962], gamma: &[1.108, 1.313], epsilon: &[0.4478, 0.44689], b: &[1.244, 0.6826] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -6.59406093943886, a2: 5.60101151987913 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[2.224, 3.148, 0.9579], t: &[4.0585856593352405, 9.776605187888352, 17.829667620080876] },
    ],
};

