// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Benzene.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Benzene` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};
use crate::transport::{FluidTransport, ViscosityModel, ViscosityDilute, ViscosityHigherOrder, ViscosityInitial, ConductivityModel, ConductivityDilute, ConductivityResidual, CriticalConductivity};

/// Benzene Helmholtz equation of state (from CoolProp).
pub static BENZENE: FluidEos = FluidEos {
    name: "Benzene",
    molar_mass: 0.07811180000000001,
    gas_constant: 8.314472,
    t_reducing: 562.02,
    rho_reducing: 3902.0,
    t_critical: 562.02,
    rho_critical: 3902.0,
    p_critical: 4894000.0,
    t_triple: 278.674,
    t_max: 725.0,
    p_max: 500000000.0,
    acentric: 0.2108369732700151,
    residual: &[
    ResidualTerm::Power { n: &[0.03513062, 2.229707, -3.100459, -0.5763224, 0.2504179, -0.7049091, -0.1393433, 0.8319673, -0.3310741, -0.02793578], t: &[1.0, 0.3, 0.744, 1.174, 0.68, 2.5, 3.67, 1.26, 2.6, 0.95], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[0.7087408, -0.3723906, -0.06267414, -0.86295], t: &[1.0, 2.47, 3.35, 0.75], d: &[1.0, 1.0, 3.0, 3.0], eta: &[1.032, 1.423, 1.071, 14.35], epsilon: &[0.7289, 0.9074, 0.7655, 0.8711], beta: &[1.867, 1.766, 1.824, 297.5], gamma: &[1.118, 0.6392, 0.6536, 1.164] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -0.6740687105, a2: 2.5560188958 },
    IdealTerm::LogTau { a: 2.94645 },
    IdealTerm::PlanckEinstein { n: &[7.36374, 18.649, 4.01834], t: &[7.32358279064802, 2.6885164229031, 1.120956549588983] },
    IdealTerm::EnthalpyEntropyOffset { a1: -2.8421709430404e-12, a2: 4.99600884354027e-11 },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static BENZENE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 4894000.0, t_r: 562.02, using_tau_r: true, exponential: true, n: &[0.005561906558935796, -0.08662136922915314, -6.964182734154488, 1.1249288132278856, -3.961859460597414, -13.106880507410812], t: &[0.037, 0.505, 1.014, 1.469, 3.711, 12.647] },
    rho_l: SatAncillary { reducing_value: 3902.0, t_r: 562.02, using_tau_r: false, exponential: false, n: &[2.852587673922022, -0.5596547795188646, 14.872052666571532, -66.42959110979461, 1158.1329856052375, -3128.774352224071], t: &[0.407, 0.565, 4.029, 5.699, 9.989, 12.299] },
    rho_v: SatAncillary { reducing_value: 3902.0, t_r: 562.02, using_tau_r: true, exponential: true, n: &[0.016427739193323233, -2.618439385733185, -2.5904375872364365, 23.553523125085235, -27.279655904334827, -452.1839777043696], t: &[0.067, 0.387, 0.865, 2.692, 2.792, 15.611] },
};

/// Transport models (CoolProp): dynamic viscosity and/or thermal
/// conductivity (dilute + residual + near-critical; see `crate::transport`).
pub static BENZENE_TRANSPORT: FluidTransport = FluidTransport {
    viscosity: Some(ViscosityModel::Correlation { dilute: ViscosityDilute::CollisionIntegral { c: 2.1357e-08, a: &[0.234018, -0.476136, -0.015269], t: &[0.0, 1.0, 3.0], molar_mass: 0.07811184, epsilon_over_k: 412.0, sigma_eta: 5.4e-10 }, initial: Some(ViscosityInitial::RainwaterFriend { b: &[-19.572881, 219.73999, -1015.3226, 2471.01251, -3375.1717, 2491.6597, -787.26086, 14.085455, -0.34664158], t: &[0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -2.5, -5.5], epsilon_over_k: 412.0, sigma_eta: 5.4e-10 }), higher_order: ViscosityHigherOrder::Benzene { molar_mass: 0.07811180000000001 } }),
    conductivity: Some(ConductivityModel::Correlation { dilute: ConductivityDilute::RatioPolynomials { t_reducing: 562.02, a: &[0.101404, -0.52144, 0.868266], n: &[0.0, 1.0, 2.0], b: &[1.0, 9.714, 1.467], m: &[0.0, 1.0, 2.0] }, residual: ConductivityResidual::Polynomial { t_reducing: 562.02, rhomass_reducing: 304.7922436, b: &[0.0282489, -0.0119268, -0.0773415, 0.0833389, 0.0714001, -0.0898176, -0.0236798, 0.0363025, 0.00300875, -0.00490052], t: &[0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0], d: &[1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 5.0] }, critical: Some(CriticalConductivity::SimplifiedOlchowySengers { r0: 1.02, gamma: 1.239, big_gamma: 0.0569, zeta0: 2.16e-10, qd: 1612903225.0, t_ref: -1.0 }) }),
};

