// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's CarbonDioxide.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `CarbonDioxide` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};
use crate::transport::{
    FluidTransport, ViscosityModel, ViscosityDilute, ViscosityHigherOrder, ViscosityInitial,
    ConductivityModel, ConductivityDilute, ConductivityResidual, CriticalConductivity,
};

/// CarbonDioxide Helmholtz equation of state (from CoolProp).
pub static CARBONDIOXIDE: FluidEos = FluidEos {
    name: "CarbonDioxide",
    molar_mass: 0.0440098,
    gas_constant: 8.31451,
    t_reducing: 304.1282,
    rho_reducing: 10624.9063,
    t_critical: 304.1282,
    rho_critical: 10624.9063,
    p_critical: 7377300.0,
    t_triple: 216.592,
    t_max: 2000.0,
    p_max: 800000000.0,
    acentric: 0.22394,
    residual: &[
        ResidualTerm::Power {
            n: &[
                0.388568232032,
                2.93854759427,
                -5.5867188535,
                -0.767531995925,
                0.317290055804,
                0.548033158978,
                0.122794112203,
                2.16589615432,
                1.58417351097,
                -0.231327054055,
                0.0581169164314,
                -0.553691372054,
                0.489466159094,
                -0.0242757398435,
                0.0624947905017,
                -0.121758602252,
                -0.370556852701,
                -0.0167758797004,
                -0.11960736638,
                -0.0456193625088,
                0.0356127892703,
                -0.00744277271321,
                -0.00173957049024,
                -0.0218101212895,
                0.0243321665592,
                -0.0374401334235,
                0.143387157569,
                -0.134919690833,
                -0.0231512250535,
                0.0123631254929,
                0.00210583219729,
                -0.000339585190264,
                0.00559936517716,
                -0.000303351180556,
            ],
            t: &[
                0.0, 0.75, 1.0, 2.0, 0.75, 2.0, 0.75, 1.5, 1.5, 2.5, 0.0, 1.5, 2.0, 0.0, 1.0, 2.0,
                3.0, 6.0, 3.0, 6.0, 8.0, 6.0, 0.0, 7.0, 12.0, 16.0, 22.0, 24.0, 16.0, 24.0, 8.0,
                2.0, 28.0, 14.0,
            ],
            d: &[
                1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 1.0, 2.0, 4.0, 5.0, 5.0, 5.0, 6.0, 6.0, 6.0,
                1.0, 1.0, 4.0, 4.0, 4.0, 7.0, 8.0, 2.0, 3.0, 3.0, 5.0, 5.0, 6.0, 7.0, 8.0, 10.0,
                4.0, 8.0,
            ],
            l: &[
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0,
                5.0, 6.0,
            ],
        },
        ResidualTerm::Gaussian {
            n: &[
                -213.654886883,
                26641.5691493,
                -24027.2122046,
                -283.41603424,
                212.472844002,
            ],
            t: &[1.0, 0.0, 1.0, 3.0, 3.0],
            d: &[2.0, 2.0, 2.0, 3.0, 3.0],
            eta: &[25.0, 25.0, 25.0, 15.0, 20.0],
            epsilon: &[1.0, 1.0, 1.0, 1.0, 1.0],
            beta: &[325.0, 300.0, 300.0, 275.0, 275.0],
            gamma: &[1.16, 1.19, 1.19, 1.25, 1.22],
        },
        ResidualTerm::NonAnalytic {
            n: &[-0.666422765408, 0.726086323499, 0.0550686686128],
            a: &[3.5, 3.5, 3.0],
            b: &[0.875, 0.925, 0.875],
            beta: &[0.3, 0.3, 0.3],
            big_a: &[0.7, 0.7, 0.7],
            big_b: &[0.3, 0.3, 1.0],
            big_c: &[10.0, 10.0, 12.5],
            big_d: &[275.0, 275.0, 275.0],
        },
    ],
    ideal: &[
        IdealTerm::Lead {
            a1: 8.37304456,
            a2: -3.70454304,
        },
        IdealTerm::LogTau { a: 2.5 },
        IdealTerm::PlanckEinstein {
            n: &[1.99427042, 0.62105248, 0.41195293, 1.04028922, 0.08327678],
            t: &[3.15163, 6.1119, 6.77708, 11.32384, 27.08792],
        },
        IdealTerm::EnthalpyEntropyOffset {
            a1: -14.4979156224319,
            a2: 8.82013935801453,
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static CARBONDIOXIDE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 7377300.0,
        t_r: 304.1282,
        using_tau_r: true,
        exponential: true,
        n: &[
            -5.867399337600407,
            -7.10969550015274,
            11.022781986239263,
            4.8260764050219995,
            -6.240803382557819,
            -6.7009642572439,
        ],
        t: &[0.983, 1.322, 1.488, 2.807, 3.571, 1.941],
    },
    rho_l: SatAncillary {
        reducing_value: 10624.906299999999,
        t_r: 304.1282,
        using_tau_r: false,
        exponential: false,
        n: &[
            0.861951794789174,
            5.535795098719573,
            -21.766373764605415,
            20.01416999278327,
            -2.2218647220786862,
            888.2387848519858,
        ],
        t: &[0.264, 0.672, 0.986, 1.092, 1.714, 9.902],
    },
    rho_v: SatAncillary {
        reducing_value: 10624.906299999999,
        t_r: 304.1282,
        using_tau_r: true,
        exponential: true,
        n: &[
            -1.1635587811569494,
            -3.64216164754343,
            2.7773118075713237,
            -3.2573848494624533,
            -1.9739104682508852,
            -16.057319994659142,
        ],
        t: &[0.306, 0.569, 0.677, 0.891, 3.206, 6.093],
    },
};

/// Transport models (CoolProp): dynamic viscosity and/or thermal
/// conductivity (dilute + residual + near-critical; see `crate::transport`).
pub static CARBONDIOXIDE_TRANSPORT: FluidTransport = FluidTransport {
    viscosity: Some(ViscosityModel::Correlation {
        dilute: ViscosityDilute::CO2LaeseckeJPCRD2017,
        initial: Some(ViscosityInitial::RainwaterFriend {
            b: &[
                -19.572881,
                219.73999,
                -1015.3226,
                2471.0125,
                -3375.1717,
                2491.6597,
                -787.26086,
                14.085455,
                -0.34664158,
            ],
            t: &[0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -2.5, -5.5],
            epsilon_over_k: 200.76,
            sigma_eta: 3.78421e-10,
        }),
        higher_order: ViscosityHigherOrder::CO2LaeseckeJPCRD2017 {
            ttriple: 216.592,
            gas_constant: 8.31451,
            molar_mass: 0.0440098,
        },
    }),
    conductivity: Some(ConductivityModel::Correlation {
        dilute: ConductivityDilute::CO2HuberJPCRD2016,
        residual: ConductivityResidual::Polynomial {
            t_reducing: 304.1282,
            rhomass_reducing: 467.6,
            b: &[
                0.0100128,
                0.0560488,
                -0.081162,
                0.0624337,
                -0.0206336,
                0.00253248,
                0.00430829,
                -0.0358563,
                0.067148,
                -0.0522855,
                0.0174571,
                -0.00196414,
            ],
            t: &[
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0,
            ],
            d: &[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        },
        critical: Some(CriticalConductivity::SimplifiedOlchowySengers {
            r0: 1.02,
            gamma: 1.239,
            big_gamma: 0.052,
            zeta0: 1.5e-10,
            qd: 2500000000.0,
            t_ref: 456.19,
        }),
    }),
};
