// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's CycloPropane.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `CycloPropane` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// CycloPropane Helmholtz equation of state (from CoolProp).
pub static CYCLOPROPANE: FluidEos = FluidEos {
    name: "CycloPropane",
    molar_mass: 0.042081,
    gas_constant: 8.3143,
    t_reducing: 398.3,
    rho_reducing: 6142.9149,
    t_critical: 398.3,
    rho_critical: 6142.914900000001,
    p_critical: 5579700.0,
    t_triple: 145.7,
    t_max: 473.0,
    p_max: 28000000.0,
    acentric: 0.1305495663687517,
    residual: &[
    ResidualTerm::Power { n: &[-1.15634007067133, 2.52574627508968, -2.82266128097357, 0.283576801605235, -0.0842720496332253, 0.931088565988454, -1.0529683988751, 0.432021581602768, -0.251108864340636, 0.127725892482498, 0.0483622335785703, -0.0116474078333994, 0.00033400656553506, -1.37016097592368, 2.12444673007915, -0.578908942731662, 0.304945770506538, -0.184276165170077, -0.292111460404481, 1.37016097592368, -2.12444673007915, 0.578908942731662], t: &[0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 3.0, 4.0, 5.0, 3.0, 4.0, 5.0, 3.0, 4.0, 5.0], d: &[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::LogTau { a: -1.0 },
    IdealTerm::CP0PolyT { c: &[6.378038040672545, -0.04582023302189515, 0.0002558503477107775, -3.908517142596848e-07, 2.051746651955177e-10], t: &[0.0, 1.0, 2.0, 3.0, 4.0], tc: 398.3, t0: 298.15 },
    IdealTerm::EnthalpyEntropyOffset { a1: -10.9358280454636, a2: 8.75156673092286 },
    ],
};

