// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Cyclopentane.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Cyclopentane` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// Cyclopentane Helmholtz equation of state (from CoolProp).
pub static CYCLOPENTANE: FluidEos = FluidEos {
    name: "Cyclopentane",
    molar_mass: 0.07013290000000001,
    gas_constant: 8.314472,
    t_reducing: 511.72,
    rho_reducing: 3920.000000000001,
    t_critical: 511.72,
    rho_critical: 3920.000000000001,
    p_critical: 4582761.1858461285,
    t_triple: 179.7,
    t_max: 550.0,
    p_max: 250000000.0,
    acentric: 0.20192904575157278,
    residual: &[
    ResidualTerm::Power { n: &[0.0630928, 1.50365, -2.37099, -0.484886, 0.191843, -0.835582, -0.435929, 0.545607, -0.209741, -0.0387635], t: &[1.0, 0.29, 0.85, 1.185, 0.45, 2.28, 1.8, 1.5, 2.9, 0.93], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[0.677674, -0.137043, -0.0852862, -0.128085, -0.00389381], t: &[1.05, 4.0, 2.33, 1.5, 1.0], d: &[1.0, 1.0, 3.0, 3.0, 2.0], eta: &[0.86, 0.85, 0.86, 1.53, 5.13], epsilon: &[0.684, 0.7, 0.77, 0.625, 0.42], beta: &[0.63, 2.8, 0.5, 0.95, 0.23], gamma: &[1.22, 0.32, 0.22, 1.94, 1.21] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -0.3946233253, a2: 2.4918910143 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[1.34, 13.4, 17.4, 6.65], t: &[0.4494645509262878, 2.3059485656218244, 4.299226139294927, 10.161807238333463] },
    ],
};

