// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's DimethylCarbonate.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `DimethylCarbonate` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// DimethylCarbonate Helmholtz equation of state (from CoolProp).
pub static DIMETHYLCARBONATE: FluidEos = FluidEos {
    name: "DimethylCarbonate",
    molar_mass: 0.0900779,
    gas_constant: 8.314472,
    t_reducing: 557.0,
    rho_reducing: 4000.0,
    t_critical: 557.0,
    rho_critical: 4000.0,
    p_critical: 4908800.0,
    t_triple: 277.06,
    t_max: 600.0,
    p_max: 60000000.0,
    acentric: 0.346,
    residual: &[
    ResidualTerm::Power { n: &[0.00052683187, 1.353396, -2.649283, -0.2785412, 0.1742554, 0.031606252, 0.399866, 1.178144, -0.0235281, -1.015, -0.7880436, -0.12696], t: &[1.0, 0.227, 1.05, 1.06, 0.5, 0.78, 1.3, 1.347, 0.706, 2.0, 2.5, 4.262], d: &[5.0, 1.0, 1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 7.0, 1.0, 2.0, 3.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0] },
    ResidualTerm::Gaussian { n: &[1.2198, -0.4883, -0.0033293, -0.0035387, -0.51172, -0.16882], t: &[1.0, 2.124, 0.4, 3.5, 0.5, 2.7], d: &[1.0, 1.0, 2.0, 2.0, 3.0, 3.0], eta: &[0.9667, 1.5154, 1.0591, 1.6642, 12.4856, 0.9662], epsilon: &[0.6734, 0.9239, 0.8636, 1.0507, 0.8482, 0.7522], beta: &[1.24, 0.821, 15.45, 2.21, 437.0, 0.743], gamma: &[1.2827, 0.4317, 1.1217, 1.1871, 1.1243, 0.4203] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 4.9916462, a2: -0.1709449 },
    IdealTerm::LogTau { a: 8.28421 },
    IdealTerm::PlanckEinstein { n: &[1.48525, 0.822585, 16.2453, 1.15925], t: &[0.03770197486535009, 2.405745062836625, 3.001795332136445, 13.27648114901257] },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static DIMETHYLCARBONATE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 4908800.0, t_r: 557.0, using_tau_r: true, exponential: true, n: &[-2.597007649585314, -15.509376515573363, 12.767875905311987, -1.7459847599351825, -1.196780284722721, -3.425253357555481], t: &[0.945, 1.114, 1.224, 2.157, 2.469, 4.522] },
    rho_l: SatAncillary { reducing_value: 4000.0, t_r: 557.0, using_tau_r: false, exponential: false, n: &[0.8639422657944309, -1.688248771620619, 3.3308155638028083, 152.44139464976624, -173.70557844277656, 36624.29817631924], t: &[0.221, 0.307, 0.394, 5.545, 5.765, 19.705] },
    rho_v: SatAncillary { reducing_value: 4000.0, t_r: 557.0, using_tau_r: true, exponential: true, n: &[-1.8639798693880143, -12.434353793968175, 9.656910477455611, -8.552325635675663, 11.090574157797857, -495.7580019137995], t: &[0.318, 0.882, 0.995, 3.273, 5.755, 13.354] },
};

