// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's EthyleneOxide.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `EthyleneOxide` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// EthyleneOxide Helmholtz equation of state (from CoolProp).
pub static ETHYLENEOXIDE: FluidEos = FluidEos {
    name: "EthyleneOxide",
    molar_mass: 0.04405256,
    gas_constant: 8.3144621,
    t_reducing: 468.92,
    rho_reducing: 7170.0,
    t_critical: 468.92,
    rho_critical: 7170.0,
    p_critical: 7304686.159635853,
    t_triple: 160.65,
    t_max: 1000.0,
    p_max: 1000000000.0,
    acentric: 0.21019548904995822,
    residual: &[
    ResidualTerm::Power { n: &[0.0300676, 2.1629, -2.72041, -0.53931, 0.181051, -2.61292, -2.08004, 0.3169968, -1.6532, -0.01981719], t: &[1.0, 0.41, 0.79, 1.06, 0.58, 2.0, 2.2, 0.73, 2.4, 0.97], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[3.34387, -0.950671, -0.445528, -0.005409938, -0.0638824, -0.093912], t: &[1.87, 2.08, 2.8, 0.97, 3.15, 0.7], d: &[1.0, 1.0, 3.0, 3.0, 2.0, 1.0], eta: &[1.02, 1.55, 1.44, 14.0, 1.63, 1.9], epsilon: &[0.705, 0.821, 0.791, 1.08, 1.64, 1.51], beta: &[0.62, 1.11, 0.62, 368.0, 0.66, 1.87], gamma: &[0.847, 0.34, 0.265, 1.13, 0.36, 1.05] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -3.90644775, a2: 4.0000956 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[6.79, 4.53, 3.68], t: &[2.8363047001620743, 4.627655037106543, 9.532542864454491] },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static ETHYLENEOXIDE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 7305000.0, t_r: 468.92, using_tau_r: true, exponential: true, n: &[-7.002, 1.1835, -2.196, -1.394, -1.582, -382.3], t: &[1.0, 1.5, 3.3, 5.05, 17.0, 36.8] },
    rho_l: SatAncillary { reducing_value: 7170.0, t_r: 468.92, using_tau_r: false, exponential: false, n: &[2.3014, -0.08549, 2.055, -2.883, 1.686], t: &[0.382, 0.93, 1.48, 2.1, 2.95] },
    rho_v: SatAncillary { reducing_value: 7170.0, t_r: 468.92, using_tau_r: false, exponential: true, n: &[-3.0498, -7.1199, -23.067, -56.11, -127.8], t: &[0.414, 1.276, 3.63, 7.84, 16.9] },
};

