// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Fluorine.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Fluorine` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// Fluorine Helmholtz equation of state (from CoolProp).
pub static FLUORINE: FluidEos = FluidEos {
    name: "Fluorine",
    molar_mass: 0.03799681000000001,
    gas_constant: 8.31448,
    t_reducing: 144.414,
    rho_reducing: 15603.0,
    t_critical: 144.41400000000002,
    rho_critical: 15603.0,
    p_critical: 5172400.0,
    t_triple: 53.4811,
    t_max: 300.0,
    p_max: 20000000.0,
    acentric: 0.0449,
    residual: &[
        ResidualTerm::Power {
            n: &[
                1.51144749736,
                -2.98666288409,
                3.29644905098,
                -2.98458624201,
                -2.28688966459,
                -1.094921934,
                3.04775277572,
                0.115689564208,
                -1.16100171627,
                0.295656394476,
                0.0711482542928,
                -0.00171363832155,
                0.000665317955515,
            ],
            t: &[
                0.0, 0.5, 1.5, 2.0, 0.5, 1.0, 0.5, 2.0, 0.5, 1.0, 0.0, 0.5, 0.0,
            ],
            d: &[
                1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 8.0, 9.0,
            ],
            l: &[
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ],
        },
        ResidualTerm::Exponential {
            n: &[
                5.06026676251,
                -6.2926843544,
                6.17784808739,
                -1.55366191788,
                -2.87170687343,
                3.17214480494,
                -2.67969025215,
                2.71865479252,
                -1.07191065039,
                1.26597342291,
                -0.706244695489,
                0.268707888826,
                0.0527251190274,
                0.0544411481926,
                0.000228949994105,
                -5.479082643040001e-10,
                -0.096427322495,
                0.000368084486225,
            ],
            t: &[
                1.0, 3.0, 4.0, 5.0, 1.0, 4.0, 5.0, 1.0, 3.0, 5.0, 4.0, 4.0, 1.0, 1.0, 5.0, 30.0,
                20.0, 25.0,
            ],
            d: &[
                2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, 5.0, 6.0, 7.0, 8.0, 12.0, 4.0,
                6.0, 6.0,
            ],
            g: &[
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                1.078102576,
                2.156205153,
                3.234307729,
                3.234307729,
            ],
            l: &[
                2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
                2.0, 2.0,
            ],
        },
    ],
    ideal: &[
        IdealTerm::Power {
            n: &[
                3.0717001e-06,
                -5.2985762e-05,
                -16.372517,
                3.6884682e-05,
                4.3887271,
            ],
            t: &[-4.0, -3.0, 1.0, 2.0, 0.0],
        },
        IdealTerm::LogTau { a: 2.5011231 },
        IdealTerm::PlanckEinsteinGeneralized {
            n: &[1.012767],
            theta: &[-8.9057501],
            c: &[1.0],
            d: &[-1.0],
        },
        IdealTerm::Lead { a1: 0.0, a2: 0.0 },
        IdealTerm::EnthalpyEntropyOffset {
            a1: -7.97036812567026,
            a2: 19.8946542032696,
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static FLUORINE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 5172400.0,
        t_r: 144.414,
        using_tau_r: true,
        exponential: true,
        n: &[
            0.032041854896500264,
            -3.429417910548146,
            -2.362258815038421,
            -1.0111386038971053,
            -7008.9949851880765,
            9283.126473335162,
        ],
        t: &[0.056, 0.84, 1.353, 4.898, 19.085, 19.761],
    },
    rho_l: SatAncillary {
        reducing_value: 15603.0,
        t_r: 144.414,
        using_tau_r: false,
        exponential: false,
        n: &[
            -2.1267466372809594,
            4.293457721465353,
            1.136882153895534,
            -2.83890898830727,
            5360.59971312227,
            -6438.621729396981,
        ],
        t: &[0.329, 0.371, 3.558, 5.918, 18.297, 18.795],
    },
    rho_v: SatAncillary {
        reducing_value: 15603.0,
        t_r: 144.414,
        using_tau_r: true,
        exponential: true,
        n: &[
            0.209065655538512,
            -5.869062694341366,
            3.6459137875713985,
            -2.7710544718284704,
            -3.720164757549319,
            23.40559168423325,
        ],
        t: &[0.135, 0.425, 0.545, 1.021, 5.359, 14.59],
    },
};
