// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's IsoButane.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `IsoButane` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};
use crate::transport::{FluidTransport, ViscosityModel, ViscosityDilute, ViscosityHigherOrder, ViscosityInitial, ConductivityModel, ConductivityDilute, ConductivityResidual};

/// IsoButane Helmholtz equation of state (from CoolProp).
pub static ISOBUTANE: FluidEos = FluidEos {
    name: "IsoButane",
    molar_mass: 0.0581222,
    gas_constant: 8.314472,
    t_reducing: 407.81,
    rho_reducing: 3879.756788283995,
    t_critical: 407.817,
    rho_critical: 3879.756788283995,
    p_critical: 3629000.0,
    t_triple: 113.73,
    t_max: 575.0,
    p_max: 35000000.0,
    acentric: 0.183531783208,
    residual: &[
    ResidualTerm::Power { n: &[2.0686820727966, -3.6400098615204, 0.51968754427244, 0.17745845870123, -0.12361807851599, 0.045145314010528, 0.03047647996598, 0.75508387706302, -0.85885381015629, 0.036324009830684, -0.01954879945055, -0.004445239290496, 0.004641076366646, -0.071444097992825, -0.080765060030713, 0.15560460945053, 0.0020318752160332, -0.10624883571689, 0.039807690546305, 0.016371431292386, 0.00053212200682628, -0.0078681561156387, -0.0030981191888963], t: &[0.5, 1.0, 1.5, 0.0, 0.5, 0.5, 0.75, 2.0, 2.5, 2.5, 1.5, 1.0, 1.5, 4.0, 7.0, 3.0, 7.0, 3.0, 1.0, 6.0, 0.0, 6.0, 13.0], d: &[1.0, 1.0, 1.0, 2.0, 3.0, 4.0, 4.0, 1.0, 1.0, 2.0, 7.0, 8.0, 8.0, 1.0, 2.0, 3.0, 3.0, 4.0, 5.0, 5.0, 10.0, 2.0, 6.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0] },
    ResidualTerm::Gaussian { n: &[-0.042276036810382, -0.0053001044558079], t: &[2.0, 0.0], d: &[1.0, 2.0], eta: &[10.0, 10.0], epsilon: &[0.85, 1.0], beta: &[150.0, 200.0], gamma: &[1.16, 1.13] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 11.60865546, a2: -5.29450411 },
    IdealTerm::LogTau { a: 3.05956619 },
    IdealTerm::PlanckEinstein { n: &[4.94641014, 4.09475197, 15.6632824, 9.73918122], t: &[0.951277902, 2.387895885, 4.346904269, 10.36885864] },
    IdealTerm::EnthalpyEntropyOffset { a1: -17.6081648486994, a2: 10.3134499204439 },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static ISOBUTANE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 3629000.0, t_r: 407.817, using_tau_r: true, exponential: true, n: &[-48.02915589537987, 43.34653680580028, -1.4421317283854331, -3.1322275225078413, 5.203481182010376, -6.173022897817098], t: &[1.082, 1.108, 1.463, 4.045, 13.157, 14.042] },
    rho_l: SatAncillary { reducing_value: 3879.756788283995, t_r: 407.817, using_tau_r: false, exponential: false, n: &[2.0418147224188545, 0.4363922893974425, 1.915261424521202, -2.1807762762122045, 1.068664850362356, -6.816247938174933], t: &[0.356, 0.824, 3.142, 3.696, 6.863, 18.441] },
    rho_v: SatAncillary { reducing_value: 3879.756788283995, t_r: 407.817, using_tau_r: true, exponential: true, n: &[-2.8656855559386294, 0.7330458189287201, -4.254613288675131, 2.9956235180226516, -5.671641417558254, 0.14361022568133902], t: &[0.37, 0.502, 1.021, 2.003, 3.403, 10.717] },
};

/// Transport models (CoolProp): dynamic viscosity and/or thermal
/// conductivity (critical enhancement omitted; see `crate::transport`).
pub static ISOBUTANE_TRANSPORT: FluidTransport = FluidTransport {
    viscosity: Some(ViscosityModel { dilute: ViscosityDilute::CollisionIntegral { c: 2.1357e-08, a: &[0.53583008, -0.4562963, 0.049911282], t: &[0.0, 1.0, 2.0], molar_mass: 0.0581222, epsilon_over_k: 307.55, sigma_eta: 4.6445e-10 }, initial: Some(ViscosityInitial::RainwaterFriend { b: &[-19.572881, 219.73999, -1015.3226, 2471.01251, -3375.1717, 2491.6597, -787.26086, 14.085455, -0.34664158], t: &[0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -2.5, -5.5], epsilon_over_k: 307.55, sigma_eta: 4.6445e-10 }), higher_order: ViscosityHigherOrder::ModifiedBatschinskiHildebrand { t_reduce: 407.817, rhomolar_reduce: 3860.0, a: &[0.000103511763411, -0.000312670896234, 0.000145253750239, -0.000210649894193, 0.000386269696509, -0.000214963015527, 0.00011258036092, -0.000223242033154, 0.000119114788598, -1.819097459e-05, 3.60438957232e-05, -2.1396018405e-05], d1: &[2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, 5.0, 5.0, 5.0], t1: &[0.0, 1.0, 2.0, 0.0, 1.0, 2.0, 0.0, 1.0, 2.0, 0.0, 1.0, 2.0], gamma: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], l: &[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], f: &[0.0019403760699], d2: &[1.0], t2: &[0.0], g: &[2.33859774637, 2.352551508384381], h: &[0.0, -0.5], p: &[1.0], q: &[0.0] } }),
    conductivity: Some(ConductivityModel { dilute: ConductivityDilute::RatioPolynomials { t_reducing: 407.85, a: &[-0.00237901, 0.0106601, 0.0215811], n: &[0.0, 1.0, 2.0], b: &[1.0], m: &[0.0] }, residual: ConductivityResidual::Polynomial { t_reducing: 407.85, rhomass_reducing: 224.4, b: &[-0.0411789, 0.146805, -0.11919, 0.0410226, -0.00488704, 0.0476346, -0.128445, 0.107565, -0.0385968, 0.00520901], t: &[0.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, -1.0, -1.0, -1.0], d: &[1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 2.0, 3.0, 4.0, 5.0] } }),
};

