// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's MethylLinolenate.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `MethylLinolenate` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// MethylLinolenate Helmholtz equation of state (from CoolProp).
pub static METHYLLINOLENATE: FluidEos = FluidEos {
    name: "MethylLinolenate",
    molar_mass: 0.29245618,
    gas_constant: 8.314472,
    t_reducing: 772.0,
    rho_reducing: 847.3000000000001,
    t_critical: 772.0,
    rho_critical: 847.3000000000002,
    p_critical: 1369000.0,
    t_triple: 218.65,
    t_max: 1000.0,
    p_max: 50000000.0,
    acentric: 1.142605258673496,
    residual: &[
    ResidualTerm::Power { n: &[0.04070829, 2.412375, -3.756194, -0.1526466, 0.04682918, -1.470958, -0.76455, 1.908964, -1.629366, -0.01242073], t: &[1.0, 0.15, 1.24, 1.6, 1.28, 2.9, 3.15, 2.16, 2.8, 1.4], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[2.180707, -0.7537264, -0.4347781], t: &[2.5, 3.0, 3.1], d: &[1.0, 1.0, 3.0], eta: &[1.1, 1.6, 1.1], epsilon: &[0.79, 0.9, 0.76], beta: &[0.9, 0.65, 0.75], gamma: &[1.14, 0.65, 0.77] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -1.0, a2: 0.0 },
    IdealTerm::LogTau { a: -1.0 },
    IdealTerm::CP0PolyT { c: &[9.572622290387171], t: &[0.214648], tc: 772.0, t0: 298.0 },
    IdealTerm::PlanckEinstein { n: &[34.92452677692582, 9.794043446174333, 57.11499178781286], t: &[1.571554404145078, 0.7496787564766839, 3.626670984455958] },
    IdealTerm::EnthalpyEntropyOffset { a1: 49.2444711864376, a2: -21.5426591230667 },
    ],
};

