// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's MethylLinoleate.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `MethylLinoleate` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// MethylLinoleate Helmholtz equation of state (from CoolProp).
pub static METHYLLINOLEATE: FluidEos = FluidEos {
    name: "MethylLinoleate",
    molar_mass: 0.29447206,
    gas_constant: 8.314472,
    t_reducing: 799.0,
    rho_reducing: 808.4,
    t_critical: 799.0,
    rho_critical: 808.4000000000001,
    p_critical: 1341000.0,
    t_triple: 238.1,
    t_max: 1000.0,
    p_max: 50000000.0,
    acentric: 0.8054063870556485,
    residual: &[
    ResidualTerm::Power { n: &[0.03183187, 1.927286, -3.685053, 0.08449312, -0.9766643, -0.4323178, 2.00047, -1.75203, -0.01726895], t: &[1.0, 0.2, 1.2, 1.0, 2.2, 2.5, 1.8, 1.92, 1.47], d: &[4.0, 1.0, 1.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[2.116515, -0.7884271, -0.3811699], t: &[1.7, 2.3, 2.1], d: &[1.0, 1.0, 3.0], eta: &[1.1, 1.6, 1.1], epsilon: &[0.79, 0.9, 0.76], beta: &[0.9, 0.65, 0.75], gamma: &[1.14, 0.65, 0.77] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -1.0, a2: 0.0 },
    IdealTerm::LogTau { a: -1.0 },
    IdealTerm::CP0PolyT { c: &[22.97031008102499], t: &[0.020213], tc: 799.0, t0: 298.0 },
    IdealTerm::PlanckEinstein { n: &[52.60358084073167, 34.54482738049993, 38.72236264672008], t: &[3.81991239048811, 0.9344568210262828, 2.032953692115144] },
    IdealTerm::EnthalpyEntropyOffset { a1: 56.2531140679551, a2: -23.9733038177064 },
    ],
};

