// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's MM.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `MM` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// MM Helmholtz equation of state (from CoolProp).
pub static MM: FluidEos = FluidEos {
    name: "MM",
    molar_mass: 0.16237752,
    gas_constant: 8.3144621,
    t_reducing: 518.7,
    rho_reducing: 1653.0,
    t_critical: 518.75,
    rho_critical: 1589.825,
    p_critical: 1939000.0,
    t_triple: 204.93,
    t_max: 673.0,
    p_max: 30000000.0,
    acentric: 0.418,
    residual: &[
    ResidualTerm::Power { n: &[0.05063651, 8.604724, -9.179684, -1.146325, 0.4878559, -2.434088, -1.621326, 0.6239872, -2.306057, -0.05555096], t: &[1.0, 0.346, 0.46, 1.01, 0.59, 2.6, 3.33, 0.75, 2.95, 0.93], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[9.385015, -2.493508, -3.308032, -0.1885803, -0.09883865, 0.111109, 0.1061928, -0.01452454], t: &[1.33, 1.68, 1.7, 3.08, 5.41, 1.4, 1.1, 5.3], d: &[1.0, 1.0, 3.0, 3.0, 1.0, 2.0, 3.0, 1.0], eta: &[1.0334, 1.544, 1.113, 1.113, 1.11, 7.2, 1.45, 4.73], epsilon: &[0.8927, 0.5957, 0.559, 1.056, 1.3, 0.106, 0.181, 0.525], beta: &[0.4707, 0.32, 0.404, 0.517, 0.432, 7.2, 1.2, 35.8], gamma: &[1.7754, 0.692, 1.242, 0.421, 0.406, 0.163, 0.795, 0.88] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[19.74, 29.58, 18.59, 4.87], t: &[6.940427993, 2.699055331, 0.038557933, 12.14574899] },
    IdealTerm::EnthalpyEntropyOffset { a1: 72.1107541562, a2: -10.4314993483 },
    ],
};

