// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's n-Decane.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `n-Decane` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// n-Decane Helmholtz equation of state (from CoolProp).
pub static N_DECANE: FluidEos = FluidEos {
    name: "n-Decane",
    molar_mass: 0.14228168,
    gas_constant: 8.314472,
    t_reducing: 617.7,
    rho_reducing: 1640.0,
    t_critical: 617.7,
    rho_critical: 1640.0000000000002,
    p_critical: 2103000.0,
    t_triple: 243.5,
    t_max: 675.0,
    p_max: 800000000.0,
    acentric: 0.4884,
    residual: &[
    ResidualTerm::Power { n: &[1.0461, -2.4807, 0.74372, -0.52579, 0.15315, 0.00032865, 0.84178, 0.055424, -0.73555, -0.18507, -0.020775, 0.012335], t: &[0.25, 1.125, 1.5, 1.375, 0.25, 0.875, 0.625, 1.75, 3.625, 3.625, 14.5, 12.0], d: &[1.0, 1.0, 1.0, 2.0, 3.0, 7.0, 2.0, 5.0, 1.0, 4.0, 3.0, 4.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 13.9361966549, a2: -10.5265128286 },
    IdealTerm::LogTau { a: 18.109 },
    IdealTerm::PlanckEinstein { n: &[25.685, 28.233, 12.417, 10.035], t: &[1.931358264529707, 3.46446495062328, 7.710862878419944, 17.58458798769629] },
    ],
};

