// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's n-Perfluorobutane.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `n-Perfluorobutane` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// n-Perfluorobutane Helmholtz equation of state (from CoolProp).
pub static N_PERFLUOROBUTANE: FluidEos = FluidEos {
    name: "n-Perfluorobutane",
    molar_mass: 0.238027,
    gas_constant: 8.314462618,
    t_reducing: 386.326,
    rho_reducing: 2637.0,
    t_critical: 386.326,
    rho_critical: 2637.0,
    p_critical: 2322400.0,
    t_triple: 144.0,
    t_max: 450.0,
    p_max: 10000000.0,
    acentric: 0.372,
    residual: &[
        ResidualTerm::Power {
            n: &[
                0.025377604,
                0.97089776,
                -0.76128126,
                -1.2517125,
                0.28005904,
                -1.7144149,
                -0.64918553,
                1.1662335,
                -0.35934725,
            ],
            t: &[1.0, 0.135, 1.0, 1.0, 0.42, 1.62, 2.35, 1.01, 2.65],
            d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0],
            l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0],
        },
        ResidualTerm::Gaussian {
            n: &[1.4986537, -0.60326234, -0.11389713, -0.2553212, -0.1017598],
            t: &[0.75, 1.28, 1.5, 1.0, 1.9],
            d: &[1.0, 1.0, 3.0, 2.0, 2.0],
            eta: &[1.431, 1.803, 1.608, 1.837, 1.846],
            epsilon: &[0.781, 0.723, 0.842, 0.652, 1.139],
            beta: &[1.544, 1.366, 0.876, 1.117, 1.29],
            gamma: &[1.265, 1.156, 0.916, 0.927, 0.926],
        },
    ],
    ideal: &[
        IdealTerm::Lead {
            a1: 7.00619051416,
            a2: -4.93953188697,
        },
        IdealTerm::LogTau { a: 13.0 },
        IdealTerm::PlanckEinstein {
            n: &[2.164, 15.64],
            t: &[0.9525633791150478, 2.0966748290304045],
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static N_PERFLUOROBUTANE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 2322400.0,
        t_r: 386.326,
        using_tau_r: true,
        exponential: true,
        n: &[-8.2957, 4.5997, -4.4355, -5.0941, -4.1863],
        t: &[1.0, 1.5, 1.9, 4.3, 15.1],
    },
    rho_l: SatAncillary {
        reducing_value: 2637.0,
        t_r: 386.326,
        using_tau_r: false,
        exponential: false,
        n: &[7.2166, -18.074, 32.084, -30.238, 12.446],
        t: &[0.507, 0.824, 1.15, 1.5, 1.9],
    },
    rho_v: SatAncillary {
        reducing_value: 2637.0,
        t_r: 386.326,
        using_tau_r: false,
        exponential: true,
        n: &[-6.2029, 7.0601, -11.424, -24.16, -67.136, -182.16],
        t: &[0.496, 0.82, 1.17, 3.3, 6.8, 15.0],
    },
};
