// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Neon.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Neon` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// Neon Helmholtz equation of state (from CoolProp).
pub static NEON: FluidEos = FluidEos {
    name: "Neon",
    molar_mass: 0.020179,
    gas_constant: 8.3144598,
    t_reducing: 44.4,
    rho_reducing: 24100.0,
    t_critical: 44.4,
    rho_critical: 24100.0,
    p_critical: 2661630.8085948555,
    t_triple: 24.5561,
    t_max: 725.0,
    p_max: 1000000000.0,
    acentric: -0.03549258024442481,
    residual: &[
    ResidualTerm::Power { n: &[0.031522418, 3.7716418, -4.27399448, -0.756466758, 0.066679921, -0.356928434, -0.053124761, 0.9407234, -0.969302374, 0.461243234, 0.008184422], t: &[1.0, 0.431, 0.592, 1.105, 0.49, 2.3, 3.18, 1.36, 2.0, 0.5, 1.12], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 4.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0] },
    ResidualTerm::Gaussian { n: &[7.84771604, 6.39604094, -1.27480579, -5.51887999, -8.76652276, -0.351732709], t: &[0.41, 0.64, 0.579, 0.6, 0.52, 0.655], d: &[1.0, 1.0, 3.0, 2.0, 1.0, 2.0], eta: &[0.76, 2.126, 2.168, 2.033, 0.743, 4.38], epsilon: &[0.5775, 0.9137, 0.7895, 0.6229, 0.4992, 0.869], beta: &[0.537, 0.765, 0.883, 0.751, 0.531, 11.4], gamma: &[1.997, 1.782, 1.663, 1.837, 1.953, 1.658] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -3.0384719151147275, a2: 3.253690479855404 },
    IdealTerm::LogTau { a: 1.5 },
    ],
};

