// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's p-Xylene.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `p-Xylene` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// p-Xylene Helmholtz equation of state (from CoolProp).
pub static P_XYLENE: FluidEos = FluidEos {
    name: "p-Xylene",
    molar_mass: 0.106165,
    gas_constant: 8.314472,
    t_reducing: 616.168,
    rho_reducing: 2693.92,
    t_critical: 616.168,
    rho_critical: 2693.92,
    p_critical: 3531500.0,
    t_triple: 286.4,
    t_max: 700.0,
    p_max: 200000000.0,
    acentric: 0.324,
    residual: &[
    ResidualTerm::Power { n: &[0.0010786811, -0.103161822, 0.0421544125, 1.47865376, -2.4266, -0.46575193, 0.190290995, -1.06376565, -0.209934069, 1.25159879, -0.951328356, -0.0269980032], t: &[1.0, 0.83, 0.83, 0.281, 0.932, 1.1, 0.443, 2.62, 2.5, 1.2, 3.0, 0.778], d: &[5.0, 1.0, 4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[1.3710318, -0.494160616, -0.0724317468, -3.69464746], t: &[1.13, 4.5, 2.2, 2.0], d: &[1.0, 1.0, 3.0, 3.0], eta: &[1.179, 1.065, 1.764, 13.675], epsilon: &[0.54944, 0.7234, 0.4926, 0.8459], beta: &[2.445, 1.483, 4.971, 413.0], gamma: &[1.267, 0.4242, 0.864, 1.1465] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 5.9815241, a2: -0.52477835 },
    IdealTerm::LogTau { a: 4.2430504 },
    IdealTerm::PlanckEinstein { n: &[5.2291378, 19.549862, 16.656178, 5.9390291], t: &[0.6718946780748107, 2.038405110294595, 4.299152179275782, 10.84282208748263] },
    ],
};

