// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's Propyne.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `Propyne` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// Propyne Helmholtz equation of state (from CoolProp).
pub static PROPYNE: FluidEos = FluidEos {
    name: "Propyne",
    molar_mass: 0.04006000000000001,
    gas_constant: 8.3143,
    t_reducing: 402.38,
    rho_reducing: 6113.33,
    t_critical: 402.38,
    rho_critical: 6113.33,
    p_critical: 5626000.0,
    t_triple: 170.5,
    t_max: 474.0,
    p_max: 31800000.0,
    acentric: 0.204,
    residual: &[
        ResidualTerm::Power {
            n: &[
                -0.986950667682466,
                4.59528109357232,
                -8.86063623531859,
                5.56346955560542,
                -1.57450028544218,
                -0.15906875357343,
                0.235738270184042,
                0.440755494598713,
                0.196126150614333,
                -0.367759650330219,
                0.00792931851007852,
                0.00247509085735293,
                0.00832903610194452,
                1.02590136933231,
                -2.20786016506394,
                1.07889905203761,
            ],
            t: &[
                0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 3.0, 4.0, 5.0,
            ],
            d: &[
                1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 0.0, 0.0, 0.0,
            ],
            l: &[
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            ],
        },
        ResidualTerm::Exponential {
            n: &[
                -3.821884669859,
                8.30345065618981,
                -4.4832307260286,
                -1.02590136933231,
                2.20786016506394,
                -1.07889905203761,
            ],
            t: &[3.0, 4.0, 5.0, 3.0, 4.0, 5.0],
            d: &[2.0, 2.0, 2.0, 0.0, 0.0, 0.0],
            g: &[
                1.65533788, 1.65533788, 1.65533788, 1.65533788, 1.65533788, 1.65533788,
            ],
            l: &[2.0, 2.0, 2.0, 2.0, 2.0, 2.0],
        },
    ],
    ideal: &[
        IdealTerm::Lead { a1: 0.0, a2: 0.0 },
        IdealTerm::LogTau { a: -1.0 },
        IdealTerm::CP0PolyT {
            c: &[
                1.649840044261093,
                0.02333952849909193,
                -1.673911795340558e-05,
                6.980952359188388e-09,
                -1.29200161168108e-12,
            ],
            t: &[0.0, 1.0, 2.0, 3.0, 4.0],
            tc: 402.38,
            t0: 298.15,
        },
        IdealTerm::EnthalpyEntropyOffset {
            a1: -11.004154248087,
            a2: 8.92674898200796,
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static PROPYNE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 5626000.0,
        t_r: 402.38,
        using_tau_r: true,
        exponential: true,
        n: &[
            0.0025352410381648404,
            -0.03566614580246839,
            -6.474512126273843,
            0.4178712360656155,
            -1.9479103016021955,
            -342.07305237113997,
        ],
        t: &[0.243, 0.628, 0.992, 1.949, 5.259, 11.136],
    },
    rho_l: SatAncillary {
        reducing_value: 6113.33,
        t_r: 402.38,
        using_tau_r: false,
        exponential: false,
        n: &[
            0.676908949567043,
            42.124365852994195,
            -52.6498660929799,
            148.86365466555566,
            -17709.824791659536,
            71543.36247766066,
        ],
        t: &[0.175, 1.172, 1.358, 3.662, 7.586, 9.174],
    },
    rho_v: SatAncillary {
        reducing_value: 6113.33,
        t_r: 402.38,
        using_tau_r: true,
        exponential: true,
        n: &[
            -5.066155131330643,
            1779.1130020151943,
            -1782.2051460501207,
            4.756104080644848,
            -2.3713377912727562,
            59.371736976095974,
        ],
        t: &[0.192, 0.32, 0.321, 0.498, 1.309, 7.491],
    },
};
