// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R113.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R113` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R113 Helmholtz equation of state (from CoolProp).
pub static R113: FluidEos = FluidEos {
    name: "R113",
    molar_mass: 0.187375,
    gas_constant: 8.314471,
    t_reducing: 487.21,
    rho_reducing: 2988.659106070714,
    t_critical: 487.21000000000004,
    rho_critical: 2988.6591060707137,
    p_critical: 3392200.0,
    t_triple: 236.93,
    t_max: 525.0,
    p_max: 200000000.0,
    acentric: 0.252535,
    residual: &[
    ResidualTerm::Power { n: &[0.8432092286, -2.019185967, 0.2920612996, 0.05323107661, 0.003214971931, 4.667858574e-05, -1.227522799e-06, 0.8167288718, -1.340790803, 0.4065752705, -0.1534754634, -0.02414435149, -0.02113056197, -0.03565436205, 0.001364654968, -0.01251838755, -0.001385761351, 0.0007206335486], t: &[0.5, 1.5, 1.5, -0.5, 2.0, 0.0, 3.0, -0.5, 0.0, 2.0, 1.5, 6.0, 2.0, 10.0, 6.0, 18.0, 15.0, 33.0], d: &[1.0, 1.0, 2.0, 3.0, 4.0, 8.0, 8.0, 3.0, 3.0, 3.0, 5.0, 1.0, 2.0, 2.0, 9.0, 3.0, 7.0, 8.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 13.1479282, a2: -5.4053715 },
    IdealTerm::LogTau { a: 2.9999966 },
    IdealTerm::PlanckEinstein { n: &[12.4464495, 2.72181845, 0.692712415, 3.32248298], t: &[1.04971737, 3.29788641, 8.62650812, 3.29670446] },
    IdealTerm::EnthalpyEntropyOffset { a1: -35.0036997726949, a2: 17.3478156256033 },
    ],
};

