// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R1132a.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R1132a` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R1132a Helmholtz equation of state (from CoolProp).
pub static R1132A: FluidEos = FluidEos {
    name: "R1132a",
    molar_mass: 0.0640340864,
    gas_constant: 8.314462618,
    t_reducing: 302.62,
    rho_reducing: 6510.0,
    t_critical: 302.62,
    rho_critical: 6510.0,
    p_critical: 4460494.408005374,
    t_triple: 111.0,
    t_max: 400.0,
    p_max: 30000000.0,
    acentric: 0.17702441908795863,
    residual: &[
    ResidualTerm::Power { n: &[0.0313181, 0.7213967, 0.1902012, 0.0562612, -0.46220008385, -0.81782202222], t: &[1.0, 0.143, 0.336, 0.13, 1.0, 1.06], d: &[4.0, 1.0, 2.0, 3.0, 1.0, 2.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
    ResidualTerm::Exponential { n: &[-0.7436092, -0.26903, -0.0883704, -0.0486345, -0.0173098], t: &[1.29, 0.95, 5.738, 3.74, 3.92], d: &[1.0, 1.0, 1.0, 2.0, 3.0], g: &[1.147, 0.9776, 0.6937, 0.389, 0.373], l: &[1.0, 2.0, 3.0, 3.0, 3.0] },
    ResidualTerm::Gaussian { n: &[-0.212, -0.01, -0.03, -0.3435674], t: &[1.17, 1.2, 1.1, 1.45], d: &[1.0, 2.0, 1.0, 1.0], eta: &[0.53, 0.3, 0.552, 1.154], epsilon: &[0.99, 0.6, 0.2, -0.3], beta: &[0.0, 0.0, 0.0, 2.27], gamma: &[1.0, 1.0, 1.0, 1.35] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -7.144967936410219, a2: 5.594245679502968 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[2.38, 9.45], t: &[2.1479082677945938, 5.287158813032846] },
    ],
};

