// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R1132(E).json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R1132(E)` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R1132(E) Helmholtz equation of state (from CoolProp).
pub static R1132_E_: FluidEos = FluidEos {
    name: "R1132(E)",
    molar_mass: 0.064035,
    gas_constant: 8.314462618,
    t_reducing: 348.82,
    rho_reducing: 6793.0,
    t_critical: 348.82,
    rho_critical: 6793.0,
    p_critical: 5173700.0,
    t_triple: 240.0,
    t_max: 400.0,
    p_max: 6500000.0,
    acentric: 0.245,
    residual: &[
    ResidualTerm::Power { n: &[0.033144696, 1.8996205, -2.19051728813, -0.8165909562367, 0.22857476, -1.650708, -1.4409077, 0.60536471, -0.66134087, -0.016787895], t: &[1.0, 0.32, 0.71, 1.2, 0.7, 2.09, 2.24, 1.17, 2.2, 0.823], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[0.31476822, -0.31991607, 2.2172762, -0.42786753, -0.41335541, 0.13023087, -0.30592804], t: &[3.14, 4.0, 1.25, 1.476, 1.5, 0.73, 1.535], d: &[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], eta: &[34.4, 34.28, 1.303, 1.855, 1.29, 1.17, 2.165], epsilon: &[0.9637, 0.9636, 0.8535, 1.15, 1.302, 1.54, 0.786], beta: &[1017.0, 1009.0, 1.011, 1.05, 1.33, 1.61, 0.8], gamma: &[1.0617, 1.062, 1.327, 1.05, 1.157, 1.183, 1.2] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -8.596223247566009, a2: 6.440533955251798 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[4.896, 7.111], t: &[2.0927699099822257, 6.4761194885614355] },
    ],
};

