// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R1130(E).json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R1130(E)` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// R1130(E) Helmholtz equation of state (from CoolProp).
pub static R1130_E_: FluidEos = FluidEos {
    name: "R1130(E)",
    molar_mass: 0.09694328,
    gas_constant: 8.314462618,
    t_reducing: 515.69,
    rho_reducing: 4540.0,
    t_critical: 515.69,
    rho_critical: 4540.0,
    p_critical: 5255460.0,
    t_triple: 223.31,
    t_max: 525.0,
    p_max: 30000000.0,
    acentric: 0.194,
    residual: &[
    ResidualTerm::Power { n: &[0.0256, 0.9, 0.054, 0.153, -0.49787364754, -0.99000024872], t: &[1.0, 0.188, 0.2496, 0.458, 0.77, 1.0385], d: &[4.0, 1.0, 2.0, 3.0, 1.0, 2.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
    ResidualTerm::Exponential { n: &[-0.318, -0.973, -0.098, -0.034, -0.0971], t: &[0.9, 1.21, 4.7, 6.61575, 2.257], d: &[1.0, 1.0, 1.0, 2.0, 3.0], g: &[2.43, 1.236548, 0.722, 1.483, 0.2255], l: &[1.0, 2.0, 3.0, 3.0, 3.0] },
    ResidualTerm::Gaussian { n: &[-0.26, -0.135, -0.21, -0.197], t: &[3.2664, 3.59, 1.2, 1.42], d: &[1.0, 2.0, 1.0, 1.0], eta: &[5.10245, 4.572, 4.63, 1.785], epsilon: &[-0.31662, 0.065, -0.28568, 0.99], beta: &[0.0, 0.0, 0.0, 0.0], gamma: &[1.0, 1.0, 1.0, 1.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -14.91185845478433, a2: 8.646546650620836 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[2.697, 6.264, 3.041], t: &[0.7116678624755182, 2.4161802633365004, 7.814772440807461] },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static R1130_E__ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 5255460.0, t_r: 515.69, using_tau_r: true, exponential: true, n: &[-7.2526, 3.8005, -7.7286, 10.953, -9.7064], t: &[1.0, 1.5, 2.12, 2.84, 3.58] },
    rho_l: SatAncillary { reducing_value: 4540.0, t_r: 515.69, using_tau_r: false, exponential: false, n: &[4.577, -6.1201, 7.6048, -4.7251, 1.6728, 1.8053], t: &[0.47, 0.83, 1.23, 1.69, 2.27, 9.8] },
    rho_v: SatAncillary { reducing_value: 4540.0, t_r: 515.69, using_tau_r: false, exponential: true, n: &[-0.063124, -10.541, 23.782, -56.858, 82.754, -76.847, -70.617], t: &[0.05, 0.64, 1.13, 1.74, 2.57, 3.25, 8.66] },
};

