// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R114.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R114` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R114 Helmholtz equation of state (from CoolProp).
pub static R114: FluidEos = FluidEos {
    name: "R114",
    molar_mass: 0.170921,
    gas_constant: 8.31451,
    t_reducing: 418.83,
    rho_reducing: 3393.2,
    t_critical: 418.83,
    rho_critical: 3393.2000000000007,
    p_critical: 3257000.0,
    t_triple: 180.63,
    t_max: 507.0,
    p_max: 21000000.0,
    acentric: 0.2523,
    residual: &[
    ResidualTerm::Power { n: &[1.07938940032879, -1.99243731009857, -0.155135220175231, -0.121465858429101, -0.0165038674558161, -0.186916017480622, 0.308074956770949, 0.115861545567346, 0.027635877981389, 0.108043424159349, 0.0460684822539207, -0.174822007470687, 0.0317531741331376, -0.340776521025164, 0.323001398918284, -0.0424950543505197], t: &[0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 3.0, 4.0, 5.0], d: &[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 0.0, 0.0, 0.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
    ResidualTerm::Exponential { n: &[-1.66940287525002, 4.08693538568874, -2.4173923391137, 0.340776521025164, -0.323001398918284, 0.0424950543505197], t: &[3.0, 4.0, 5.0, 3.0, 4.0, 5.0], d: &[2.0, 2.0, 2.0, 0.0, 0.0, 0.0], g: &[1.21104, 1.21104, 1.21104, 1.21104, 1.21104, 1.21104], l: &[2.0, 2.0, 2.0, 2.0, 2.0, 2.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::LogTau { a: -1.0 },
    IdealTerm::CP0PolyT { c: &[2.007414931364566, 0.06662223065231744, -0.0001211907268430731, 1.385112968303604e-07, -7.290244178478347e-11], t: &[0.0, 1.0, 2.0, 3.0, 4.0], tc: 418.83, t0: 298.15 },
    IdealTerm::EnthalpyEntropyOffset { a1: -28.2691959611666, a2: 17.4464013989786 },
    ],
};

