// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R116.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R116` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R116 Helmholtz equation of state (from CoolProp).
pub static R116: FluidEos = FluidEos {
    name: "R116",
    molar_mass: 0.13801182,
    gas_constant: 8.314472,
    t_reducing: 293.03,
    rho_reducing: 4444.0,
    t_critical: 293.03000000000003,
    rho_critical: 4444.0,
    p_critical: 3048000.0,
    t_triple: 173.1,
    t_max: 425.0,
    p_max: 50000000.0,
    acentric: 0.2566,
    residual: &[
    ResidualTerm::Power { n: &[1.1632, -2.8123, 0.77202, -0.14331, 0.10227, 0.00024629, 0.30893, -0.028499, -0.30343, -0.068793, -0.027218, 0.010665], t: &[0.25, 1.125, 1.5, 1.375, 0.25, 0.875, 0.625, 1.75, 3.625, 3.625, 14.5, 12.0], d: &[1.0, 1.0, 1.0, 2.0, 3.0, 7.0, 2.0, 5.0, 1.0, 4.0, 3.0, 4.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -10.7088650331, a2: 8.9148979056 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[2.4818, 7.0622, 7.9951], t: &[0.6483977749718459, 2.122649558065727, 5.016551206361124] },
    ],
};

