// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R1243zf.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R1243zf` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// R1243zf Helmholtz equation of state (from CoolProp).
pub static R1243ZF: FluidEos = FluidEos {
    name: "R1243zf",
    molar_mass: 0.09605113,
    gas_constant: 8.314462618,
    t_reducing: 376.93,
    rho_reducing: 4300.0,
    t_critical: 376.93,
    rho_critical: 4300.0,
    p_critical: 3513700.0,
    t_triple: 122.35,
    t_max: 430.0,
    p_max: 35000000.0,
    acentric: 0.2595,
    residual: &[
        ResidualTerm::Power {
            n: &[
                0.02626021,
                0.701348,
                -0.6180002748076,
                0.1916400159007,
                0.0762,
                -0.795,
            ],
            t: &[1.0, 0.12425, 1.0096, 0.271875, 0.405, 1.07288],
            d: &[4.0, 1.0, 1.0, 2.0, 3.0, 2.0],
            l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        },
        ResidualTerm::Exponential {
            n: &[-0.8537, -0.3531, -0.07971, -0.05411, -0.0424],
            t: &[1.45525, 2.105, 6.07, 5.794375, 4.094],
            d: &[1.0, 1.0, 1.0, 2.0, 3.0],
            g: &[1.0, 1.0, 1.0, 0.66, 0.33],
            l: &[1.0, 2.0, 3.0, 3.0, 3.0],
        },
        ResidualTerm::Gaussian {
            n: &[-0.06774, -0.01032, -0.1184, -0.1135],
            t: &[1.029, 1.65, 1.62, 1.653125],
            d: &[1.0, 2.0, 1.0, 1.0],
            eta: &[0.78, 2.796, 1.643, 3.03],
            epsilon: &[1.09375, 1.0392, -0.3076, -0.426],
            beta: &[0.0, 0.0, 1.86, 2.03],
            gamma: &[1.0, 1.0, 0.80625, 1.16],
        },
    ],
    ideal: &[
        IdealTerm::Lead {
            a1: -12.2722866918,
            a2: 8.2858157407,
        },
        IdealTerm::LogTau { a: 3.0 },
        IdealTerm::PlanckEinstein {
            n: &[13.285, 7.67],
            t: &[2.328283766216539, 9.451357015891544],
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static R1243ZF_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 3513700.0,
        t_r: 376.93,
        using_tau_r: true,
        exponential: true,
        n: &[-7.2325, 1.3165, -0.8189, -3.5606, -3.4861],
        t: &[1.0, 1.5, 2.32, 4.07, 15.4],
    },
    rho_l: SatAncillary {
        reducing_value: 4300.0,
        t_r: 376.93,
        using_tau_r: false,
        exponential: false,
        n: &[1.2627, 2.6023, -2.4034, 1.637, 0.29192],
        t: &[0.258, 0.82, 1.43, 2.11, 8.4],
    },
    rho_v: SatAncillary {
        reducing_value: 4300.0,
        t_r: 376.93,
        using_tau_r: false,
        exponential: true,
        n: &[-1.6776, -6.5573, -14.195, -33.488, -49.802, -127.65],
        t: &[0.28, 0.96, 2.78, 5.38, 9.36, 16.6],
    },
};
