// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R13I1.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R13I1` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R13I1 Helmholtz equation of state (from CoolProp).
pub static R13I1: FluidEos = FluidEos {
    name: "R13I1",
    molar_mass: 0.1959104,
    gas_constant: 8.3144621,
    t_reducing: 396.44,
    rho_reducing: 4430.6,
    t_critical: 396.44,
    rho_critical: 4430.6,
    p_critical: 3952566.071718672,
    t_triple: 120.0,
    t_max: 420.0,
    p_max: 50000000.0,
    acentric: 0.17618111777018552,
    residual: &[
    ResidualTerm::Power { n: &[1.12191, -3.08087, 1.11307, -0.184885, 0.110971, 0.000325, 0.333357, -0.0288288, -0.371554, -0.0997985, -0.0333205, 0.0207882], t: &[0.25, 1.125, 1.5, 1.375, 0.25, 0.875, 0.625, 1.75, 3.625, 3.625, 14.5, 12.0], d: &[1.0, 1.0, 1.0, 2.0, 3.0, 7.0, 2.0, 5.0, 1.0, 4.0, 3.0, 4.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[6.2641], t: &[1.7505801634547473] },
    IdealTerm::EnthalpyEntropyOffset { a1: -24.691504134838297, a2: 14.217528781905427 },
    ],
};

