// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R21.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R21` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R21 Helmholtz equation of state (from CoolProp).
pub static R21: FluidEos = FluidEos {
    name: "R21",
    molar_mass: 0.1029227,
    gas_constant: 8.31451,
    t_reducing: 451.48,
    rho_reducing: 5110.765599999999,
    t_critical: 451.48,
    rho_critical: 5110.765599999999,
    p_critical: 5181200.0,
    t_triple: 142.8,
    t_max: 473.0,
    p_max: 138000000.0,
    acentric: 0.2061,
    residual: &[
    ResidualTerm::Power { n: &[0.50467662375195, -0.732431416212257, -0.868403860880684, 0.146234705622829, -0.280576335158724, 0.864743657302055, -2.70767234069002, 3.30476391081085, -0.210878239585469, 0.449531450327333, 0.120779813434928, -0.277297954448155, 0.030544129220629, -44.3864848810647, 9.26505601085111, -0.551709104525115], t: &[0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 3.0, 4.0, 5.0], d: &[1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 0.0, 0.0, 0.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
    ResidualTerm::Exponential { n: &[1.21128809697908, 0.167119476809363, -0.0504876793555323, 44.3864848810647, -9.26505601085111, 0.551709104525115], t: &[3.0, 4.0, 5.0, 3.0, 4.0, 5.0], d: &[2.0, 2.0, 2.0, 0.0, 0.0, 0.0], g: &[0.07470252, 0.07470252, 0.07470252, 0.07470252, 0.07470252, 0.07470252], l: &[2.0, 2.0, 2.0, 2.0, 2.0, 2.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 0.0, a2: 0.0 },
    IdealTerm::LogTau { a: -1.0 },
    IdealTerm::CP0PolyT { c: &[2.941888561986215, 0.01573866857206258, 4.012367529660798e-06, -3.085298103142579e-08, 2.125677686617732e-11], t: &[0.0, 1.0, 2.0, 3.0, 4.0], tc: 451.48, t0: 298.15 },
    IdealTerm::EnthalpyEntropyOffset { a1: -19.5492777147267, a2: 12.6393155496886 },
    ],
};

