// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R236EA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R236EA` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R236EA Helmholtz equation of state (from CoolProp).
pub static R236EA: FluidEos = FluidEos {
    name: "R236EA",
    molar_mass: 0.1520384,
    gas_constant: 8.314472,
    t_reducing: 412.44,
    rho_reducing: 3716.16644216198,
    t_critical: 412.44,
    rho_critical: 3716.16644216198,
    p_critical: 3415700.7078681667,
    t_triple: 170.0,
    t_max: 412.0,
    p_max: 6000000.0,
    acentric: 0.3682166321629954,
    residual: &[
    ResidualTerm::Power { n: &[0.051074, 2.5584, -2.918, -0.71485, 0.15534, -1.5894, -0.784, 0.85767, -0.67235, -0.017953], t: &[1.0, 0.264, 0.5638, 1.306, 0.2062, 2.207, 2.283, 1.373, 2.33, 0.6376], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
    ResidualTerm::Gaussian { n: &[1.3165, -0.42023, -0.28053, -1.4134, -6.2617e-06], t: &[1.08, 1.67, 3.502, 4.357, 0.6945], d: &[1.0, 1.0, 3.0, 3.0, 2.0], eta: &[1.019, 1.341, 1.034, 5.264, 24.44], epsilon: &[0.7119, 0.9102, 0.678, 0.7091, 1.727], beta: &[1.3, 2.479, 1.068, 79.85, 49.06], gamma: &[1.13, 0.6691, 0.465, 1.28, 0.8781] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -14.121424135, a2: 10.2355589225 },
    IdealTerm::LogTau { a: 2.762 },
    IdealTerm::PlanckEinstein { n: &[0.7762, 10.41, 12.18, 3.332], t: &[0.3491416933372127, 0.93346911065852, 3.724178062263602, 17.26554165454369] },
    ],
};

