// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R236FA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R236FA` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// R236FA Helmholtz equation of state (from CoolProp).
pub static R236FA: FluidEos = FluidEos {
    name: "R236FA",
    molar_mass: 0.1520384,
    gas_constant: 8.314472,
    t_reducing: 398.07,
    rho_reducing: 3626.0,
    t_critical: 398.07,
    rho_critical: 3626.0,
    p_critical: 3200000.0,
    t_triple: 179.6,
    t_max: 400.0,
    p_max: 70000000.0,
    acentric: 0.3769117976336991,
    residual: &[
        ResidualTerm::Power {
            n: &[
                0.04453255,
                1.777017,
                -2.230519,
                -0.6708606,
                0.1587907,
                -1.425119,
                -0.6461628,
                0.8469985,
                -0.5635356,
                -0.01535611,
            ],
            t: &[
                1.07, 0.222, 0.66, 1.33, 0.227, 2.33, 1.94, 1.53, 2.65, 0.722,
            ],
            d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0],
            l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0],
        },
        ResidualTerm::Gaussian {
            n: &[1.156362, -0.407031, -0.2172753, -1.007176, -6.902909e-05],
            t: &[1.11, 2.31, 3.68, 4.23, 0.614],
            d: &[1.0, 1.0, 3.0, 3.0, 2.0],
            eta: &[1.02, 1.336, 1.055, 5.84, 16.2],
            epsilon: &[0.712, 0.91, 0.677, 0.718, 1.64],
            beta: &[1.42, 2.31, 0.89, 80.0, 108.0],
            gamma: &[1.13, 0.67, 0.46, 1.28, 1.2],
        },
    ],
    ideal: &[
        IdealTerm::Lead {
            a1: -17.5983849,
            a2: 8.87150449,
        },
        IdealTerm::LogTau { a: 9.175 },
        IdealTerm::PlanckEinstein {
            n: &[9.8782, 18.236, 49.934],
            t: &[2.416660386364208, 6.014017635089306, 13.03288366367724],
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static R236FA_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 3200000.0,
        t_r: 398.07,
        using_tau_r: true,
        exponential: true,
        n: &[
            -0.0049249850273236865,
            0.012816148225752128,
            -6.97674339296593,
            0.34709652116366274,
            -3.3890300356223824,
            -3.905418212194194,
        ],
        t: &[0.017, 0.253, 0.971, 2.069, 3.12, 5.366],
    },
    rho_l: SatAncillary {
        reducing_value: 3626.0,
        t_r: 398.07,
        using_tau_r: false,
        exponential: false,
        n: &[
            -0.6129462210275856,
            2.32975618477472,
            0.44026610528146576,
            0.18569408128843393,
            0.41600763700797233,
            0.3257761223988926,
        ],
        t: &[0.177, 0.276, 0.561, 0.741, 1.15, 3.764],
    },
    rho_v: SatAncillary {
        reducing_value: 3626.0,
        t_r: 398.07,
        using_tau_r: true,
        exponential: true,
        n: &[
            -3.799841638369613,
            -7.207160418715132,
            47.73949958715277,
            -59.040754885379386,
            33.03413077298916,
            -27.228555278145553,
        ],
        t: &[0.436, 1.661, 2.91, 3.307, 5.447, 6.392],
    },
};
