// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R32.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R32` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// R32 Helmholtz equation of state (from CoolProp).
pub static R32: FluidEos = FluidEos {
    name: "R32",
    molar_mass: 0.052024,
    gas_constant: 8.314471,
    t_reducing: 351.255,
    rho_reducing: 8150.084599999999,
    t_critical: 351.255,
    rho_critical: 8150.084599999999,
    p_critical: 5782000.0,
    t_triple: 136.34,
    t_max: 435.0,
    p_max: 70000000.0,
    acentric: 0.2769,
    residual: &[
    ResidualTerm::Power { n: &[1.046634, -0.5451165, -0.002448595, -0.04877002, 0.03520158, 0.00162275, 2.377225e-05, 0.029149, 0.003386203, -0.004202444, 0.0004782025, -0.005504323, -0.02418396, 0.4209034, -0.4616537, -1.200513, -2.59155, -1.400145, 0.8263017], t: &[0.25, 1.0, -0.25, -1.0, 2.0, 2.0, 0.75, 0.25, 18.0, 26.0, -1.0, 25.0, 1.75, 4.0, 5.0, 1.0, 1.5, 1.0, 0.5], d: &[1.0, 2.0, 5.0, 1.0, 1.0, 3.0, 8.0, 4.0, 4.0, 4.0, 8.0, 3.0, 5.0, 1.0, 1.0, 3.0, 1.0, 2.0, 3.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 3.0, 1.0, 4.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -8.258096, a2: 6.353098 },
    IdealTerm::LogTau { a: 3.004486 },
    IdealTerm::PlanckEinstein { n: &[1.160761, 2.645151, 5.794987, 1.129475], t: &[2.2718538, 11.914421, 5.1415638, 32.768217] },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static R32_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 5782000.0, t_r: 351.255, using_tau_r: true, exponential: true, n: &[0.019194334673139708, -6.794802163795212, 9.276391392786632, -12.327153852761946, 28.46579606476374, -28.570870718190093], t: &[0.531, 0.979, 2.203, 2.382, 3.421, 3.558] },
    rho_l: SatAncillary { reducing_value: 8150.084599999999, t_r: 351.255, using_tau_r: false, exponential: false, n: &[3.0283368557227064, -13.30754793568124, 53.97035773548243, -41.10515088784585, 0.6410010855629815, -18.757652443918627], t: &[0.358, 0.676, 0.831, 0.88, 2.592, 16.556] },
    rho_v: SatAncillary { reducing_value: 8150.084599999999, t_r: 351.255, using_tau_r: true, exponential: true, n: &[-0.06522522852577171, -3.3577643698607456, -2.746299718061842, -64.77289013657663, 511.3349286855849, -1525.315265366156], t: &[0.069, 0.425, 1.18, 8.115, 12.06, 16.085] },
};

