// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R41.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R41` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};

/// R41 Helmholtz equation of state (from CoolProp).
pub static R41: FluidEos = FluidEos {
    name: "R41",
    molar_mass: 0.03403291999999999,
    gas_constant: 8.314472,
    t_reducing: 317.28,
    rho_reducing: 9300.0,
    t_critical: 317.28000000000003,
    rho_critical: 9300.0,
    p_critical: 5897000.0,
    t_triple: 129.82,
    t_max: 425.0,
    p_max: 70000000.0,
    acentric: 0.2004,
    residual: &[
    ResidualTerm::Power { n: &[0.85316, -2.6366, 0.69129, 0.054681, 0.00012796, -0.37093, 0.3392, -0.0017413, -0.095417, -0.078852, -0.030729, -0.011497], t: &[0.25, 1.25, 1.5, 0.25, 0.875, 2.375, 2.0, 2.125, 3.5, 6.5, 4.75, 12.5], d: &[1.0, 1.0, 1.0, 3.0, 7.0, 1.0, 2.0, 5.0, 1.0, 1.0, 4.0, 2.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: -4.867644116, a2: 4.2527951258 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::Power { n: &[-0.0268688568], t: &[-1.0] },
    IdealTerm::PlanckEinstein { n: &[5.6936, 2.9351], t: &[5.802445789208271, 13.33837619768028] },
    IdealTerm::EnthalpyEntropyOffset { a1: 0.00152259725820867, a2: -0.00354958910457479 },
    ],
};

