// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's R41.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `R41` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};

/// R41 Helmholtz equation of state (from CoolProp).
pub static R41: FluidEos = FluidEos {
    name: "R41",
    molar_mass: 0.03403291999999999,
    gas_constant: 8.314472,
    t_reducing: 317.28,
    rho_reducing: 9300.0,
    t_critical: 317.28000000000003,
    rho_critical: 9300.0,
    p_critical: 5897000.0,
    t_triple: 129.82,
    t_max: 425.0,
    p_max: 70000000.0,
    acentric: 0.2004,
    residual: &[ResidualTerm::Power {
        n: &[
            0.85316, -2.6366, 0.69129, 0.054681, 0.00012796, -0.37093, 0.3392, -0.0017413,
            -0.095417, -0.078852, -0.030729, -0.011497,
        ],
        t: &[
            0.25, 1.25, 1.5, 0.25, 0.875, 2.375, 2.0, 2.125, 3.5, 6.5, 4.75, 12.5,
        ],
        d: &[1.0, 1.0, 1.0, 3.0, 7.0, 1.0, 2.0, 5.0, 1.0, 1.0, 4.0, 2.0],
        l: &[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0],
    }],
    ideal: &[
        IdealTerm::Lead {
            a1: -4.867644116,
            a2: 4.2527951258,
        },
        IdealTerm::LogTau { a: 3.0 },
        IdealTerm::Power {
            n: &[-0.0268688568],
            t: &[-1.0],
        },
        IdealTerm::PlanckEinstein {
            n: &[5.6936, 2.9351],
            t: &[5.802445789208271, 13.33837619768028],
        },
        IdealTerm::EnthalpyEntropyOffset {
            a1: 0.00152259725820867,
            a2: -0.00354958910457479,
        },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static R41_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary {
        reducing_value: 5897000.0,
        t_r: 317.28,
        using_tau_r: true,
        exponential: true,
        n: &[
            0.039268780221147596,
            0.8889694467325728,
            -6.90749554283487,
            -2.0706202534383804,
            -0.8793688751729696,
            -73.19636369827167,
        ],
        t: &[0.321, 0.945, 0.945, 3.51, 6.214, 19.933],
    },
    rho_l: SatAncillary {
        reducing_value: 9300.0,
        t_r: 317.28,
        using_tau_r: false,
        exponential: false,
        n: &[
            2.597706385655882,
            -22.310070383317598,
            139.51691751158674,
            -170.32067961108578,
            59.24775396461156,
            -887.3638436688191,
        ],
        t: &[0.408, 2.476, 3.081, 3.478, 4.372, 18.469],
    },
    rho_v: SatAncillary {
        reducing_value: 9300.0,
        t_r: 317.28,
        using_tau_r: true,
        exponential: true,
        n: &[
            -4.548581015916281,
            2.6834555626875343,
            -3.8161276706535663,
            -15.526729016233224,
            21.743182012896813,
            -33.19736982637592,
        ],
        t: &[0.471, 0.914, 1.181, 6.61, 8.764, 19.551],
    },
};
