// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_fluid.py from CoolProp's SulfurHexafluoride.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.
//! CoolProp `SulfurHexafluoride` Helmholtz EOS, as hardcoded `const` data.
#![allow(clippy::approx_constant)]

use crate::eos::{FluidEos, IdealTerm, ResidualTerm};
use crate::ancillaries::{FluidAncillaries, SatAncillary};
use crate::transport::{FluidTransport, ViscosityModel, ViscosityDilute, ViscosityHigherOrder, ConductivityModel, ConductivityDilute, ConductivityResidual, CriticalConductivity};

/// SulfurHexafluoride Helmholtz equation of state (from CoolProp).
pub static SULFURHEXAFLUORIDE: FluidEos = FluidEos {
    name: "SulfurHexafluoride",
    molar_mass: 0.1460554192,
    gas_constant: 8.314472,
    t_reducing: 318.7232,
    rho_reducing: 5082.317411198119,
    t_critical: 318.7232,
    rho_critical: 5082.317411198119,
    p_critical: 3754983.0,
    t_triple: 223.555,
    t_max: 625.0,
    p_max: 150000000.0,
    acentric: 0.21,
    residual: &[
    ResidualTerm::Power { n: &[0.54958259132835, -0.87905033269396, -0.84656969731452, 0.27692381593529, -4.9864958372345, 4.8879127058055, 0.036917081634281, 0.00037030130305087, 0.039389132911585, 0.00042477413690006, -0.02415001386389, 0.059447650642255, -0.38302880142267, 0.32606800951983, -0.029955940562031, -0.086579186671173, 4.1600684707562, -4.1398128855814, -0.55842159922714, 0.56531382776891, 0.0082612463415545, -0.01020099533808], t: &[0.125, 1.25, 1.875, 0.125, 1.5, 1.625, 1.5, 5.625, 0.625, 0.25, 6.0, 0.25, 4.75, 5.375, 5.875, 2.0, 5.875, 6.0, 5.625, 5.75, 0.0, 0.5], d: &[1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 4.0, 6.0, 1.0, 2.0, 2.0, 2.0, 3.0, 6.0, 2.0, 2.0, 4.0, 4.0, 2.0, 2.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0] },
    ResidualTerm::Gaussian { n: &[-0.021662523861406, 0.034650943893908, -0.028694281385812, 0.0084007238998053, -0.26969359922498, 9.0415215646344, -3.7233103557977, -2752.4670823704, 5771.1861697319, -3023.4003119748, 2225277.843536, -2305606.5559032, 6391885.2944475, -6079209.1415592], t: &[4.0, 1.0, 3.0, 2.0, 4.0, 3.0, 4.0, 1.0, 2.0, 3.0, 3.0, 4.0, 3.0, 4.0], d: &[1.0, 3.0, 4.0, 1.0, 1.0, 4.0, 3.0, 4.0, 4.0, 4.0, 1.0, 1.0, 3.0, 3.0], eta: &[10.0, 10.0, 10.0, 10.0, 11.0, 25.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0], epsilon: &[0.85, 0.85, 0.85, 0.85, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], beta: &[150.0, 150.0, 150.0, 150.0, 225.0, 300.0, 350.0, 350.0, 350.0, 350.0, 400.0, 400.0, 400.0, 400.0], gamma: &[1.13, 1.13, 1.13, 1.16, 1.19, 1.19, 1.16, 1.16, 1.16, 1.16, 1.22, 1.22, 1.22, 1.22] },
    ],
    ideal: &[
    IdealTerm::Lead { a1: 11.638611086, a2: -6.392241811 },
    IdealTerm::LogTau { a: 3.0 },
    IdealTerm::PlanckEinstein { n: &[3.66118232, 7.87885103, 3.45981679], t: &[1.617282065, 2.747115139, 4.232907175] },
    IdealTerm::EnthalpyEntropyOffset { a1: -27.047571044927, a2: 17.2073865481014 },
    ],
};

/// Saturation ancillaries (CoolProp): fast p_sat/rho' /rho'' fits, used
/// as the VLE initial guess and for standalone saturation lookups.
pub static SULFURHEXAFLUORIDE_ANCILLARIES: FluidAncillaries = FluidAncillaries {
    p_sat: SatAncillary { reducing_value: 3754983.0, t_r: 318.7232, using_tau_r: true, exponential: true, n: &[-0.3409184825729817, -7.189246611969527, -4.574500860459857, -2.1124260160105846, -0.884461264916517, 5.474973854948071], t: &[0.888, 1.017, 1.742, 3.975, 4.849, 1.549] },
    rho_l: SatAncillary { reducing_value: 5082.317411198119, t_r: 318.7232, using_tau_r: false, exponential: false, n: &[-0.09723399675840705, 2.15858946914358, 1.7637219963539608, -1153.263728198288, 3460.272067774808, -16941.095002681574], t: &[0.162, 0.34, 1.704, 5.628, 6.422, 9.099] },
    rho_v: SatAncillary { reducing_value: 5082.317411198119, t_r: 318.7232, using_tau_r: true, exponential: true, n: &[-8.935879409973415, 7.030558315225393, -4.599609615155371, 1.6300884890508534, -2145.5926123421355, 7242407.029292246], t: &[0.452, 0.51, 1.021, 1.739, 8.69, 16.008] },
};

/// Transport models (CoolProp): dynamic viscosity and/or thermal
/// conductivity (dilute + residual + near-critical; see `crate::transport`).
pub static SULFURHEXAFLUORIDE_TRANSPORT: FluidTransport = FluidTransport {
    viscosity: Some(ViscosityModel::Correlation { dilute: ViscosityDilute::PowersOfT { a: &[0.000118561, -8.948633138369e-05, 2.3325614004395282e-05, -2.191287992665495e-06, 7.69887476029357e-08], t: &[0.0, 0.25, 0.5, 0.75, 1.0] }, initial: None, higher_order: ViscosityHigherOrder::FrictionTheory { t_reduce: 318.7232, c1: 1.0, c2: 1.0, ai: &[5.38783e-08, 1.63805e-09, -2.0816e-08], aa: &[-6.87811e-07, 8.22661e-07, -3.54867e-07], ar: &[1.72737e-07, -2.02448e-07, 1.95952e-07], aaa: &[9.99563e-11, -9.64167e-12, -7.54196e-12], arr: &[], adrdr: &[-8.98256e-11, -8.49428e-11, 0.0], aii: &[-8.53432e-09, 1.14404e-08, -5.65762e-09], arrr: &[0.0, 0.0, 2.2798e-14], aaaa: &[0.0, -5.69402e-14, 2.9219e-14], na: 1.0, nr: 1.0, naa: 3.0, nrr: 3.0, nii: 3.0, nrrr: 1.0, naaa: 1.0 } }),
    conductivity: Some(ConductivityModel::Correlation { dilute: ConductivityDilute::RatioPolynomials { t_reducing: 1.0, a: &[1461.86, -18.5394, 0.0777891, 2.41059e-05], n: &[0.0, 1.0, 2.0, 3.0], b: &[29661.7, 505.67, 1.0], m: &[0.0, 1.0, 2.0] }, residual: ConductivityResidual::Polynomial { t_reducing: 318.7232, rhomass_reducing: 742.297, b: &[-0.0283746, 0.0352768, 0.0207472, -0.0433053, -0.0055718, 0.0512084, 0.0053289, -0.0290262, -0.00161688, 0.00598438], t: &[0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0], d: &[1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 5.0] }, critical: Some(CriticalConductivity::SimplifiedOlchowySengers { r0: 1.01, gamma: 1.2415, big_gamma: 0.052, zeta0: 1.9e-10, qd: 2857000000.0, t_ref: -1.0 }) }),
};

