//! **V&V: this crate's elastic mean scattering cosine against OpenMC's, on the
//! same evaluation — the check that clears elastic scattering of the Godiva
//! leakage discrepancy.**
//!
//! # Why `⟨μ⟩`, and why against an external code
//!
//! Leakage from a bare assembly is governed by the transport cross section
//! `Σ_tr = Σ_t(1 − ⟨μ⟩)`, so `⟨μ⟩` is *the* number a leakage error lives in.
//! `outram-mc-libs` is `+250 ± 51 pcm` above OpenMC on Godiva and about 72 % of
//! that is leakage
//! (`verification_and_validation/openmc_godiva_cross_code/`), which makes the
//! elastic angular distribution — 85 % of all scattering — the first thing that
//! has to be cleared or convicted.
//!
//! `tests/elastic_anisotropy_vs_endf_mf4.rs` already checks the **sampler**
//! against this crate's own quadrature of the same table. Its own docs note the
//! limit of that: *"a check no comparison against an external library can make,
//! because both sides here come from one tape."* The converse gap is what this
//! test closes — both sides there come from **our** parse, so a misreading of
//! MF=4 would be invisible. Here the oracle is OpenMC's independent read of the
//! same evaluation.
//!
//! # Methodology
//!
//! U-235 (94 % of Godiva), ENDF/B-VIII.0, HIGH tier. Compare
//! [`Nuclide::elastic_mubar_cm`] against `⟨μ⟩` computed by OpenMC 0.15.3 from
//! ACE generated by NJOY2016 from the *same* tape.
//!
//! **The oracle is linearly interpolated between OpenMC's tabulated incident
//! energies, and that is the correct comparison, not a convenience.** OpenMC's
//! `AngleDistribution::sample` (`src/distribution_angle.cpp`) picks table `i` or
//! `i+1` with probability `r`, so the *expectation* of its sampled cosine is
//! `(1−r)·μ̄ᵢ + r·μ̄ᵢ₊₁` — exactly the linear interpolation this crate computes
//! directly. Comparing against the nearest tabulated point instead would show
//! spurious differences of ~4e-3 that are an artefact of the comparison.
//!
//! # Oracle provenance
//!
//! OpenMC 0.15.3 (commit `27e38e89`), reading `U235.h5` converted from
//! NJOY2016 `ac5adf5f` ACE built from `reference-data/endf/n-092_U_235-ENDF8.0.endf`.
//! `⟨μ⟩` per tabulated energy is the trapezoidal integral of `μ·p(μ)` over the
//! stored cosine grid, then linearly interpolated in incident energy. All 126
//! of that distribution's incident energies are **linear-linear**, which is why
//! trapezoidal quadrature is the right integral for both sides. Regenerate with
//! `verification_and_validation/openmc_godiva_cross_code/`.
//!
//! # Results (2026-09-15)
//!
//! | E (eV) | this crate | OpenMC | difference |
//! |---|---|---|---|
//! | 1.0e3 | +0.00123 | +0.00179 | −5.6e-4 |
//! | 1.0e5 | +0.13007 | +0.13007 | 0.0 |
//! | 1.0e6 | +0.49728 | +0.49722 | +6e-5 |
//! | 2.0e6 | +0.62270 | +0.62245 | +2.5e-4 |
//! | 5.0e6 | +0.85160 | +0.85135 | +2.5e-4 |
//!
//! Worst **5.6e-4**, at 1 keV where `⟨μ⟩ ≈ 0` and Godiva has negligible flux;
//! across the MeV range that carries the flux it is ≤ 2.5e-4.
//!
//! **Elastic scattering is therefore cleared.** The Godiva leakage discrepancy
//! is not here, which leaves the *inelastic* angular distributions this crate
//! does not sample at all — independently priced at +168/+181/+219 pcm by three
//! routes in the V&V study.
//!
//! A sampled cross-check is included: 200 000 draws from
//! [`Nuclide::sample_elastic_mu_cm`] at 2 MeV average **+0.62268** against the
//! analytic **+0.62270**, so the sampler reproduces the table it is given.
//!
//! # A latent gap found while doing this, and deliberately not fixed here
//!
//! This crate's cosine tables carry **no interpolation flag**: `EnergyAngular`
//! stores cosines/pdf/cdf and the sampler always applies the linear-linear
//! inverse CDF, where OpenMC's `Tabular::sample` branches on
//! `Interpolation::histogram` vs `lin_lin`. It is harmless on this data — all
//! 126 incident energies of U-235's elastic distribution are linear-linear — and
//! that is *why* this test passes. An evaluation using histogram angular data
//! would be mis-sampled silently. Filed rather than fixed, because fixing it
//! blind, with no evaluation here that exercises it, would be untested code.

use njoy_outram_park_fork::reference_data::reference_file_or_skip;
use outram_mc_libs::material::nuclide::Nuclide;

const TEMP_K: f64 = 293.6;

/// `(incident energy [eV], OpenMC ⟨μ⟩ in CM)` — see "Oracle provenance".
const OPENMC_MUBAR: &[(f64, f64)] = &[
    (1.0e3, 0.00179),
    (1.0e5, 0.13007),
    (1.0e6, 0.49722),
    (2.0e6, 0.62245),
    (5.0e6, 0.85135),
];

/// Absolute tolerance on `⟨μ⟩`. Loose enough for the oracle being quoted to
/// five decimals and for trapezoidal quadrature on two independently built
/// cosine grids; far tighter than any difference that could matter to leakage.
const MUBAR_TOL: f64 = 1.0e-3;

#[test]
fn elastic_mean_cosine_matches_openmc() {
    let Some(tape) = reference_file_or_skip(
        "endf",
        "n-092_U_235-ENDF8.0.endf",
        "U-235 evaluation (elastic mu-bar vs OpenMC)",
    ) else {
        return;
    };
    let nuc = Nuclide::from_endf_file(&tape, "U235", TEMP_K, 1.0e-3).expect("U-235 reconstructs");

    println!("{:>12} {:>12} {:>12} {:>12}", "E (eV)", "ours", "OpenMC", "diff");
    let mut worst = 0.0_f64;
    for &(e, theirs) in OPENMC_MUBAR {
        let ours = nuc.elastic_mubar_cm(e);
        let d = ours - theirs;
        worst = worst.max(d.abs());
        println!("{e:12.3e} {ours:+12.5} {theirs:+12.5} {d:+12.2e}");
        assert!(
            d.abs() <= MUBAR_TOL,
            "elastic <mu> at {e:.3e} eV is {ours:+.5} here against OpenMC's {theirs:+.5} \
             (difference {d:+.2e}, tolerance {MUBAR_TOL:.0e}).\n\
             <mu> sets Sigma_tr = Sigma_t(1 - <mu>) and therefore leakage, so a real \
             disagreement here would mean the MF=4 parse is wrong -- which would make the \
             Godiva leakage attribution in verification_and_validation/\
             openmc_godiva_cross_code/ wrong too. Do not widen this tolerance to make it pass."
        );
    }
    println!("  worst |difference| = {worst:.2e}");

    // The sampler must reproduce the table it is handed. This duplicates
    // tests/elastic_anisotropy_vs_endf_mf4.rs in spirit, kept here so this file
    // stands alone as "elastic is cleared": table right AND sampling right.
    let mut seed = 42u64;
    let (mut acc, mut n) = (0.0_f64, 0usize);
    for _ in 0..200_000 {
        if let Some(mu) = nuc.sample_elastic_mu_cm(2.0e6, &mut seed) {
            acc += mu;
            n += 1;
        }
    }
    assert!(n > 0, "the sampler returned no anisotropic cosines at 2 MeV");
    let sampled = acc / n as f64;
    let analytic = nuc.elastic_mubar_cm(2.0e6);
    println!("  sampled <mu> at 2 MeV over {n} draws = {sampled:+.5} (analytic {analytic:+.5})");
    assert!(
        (sampled - analytic).abs() < 5.0e-3,
        "sampled <mu> {sampled:+.5} does not reproduce the analytic {analytic:+.5}; the \
         inverse-CDF sampling disagrees with the table it draws from"
    );
}
