//! **V&V: this crate's discrete-inelastic mean scattering cosine against
//! OpenMC's, on the same evaluation — the check that the `op-tm9f` fix is right
//! for the right reason, not merely that `k` came out well.**
//!
//! # Why this test and not the eigenvalue
//!
//! Wiring in the ENDF MF=4 angular distributions for MT=51…90 moved Godiva from
//! `+214` to `+16 ± 11 pcm` against ICSBEP. **An eigenvalue landing on a
//! benchmark is weak evidence about the physics underneath**: two offsetting
//! errors land there too, and this crate's own record contains a case where a
//! physically *correct* fix moved `k` further from the experiment (the MT=91
//! Q-value cap, gh:#192, `+85 ± 26 pcm` away, kept because it was right).
//!
//! What makes the fix checkable is that `⟨μ⟩` is a **directly comparable
//! number**, independent of any transport run. Leakage from a bare assembly is
//! governed by `Σ_tr = Σ_t(1 − ⟨μ⟩)`, so if our `⟨μ⟩` per level matches an
//! independent code's read of the same tape, the parse, the linearisation and
//! the sampler are all right — whatever `k` does.
//!
//! This is the inelastic counterpart of `tests/elastic_mubar_vs_openmc.rs`,
//! which cleared elastic and thereby pointed at these levels in the first place.
//!
//! # Methodology
//!
//! U-238 and U-235, ENDF/B-VIII.0, HIGH tier. Compare
//! [`Nuclide::inelastic_mubar_cm`] per level against `⟨μ_cm⟩` computed by
//! OpenMC 0.15.3 from ACE generated by NJOY2016 from the **same tape**, at
//! 1, 2, 5 and 14 MeV — the band carrying Godiva's flux.
//!
//! Both sides integrate `μ·p(μ)` trapezoidally over their own linearised cosine
//! grid and interpolate linearly in incident energy. **Linear interpolation is
//! the correct comparison, not a convenience:** OpenMC's
//! `AngleDistribution::sample` picks table `i` or `i+1` with probability `r`, so
//! the expectation of its draw *is* the interpolation. Reading its nearest
//! tabulated energy instead produces spurious differences — a trap this study
//! hit three separate times.
//!
//! # Oracle provenance
//!
//! OpenMC 0.15.3 (commit `27e38e89`) reading ACE from NJOY2016 `ac5adf5f`, built
//! from `reference-data/endf/n-092_U_238.endf` and
//! `n-092_U_235-ENDF8.0.endf`. Regenerate with
//! `verification_and_validation/openmc_godiva_cross_code/` (`make_ace.sh`, then
//! the `inel_mu_oracle.py` recipe recorded in that README).
//!
//! # Results (2026-09-16)
//!
//! **Worst difference across all 32 compared points: `3.1e-3`**, at 14 MeV on
//! U-238 MT=53/54. Across the 1–5 MeV band that carries most of Godiva's
//! inelastic collisions it is `≤ 1.3e-3`.
//!
//! The differences are **random in sign**, which is the signature of two
//! independent linearisations of the same Legendre coefficients rather than of a
//! systematic misreading — this crate linearises `f(μ)` to a 5e-3 relative
//! tolerance and NJOY/OpenMC to its own, so exact agreement is not expected and
//! would in fact be suspicious.
//!
//! A structural agreement worth more than the numbers: **U-235's MT=51/52/54/55
//! are near-isotropic and its MT=53/56 are not**, and OpenMC's independent read
//! says the same. That asymmetry is a real property of the evaluation, and it is
//! the thing a naive parse would get wrong.
//!
//! # What this does NOT check
//!
//! - **The continuum.** MT=91's angular law lives in MF=6, not MF=4, and is
//!   still taken isotropic in the frame the evaluation names (`op-og56`).
//! - **The interpolation flag.** `EnergyAngular` carries none, so histogram
//!   angular data would be sampled as linear-linear and silently mis-drawn.
//!   Harmless on this data — these tables are all linear-linear, which is *why*
//!   this passes.
//! - **The secondary-energy law**, which is a separate residual (`op-os8x`).

use njoy_outram_park_fork::reference_data::reference_file_or_skip;
use outram_mc_libs::material::nuclide::Nuclide;

const TEMP_K: f64 = 293.6;

/// Incident energies the oracle was taken at \[eV\].
const ENERGIES: [f64; 4] = [1.0e6, 2.0e6, 5.0e6, 1.4e7];

/// Absolute tolerance on `⟨μ_cm⟩`.
///
/// Sized at roughly 1.6x the worst observed difference (3.1e-3), which is what
/// two independent linearisations of the same Legendre expansion produce. It is
/// **not** sized at what would matter to leakage — that would be far looser.
/// Do not widen it to make a failure pass: a real disagreement here means the
/// MF=4 parse is wrong, which would make the Godiva attribution wrong too.
const MUBAR_TOL: f64 = 5.0e-3;

/// `(MT, [⟨μ_cm⟩ at 1, 2, 5, 14 MeV])` from OpenMC's ACE — see "Oracle
/// provenance". U-238: every low-lying level is anisotropic.
const OPENMC_U238: &[(i32, [f64; 4])] = &[
    (51, [0.034410, 0.031102, 0.249644, 0.509507]),
    (52, [0.056749, 0.157696, 0.320046, 0.434335]),
    (53, [0.052780, 0.277476, 0.283667, 0.280864]),
    (54, [-0.009566, 0.116892, 0.160212, 0.135552]),
    (55, [-0.011621, 0.009524, 0.037492, -0.306607]),
    (56, [-0.003989, -0.002626, -0.122940, -0.432515]),
    (57, [0.004322, -0.109511, 0.026002, -0.013020]),
    (58, [-0.001896, -0.001300, 0.032319, -0.145003]),
];

/// U-235, where MT=53 and MT=56 are anisotropic and the rest of the low-lying
/// levels are essentially isotropic. The near-zero rows are the point of
/// including this nuclide: a parse that invented anisotropy would fail them.
const OPENMC_U235: &[(i32, [f64; 4])] = &[
    (51, [0.000105, 0.000345, 0.0, 0.0]),
    (52, [0.0, 0.000004, 0.0, 0.0]),
    (53, [0.115871, 0.056248, 0.247471, 0.497655]),
    (54, [-0.000221, 0.0, 0.0, 0.0]),
    (55, [-0.000082, -0.000072, 0.0, 0.0]),
    (56, [0.098198, 0.116133, 0.303293, 0.505830]),
    (57, [-0.000234, 0.0, 0.0, 0.0]),
    (58, [-0.000218, 0.0, 0.0, 0.0]),
];

fn check(nuclide: &str, file: &str, oracle: &[(i32, [f64; 4])]) -> f64 {
    let Some(tape) = reference_file_or_skip(
        "endf",
        file,
        "evaluation (inelastic mu-bar vs OpenMC)",
    ) else {
        return -1.0;
    };
    let nuc =
        Nuclide::from_endf_file(&tape, nuclide, TEMP_K, 1.0e-3).expect("nuclide reconstructs");

    println!("\n{nuclide}: <mu_cm> per discrete level, ours vs OpenMC");
    println!("{:>4} {:>11} {:>11} {:>11} {:>10}", "MT", "E (eV)", "ours", "OpenMC", "diff");
    let mut worst = 0.0_f64;
    for &(mt, theirs) in oracle {
        for (k, &e) in ENERGIES.iter().enumerate() {
            let ours = nuc.inelastic_mubar_cm(mt, e);
            let d = ours - theirs[k];
            worst = worst.max(d.abs());
            println!("{mt:4} {e:11.3e} {ours:+11.6} {:+11.6} {d:+10.2e}", theirs[k]);
            assert!(
                d.abs() <= MUBAR_TOL,
                "{nuclide} MT={mt} <mu_cm> at {e:.3e} eV is {ours:+.6} here against OpenMC's \
                 {:+.6} (difference {d:+.2e}, tolerance {MUBAR_TOL:.0e}).\n\
                 <mu> sets Sigma_tr = Sigma_t(1 - <mu>) and therefore leakage. A real \
                 disagreement here means the MF=4 parse is wrong, which would make the Godiva \
                 leakage attribution in verification_and_validation/openmc_godiva_cross_code/ \
                 wrong as well. Do NOT widen this tolerance to make it pass.",
                theirs[k]
            );
        }
    }
    println!("  {nuclide} worst |difference| = {worst:.2e}");
    worst
}

#[test]
fn inelastic_level_mean_cosines_match_openmc() {
    let w8 = check("U238", "n-092_U_238.endf", OPENMC_U238);
    let w5 = check("U235", "n-092_U_235-ENDF8.0.endf", OPENMC_U235);
    if w8 < 0.0 && w5 < 0.0 {
        return; // both tapes absent; reference_file_or_skip already said so
    }
    println!("\n  worst over both nuclides = {:.2e}", w8.max(w5));
}

/// The structural check: U-235's low-lying levels are near-isotropic while
/// U-238's are strongly forward-peaked, and both codes agree on *which* is
/// which.
///
/// This is worth more than any single number. A parse that silently produced
/// isotropic distributions everywhere would still pass the U-235 rows above; a
/// parse that invented anisotropy everywhere would still pass the U-238 rows.
/// Only a correct parse passes both, and this test states that as the
/// proposition rather than leaving it implicit in a table.
#[test]
fn the_two_nuclides_differ_in_anisotropy_the_way_the_evaluation_says() {
    let (Some(t8), Some(t5)) = (
        reference_file_or_skip("endf", "n-092_U_238.endf", "U-238 (anisotropy asymmetry)"),
        reference_file_or_skip(
            "endf",
            "n-092_U_235-ENDF8.0.endf",
            "U-235 (anisotropy asymmetry)",
        ),
    ) else {
        return;
    };
    let u238 = Nuclide::from_endf_file(&t8, "U238", TEMP_K, 1.0e-3).expect("U-238 reconstructs");
    let u235 = Nuclide::from_endf_file(&t5, "U235", TEMP_K, 1.0e-3).expect("U-235 reconstructs");

    let e = 5.0e6;
    let a8 = u238.inelastic_mubar_cm(51, e);
    let a5 = u235.inelastic_mubar_cm(51, e);
    let b5 = u235.inelastic_mubar_cm(53, e);

    assert!(
        a8 > 0.2,
        "U-238 MT=51 <mu_cm> at 5 MeV is {a8:+.4}, expected ~+0.25. The strongest anisotropy in \
         the levels that matter for Godiva has gone missing."
    );
    assert!(
        a5.abs() < 0.01,
        "U-235 MT=51 <mu_cm> at 5 MeV is {a5:+.4}, expected ~0. This level is near-isotropic in \
         ENDF/B-VIII.0 (9-point distributions with a_1 ~ 0 at all 124 tabulated energies) and \
         OpenMC reads it the same way. A non-zero value here means anisotropy is being \
         manufactured where the evaluation has none."
    );
    assert!(
        b5 > 0.2,
        "U-235 MT=53 <mu_cm> at 5 MeV is {b5:+.4}, expected ~+0.25. U-235 is not uniformly \
         isotropic -- MT=53 and MT=56 are strongly forward-peaked, and reading the whole nuclide \
         as isotropic would lose that."
    );
    println!(
        "  at 5 MeV: U-238 MT=51 {a8:+.4} (anisotropic), U-235 MT=51 {a5:+.4} (isotropic), \
         U-235 MT=53 {b5:+.4} (anisotropic) -- the asymmetry the evaluation carries"
    );
}
