//! # Non-coherent fault trees, verified against compiled SCRAM
//!
//! A tree is **non-coherent** when a component *working* can contribute to the
//! top event — a `not`, `nand`, `nor` or `xor` somewhere in its logic. The
//! cut sets then involve complemented literals, and getting from those to the
//! minimal cut sets needs a step the coherent case does not: deleting the
//! complements and re-minimising.
//!
//! [`raffles::scram::mocus`] does that, and this file checks it against
//! upstream. The other SCRAM test files cover coherent trees only, and are
//! kept separate because **non-coherent models need different expectations**
//! — see [`our_exact_value_exceeds_scrams_because_cut_sets_are_conservative`],
//! which is the reason the split exists rather than a footnote to it.
//!
//! ## Where the models come from
//!
//! | model | source | why |
//! |---|---|---|
//! | `models-for-this-port/noncoherent_small` | **written here** | upstream has no small non-coherent model |
//! | `Aralia/das9601` | upstream's `input/` suite | 288 gates, 14 `not`, 12 `xor`, 4,259 products |
//!
//! Writing one of the inputs needs saying plainly. Of upstream's seven models
//! containing a negating connective, four produce no products, two are
//! event-tree or alignment models this port does not handle, and the only
//! usable one is `das9601` — at 288 gates and 4,259 products, not something a
//! failure can be diagnosed from. **SCRAM is still the oracle either way**:
//! every expected value below came from running the compiled binary. Only the
//! question is ours, and the model is committed at
//! `reference-data/scram/models-for-this-port/noncoherent_small.xml` with its
//! reasoning in an XML comment.
//!
//! ## What `das9601` does and does not contribute
//!
//! Its 4,259 products exercise the **quantification** layer at a scale nothing
//! else here reaches. Its cut sets are **not** generated by this port:
//! `scram::mocus` exceeds its expansion ceiling on it, which is measured and
//! recorded rather than hidden — see
//! [`das9601_is_beyond_this_algorithm_and_says_so`].

use raffles::scram::fault_tree::{Connective, FaultTreeBuilder, FaultTreeModel};
use raffles::scram::mocus::{minimal_cut_sets, DEFAULT_LIMIT_ORDER};
use raffles::scram::probability::{top_event_probability, Approximation, CutSet};
use std::collections::{BTreeSet, HashMap};

const FIXTURE: &str = "oracle-noncoherent.txt";

// ---------------------------------------------------------------------------
// Fixture loading — the same format as the coherent oracle, different file.
// ---------------------------------------------------------------------------

struct Oracle {
    events: HashMap<String, f64>,
    products: Vec<BTreeSet<String>>,
    totals: HashMap<String, f64>,
}

struct ModelSpec {
    gates: Vec<(String, String, Option<usize>, Vec<String>)>,
    top: Option<String>,
    unparsed: Vec<String>,
}

fn fixture(name: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../reference-data/scram")
        .join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

fn load_oracles() -> HashMap<String, Oracle> {
    let mut out = HashMap::new();
    let mut name = String::new();
    let mut cur: Option<Oracle> = None;
    for line in fixture(FIXTURE).lines() {
        let f: Vec<&str> = line.split_whitespace().collect();
        if f.is_empty() {
            continue;
        }
        match f[0] {
            "MODEL" => {
                name = f[1].to_string();
                cur = Some(Oracle {
                    events: HashMap::new(),
                    products: Vec::new(),
                    totals: HashMap::new(),
                });
            }
            "EVENT" => {
                if let Some(o) = cur.as_mut() {
                    o.events.insert(f[1].to_string(), f[2].parse().unwrap());
                }
            }
            "PRODUCT" => {
                if let Some(o) = cur.as_mut() {
                    o.products
                        .push(f[2..].iter().map(|s| s.to_string()).collect());
                }
            }
            "TOTAL" => {
                if let Some(o) = cur.as_mut() {
                    o.totals.insert(f[1].to_string(), f[2].parse().unwrap());
                }
            }
            "END" => {
                if let Some(o) = cur.take() {
                    out.insert(std::mem::take(&mut name), o);
                }
            }
            _ => {}
        }
    }
    out
}

fn load_model(wanted: &str) -> ModelSpec {
    let mut cur: Option<ModelSpec> = None;
    let mut found = None;
    for line in fixture("models.txt").lines() {
        let f: Vec<&str> = line.split_whitespace().collect();
        if f.is_empty() {
            continue;
        }
        match f[0] {
            "MODEL" => {
                cur = (f[1] == wanted).then(|| ModelSpec {
                    gates: Vec::new(),
                    top: None,
                    unparsed: Vec::new(),
                })
            }
            "GATE" => {
                if let Some(m) = cur.as_mut() {
                    let min = (f[3] != "-").then(|| f[3].parse().expect("a number"));
                    m.gates.push((
                        f[1].to_string(),
                        f[2].to_string(),
                        min,
                        f[4..].iter().map(|s| s.to_string()).collect(),
                    ));
                }
            }
            "TOP" => {
                if let Some(m) = cur.as_mut() {
                    m.top = Some(f[1].to_string())
                }
            }
            "CANNOT-PARSE" => {
                if let Some(m) = cur.as_mut() {
                    m.unparsed.push(f[1..].join(" "))
                }
            }
            "END" => {
                if let Some(m) = cur.take() {
                    found = Some(m)
                }
            }
            _ => {}
        }
    }
    found.unwrap_or_else(|| panic!("`{wanted}` is not in models.txt"))
}

/// Builds the tree from the structure fixture, with probabilities from the
/// oracle.
///
/// An event the model names but SCRAM never priced gets `0.5` and is returned
/// in the second slot; every caller asserts no generated cut set touches one.
/// `noncoherent_small`'s `b` is exactly that case — it appears only under a
/// `not`, so it survives in no minimal cut set and SCRAM's report never
/// mentions it.
fn build(name: &str, oracle: &Oracle) -> (FaultTreeModel, Vec<usize>) {
    let spec = load_model(name);
    assert!(
        spec.unparsed.is_empty(),
        "{name}: structure not readable: {:?}",
        spec.unparsed
    );

    let gate_names: BTreeSet<&str> = spec.gates.iter().map(|(n, ..)| n.as_str()).collect();
    let mut event_names: Vec<&str> = oracle.events.keys().map(|s| s.as_str()).collect();
    for (_, _, _, args) in &spec.gates {
        for a in args {
            let n = &a[2..];
            if !gate_names.contains(n)
                && !oracle.events.contains_key(n)
                && !event_names.contains(&n)
            {
                event_names.push(n);
            }
        }
    }
    event_names.sort_unstable();

    let mut b = FaultTreeBuilder::new();
    let mut unpriced = Vec::new();
    for (i, n) in event_names.iter().enumerate() {
        let p = match oracle.events.get(*n) {
            Some(&p) => p,
            None => {
                unpriced.push(i);
                0.5
            }
        };
        b.basic_event(n, p).expect("valid probability");
    }
    for (gate, connective, min, args) in &spec.gates {
        let c = match connective.as_str() {
            "and" => Connective::And,
            "or" => Connective::Or,
            "null" => Connective::Null,
            "not" => Connective::Not,
            "nand" => Connective::Nand,
            "nor" => Connective::Nor,
            "xor" => Connective::Xor,
            "atleast" => Connective::Atleast {
                min: min.expect("atleast carries its min"),
            },
            other => panic!("{name}: unhandled connective `{other}`"),
        };
        let arg_names: Vec<&str> = args.iter().map(|a| &a[2..]).collect();
        b.gate(gate, c, &arg_names)
            .unwrap_or_else(|e| panic!("{name} gate `{gate}`: {e}"));
    }
    let model = b
        .build(spec.top.as_ref().expect("a top gate"))
        .unwrap_or_else(|e| panic!("{name}: {e}"));
    assert!(
        !model.tree().is_coherent(),
        "{name} is in the non-coherent fixture but every gate is coherent"
    );
    (model, unpriced)
}

/// Turns an oracle's named products into indexed cut sets, with probabilities.
fn indexed(o: &Oracle) -> (Vec<f64>, Vec<CutSet>) {
    let mut names: Vec<&String> = o.events.keys().collect();
    names.sort();
    let index: HashMap<&str, usize> = names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i))
        .collect();
    let probs: Vec<f64> = names.iter().map(|n| o.events[*n]).collect();
    let cut_sets = o
        .products
        .iter()
        .map(|p| {
            let members: Vec<usize> = p.iter().map(|n| index[n.as_str()]).collect();
            CutSet::new(&members).unwrap()
        })
        .collect();
    (probs, cut_sets)
}

fn agrees(ours: f64, theirs: f64, tol: f64) -> bool {
    (ours - theirs).abs() / theirs.abs().max(1.0) < tol
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// **Methodology.** Generate the minimal cut sets of a non-coherent tree and
/// compare them, as a set of sets, against the products SCRAM reports for the
/// same model.
///
/// The model is `a AND NOT b`, OR'd with `c XOR d`. By hand: the first branch
/// gives the implicant `{a+, b-}`; the `xor` gives `{c+, d-}` and `{c-, d+}`.
/// Deleting the complements and absorbing leaves `{a}`, `{c}`, `{d}`. That is
/// small enough to check by eye, which is the point of having written it —
/// the only non-coherent model in upstream's suite that produces anything is
/// `das9601`, and a disagreement there would be undiagnosable.
///
/// **Result** (2026-09-21): `{a}`, `{c}`, `{d}` — exactly SCRAM's three
/// products, none missing and none spurious. `b` appears in no cut set, which
/// is why SCRAM's report never prices it.
#[test]
fn generated_cut_sets_of_a_non_coherent_tree_match_scram() {
    let oracles = load_oracles();
    let name = "models-for-this-port/noncoherent_small";
    let oracle = &oracles[name];
    let (model, unpriced) = build(name, oracle);

    let ours = minimal_cut_sets(model.tree(), DEFAULT_LIMIT_ORDER).unwrap();
    for c in &ours {
        for m in c.members() {
            assert!(!unpriced.contains(m), "a cut set reached an unpriced event");
        }
    }
    let ours_named: BTreeSet<BTreeSet<String>> = ours
        .iter()
        .map(|c| {
            c.members()
                .iter()
                .map(|&i| model.basic_event_names()[i].clone())
                .collect()
        })
        .collect();
    let theirs: BTreeSet<BTreeSet<String>> = oracle.products.iter().cloned().collect();

    println!("ours {ours_named:?}");
    println!("scram {theirs:?}");
    assert_eq!(ours_named, theirs);
}

/// **Methodology.** The two approximations are computed **from the cut sets**
/// by both codes, so they must agree; the exact value is not, and must not.
///
/// This is the distinction the whole file exists for. For a non-coherent tree
/// SCRAM's reported `probability` with no approximation flag is the
/// **true function's** probability, obtained from its BDD. This port has no
/// BDD, and `Approximation::Exact` is inclusion-exclusion over the *minimal
/// cut sets* — which for a non-coherent tree describe a strictly larger
/// function, because deleting the negative literals throws away the
/// requirement that some component be working. So ours must come out
/// **higher**, and a run where it did not would mean the elimination had lost
/// something.
///
/// **Result** (2026-09-21), on `a AND NOT b` OR `c XOR d`:
///
/// | quantity | RAFFLES | SCRAM | |
/// |---|---|---|---|
/// | rare-event | 0.800000 | 0.8 | agree — both sum the same 3 cut sets |
/// | MCUB | 0.622000 | 0.622 | agree — both combine the same 3 cut sets |
/// | "exact" | **0.622000** | **0.503200** | **differ, necessarily** |
///
/// The gap is `+23.6 %`, and it is the conservatism of minimal cut sets, not
/// an error: `P(top)` really is 0.5032, and any method that reasons from
/// `{a}, {c}, {d}` alone cannot recover that. Note ours coincides with MCUB
/// here because the three cut sets are disjoint singletons; that is arithmetic
/// of this example, not a general identity.
#[test]
fn our_exact_value_exceeds_scrams_because_cut_sets_are_conservative() {
    let oracles = load_oracles();
    let name = "models-for-this-port/noncoherent_small";
    let oracle = &oracles[name];
    let (model, _) = build(name, oracle);
    let cut_sets = minimal_cut_sets(model.tree(), DEFAULT_LIMIT_ORDER).unwrap();
    let p = model.probabilities();

    for (mode, approximation) in [
        ("rare-event", Approximation::RareEvent),
        ("mcub", Approximation::Mcub),
    ] {
        let ours = top_event_probability(&cut_sets, p, approximation).unwrap();
        let theirs = oracle.totals[mode];
        println!("{mode:<11} ours {ours:.6}  scram {theirs:.6}");
        assert!(
            agrees(ours, theirs, 5e-6),
            "{mode}: ours {ours}, SCRAM {theirs}"
        );
    }

    let ours = top_event_probability(&cut_sets, p, Approximation::Exact).unwrap();
    let theirs = oracle.totals["exact"];
    let excess = 100.0 * (ours - theirs) / theirs;
    println!("exact       ours {ours:.6}  scram {theirs:.6}  (+{excess:.1} % conservative)");
    assert!(
        ours > theirs,
        "cut-set quantification of a non-coherent tree must be an UPPER bound on the \
         true probability; ours {ours} is not above SCRAM's BDD value {theirs}"
    );
    assert!(
        excess > 20.0 && excess < 25.0,
        "the conservatism of this model is +23.6 %; got +{excess:.1} %"
    );
}

/// **Methodology.** The quantification layer at a scale nothing else in the
/// fixture reaches: `Aralia/das9601`'s **4,259 cut sets over 108 basic
/// events**, taken from SCRAM's own report, summed and combined by this port
/// and compared against SCRAM's own two approximation runs.
///
/// Only the approximations are checked. `Approximation::Exact` is `2^n` and
/// refuses past [`raffles::scram::probability::EXACT_CUT_SET_LIMIT`]; and for
/// a non-coherent tree it would not match anyway, for the reason the test
/// above measures.
///
/// **Result** (2026-09-21): rare-event `0.004783225` against SCRAM's
/// `0.004783220`, MCUB `0.004772037` against `0.004772040`. SCRAM's exact BDD
/// value for this model is `0.0042344` — 11 % below its own rare-event figure,
/// which is the same conservatism showing up on a real model.
#[test]
fn quantifying_4259_cut_sets_matches_scram() {
    let oracles = load_oracles();
    let oracle = &oracles["Aralia/das9601"];
    let (probs, cut_sets) = indexed(oracle);
    assert_eq!(cut_sets.len(), 4259, "fixture changed");
    assert_eq!(probs.len(), 108, "fixture changed");

    for (mode, approximation) in [
        ("rare-event", Approximation::RareEvent),
        ("mcub", Approximation::Mcub),
    ] {
        let ours = top_event_probability(&cut_sets, &probs, approximation).unwrap();
        let theirs = oracle.totals[mode];
        println!("{mode:<11} ours {ours:.9}  scram {theirs:.9}");
        assert!(
            agrees(ours, theirs, 5e-6),
            "{mode}: ours {ours}, SCRAM {theirs}"
        );
    }
    println!(
        "scram's exact BDD value is {:.7}, {:.0} % below its own rare-event figure",
        oracle.totals["exact"],
        100.0 * (oracle.totals["rare-event"] - oracle.totals["exact"])
            / oracle.totals["rare-event"]
    );
}

/// **Methodology.** `Aralia/das9601` is beyond this algorithm, and this pins
/// *how* it fails: with the named expansion-limit error, not a hang, not an
/// out-of-memory kill, and not a wrong answer.
///
/// That distinction is the whole value of the check. A top-down MOCUS on 288
/// gates carrying 12 `xor`s — each of which doubles the branch count — is
/// exactly the case Rauzy's 1993 paper was written about, and exactly why
/// upstream uses a ZBDD instead. This port cannot do it and should say so
/// rather than appear to succeed.
///
/// **Result** (2026-09-21): exceeds [`raffles::scram::mocus::EXPANSION_LIMIT`]
/// (5,000,000 intermediate states) at the default order limit of 20 after
/// **28.9 s**, and again at order limit 9 — SCRAM's own highest product order
/// for this model, so the tightest limit that could still reproduce its answer
/// — after a further **26.3 s**. Both return the error rather than
/// misbehaving; the whole reproduction takes 57 s.
///
/// **Ignored by default** because it costs ~57 s to demonstrate a negative,
/// against about 1 s for the rest of the SCRAM suite. Run it with
/// `cargo test -p raffles --release --test scram_noncoherent -- --ignored`.
#[test]
#[ignore = "reproduces a measured scale limit; ~57 s. See docs/scram-port-verification.md"]
fn das9601_is_beyond_this_algorithm_and_says_so() {
    let oracles = load_oracles();
    let oracle = &oracles["Aralia/das9601"];
    let (model, _) = build("Aralia/das9601", oracle);

    let max_order = oracle.products.iter().map(|p| p.len()).max().unwrap();
    assert_eq!(max_order, 9, "SCRAM's highest product order for this model");

    for limit in [DEFAULT_LIMIT_ORDER, max_order] {
        let started = std::time::Instant::now();
        let err = minimal_cut_sets(model.tree(), limit)
            .expect_err("das9601 is expected to exceed the expansion ceiling");
        let message = err.to_string();
        println!(
            "limit {limit}: {message} (after {:.1} s)",
            started.elapsed().as_secs_f64()
        );
        assert!(
            message.contains("expansion exceeded") && message.contains("BDD"),
            "the failure must name the limit and point at the alternative, got: {message}"
        );
    }
}

/// **Methodology.** Properties of the complement handling that no oracle model
/// in the fixture exercises, checked on trees small enough to reason about.
///
/// **Result** (2026-09-21): all hold.
#[test]
fn complement_elimination_handles_the_cases_no_oracle_model_reaches() {
    let named = |model: &FaultTreeModel| -> BTreeSet<BTreeSet<String>> {
        minimal_cut_sets(model.tree(), DEFAULT_LIMIT_ORDER)
            .unwrap()
            .iter()
            .map(|c| {
                c.members()
                    .iter()
                    .map(|&i| model.basic_event_names()[i].clone())
                    .collect()
            })
            .collect()
    };
    let expect = |sets: &[&[&str]]| -> BTreeSet<BTreeSet<String>> {
        sets.iter()
            .map(|s| s.iter().map(|n| n.to_string()).collect())
            .collect()
    };
    let two = |f: &dyn Fn(&mut FaultTreeBuilder)| {
        let mut b = FaultTreeBuilder::new();
        b.basic_event("A", 0.1).unwrap();
        b.basic_event("B", 0.2).unwrap();
        f(&mut b);
        b.build("Top").unwrap()
    };

    // A contradiction is the empty function, not a cut set: `A AND NOT A`
    // cannot happen, and must not survive as `{A}` once the complement is
    // deleted. This is the case that makes the drop-contradictions step
    // load-bearing rather than an optimisation.
    let m = two(&|b| {
        b.gate("NotA", Connective::Not, &["A"]).unwrap();
        b.gate("Top", Connective::And, &["A", "NotA"]).unwrap();
    });
    assert!(named(&m).is_empty(), "A AND NOT A has no cut set");

    // Double negation cancels.
    let m = two(&|b| {
        b.gate("NotA", Connective::Not, &["A"]).unwrap();
        b.gate("Top", Connective::Not, &["NotA"]).unwrap();
    });
    assert_eq!(named(&m), expect(&[&["A"]]), "NOT NOT A is A");

    // De Morgan: NAND is NOT(AND), so each argument alone suffices, and the
    // complements then vanish leaving one empty set — no cut set at all.
    let m = two(&|b| {
        b.gate("Top", Connective::Nand, &["A", "B"]).unwrap();
    });
    assert!(named(&m).is_empty(), "NAND alone yields only complements");

    // NOR is NOT(OR): both must be absent, so again only complements.
    let m = two(&|b| {
        b.gate("Top", Connective::Nor, &["A", "B"]).unwrap();
    });
    assert!(named(&m).is_empty(), "NOR alone yields only complements");

    // A negated at-least: NOT(at least 2 of 3) is at least 2 of the three
    // complements, so once more nothing positive survives. Checked because the
    // index arithmetic (`n - min + 1`) is the easiest thing here to get wrong.
    let mut b = FaultTreeBuilder::new();
    for n in ["A", "B", "C"] {
        b.basic_event(n, 0.1).unwrap();
    }
    b.gate("Vote", Connective::Atleast { min: 2 }, &["A", "B", "C"])
        .unwrap();
    b.gate("Top", Connective::Not, &["Vote"]).unwrap();
    let m = b.build("Top").unwrap();
    assert!(named(&m).is_empty(), "NOT(2-of-3) yields only complements");

    // And the same negated at-least in a position where something positive
    // does survive: `D AND NOT(2-of-3)` keeps `{D}`.
    let mut b = FaultTreeBuilder::new();
    for n in ["A", "B", "C", "D"] {
        b.basic_event(n, 0.1).unwrap();
    }
    b.gate("Vote", Connective::Atleast { min: 2 }, &["A", "B", "C"])
        .unwrap();
    b.gate("NotVote", Connective::Not, &["Vote"]).unwrap();
    b.gate("Top", Connective::And, &["D", "NotVote"]).unwrap();
    let m = b.build("Top").unwrap();
    assert_eq!(
        named(&m),
        expect(&[&["D"]]),
        "D AND NOT(2-of-3) keeps {{D}}"
    );
}
