//! Macro-support framework.
//!
//! Scaffolding for the macro-based half of KOVAN codegen (docs/kovan.md §
//! "Macro Support": derive macros, attribute macros, procedural macros,
//! declarative macros, `build.rs` generation).
//!
//! ## What is fully realised vs scaffolded
//!
//! * **Declarative macros** (`macro_rules!`) — fully realised. They run entirely
//!   at compile time with zero dependencies, so they are the Android-first,
//!   offline-friendly workhorse. [`crate::kovan_fixed_point`] is a working, tested
//!   example (defined at the crate root by `#[macro_export]`).
//! * **Derive / attribute / procedural macros** — *scaffolded only*. A
//!   procedural macro must live in its own crate compiled with
//!   `proc-macro = true` (and pulls in `syn` / `quote` / `proc-macro2`), so it
//!   cannot be defined inside this library crate. [`generate_macro_scaffold`]
//!   therefore emits a documented skeleton (the separate-crate `Cargo.toml`
//!   stanza plus the macro entry point) for a human to drop into a companion
//!   `kovan-codegen-macros` crate. See `DECISIONS.md`.
//! * **`build.rs` generation** — *scaffolded only*. [`generate_macro_scaffold`]
//!   emits a `build.rs` skeleton that writes a generated `.rs` file into
//!   `OUT_DIR` for `include!`, the standard offline codegen pattern.

/// The macro mechanisms KOVAN can scaffold. Closed, enum-dispatched set.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MacroKind {
    /// `macro_rules!` — compile-time, dependency-free. Fully realised.
    Declarative,
    /// `#[derive(...)]` proc-macro — scaffold only (needs a proc-macro crate).
    Derive,
    /// Attribute proc-macro — scaffold only (needs a proc-macro crate).
    Attribute,
    /// Function-like proc-macro — scaffold only (needs a proc-macro crate).
    Procedural,
    /// `build.rs` code generation into `OUT_DIR` — scaffold only.
    BuildRs,
}

/// Emit scaffold source/skeleton text for the requested [`MacroKind`].
///
/// For [`MacroKind::Declarative`] this returns a ready-to-use `macro_rules!`
/// template. For the procedural kinds and `build.rs` it returns a **skeleton
/// with `// TODO(kovan)` markers** and the surrounding boilerplate a human needs
/// to complete the macro in a companion crate — deliberately *not* compilable
/// in-crate, because proc-macros require their own `proc-macro = true` crate.
/// The output is deterministic.
pub fn generate_macro_scaffold(kind: MacroKind) -> String {
    match kind {
        MacroKind::Declarative => DECLARATIVE_TEMPLATE.to_string(),
        MacroKind::Derive => DERIVE_SKELETON.to_string(),
        MacroKind::Attribute => ATTRIBUTE_SKELETON.to_string(),
        MacroKind::Procedural => PROCEDURAL_SKELETON.to_string(),
        MacroKind::BuildRs => BUILD_RS_SKELETON.to_string(),
    }
}

const DECLARATIVE_TEMPLATE: &str = r#"/// Declarative fixed-point loop, expanded at compile time (no dependencies).
///
/// `kovan_fixed_point!(x0, tol, max_iter, g)` iterates `x = g(x)` from `x0`
/// until `|g(x) - x| <= tol` or `max_iter` iterations elapse, evaluating to
/// `Option<f64>` (`Some(root)` on convergence, `None` otherwise).
#[macro_export]
macro_rules! kovan_fixed_point {
    ($x0:expr, $tol:expr, $max_iter:expr, $g:expr) => {{
        let g = $g;
        let mut x: f64 = $x0;
        let mut converged = None;
        for _ in 0..$max_iter {
            let xn = g(x);
            if (xn - x).abs() <= $tol {
                converged = Some(xn);
                break;
            }
            x = xn;
        }
        converged
    }};
}
"#;

const DERIVE_SKELETON: &str = r#"// Companion proc-macro crate `kovan-codegen-macros` (proc-macro = true).
// [package] ... [lib] proc-macro = true
// [dependencies] syn = "2" ; quote = "1" ; proc-macro2 = "1"
//
// NOTE: a derive macro CANNOT be defined in a normal library crate; it must
// live in its own `proc-macro = true` crate. This is a scaffold, not compilable
// here. (Android/offline note: `syn`/`quote` are pure Rust and cross-compile,
// but they are heavy — prefer declarative macros where they suffice.)
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};

#[proc_macro_derive(KovanModel)]
pub fn derive_kovan_model(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let name = &ast.ident;
    // TODO(kovan): generate the trait impl body for `name`.
    let expanded = quote! {
        impl #name {
            /// Generated by kovan-codegen derive scaffold.
            pub fn kovan_model_name() -> &'static str { stringify!(#name) }
        }
    };
    expanded.into()
}
"#;

const ATTRIBUTE_SKELETON: &str = r#"// Companion proc-macro crate `kovan-codegen-macros` (proc-macro = true).
// NOTE: attribute macros must live in a `proc-macro = true` crate — scaffold
// only, not compilable here.
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn kovan_validated(_attr: TokenStream, item: TokenStream) -> TokenStream {
    // TODO(kovan): wrap `item` (e.g. a solver fn) with a validation harness
    // that records the benchmark id and tolerance, then re-emit it unchanged.
    item
}
"#;

const PROCEDURAL_SKELETON: &str = r#"// Companion proc-macro crate `kovan-codegen-macros` (proc-macro = true).
// NOTE: function-like proc-macros must live in a `proc-macro = true` crate —
// scaffold only, not compilable here.
use proc_macro::TokenStream;

#[proc_macro]
pub fn kovan_stencil(_input: TokenStream) -> TokenStream {
    // TODO(kovan): parse a finite-difference stencil spec and emit the
    // corresponding update expression at compile time.
    TokenStream::new()
}
"#;

const BUILD_RS_SKELETON: &str = r#"// build.rs — offline code generation into OUT_DIR (the standard pattern).
// The generated file is then pulled in with `include!(concat!(env!("OUT_DIR"),
// "/generated.rs"));`. No network, no external services — Android/offline safe.
use std::{env, fs, path::Path};

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out_dir).join("generated.rs");
    // TODO(kovan): call kovan_codegen::generate(...) and write the source here.
    let generated = "// generated by build.rs\n";
    fs::write(&dest, generated).expect("write generated.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
"#;

// A working declarative macro, defined here so the crate compiles and tests it.
// `#[macro_export]` lifts it to the crate root: call it as
// `kovan_codegen::kovan_fixed_point!(...)`.
/// Declarative fixed-point loop, expanded at compile time (no dependencies).
///
/// `kovan_fixed_point!(x0, tol, max_iter, g)` iterates `x = g(x)` from `x0`
/// until `|g(x) - x| <= tol` or `max_iter` iterations elapse, evaluating to
/// `Option<f64>` (`Some(root)` on convergence, `None` otherwise). This is the
/// canonical example of KOVAN's declarative-macro strategy: pure compile-time
/// expansion, zero dependencies, Android/offline friendly.
#[macro_export]
macro_rules! kovan_fixed_point {
    ($x0:expr, $tol:expr, $max_iter:expr, $g:expr) => {{
        let g = $g;
        let mut x: f64 = $x0;
        let mut converged = None;
        for _ in 0..$max_iter {
            let xn = g(x);
            if (xn - x).abs() <= $tol {
                converged = Some(xn);
                break;
            }
            x = xn;
        }
        converged
    }};
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declarative_macro_finds_dottie_number() {
        // x = cos(x) -> Dottie number, via the compile-time-expanded macro.
        let r: Option<f64> = kovan_fixed_point!(1.0_f64, 1e-12, 500, |x: f64| x.cos());
        let r = r.unwrap();
        assert!((r - 0.739_085_133_215_160_6).abs() < 1e-10, "got {r}");
    }

    #[test]
    fn scaffold_is_deterministic_and_nonempty() {
        for k in [
            MacroKind::Declarative,
            MacroKind::Derive,
            MacroKind::Attribute,
            MacroKind::Procedural,
            MacroKind::BuildRs,
        ] {
            let a = generate_macro_scaffold(k);
            assert_eq!(a, generate_macro_scaffold(k));
            assert!(!a.is_empty());
        }
    }

    #[test]
    fn declarative_scaffold_contains_the_macro() {
        assert!(generate_macro_scaffold(MacroKind::Declarative)
            .contains("macro_rules! kovan_fixed_point"));
    }
}
