//! Experimental explicit backward correlations for IAPWS-IF97 Region 5:
//! temperature from pressure and enthalpy, `T(p,h)`, and from pressure and
//! entropy, `T(p,s)`.
//!
//! # Status — NOT an IAPWS release
//!
//! IAPWS-IF97 publishes **no** backward equations for Region 5; the only
//! official route from `(p,h)` or `(p,s)` to temperature there is to iterate
//! on the forward equations. These correlations are an in-house fit to this
//! crate's own Region 5 forward Gibbs formulation, so they are an accelerator
//! for that iteration, not a normative IAPWS supplementary release. Do not
//! cite them as IAPWS values.
//!
//! # Methodology
//!
//! Each correlation is a tensor-product Chebyshev polynomial in
//! `x = scaled(log10(p/MPa))` and `y = scaled(h)` or `scaled(s)`. Evaluation
//! is a direct polynomial sum — there is no root finding and no iteration, so
//! cost is fixed and the result is a pure function of its inputs.
//!
//! Coefficients were fitted against states generated by this crate's Region 5
//! forward equations ([`h_tp_5`](crate::region_5_steam_at_800_plus_degc::h_tp_5)
//! and [`s_tp_5`](crate::region_5_steam_at_800_plus_degc::s_tp_5)) over the fit
//! domain below.
//!
//! # Fit domain
//!
//! - Pressure: `1e-4 MPa <= p <= 50 MPa`
//! - Temperature: `1073.15 K <= T <= 2273.15 K`
//!
//! Enthalpy and entropy inputs are correspondingly bounded by the forward
//! equations over that box — roughly `3940 <= h <= 7377 kJ/kg` and
//! `6.54 <= s <= 14.72 kJ/(kg K)`. **Outside the fit domain the Chebyshev
//! polynomial is an unbounded extrapolation and the result is meaningless.**
//! Neither function clamps or validates its input; callers that cannot
//! guarantee an in-domain state should bound-check first.
//!
//! # Verification results
//!
//! Round-trip accuracy against the Region 5 forward equations is measured by
//! the tests in [`super::tests`]; see those tests for the measured maximum and
//! RMS temperature deviation and the date they were taken. No comparison
//! against published IAPWS backward-equation reference values is possible,
//! because no such published backward equations exist for Region 5.

use uom::si::{
    available_energy::kilojoule_per_kilogram, f64::*, pressure::megapascal,
    specific_heat_capacity::kilojoule_per_kilogram_kelvin, thermodynamic_temperature::kelvin,
};

use super::chebyshev::{cheb2_dense, scale};

const PH_XMIN: f64 = -3.99999353394005697e+00;
const PH_XMAX: f64 = 1.69893404407708815e+00;
const PH_YMIN: f64 = 3.94047337303068116e+03;
const PH_YMAX: f64 = 7.37696947955125324e+03;
const PS_XMIN: f64 = -3.99999353394005697e+00;
const PS_XMAX: f64 = 1.69893404407708815e+00;
const PS_YMIN: f64 = 6.53664378866310258e+00;
const PS_YMAX: f64 = 1.47190091453600029e+01;

const PH_COEFFS: [[f64; 17]; 13] = [
    [
        1.65145740620776633e+03,
        6.37497897732013485e+02,
        -1.70231887664178032e+01,
        1.99274906532221507e+00,
        -1.12987372680336762e-01,
        -5.89204709590376297e-02,
        2.24069520336627193e-02,
        -2.76225407007757440e-03,
        -3.09047790139516110e-03,
        3.75288517379601672e-03,
        -2.99566924967109571e-03,
        2.06032263626809709e-03,
        -1.28541776732049584e-03,
        7.15864335404603480e-04,
        -3.40739042236748446e-04,
        1.23600109915855683e-04,
        -2.93098655301804456e-05,
    ],
    [
        1.09266026700253889e+01,
        -1.34295405658473399e+01,
        4.83858507183198938e+00,
        -1.55010725440645913e+00,
        4.66192342880916044e-01,
        -1.40513310054608098e-01,
        4.87129192029271962e-02,
        -2.27073300662539168e-02,
        1.40584981322007252e-02,
        -9.84150796413985063e-03,
        6.95685477008911590e-03,
        -4.70161302285543314e-03,
        3.00017276445174730e-03,
        -1.76677315702988835e-03,
        9.79931172253145633e-04,
        -4.60735106372567316e-04,
        1.77603216160449051e-04,
    ],
    [
        8.36674751332269295e+00,
        -1.02301316402997884e+01,
        3.61181141148542650e+00,
        -1.10885370622947921e+00,
        2.99112451614506725e-01,
        -6.42525279768033641e-02,
        3.84153404570941603e-03,
        8.60102831217268715e-03,
        -9.11977530165586359e-03,
        7.14372537398233476e-03,
        -5.05068160747157435e-03,
        3.32519696681909949e-03,
        -2.05587113246963327e-03,
        1.14593206299096195e-03,
        -5.63068012753742408e-04,
        2.12027910032386302e-04,
        -6.39681626495303135e-05,
    ],
    [
        5.43810932508739242e+00,
        -6.62470664537465481e+00,
        2.31285094925091173e+00,
        -7.14807389020634787e-01,
        2.09800439833157881e-01,
        -6.53761470655993548e-02,
        2.64570953197326153e-02,
        -1.52492053203752143e-02,
        1.07596167082331107e-02,
        -7.89567012283054481e-03,
        5.62094638494414767e-03,
        -3.77465183422720507e-03,
        2.37204805643287386e-03,
        -1.37309560206588799e-03,
        7.36316452572438607e-04,
        -3.40799270855285386e-04,
        1.17729961207846401e-04,
    ],
    [
        2.94231558867568310e+00,
        -3.52405660611864135e+00,
        1.14724617635113191e+00,
        -3.04186218662147567e-01,
        5.62645755281039328e-02,
        5.14839067463057631e-03,
        -1.58609454038254327e-02,
        1.47709505345385850e-02,
        -1.16621640218070866e-02,
        8.61482248472356105e-03,
        -6.08723776782227333e-03,
        4.07930990688676332e-03,
        -2.59913742674533488e-03,
        1.51050695376753197e-03,
        -8.09425551050679815e-04,
        3.43981356980549435e-04,
        -1.30334692737932301e-04,
    ],
    [
        1.36017200688132789e+00,
        -1.60745227553510617e+00,
        4.99307826355682494e-01,
        -1.34511688737294577e-01,
        3.83752670550929764e-02,
        -1.71992621185079742e-02,
        1.27067121206616562e-02,
        -1.06971689176145190e-02,
        8.69037086807367132e-03,
        -6.63627202710692643e-03,
        4.74361893683106217e-03,
        -3.16630999399780677e-03,
        1.96054470273132608e-03,
        -1.11449897328608216e-03,
        5.67012957768397996e-04,
        -2.48517316804530708e-04,
        6.65189197945892374e-05,
    ],
    [
        4.76937209033508225e-01,
        -5.18152678770221087e-01,
        9.57557344184181147e-02,
        1.69932994699735218e-02,
        -3.23217663187911342e-02,
        2.72699225868056061e-02,
        -2.08165937658542077e-02,
        1.57007400667517061e-02,
        -1.17749162405651475e-02,
        8.59323391773969547e-03,
        -6.07184679806138661e-03,
        4.07297673388029580e-03,
        -2.61381972374508109e-03,
        1.53244489355852664e-03,
        -8.47613150813941729e-04,
        3.72133777862160287e-04,
        -1.57230908701677663e-04,
    ],
    [
        1.36361480057581197e-01,
        -1.38941477052188844e-01,
        1.57072572025249713e-02,
        9.96766089835787739e-04,
        5.01915707126343591e-03,
        -9.73366969168054652e-03,
        1.07739139958251684e-02,
        -9.74238191313414603e-03,
        7.90438416703764801e-03,
        -5.95166595589624592e-03,
        4.17897116781640321e-03,
        -2.73700189325731813e-03,
        1.65105774452456444e-03,
        -9.00710503517032635e-04,
        4.23094703233317659e-04,
        -1.74101649045965701e-04,
        3.38499978005391000e-05,
    ],
    [
        -1.01328958959356896e-02,
        4.26036538309020330e-02,
        -5.68566197346314084e-02,
        4.22626903220612027e-02,
        -2.84053244616488954e-02,
        1.98625345973759693e-02,
        -1.47746233379191239e-02,
        1.12711595620176297e-02,
        -8.57531527378174729e-03,
        6.32276354951066821e-03,
        -4.49482787728783251e-03,
        3.02794771828374110e-03,
        -1.96275908003978872e-03,
        1.16840084965197377e-03,
        -6.64230422932732267e-04,
        2.98550584567180977e-04,
        -1.32757465069133218e-04,
    ],
    [
        -1.07820921546157855e-02,
        1.55649841593045735e-02,
        -6.20322629505709600e-03,
        -5.97970582283835483e-03,
        1.22284032915165319e-02,
        -1.35328111939605478e-02,
        1.23920417912661840e-02,
        -1.03571872833914114e-02,
        8.13321522164489608e-03,
        -6.04358350163725078e-03,
        4.24734423781636394e-03,
        -2.78924580483774776e-03,
        1.69870887846901297e-03,
        -9.32565422440134739e-04,
        4.45664102765697123e-04,
        -1.82020950473038567e-04,
        4.33046843397733028e-05,
    ],
    [
        -2.39649280211153837e-02,
        3.84100985897948277e-02,
        -2.67445012581930541e-02,
        1.69836935535789824e-02,
        -1.13137388603021805e-02,
        8.21400375959324691e-03,
        -6.26425410499376056e-03,
        4.76717163892459439e-03,
        -3.52304200246324195e-03,
        2.47908570962040997e-03,
        -1.63897837360238441e-03,
        1.01948522301142930e-03,
        -6.07444709377347181e-04,
        3.39499981819813001e-04,
        -1.91241525709706650e-04,
        8.49823753709955110e-05,
        -4.58435579604454801e-05,
    ],
    [
        -2.98903161950114793e-03,
        6.81478853742589763e-04,
        4.90397372113804408e-03,
        -8.19607145476530796e-03,
        9.05670391696666854e-03,
        -8.49813772861196526e-03,
        7.38584983766266134e-03,
        -6.11851307737953931e-03,
        4.87329503560385291e-03,
        -3.71015587633505284e-03,
        2.70070876256411907e-03,
        -1.84717550071145098e-03,
        1.18783923094323285e-03,
        -6.93854405710681021e-04,
        3.61653776601800203e-04,
        -1.54188411206845899e-04,
        4.15505485431566512e-05,
    ],
    [
        -8.82705732749400340e-03,
        1.45695970860817425e-02,
        -1.10377363702598430e-02,
        8.48502849287058325e-03,
        -6.78355915971096124e-03,
        5.47574486304114316e-03,
        -4.28232196185795999e-03,
        3.17842975808879658e-03,
        -2.18992043410537462e-03,
        1.38273770975416710e-03,
        -7.60462629827429737e-04,
        3.43192422382898599e-04,
        -9.46286266358953299e-05,
        -1.65052129750264953e-05,
        5.14890060721029386e-05,
        -3.94459562684801313e-05,
        1.55465051001613119e-05,
    ],
];

const PS_COEFFS: [[f64; 13]; 9] = [
    [
        -1.88634563477112315e+04,
        2.14732494509985117e+04,
        -3.24670149739834742e+04,
        1.26729320702107434e+04,
        -1.53034253439417262e+04,
        5.15420632253962503e+03,
        -4.20853711644781015e+03,
        1.10543597591171965e+03,
        -6.50317554340270817e+02,
        1.03655391029797102e+02,
        -4.44434959497593809e+01,
        2.66931853022742871e+00,
        -6.34276323567974032e-01,
    ],
    [
        1.98158224482651203e+04,
        -6.96192327257876459e+04,
        2.95262000972270653e+04,
        -4.26333699627049355e+04,
        1.55381434609253192e+04,
        -1.51407253309959433e+04,
        4.63372891714327034e+03,
        -3.14805351536721309e+03,
        6.65619407332220362e+02,
        -3.34386935135582462e+02,
        3.47352383688271402e+01,
        -1.18642898427401633e+01,
        2.21008022060232179e-01,
    ],
    [
        -2.65353731566767747e+04,
        2.49599475713666252e+04,
        -4.13170736713112201e+04,
        1.64709632796422666e+04,
        -1.87666171243517019e+04,
        6.51371753881559926e+03,
        -5.05008250225583561e+03,
        1.32109575472804181e+03,
        -7.53447906733806121e+02,
        1.12372038650977629e+02,
        -4.69562441875768855e+01,
        2.21541087935906944e+00,
        -4.60509372008800710e-01,
    ],
    [
        7.66983260688171868e+03,
        -2.77810121112206361e+04,
        1.24674719681384995e+04,
        -1.61524604926861048e+04,
        6.31946935680941169e+03,
        -5.52979696218457411e+03,
        1.72639719193740075e+03,
        -1.09729534222824077e+03,
        2.16035743500580338e+02,
        -1.03925942126277960e+02,
        8.53737341083433421e+00,
        -2.63965184794869856e+00,
        2.90545699153881287e-02,
    ],
    [
        -6.34821922659493976e+03,
        6.67627574551564976e+03,
        -9.56781515697433861e+03,
        4.24775597664725501e+03,
        -4.15682135364391615e+03,
        1.52025378467837027e+03,
        -1.06424055788827536e+03,
        2.64623607751853342e+02,
        -1.41951183950503491e+02,
        1.75066789558986784e+01,
        -6.52233721462471294e+00,
        2.43696565891241335e-01,
        -3.94958570584549307e-02,
    ],
    [
        1.22452620465228938e+03,
        -3.79166454945675287e+03,
        1.94199882105534016e+03,
        -2.11010620418506369e+03,
        8.96607970670833311e+02,
        -6.86016718733332027e+02,
        2.10181558469152151e+02,
        -1.23349442224956874e+02,
        2.11317364184742473e+01,
        -8.83966515114389040e+00,
        6.68171520232135663e-01,
        -1.49952810017566662e-01,
        4.16320929304803133e-03,
    ],
    [
        -4.73091048763495564e+02,
        5.74840149299885525e+02,
        -6.90544288109832451e+02,
        3.40742166771957727e+02,
        -2.83660390289516272e+02,
        1.05747874386906915e+02,
        -6.70868970895035091e+01,
        1.52695302101164998e+01,
        -6.95063387570553459e+00,
        8.71379817012439162e-01,
        -2.29601921422727173e-01,
        1.78231870304443873e-02,
        -1.03979943105514394e-03,
    ],
    [
        4.95533399955065761e+01,
        -1.31365975546777008e+02,
        7.57176672511554898e+01,
        -6.84496607340662422e+01,
        3.08990503917107162e+01,
        -2.10380978445905384e+01,
        6.18331877449418243e+00,
        -3.01770902223415760e+00,
        5.62200564250815660e-01,
        -1.66144700193399331e-01,
        2.39206219703191891e-02,
        -2.48197079508827301e-03,
        4.53188222309108824e-04,
    ],
    [
        -5.53249017363305029e+00,
        7.56168336881728465e+00,
        -7.42680583726928489e+00,
        4.06992989064099220e+00,
        -2.95930595757317860e+00,
        1.10261521033771714e+00,
        -5.71567696401871217e-01,
        1.46593819254121627e-01,
        -4.70660222663354944e-02,
        9.82785668475116836e-03,
        -1.03294053678837372e-03,
        2.48766169534064829e-04,
        9.26019283724599518e-05,
    ],
];

/// Lowest pressure of the `T(p,h)` / `T(p,s)` fit domain, 1e-4 MPa.
pub const REGION_5_BACK_P_MIN_MPA: f64 = 1.0e-4;
/// Highest pressure of the `T(p,h)` / `T(p,s)` fit domain, 50 MPa.
pub const REGION_5_BACK_P_MAX_MPA: f64 = 50.0;
/// Lowest temperature of the `T(p,h)` / `T(p,s)` fit domain, 1073.15 K.
pub const REGION_5_BACK_T_MIN_KELVIN: f64 = 1073.15;
/// Highest temperature of the `T(p,h)` / `T(p,s)` fit domain, 2273.15 K.
pub const REGION_5_BACK_T_MAX_KELVIN: f64 = 2273.15;

/// Region 5 experimental backward correlation `T(p,h)`, on bare floats.
///
/// `p_mpa` is pressure in MPa and `h_kj_kg` specific enthalpy in kJ/kg; the
/// return value is temperature in K. See the module documentation for the fit
/// domain and its limitations.
///
/// # Panics
///
/// Panics if `p_mpa` is not strictly positive, since the correlation is a
/// polynomial in `log10(p)`.
#[inline]
pub fn t_ph_5_explicit(p_mpa: f64, h_kj_kg: f64) -> f64 {
    assert!(
        p_mpa > 0.0,
        "Region 5 backward T(p,h) needs a strictly positive pressure, got {p_mpa} MPa"
    );
    let x = scale(p_mpa.log10(), PH_XMIN, PH_XMAX);
    let y = scale(h_kj_kg, PH_YMIN, PH_YMAX);
    cheb2_dense(x, y, &PH_COEFFS)
}

/// Region 5 experimental backward correlation `T(p,s)`, on bare floats.
///
/// `p_mpa` is pressure in MPa and `s_kj_kg_k` specific entropy in kJ/(kg K);
/// the return value is temperature in K. See the module documentation for the
/// fit domain and its limitations.
///
/// # Panics
///
/// Panics if `p_mpa` is not strictly positive, since the correlation is a
/// polynomial in `log10(p)`.
#[inline]
pub fn t_ps_5_explicit(p_mpa: f64, s_kj_kg_k: f64) -> f64 {
    assert!(
        p_mpa > 0.0,
        "Region 5 backward T(p,s) needs a strictly positive pressure, got {p_mpa} MPa"
    );
    let x = scale(p_mpa.log10(), PS_XMIN, PS_XMAX);
    let y = scale(s_kj_kg_k, PS_YMIN, PS_YMAX);
    cheb2_dense(x, y, &PS_COEFFS)
}

/// Region 5 experimental backward correlation for temperature from pressure
/// and specific enthalpy, `T(p,h)`.
///
/// This is the dimensioned entry point; it wraps [`t_ph_5_explicit`].
///
/// Valid for `1e-4 MPa <= p <= 50 MPa` and enthalpies corresponding to
/// `1073.15 K <= T <= 2273.15 K`. Outside that box the result is a diverging
/// extrapolation — see the module documentation.
///
/// # Panics
///
/// Panics if `p` is not strictly positive.
pub fn t_ph_5(p: Pressure, h: AvailableEnergy) -> ThermodynamicTemperature {
    let p_mpa = p.get::<megapascal>();
    let h_kj_kg = h.get::<kilojoule_per_kilogram>();
    ThermodynamicTemperature::new::<kelvin>(t_ph_5_explicit(p_mpa, h_kj_kg))
}

/// Region 5 experimental backward correlation for temperature from pressure
/// and specific entropy, `T(p,s)`.
///
/// This is the dimensioned entry point; it wraps [`t_ps_5_explicit`].
///
/// Valid for `1e-4 MPa <= p <= 50 MPa` and entropies corresponding to
/// `1073.15 K <= T <= 2273.15 K`. Outside that box the result is a diverging
/// extrapolation — see the module documentation.
///
/// # Panics
///
/// Panics if `p` is not strictly positive.
pub fn t_ps_5(p: Pressure, s: SpecificHeatCapacity) -> ThermodynamicTemperature {
    let p_mpa = p.get::<megapascal>();
    let s_kj_kg_k = s.get::<kilojoule_per_kilogram_kelvin>();
    ThermodynamicTemperature::new::<kelvin>(t_ps_5_explicit(p_mpa, s_kj_kg_k))
}
