// Part of the kovan Zotero port (GitHub #747, #748).
//
// Upstream: Zotero, https://github.com/zotero/zotero (commit 9cbba8c4d281);
// Zotero utilities, https://github.com/zotero/utilities (commit 4051881d59c6);
// zotero-schema, https://github.com/zotero/zotero-schema (commit b86c79b56479;
// no licence text upstream; treated as AGPLv3 as part of Zotero, maintainer
// decision 2026-10-07, #747).
// Copyright (c) Corporation for Digital Scholarship, Vienna, Virginia, USA.
// Licence: AGPL-3.0. See this crate's NOTICE, "Upstream: Zotero".

//! Zotero's data model, ported so Zotero libraries can be imported into and
//! exported from kovan (GitHub #748, epic #747).
//!
//! | Module | What | Ported from |
//! |---|---|---|
//! | [`schema_generated`] | `ItemType`, `Field`, `CreatorType` enums; every item type's fields, base fields and creator types; `meta`; the CSL mappings; en-US labels | zotero-schema `schema.json` v45, generated by `kovan_codegen::zotero` |
//! | [`schema`] | field validity, base-field <-> type-specific field mapping, primary creator types | `itemFields.js`, `cachedTypes.js` |
//! | [`item`] | [`ZoteroItem`], [`ZoteroCollection`], [`ZoteroLibrary`]: the Web API / translator JSON shape | `item.js` `toJSON`/`fromJSON`, `collection.js` |
//! | [`validate`] | schema checks and `fromJSON`'s move of invalid fields into Extra | `item.js`, `utilities_internal.js` |
//! | [`date`] | `strToDate`, `parseEDTF`, `formatDate`, SQL/ISO dates | utilities `date.js` |
//! | [`csl`] | CSL-JSON both ways | utilities `utilities_item.js` |
//! | [`search`] | [`ZoteroSearch`]: a saved search, conditions as stored (added 2026-10-07, #750) | `search.js` `toJSON`/`fromJSON` |
//! | [`kovan`] | [`ZoteroItem`] <-> [`crate::KovanDocument`], with the lossy fields listed | (kovan's own) |
//!
//! Every value the ports were checked against comes from upstream's own data
//! (schema.json and Zotero's test suites); upstream code was read, never run.
//! Running upstream for code-to-code verification is GitHub #752.
//!
//! **Maturity: AI draft (1).** Not yet human-reviewed.

pub mod csl;
pub mod date;
pub mod item;
pub mod kovan;
pub mod schema;
pub mod search;
#[rustfmt::skip]
pub mod schema_generated;
pub mod validate;

pub use csl::{item_from_csl_json, item_to_csl_json, CslError, CslItem};
pub use item::{
    AnnotationData, AnnotationType, AttachmentData, Creator, CreatorName, LinkMode, Tag,
    ZoteroCollection, ZoteroItem, ZoteroJsonError, ZoteroLibrary,
};
pub use schema::{ItemTypeField, ItemTypeSchema};
pub use search::{SearchCondition, ZoteroSearch};
pub use schema_generated::{CreatorType, Field, ItemType, SCHEMA_COMMIT, SCHEMA_VERSION};
pub use validate::ValidationIssue;
