/// Solve the scalar equation `x = g(x)` by **fixed-point iteration**.
///
/// Starting from `x0`, repeatedly applies `x_{k+1} = g(x_k)`. The iteration
/// converges to a fixed point `x* = g(x*)` whenever `g` is a contraction near
/// `x*` (i.e. `|g'(x*)| < 1`); the smaller `|g'|`, the faster the (linear)
/// convergence. If `|g'| >= 1` the iteration may diverge — reformulate the
/// equation so the fixed-point map is contractive.
///
/// # Arguments
/// * `g`        — the fixed-point map.
/// * `x0`       — initial guess.
/// * `tol`      — absolute tolerance: stop when `|g(x) - x| <= tol`.
/// * `max_iter` — iteration cap.
///
/// # Returns
/// `Some(x)` on convergence, or `None` if `max_iter` is exceeded.
///
/// Generated by kovan-codegen (docs/kovan.md § "Numerical Methods → Nonlinear
/// Solvers"). Deterministic template; depends only on `core`/`std` `f64`.
pub fn fixed_point<G>(g: G, x0: f64, tol: f64, max_iter: usize) -> Option<f64>
where
    G: Fn(f64) -> f64,
{
    let mut x = x0;
    for _ in 0..max_iter {
        let xn = g(x);
        if (xn - x).abs() <= tol {
            return Some(xn);
        }
        x = xn;
    }
    None
}
