/// Solve the vector equation `F(x) = 0` for `x` in `R^n` by **Newton's method
/// for systems**.
///
/// Each iteration linearises `F` at `x_k` and solves the Jacobian system for the
/// Newton step: `J(x_k) delta = -F(x_k)`, then updates `x_{k+1} = x_k + delta`.
/// Near a simple root with a nonsingular Jacobian it converges quadratically.
/// The linear solve uses Gaussian elimination with partial pivoting (embedded
/// below so the template is self-contained).
///
/// # Arguments
/// * `f`        — residual map: `f(x)` returns the length-`n` vector `F(x)`.
/// * `jac`      — Jacobian map: `jac(x)` returns the `n x n` matrix `J[i][j] = dF_i / dx_j`.
/// * `x0`       — initial guess (its length fixes `n`).
/// * `tol`      — absolute tolerance on the Euclidean residual norm `||F(x)||`.
/// * `max_iter` — iteration cap.
///
/// # Returns
/// `Some(x)` on convergence, or `None` if a Jacobian solve fails (singular) or
/// `max_iter` is exceeded.
///
/// Generated by kovan-codegen (docs/kovan.md § "Numerical Methods → Nonlinear
/// Solvers"). Deterministic template; depends only on `core`/`std` `f64`.
pub fn newton_system<F, J>(
    f: F,
    jac: J,
    x0: Vec<f64>,
    tol: f64,
    max_iter: usize,
) -> Option<Vec<f64>>
where
    F: Fn(&[f64]) -> Vec<f64>,
    J: Fn(&[f64]) -> Vec<Vec<f64>>,
{
    let n = x0.len();
    let mut x = x0;
    for _ in 0..max_iter {
        let fx = f(&x);
        let norm = fx.iter().map(|v| v * v).sum::<f64>().sqrt();
        if norm <= tol {
            return Some(x);
        }
        let j = jac(&x);
        let rhs: Vec<f64> = fx.iter().map(|v| -v).collect();
        let delta = solve_linear(&j, &rhs)?;
        if delta.len() != n {
            return None;
        }
        for i in 0..n {
            x[i] += delta[i];
        }
    }
    None
}

/// Dense LU solve with partial pivoting, used for the per-iteration Jacobian
/// system. Returns `None` if the system is inconsistent or singular.
fn solve_linear(a: &[Vec<f64>], b: &[f64]) -> Option<Vec<f64>> {
    let n = b.len();
    if a.len() != n || a.iter().any(|row| row.len() != n) {
        return None;
    }
    let mut m: Vec<Vec<f64>> = a.to_vec();
    let mut x = b.to_vec();
    for k in 0..n {
        let mut piv = k;
        let mut best = m[k][k].abs();
        for (i, row) in m.iter().enumerate().skip(k + 1) {
            let v = row[k].abs();
            if v > best {
                best = v;
                piv = i;
            }
        }
        if best == 0.0 {
            return None;
        }
        if piv != k {
            m.swap(k, piv);
            x.swap(k, piv);
        }
        let pivot_row = m[k].clone();
        let pivot = pivot_row[k];
        let xk = x[k];
        for i in (k + 1)..n {
            let factor = m[i][k] / pivot;
            m[i][k] = 0.0;
            for (mij, &pkj) in m[i].iter_mut().zip(pivot_row.iter()).skip(k + 1) {
                *mij -= factor * pkj;
            }
            x[i] -= factor * xk;
        }
    }
    for i in (0..n).rev() {
        let mut sum = x[i];
        for (mij, xj) in m[i].iter().zip(x.iter()).skip(i + 1) {
            sum -= mij * xj;
        }
        x[i] = sum / m[i][i];
    }
    Some(x)
}
