//! The incompressible-fluid selector — an **enum**, matching each fluid to
//! its hardcoded [`IncompressibleFluid`](super::IncompressibleFluid). The
//! enum-dispatch replacement for CoolProp's string-keyed `INCOMP::<name>`
//! lookup: adding a fluid is a new variant, and every `match` on
//! `Incompressible` becomes exhaustive.
//!
//! GENERATED by `dev/regen_incompressible_all.py` — do not edit by hand.
//! Variant names follow the CoolProp fluid name with non-alphanumerics
//! removed (e.g. `HC10` stays `HC10`); [`Incompressible::name`] returns the
//! original CoolProp name.

use super::fluids;
use super::IncompressibleFluid;

/// A supported incompressible fluid (one per CoolProp `INCOMP` entry, 126
/// in total). Each variant maps to a hardcoded `const` [`IncompressibleFluid`]
/// via [`Incompressible::data`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
#[allow(non_camel_case_types)]
pub enum Incompressible {
    /// CoolProp `AEG`.
    AEG,
    /// CoolProp `AKF`.
    AKF,
    /// CoolProp `AL`.
    AL,
    /// CoolProp `AN`.
    AN,
    /// CoolProp `APG`.
    APG,
    /// CoolProp `AS10`.
    AS10,
    /// CoolProp `AS20`.
    AS20,
    /// CoolProp `AS30`.
    AS30,
    /// CoolProp `AS40`.
    AS40,
    /// CoolProp `AS55`.
    AS55,
    /// CoolProp `Acetone`.
    Acetone,
    /// CoolProp `Air`.
    Air,
    /// CoolProp `DEB`.
    DEB,
    /// CoolProp `DSF`.
    DSF,
    /// CoolProp `DowJ`.
    DowJ,
    /// CoolProp `DowJ2`.
    DowJ2,
    /// CoolProp `DowQ`.
    DowQ,
    /// CoolProp `DowQ2`.
    DowQ2,
    /// CoolProp `Ethanol`.
    Ethanol,
    /// CoolProp `ExampleDigital`.
    ExampleDigital,
    /// CoolProp `ExampleDigitalPure`.
    ExampleDigitalPure,
    /// CoolProp `ExampleMelinder`.
    ExampleMelinder,
    /// CoolProp `ExamplePure`.
    ExamplePure,
    /// CoolProp `ExampleSecCool`.
    ExampleSecCool,
    /// CoolProp `ExampleSolution`.
    ExampleSolution,
    /// CoolProp `FRE`.
    FRE,
    /// CoolProp `FoodAsh`.
    FoodAsh,
    /// CoolProp `FoodCarbohydrate`.
    FoodCarbohydrate,
    /// CoolProp `FoodFat`.
    FoodFat,
    /// CoolProp `FoodFiber`.
    FoodFiber,
    /// CoolProp `FoodIce`.
    FoodIce,
    /// CoolProp `FoodProtein`.
    FoodProtein,
    /// CoolProp `FoodWater`.
    FoodWater,
    /// CoolProp `GKN`.
    GKN,
    /// CoolProp `HC10`.
    HC10,
    /// CoolProp `HC20`.
    HC20,
    /// CoolProp `HC30`.
    HC30,
    /// CoolProp `HC40`.
    HC40,
    /// CoolProp `HC50`.
    HC50,
    /// CoolProp `HCB`.
    HCB,
    /// CoolProp `HCM`.
    HCM,
    /// CoolProp `HFE`.
    HFE,
    /// CoolProp `HFE2`.
    HFE2,
    /// CoolProp `HY20`.
    HY20,
    /// CoolProp `HY30`.
    HY30,
    /// CoolProp `HY40`.
    HY40,
    /// CoolProp `HY45`.
    HY45,
    /// CoolProp `HY50`.
    HY50,
    /// CoolProp `Hexane`.
    Hexane,
    /// CoolProp `IceEA`.
    IceEA,
    /// CoolProp `IceNA`.
    IceNA,
    /// CoolProp `IcePG`.
    IcePG,
    /// CoolProp `LiBr`.
    LiBr,
    /// CoolProp `LiqNa`.
    LiqNa,
    /// CoolProp `MAM`.
    MAM,
    /// CoolProp `MAM2`.
    MAM2,
    /// CoolProp `MCA`.
    MCA,
    /// CoolProp `MCA2`.
    MCA2,
    /// CoolProp `MEA`.
    MEA,
    /// CoolProp `MEA2`.
    MEA2,
    /// CoolProp `MEG`.
    MEG,
    /// CoolProp `MEG2`.
    MEG2,
    /// CoolProp `MGL`.
    MGL,
    /// CoolProp `MGL2`.
    MGL2,
    /// CoolProp `MITSW`.
    MITSW,
    /// CoolProp `MKA`.
    MKA,
    /// CoolProp `MKA2`.
    MKA2,
    /// CoolProp `MKC`.
    MKC,
    /// CoolProp `MKC2`.
    MKC2,
    /// CoolProp `MKF`.
    MKF,
    /// CoolProp `MLI`.
    MLI,
    /// CoolProp `MMA`.
    MMA,
    /// CoolProp `MMA2`.
    MMA2,
    /// CoolProp `MMG`.
    MMG,
    /// CoolProp `MMG2`.
    MMG2,
    /// CoolProp `MNA`.
    MNA,
    /// CoolProp `MNA2`.
    MNA2,
    /// CoolProp `MPG`.
    MPG,
    /// CoolProp `MPG2`.
    MPG2,
    /// CoolProp `NBS`.
    NBS,
    /// CoolProp `NaK`.
    NaK,
    /// CoolProp `PBB`.
    PBB,
    /// CoolProp `PCL`.
    PCL,
    /// CoolProp `PCR`.
    PCR,
    /// CoolProp `PGLT`.
    PGLT,
    /// CoolProp `PHE`.
    PHE,
    /// CoolProp `PHR`.
    PHR,
    /// CoolProp `PK2`.
    PK2,
    /// CoolProp `PKL`.
    PKL,
    /// CoolProp `PLR`.
    PLR,
    /// CoolProp `PMR`.
    PMR,
    /// CoolProp `PMS1`.
    PMS1,
    /// CoolProp `PMS2`.
    PMS2,
    /// CoolProp `PNF`.
    PNF,
    /// CoolProp `PNF2`.
    PNF2,
    /// CoolProp `S800`.
    S800,
    /// CoolProp `SAB`.
    SAB,
    /// CoolProp `T66`.
    T66,
    /// CoolProp `T72`.
    T72,
    /// CoolProp `TCO`.
    TCO,
    /// CoolProp `TD12`.
    TD12,
    /// CoolProp `TVP1`.
    TVP1,
    /// CoolProp `TVP1869`.
    TVP1869,
    /// CoolProp `TX22`.
    TX22,
    /// CoolProp `TY10`.
    TY10,
    /// CoolProp `TY15`.
    TY15,
    /// CoolProp `TY20`.
    TY20,
    /// CoolProp `TY24`.
    TY24,
    /// CoolProp `VCA`.
    VCA,
    /// CoolProp `VKC`.
    VKC,
    /// CoolProp `VMA`.
    VMA,
    /// CoolProp `VMG`.
    VMG,
    /// CoolProp `VNA`.
    VNA,
    /// CoolProp `Water`.
    Water,
    /// CoolProp `XLT`.
    XLT,
    /// CoolProp `XLT2`.
    XLT2,
    /// CoolProp `ZAC`.
    ZAC,
    /// CoolProp `ZFC`.
    ZFC,
    /// CoolProp `ZLC`.
    ZLC,
    /// CoolProp `ZM`.
    ZM,
    /// CoolProp `ZMC`.
    ZMC,
    /// CoolProp `ZS10`.
    ZS10,
    /// CoolProp `ZS25`.
    ZS25,
    /// CoolProp `ZS40`.
    ZS40,
    /// CoolProp `ZS45`.
    ZS45,
    /// CoolProp `ZS55`.
    ZS55,
}

impl Incompressible {
    /// Every supported fluid, for enumeration (126 in total).
    pub const ALL: &'static [Incompressible] = &[
        Incompressible::AEG,
        Incompressible::AKF,
        Incompressible::AL,
        Incompressible::AN,
        Incompressible::APG,
        Incompressible::AS10,
        Incompressible::AS20,
        Incompressible::AS30,
        Incompressible::AS40,
        Incompressible::AS55,
        Incompressible::Acetone,
        Incompressible::Air,
        Incompressible::DEB,
        Incompressible::DSF,
        Incompressible::DowJ,
        Incompressible::DowJ2,
        Incompressible::DowQ,
        Incompressible::DowQ2,
        Incompressible::Ethanol,
        Incompressible::ExampleDigital,
        Incompressible::ExampleDigitalPure,
        Incompressible::ExampleMelinder,
        Incompressible::ExamplePure,
        Incompressible::ExampleSecCool,
        Incompressible::ExampleSolution,
        Incompressible::FRE,
        Incompressible::FoodAsh,
        Incompressible::FoodCarbohydrate,
        Incompressible::FoodFat,
        Incompressible::FoodFiber,
        Incompressible::FoodIce,
        Incompressible::FoodProtein,
        Incompressible::FoodWater,
        Incompressible::GKN,
        Incompressible::HC10,
        Incompressible::HC20,
        Incompressible::HC30,
        Incompressible::HC40,
        Incompressible::HC50,
        Incompressible::HCB,
        Incompressible::HCM,
        Incompressible::HFE,
        Incompressible::HFE2,
        Incompressible::HY20,
        Incompressible::HY30,
        Incompressible::HY40,
        Incompressible::HY45,
        Incompressible::HY50,
        Incompressible::Hexane,
        Incompressible::IceEA,
        Incompressible::IceNA,
        Incompressible::IcePG,
        Incompressible::LiBr,
        Incompressible::LiqNa,
        Incompressible::MAM,
        Incompressible::MAM2,
        Incompressible::MCA,
        Incompressible::MCA2,
        Incompressible::MEA,
        Incompressible::MEA2,
        Incompressible::MEG,
        Incompressible::MEG2,
        Incompressible::MGL,
        Incompressible::MGL2,
        Incompressible::MITSW,
        Incompressible::MKA,
        Incompressible::MKA2,
        Incompressible::MKC,
        Incompressible::MKC2,
        Incompressible::MKF,
        Incompressible::MLI,
        Incompressible::MMA,
        Incompressible::MMA2,
        Incompressible::MMG,
        Incompressible::MMG2,
        Incompressible::MNA,
        Incompressible::MNA2,
        Incompressible::MPG,
        Incompressible::MPG2,
        Incompressible::NBS,
        Incompressible::NaK,
        Incompressible::PBB,
        Incompressible::PCL,
        Incompressible::PCR,
        Incompressible::PGLT,
        Incompressible::PHE,
        Incompressible::PHR,
        Incompressible::PK2,
        Incompressible::PKL,
        Incompressible::PLR,
        Incompressible::PMR,
        Incompressible::PMS1,
        Incompressible::PMS2,
        Incompressible::PNF,
        Incompressible::PNF2,
        Incompressible::S800,
        Incompressible::SAB,
        Incompressible::T66,
        Incompressible::T72,
        Incompressible::TCO,
        Incompressible::TD12,
        Incompressible::TVP1,
        Incompressible::TVP1869,
        Incompressible::TX22,
        Incompressible::TY10,
        Incompressible::TY15,
        Incompressible::TY20,
        Incompressible::TY24,
        Incompressible::VCA,
        Incompressible::VKC,
        Incompressible::VMA,
        Incompressible::VMG,
        Incompressible::VNA,
        Incompressible::Water,
        Incompressible::XLT,
        Incompressible::XLT2,
        Incompressible::ZAC,
        Incompressible::ZFC,
        Incompressible::ZLC,
        Incompressible::ZM,
        Incompressible::ZMC,
        Incompressible::ZS10,
        Incompressible::ZS25,
        Incompressible::ZS40,
        Incompressible::ZS45,
        Incompressible::ZS55,
    ];

    /// The original CoolProp fluid name (not the Rust variant identifier).
    pub fn name(self) -> &'static str {
        self.data().name
    }

    /// The hardcoded coefficient block for this fluid.
    pub fn data(self) -> &'static IncompressibleFluid {
        match self {
            Incompressible::AEG => &fluids::aeg::AEG_INCOMP,
            Incompressible::AKF => &fluids::akf::AKF_INCOMP,
            Incompressible::AL => &fluids::al::AL_INCOMP,
            Incompressible::AN => &fluids::an::AN_INCOMP,
            Incompressible::APG => &fluids::apg::APG_INCOMP,
            Incompressible::AS10 => &fluids::as10::AS10_INCOMP,
            Incompressible::AS20 => &fluids::as20::AS20_INCOMP,
            Incompressible::AS30 => &fluids::as30::AS30_INCOMP,
            Incompressible::AS40 => &fluids::as40::AS40_INCOMP,
            Incompressible::AS55 => &fluids::as55::AS55_INCOMP,
            Incompressible::Acetone => &fluids::acetone::ACETONE_INCOMP,
            Incompressible::Air => &fluids::air::AIR_INCOMP,
            Incompressible::DEB => &fluids::deb::DEB_INCOMP,
            Incompressible::DSF => &fluids::dsf::DSF_INCOMP,
            Incompressible::DowJ => &fluids::dowj::DOWJ_INCOMP,
            Incompressible::DowJ2 => &fluids::dowj2::DOWJ2_INCOMP,
            Incompressible::DowQ => &fluids::dowq::DOWQ_INCOMP,
            Incompressible::DowQ2 => &fluids::dowq2::DOWQ2_INCOMP,
            Incompressible::Ethanol => &fluids::ethanol::ETHANOL_INCOMP,
            Incompressible::ExampleDigital => &fluids::exampledigital::EXAMPLEDIGITAL_INCOMP,
            Incompressible::ExampleDigitalPure => {
                &fluids::exampledigitalpure::EXAMPLEDIGITALPURE_INCOMP
            }
            Incompressible::ExampleMelinder => &fluids::examplemelinder::EXAMPLEMELINDER_INCOMP,
            Incompressible::ExamplePure => &fluids::examplepure::EXAMPLEPURE_INCOMP,
            Incompressible::ExampleSecCool => &fluids::exampleseccool::EXAMPLESECCOOL_INCOMP,
            Incompressible::ExampleSolution => &fluids::examplesolution::EXAMPLESOLUTION_INCOMP,
            Incompressible::FRE => &fluids::fre::FRE_INCOMP,
            Incompressible::FoodAsh => &fluids::foodash::FOODASH_INCOMP,
            Incompressible::FoodCarbohydrate => &fluids::foodcarbohydrate::FOODCARBOHYDRATE_INCOMP,
            Incompressible::FoodFat => &fluids::foodfat::FOODFAT_INCOMP,
            Incompressible::FoodFiber => &fluids::foodfiber::FOODFIBER_INCOMP,
            Incompressible::FoodIce => &fluids::foodice::FOODICE_INCOMP,
            Incompressible::FoodProtein => &fluids::foodprotein::FOODPROTEIN_INCOMP,
            Incompressible::FoodWater => &fluids::foodwater::FOODWATER_INCOMP,
            Incompressible::GKN => &fluids::gkn::GKN_INCOMP,
            Incompressible::HC10 => &fluids::hc10::HC10_INCOMP,
            Incompressible::HC20 => &fluids::hc20::HC20_INCOMP,
            Incompressible::HC30 => &fluids::hc30::HC30_INCOMP,
            Incompressible::HC40 => &fluids::hc40::HC40_INCOMP,
            Incompressible::HC50 => &fluids::hc50::HC50_INCOMP,
            Incompressible::HCB => &fluids::hcb::HCB_INCOMP,
            Incompressible::HCM => &fluids::hcm::HCM_INCOMP,
            Incompressible::HFE => &fluids::hfe::HFE_INCOMP,
            Incompressible::HFE2 => &fluids::hfe2::HFE2_INCOMP,
            Incompressible::HY20 => &fluids::hy20::HY20_INCOMP,
            Incompressible::HY30 => &fluids::hy30::HY30_INCOMP,
            Incompressible::HY40 => &fluids::hy40::HY40_INCOMP,
            Incompressible::HY45 => &fluids::hy45::HY45_INCOMP,
            Incompressible::HY50 => &fluids::hy50::HY50_INCOMP,
            Incompressible::Hexane => &fluids::hexane::HEXANE_INCOMP,
            Incompressible::IceEA => &fluids::iceea::ICEEA_INCOMP,
            Incompressible::IceNA => &fluids::icena::ICENA_INCOMP,
            Incompressible::IcePG => &fluids::icepg::ICEPG_INCOMP,
            Incompressible::LiBr => &fluids::libr::LIBR_INCOMP,
            Incompressible::LiqNa => &fluids::liqna::LIQNA_INCOMP,
            Incompressible::MAM => &fluids::mam::MAM_INCOMP,
            Incompressible::MAM2 => &fluids::mam2::MAM2_INCOMP,
            Incompressible::MCA => &fluids::mca::MCA_INCOMP,
            Incompressible::MCA2 => &fluids::mca2::MCA2_INCOMP,
            Incompressible::MEA => &fluids::mea::MEA_INCOMP,
            Incompressible::MEA2 => &fluids::mea2::MEA2_INCOMP,
            Incompressible::MEG => &fluids::meg::MEG_INCOMP,
            Incompressible::MEG2 => &fluids::meg2::MEG2_INCOMP,
            Incompressible::MGL => &fluids::mgl::MGL_INCOMP,
            Incompressible::MGL2 => &fluids::mgl2::MGL2_INCOMP,
            Incompressible::MITSW => &fluids::mitsw::MITSW_INCOMP,
            Incompressible::MKA => &fluids::mka::MKA_INCOMP,
            Incompressible::MKA2 => &fluids::mka2::MKA2_INCOMP,
            Incompressible::MKC => &fluids::mkc::MKC_INCOMP,
            Incompressible::MKC2 => &fluids::mkc2::MKC2_INCOMP,
            Incompressible::MKF => &fluids::mkf::MKF_INCOMP,
            Incompressible::MLI => &fluids::mli::MLI_INCOMP,
            Incompressible::MMA => &fluids::mma::MMA_INCOMP,
            Incompressible::MMA2 => &fluids::mma2::MMA2_INCOMP,
            Incompressible::MMG => &fluids::mmg::MMG_INCOMP,
            Incompressible::MMG2 => &fluids::mmg2::MMG2_INCOMP,
            Incompressible::MNA => &fluids::mna::MNA_INCOMP,
            Incompressible::MNA2 => &fluids::mna2::MNA2_INCOMP,
            Incompressible::MPG => &fluids::mpg::MPG_INCOMP,
            Incompressible::MPG2 => &fluids::mpg2::MPG2_INCOMP,
            Incompressible::NBS => &fluids::nbs::NBS_INCOMP,
            Incompressible::NaK => &fluids::nak::NAK_INCOMP,
            Incompressible::PBB => &fluids::pbb::PBB_INCOMP,
            Incompressible::PCL => &fluids::pcl::PCL_INCOMP,
            Incompressible::PCR => &fluids::pcr::PCR_INCOMP,
            Incompressible::PGLT => &fluids::pglt::PGLT_INCOMP,
            Incompressible::PHE => &fluids::phe::PHE_INCOMP,
            Incompressible::PHR => &fluids::phr::PHR_INCOMP,
            Incompressible::PK2 => &fluids::pk2::PK2_INCOMP,
            Incompressible::PKL => &fluids::pkl::PKL_INCOMP,
            Incompressible::PLR => &fluids::plr::PLR_INCOMP,
            Incompressible::PMR => &fluids::pmr::PMR_INCOMP,
            Incompressible::PMS1 => &fluids::pms1::PMS1_INCOMP,
            Incompressible::PMS2 => &fluids::pms2::PMS2_INCOMP,
            Incompressible::PNF => &fluids::pnf::PNF_INCOMP,
            Incompressible::PNF2 => &fluids::pnf2::PNF2_INCOMP,
            Incompressible::S800 => &fluids::s800::S800_INCOMP,
            Incompressible::SAB => &fluids::sab::SAB_INCOMP,
            Incompressible::T66 => &fluids::t66::T66_INCOMP,
            Incompressible::T72 => &fluids::t72::T72_INCOMP,
            Incompressible::TCO => &fluids::tco::TCO_INCOMP,
            Incompressible::TD12 => &fluids::td12::TD12_INCOMP,
            Incompressible::TVP1 => &fluids::tvp1::TVP1_INCOMP,
            Incompressible::TVP1869 => &fluids::tvp1869::TVP1869_INCOMP,
            Incompressible::TX22 => &fluids::tx22::TX22_INCOMP,
            Incompressible::TY10 => &fluids::ty10::TY10_INCOMP,
            Incompressible::TY15 => &fluids::ty15::TY15_INCOMP,
            Incompressible::TY20 => &fluids::ty20::TY20_INCOMP,
            Incompressible::TY24 => &fluids::ty24::TY24_INCOMP,
            Incompressible::VCA => &fluids::vca::VCA_INCOMP,
            Incompressible::VKC => &fluids::vkc::VKC_INCOMP,
            Incompressible::VMA => &fluids::vma::VMA_INCOMP,
            Incompressible::VMG => &fluids::vmg::VMG_INCOMP,
            Incompressible::VNA => &fluids::vna::VNA_INCOMP,
            Incompressible::Water => &fluids::water::WATER_INCOMP,
            Incompressible::XLT => &fluids::xlt::XLT_INCOMP,
            Incompressible::XLT2 => &fluids::xlt2::XLT2_INCOMP,
            Incompressible::ZAC => &fluids::zac::ZAC_INCOMP,
            Incompressible::ZFC => &fluids::zfc::ZFC_INCOMP,
            Incompressible::ZLC => &fluids::zlc::ZLC_INCOMP,
            Incompressible::ZM => &fluids::zm::ZM_INCOMP,
            Incompressible::ZMC => &fluids::zmc::ZMC_INCOMP,
            Incompressible::ZS10 => &fluids::zs10::ZS10_INCOMP,
            Incompressible::ZS25 => &fluids::zs25::ZS25_INCOMP,
            Incompressible::ZS40 => &fluids::zs40::ZS40_INCOMP,
            Incompressible::ZS45 => &fluids::zs45::ZS45_INCOMP,
            Incompressible::ZS55 => &fluids::zs55::ZS55_INCOMP,
        }
    }
}
