// Reference driver: emits companion-matrix root-finding output from the
// `roots` crate 0.0.8, for PETIR's code-to-code comparison.
//
// Build and run:
//     cargo run --release > roots-0.0.8-reference.txt
//
// Coefficient convention on each `poly` line is DESCENDING with an explicit
// leading coefficient: c0 x^n + c1 x^(n-1) + ... + cn. The driver converts to
// the ascending implicit-monic form `find_roots_eigen` wants.
use roots::{find_roots_eigen, find_roots_sturm, SimpleConvergency};

fn eigen_desc(c: &[f64]) -> Vec<f64> {
    let first = match c.iter().position(|v| *v != 0.0) { Some(i) => i, None => return vec![] };
    let t = &c[first..];
    if t.len() < 2 { return vec![]; }
    let lead = t[0];
    let mut asc: Vec<f64> = t[1..].iter().map(|v| v / lead).collect();
    asc.reverse();
    find_roots_eigen(asc).into_iter().collect()
}

fn main() {
    println!("# roots 0.0.8 reference output for PETIR poly::companion");
    println!("# generated by reference-data/roots/roots_reference_driver.rs");
    println!("#");
    println!("# Each record is:");
    println!("#   poly <descending coefficients, explicit leading>");
    println!("#   eigen <root real parts, in the order find_roots_eigen returns them>");
    println!("#   sturm <what find_roots_sturm returns on the same polynomial>");
    println!("#");
    println!("# `sturm` is recorded to document the upstream defect PETIR");
    println!("# declines to port, not because PETIR implements it.");

    let mut cases: Vec<(String, Vec<f64>)> = Vec::new();
    // prod (x - k), k = 1..n, for n = 2..10
    for n in 2..=10usize {
        let mut c = vec![1.0f64];
        for k in 1..=n {
            let mut next = vec![0.0f64; c.len() + 1];
            for (i, &v) in c.iter().enumerate() { next[i] += v; next[i + 1] -= v * k as f64; }
            c = next;
        }
        cases.push((format!("prod_x_minus_k_n{n}"), c));
    }
    cases.push(("x3_minus_x".into(), vec![1.0, 0.0, -1.0, 0.0]));
    cases.push(("x4_plus_1".into(), vec![1.0, 0.0, 0.0, 0.0, 1.0]));
    cases.push(("double_roots".into(), vec![1.0, -9.0, 31.0, -51.0, 40.0, -12.0]));
    cases.push(("one_real_four_complex".into(), vec![1.0, -1.0, 1.0, -1.0, 1.0, -1.0]));
    cases.push(("scaled_quartic".into(), vec![2.0, -20.0, 70.0, -100.0, 48.0]));
    cases.push(("wilkinson_like_6".into(), vec![1.0, -3.0, -10.0, 24.0, 0.0, 0.0, 0.0]));

    for (name, c) in cases {
        println!("\ncase {name}");
        print!("poly");
        for v in &c { print!(" {v:.17e}"); }
        println!();

        let mut e = eigen_desc(&c);
        e.sort_by(|a, b| a.partial_cmp(b).unwrap());
        print!("eigen");
        for v in &e { print!(" {v:.17e}"); }
        println!();

        // sturm wants descending implicit-monic
        let first = c.iter().position(|v| *v != 0.0).unwrap_or(0);
        let t = &c[first..];
        let mut sv: Vec<f64> = vec![];
        if t.len() >= 2 {
            let monic: Vec<f64> = t[1..].iter().map(|v| v / t[0]).collect();
            let mut cv = SimpleConvergency { eps: 1e-12f64, max_iter: 100usize };
            sv = find_roots_sturm(&monic, &mut cv).iter().filter_map(|s| s.as_ref().ok().copied()).collect();
            sv.sort_by(|a, b| a.partial_cmp(b).unwrap());
        }
        print!("sturm");
        for v in &sv { print!(" {v:.17e}"); }
        println!();
    }
}
