#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# The exact CDF of the continuum cosine that OpenMC's CorrelatedAngleEnergy
# samples (law 61), for U-235 and U-238 MT=91 and MT=16 over the energies a
# fast system sees, for GitHub #365 audit. It is the distributional companion
# of correlated_angle_reference.py, which checks only moments. The moments are
# near zero below ~3 MeV, so they cannot see a shape error there.
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
#
# F(mu) = sum_l w_l sum_k [ (m_k - c_k) G_k(mu) + (c_k1 - m_k) G_k1(mu) ],
# m_k the bin's cdf midpoint (histogram E' tables: all on row k); G is the row's
# Tabular CDF (quadratic within a lin-lin bin). The E' sampling does not enter.
# Output rows: <nuclide>,<mt>,<E eV>,<mu>,<F(mu)>   on 101 mu points.
# Usage: openmc-env; python correlated_mu_cdf_reference.py <U235.ace> <U238.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

MU = np.linspace(-1.0, 1.0, 101)
CASES = {91: [0.6e6, 1.0e6, 1.5e6, 2.0e6, 3.0e6, 5.0e6, 8.0e6, 1.4e7],
         16: [8.0e6, 1.4e7]}


def row_cdf(t, mu):
    x, p, c = np.asarray(t.x), np.asarray(t.p), np.asarray(t.c)
    out = np.empty_like(mu)
    for j, m in enumerate(mu):
        if m <= x[0]:
            out[j] = 0.0
            continue
        if m >= x[-1]:
            out[j] = c[-1]
            continue
        k = int(np.searchsorted(x, m, side="right") - 1)
        d = m - x[k]
        if t.interpolation == "histogram":
            out[j] = c[k] + p[k] * d
        else:
            s = (p[k + 1] - p[k]) / (x[k + 1] - x[k])
            out[j] = c[k] + p[k] * d + 0.5 * s * d * d
    return out / c[-1]


def cdf(dist, e):
    g = np.asarray(dist.energy)
    i = int(np.clip(np.searchsorted(g, e, side="right") - 1, 0, len(g) - 2))
    r = float(np.clip((e - g[i]) / (g[i + 1] - g[i]), 0.0, 1.0))
    F = np.zeros_like(MU)
    for w, l in ((1 - r, i), (r, i + 1)):
        if w == 0:
            continue
        t = dist.energy_out[l]
        c = np.asarray(t.c)
        rows = [row_cdf(m, MU) for m in dist.mu[l]]
        hist = t.interpolation == "histogram"
        for k in range(len(c) - 1):
            lo, hi = c[k], c[k + 1]
            if hi <= lo:
                continue
            if hist:
                F += w * (hi - lo) * rows[k]
            else:
                mid = 0.5 * (lo + hi)
                F += w * ((mid - lo) * rows[k] + (hi - mid) * rows[k + 1])
    return F / F[-1]


def main(u235, u238, out):
    lines = []
    for name, f in (("U235", u235), ("U238", u238)):
        d = od.IncidentNeutron.from_ace(f)
        for mt, es in CASES.items():
            dist = d.reactions[mt].products[0].distribution[0]
            assert type(dist).__name__ == "CorrelatedAngleEnergy"
            for e in es:
                F = cdf(dist, e)
                lines += [f"{name},{mt},{e!r},{float(m)!r},{float(v)!r}" for m, v in zip(MU, F)]
    with open(out, "w") as fh:
        fh.write("# generated by correlated_mu_cdf_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
