#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# OpenMC's distribution of the energy after ONE elastic scatter off U-238 at
# 293.6 K, near the 6.67 / 20.9 / 36.7 eV resonances, with and without DBRC,
# for GitHub #407. Own work, GPL-3.0; OpenMC (MIT).
#
# A monoenergetic isotropic point source sits at the centre of a U-238 sphere so
# thin (optical radius <= 3e-3 at the resonance peak) that the escaping
# spectrum is the uncollided line plus single scatters (at most ~2 % of the
# collided neutrons have scattered twice); the surface current is
# tallied on an energy grid around E0. The uncollided line is removed by its
# bin. Library: the five-route NJOY2016 HDF5 (h5_njoy), which carries U-238's
# 0 K elastic from the same library's 0 K table.
# Output rows: <E0>,<dbrc 0/1>,<bin lo>,<bin hi>,<counts per source neutron>,<rel err>
# Usage: openmc-env; python dbrc_single_scatter_reference.py <cross_sections.xml> <workdir> <out.csv>

import sys, pathlib
import numpy as np
import openmc

T = 293.6
CASES = [(6.4, 1.0e-2), (20.5, 2.0e-3), (36.4, 1.0e-4)]   # (E0 eV, radius cm)
NB = 60


def run(xs, wd, e0, r, dbrc):
    m = openmc.Material(); m.add_nuclide("U238", 1.0); m.set_density("g/cm3", 19.05)
    m.temperature = T
    mats = openmc.Materials([m]); mats.cross_sections = xs
    s = openmc.Sphere(r=r, boundary_type="vacuum")
    geo = openmc.Geometry([openmc.Cell(fill=m, region=-s)])
    st = openmc.Settings(); st.run_mode = "fixed source"; st.batches = 20; st.particles = 2_000_000
    st.source = openmc.IndependentSource(space=openmc.stats.Point(), energy=openmc.stats.Discrete([e0], [1.0]),
                                         angle=openmc.stats.Isotropic())
    st.temperature = {"default": T, "method": "nearest", "tolerance": 10.0}
    st.resonance_scattering = {"enable": dbrc, "method": "dbrc", "energy_min": 1.0e-5, "energy_max": 1000.0}
    st.output = {"summary": False}
    lo, hi = e0 * (1 - 0.03), e0 * (1 + 0.012)
    edges = np.linspace(lo, hi, NB + 1)
    t = openmc.Tally(); t.filters = [openmc.SurfaceFilter(s), openmc.EnergyFilter(edges)]; t.scores = ["current"]
    model = openmc.Model(geo, mats, st, openmc.Tallies([t]))
    d = pathlib.Path(wd) / f"e{e0}_d{int(dbrc)}"; d.mkdir(parents=True, exist_ok=True)
    sp = model.run(cwd=d, threads=4, output=False)
    with openmc.StatePoint(sp) as p:
        tt = p.tallies[t.id]
        return edges, tt.mean.ravel(), tt.std_dev.ravel()


def main(xs, wd, out):
    rows = []
    for e0, r in CASES:
        for dbrc in (True, False):
            edges, mean, sd = run(xs, wd, e0, r, dbrc)
            for k in range(NB):
                rows.append(f"{e0!r},{int(dbrc)},{float(edges[k])!r},{float(edges[k+1])!r},{float(mean[k])!r},{float(sd[k]/mean[k]) if mean[k]>0 else 0.0!r}")
            print(e0, dbrc, "scattered fraction in window", mean.sum())
    open(out, "w").write("# generated by dbrc_single_scatter_reference.py, openmc " + openmc.__version__ + "\n" + "\n".join(rows) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
