#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# An ACE LAW=4 table WITH DISCRETE LINES (INTT = 10*ND + LEP), constructed from
# NJOY2016 Li-7 (ENDF/B-VIII.0, MT=16), and the exact mean of OpenMC's
# ContinuousTabular sampling of it, for GitHub #365 audit.
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
#
# No neutron evaluation in ENDF/B-VIII.0 has discrete lines on an MF=6 LAW=1
# neutron subsection (scanned: 2377 subsections in 557 tapes), so no NJOY-built
# table has one. This converts the FIRST outgoing point of every MT=16 table
# into a line: INTT += 10, and the point's cdf and "pdf" (a line's
# probability) are both set to the table's cdf at the next point, i.e. the mass
# of the first panel is moved onto a line at its lower edge. The table stays a
# normalised distribution; the physics is artificial, the FORMAT is ACE's.
#
# Exact mean of OpenMC's scheme (src/distribution_energy.cpp
# ContinuousTabular::sample) at E_in: table i or i+1 with probability 1-r, r;
# in table l a line is emitted with probability c_l[0] at x_l[0], UNSCALED; the
# continuum (from x_l[1]) is scaled into [E_1, E_K] with
# E_1 = x_i[1] + r (x_i1[1] - x_i[1]) (upstream's e_out[n_discrete]).
# Output rows: <E eV>,<mean E'>
# Usage: openmc-env; python discrete_lines_reference.py <Li7 tape24> <out.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od
import openmc.data.ace as A

ENERGIES = [9.0e6, 1.2e7, 1.4e7, 1.73e7, 1.95e7]


def main(src, out_ace, out_csv):
    t = A.get_table(src)
    x = t.xss  # 1-based (x[0] = 0 padding)
    nr = int(t.nxs[5])
    mtr = [int(v) for v in x[t.jxs[3]:t.jxs[3] + int(t.nxs[4])]]
    i16 = mtr.index(16)
    assert i16 < nr
    ldlw, dlw = t.jxs[10], t.jxs[11]
    loc = int(x[ldlw + i16])
    assert int(x[dlw + loc - 1 + 1]) == 4, "MT=16 must be LAW=4"
    idat = int(x[dlw + loc - 1 + 2])
    at = dlw + idat - 1
    nreg = int(x[at]); at += 1 + 2 * nreg
    ne = int(x[at]); at += 1
    locs = [int(v) for v in x[at + ne:at + 2 * ne]]
    xss = list(t.xss[1:])
    for L in locs:
        d = dlw + L - 1            # 1-based index of INTT
        intt = int(x[d]); n = int(x[d + 1])
        assert intt in (1, 2)
        c1 = x[d + 2 + 2 * n + 1]   # cdf at the second point
        xss[d - 1] = float(10 + intt)
        xss[d + 2 + n - 1] = c1      # line "pdf" = its probability
        xss[d + 2 + 2 * n - 1] = c1  # cdf at the line
    lines = open(src).read().splitlines()
    with open(out_ace, "w") as f:
        f.write("\n".join(lines[:12]) + "\n")
        for k in range(0, len(xss), 4):
            f.write("".join(f"{v:20.11E}" for v in xss[k:k + 4]) + "\n")

    d = od.IncidentNeutron.from_ace(out_ace)
    ct = d.reactions[16].products[0].distribution[0].energy
    assert type(ct).__name__ == "ContinuousTabular"
    assert type(ct.energy_out[0]).__name__ == "Mixture", "OpenMC must see the lines"
    t2 = A.get_table(out_ace)
    y = t2.xss
    raw = []
    for L in locs:
        dd = dlw + L - 1
        n = int(y[dd + 1])
        raw.append((int(y[dd]) % 10, np.asarray(y[dd + 2:dd + 2 + n]) * 1e6,
                    np.asarray(y[dd + 2 + n:dd + 2 + 2 * n]) / 1e6, np.asarray(y[dd + 2 + 2 * n:dd + 2 + 3 * n])))
    g = np.asarray(ct.energy)
    rows = []
    for e in ENERGIES:
        i = int(np.clip(np.searchsorted(g, e, side="right") - 1, 0, len(g) - 2))
        r = float(np.clip((e - g[i]) / (g[i + 1] - g[i]), 0.0, 1.0))
        (ia, xa, pa, ca), (ib, xb, pb, cb) = raw[i], raw[i + 1]
        e1 = xa[1] + r * (xb[1] - xa[1])
        ek = xa[-1] + r * (xb[-1] - xa[-1])
        mean = 0.0
        for w, (intt, xs, ps, cs) in ((1 - r, raw[i]), (r, raw[i + 1])):
            if w == 0:
                continue
            m = cs[0] * xs[0]                      # the line, unscaled
            xc, pc, cc = xs[1:], ps[1:], cs[1:]
            h = np.diff(xc)
            if intt == 1:
                seg = pc[:-1] * h * 0.5 * (xc[1:] + xc[:-1])
                mass = pc[:-1] * h
            else:
                seg = h * (xc[:-1] * (2 * pc[:-1] + pc[1:]) + xc[1:] * (pc[:-1] + 2 * pc[1:])) / 6
                mass = h * (pc[:-1] + pc[1:]) / 2
            # continuum raw mean -> scaled: E_1 + (E - x1)(E_K - E_1)/(xK - x1)
            cont_mass = mass.sum()
            cont_mean_raw = seg.sum() / cont_mass
            scaled = e1 + (cont_mean_raw - xc[0]) * (ek - e1) / (xc[-1] - xc[0])
            m += (1 - cs[0]) * scaled
            mean += w * m
        rows.append(f"{e!r},{float(mean)!r}")
        print(e, "<E'>", mean)
    with open(out_csv, "w") as f:
        f.write("# generated by discrete_lines_reference.py, openmc " + openmc.__version__ + "\n")
        f.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
