#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Reference CDF of the F-19 MT=16 (n,2n) secondary-neutron energy, from
# OpenMC's own ACE reader, for GitHub #365 (outram-mc ACE LNW mixture).
#
# Own work (outram-park-backend), GPL-3.0. Uses the OpenMC Python API
# (MIT licence) as a library only; no OpenMC source is copied.
#
# What it computes
# ----------------
# `openmc.data.IncidentNeutron.from_ace` decodes the table independently of
# outram-mc. MT=16's neutron product is a list of distributions plus an
# applicability p_k(E) per distribution (the ACE LNW chain). For each incident
# energy E this writes the exact CDF of E' that OpenMC's C++ sampler produces:
#
#   F(x | E) = sum_k p_k(E) * [ (1 - r) F_{k,i}(y_i(x)) + r F_{k,i+1}(y_{i+1}(x)) ]
#
# where i, r come from `get_energy_index` (lin-lin in E, `src/secondary_correlated.cpp`),
# F_{k,l} is table l's tabulated CDF (histogram tables => piecewise-linear CDF),
# and y_l(x) inverts OpenMC's envelope scaling
#   x = E_1 + (y - E_{l,1}) (E_K - E_1) / (E_{l,K} - E_{l,1}),
#   E_1 = E_{i,1} + r (E_{i+1,1} - E_{i,1}),  E_K likewise.
# p_k(E) is evaluated with OpenMC's `Tabulated1D` (clamped, region-aware), and
# the p_k are used unnormalised exactly as `ReactionProduct::sample_dist` does.
# Every table here is histogram with no discrete lines (asserted), so F is
# piecewise linear in x between the union of all scaled knots: the CSV lists
# every such knot, so linear interpolation of it is exact.
#
# Usage:  openmc-env; python f19_mt16_reference_cdf.py <F19.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

ENERGIES = [14.0e6, 16.25e6, 18.0e6]


def table_cdf_on(x, dist, e_in):
    """CDF of E' at incident e_in for one CorrelatedAngleEnergy, on grid x."""
    egrid = np.asarray(dist.energy)
    i = int(np.searchsorted(egrid, e_in, side="right") - 1)
    i = min(max(i, 0), len(egrid) - 2)
    r = (e_in - egrid[i]) / (egrid[i + 1] - egrid[i])
    eo_i, eo_j = dist.energy_out[i], dist.energy_out[i + 1]
    for eo in (eo_i, eo_j):
        assert eo.interpolation == "histogram", eo.interpolation
        assert getattr(eo, "_n_discrete", 0) == 0
    e_1 = eo_i.x[0] + r * (eo_j.x[0] - eo_i.x[0])
    e_k = eo_i.x[-1] + r * (eo_j.x[-1] - eo_i.x[-1])
    out = np.zeros_like(x)
    knots = []
    for w, eo in ((1.0 - r, eo_i), (r, eo_j)):
        if w == 0.0:
            continue
        ex, c = np.asarray(eo.x), np.asarray(eo.c)
        # scaled position of every raw knot
        scaled = e_1 + (ex - ex[0]) * (e_k - e_1) / (ex[-1] - ex[0])
        knots.append(scaled)
        out += w * np.interp(x, scaled, c, left=0.0, right=c[-1])
    return out, np.concatenate(knots)


def main(ace_path, out_path):
    t = od.IncidentNeutron.from_ace(ace_path)
    prod = t.reactions[16].products[0]
    assert len(prod.distribution) == len(prod.applicability) >= 2
    rows = []
    for e in ENERGIES:
        p = [float(a(e)) for a in prod.applicability]
        # union of all scaled knots first, then the CDF on it
        knots = np.concatenate(
            [table_cdf_on(np.array([0.0]), d, e)[1] for d in prod.distribution])
        x = np.unique(knots)
        cdf = np.zeros_like(x)
        for pk, d in zip(p, prod.distribution):
            cdf += pk * table_cdf_on(x, d, e)[0]
        # mean of a piecewise-linear CDF: sum over segments of midpoint * dF
        mean = float(np.sum(0.5 * (x[1:] + x[:-1]) * np.diff(cdf)))
        print(f"E = {e/1e6:6.3f} MeV  p = {p}  knots = {len(x)}  "
              f"F_max = {cdf[-1]:.9f}  <E'> = {mean/1e6:.6f} MeV")
        for xi, ci in zip(x, cdf):
            rows.append((e, xi, ci))
    with open(out_path, "w") as f:
        f.write("# F-19 MT=16 E' CDF under OpenMC's sampling of " + ace_path + "\n")
        f.write("# generated by f19_mt16_reference_cdf.py, openmc " + openmc.__version__ + "\n")
        f.write("e_in_ev,e_out_ev,cdf\n")
        for e, xi, ci in rows:
            f.write(f"{e:.10e},{xi:.10e},{ci:.12e}\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
