#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Exact means of OpenMC's sampling of an ACE LAW=4 continuum with its AND
# cosine (UncorrelatedAngleEnergy), for GitHub #365 audit: outram used to drop
# the AND cosine of a LAW=4 continuum on MT=91/16/17.
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
# Tables: NJOY2016 ACE of Li-7 (ENDF/B-VIII.0) and U-238 (JENDL-3.3), built by
# openmc_godiva_cross_code/make_ace.sh (decks there).
#
# <E'>: ContinuousTabular sampling (src/distribution_energy.cpp): table i or
#       i+1 with probability 1-r / r (r lin-lin in E), then envelope scaling;
#       the mean of that scheme is exact from each table's own mean.
# <mu>: AngleDistribution::sample (src/distribution_angle.cpp): table i or i+1
#       with probability 1-r / r, then the tabular cosine law; mean exact.
# Output rows: <file>,<mt>,<E eV>,<mean E' eV>,<mean mu>
# Usage: openmc-env; python law4_continuum_reference.py <ace_extra dir> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

CASES = [("Li7/tape24", 16, [1.0e7, 1.4e7, 1.8e7]),
         ("U238J33/tape24", 91, [2.0e6, 5.0e6, 1.4e7])]


def tab_mean(x, p, interp):
    x, p = np.asarray(x, float), np.asarray(p, float)
    h = np.diff(x)
    if interp == "histogram":
        return float(np.sum(0.5 * (x[1:] + x[:-1]) * p[:-1] * h) / np.sum(p[:-1] * h))
    m1 = np.sum(h * (x[:-1] * (2 * p[:-1] + p[1:]) + x[1:] * (p[:-1] + 2 * p[1:])) / 6.0)
    return float(m1 / np.sum(h * (p[:-1] + p[1:]) / 2.0))


def bracket(grid, e):
    g = np.asarray(grid)
    i = int(np.clip(np.searchsorted(g, e, side="right") - 1, 0, len(g) - 2))
    return i, float(np.clip((e - g[i]) / (g[i + 1] - g[i]), 0.0, 1.0))


def e_mean(ct, e):
    i, r = bracket(ct.energy, e)
    a, b = ct.energy_out[i], ct.energy_out[i + 1]
    e1 = a.x[0] + r * (b.x[0] - a.x[0])
    ek = a.x[-1] + r * (b.x[-1] - a.x[-1])
    out = 0.0
    for w, t in ((1 - r, a), (r, b)):
        if w > 0:
            m = tab_mean(t.x, t.p, t.interpolation)
            out += w * (e1 + (m - t.x[0]) * (ek - e1) / (t.x[-1] - t.x[0]))
    return out


def mu_mean(ang, e):
    i, r = bracket(ang.energy, e)
    out = 0.0
    for w, m in ((1 - r, ang.mu[i]), (r, ang.mu[i + 1])):
        if w > 0:
            out += w * (0.0 if type(m).__name__ == "Uniform" else tab_mean(m.x, m.p, m.interpolation))
    return out


def main(d, out):
    rows = []
    for f, mt, es in CASES:
        data = od.IncidentNeutron.from_ace(f"{d}/{f}")
        rx = data.reactions[mt]
        assert not rx.center_of_mass
        dist = rx.products[0].distribution[0]
        assert type(dist).__name__ == "UncorrelatedAngleEnergy"
        for e in es:
            me, mm = e_mean(dist.energy, e), mu_mean(dist.angle, e)
            rows.append(f"{f},{mt},{float(e)!r},{float(me)!r},{float(mm)!r}")
            print(f, mt, e, "<E'>", me, "<mu>", mm)
    with open(out, "w") as fh:
        fh.write("# generated by law4_continuum_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
