#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# MT=5 (n,anything) neutron multiplicity y(E) as OpenMC reads it from an ACE
# table (|TY| > 100 energy-dependent yield, openmc/data/reaction.py:1059-1062),
# the reference for outram-mc's ACE route (GitHub #365 audit).
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
# Output rows: <nuclide>,<E eV>,<y>
# Usage: openmc-env; python mt5_yield_reference.py <ace dir> <out.csv>

import glob
import os
import sys

import openmc
import openmc.data as od

ENERGIES = [6.0e6, 1.0e7, 1.2e7, 1.4e7, 1.7e7, 2.0e7]


def main(d, out):
    rows = []
    for f in sorted(glob.glob(os.path.join(d, "*.ace"))):
        name = os.path.basename(f)[:-4]
        try:
            data = od.IncidentNeutron.from_ace(f)
        except Exception as exc:  # thermal or binary tables
            print("skip", name, exc)
            continue
        if 5 not in data.reactions:
            continue
        rx = data.reactions[5]
        neutron = [p for p in rx.products if p.particle == "neutron"][0]
        y = neutron.yield_
        for e in ENERGIES:
            rows.append(f"{name},{e!r},{float(y(e))!r}")
        print(name, type(y).__name__, [round(float(y(e)), 5) for e in ENERGIES])
    with open(out, "w") as fh:
        fh.write("# generated by mt5_yield_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("nuclide,e_ev,yield\n" + "\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
