#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Build an ACE table whose fission nu-bar is a POLYNOMIAL (NU block LNU = 1),
# from NJOY2016's U-235 table, and record OpenMC's reading of it, for GitHub
# #365 audit (outram used to tabulate the polynomial on 1e-5 eV - 20 MeV and
# read it lin-lin and clamped).
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
#
# The new NU block is appended to XSS and JXS(2) pointed at it; JXS(24) (DNU)
# is set to 0 so the single block is TOTAL nu (openmc reaction.py:257). The
# coefficients are a quadratic in MeV, chosen to be visibly non-linear:
#   nu(E) = 2.4355 + 0.0650 E + 0.0020 E^2   (E in MeV)
# Output: <out.ace> and <out.csv> rows <E eV>,<nu_total per OpenMC>.
# Usage: openmc-env; python nu_polynomial_reference.py <U235.ace> <out.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od
import openmc.data.ace as A

COEF = [2.4355, 0.0650, 0.0020]
ENERGIES = [1.0e-7, 1.0e-5, 0.0253, 1.0e3, 1.37e6, 5.5e6, 1.9e7, 2.0e7, 3.0e7, 1.5e8]


def main(src, out_ace, out_csv):
    lines = open(src).read().splitlines()
    t = A.get_table(src)
    xss = list(t.xss[1:])
    loc = len(xss) + 1                      # 1-based locator of the new block
    xss += [1.0, float(len(COEF))] + COEF   # LNU = 1, NC, coefficients
    nxs = [int(v) for v in t.nxs[1:17]]
    jxs = [int(v) for v in t.jxs[1:33]]
    nxs[0] = len(xss)
    jxs[1] = loc
    jxs[23] = 0
    ints = nxs + jxs
    with open(out_ace, "w") as f:
        f.write("\n".join(lines[:6]) + "\n")
        for r in range(6):
            f.write("".join(f"{v:9d}" for v in ints[8 * r:8 * r + 8]) + "\n")
        for k in range(0, len(xss), 4):
            f.write("".join(f"{v:20.11E}" for v in xss[k:k + 4]) + "\n")
    d = od.IncidentNeutron.from_ace(out_ace)
    tot = [p for p in d.reactions[18].products if p.emission_mode == "total"][0]
    assert type(tot.yield_).__name__ == "Polynomial"
    with open(out_csv, "w") as f:
        f.write("# generated by nu_polynomial_reference.py, openmc " + openmc.__version__ + "\n")
        for e in ENERGIES:
            v = float(tot.yield_(e))
            f.write(f"{e!r},{v!r}\n")
            print(e, v)


if __name__ == "__main__":
    main(*sys.argv[1:4])
