#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# OpenMC's view of the "other" neutron-emitting reactions -- every
# non-redundant reaction with a neutron product other than elastic, the
# levels/continuum MT=51..91, (n,2n), (n,3n), MT=5 and fission -- for GitHub
# #365 audit (outram used to sample them as elastic).
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
# Rows:  <route>,<nuclide>,<mt>,<E eV>,<sigma b>,<neutron yield>,<cm 0/1>
#   route "ace": IncidentNeutron.from_ace of the NJOY2016 table;
#   route "endf": IncidentNeutron.from_endf of the evaluation (independent of
#   NJOY), at 294 K interpolation is not needed for these threshold reactions
#   (sigma rows are ACE-route only; the ENDF rows carry sigma = nan).
# Usage: openmc-env; python other_channels_reference.py <out.csv>

import math
import sys
import openmc
import openmc.data as od

ACE = {
    "O16": "target/five_route_keff/njoy/293.6K/O16.ace",
    "F19": "target/five_route_keff/njoy/293.6K/F19.ace",
    "Al27": "target/five_route_keff/njoy/293.6K/Al27.ace",
    "Si28": "target/five_route_keff/njoy/293.6K/Si28.ace",
    "Mn55": "target/five_route_keff/njoy/293.6K/Mn55.ace",
    "U234": "target/five_route_keff/njoy/293.6K/U234.ace",
    "Li7": "target/ace_extra/Li7/tape24",
}
ENDF = {
    "O16": "reference-data/endf/n-008_O_016-ENDF8.0.endf",
    "F19": "reference-data/endf/n-009_F_019-ENDF8.0.endf",
    "Li7": "reference-data/endf/n-003_Li_007-ENDF8.0.endf",
}
OWN = {2, 4, 5, 16, 17, 18, 19, 20, 21, 38} | set(range(50, 92))
ENERGIES = [1.4e7, 1.9e7]


def other(data):
    out = []
    for mt, rx in sorted(data.reactions.items()):
        if rx.redundant or mt in OWN or 102 <= mt <= 117 or 600 <= mt <= 849 or mt >= 200:
            continue
        neut = [p for p in rx.products if p.particle == "neutron"]
        if not neut:
            continue
        out.append((mt, rx, neut[0]))
    return out


def main(out):
    rows = []
    for name, path in ACE.items():
        d = od.IncidentNeutron.from_ace(path)
        T = list(d.energy)[0]
        for mt, rx, p in other(d):
            for e in ENERGIES:
                rows.append(f"ace,{name},{mt},{e!r},{float(rx.xs[T](e))!r},{float(p.yield_(e))!r},{int(rx.center_of_mass)}")
        print("ace", name, [m for m, _, _ in other(d)])
    for name, path in ENDF.items():
        d = od.IncidentNeutron.from_endf(path)
        for mt, rx, p in other(d):
            for e in ENERGIES:
                rows.append(f"endf,{name},{mt},{e!r},nan,{float(p.yield_(e))!r},{int(rx.center_of_mass)}")
        print("endf", name, [m for m, _, _ in other(d)])
    with open(out, "w") as f:
        f.write("# generated by other_channels_reference.py, openmc " + openmc.__version__ + "\n")
        f.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
