#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Exact moments and the exact outgoing-energy CDF of OpenMC's sampling of an
# ACE IFENG = 0 (equiprobable) S(a,b) law, IncoherentInelasticAEDiscrete with
# skewed_ = false (openmc src/secondary_thermal.cpp, d7d3284a1), for GitHub
# #407: outram's default for this form is now OpenMC's scheme.
# Own work, GPL-3.0; OpenMC Python API (MIT) as a library.
#
# OpenMC: i, f from get_energy_index; j = floor(prn n) (every bin 1/n); E' =
# (1-f) E(i,j) + f E(i+1,j); k = floor(prn m); mu = (1-f) mu(i,j,k) +
# f mu(i+1,j,k). So E' takes n discrete values, each with probability 1/n,
# and (E', mu) takes n m values, each 1/(n m). Moments are exact sums. The CDF
# of E' is written at each of its n support points.
# Output (moments): M,<table>,<E eV>,<E'>,<E'^2>,<mu>,<mu^2>,<E' mu>
#        (CDF):     C,<table>,<E eV>,<x>,<F(x)>
# Usage: openmc-env; python thermal_equiprobable_reference.py <H2O ace> <graphite ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

ENERGIES = {"HinH2O": [0.002, 0.0253, 0.1, 0.4, 1.0, 3.0],
            "Cgraph": [0.005, 0.0253, 0.1, 0.5, 1.5]}


def rows_for(name, path):
    th = od.ThermalScattering.from_ace(path)
    d = list(th.inelastic.distribution.values())[0]
    assert type(d).__name__ == "IncoherentInelasticAEDiscrete" and not d.skewed
    grid = np.asarray(list(th.inelastic.xs.values())[0].x)
    eo = np.asarray(d.energy_out)
    mu = np.asarray(d.mu_out)
    out = []
    for e in ENERGIES[name]:
        assert e < grid[-1]
        i, f = 0, 0.0
        if e >= grid[0]:
            i = int(np.searchsorted(grid, e, side="right") - 1)
            if i + 1 < len(grid):
                f = (e - grid[i]) / (grid[i + 1] - grid[i])
        E = (1 - f) * eo[i] + f * eo[i + 1]            # (n,)
        M = (1 - f) * mu[i] + f * mu[i + 1]            # (n, m)
        m1 = [E.mean(), (E * E).mean(), M.mean(), (M * M).mean(), (E[:, None] * M).mean()]
        out.append("M," + name + "," + ",".join(repr(float(v)) for v in [e] + m1))
        xs = np.sort(E)
        for x in np.unique(xs):
            out.append(f"C,{name},{e!r},{float(x)!r},{float(np.mean(xs <= x))!r}")
        print(name, e, "<E'>", m1[0], "<mu>", m1[2])
    return out


def main(h2o, cg, out):
    rows = rows_for("HinH2O", h2o) + rows_for("Cgraph", cg)
    with open(out, "w") as fh:
        fh.write("# generated by thermal_equiprobable_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
