#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Build a MIXED-elastic (IDPNC = 5) thermal ACE table and record OpenMC's
# reading and sampling moments of it, for GitHub #365 audit.
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
#
# No ENDF/B-VIII.0 thermal evaluation is LTHR = 3 (scanned: 34 TSL tapes, all
# LTHR 1 or 2 or no elastic), so NJOY cannot produce one from held data. This
# script CONSTRUCTS a format-exact one from two NJOY2016 tables:
#   - the coherent part and the inelastic data from C in crystalline graphite
#     (IDPNC = 4, ITCE/ITCX), unchanged;
#   - the incoherent-elastic block (energies, sigma, cosines) of H in ZrH
#     (IDPNC = 3), appended to XSS as ITCEI/ITCXI/ITCAI, NXS(8) = NCL(ZrH).
# The physics is artificial; the FORMAT is ACE's mixed-elastic layout, which is
# what the reader and sampler under test must handle. OpenMC reads it through
# ThermalScattering.from_ace (thermal.py:897-942).
#
# Moments of OpenMC's sampling (exact sums, no random numbers):
#   w_c = sigma_coh/(sigma_coh + sigma_inc)          (MixedElasticAE::sample_dist)
#   coherent: edge k below E with prob (S_k - S_k-1)/S_i, mu = 1 - 2 E_k/E
#   incoherent: IncoherentElasticAEDiscrete (interpolated + smeared cosines),
#     <mu> = mean_k mu_k,  <mu^2> = mean_k (mu_k^2 + d_k^2/12)
# Output rows: <E eV>,<sigma_el b>,<mean mu>,<mean mu^2>
# Usage: openmc-env; python thermal_mixed_elastic_reference.py <graphite tape30> <zrh tape30> <out.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od
import openmc.data.ace as A

ENERGIES = [0.003, 0.0253, 0.1, 0.5, 1.5, 3.5]


def write(src_lines, nxs, jxs, xss, out):
    ints = list(nxs) + list(jxs)
    with open(out, "w") as f:
        f.write("\n".join(src_lines[:6]) + "\n")
        for r in range(6):
            f.write("".join(f"{v:9d}" for v in ints[8 * r:8 * r + 8]) + "\n")
        for k in range(0, len(xss), 4):
            f.write("".join(f"{v:20.11E}" for v in xss[k:k + 4]) + "\n")


def main(gph, zrh, out_ace, out_csv):
    g = A.get_table(gph)
    z = A.get_table(zrh)
    xss = list(g.xss[1:])
    nxs = [int(v) for v in g.nxs[1:17]]
    jxs = [int(v) for v in g.jxs[1:33]]
    # the incoherent block from ZrH
    i0 = z.jxs[4]
    n = int(z.xss[i0])
    e = list(z.xss[i0 + 1:i0 + 1 + n])
    s = list(z.xss[i0 + 1 + n:i0 + 1 + 2 * n])
    nmu = int(z.nxs[6]) + 1
    a0 = z.jxs[6]
    mu = list(z.xss[a0:a0 + n * nmu])
    loc = len(xss) + 1
    xss += [float(n)] + e + s
    jxs[6] = loc                 # JXS(7) ITCEI
    jxs[7] = loc + 1 + n         # JXS(8) ITCXI
    jxs[8] = len(xss) + 1        # JXS(9) ITCAI
    xss += mu
    nxs[0] = len(xss)
    nxs[4] = 5                   # NXS(5) IDPNC = 5
    nxs[7] = nmu - 1             # NXS(8) NCLI
    write(open(gph).read().splitlines(), nxs, jxs, xss, out_ace)

    th = od.ThermalScattering.from_ace(out_ace)
    dist = list(th.elastic.distribution.values())[0]
    xsum = list(th.elastic.xs.values())[0]
    assert type(dist).__name__ == "MixedElasticAE"
    coh_xs, inc_xs = xsum.functions
    bragg = np.asarray(coh_xs.bragg_edges)
    fac = np.asarray(coh_xs.factors)
    inc = dist.incoherent
    grid = np.asarray(inc_xs.x)
    mo = np.asarray(inc.mu_out)
    rows = []
    for E in ENERGIES:
        sc, si = float(coh_xs(E)), float(inc_xs(E))
        # coherent moments
        ib = int(np.searchsorted(bragg, E, side="right")) - 1
        if ib >= 0 and sc > 0:
            p = np.diff(np.concatenate([[0.0], fac[:ib + 1]])) / fac[ib]
            m = 1 - 2 * bragg[:ib + 1] / E
            c1, c2 = float(p @ m), float(p @ (m * m))
        else:
            c1 = c2 = 0.0
        # incoherent moments
        i, f = 0, 0.0
        if E >= grid[0]:
            i = int(np.searchsorted(grid, E, side="right") - 1)
            if i + 1 < len(grid):
                f = (E - grid[i]) / (grid[i + 1] - grid[i])
        i1 = min(i + 1, len(grid) - 1)
        mk = mo[i] + f * (mo[i1] - mo[i])
        left = np.concatenate([[-1 - (mk[0] + 1)], mk[:-1]])
        right = np.concatenate([mk[1:], [1 + (1 - mk[-1])]])
        dk = np.minimum(mk - left, right - mk)
        n1, n2 = float(mk.mean()), float((mk * mk + dk * dk / 12).mean())
        w = sc / (sc + si)
        rows.append(",".join(repr(float(v)) for v in (E, sc + si, w * c1 + (1 - w) * n1, w * c2 + (1 - w) * n2)))
        print(E, "sigma", sc + si, "w_coh", w)
    with open(out_csv, "w") as fh:
        fh.write("# generated by thermal_mixed_elastic_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:5])
