#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Exact moments of OpenMC's sampling of an ACE IFENG = 1 (skewed) S(a,b) law,
# IncoherentInelasticAEDiscrete (openmc src/secondary_thermal.cpp), for GitHub
# #365 audit. Own work, GPL-3.0; OpenMC Python API (MIT) as a library.
#
# Bin j is chosen with upstream's skewed weights: r = xi (n-3); j = floor(r)+1
# for r > 1 (each middle bin probability 1/(n-3)), n-2 for 0.6<r<=1 (0.4/(n-3)),
# n-1 for 0.5<r<=0.6 (0.1/(n-3)), 1 for 0.1<r<=0.5 (0.4/(n-3)), 0 for r<=0.1
# (0.1/(n-3)). E' and mu are interpolated between tables i, i+1 with f from
# get_energy_index. All moments are exact sums.
# Output rows: <E eV>,<mean E'>,<mean E'^2>,<mean mu>
# Usage: openmc-env; python thermal_skewed_reference.py <tape30> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

ENERGIES = [0.005, 0.0253, 0.1, 0.4, 1.0, 2.5]


def main(path, out):
    th = od.ThermalScattering.from_ace(path)
    d = list(th.inelastic.distribution.values())[0]
    assert type(d).__name__ == "IncoherentInelasticAEDiscrete" and d.skewed
    grid = np.asarray(list(th.inelastic.xs.values())[0].x)
    eo = np.asarray(d.energy_out)       # (n_e, n)
    mu = np.asarray(d.mu_out)           # (n_e, n, m)
    n = eo.shape[1]
    w = np.full(n, 1.0)
    w[0] = w[n - 1] = 0.1
    w[1] = w[n - 2] = 0.4
    w /= (n - 3)
    assert abs(w.sum() - 1.0) < 1e-12
    rows = []
    for e in ENERGIES:
        i, f = 0, 0.0
        if e >= grid[0]:
            i = int(np.searchsorted(grid, e, side="right") - 1)
            if i + 1 < len(grid):
                f = (e - grid[i]) / (grid[i + 1] - grid[i])
        E = (1 - f) * eo[i] + f * eo[i + 1]
        M = ((1 - f) * mu[i] + f * mu[i + 1]).mean(axis=1)
        rows.append(",".join(repr(float(v)) for v in (e, w @ E, w @ (E * E), w @ M)))
        print(e, "<E'>", w @ E, "<mu>", w @ M)
    with open(out, "w") as fh:
        fh.write("# generated by thermal_skewed_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
