#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Exact <mu> and <mu^2> of OpenMC's IncoherentElasticAEDiscrete::sample
# (openmc src/secondary_thermal.cpp) on an ACE incoherent-elastic S(a,b)
# table (IDPNC = 3), for GitHub #365 audit. Own work, GPL-3.0; OpenMC Python
# API (MIT) as a library.
#
# mu_k = mu(i,k) + f (mu(i+1,k) - mu(i,k)); smear s = d_k (u - 1/2),
# d_k = min(mu_k - left_k, right_k - mu_k), left/right the interpolated
# neighbours (reflected at +-1 for the end cosines). Then
#   <mu>   = mean_k mu_k                       (the smear is zero-mean)
#   <mu^2> = mean_k (mu_k^2 + d_k^2 / 12)
# Output rows: <E eV>,<mean mu>,<mean mu^2>
# Usage: openmc-env; python thermal_incoherent_elastic_reference.py <tape30> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

ENERGIES = [0.001, 0.0253, 0.1, 0.5, 1.5, 3.9]


def main(path, out):
    th = od.ThermalScattering.from_ace(path)
    xs = list(th.elastic.xs.values())[0]
    d = list(th.elastic.distribution.values())[0]
    assert type(d).__name__ == "IncoherentElasticAEDiscrete"
    grid = np.asarray(xs.x)
    mu_out = np.asarray(d.mu_out)
    n = mu_out.shape[1]
    rows = []
    for e in ENERGIES:
        i, f = 0, 0.0
        if e >= grid[0]:
            i = int(np.searchsorted(grid, e, side="right") - 1)
            if i + 1 < len(grid):
                f = (e - grid[i]) / (grid[i + 1] - grid[i])
        i1 = min(i + 1, len(grid) - 1)
        m = mu_out[i] + f * (mu_out[i1] - mu_out[i])
        left = np.concatenate([[-1.0 - (m[0] + 1.0)], m[:-1]])
        right = np.concatenate([m[1:], [1.0 + (1.0 - m[-1])]])
        dk = np.minimum(m - left, right - m)
        rows.append(",".join(repr(float(v)) for v in (e, m.mean(), (m * m + dk * dk / 12).mean())))
        print(e, "<mu>", m.mean())
    with open(out, "w") as fh:
        fh.write("# generated by thermal_incoherent_elastic_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
