#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# Exact moments of OpenMC's sampling of an ACE IFENG = 2 (continuous)
# incoherent-inelastic S(a,b) law, for GitHub #365 audit.
#
# Own work (outram-park-backend), GPL-3.0; OpenMC Python API (MIT) as a library.
# Data: OpenMC's ThermalScattering.from_ace reader of an NJOY2016 table built
# with iwt = 2 (deck: target/ace_extra/HH2O_iwt2/input, recorded in the V&V
# note). Algorithm: IncoherentInelasticAE::sample_params / sample
# (openmc src/secondary_thermal.cpp) written as a DETERMINISTIC function of the
# uniform r1, then integrated over r1 by a 400 000-point midpoint rule
# (vectorised; no random numbers):
#   l = nearer incident table; j, c_j from the cdf search (including upstream's
#   fall-through when r1 >= c_last); E' by lin-lin inversion; E' adjusted to
#   the incident energy; f = (r1-c_j)/(c_j1-c_j); <mu> = mean over the n_mu
#   cosine indices of mu(j,k) + f (mu(j+1,k) - mu(j,k)) (the smear is
#   zero-mean).
# Output rows: <E eV>,<mean E' eV>,<mean E'^2 eV^2>,<mean mu>
# Usage: openmc-env; python thermal_ifeng2_reference.py <tape30> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

ENERGIES = [0.005, 0.0253, 0.1, 0.4, 1.0, 2.5]
M = 400_000


def main(path, out):
    th = od.ThermalScattering.from_ace(path)
    T = list(th.kTs)[0]
    d = list(th.inelastic.distribution.values())[0]
    grid = np.asarray(d._energy if hasattr(d, "_energy") else d.energy)
    rows = []
    r1 = (np.arange(M) + 0.5) / M
    for e in ENERGIES:
        i = 0
        f0 = 0.0
        if e >= grid[0]:
            i = int(np.searchsorted(grid, e, side="right") - 1)
            if i + 1 < len(grid):
                f0 = (e - grid[i]) / (grid[i + 1] - grid[i])
        l = i + 1 if f0 > 0.5 else i
        eo = d.energy_out[l]
        x, p, c = np.asarray(eo.x), np.asarray(eo.p), np.asarray(eo.c)
        n = len(x)
        # j = first index with r1 < c[j+1], j in [0, n-2]; fall-through -> c_j = c[n-1]
        k = np.searchsorted(c[1:], r1, side="right")  # count of c[1:] <= r1
        fell = k >= n - 1
        j = np.minimum(k, n - 2)
        c_j = np.where(fell, c[n - 1], c[j])
        c_j1 = np.where(fell, c[n - 1], c[j + 1])
        ej, pj, ej1, pj1 = x[j], p[j], x[j + 1], p[j + 1]
        frac = (pj1 - pj) / (ej1 - ej)
        with np.errstate(divide="ignore", invalid="ignore"):
            lin = np.where(pj > 0, ej + (r1 - c_j) / np.where(pj > 0, pj, 1), ej)
            quad = ej + (np.sqrt(np.maximum(0.0, pj * pj + 2 * frac * (r1 - c_j))) - pj) / np.where(frac == 0, 1, frac)
        E = np.where(frac == 0, lin, quad)
        el = grid[l]
        E = np.where(E < 0.5 * el, E * (2 * e / el - 1), E + e - el)
        with np.errstate(divide="ignore", invalid="ignore"):
            f = np.where(c_j1 > c_j, (r1 - c_j) / (c_j1 - c_j), 0.0)
        mus = d.mu[l]
        mu_rows = np.array([np.asarray(m.x) for m in mus])  # (n, n_mu), sorted
        mean_row = mu_rows.mean(axis=1)
        mu = mean_row[j] + f * (mean_row[j + 1] - mean_row[j])
        rows.append(f"{e!r},{float(E.mean())!r},{float((E * E).mean())!r},{float(mu.mean())!r}")
        print(e, "table", l, "<E'>", E.mean(), "<mu>", mu.mean(), "fell-through frac", fell.mean())
    with open(out, "w") as fh:
        fh.write("# generated by thermal_ifeng2_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
