#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
#
# OpenMC's unresolved-resonance cross sections for given (E, xi), from OpenMC's
# own reader of an ACE table: the reference for outram-mc's URR sampling
# (GitHub #365 audit: interpolation between table energies, and the total as
# the sum of partials).
#
# Own work (outram-park-backend), GPL-3.0. Uses the OpenMC Python API (MIT) as
# a library only. The algorithm is a transcription of
# `Nuclide::calculate_urr_xs` (openmc src/nuclide.cpp), lin-lin branch (every
# table here has INT = 2, asserted):
#
#   i      = lower_bound_index(E_grid, E)            E_i <= E < E_{i+1}
#   i_low  = first band of table i   with cdf > xi   (upper_bound_index + 1)
#   i_up   = first band of table i+1 with cdf > xi
#   f      = (E - E_i) / (E_{i+1} - E_i)
#   x      = (1-f) x[i, i_low] + f x[i+1, i_up]       for elastic, fission, capture
#   inelastic = smooth sigma of the ILF reaction (0 when ILF = -1)
#   if multiply_smooth: elastic *= sigma_el, capture *= (sigma_abs - sigma_f),
#                       fission *= sigma_f          (smooth values at E)
#   negatives -> 0;  total = elastic + inelastic + capture + fission
#
# Smooth values are OpenMC's Tabulated1D of the same table (lin-lin on its
# grid); sigma_abs is the sum of the non-redundant disappearance MTs (102-117,
# or their levels 600-849 where OpenMC keeps those) plus fission,
# which is what OpenMC's `micro.absorption` holds.
#
# Output rows:  <nuclide>,<E eV>,<xi>,<elastic>,<fission>,<capture>,<inelastic>,<total>
# Usage:  openmc-env; python urr_sampling_reference.py <dir with U23x.ace> <out.csv>

import sys
import numpy as np
import openmc
import openmc.data as od

NUCLIDES = ["U234", "U235", "U238"]
XIS = [0.0, 0.013, 0.2, 0.5, 0.77, 0.9999]


def main(d, out):
    rows = []
    for n in NUCLIDES:
        data = od.IncidentNeutron.from_ace(f"{d}/{n}.ace")
        T = list(data.energy)[0]
        u = data.urr[T]
        assert u.interpolation == 2
        eg = np.asarray(u.energy)
        rx = data.reactions

        def smooth(e):
            el = float(rx[2].xs[T](e))
            fis = sum(float(rx[m].xs[T](e)) for m in (18, 19, 20, 21, 38)
                      if m in rx and not rx[m].redundant)
            # every non-redundant disappearance reaction: the lumps 102-117 or,
            # where OpenMC keeps them instead, the levels 600-849
            dis = sum(float(r.xs[T](e)) for m, r in rx.items()
                      if (102 <= m <= 117 or 600 <= m <= 849) and not r.redundant)
            return el, fis, dis + fis

        ilf = u.inelastic_flag
        # energies: every table point, and the midpoints of a few bins
        # interior table points only: OpenMC's `energy_in_bounds` is strict at both
        # ends (include/openmc/urr.h), so the end points are not in the URR at all
        es = list(eg[1:-1:max(1, len(eg) // 6)]) + [0.5 * (eg[k] + eg[k + 1])
                                                  for k in (0, len(eg) // 2, len(eg) - 2)]
        es += [eg[1] + 0.3 * (eg[2] - eg[1])]
        for e in es:
            i = int(np.clip(np.searchsorted(eg, e, side="right") - 1, 0, len(eg) - 2))
            f = (e - eg[i]) / (eg[i + 1] - eg[i])
            for xi in XIS:
                def band(k):
                    cdf = u.table[k][0]
                    return int(min(np.searchsorted(cdf, xi, side="right"), len(cdf) - 1))
                lo, hi = band(i), band(i + 1)
                col = lambda c: (1 - f) * u.table[i][c][lo] + f * u.table[i + 1][c][hi]
                el, fi, ca = col(2), col(3), col(4)
                if ilf == -1:
                    inel = 0.0
                elif 51 <= ilf <= 91:
                    inel = float(rx[ilf].xs[T](e)) if ilf in rx else 0.0
                else:  # 4: the lump, i.e. the sum of the levels
                    inel = sum(float(rx[m].xs[T](e)) for m in rx if 51 <= m <= 91)
                if u.multiply_smooth:
                    sel, sf, sab = smooth(e)
                    el, ca, fi = el * sel, ca * (sab - sf), fi * sf
                el, fi, ca = max(el, 0.0), max(fi, 0.0), max(ca, 0.0)
                tot = el + inel + ca + fi
                rows.append(f"{n},{float(e)!r},{xi:.6f},{el:.15e},{fi:.15e},{ca:.15e},{inel:.15e},{tot:.15e}")
        print(n, "ILF", ilf, "multiply_smooth", u.multiply_smooth, "points", len(es))
    with open(out, "w") as fh:
        fh.write("# generated by urr_sampling_reference.py, openmc " + openmc.__version__ + "\n")
        fh.write("nuclide,e_ev,xi,elastic,fission,capture,inelastic,total\n")
        fh.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
