//! **HTR-10 cross sections through the ported `openmc.Model.plot`** — TRISO,
//! fuel and dummy pebbles, R-Z through the pebbles, and r-theta (`x-y`) slices
//! of the whole reactor at the heights that show every boring and the
//! defuelling chute. Helpers: [`nee_soon::htr10_rmc::plots::Htr10Plotter`].
//!
//! ```bash
//! cargo run --release -p nee_soon --example htr10_python_plots
//! OUTRAM_PYTHON=/path/to/python OUTRAM_HTR10_IMG_OUT=/some/dir cargo run --release ...
//! ```
//!
//! Writes, per plot, the standalone matplotlib script `<name>.py` (upstream's
//! `Model.plot` code on this crate's id map, verified pixel-for-pixel against
//! OpenMC in `outram-mc-libs/verification_and_validation/python_plotting_parity/`)
//! and, when a Python with numpy + matplotlib is available (`OUTRAM_PYTHON`,
//! default `python3`), runs it to `<name>.png`. `PLANES.md` records how each
//! plane was chosen and how many ball centres lie on it.
//!
//! Default output: `crates/nee_soon/verification_and_validation/htr10_python_plots/`.
//! Size: 14 rings x `OUTRAM_HTR10_LAYERS` (default 25, the critical loading,
//! 122.474 cm) — the geometry the k-eff runs use, drawn with the withdrawn rods
//! IN (the geometry default). NOT a validation artefact: no transport runs.

use std::path::PathBuf;
use std::process::Command;

use nee_soon::htr10_rmc::core_model::assemble_explicit_triso;
use nee_soon::htr10_rmc::plots::Htr10Plotter;

fn env_usize(k: &str, d: usize) -> usize {
    std::env::var(k)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(d)
}

fn main() {
    let rings = env_usize("OUTRAM_HTR10_RINGS", 14);
    let layers = env_usize("OUTRAM_HTR10_LAYERS", 25);
    let out = std::env::var("OUTRAM_HTR10_IMG_OUT").map_or_else(
        |_| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("verification_and_validation/htr10_python_plots")
        },
        PathBuf::from,
    );
    std::fs::create_dir_all(&out).expect("create output directory");
    let python = std::env::var("OUTRAM_PYTHON").unwrap_or_else(|_| "python3".into());

    let t0 = std::time::Instant::now();
    let plotter = Htr10Plotter::new(assemble_explicit_triso(rings, layers, 0));
    let c = &plotter.core;
    println!(
        "assembled {rings} x {layers} in {:.1} s: bed r {:.1} cm, z {:.3} .. {:.3}, conus floor {:.3}, model z {:.3} .. {:.3}",
        t0.elapsed().as_secs_f64(),
        c.bed_radius,
        -c.bed_half_height,
        c.bed_half_height,
        c.conus_floor,
        c.refl_bottom,
        c.refl_top
    );

    let mut planes = String::from(
        "# How each plane was chosen\n\nGenerated by `examples/htr10_python_plots.rs`. \
         Each line is the plane and the number of present ball centres on it.\n\n| Image | Plane |\n|---|---|\n",
    );
    for job in plotter.standard_set() {
        let t = std::time::Instant::now();
        let script = plotter.script(&job).expect("emit");
        let py = out.join(format!("{}.py", job.name));
        std::fs::write(&py, &script).expect("write script");
        let png = out.join(format!("{}.png", job.name));
        let ran = Command::new(&python).arg(&py).arg(&png).status();
        let status = match ran {
            Ok(s) if s.success() => "png written",
            Ok(_) => "python FAILED",
            Err(_) => "no python: script only",
        };
        println!(
            "{:<32} {:>5} kB script, {status} ({:.1} s) -- {}",
            job.name,
            script.len() / 1024,
            t.elapsed().as_secs_f64(),
            job.note
        );
        planes.push_str(&format!("| `{}.png` | {} |\n", job.name, job.note));
    }
    std::fs::write(out.join("PLANES.md"), planes).expect("write PLANES.md");
}
