//! The machine-readable and manuscript-facing artifacts: two CSVs and three
//! LaTeX tables.
//!
//! # Every byte here is compared
//!
//! These files are gated against `docs/kloc-parity-baseline/`, so nothing about
//! their shape is discretionary — not the CSV line terminator, not the quoting
//! rule, not a word of the table captions. Ported from `write_csvs` and the
//! `*_table_tex` functions of the retired `scripts/kloc_accounting.py`.
//!
//! # Two details that are easy to get wrong
//!
//! **CSV line endings are CRLF.** Python's `csv.writer` defaults to the `excel`
//! dialect, whose terminator is `\r\n`. Writing `\n` produces a file that looks
//! identical in an editor and fails the byte comparison.
//!
//! **LaTeX numbers use a thin space, not a comma.** `303\,463`, via
//! [`tex_num`] — a comma inside a numeric column reads as a decimal separator
//! to a European reader.
//!
//! # The one intended difference from the fixture
//!
//! These files name the tool that produced them, in the `% Generated by`
//! header and again in each caption's `\emph{...}` note — text that **prints in
//! the paper**. The fixture says `kloc_accounting.py`; this says `kovan kloc`,
//! because the script no longer exists and a caption pointing a reader at a
//! deleted file is worse than a failed byte comparison.
//!
//! So the parity check on the three `.tex` files is: **identical except the
//! lines naming the tool.** Every number, row, subtotal and caption sentence is
//! byte-for-byte. Verified 2026-08-14 — the only diff hunks were those lines.

use super::config::{
    Provenance, AGENTIC_MEASURE_REF, AGENTIC_SINCE, AGENTIC_UNTIL, BASELINE_FOOTNOTES,
    CRATE_TEX_NAME, GENERATED_BY, MONTHS,
};
use super::measure::{AgenticSummary, BaselineTotals, CrateStats, RepoStats};
use super::report::fmt;

// ---------------------------------------------------------------------------
// CSV
// ---------------------------------------------------------------------------

/// Quote a CSV field the way Python's `QUOTE_MINIMAL` does: only when the field
/// contains the delimiter, a quote, or a line break; embedded quotes doubled.
fn csv_field(value: &str) -> String {
    let needs_quotes =
        value.contains(',') || value.contains('"') || value.contains('\n') || value.contains('\r');
    if needs_quotes {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}

/// Join one CSV record, terminated CRLF (see the module docs).
fn csv_row(fields: &[String]) -> String {
    let joined: Vec<String> = fields.iter().map(|f| csv_field(f)).collect();
    format!("{}\r\n", joined.join(","))
}

/// Render `baseline_repositories.csv`.
pub fn baseline_csv(base_stats: &[RepoStats]) -> String {
    let mut out = csv_row(&[
        "repository".into(),
        "ref".into(),
        "first_commit".into(),
        "last_commit".into(),
        "total_lines".into(),
        "code_lines".into(),
        "active_days".into(),
        "rust_files".into(),
        "ai_assistance".into(),
    ]);
    for stats in base_stats {
        if stats.missing {
            out.push_str(&csv_row(&[
                stats.key.clone(),
                String::new(),
                String::new(),
                String::new(),
                String::new(),
                String::new(),
                String::new(),
                String::new(),
                "MISSING".into(),
            ]));
            continue;
        }
        out.push_str(&csv_row(&[
            stats.key.clone(),
            stats.reference.clone(),
            stats.first.clone(),
            stats.last.clone(),
            stats.lines.total.to_string(),
            stats.lines.code.to_string(),
            stats.days.len().to_string(),
            stats.lines.files.to_string(),
            stats.note.clone(),
        ]));
    }
    out
}

/// Render `agentic_crates.csv`.
pub fn agentic_csv(crate_rows: &[CrateStats]) -> String {
    let mut out = csv_row(&[
        "crate".into(),
        "class".into(),
        "upstream".into(),
        "total_lines".into(),
        "code_lines_in_backend".into(),
        "preagentic_baseline_code_lines".into(),
        "agentic_code_lines".into(),
        "cargo_toml_description".into(),
    ]);
    for row in crate_rows {
        out.push_str(&csv_row(&[
            row.display.clone(),
            row.class.key().to_string(),
            row.upstream.clone().unwrap_or_default(),
            row.total_lines.to_string(),
            row.raw_code_lines.to_string(),
            row.baseline_code_lines.to_string(),
            row.code_lines.to_string(),
            row.description.clone(),
        ]));
    }
    out
}

// ---------------------------------------------------------------------------
// LaTeX
// ---------------------------------------------------------------------------

/// Format an integer with LaTeX thin-space thousands separators: `303\,463`.
pub fn tex_num(n: u64) -> String {
    fmt(n).replace(',', r"\,")
}

/// How a crate is named in a table cell.
pub fn tex_name(crate_name: &str) -> String {
    if let Some((_, tex)) = CRATE_TEX_NAME.iter().find(|(name, _)| *name == crate_name) {
        return (*tex).to_string();
    }
    format!(r"\texttt{{{}}}", crate_name.replace('_', r"\_"))
}

/// `2023-06-27` becomes `Jun 2023`; an empty date becomes `---`.
pub fn tex_month(date: &str) -> String {
    if date.is_empty() {
        return "---".to_string();
    }
    let parts: Vec<&str> = date.split('-').collect();
    if parts.len() < 2 {
        return "---".to_string();
    }
    let month: usize = parts[1].parse().unwrap_or(1);
    let name = MONTHS
        .get(month.saturating_sub(1))
        .copied()
        .unwrap_or("Jan");
    format!("{name} {}", parts[0])
}

/// The year alone, from a `YYYY-MM-DD` date.
fn tex_year(date: &str) -> String {
    tex_month(date)
        .split_whitespace()
        .next_back()
        .unwrap_or("---")
        .to_string()
}

/// Render `baseline_table.tex` — `tab:preagentic_baseline`.
pub fn baseline_table_tex(base_stats: &[RepoStats], base_totals: &BaselineTotals) -> String {
    let net = base_totals.tuas_net.unwrap_or_default();
    let head_total = tex_num(net.head.total);
    let head_code = tex_num(net.head.code);

    let rows: Vec<String> = base_stats
        .iter()
        .filter(|s| !s.missing)
        .map(|s| {
            let marker = if s.marker.is_empty() {
                String::new()
            } else {
                format!("$^{{{}}}$", s.marker)
            };
            let cite = if s.cite.is_empty() {
                String::new()
            } else {
                format!(r" \cite{{{}}}", s.cite)
            };
            format!(
                "{}{marker}{cite} & {} -- {} & {} & {} & {} \\\\",
                s.label,
                tex_month(&s.first),
                tex_month(&s.last),
                tex_num(s.lines.total),
                tex_num(s.lines.code),
                s.days.len()
            )
        })
        .collect();

    let notes: Vec<String> = BASELINE_FOOTNOTES
        .iter()
        .map(|(marker, text)| format!("$^{{{marker}}}$~{text}"))
        .collect();

    format!(
        r"{GENERATED_BY}\begin{{table}}[H]
\centering
\caption{{Pre-agentic repositories forming the productivity baseline, measured
{as_of}. Code lines exclude blank and
comment-only lines; total lines include both, so Rust doc comments, which carry
executable doctests, appear only in the total. An active day is any calendar
date carrying at least one commit; the total is a union of distinct dates
rather than a column sum, because these projects overlapped in time. TUAS is
reported net of the code it inherited from \texttt{{thermal\_hydraulics\_rs}} at
spin-out --- specifically net of the tree TUAS imported wholesale at its second
commit, \texttt{{c451c8e}}, rather than net of the predecessor's own full extent,
so that what is removed is what actually came across. At its head TUAS stands at
{head_total} total and {head_code} code lines, the 96~KLOC
quoted in the text. All figures are measured on each repository's
\texttt{{develop}} branch, which is where the development history lives ---
these repositories squash-merge into \texttt{{main}}, so measuring \texttt{{main}}
would collapse years of work into a handful of commits.
\texttt{{thermal\_hydraulics\_rs}} is measured at commit \texttt{{4d534af}}, the
last before its code was moved into TUAS on 2024-10-11 and the repository
emptied. None of these repositories used an agentic coding workflow.
\emph{{Every figure in this table is produced by \texttt{{kovan kloc}},
which walks the repositories and their git histories directly; see
Section~\ref{{sec:reproducing_the_counts}}}}}}
\label{{tab:preagentic_baseline}}
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\begin{{tabular}}{{@{{}}
  >{{\raggedright\arraybackslash}}p{{0.33\linewidth}}
  >{{\raggedright\arraybackslash}}p{{0.19\linewidth}}
  r r r@{{}}}}
\toprule
\textbf{{Repository}} & \textbf{{Period}} & \textbf{{Total}} & \textbf{{Code}} &
\textbf{{Active}} \\
 & & \textbf{{lines}} & \textbf{{lines}} & \textbf{{days}} \\
\midrule
{rows}
\midrule
\textbf{{Baseline total}} & \textbf{{{first_year} -- {last_year}}} & \textbf{{{total}}} & \textbf{{{code}}} & \textbf{{{days}}} \\
\bottomrule
\end{{tabular}}

\vspace{{3pt}}
{{\footnotesize
\begin{{minipage}}{{\linewidth}}
{notes}
\end{{minipage}}}}
\end{{table}}
",
        as_of = base_totals.as_of(),
        rows = rows.join("\n"),
        notes = notes.join("\n"),
        first_year = tex_year(&base_totals.first),
        last_year = tex_year(&base_totals.last),
        total = tex_num(base_totals.lines.total),
        code = tex_num(base_totals.lines.code),
        days = base_totals.active_days(),
    )
}

/// Render `rate_table.tex` — the per-repository rate table, fastest first.
pub fn rate_table_tex(
    base_stats: &[RepoStats],
    base_totals: &BaselineTotals,
    agentic: &AgenticSummary,
) -> String {
    let mut ranked: Vec<&RepoStats> = base_stats
        .iter()
        .filter(|s| !s.missing && !s.days.is_empty())
        .collect();
    ranked.sort_by(|a, b| {
        b.rate()
            .unwrap_or(0.0)
            .partial_cmp(&a.rate().unwrap_or(0.0))
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let rows: Vec<String> = ranked
        .iter()
        .map(|s| {
            format!(
                "{} & {} & {} \\\\",
                tex_num(s.rate().unwrap_or(0.0).round() as u64),
                s.label,
                s.note
            )
        })
        .collect();

    let mut extra: Vec<String> = Vec::new();
    if let Some(rate) = base_totals.rate() {
        extra.push(format!(
            "\\midrule\n\\textbf{{{}}} & \\textbf{{Pre-agentic baseline, all repositories}} & \\textbf{{mixed}} \\\\",
            tex_num(rate.round() as u64)
        ));
    }
    if let Some(rate) = agentic.rate() {
        extra.push(format!(
            "\\textbf{{{}}} & \\textbf{{\\texttt{{outram-park-backend}}}} & \\textbf{{agentic}} \\\\",
            tex_num(rate.round() as u64)
        ));
    }

    format!(
        r"{GENERATED_BY}\begin{{table}}[H]
\centering
\caption{{Code lines per active day, each pre-agentic repository ranked fastest
first, against the agentic month. The spread among the pre-agentic
repositories --- roughly a factor of three, from 206 to 572 --- is the useful
context for the agentic figure: it is the ordinary variation between projects
of differing nature, and it is far smaller than the gap to the agentic rate.
The \emph{{AI?}} column records only non-agentic assistance; none of the
pre-agentic repositories used an agentic workflow.
\emph{{Produced by \texttt{{kovan kloc}}; see
Section~\ref{{sec:reproducing_the_counts}}}}}}
\label{{tab:baseline_rates}}
\footnotesize
\begin{{tabular}}{{@{{}}r
  >{{\raggedright\arraybackslash}}p{{0.42\linewidth}}
  >{{\raggedright\arraybackslash}}p{{0.26\linewidth}}@{{}}}}
\toprule
\textbf{{Code lines}} & \textbf{{Repository}} & \textbf{{Non-agentic}} \\
\textbf{{per active day}} & & \textbf{{AI assistance}} \\
\midrule
{rows}
{extra}
\bottomrule
\end{{tabular}}
\end{{table}}
",
        rows = rows.join("\n"),
        extra = extra.join("\n"),
    )
}

/// Render `agentic_table.tex` — `tab:agentic_crates`.
pub fn agentic_table_tex(crate_rows: &[CrateStats], agentic: &AgenticSummary) -> String {
    let mut body: Vec<String> = Vec::new();
    for class in Provenance::ORDER {
        let mut members: Vec<&CrateStats> =
            crate_rows.iter().filter(|r| r.class == *class).collect();
        if members.is_empty() {
            continue;
        }
        members.sort_by(|a, b| b.code_lines.cmp(&a.code_lines));
        if !body.is_empty() {
            body.push(r"\midrule".to_string());
        }
        body.push(format!(
            r"\multicolumn{{3}}{{@{{}}l}}{{\textit{{{}}}}} \\",
            class.tex_section()
        ));
        for row in members {
            let upstream = match class {
                Provenance::Translated => row.upstream.clone().unwrap_or_default(),
                Provenance::Original => "---".to_string(),
                Provenance::Extension => "(own, pre-agentic)".to_string(),
            };
            body.push(format!(
                "{} & {upstream} & {} \\\\",
                tex_name(&row.display),
                tex_num(row.code_lines)
            ));
        }
        body.push(r"\cmidrule(r){1-3}".to_string());
        body.push(format!(
            "{} & & \\textbf{{{}}} \\\\",
            class.tex_subtotal(),
            tex_num(agentic.subtotal(*class))
        ));
    }

    let pin = AGENTIC_MEASURE_REF.unwrap_or("HEAD");
    let pin_short = &pin[..pin.len().min(7)];

    format!(
        r"{GENERATED_BY}\begin{{table}}[H]
\centering
\caption{{Agentic lines of code in \texttt{{outram-park-backend}} by crate,
{AGENTIC_SINCE} -- {AGENTIC_UNTIL}. Code lines exclude blank
and comment-only lines. Translated crates are pure-Rust forks or ports of the
named upstream project and are independent works, not the official software.
Extensions are the excess of a vendored crate over its standalone pre-agentic
original, and are credited here rather than to the baseline.
\emph{{Every figure in this table is produced by \texttt{{kovan kloc}}
from the repository pinned at commit \texttt{{{pin_short}}}, because
\texttt{{develop}} moves daily and a tip measurement could not be reproduced
later; the classification of each
crate is the one editorial input, and is carried in the script beside each
crate's own \texttt{{Cargo.toml}} description so it can be audited. See
Section~\ref{{sec:reproducing_the_counts}}.}}}}
\label{{tab:agentic_crates}}
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\begin{{tabular}}{{@{{}}
  >{{\raggedright\arraybackslash}}p{{0.42\linewidth}}
  >{{\raggedright\arraybackslash}}p{{0.22\linewidth}}
  r@{{}}}}
\toprule
\textbf{{Crate}} & \textbf{{Upstream}} & \textbf{{Code lines}} \\
\midrule
{body}
\midrule
\textbf{{Total agentic}} & & \textbf{{{total}}} \\
\bottomrule
\end{{tabular}}

\vspace{{3pt}}
{{\footnotesize
\begin{{minipage}}{{\linewidth}}
$^{{\dagger}}$~\texttt{{nee\_soon}} succeeds \texttt{{teh-o-prke}} in naming --- the
former Teh-O package --- but its code is newly written; the point kinetics
module itself remains vendored as \texttt{{teh-o-prke}}.
\end{{minipage}}}}
\end{{table}}
",
        body = body.join("\n"),
        total = tex_num(agentic.agentic_total),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csv_records_end_crlf_because_python_uses_the_excel_dialect() {
        let row = csv_row(&["a".into(), "b".into()]);
        assert_eq!(row, "a,b\r\n");
        assert!(
            !row.ends_with("\n\n") && row.ends_with("\r\n"),
            "a bare \\n looks identical in an editor and fails the byte comparison"
        );
    }

    #[test]
    fn only_fields_that_need_quotes_get_them() {
        assert_eq!(csv_field("plain"), "plain");
        assert_eq!(csv_field("a,b"), "\"a,b\"");
        assert_eq!(csv_field("say \"hi\""), "\"say \"\"hi\"\"\"");
        assert_eq!(csv_field(""), "");
    }

    #[test]
    fn latex_numbers_use_a_thin_space_not_a_comma() {
        assert_eq!(tex_num(303_463), r"303\,463");
        assert_eq!(tex_num(849), "849");
        assert_eq!(tex_num(0), "0");
    }

    #[test]
    fn crate_names_are_escaped_or_overridden() {
        assert_eq!(tex_name("outram-mc-libs"), r"\texttt{outram-mc-libs}");
        // An underscore is a LaTeX control character.
        assert_eq!(tex_name("kovan_common"), r"\texttt{kovan\_common}");
        // Overrides win.
        assert_eq!(tex_name("nee_soon"), r"\texttt{nee\_soon}$^{\dagger}$");
        assert_eq!(
            tex_name("chem-eng-real-time-process-control-simulator"),
            r"\texttt{chem-eng-\ldots-simulator}"
        );
    }

    #[test]
    fn dates_render_as_month_and_year() {
        assert_eq!(tex_month("2023-06-27"), "Jun 2023");
        assert_eq!(tex_month("2024-10-14"), "Oct 2024");
        assert_eq!(tex_month(""), "---");
        assert_eq!(tex_year("2023-06-27"), "2023");
    }

    #[test]
    fn generated_files_warn_against_hand_editing() {
        let text = rate_table_tex(&[], &BaselineTotals::default(), &AgenticSummary::default());
        assert!(text.starts_with("% Generated by"));
        assert!(text.contains("do not edit by hand"));
    }
}
