//! # outram-park-fork-coolprop
//!
//! A pure-Rust fork/translation of [CoolProp](https://github.com/CoolProp/CoolProp)
//! (MIT) — thermophysical properties from Helmholtz-energy-explicit equations
//! of state — built to OUTRAM PARK's design rules:
//!
//! - **Enum dispatch, no trait objects.** Fluids are a [`Fluid`] enum and
//!   EOS-term forms are [`eos::ResidualTerm`] / [`eos::IdealTerm`] enums,
//!   dispatched by `match` (see [`eos`]).
//! - **Hardcoded data, no runtime JSON.** Each fluid's EOS coefficients are
//!   `const` Rust in [`fluids`], generated once from CoolProp's fluid JSON by
//!   `dev/gen_fluid.py` (the CoolProp clone lives in the gitignored
//!   `reference/` for development only). A few KB per fluid.
//! - **Pure `std`, no BLAS / C deps** — so it builds on Android too.
//!
//! ## Status
//!
//! - **Engine** ([`eos`]): every Helmholtz term form CoolProp's fluids use
//!   (residual Power / Gaussian / Exponential / DoubleExponential / GaoB, ideal
//!   Lead / LogTau / Planck–Einstein(+Generalized) / Power / CP0*), with all
//!   first/second `δ`,`τ` derivatives.
//! - **Fluids** ([`fluid::Fluid`]): all 137 CoolProp pure fluids, hardcoded and
//!   wired into the enum (`Fluid::ALL`).
//! - **Properties**: `(T, ρ)` native ([`props::state_trho`]) plus single-phase
//!   `(p, T)` / `(p, h)` / `(p, s)` flashes ([`flash`]).
//! - **Saturation / VLE** ([`vle`], [`ancillaries`]): fast saturation-ancillary
//!   lookups and a thermodynamically-consistent Maxwell two-phase solve
//!   (`p_sat`, `ρ'`, `ρ''`, `T_sat(p)`, and `(p,h)` quality).
//! - **Transport** ([`transport`]): dynamic viscosity `μ` and thermal
//!   conductivity `λ` (CoolProp correlations; critical enhancement omitted).
//! - **Control volume** ([`single_cv::OPCPFluidSingleCV`]): a `uom`-typed 0-D
//!   equilibrium lump of one fluid (the CoolProp analogue of
//!   `tampines-steam-tables`' `TampinesSteamTableCV`) — two-phase-aware, with
//!   `μ`/`λ` getters.
//! - **Transient flow** ([`openfoam_algorithms`]): a vendored pure-Rust
//!   OpenFOAM finite-volume layer + the 1-D compressible `OPCPFluidArray`
//!   solver (no `openfoam-basic-lib` dependency), driven by this crate's EOS.
//!
//! The **non-analytic** critical-region residual term is evaluated (verified
//! to `5.2e-14` at Water's exact critical point — see
//! `tests/non_analytic_critical_region.rs`). Transport covers the generic
//! models, near-critical enhancement, friction/kinetic theory, the per-fluid
//! hardcoded formulas, and Chung (1988) corresponding-states viscosity
//! (cyclopentane, isopentane); ECS/rhosr-CS (ethylbenzene, R1234yf,
//! R1234ze(E), R152A) remain a scaffolded follow-up
//! ([`transport_corresponding_states`], bead op-kbc.17).
//!
//! **Humid air** ([`humid_air`], ASHRAE RP-1485 / `HAPropsSI`-equivalent):
//! `(T, p, W)`/`(T, p, R)` inputs, `W`/`R`/`ψ_w`/enthalpy/volume outputs,
//! verified (`c_p` and `V` vs the ideal-gas limit, <0.1%). Entropy, wet-bulb
//! and dew-point are not implemented (bead op-kbc.14 — see the module doc).
//!
//! **Incompressibles** ([`incompressibles`], the `INCOMP` backend, bead
//! op-kbc.15, done): **all 126** CoolProp incompressible fluids, generated by
//! `dev/gen_incompressible.py`/`dev/regen_incompressible_all.py` (mirroring
//! the pure-fluid codegen). 2-D polynomial/exponential/log-exponential fits
//! with `T_base`/`x_base` centring, verified against T66 (Therminol 66) to
//! <1e-6 and a 126-fluid smoke test.
//!
//! **Mixtures** ([`mixtures`], multi-fluid Helmholtz + departure functions,
//! bead op-kbc.16, done): **840 of 888** CoolProp binary pairs, generated by
//! `dev/gen_mixture.py`/`dev/regen_mixture_all.py` (the other 48 touch a
//! component outside this crate's 137 ported pure fluids). The GERG-2008
//! reducing-function + residual/ideal-gas engine (including all three
//! departure-function forms: `Power`, `Gaussian`, `GergExponential`) is
//! verified against Nitrogen–Oxygen (`F = 0`, reproducing air's speed of
//! sound to <0.1%), R32–R125 (a real `F ≠ 0` departure function, part of the
//! R410A refrigerant blend), and a 840-pair smoke test. No flash/VLE.
//!
//! `rfluids` oracle verification is planned (bead op-kbc.3).
//!
//! ## Example
//!
//! ```
//! use outram_park_fork_coolprop::{Fluid, props::state_trho};
//! // Superheated steam at 500 K, 2 kg/m³ (~0.46 MPa).
//! let s = state_trho(Fluid::Water, 500.0, 2.0);
//! assert!(s.pressure > 0.0);
//! assert!(s.speed_of_sound > 0.0);
//! ```
//!
//! (Note: liquid water's `p(ρ)` is extremely steep, so a density just below the
//! saturated-liquid value gives a small *negative* pressure — the metastable
//! tension region. `(T, ρ)` inputs are literal EOS evaluations, not a
//! phase-stable flash.)

pub mod ancillaries;
pub mod eos;
pub mod flash;
pub mod fluid;
pub mod fluids;
pub mod props;
pub mod single_cv;
pub mod transport;
pub mod vle;

// --- Newer backends / refinements (bead op-kbc) ---
//
// Not yet wired into the public prelude below — see each module's `//!` doc
// for implementation status (`humid_air` has real physics; `incompressibles`
// and `mixtures` are still `todo!()` skeletons).

/// Humid (moist) air properties — the CoolProp `HAPropsSI` backend (ASHRAE
/// RP-1485). `(T,p,W)`/`(T,p,R)` inputs implemented and verified; see the
/// module doc for coverage (bead op-kbc.14).
pub mod humid_air;

/// Incompressible-fluid properties — the CoolProp `INCOMP` backend.
/// **Scaffold only** (bead op-kbc.15).
pub mod incompressibles;

/// Multi-fluid mixture properties — the CoolProp Helmholtz mixture backend.
/// **Scaffold only** (bead op-kbc.16).
pub mod mixtures;

/// General corresponding-states transport (Chung / ECS / rhosr-CS) — the
/// viscosity fallback for fluids with no dedicated fit. **Scaffold only**
/// (bead op-kbc.17).
pub mod transport_corresponding_states;

/// Vendored pure-Rust OpenFOAM finite-volume layer + 1-D compressible solvers,
/// copied from `tampines-steam-tables` (no `openfoam-basic-lib` dependency).
/// The transient-flow backbone whose thermo plug-in point is backed by this
/// crate's CoolProp EOS. See its module `CLAUDE.md` for provenance.
pub mod openfoam_algorithms;

pub use ancillaries::{FluidAncillaries, SatAncillary};
pub use eos::{FluidEos, HelmholtzDerivs, IdealTerm, ResidualTerm};
pub use flash::{state_ph, state_ps, state_pt, density_pt, FlashError};
pub use fluid::Fluid;
pub use openfoam_algorithms::rhoPimpleFoam::OPCPFluidArray;
pub use props::{state_trho, pressure_trho, FluidState};
pub use single_cv::OPCPFluidSingleCV;
pub use transport::{conductivity, viscosity, FluidTransport};
pub use vle::{phase_at_ph, saturation_at_temperature, saturation_temperature, PhaseAtPh, SaturationState};
