// SPDX-License-Identifier: GPL-3.0
//
// Code-to-code verification of `changi::flexpart::{met_fields, wet_deposition,
// oh_chemistry, landuse}` against upstream FLEXPART v10.4 (commit 3d7eebf,
// GPL-3.0-or-later).
//
// Uses only changi, and reads its fixtures through `include_str!`, so there is
// no filesystem access at run time and no target gate is needed.

//! # V&V: FLEXPART stage `met` — boundary-layer parameters, PV, wet deposition, OH, landuse
//!
//! ## Methodology
//!
//! `dev/flexpart_reference_met.f90` links upstream's `calcpar`,
//! `calcpar_nests`, `calcpv`, `calcpv_nests`, `interpol_rain`,
//! `interpol_rain_nests`, `get_wetscav`, `wetdepo`, `wetdepokernel`,
//! `wetdepokernel_nest`, `ohreaction`, `gethourlyOH` and `assignland`
//! **verbatim**, with everything they call. It writes synthetic fields into
//! `com_mod` / `oh_mod` and echoes them as setup rows (`cp.*`, `wet.*`,
//! `wd.*`, `oh.*`, `lu.*`). Two large tables are instead generated by an
//! integer formula reproduced here exactly (the 360 x 180 x 12
//! `jrate_average` and the 1200 x 600 landuse inventory); each is
//! cross-checked against sample rows (`oh.jrcheck`, `lu.check`).
//!
//! The nest routines need one configuration change: the build compiles a
//! copy of `par_mod.f90` with `maxnests=1, nxmaxn=12, nymaxn=12` instead of
//! the shipped zeros. Every routine under test is verbatim.
//!
//! Built twice by `dev/build_reference_met.sh`: real(4) as FLEXPART ships,
//! and `-fdefault-real-8 -fdefault-double-8`. The real(8) comparison proves
//! the translation; the real(4) comparison measures FLEXPART as shipped.
//!
//! Each Rust function that replaces a `_nests` twin is driven against both
//! upstream routines: a nest row (`calcpar` scenario 3, `interpol_rain` grid
//! 1, `get_wetscav` points inside the nest, `wetdepokernel` variant 2) is
//! evaluated by the same Rust function on the nest's fields.
//!
//! ## Results
//!
//! Re-print with `cargo test --release -p changi --test
//! flexpart_met_code_to_code -- --nocapture`. Recorded, with the
//! interpretation, in `docs/flexpart-code-to-code.md`.
//!
//! ## What this does NOT establish
//!
//! Verification, not validation, on synthetic fields. Nothing here supports
//! emergency response or dose assessment for real populations.

mod common;

use std::collections::HashMap;
use std::sync::OnceLock;

use changi::flexpart::aerosol::AerosolBins;
use changi::flexpart::constants::{NI, NUMCLASS};
use changi::flexpart::dry_deposition::{DepositionSpecies, GasSpecies, SurfaceResistances, NSEASON};
use changi::flexpart::landuse::{assignland, LanduseGrid, LanduseInventory, LUMAXX, LUMAXY};
use changi::flexpart::met_fields::{
    calcpar, calcpv, CalcparInput, CalcparOptions, CalcparOutput, DryDepositionInput, Field2,
    Field3, GlobalDomain, GridGeometry, GridKind,
};
use changi::flexpart::oh_chemistry::{
    gethourly_oh, ohreaction, HourlyOh, JrateClimatology, OhClimatology, OhMet, OhSpecies,
};
use changi::flexpart::surface_layer::MetDataFormat;
use changi::flexpart::wet_deposition::{
    get_wetscav, interpol_rain, wetdepo, wetdepokernel, CloudField, DepositionGrid, KernelRule,
    NestFrame, OutputFrame, ParticleRecord, ScavCounts, ScavengingRegime, WetDepoSettings,
    WetFields, WetGrid, WetOutputGrid, WetScavMet, WetScavSpecies,
};
use common::{check_group, Bounds, Fixtures, Precision, Real4Rule, Row};

const FIXTURE_REAL4: &str = include_str!("data/flexpart_met_real4.csv");
const FIXTURE_REAL8: &str = include_str!("data/flexpart_met_real8.csv");
const DP_FUNCTIONS: &[&str] = &["cp.time", "oh.bdate"];

const SENTINEL: f64 = -7.0;

fn find<'a>(rows: &'a [Row], name: &str) -> impl Iterator<Item = &'a Row> + 'a {
    let name = name.to_string();
    rows.iter().filter(move |r| r.function == name)
}

fn one<'a>(rows: &'a [Row], name: &str, pred: impl Fn(&Row) -> bool) -> &'a Row {
    rows.iter()
        .find(|r| r.function == name && pred(r))
        .unwrap_or_else(|| panic!("no `{name}` setup row"))
}

// ── calcpar / calcpv ──────────────────────────────────────────────────────────

struct CalcparScenario {
    out: CalcparOutput,
    nx: usize,
    z0_table7: f64,
}

fn wesely(rows: &[Row]) -> ([[SurfaceResistances; NUMCLASS]; NSEASON], [f64; NUMCLASS]) {
    let mut t = [[SurfaceResistances::default(); NUMCLASS]; NSEASON];
    let mut z0 = [0.0; NUMCLASS];
    for r in find(rows, "wesely") {
        let a = &r.args;
        let (i, j) = (a[0] as usize - 1, a[1] as usize - 1);
        t[i][j] = SurfaceResistances {
            ri: a[2],
            rac: a[3],
            rcl: a[4],
            rgs: a[5],
            rlu: a[6],
        };
        z0[j] = a[7];
    }
    (t, z0)
}

fn bins(rows: &[Row]) -> AerosolBins {
    let a = &one(rows, "particle_bins", |_| true).args;
    let mut b = AerosolBins {
        mass_fraction: [0.0; NI],
        schmidt_factor: [0.0; NI],
        settling_velocity: [0.0; NI],
        cunningham: [0.0; NI],
    };
    for j in 0..NI {
        b.settling_velocity[j] = a[j];
        b.schmidt_factor[j] = a[NI + j];
        b.mass_fraction[j] = a[2 * NI + j];
    }
    b
}

fn drydep_species(rows: &[Row], kind: usize) -> DepositionSpecies {
    // cp.species: kind, reldiff, henry, f0, rm, density, dryvel
    let a = &one(rows, "cp.species", |r| r.args[0] as usize == kind).args;
    match kind {
        1 | 4 => DepositionSpecies::Gas(GasSpecies {
            reldiff: a[1],
            henry: a[2],
            f0: a[3],
            rm: a[4],
        }),
        2 => DepositionSpecies::Particle {
            density: a[5],
            bins: bins(rows),
        },
        _ => DepositionSpecies::Prescribed(a[6]),
    }
}

fn run_scenario(rows: &[Row], sc: usize) -> CalcparScenario {
    let g = &one(rows, "cp.grid", |r| r.args[0] as usize == sc).args;
    let kind = if g[1] == 1.0 {
        GridKind::Nest
    } else {
        GridKind::Mother
    };
    let (nx, ny) = (g[3] as usize, g[4] as usize);
    let geom = GridGeometry {
        nx,
        ny,
        dx: g[5],
        dy: g[6],
        xlon0: g[7],
        ylat0: g[8],
    };
    let lev = &one(rows, "cp.levels", |r| r.args[0] as usize == sc).args;
    let n = lev[1] as usize;
    let akz = lev[2..2 + n].to_vec();
    let bkz = lev[2 + n..2 + 2 * n].to_vec();
    let (akm, bkm) = (
        [lev[2 + 2 * n], lev[3 + 2 * n]],
        [lev[4 + 2 * n], lev[5 + 2 * n]],
    );
    let format = if g[2] == 1.0 {
        MetDataFormat::Ncep
    } else {
        MetDataFormat::Ecmwf { akm, bkm }
    };
    let domain = find(rows, "cp.global")
        .find(|r| r.args[0] as usize == sc)
        .map_or(GlobalDomain::LIMITED, |r| GlobalDomain {
            xglobal: r.args[1] == 1.0,
            sglobal: r.args[2] == 1.0,
            nglobal: r.args[3] == 1.0,
        });
    // scenarios 4 and 5 rerun the fields of scenario 1
    let col_sc = if sc == 4 || sc == 5 { 1 } else { sc };
    let f2 = || Field2::filled(nx, ny, 0.0);
    let f3 = || Field3::filled(nx, ny, n, 0.0);
    let mut inp = CalcparInput {
        ps: f2(),
        tt2: f2(),
        td2: f2(),
        surfstr: f2(),
        sshf: f2(),
        ssr: f2(),
        lsprec: f2(),
        convprec: f2(),
        sd: f2(),
        excessoro: f2(),
        hmix_in: f2(),
        tth: f3(),
        qvh: f3(),
        uuh: f3(),
        vvh: f3(),
        akz: akz.clone(),
        bkz: bkz.clone(),
    };
    let mut landuse = vec![[0.0; NUMCLASS]; nx * ny];
    for r in find(rows, "cp.column").filter(|r| r.args[0] as usize == col_sc) {
        let a = &r.args;
        let (ix, jy) = (a[1] as usize, a[2] as usize);
        let s = &a[3..14];
        for (f, v) in [
            &mut inp.ps,
            &mut inp.tt2,
            &mut inp.td2,
            &mut inp.surfstr,
            &mut inp.sshf,
            &mut inp.ssr,
            &mut inp.lsprec,
            &mut inp.convprec,
            &mut inp.sd,
            &mut inp.excessoro,
            &mut inp.hmix_in,
        ]
        .into_iter()
        .zip(s)
        {
            f.set(ix, jy, *v);
        }
        for k in 0..n {
            inp.tth.set(ix, jy, k, a[14 + k]);
            inp.qvh.set(ix, jy, k, a[14 + n + k]);
            inp.uuh.set(ix, jy, k, a[14 + 2 * n + k]);
            inp.vvh.set(ix, jy, k, a[14 + 3 * n + k]);
        }
        landuse[ix + nx * jy].copy_from_slice(&a[14 + 4 * n..14 + 4 * n + NUMCLASS]);
    }
    let (table, z0) = wesely(rows);
    if sc >= 6 {
        let pv = calcpv(
            &geom, domain, &akz, &bkz, &inp.ps, &inp.tth, &inp.uuh, &inp.vvh,
        )
        .expect("calcpv");
        let out = CalcparOutput {
            ustar: f2(),
            oli: f2(),
            hmix: f2(),
            wstar: f2(),
            vdep: Vec::new(),
            tropopause: Vec::new(),
            z0_water_last: None,
            pv,
        };
        return CalcparScenario {
            out,
            nx,
            z0_table7: z0[6],
        };
    }
    let t = &one(rows, "cp.time", |r| r.args[0] as usize == sc).args;
    let drydep = (g[10] == 1.0).then(|| DryDepositionInput {
        jul: t[1] + t[2] / 86400.0,
        season_lat0: g[13],
        season_dy: g[12],
        landuse,
        z0,
        species: vec![(drydep_species(rows, g[11] as usize), table)],
    });
    let opts = CalcparOptions {
        format,
        kind,
        lsubgrid: g[9] == 1.0,
        domain,
    };
    let out = calcpar(&geom, &opts, &inp, drydep.as_ref()).expect("calcpar");
    CalcparScenario {
        out,
        nx,
        z0_table7: z0[6],
    }
}

// ── wet deposition ────────────────────────────────────────────────────────────

struct WetSetup {
    /// [grid][storage slot] fields
    fields: [[WetFields; 2]; 2],
    nest: NestFrame,
    height: Vec<f64>,
    species: Vec<WetScavSpecies>,
    frame_mother: OutputFrame,
    frame_nest: OutputFrame,
    out_dims: [(usize, usize); 2],
}

fn wet_setup(rows: &[Row]) -> WetSetup {
    let nestrow = &one(rows, "wet.nest", |_| true).args;
    let dims = [(6usize, 5usize), (nestrow[6] as usize, nestrow[7] as usize)];
    let height = one(rows, "wet.height", |_| true).args.clone();
    let nz = height.len();
    let mk = |g: usize| {
        let (nx, ny) = dims[g];
        WetFields {
            lsprec: Field2::filled(nx, ny, 0.0),
            convprec: Field2::filled(nx, ny, 0.0),
            tcc: Field2::filled(nx, ny, 0.0),
            clouds: CloudField {
                nx,
                ny,
                nz,
                data: vec![0; nx * ny * nz],
            },
            tt: Field3::filled(nx, ny, nz, 0.0),
            ctwc: Field2::filled(nx, ny, 0.0),
        }
    };
    let mut fields = [[mk(0), mk(0)], [mk(1), mk(1)]];
    for name in ["wet.field", "wet.clouds", "wet.tt"] {
        for r in find(rows, name) {
            let (g, m, k) = (
                r.args[0] as usize,
                r.args[1] as usize - 1,
                r.args[2] as usize,
            );
            let f = &mut fields[g][m];
            match name {
                "wet.field" => {
                    let t = match k {
                        1 => &mut f.lsprec,
                        2 => &mut f.convprec,
                        3 => &mut f.tcc,
                        _ => &mut f.ctwc,
                    };
                    t.data.copy_from_slice(&r.outs);
                }
                "wet.clouds" => {
                    let n = f.clouds.nx * f.clouds.ny;
                    for (i, v) in r.outs.iter().enumerate() {
                        f.clouds.data[i + n * (k - 1)] = *v as i8;
                    }
                }
                _ => {
                    let n = f.tt.nx * f.tt.ny;
                    f.tt.data[n * (k - 1)..n * k].copy_from_slice(&r.outs);
                }
            }
        }
    }
    let mut species = vec![
        WetScavSpecies {
            dquer: 0.0,
            weta_gas: 0.0,
            wetb_gas: 0.0,
            crain_aero: 0.0,
            csnow_aero: 0.0,
            ccn_aero: 0.0,
            in_aero: 0.0,
            henry: 0.0,
        };
        6
    ];
    for r in find(rows, "wet.species") {
        let o = &r.outs;
        species[r.args[0] as usize - 1] = WetScavSpecies {
            dquer: o[0],
            weta_gas: o[1],
            wetb_gas: o[2],
            crain_aero: o[3],
            csnow_aero: o[4],
            ccn_aero: o[5],
            in_aero: o[6],
            henry: o[7],
        };
    }
    let o = &one(rows, "out.grid", |_| true).args;
    WetSetup {
        fields,
        nest: NestFrame {
            xl: nestrow[0],
            xr: nestrow[1],
            yl: nestrow[2],
            yr: nestrow[3],
            xresol: nestrow[4],
            yresol: nestrow[5],
        },
        height,
        species,
        frame_mother: OutputFrame {
            dx: o[0],
            dy: o[1],
            xoutshift: o[2],
            youtshift: o[3],
            dxout: o[4],
            dyout: o[5],
        },
        frame_nest: OutputFrame {
            dx: o[0],
            dy: o[1],
            xoutshift: o[8],
            youtshift: o[9],
            dxout: o[10],
            dyout: o[11],
        },
        out_dims: [
            (o[6] as usize, o[7] as usize),
            (o[12] as usize, o[13] as usize),
        ],
    }
}

impl WetSetup {
    /// `memind1` is the storage slot (1-based) of the earlier field.
    fn met(&self, memind1: usize, readclouds: bool) -> WetScavMet {
        let order = |g: usize| {
            let (a, b) = if memind1 == 1 { (0, 1) } else { (1, 0) };
            WetGrid {
                slots: [self.fields[g][a].clone(), self.fields[g][b].clone()],
                readclouds,
            }
        };
        WetScavMet {
            memtime: [0, 10801],
            height: self.height.clone(),
            mother: order(0),
            nests: vec![(self.nest, order(1))],
        }
    }

    fn grid(&self, g: usize) -> DepositionGrid {
        let (nx, ny) = self.out_dims[g];
        DepositionGrid::zeros(nx, ny, 1, 2, 1, 1)
    }

    fn slice(grid: &DepositionGrid, kp: usize) -> Vec<f64> {
        let mut v = Vec::with_capacity(grid.nx * grid.ny);
        for jy in 0..grid.ny {
            for ix in 0..grid.nx {
                v.push(f64::from(grid.data[grid.index(ix, jy, 0, kp - 1, 0, 0)]));
            }
        }
        v
    }
}

struct WetDepoRun {
    masses: Vec<f64>,
    grids: [DepositionGrid; 2],
    counts: ScavCounts,
}

/// The driver echoes the integer `itra1` through `real()`. The inactive
/// marker `-999999999` is not representable in `f32` and prints as `-1e9` in
/// the real(4) fixture; it is the only such value (the others are small
/// multiples of 100 s), so it is mapped back here.
fn itra1_of(v: f64) -> i64 {
    if v <= -999_999_000.0 {
        -999_999_999
    } else {
        v as i64
    }
}

fn run_wetdepo(rows: &[Row], ws: &WetSetup, run: usize) -> WetDepoRun {
    let a = &one(rows, "wd.run", |r| r.args[0] as usize == run).args;
    let (itime, ltsample, loutnext, loutstep, ldirect) = (
        a[1] as i64,
        a[2] as i64,
        a[3] as i64,
        a[4] as i64,
        a[5] as i64,
    );
    let mut particles: Vec<ParticleRecord> = find(rows, "wd.particle")
        .filter(|r| r.args[0] as usize == run)
        .map(|r| {
            let p = &r.args;
            ParticleRecord {
                itra1: itra1_of(p[2]),
                itramem: p[3] as i64,
                xtra1: p[4],
                ytra1: p[5],
                ztra1: p[6],
                npoint: p[7] as usize,
                nclass: p[8] as usize,
                xmass1: vec![p[9]],
            }
        })
        .collect();
    let mut species = vec![ws.species[a[11] as usize - 1]];
    let met = ws.met(a[12] as usize, false);
    let settings = WetDepoSettings {
        ldirect,
        loutstep,
        lage: vec![86400],
        ioutputforeachrelease: a[8] == 1.0,
        decay: vec![a[9]],
        wetdepspec: vec![a[10] == 1.0],
    };
    let mut mother = WetOutputGrid {
        grid: ws.grid(0),
        frame: ws.frame_mother,
        rule: KernelRule::Mother { use_kernel: true },
    };
    let mut nested = WetOutputGrid {
        grid: ws.grid(1),
        frame: ws.frame_nest,
        rule: KernelRule::Nest,
    };
    let mut counts = ScavCounts {
        blc: vec![0],
        inc: vec![0],
    };
    wetdepo(
        itime,
        ltsample,
        loutnext,
        &mut particles,
        &mut species,
        &met,
        &settings,
        &mut mother,
        (a[7] == 1.0).then_some(&mut nested),
        &mut counts,
    )
    .expect("wetdepo");
    WetDepoRun {
        masses: particles.iter().map(|p| p.xmass1[0]).collect(),
        grids: [mother.grid, nested.grid],
        counts,
    }
}

// ── OH ────────────────────────────────────────────────────────────────────────

fn jr_formula(i: usize, j: usize, m: usize) -> f64 {
    // the driver's jr_formula: integer / 2^20, exact at both precisions
    ((i * 7 + j * 13 + m * 5) % 11) as f64 / 1_048_576.0
}

struct OhSetup {
    clim: OhClimatology,
    jr: JrateClimatology,
    bdate: f64,
    /// gethourlyOH results by (ldirect, itime)
    hourly: HashMap<(i64, i64), HourlyOh>,
    /// ohreaction masses by run
    masses: HashMap<usize, Vec<f64>>,
}

fn oh_setup(rows: &[Row]) -> OhSetup {
    let c = &one(rows, "oh.coords", |_| true).args;
    let (lon, lat, alt) = (c[0..8].to_vec(), c[8..14].to_vec(), c[14..18].to_vec());
    let (nx, ny, nz) = (8, 6, 4);
    let mut field = vec![0.0; nx * ny * nz * 12];
    for r in find(rows, "oh.field") {
        let (m, kz) = (r.args[0] as usize, r.args[1] as usize);
        let off = nx * ny * ((kz - 1) + nz * (m - 1));
        field[off..off + nx * ny].copy_from_slice(&r.outs);
    }
    let clim = OhClimatology {
        lon,
        lat,
        alt,
        field,
    };
    let mut average = vec![0.0; 360 * 180 * 12];
    for m in 1..=12 {
        for j in 1..=180 {
            for i in 1..=360 {
                average[(i - 1) + 360 * ((j - 1) + 180 * (m - 1))] = jr_formula(i, j, m);
            }
        }
    }
    let jr = JrateClimatology {
        lon: one(rows, "oh.lonjr", |_| true).args.clone(),
        lat: one(rows, "oh.latjr", |_| true).args.clone(),
        average,
    };
    let bdate = one(rows, "oh.bdate", |_| true).args[0];

    // replay the gethourlyOH sequences; the driver resets the state when the
    // direction changes
    let mut hourly = HashMap::new();
    let mut state = HourlyOh::empty(&clim);
    let mut last_dir = 0;
    for r in find(rows, "gethourlyOH") {
        let (ld, it) = (r.args[0] as i64, r.args[1] as i64);
        if ld != last_dir {
            state = HourlyOh::empty(&clim);
            last_dir = ld;
        }
        gethourly_oh(&mut state, it, ld, bdate, &clim, &jr);
        hourly.insert((ld, it), state.clone());
    }

    // ohreaction from the echoed state
    let st = &one(rows, "oh.state", |_| true).outs;
    let n3 = nx * ny * nz;
    let state = HourlyOh {
        memtime: [st[0], st[1]],
        hourly: [st[2..2 + n3].to_vec(), st[2 + n3..2 + 2 * n3].to_vec()],
    };
    let m = &one(rows, "oh.met", |_| true).args;
    let (mnx, mny) = (m[4] as usize, m[5] as usize);
    let height = m[6..12].to_vec();
    let mut tt_slots = [
        Field3::filled(mnx, mny, 6, 0.0),
        Field3::filled(mnx, mny, 6, 0.0),
    ];
    for r in find(rows, "oh.tt") {
        let (s, k) = (r.args[0] as usize - 1, r.args[1] as usize - 1);
        let n = mnx * mny;
        tt_slots[s].data[n * k..n * (k + 1)].copy_from_slice(&r.outs);
    }
    let met = OhMet {
        memtime: [0, 10801],
        height,
        tt_slots,
        dx: m[0],
        dy: m[1],
        xlon0: m[2],
        ylat0: m[3],
        nests: vec![NestFrame {
            xl: m[12],
            xr: m[13],
            yl: m[14],
            yr: m[15],
            xresol: m[16],
            yresol: m[17],
        }],
    };
    let mut masses = HashMap::new();
    for r in find(rows, "oh.run") {
        let a = &r.args;
        let run = a[0] as usize;
        let mut particles: Vec<ParticleRecord> = find(rows, "oh.particle")
            .filter(|p| p.args[0] as usize == run)
            .map(|p| ParticleRecord {
                itra1: itra1_of(p.args[2]),
                itramem: 0,
                xtra1: p.args[3],
                ytra1: p.args[4],
                ztra1: p.args[5],
                npoint: 1,
                nclass: 1,
                xmass1: vec![p.args[6]],
            })
            .collect();
        let sp = [OhSpecies {
            ohcconst: a[3],
            ohdconst: a[4],
            ohnconst: a[5],
        }];
        ohreaction(
            a[1] as i64,
            a[2] as i64,
            &mut particles,
            &sp,
            &met,
            &clim,
            &state,
        )
        .expect("ohreaction");
        masses.insert(run, particles.iter().map(|p| p.xmass1[0]).collect());
    }
    OhSetup {
        clim,
        jr,
        bdate,
        hourly,
        masses,
    }
}

// ── landuse ───────────────────────────────────────────────────────────────────

/// The driver's `fill_landinvent` (integers, so exact).
fn inventory() -> LanduseInventory {
    let mut classes = vec![[0i8; 3]; LUMAXX * LUMAXY];
    let mut weights = vec![[0i8; 3]; LUMAXX * LUMAXY];
    for j in 1..=LUMAXY {
        for i in 1..=LUMAXX {
            let c = (i - 1) + LUMAXX * (j - 1);
            classes[c] = [
                (1 + (i * 7 + j * 3) % 13) as i8,
                (1 + (i * 5 + j * 11 + 4) % 13) as i8,
                (1 + (i + j * 2 + 9) % 13) as i8,
            ];
            weights[c] = if i <= 25 {
                [0, 0, 0]
            } else {
                [
                    ((i + 2 * j) % 16) as i8,
                    ((3 * i + j) % 11) as i8,
                    ((i * j) % 7) as i8,
                ]
            };
        }
    }
    LanduseInventory { classes, weights }
}

/// `assignland` results by (call, grid): (nx, fractions per point).
type LanduseResults = HashMap<(usize, usize), (usize, Vec<[f64; NUMCLASS]>)>;

fn landuse_results(rows: &[Row], inv: &LanduseInventory) -> LanduseResults {
    let mut out = HashMap::new();
    for g in find(rows, "lu.grid") {
        let a = &g.args;
        let (c, gr) = (a[0] as usize, a[1] as usize);
        let geom = GridGeometry {
            nx: a[2] as usize,
            ny: a[3] as usize,
            dx: a[4],
            dy: a[5],
            xlon0: a[6],
            ylat0: a[7],
        };
        let lsm_row = one(rows, "lu.lsm", |r| {
            r.args[0] as usize == c && r.args[1] as usize == gr
        });
        let lsm = Field2 {
            nx: geom.nx,
            ny: geom.ny,
            data: lsm_row.outs.clone(),
        };
        let kind = if gr == 1 {
            LanduseGrid::Nest
        } else {
            LanduseGrid::Mother
        };
        let lu = assignland(inv, &geom, &lsm, kind).expect("assignland");
        out.insert((c, gr), (geom.nx, lu));
    }
    out
}

// ── setup per precision ───────────────────────────────────────────────────────

struct PrecisionSetup {
    calcpar: HashMap<usize, CalcparScenario>,
    wet: WetSetup,
    wetdepo: HashMap<usize, WetDepoRun>,
    oh: OhSetup,
    landuse: LanduseResults,
}

fn build(rows: &[Row], inv: &LanduseInventory) -> PrecisionSetup {
    let calcpar = (1..=7).map(|sc| (sc, run_scenario(rows, sc))).collect();
    let wet = wet_setup(rows);
    let wetdepo = (1..=4)
        .map(|run| (run, run_wetdepo(rows, &wet, run)))
        .collect();
    let oh = oh_setup(rows);
    let landuse = landuse_results(rows, inv);
    PrecisionSetup {
        calcpar,
        wet,
        wetdepo,
        oh,
        landuse,
    }
}

struct Setup {
    fx: Fixtures,
    s4: PrecisionSetup,
    s8: PrecisionSetup,
    inv: LanduseInventory,
}

fn setup() -> &'static Setup {
    static S: OnceLock<Setup> = OnceLock::new();
    S.get_or_init(|| {
        let fx = Fixtures::new(FIXTURE_REAL4, FIXTURE_REAL8, DP_FUNCTIONS);
        let inv = inventory();
        let s4 = build(&fx.real4, &inv);
        let s8 = build(&fx.real8, &inv);
        Setup { fx, s4, s8, inv }
    })
}

fn ps(p: Precision) -> &'static PrecisionSetup {
    let s = setup();
    match p {
        Precision::Real4 => &s.s4,
        Precision::Real8 => &s.s8,
    }
}

fn evaluate(r: &Row, p: Precision) -> Option<Vec<f64>> {
    let s = ps(p);
    let a = &r.args;
    Some(match r.function.as_str() {
        "calcpar" => {
            let sc = &s.calcpar[&(a[0] as usize)];
            let (ix, jy) = (a[1] as usize, a[2] as usize);
            let o = &sc.out;
            vec![
                o.ustar.at(ix, jy),
                o.oli.at(ix, jy),
                o.hmix.at(ix, jy),
                o.wstar.at(ix, jy),
                o.vdep.first().map_or(SENTINEL, |v| v.at(ix, jy)),
                o.tropopause[ix + sc.nx * jy].unwrap_or(SENTINEL),
            ]
        }
        "calcpv" => {
            let sc = &s.calcpar[&(a[0] as usize)];
            sc.out.pv.column(a[1] as usize, a[2] as usize)
        }
        "calcpar.z0water" => {
            let sc = &s.calcpar[&(a[0] as usize)];
            vec![sc.out.z0_water_last.unwrap_or(sc.z0_table7)]
        }
        "interpol_rain" => {
            let (g, m) = (a[0] as usize, a[1] as usize - 1);
            let f = &s.wet.fields[g][m];
            let q = interpol_rain(&f.lsprec, &f.convprec, &f.tcc, a[2], a[3]).expect("inside");
            vec![q.lsp, q.convp, q.cc, q.xt, q.yt]
        }
        "get_wetscav" => {
            // itime, ltsample, memind(1), readclouds, x, y, z, species id
            let met = s.wet.met(a[2] as usize, a[3] == 1.0);
            let mut sp = s.wet.species[a[7] as usize - 1];
            let w = get_wetscav(a[0] as i64, a[1] as i64, a[4], a[5], a[6], &mut sp, &met)
                .expect("defined");
            vec![
                w.wetscav,
                w.grfraction.unwrap_or(SENTINEL),
                f64::from(u8::from(w.counted == Some(ScavengingRegime::BelowCloud))),
                f64::from(u8::from(w.counted == Some(ScavengingRegime::InCloud))),
                sp.ccn_aero,
                sp.in_aero,
            ]
        }
        "wetdepokernel" => {
            // variant (0 mother, 2 nest), x, y, deposit, kp
            let (g, rule, frame) = if a[0] == 2.0 {
                (1, KernelRule::Nest, &s.wet.frame_nest)
            } else {
                (
                    0,
                    KernelRule::Mother { use_kernel: true },
                    &s.wet.frame_mother,
                )
            };
            let mut grid = s.wet.grid(g);
            let kp = a[4] as usize;
            wetdepokernel(rule, frame, a[1], a[2], &[a[3]], &mut grid, kp, 1, 1).expect("in range");
            WetSetup::slice(&grid, kp)
        }
        "wetdepo.mass" => vec![s.wetdepo[&(a[0] as usize)].masses[a[1] as usize - 1]],
        "wetdepo.grid" => WetSetup::slice(
            &s.wetdepo[&(a[0] as usize)].grids[a[1] as usize],
            a[2] as usize,
        ),
        "wetdepo.counts" => {
            let c = &s.wetdepo[&(a[0] as usize)].counts;
            vec![c.blc[0] as f64, c.inc[0] as f64]
        }
        "gethourlyOH" => {
            let h = &s.oh.hourly[&(a[0] as i64, a[1] as i64)];
            let mut v = vec![h.memtime[0], h.memtime[1]];
            v.extend(&h.hourly[0]);
            v.extend(&h.hourly[1]);
            v
        }
        "ohreaction" => vec![s.oh.masses[&(a[0] as usize)][a[1] as usize - 1]],
        "assignland" => {
            let (nx, lu) = &s.landuse[&(a[0] as usize, a[1] as usize)];
            lu[a[2] as usize + nx * a[3] as usize].to_vec()
        }
        _ => return None,
    })
}

fn all(_: &Row, _: Precision) -> bool {
    true
}

// ── setup cross-checks ────────────────────────────────────────────────────────

/// The two formula-generated tables agree with the driver's own values.
#[test]
fn formula_tables_match_driver() {
    let s = setup();
    for rows in [&s.fx.real4, &s.fx.real8] {
        for r in find(rows, "oh.jrcheck") {
            let (i, j, m) = (r.args[0] as usize, r.args[1] as usize, r.args[2] as usize);
            assert_eq!(jr_formula(i, j, m), r.outs[0], "jrate_average({i},{j},{m})");
        }
        for r in find(rows, "lu.check") {
            let (i, j) = (r.args[0] as usize, r.args[1] as usize);
            let c = (i - 1) + LUMAXX * (j - 1);
            let want: Vec<f64> = r.outs.clone();
            let got: Vec<f64> = s.inv.classes[c]
                .iter()
                .chain(s.inv.weights[c].iter())
                .map(|&v| f64::from(v))
                .collect();
            assert_eq!(got, want, "landinvent({i},{j},:)");
        }
    }
    let _ = (&s.s4.oh.jr, s.s4.oh.bdate, &s.s4.oh.clim);
}

// ── calcpar / calcpv ──────────────────────────────────────────────────────────

/// `calcpar.f90` (scenarios 1, 2, 4, 5) and `calcpar_nests.f90` (scenario
/// 3): `u*`, `1/L`, `h`, `w*`, `v_d` and the tropopause on every column.
///
/// The sweep covers ECMWF and NCEP input (NCEP `llev` at 2, 10 and the
/// `nuvz-1` cap), all `altmin` branches (rows at 60S..60N in 10° steps), a
/// zero surface stress (`u*` floored at `1e-8`), zero heat flux (`L = 9999`),
/// both `hmix` clamps, `lsubgrid` on and off, gas / particle / prescribed
/// species and `DRYDEP` off, snow cover, columns without a tropopause
/// (`None`, sentinel `-7`) and an NCEP tropical row that finds its tropopause
/// **only through the stale `kzmin`** left by the previous row.
///
/// # Real(8): 52 of 978 outputs differ by 1 ulp, cause identified
///
/// Measured max `3.7e-16`, all in `1/L` (and two `v_d` that inherit it). The
/// cause is in the already-ported `surface_layer::obukhov`, not here:
/// upstream evaluates `theta*ustar**2` as `theta*(ustar*ustar)`, the port as
/// `(theta*ustar)*ustar`. With the association corrected in a scratch copy,
/// every output of this group is bit-exact (2026-10-02). Reported, not fixed
/// here (that file belongs to stage 0).
///
/// # Real(4)
///
/// Two attributions, both measured:
/// - `h` (column 2) through `richardson`'s single precision: 6 outputs are
///   accepted by the precision-spread rule, the largest residual `6.2e-5`.
///   Because the driver feeds both builds identical inputs (see
///   [`calcpar_inputs_identical_in_both_builds`]) that spread is upstream's
///   arithmetic alone.
/// - `v_d` at `u* = 1e-8`: `1.26e-40 m/s` in real(8) and the port, `0` in the
///   shipped build, where the stable-branch `psi_h ~ (z/L)^1.5` overflows
///   `f32` and the resistance becomes infinite. Hence the `1e-30 m/s`
///   absolute floor, ten orders above that value and far below any physical
///   deposition velocity.
#[test]
fn calcpar_matches_flexpart() {
    check_group(
        &setup().fx,
        "calcpar",
        Bounds {
            tol8: 1e-13,
            floor8: 0.0,
            tol4: 1e-5,
            floor4: 1e-30,
            rule: Real4Rule::PrecisionSpreadOn(&[2]),
        },
        all,
        evaluate,
    );
}

/// `calcpar.f90`'s overwrite of `z0(7)`: the last value written.
#[test]
fn calcpar_z0_water_matches_flexpart() {
    check_group(
        &setup().fx,
        "calcpar.z0water",
        Bounds::rel(1e-14, 1e-6),
        all,
        evaluate,
    );
}

/// `calcpv.f90` (via `calcpar`, and directly on two global grids) and
/// `calcpv_nests.f90` (via `calcpar_nests`): limited-area edges, `xglobal`
/// wrap, both poles (`sglobal`/`nglobal`, one-sided rows and ring means), a
/// row uniform in x with two levels of identical `theta` (the `dt < 1e-5`
/// averaging branch), and a +20 K column (no bracket within `nuvz/3`
/// layers, so the gap shrinks or falls back to the same-level difference).
///
/// Real(8): 5192/5192 outputs bit-exact. Real(4): PV is a product of a
/// vertical `theta` difference of a few kelvin and horizontal wind
/// differences along interpolated `theta` surfaces; in `f32` it is good to
/// about `1e-3` (measured max `1.06e-3`), and 736 of 5192 outputs exceed
/// `1e-5`. The precision-spread rule accepts them; with identical inputs in
/// both builds (the port reproduces the real(8) build bit for bit from the
/// real(4) fixture's inputs) this is an exact statement that the residual
/// is FLEXPART's own single-precision arithmetic.
#[test]
fn calcpv_matches_flexpart() {
    check_group(
        &setup().fx,
        "calcpv",
        Bounds {
            rule: Real4Rule::PrecisionSpread,
            ..Bounds::rel(1e-12, 1e-5)
        },
        all,
        evaluate,
    );
}

// ── wet deposition ────────────────────────────────────────────────────────────

/// `interpol_rain.f90` (grid 0) and `interpol_rain_nests.f90` (grid 1),
/// including the in-place move of `xt`, `yt`, points in `(-1, 0)` and beyond
/// the last grid line.
///
/// Real(8) bit-exact. Real(4): 28 outputs at points moved to
/// `n-1 - 0.00001` exceed `1e-6` (max `1.36e-3`). Near 5.0 an `f32` holds
/// that offset to only ~5 %, so the interpolation weight of the last column
/// is a rounding residue; the moved `xt`, `yt` themselves (columns 3, 4) are
/// held strictly. Spread rule on the three interpolated fields only.
#[test]
fn interpol_rain_matches_flexpart() {
    check_group(
        &setup().fx,
        "interpol_rain",
        Bounds {
            rule: Real4Rule::PrecisionSpreadOn(&[0, 1, 2]),
            ..Bounds::rel(1e-14, 1e-6)
        },
        all,
        evaluate,
    );
}

/// `get_wetscav.f90` over six species, fourteen positions (mother and nest),
/// three times (including `nint` of an exact half, which picks the field),
/// both `memind` orders and both cloud-water sources. Covers: no
/// precipitation, cloud code <= 1, below cloud (gas; aerosol rain and snow;
/// counted but zero), in cloud (gas Henry, aerosol with the `ccn_aero < 0`
/// zeroing side effect, liquid / mixed / ice phase at exactly 253 and 273 K),
/// all five rate classes at their exact thresholds, and `cc = 0` with cloud
/// water read, where upstream's `grfraction/cc` gives NaN for a gas (the
/// port too).
///
/// Real(8) bit-exact. Real(4): the aerosol below-cloud coefficient
/// `10^(274 + 332840 L^-4 - 226657 L^-3 + ...)` cancels terms of order
/// `1e3` to an exponent of order 1, so its `f32` error is ~`1e-4` (measured
/// max `1.9e-4`, 48 outputs); spread rule on `wetscav` only.
#[test]
fn get_wetscav_matches_flexpart() {
    check_group(
        &setup().fx,
        "get_wetscav",
        Bounds {
            rule: Real4Rule::PrecisionSpreadOn(&[0]),
            ..Bounds::rel(1e-13, 1e-5)
        },
        all,
        evaluate,
    );
}

/// `wetdepokernel.f90` (variant 0) and `wetdepokernel_nest.f90` (variant
/// 2), including `ddx` exactly 0.5, the grid edges and the `(-1, -0.5]` band
/// where the mother routine's `int()` gives a negative weight.
///
/// Real(8) bit-exact (grids are `real(sp)` in both builds; the port adds in
/// `f64` and rounds once, as the real(8) build does). Real(4): at `y = 3.05`
/// the shipped build rounds `yl` to exactly 1.5, so the neighbour weight
/// `1 - wy` is 0, while the same `f32` input gives `3e-8` in `f64`. Such a
/// residue is at most deposit x 2^-23 x a few; with deposits up to 4.5 the
/// `1e-6` absolute floor covers it (measured residues `6.5e-8`).
#[test]
fn wetdepokernel_matches_flexpart() {
    check_group(
        &setup().fx,
        "wetdepokernel",
        Bounds {
            floor4: 1e-6,
            ..Bounds::rel(1e-14, 1e-6)
        },
        all,
        evaluate,
    );
}

/// `wetdepo.f90`: particle masses after four runs (forward with nested
/// output and per-release grids and decay; forward with `itime > loutnext`;
/// backward with `WETDEPSPEC` false; backward with a particle exactly at
/// `itra1 == itime`). Real(4) residuals come from `get_wetscav`'s aerosol
/// polynomial (2 outputs, max `1.7e-5`); spread rule.
#[test]
fn wetdepo_masses_match_flexpart() {
    check_group(
        &setup().fx,
        "wetdepo.mass",
        Bounds {
            rule: Real4Rule::PrecisionSpread,
            ..Bounds::rel(1e-14, 1e-6)
        },
        all,
        evaluate,
    );
}

/// `wetdepo.f90`: the gridded deposition (mother and nested output).
/// Real(4): the aerosol polynomial again (8 outputs, max `1.85e-4`, spread
/// rule), and kernel-weight residues as in [`wetdepokernel_matches_flexpart`]
/// of at most deposit x 2^-23 (deposits here <= 0.03 kg), under the `1e-8`
/// floor.
#[test]
fn wetdepo_grids_match_flexpart() {
    check_group(
        &setup().fx,
        "wetdepo.grid",
        Bounds {
            floor4: 1e-8,
            rule: Real4Rule::PrecisionSpread,
            ..Bounds::rel(1e-14, 1e-5)
        },
        all,
        evaluate,
    );
}

/// `wetdepo.f90`: below-/in-cloud counters.
#[test]
fn wetdepo_counts_match_flexpart() {
    check_group(
        &setup().fx,
        "wetdepo.counts",
        Bounds::rel(0.0, 0.0),
        all,
        evaluate,
    );
}

// ── OH ────────────────────────────────────────────────────────────────────────

/// `gethourlyOH.f90` over forward and backward sequences: initialisation,
/// in-range, one-hour advances crossing into February, a jump of more than
/// an hour (only one step taken), and re-initialisation.
///
/// Real(8) bit-exact. Real(4): `J(O1D)` near the horizon is
/// `exp(-0.4/cos(sza))` and amplifies the `f32` error of `cos` (stage 1
/// measured `3e-5` for `photo_O1D` alone); scaled by the climatology the
/// hourly fields differ by up to `7.6e-4` (100 outputs). Spread rule.
#[test]
fn gethourly_oh_matches_flexpart() {
    check_group(
        &setup().fx,
        "gethourlyOH",
        Bounds {
            rule: Real4Rule::PrecisionSpread,
            ..Bounds::rel(1e-13, 1e-5)
        },
        all,
        evaluate,
    );
}

/// `ohreaction.f90`: particle masses after four runs.
#[test]
fn ohreaction_matches_flexpart() {
    check_group(
        &setup().fx,
        "ohreaction",
        Bounds::rel(1e-14, 1e-6),
        all,
        evaluate,
    );
}

// ── landuse ───────────────────────────────────────────────────────────────────

/// `assignland.f90`: mother grids (regional with a no-data band; crossing
/// 180° up to 90°N) and a nest crossing 180°.
#[test]
fn assignland_matches_flexpart() {
    check_group(
        &setup().fx,
        "assignland",
        Bounds::rel(1e-14, 1e-6),
        all,
        evaluate,
    );
}

// ── input identity and refusals ───────────────────────────────────────────

/// The driver generates the `calcpar` / `calcpv` inputs in double precision
/// and rounds them once to real(4) in **both** builds, so the two fixtures
/// echo identical values. This is what makes the real(4) attribution of those
/// groups exact rather than statistical: the port fed the real(4) fixture's
/// inputs must reproduce the real(8) build bit for bit (up to the known
/// `obukhov` 1-ulp association, see [`calcpar_matches_flexpart`]).
#[test]
fn calcpar_inputs_identical_in_both_builds() {
    let s = setup();
    for name in [
        "cp.column",
        "cp.levels",
        "cp.species",
        "particle_bins",
        "wesely",
        "cp.grid",
    ] {
        let a: Vec<&Row> = find(&s.fx.real4, name).collect();
        let b: Vec<&Row> = find(&s.fx.real8, name).collect();
        assert_eq!(a.len(), b.len(), "{name}");
        for (x, y) in a.iter().zip(&b) {
            assert_eq!(x.args, y.args, "{name} echoes differ between builds");
        }
    }
    for name in ["calcpv", "calcpar.z0water"] {
        let r4: Vec<&Row> = find(&s.fx.real4, name).collect();
        let r8: Vec<&Row> = find(&s.fx.real8, name).collect();
        for (a, b) in r4.iter().zip(&r8) {
            assert_eq!(
                evaluate(a, Precision::Real4).unwrap(),
                b.outs,
                "{name}{:?}",
                a.args
            );
        }
    }
}

fn small_wet_met() -> WetScavMet {
    let fields = |rain: f64| WetFields {
        lsprec: Field2::filled(3, 3, rain),
        convprec: Field2::filled(3, 3, 0.0),
        tcc: Field2::filled(3, 3, 1.0),
        clouds: CloudField {
            nx: 3,
            ny: 3,
            nz: 3,
            data: vec![4; 27],
        },
        tt: Field3::filled(3, 3, 3, 280.0),
        ctwc: Field2::filled(3, 3, 0.0),
    };
    WetScavMet {
        memtime: [0, 3600],
        height: vec![0.0, 500.0, 1500.0],
        mother: WetGrid {
            slots: [fields(2.0), fields(2.0)],
            readclouds: false,
        },
        nests: Vec::new(),
    }
}

fn gas() -> WetScavSpecies {
    WetScavSpecies {
        dquer: -1.0,
        weta_gas: 1e-4,
        wetb_gas: 0.6,
        crain_aero: 0.0,
        csnow_aero: 0.0,
        ccn_aero: -1.0,
        in_aero: -1.0,
        henry: 0.0,
    }
}

/// Where upstream reads an unassigned level index (particle at or above the
/// top level while it rains), the port refuses; without rain upstream never
/// reaches that read, and neither does the port.
#[test]
fn get_wetscav_refuses_undefined_level() {
    use changi::flexpart::wet_deposition::WetDepError;
    let met = small_wet_met();
    let mut sp = gas();
    assert_eq!(
        get_wetscav(1800, 900, 1.0, 1.0, 1500.0, &mut sp, &met),
        Err(WetDepError::AboveTopLevel)
    );
    let mut dry = met.clone();
    for f in &mut dry.mother.slots {
        f.lsprec = Field2::filled(3, 3, 0.0);
    }
    assert!(get_wetscav(1800, 900, 1.0, 1.0, 1500.0, &mut sp, &dry).is_ok());
    assert!(get_wetscav(1800, 900, -1.5, 1.0, 100.0, &mut sp, &met).is_err());
}

/// `wetdepo` refuses the two upstream reads of undefined state: a forward
/// run with a `WETDEPSPEC = false` species (stale `wetdeposit`), and a
/// particle older than the last age class (`nage = nageclass + 1`).
#[test]
fn wetdepo_refuses_undefined_state() {
    use changi::flexpart::wet_deposition::WetDepError;
    let met = small_wet_met();
    let frame = OutputFrame {
        dx: 1.0,
        dy: 1.0,
        xoutshift: 0.0,
        youtshift: 0.0,
        dxout: 1.0,
        dyout: 1.0,
    };
    let particle = |age: i64| ParticleRecord {
        itra1: 3600,
        itramem: 3600 - age,
        xtra1: 1.0,
        ytra1: 1.0,
        ztra1: 100.0,
        npoint: 1,
        nclass: 1,
        xmass1: vec![1.0],
    };
    let run = |wetdepspec: bool, age: i64, ldirect: i64| {
        let mut out = WetOutputGrid {
            grid: DepositionGrid::zeros(3, 3, 1, 1, 1, 1),
            frame,
            rule: KernelRule::Mother { use_kernel: true },
        };
        let mut counts = ScavCounts {
            blc: vec![0],
            inc: vec![0],
        };
        let settings = WetDepoSettings {
            ldirect,
            loutstep: 3600,
            lage: vec![86400],
            ioutputforeachrelease: false,
            decay: vec![0.0],
            wetdepspec: vec![wetdepspec],
        };
        wetdepo(
            3600,
            900,
            3600,
            &mut [particle(age)],
            &mut [gas()],
            &met,
            &settings,
            &mut out,
            None,
            &mut counts,
        )
    };
    assert_eq!(run(false, 100, 1), Err(WetDepError::UndefinedDeposit));
    assert_eq!(run(false, 100, -1), Ok(()), "backward runs never grid");
    assert_eq!(run(true, 90000, 1), Err(WetDepError::AgeBeyondLastClass));
    assert_eq!(run(true, 100, 1), Ok(()));
}

/// `calcpar_nests` with NCEP input reads the never-assigned `dummyakzllev`;
/// `calcpv` with a one-point stencil reads an unassigned `vx(2)`.
#[test]
fn calcpar_refuses_undefined_cases() {
    use changi::flexpart::met_fields::MetFieldsError;
    let s = setup();
    let rows = &s.fx.real8;
    // any valid scenario input, reused with NCEP on a nest
    let geom = GridGeometry {
        nx: 1,
        ny: 3,
        dx: 1.0,
        dy: 1.0,
        xlon0: 0.0,
        ylat0: 0.0,
    };
    let f2 = Field2::filled(1, 3, 1.0e5);
    let f3 = Field3::filled(1, 3, 2, 280.0);
    let r = calcpv(
        &geom,
        GlobalDomain::LIMITED,
        &[0.0, 0.0],
        &[1.0, 0.5],
        &f2,
        &f3,
        &f3,
        &f3,
    );
    assert_eq!(r, Err(MetFieldsError::DegenerateStencil));
    let inp = CalcparInput {
        ps: f2.clone(),
        tt2: f2.clone(),
        td2: f2.clone(),
        surfstr: f2.clone(),
        sshf: f2.clone(),
        ssr: f2.clone(),
        lsprec: f2.clone(),
        convprec: f2.clone(),
        sd: f2.clone(),
        excessoro: f2.clone(),
        hmix_in: f2.clone(),
        tth: f3.clone(),
        qvh: f3.clone(),
        uuh: f3.clone(),
        vvh: f3.clone(),
        akz: vec![0.0, 0.0],
        bkz: vec![1.0, 0.5],
    };
    let opts = CalcparOptions {
        format: MetDataFormat::Ncep,
        kind: GridKind::Nest,
        lsubgrid: false,
        domain: GlobalDomain::LIMITED,
    };
    assert_eq!(
        calcpar(&geom, &opts, &inp, None).err(),
        Some(MetFieldsError::NestWithNcep)
    );
    let _ = rows;
}

/// `ohreaction` refuses the unassigned level index (particle above the top
/// level while OH is present).
#[test]
fn ohreaction_refuses_undefined_level() {
    use changi::flexpart::oh_chemistry::OhError;
    let s = ps(Precision::Real8);
    let clim = &s.oh.clim;
    let n3 = clim.lon.len() * clim.lat.len() * clim.alt.len();
    let hourly = HourlyOh {
        memtime: [0.0, 3600.0],
        hourly: [vec![1.0e6; n3], vec![1.0e6; n3]],
    };
    let met = OhMet {
        memtime: [0, 3600],
        height: vec![0.0, 500.0, 1500.0],
        tt_slots: [
            Field3::filled(3, 3, 3, 280.0),
            Field3::filled(3, 3, 3, 280.0),
        ],
        dx: 1.0,
        dy: 1.0,
        xlon0: 0.0,
        ylat0: 0.0,
        nests: Vec::new(),
    };
    let sp = [OhSpecies {
        ohcconst: 1e-17,
        ohdconst: 1500.0,
        ohnconst: 2.0,
    }];
    let mut p = vec![ParticleRecord {
        itra1: 0,
        itramem: 0,
        xtra1: 1.0,
        ytra1: 1.0,
        ztra1: 2000.0,
        npoint: 1,
        nclass: 1,
        xmass1: vec![1.0],
    }];
    assert_eq!(
        ohreaction(1800, 900, &mut p, &sp, &met, clim, &hourly),
        Err(OhError::AboveTopLevel)
    );
    p[0].ztra1 = 100.0;
    assert!(ohreaction(1800, 900, &mut p, &sp, &met, clim, &hourly).is_ok());
    assert!(p[0].xmass1[0] < 1.0);
}

/// `assignland` refuses an inventory class outside 1..=13 (written outside
/// the array upstream) and a sample left of the inventory (upstream stops).
#[test]
fn assignland_refuses_out_of_range() {
    use changi::flexpart::landuse::LanduseError;
    let s = setup();
    let lsm = Field2::filled(1, 1, 0.5);
    let geom = |xlon0: f64| GridGeometry {
        nx: 1,
        ny: 1,
        dx: 0.1,
        dy: 0.1,
        xlon0,
        ylat0: 10.0,
    };
    assert!(assignland(&s.inv, &geom(10.0), &lsm, LanduseGrid::Mother).is_ok());
    assert_eq!(
        assignland(&s.inv, &geom(-181.0), &lsm, LanduseGrid::Mother),
        Err(LanduseError::SamplingStop)
    );
    let mut bad = s.inv.clone();
    for c in &mut bad.classes {
        c[1] = 0;
    }
    assert_eq!(
        assignland(&bad, &geom(10.0), &lsm, LanduseGrid::Mother),
        Err(LanduseError::ClassOutOfRange)
    );
}
