//! ACER's **photo-nuclear** path — upstream `acer` with `iopt = 5`
//! (`acepn.f90`).
//!
//! A photo-nuclear table (`class u`) describes what a *photon* does to a
//! nucleus: the giant dipole resonance and above, where the photon knocks out
//! neutrons, protons and alphas. Structurally it is the richest ACE class,
//! because each emitted particle carries a full production sub-table —
//! cross section, heating, reaction list, angular and energy distributions —
//! addressed through a `NEIXS × NTYPE` locator array.
//!
//! [`layout`] is the shared description of that structure, walked exactly as
//! `phnout` writes it. It is what lets a table read from a file be written
//! back byte for byte, and it is the skeleton the builder fills.
//!
//! ## Status
//!
//! **Read and rewrite: done and gated.** A photo-nuclear table reads through
//! [`crate::acer::read`] like any other class, and
//! [`crate::acer::read::RawAceTable::derive_xss_is_int`] uses the walk here,
//! so a read-then-write round trip is byte-exact.
//!
//! **Build: done for the LANL-style path, and byte-exact.** [`build`] ports
//! `acephn` (`acepn.f90:27-1853`) for MF=3 plus MF=6 `LAW=1`/`LANG=1`, and
//! reproduces NJOY's own `acer iopt=5` output **byte for byte** (556 781
//! bytes, worst value difference 1.0e-13). Every representation it does not
//! cover returns [`crate::NjoyError::NotPorted`] naming itself rather than
//! writing a table that is quietly missing something; the list is in
//! `verification_and_validation/acer_photonuclear_vs_njoy2016.md`.
//!
//! ## Reference data
//!
//! `reference-data/endf/` holds no photo-nuclear sublibrary tape and the IAEA
//! NDS host this crate's `acquire` module downloads from is blocked by the
//! execution environment's network policy, so verification uses
//! `photonuc-synthetic-Z6.endf` — a synthetic NSUB=0 tape generated by the
//! committed script beside it and fed to **both** codes. That is the same
//! device `photoat-synthetic-Z6.endf` and `synthetic-caseb-lfw1.endf` already
//! use here: it verifies that the two codes agree, and claims nothing about
//! physics.

pub mod build;
pub mod layout;
