#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Authoring-time codegen: read one CoolProp fluid JSON (from the gitignored
# `reference/CoolProp/dev/fluids/`) and emit a hardcoded Rust `FluidEos` `const`
# for `src/fluids/`. This is a *data-reduction* step: it copies out only the
# Helmholtz-EOS coefficients (residual + ideal terms + reducing/critical
# params) — NOT the JSON's ANCILLARIES / TRANSPORT / metadata — so the shipped
# crate carries only kilobytes per fluid and never reads JSON at runtime.
#
# Usage (run from the crate root, with the reference clone present):
#   python3 dev/gen_fluid.py Water > src/fluids/water.rs
#
# The reference clone is regenerated with:
#   git clone --depth 1 https://github.com/CoolProp/CoolProp.git reference/CoolProp
import json, sys, os

def slice_f64(xs):
    return "&[" + ", ".join(repr(float(x)) for x in xs) + "]"

def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_fluid.py <FluidName>")
    fluid = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "reference", "CoolProp", "dev", "fluids", f"{fluid}.json")
    d = json.load(open(path))
    eos = d["EOS"][0]
    red = eos["STATES"]["reducing"]
    crit = d["STATES"]["critical"]
    const_name = fluid.upper().replace("-", "_")

    residual = []
    for t in eos["alphar"]:
        ty = t["type"]
        if ty == "ResidualHelmholtzPower":
            residual.append("    ResidualTerm::Power {{ n: {}, t: {}, d: {}, l: {} }},".format(
                slice_f64(t["n"]), slice_f64(t["t"]), slice_f64(t["d"]), slice_f64(t["l"])))
        elif ty == "ResidualHelmholtzGaussian":
            residual.append("    ResidualTerm::Gaussian {{ n: {}, t: {}, d: {}, eta: {}, epsilon: {}, beta: {}, gamma: {} }},".format(
                slice_f64(t["n"]), slice_f64(t["t"]), slice_f64(t["d"]),
                slice_f64(t["eta"]), slice_f64(t["epsilon"]), slice_f64(t["beta"]), slice_f64(t["gamma"])))
        elif ty == "ResidualHelmholtzNonAnalytic":
            residual.append("    ResidualTerm::NonAnalytic {{ n: {}, a: {}, b: {}, beta: {}, big_a: {}, big_b: {}, big_c: {}, big_d: {} }},".format(
                slice_f64(t["n"]), slice_f64(t["a"]), slice_f64(t["b"]), slice_f64(t["beta"]),
                slice_f64(t["A"]), slice_f64(t["B"]), slice_f64(t["C"]), slice_f64(t["D"])))
        else:
            sys.exit(f"unsupported residual term type: {ty} (extend the engine + codegen)")

    ideal = []
    for t in eos["alpha0"]:
        ty = t["type"]
        if ty == "IdealGasHelmholtzLead":
            ideal.append("    IdealTerm::Lead {{ a1: {!r}, a2: {!r} }},".format(float(t["a1"]), float(t["a2"])))
        elif ty == "IdealGasHelmholtzLogTau":
            ideal.append("    IdealTerm::LogTau {{ a: {!r} }},".format(float(t["a"])))
        elif ty == "IdealGasHelmholtzPlanckEinstein":
            ideal.append("    IdealTerm::PlanckEinstein {{ n: {}, t: {} }},".format(
                slice_f64(t["n"]), slice_f64(t["t"])))
        else:
            sys.exit(f"unsupported ideal term type: {ty} (extend the engine + codegen)")

    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("// GENERATED by dev/gen_fluid.py from CoolProp's {}.json (MIT).".format(fluid))
    out.append("// Do not edit by hand — re-run the generator. See dev/gen_fluid.py.")
    out.append("//! CoolProp `{}` Helmholtz EOS, as hardcoded `const` data.".format(fluid))
    out.append("")
    out.append("use crate::eos::{FluidEos, IdealTerm, ResidualTerm};")
    out.append("")
    out.append("/// {} Helmholtz equation of state (from CoolProp).".format(fluid))
    out.append("pub static {}: FluidEos = FluidEos {{".format(const_name))
    out.append('    name: "{}",'.format(fluid))
    out.append("    molar_mass: {!r},".format(float(eos["molar_mass"])))
    out.append("    gas_constant: {!r},".format(float(eos["gas_constant"])))
    out.append("    t_reducing: {!r},".format(float(red["T"])))
    out.append("    rho_reducing: {!r},".format(float(red["rhomolar"])))
    out.append("    t_critical: {!r},".format(float(crit["T"])))
    out.append("    rho_critical: {!r},".format(float(crit["rhomolar"])))
    out.append("    p_critical: {!r},".format(float(crit["p"])))
    out.append("    t_triple: {!r},".format(float(eos["Ttriple"])))
    out.append("    t_max: {!r},".format(float(eos["T_max"])))
    out.append("    p_max: {!r},".format(float(eos["p_max"])))
    out.append("    acentric: {!r},".format(float(eos["acentric"])))
    out.append("    residual: &[")
    out.extend(residual)
    out.append("    ],")
    out.append("    ideal: &[")
    out.extend(ideal)
    out.append("    ],")
    out.append("};")
    out.append("")
    print("\n".join(out))

if __name__ == "__main__":
    main()
