#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Regenerate the binary-pair table: run dev/gen_mixture.py over every
# CoolProp binary pair in the gitignored reference clone whose two
# components both resolve to a fluid already ported into this crate's
# `Fluid` enum, then rewrite `src/mixtures/binary_pairs/`. Mirrors
# dev/regen_all.py for the pure-fluid side.
#
# Usage (from the crate root, with reference/CoolProp present):
#   python3 dev/regen_mixture_all.py
#
# Component-name resolution is by CAS number (see dev/gen_mixture.py's
# module doc) -- `mixture_binary_pairs.json` uses REFPROP-style short names
# ("CYCLOHEX") that don't match this crate's canonical CoolProp names
# ("Cyclohexane") directly. A handful of components (6, as of this writing:
# e.g. R1216, isooctane) are not among this crate's 137 ported pure fluids;
# every binary pair touching one of them is skipped with a printed warning,
# not an error -- CoolProp's own mixture set is broader than the pure-fluid
# set this port covers today.
#
# Output is chunked into src/mixtures/binary_pairs/data_<n>.rs (~200 pairs
# each, ~1500 chars/pair worst case -> well under the workspace's 1000-line
# file-size convention) plus a hand-stable mod.rs holding the `BinaryPair`
# struct and `lookup()` (which searches every chunk in turn).
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)
FLUID_DIR = os.path.join(CRATE, "reference", "CoolProp", "dev", "fluids")
MIXTURE_DIR = os.path.join(CRATE, "reference", "CoolProp", "dev", "mixtures")
OUT_DIR = os.path.join(CRATE, "src", "mixtures", "binary_pairs")
CHUNK_SIZE = 200


def load_cas_map():
    cas_map = {}
    for fname in os.listdir(FLUID_DIR):
        if not fname.endswith(".json"):
            continue
        name = fname[:-5]
        with open(os.path.join(FLUID_DIR, fname)) as fh:
            d = json.load(fh)
        cas = d.get("INFO", {}).get("CAS")
        if cas:
            cas_map[cas] = name
    return cas_map


def main():
    cas_to_name = load_cas_map()
    with open(os.path.join(MIXTURE_DIR, "mixture_binary_pairs.json")) as fh:
        pairs = json.load(fh)

    entries, skipped, failed = [], [], []
    seen = set()
    for p in pairs:
        cas1, cas2 = p["CAS1"], p["CAS2"]
        if cas1 not in cas_to_name or cas2 not in cas_to_name:
            skipped.append((p["Name1"], p["Name2"]))
            continue
        name_a, name_b = cas_to_name[cas1], cas_to_name[cas2]
        key = frozenset((name_a, name_b))
        if key in seen:
            continue  # a few pairs are duplicated (different BibTeX) in the source; keep the first
        seen.add(key)

        r = subprocess.run([sys.executable, os.path.join(HERE, "gen_mixture.py"), name_a, name_b],
                           capture_output=True, text=True)
        if r.returncode != 0:
            failed.append((name_a, name_b, r.stderr.strip()))
            continue
        entries.append((name_a, name_b, r.stdout))

    if failed:
        for a, b, e in failed:
            print("FAILED", a, b, e, file=sys.stderr)
        sys.exit(f"{len(failed)} binary pair(s) failed to generate")

    os.makedirs(OUT_DIR, exist_ok=True)
    for old in os.listdir(OUT_DIR):
        if old.startswith("data_") and old.endswith(".rs"):
            os.remove(os.path.join(OUT_DIR, old))

    chunks = [entries[i:i + CHUNK_SIZE] for i in range(0, len(entries), CHUNK_SIZE)]
    for i, chunk in enumerate(chunks):
        needs_departure_term = any("DepartureTerm::" in literal for _, _, literal in chunk)
        with open(os.path.join(OUT_DIR, f"data_{i}.rs"), "w") as fh:
            fh.write(
                "// SPDX-License-Identifier: MIT\n"
                "// GENERATED by dev/regen_mixture_all.py -- do not edit by hand.\n"
                f"//! Binary-pair data, chunk {i} of {len(chunks)} ({len(chunk)} pairs) --\n"
                "//! see `dev/gen_mixture.py` and the parent module's doc.\n\n"
                "use super::BinaryPair;\n"
                + ("use crate::mixtures::departure::DepartureTerm;\n" if needs_departure_term else "")
                + "use crate::fluid::Fluid;\n\n"
                f"pub(super) static DATA: &[BinaryPair] = &[\n")
            for name_a, name_b, literal in chunk:
                fh.write(f"    // {name_a}-{name_b}\n    {literal},\n")
            fh.write("];\n")

    with open(os.path.join(OUT_DIR, "mod.rs"), "w") as fh:
        fh.write(
            "//! Binary **interaction parameters** and departure-function assignments for\n"
            "//! the multi-fluid mixture model -- CoolProp's `mixture_binary_pairs.json` +\n"
            "//! `mixture_departure_functions.json`, hardcoded.\n"
            "//!\n"
            f"//! **{len(entries)}** of CoolProp's {len(pairs)} binary pairs are ported (the rest\n"
            "//! touch a component outside this crate's 137 ported pure fluids -- see\n"
            "//! `dev/regen_mixture_all.py`'s module doc). Data lives in `data_<n>.rs`\n"
            f"//! ({len(chunks)} chunks, generated by `dev/gen_mixture.py` / `dev/regen_mixture_all.py`\n"
            "//! -- do not edit those by hand); this file is hand-maintained.\n"
            "//!\n"
            "//! A pair **absent** from the table is treated as ideal Lorentz-Berthelot\n"
            "//! combining (`β = γ = 1`, `F = 0`) by\n"
            "//! [`super::reducing`]/[`super::Mixture::residual_derivs`] -- matching\n"
            "//! CoolProp's own default for binary pairs it has no fitted data for, not an\n"
            "//! error condition. [`lookup`] returning `None` is the normal, common case.\n\n")
        for i in range(len(chunks)):
            fh.write(f"mod data_{i};\n")
        fh.write(
            "\n"
            "use crate::fluid::Fluid;\n"
            "use crate::mixtures::departure::DepartureTerm;\n\n"
            "/// The interaction data for one unordered pair of components `(i, j)`.\n"
            "///\n"
            "/// Holds the Lorentz-Berthelot reducing-function parameters ([`reducing`])\n"
            "/// and the departure-function scaling `F_{ij}` + term list ([`departure`]).\n"
            "///\n"
            "/// [`reducing`]: super::reducing\n"
            "/// [`departure`]: super::departure\n"
            "#[derive(Debug, Clone, Copy)]\n"
            "pub struct BinaryPair {\n"
            "    /// First component.\n"
            "    pub a: Fluid,\n"
            "    /// Second component.\n"
            "    pub b: Fluid,\n"
            "    /// Reducing-temperature parameters `(β^T, γ^T)`.\n"
            "    pub beta_gamma_t: (f64, f64),\n"
            "    /// Reducing-volume parameters `(β^v, γ^v)`.\n"
            "    pub beta_gamma_v: (f64, f64),\n"
            "    /// Departure-function scaling `F_{ij}` (0 ⇒ no departure term, ideal mixing).\n"
            "    pub f_departure: f64,\n"
            "    /// Departure-function term list (empty when `f_departure == 0`).\n"
            "    pub departure_terms: &'static [DepartureTerm],\n"
            "}\n\n"
            f"/// Every data chunk, searched in turn by [`lookup`] ({len(entries)} pairs total).\n"
            "static CHUNKS: &[&[BinaryPair]] = &[\n")
        for i in range(len(chunks)):
            fh.write(f"    data_{i}::DATA,\n")
        fh.write(
            "];\n\n"
            "/// Look up the interaction data for the unordered pair `(a, b)`.\n"
            "///\n"
            "/// Returns `None` when the pair is absent from the table -- the common\n"
            "/// case, treated as ideal combining (`β=γ=1`, `F=0`) by the callers, per\n"
            "/// the module doc.\n"
            "pub fn lookup(a: Fluid, b: Fluid) -> Option<&'static BinaryPair> {\n"
            "    all().find(|p| (p.a == a && p.b == b) || (p.a == b && p.b == a))\n"
            "}\n\n"
            f"/// Every ported binary pair, for enumeration ({len(entries)} in total).\n"
            "pub fn all() -> impl Iterator<Item = &'static BinaryPair> {\n"
            "    CHUNKS.iter().flat_map(|chunk| chunk.iter())\n"
            "}\n")

    print(f"regenerated {len(entries)} binary pairs across {len(chunks)} chunk(s) + mod.rs "
          f"({len(skipped)} pairs skipped -- component outside the 137 ported pure fluids)")


if __name__ == "__main__":
    main()
