#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Regenerate ALL incompressible fluids: run dev/gen_incompressible.py over
# every CoolProp incompressible-liquid JSON in the gitignored reference
# clone, then rewrite src/incompressibles/fluids/mod.rs and
# src/incompressibles/fluid_enum.rs so every fluid is declared and wired into
# the `Incompressible` enum. Mirrors dev/regen_all.py for the pure-fluid side.
#
# Usage (from the crate root, with upstream_source/CoolProp present):
#   python3 dev/regen_incompressible_all.py
#
# Naming (kept consistent with dev/gen_incompressible.py's `rust_const_ident`):
#   module  = lowercase, non-alnum -> '_', digit-leading -> 'f_'   (file name)
#   const   = UPPER,     non-alnum -> '_', digit-leading -> 'F_'    (in the file)
#   variant = CoolProp name, non-alnum removed, each token capitalised,
#             digit-leading -> 'F' prefix
import glob, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)


def module_name(fluid):
    s = re.sub(r"[^0-9a-zA-Z]", "_", fluid).lower()
    return "f_" + s if s and s[0].isdigit() else s


def const_name(fluid):
    s = "".join(ch if ch.isalnum() else "_" for ch in fluid).upper()
    return "F_" + s if s and s[0].isdigit() else s


def variant_name(fluid):
    toks = [t for t in re.split(r"[^0-9a-zA-Z]", fluid) if t]
    v = "".join(t[:1].upper() + t[1:] for t in toks)
    return "F" + v if v and v[0].isdigit() else v


def main():
    json_dir = os.path.join(CRATE, "upstream_source", "CoolProp", "dev", "incompressible_liquids", "json")
    names = sorted(os.path.basename(f)[:-5] for f in glob.glob(os.path.join(json_dir, "*.json")))
    if not names:
        sys.exit(f"no incompressible-liquid JSON found under {json_dir} (clone upstream_source first)")

    fluids_out = os.path.join(CRATE, "src", "incompressibles", "fluids")
    os.makedirs(fluids_out, exist_ok=True)
    for old in glob.glob(os.path.join(fluids_out, "*.rs")):
        if os.path.basename(old) != "mod.rs":
            os.remove(old)

    rows, failed = [], []
    for n in names:
        r = subprocess.run([sys.executable, os.path.join(HERE, "gen_incompressible.py"), n],
                           capture_output=True, text=True)
        if r.returncode != 0:
            failed.append((n, r.stderr.strip()))
            continue
        with open(os.path.join(fluids_out, module_name(n) + ".rs"), "w") as fh:
            fh.write(r.stdout)
        rows.append((variant_name(n), module_name(n), const_name(n) + "_INCOMP", n))

    if failed:
        for n, e in failed:
            print("FAILED", n, e, file=sys.stderr)
        sys.exit(f"{len(failed)} fluid(s) failed to generate")

    with open(os.path.join(fluids_out, "mod.rs"), "w") as fh:
        fh.write(
            "//! Hardcoded per-fluid coefficient blocks for the incompressible backend\n"
            "//! (`const IncompressibleFluid`), generated from CoolProp's\n"
            "//! incompressible-liquid JSON by `dev/gen_incompressible.py` (one file per\n"
            "//! fluid) and wired into [`super::fluid_enum::Incompressible`].\n"
            "//!\n"
            "//! Regenerate the whole set with `dev/regen_incompressible_all.py` (see the\n"
            "//! crate README).\n\n")
        for row in sorted(rows, key=lambda r: r[1]):
            fh.write(f"pub mod {row[1]};\n")

    with open(os.path.join(CRATE, "src", "incompressibles", "fluid_enum.rs"), "w") as fh:
        fh.write(
            "//! The incompressible-fluid selector — an **enum**, matching each fluid to\n"
            "//! its hardcoded [`IncompressibleFluid`](super::IncompressibleFluid). The\n"
            "//! enum-dispatch replacement for CoolProp's string-keyed `INCOMP::<name>`\n"
            "//! lookup: adding a fluid is a new variant, and every `match` on\n"
            "//! `Incompressible` becomes exhaustive.\n"
            "//!\n"
            "//! GENERATED by `dev/regen_incompressible_all.py` — do not edit by hand.\n"
            "//! Variant names follow the CoolProp fluid name with non-alphanumerics\n"
            "//! removed (e.g. `HC10` stays `HC10`); [`Incompressible::name`] returns the\n"
            "//! original CoolProp name.\n\n"
            "use super::fluids;\n"
            "use super::IncompressibleFluid;\n\n"
            f"/// A supported incompressible fluid (one per CoolProp `INCOMP` entry, {len(rows)}\n"
            "/// in total). Each variant maps to a hardcoded `const` [`IncompressibleFluid`]\n"
            "/// via [`Incompressible::data`].\n"
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n"
            "#[non_exhaustive]\n"
            "#[allow(non_camel_case_types)]\n"
            "pub enum Incompressible {\n")
        for var, _, _, n in sorted(rows):
            fh.write(f"    /// CoolProp `{n}`.\n    {var},\n")
        fh.write("}\n\nimpl Incompressible {\n")
        fh.write(f"    /// Every supported fluid, for enumeration ({len(rows)} in total).\n")
        fh.write("    pub const ALL: &'static [Incompressible] = &[\n")
        for var, _, _, _ in sorted(rows):
            fh.write(f"        Incompressible::{var},\n")
        fh.write("    ];\n\n")
        fh.write("    /// The original CoolProp fluid name (not the Rust variant identifier).\n"
                 "    pub fn name(self) -> &'static str {\n"
                 "        self.data().name\n    }\n\n")
        fh.write("    /// The hardcoded coefficient block for this fluid.\n"
                 "    pub fn data(self) -> &'static IncompressibleFluid {\n"
                 "        match self {\n")
        for var, mod, const, _ in sorted(rows):
            fh.write(f"            Incompressible::{var} => &fluids::{mod}::{const},\n")
        fh.write("        }\n    }\n}\n")

    print(f"regenerated {len(rows)} incompressible fluids + fluids/mod.rs + fluid_enum.rs")


if __name__ == "__main__":
    main()
