#!/usr/bin/env python3
"""HTR-10 k_eff against loading height, ENDF/B-VIII.0, heavy sweep.

Generated by nee_soon::htr10_rmc::keff_vs_height::script::plot_script
(example `htr10_endf8_kvsh_heavy`, gh:#501). Every number is embedded; nothing is read from
disk, so this file alone redraws the figure. Needs matplotlib only.

Usage: python3 <this script> [out.png]   (default: <this script>.png)

Reference curves are the constants RMC_KEFF_VS_HEIGHT,
MCNP_TABLE3_KEFF_VS_HEIGHT and MCNP_TABLE4_KEFF_VS_HEIGHT of
crates/nee_soon/src/htr10_rmc/mod.rs, written out by the emitter.
Each model point sits at the height where Seker & Colak (2003)'s model
holds as many balls as the built bed (gh:#472); every reference value
below is read there by linear interpolation.
"""
import pathlib
import sys
import textwrap

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ---- data (embedded by the emitter) --------------------------------------
LIBRARY = "ENDF/B-VIII.0"
SWEEP = "heavy"
# (N, balls, built height cm, reference height cm, k, sigma, RMC, MCNP T3, MCNP T4)
POINTS = [
    (10, 14021, 103.980, 102.728, 0.926453, 0.001077, 0.931700, 0.925158, 0.926201),
    (11, 15351, 113.778, 112.409, 0.966199, 0.001008, 0.967269, 0.964468, 0.964382),
    (12, 16681, 123.576, 122.091, 0.995663, 0.001136, 0.999419, 0.998250, 0.999476),
    (13, 18011, 133.373, 131.773, 1.027693, 0.001037, 1.026415, 1.028698, 1.027829),
    (14, 19341, 143.171, 141.454, 1.051335, 0.001085, 1.052285, 1.054062, 1.055396),
    (15, 20671, 152.969, 151.136, 1.075658, 0.001149, 1.074407, 1.080117, 1.078506),
    (16, 22001, 162.767, 160.817, 1.094468, 0.001111, 1.093602, 1.099360, 1.098301),
    (17, 23331, 172.565, 170.499, 1.113519, 0.001034, 1.111103, 1.118262, 1.118197),
    (18, 24661, 182.363, 180.180, 1.133894, 0.001170, 1.129620, 1.135325, 1.134409),
    (19, 25991, 192.161, 189.862, 1.147874, 0.000924, 1.144356, 1.153901, 1.152369),
    (20, 27321, 201.959, 199.543, 1.161718, 0.000964, 1.158614, 1.168608, 1.166548),
]
RMC = [
    (94.182, 0.894693),
    (103.980, 0.937122),
    (113.778, 0.972163),
    (123.576, 1.004288),
    (133.374, 1.030738),
    (143.172, 1.056866),
    (152.970, 1.078448),
    (162.768, 1.097370),
    (172.566, 1.114775),
    (182.364, 1.133878),
    (192.162, 1.147570),
    (201.960, 1.162230),
]
MCNP_T3 = [
    (94.182, 0.888560),
    (103.980, 0.930520),
    (113.778, 0.969980),
    (123.576, 1.003300),
    (133.374, 1.033660),
    (143.172, 1.058400),
    (152.970, 1.085120),
    (162.768, 1.102900),
    (172.566, 1.122370),
    (182.364, 1.139040),
    (192.162, 1.158460),
    (201.960, 1.171930),
]
MCNP_T4 = [
    (94.182, 0.890440),
    (103.980, 0.931440),
    (113.778, 0.969730),
    (123.576, 1.004790),
    (133.374, 1.032330),
    (143.172, 1.060300),
    (152.970, 1.082700),
    (162.768, 1.102180),
    (172.566, 1.122480),
    (182.364, 1.137830),
    (192.162, 1.156830),
    (201.960, 1.169730),
]
FOOTER = [
    "10000 particles x [5 inactive + 135 active], seed 20260917, one seed per point; error bars are the within-run 1 sigma (the references quote none).",
    "ENDF/B-VIII.0, Seker 13-ball bed, 14 rings, 300.15 K; graphite S(a,b) Reactor30P, SiC and UO2 bound laws; carbon Natural; coolant Helium; rod metal FULL: real Ni-58/60/61/62/64 and Fe-54/56/57/58; TECDOC-1382 reflector zone 22, natural boron, fixed core cavity.",
    "commit eb5ee78b69, reference-data/ace 6440b6dfe0, example htr10_endf8_kvsh_heavy; 8 transport threads per run, CPUs 0-9.",
    "host: NVIDIA RTX A5000 / Vulkan, 10 cores, linux, 13th Gen Intel(R) Core(TM) i9-13900K, 62.5 GiB RAM (shared machine; GPU, if listed, detected but not used).",
    "thick solid = published (Li, Yu & Wei 2014; Seker & Colak 2003); markers on a dotted line = this project's calculation (not validated); dashed = guides.",
]

# ---- style: dataviz reference palette, light mode ----------------------------
MODEL = "#2a78d6"   # categorical slot 1: this project's calculation
INK = "#0b0b0b"     # RMC, the reference
T3 = "#eb6834"      # categorical slot 2: MCNP Table 3 (vacuum), gauge
T4 = "#1baf7a"      # categorical slot 3: MCNP Table 4 (helium), gauge
MUTED = "#8a8985"
GRID = "#e4e3df"
SURFACE = "#fcfcfb"
TEXT2 = "#52514e"


def residuals(col):
    """(height, pcm, sigma pcm) of every point that has reference column col."""
    return [(p[3], (p[4] - p[col]) * 1e5, p[5] * 1e5) for p in POINTS if p[col] is not None]


def model_bars(ax, pts, color, marker, label, dx=0.0, filled=True):
    xs = [h + dx for h, _, _ in pts]
    ax.plot(xs, [v for _, v, _ in pts], color=color, lw=0.8, ls=":")
    ax.errorbar(xs, [v for _, v, _ in pts], yerr=[e for _, _, e in pts], color=color,
                marker=marker, ms=7, ls="none", elinewidth=1.5, capsize=3,
                mfc=color if filled else SURFACE, mec=color if not filled else SURFACE,
                mew=1.3, label=label)


def bands(ax):
    ax.axhspan(-1000, 1000, color=GRID, alpha=0.55, lw=0)
    ax.axhspan(-500, 500, color=GRID, lw=0)
    for y in (-1000, -500, 500, 1000):
        ax.axhline(y, color=MUTED, lw=0.6, ls="--")
    ax.axhline(0, color=INK, lw=0.9, ls="--")


def main():
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).with_suffix(".png")
    plt.rcParams.update({"font.size": 9.5, "axes.edgecolor": MUTED, "axes.labelcolor": TEXT2,
                         "xtick.color": TEXT2, "ytick.color": TEXT2})
    fig, (ax, ax_rmc, ax_mcnp) = plt.subplots(
        3, 1, figsize=(8.4, 10.6), sharex=True, facecolor=SURFACE,
        gridspec_kw={"height_ratios": [3, 1.7, 1.7]})
    for a in (ax, ax_rmc, ax_mcnp):
        a.set_facecolor(SURFACE)
        a.grid(True, color=GRID, lw=0.8)
        a.set_axisbelow(True)
        for sp in ("top", "right"):
            a.spines[sp].set_visible(False)

    # Panel 1: k against height. Published curves thick solid.
    ax.plot(*zip(*RMC), color=INK, lw=2.6, label="RMC, Li, Yu & Wei 2014, ENDF/B-VII.0 (reference)")
    ax.plot(*zip(*MCNP_T3), color=T3, lw=2.6, alpha=0.85,
            label="MCNP, Li Table 3 = Seker vacuum, ENDF/B-VI (gauge)")
    ax.plot(*zip(*MCNP_T4), color=T4, lw=2.6, alpha=0.85,
            label="MCNP, Li Table 4 = Seker helium, ENDF/B-VI (gauge)")
    ax.axhline(1.0, color=MUTED, lw=0.8, ls="--")
    model_bars(ax, [(p[3], p[4], p[5]) for p in POINTS], MODEL, "o",
               f"this model, {LIBRARY}, ±1σ (outram-mc, not validated)")
    ax.set_ylabel("k_eff")
    ax.set_title(f"HTR-10 k_eff vs loading height, {LIBRARY} ({SWEEP} sweep)",
                 loc="left", color=INK, fontsize=12)
    ax.legend(frameon=False, fontsize=8, loc="upper left")

    # Panel 2: k - RMC.
    bands(ax_rmc)
    model_bars(ax_rmc, residuals(6), INK, "o", "k − RMC (reference), ±1σ")
    ax_rmc.set_ylabel("k − RMC [pcm]")
    ax_rmc.legend(frameon=False, fontsize=8, loc="lower right", bbox_to_anchor=(1.0, 1.0))

    # Panel 3: k - MCNP, both columns, dodged so the bars do not overlap.
    bands(ax_mcnp)
    model_bars(ax_mcnp, residuals(7), T3, "s", "k − MCNP T3 (vacuum, gauge), ±1σ", dx=-0.6)
    model_bars(ax_mcnp, residuals(8), T4, "D", "k − MCNP T4 (helium, gauge), ±1σ", dx=0.6,
               filled=False)
    ax_mcnp.set_ylabel("k − MCNP [pcm]")
    ax_mcnp.set_xlabel("loading height at equal ball count with Seker's model [cm] (gh:#472)")
    ax_mcnp.legend(frameon=False, fontsize=8, loc="lower right", bbox_to_anchor=(1.0, 1.0), ncol=2)
    for a in (ax_rmc, ax_mcnp):
        a.text(0.005, 0.97, "bands: ±500, ±1000 pcm", transform=a.transAxes, va="top",
               fontsize=7.5, color=TEXT2)
    lim = max([1100.0] + [abs(v) + e + 100 for c in (6, 7, 8) for _, v, e in residuals(c)])
    for a in (ax_rmc, ax_mcnp):
        a.set_ylim(-lim, lim)
    ax_mcnp.set_xlim(90, 212)

    lines = [w for line in FOOTER for w in textwrap.wrap(line, 150)]
    fig.text(0.01, 0.004, "\n".join(lines), fontsize=6.6, color=TEXT2, va="bottom")
    fig.tight_layout(rect=(0, 0.012 * len(lines) + 0.01, 1, 1))
    fig.savefig(out, dpi=150, facecolor=SURFACE)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
