//! Markdown output generators — KOVAN's deliverable artifacts.
//!
//! Per `docs/kovan.md` ("# KOVAN Semantics" → "Outputs"), KOVAN prefers
//! **generated Markdown**, not hidden databases. This module renders the
//! catalogued [`KovanSymbol`]s into two of the documented artifacts:
//!
//! - [`symbols_markdown`] → `symbols.md`
//! - [`repository_summary_markdown`] → `repository-summary.md`
//!
//! Since the `kovan-common` v2 pass, [`KovanSymbol`] carries the file/line
//! location and language directly, so these renderers work off the shared type
//! alone (no crate-local `ExtractedSymbol` needed here). Feed them the output of
//! [`crate::catalogue_symbols`].
//!
//! Rendering is deterministic: symbols are sorted by `(file, line)` and kind
//! counts by kind name, so re-running the scan on an unchanged tree yields a
//! byte-identical document (KOVAN's determinism + reviewable-artifact mandate).

use std::collections::BTreeMap;

use kovan_common::{KovanRepository, KovanSymbol};

use crate::extract::SymbolKind;

/// All symbol kinds in a stable display order, for deterministic count tables.
const KIND_ORDER: &[SymbolKind] = &[
    SymbolKind::Module,
    SymbolKind::Namespace,
    SymbolKind::Struct,
    SymbolKind::Class,
    SymbolKind::Enum,
    SymbolKind::Union,
    SymbolKind::Trait,
    SymbolKind::Type,
    SymbolKind::Impl,
    SymbolKind::Function,
    SymbolKind::Subroutine,
];

/// Count symbols per kind, preserving [`KIND_ORDER`] and dropping empties.
///
/// A [`KovanSymbol::kind`] is free text (it comes from
/// [`SymbolKind::as_str`]); kinds outside [`KIND_ORDER`] are simply not
/// listed, matching the previous behaviour.
fn counts_by_kind(symbols: &[KovanSymbol]) -> Vec<(SymbolKind, usize)> {
    let mut map: BTreeMap<&str, usize> = BTreeMap::new();
    for s in symbols {
        *map.entry(s.kind.as_str()).or_default() += 1;
    }
    KIND_ORDER
        .iter()
        .filter_map(|&k| {
            let n = map.get(k.as_str()).copied().unwrap_or(0);
            (n > 0).then_some((k, n))
        })
        .collect()
}

/// Sort a copy of `symbols` by `(file, line)` for stable output.
fn sorted(symbols: &[KovanSymbol]) -> Vec<&KovanSymbol> {
    let mut v: Vec<&KovanSymbol> = symbols.iter().collect();
    v.sort_by(|a, b| a.file.cmp(&b.file).then(a.line.cmp(&b.line)));
    v
}

/// Render `symbols.md`: a title, a per-kind count table, and a full symbol
/// table (`qualified name` | `kind` | `location`). Deterministic.
///
/// `repo_name` is used only for the heading. Safe on an empty slice (renders the
/// heading and an "no symbols found" note).
pub fn symbols_markdown(repo_name: &str, symbols: &[KovanSymbol]) -> String {
    let mut md = String::new();
    md.push_str(&format!("# Symbols — {repo_name}\n\n"));
    md.push_str(
        "> Generated by `kovan-semantics` (ripgrep-first heuristic). \
Qualified names are best-effort; see the crate docs for known limits.\n\n",
    );

    if symbols.is_empty() {
        md.push_str("_No symbols found._\n");
        return md;
    }

    md.push_str(&format!("Total symbols: **{}**\n\n", symbols.len()));

    md.push_str("## Counts by kind\n\n");
    md.push_str("| Kind | Count |\n|---|---|\n");
    for (kind, n) in counts_by_kind(symbols) {
        md.push_str(&format!("| {} | {} |\n", kind.as_str(), n));
    }
    md.push('\n');

    md.push_str("## All symbols\n\n");
    md.push_str("| Symbol | Kind | Location |\n|---|---|---|\n");
    for s in sorted(symbols) {
        md.push_str(&format!(
            "| `{}` | {} | `{}:{}` |\n",
            s.qualified_name, s.kind, s.file, s.line
        ));
    }
    md
}

/// Render `repository-summary.md`: the repository identity plus a per-kind
/// symbol count and the number of distinct source files touched. Deterministic.
///
/// Takes the catalogued `symbols` so the summary reflects a real scan; pass an
/// empty slice before a scan has run.
pub fn repository_summary_markdown(repo: &KovanRepository, symbols: &[KovanSymbol]) -> String {
    let mut files: Vec<_> = symbols.iter().map(|s| s.file.clone()).collect();
    files.sort();
    files.dedup();

    let mut md = String::new();
    md.push_str(&format!("# Repository summary — {}\n\n", repo.name));
    md.push_str("| Field | Value |\n|---|---|\n");
    md.push_str(&format!("| ID | `{}` |\n", repo.id));
    md.push_str(&format!("| Name | {} |\n", repo.name));
    md.push_str(&format!("| Primary language | {} |\n", repo.language));
    md.push_str(&format!(
        "| Source files with symbols | {} |\n",
        files.len()
    ));
    md.push_str(&format!("| Total symbols | {} |\n\n", symbols.len()));

    if !symbols.is_empty() {
        md.push_str("## Symbol counts\n\n");
        md.push_str("| Kind | Count |\n|---|---|\n");
        for (kind, n) in counts_by_kind(symbols) {
            md.push_str(&format!("| {} | {} |\n", kind.as_str(), n));
        }
        md.push('\n');
    }

    md.push_str(
        "_Generated by `kovan-semantics`. Ripgrep-first heuristic — not a \
compiler-accurate index; escalate to the language-server path for full \
fidelity._\n",
    );
    md
}

#[cfg(test)]
mod tests {
    use super::*;
    use kovan_common::Language;

    fn sym(name: &str, kind: SymbolKind, line: u32) -> KovanSymbol {
        KovanSymbol {
            id: format!("repo::src/lib.rs:{line}::{name}"),
            qualified_name: name.to_string(),
            kind: kind.as_str().to_string(),
            repository_id: "repo".to_string(),
            file: "src/lib.rs".to_string(),
            line,
            language: Language::Rust,
        }
    }

    #[test]
    fn symbols_markdown_is_deterministic_and_lists_symbols() {
        let syms = vec![
            sym("beta", SymbolKind::Struct, 10),
            sym("alpha", SymbolKind::Function, 3),
        ];
        let a = symbols_markdown("demo", &syms);
        let b = symbols_markdown("demo", &syms);
        assert_eq!(a, b, "same input must render identically");
        // Sorted by line: alpha (3) before beta (10).
        let ia = a.find("alpha").unwrap();
        let ib = a.find("beta").unwrap();
        assert!(ia < ib);
        assert!(a.contains("Total symbols: **2**"));
    }

    #[test]
    fn empty_symbols_render_a_note() {
        let md = symbols_markdown("demo", &[]);
        assert!(md.contains("_No symbols found._"));
    }

    #[test]
    fn repository_summary_counts_files_and_kinds() {
        let repo = KovanRepository {
            id: "tampines".into(),
            name: "TAMPINES".into(),
            language: "Rust".into(),
        };
        let syms = vec![
            sym("a", SymbolKind::Function, 1),
            sym("b", SymbolKind::Function, 2),
            sym("C", SymbolKind::Struct, 3),
        ];
        let md = repository_summary_markdown(&repo, &syms);
        assert!(md.contains("Total symbols | 3"));
        assert!(md.contains("Source files with symbols | 1"));
        assert!(md.contains("| fn | 2 |"));
        assert!(md.contains("| struct | 1 |"));
    }
}
