//! Stochastic-media transport — random geometry that is *sampled* rather than stored.
//!
//! A stochastic (random) medium is one whose geometry is not known deterministically:
//! dispersion fuel, TRISO kernels scattered through a graphite matrix, burnable-poison
//! particles in an absorber. The defining problem is scale — a pebble holds O(10⁴) fuel
//! kernels and a core O(10⁵) pebbles — so the practical question is *how much of that
//! geometry a transport calculation actually has to remember*.
//!
//! This module is the research track for that question. Three model families sit on a
//! memory/fidelity spectrum:
//!
//! | Model | Geometry stored | Point membership | Cost |
//! |---|---|---|---|
//! | Explicit / RSA ([`medium::RsaMedium`]) | all of it | exact | O(N) memory |
//! | SCLS ([`scls::SclsMedium`]) | a moving local window | partial | bounded |
//! | CLS ([`cls::ClsMedium`]) | none | sampled | O(1) memory |
//!
//! - **[`medium`]** — the unifying [`medium::StochasticMedium`] enum: one "which
//!   material is here?" query across all three models, dispatched by `match`.
//! - **[`cls`]** — Chord Length Sampling: inclusion crossings re-sampled from
//!   closed-form chord statistics. Cheap and memoryless, so it forgets geometry.
//! - **[`scls`]** — Semi-Implicit CLS: CLS plus a bounded window of remembered
//!   inclusions, governed by the Dynamic Inclusion Sphere ([`scls::InclusionSphere`],
//!   radius `λ_TMFP + R_largest`). The primary research target.
//! - **[`spatial_index`]** — the acceleration seam for SCLS history lookup, the
//!   anticipated bottleneck.
//!
//! # Why this is not inside `pebble_beds`
//!
//! [`crate::pebble_beds`] is the *pebble-bed reactor* specialization — delta tracking
//! and the doubly-heterogeneous k-eigenvalue assembly. The methods here are broader
//! than that application: chord-length sampling applies to any binary random medium,
//! including dispersion fuel and burnable-poison particles that have nothing to do with
//! pebbles. Keeping them separate stops a general method from being filed under one
//! reactor type.
//!
//! The two do meet: [`medium::RsaMedium`] wraps the RSA packing generated by
//! [`crate::pebble_beds::sphere_packing`], which stays where it is because the
//! delta-tracking path depends on it directly.
//!
//! # Status: scaffold
//!
//! The chord statistics, the SCLS retention machinery and the brute-force index are
//! implemented and unit-tested. The **CLS and SCLS transport drivers are not** — those
//! paths return typed `NotImplemented` errors rather than fabricated answers.
//!
//! **No accuracy claim is made for CLS or SCLS.** Whether either reproduces the
//! explicit-RSA reference is an empirical question the benchmark suite (bead
//! `op-eby.7`) must measure before anything here may be called validated.
//!
//! Scaffolded per the *OUTRAM-MC Design Scaffold v0.1* (Theodore Ong, Zhe Chuan Tan),
//! tracked under beads epic `op-eby`. This is **new work**, not an OpenMC port —
//! upstream has no CLS or SCLS — so the crate's "mirror the canonical source" rule does
//! not apply here (see the crate `CLAUDE.md`: new parts are scaffolded only where
//! genuinely absent upstream).

pub mod cls;
pub mod medium;
pub mod scls;
pub mod spatial_index;
