//! Stochastic-media transport — random geometry that is *sampled* rather than stored.
//!
//! A stochastic (random) medium is one whose geometry is not known deterministically:
//! dispersion fuel, TRISO kernels scattered through a graphite matrix, burnable-poison
//! particles in an absorber. The defining problem is scale — a pebble holds O(10⁴) fuel
//! kernels and a core O(10⁵) pebbles — so the practical question is *how much of that
//! geometry a transport calculation actually has to remember*.
//!
//! This module is the research track for that question. Three model families sit on a
//! memory/fidelity spectrum:
//!
//! | Model | Geometry stored | Point membership | Cost |
//! |---|---|---|---|
//! | Explicit / RSA ([`medium::RsaMedium`]) | all of it | exact | O(N) memory |
//! | SCLS ([`scls::SclsMedium`]) | a moving local window | partial | bounded |
//! | CLS ([`cls::ClsMedium`]) | none | sampled | O(1) memory |
//!
//! - **[`medium`]** — the unifying [`medium::StochasticMedium`] enum: one "which
//!   material is here?" query across all three models, dispatched by `match`.
//! - **[`cls`]** — Chord Length Sampling: inclusion crossings re-sampled from
//!   closed-form chord statistics. Cheap and memoryless, so it forgets geometry.
//! - **[`scls`]** — Semi-Implicit CLS: CLS plus a bounded window of remembered
//!   inclusions, governed by the Dynamic Inclusion Sphere ([`scls::InclusionSphere`],
//!   radius `λ_TMFP + R_largest`). The primary research target.
//! - **[`spatial_index`]** — the acceleration seam for SCLS history lookup, the
//!   anticipated bottleneck.
//!
//! # Why this is not inside `pebble_beds`
//!
//! [`crate::pebble_beds`] is the *pebble-bed reactor* specialization — delta tracking
//! and the doubly-heterogeneous k-eigenvalue assembly. The methods here are broader
//! than that application: chord-length sampling applies to any binary random medium,
//! including dispersion fuel and burnable-poison particles that have nothing to do with
//! pebbles. Keeping them separate stops a general method from being filed under one
//! reactor type.
//!
//! The two do meet: [`medium::RsaMedium`] wraps the RSA packing generated by
//! [`crate::pebble_beds::sphere_packing`], which stays where it is because the
//! delta-tracking path depends on it directly.
//!
//! # Status — CORRECTED 2026-09-18
//!
//! ~~Status: scaffold. The CLS and SCLS transport drivers are not implemented —
//! those paths return typed `NotImplemented` errors. No accuracy claim is
//! made.~~
//!
//! **All three statements were stale.** Both drivers are implemented, no
//! `NotImplemented` remains on either path, and accuracy has been measured and
//! published: [`crate::dh_universe::DhTreatment`] runs CLS and SCLS as full arms
//! of the FHR unit-cell k-eigenvalue comparison, and `examples/dh_keff_vv.rs`
//! reports their eigenvalues against an exact delta-tracked reference.
//!
//! What *is* still true, and matters more than the scaffold label did:
//!
//! - **The old text asked whether CLS reproduces the explicit-RSA reference,
//!   and left it open. It does not, and the reason is implementation —
//!   specifically *what CLS was applied to*.** Whole-particle CLS measures `-3149 pcm`
//!   (2.9σ, resolved) because it smears the fuel kernel over 7.7x its volume
//!   and destroys grain-level self-shielding. Applying CLS at the **kernel**
//!   instead — [`crate::dh_universe::DhTreatment::ChordLengthKernel`] — gives
//!   `+669 pcm`, **not resolved from exact** at these statistics: a recovery of
//!   **+3818 pcm**. The price is the whole speed advantage (157.6 s against
//!   exact delta tracking's 148.4 s); what survives is O(1) memory.
//! - The absorbing-inclusion benchmark ([`benchmark`]) independently measures
//!   CLS **over-absorbing** against an explicit RSA reference — the same sign.
//! - One implementation defect is found and fixed: inclusion chords were drawn
//!   exponentially rather than from a sphere's chord law, see
//!   [`cls::sample_chord_sphere`]. It preserved the mean, so the mean-only tests
//!   passed, while putting 22 % of sampled chords beyond `2R`. Correcting it
//!   moves absorption *up*, so it does not explain the eigenvalue gap — it was
//!   masking part of it.
//!
//! **Nothing here is validated.** These are measurements against another code
//! path, not against experiment.
//!
//! Scaffolded per the *OUTRAM-MC Design Scaffold v0.1* (Theodore Ong, Zhe Chuan Tan),
//! tracked under beads epic `op-eby`. This is **new work**, not an OpenMC port —
//! upstream has no CLS or SCLS — so the crate's "mirror the canonical source" rule does
//! not apply here (see the crate `CLAUDE.md`: new parts are scaffolded only where
//! genuinely absent upstream).

pub mod benchmark;
pub mod cls;
pub mod medium;
pub mod scls;
pub mod spatial_index;
