#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
#
# Convert a per-particle snapshot CSV (id,x,y,z,vx,vy,vz) into a LAMMPS/LIGGGHTS
# `read_data` file for atom_style granular, so a bed settled by EITHER code can
# be handed to LIGGGHTS as an initial condition.
#
# This is the inverse of dump2csv.sh, and it is what lets the conus-slump case
# start both codes from the identical configuration rather than from each code's
# own random insertion.
#
# Coordinates are copied verbatim -- the CSVs carry full double precision (see
# the output-precision patch in README.md), and awk's %.17g round-trips a double
# exactly. Velocities are carried across into a Velocities section.
#
# Usage: ./csv2data.sh <in.csv> <out.data> <diameter> <density> <zlo> <zhi>
set -eu

IN="$1"; OUT="$2"; DIAM="$3"; DENS="$4"; ZLO="$5"; ZHI="$6"

N=$(awk 'NR>1 && NF' "$IN" | wc -l)

{
  echo "LIGGGHTS data file -- generated by csv2data.sh from $(basename "$IN")"
  echo
  echo "$N atoms"
  echo "1 atom types"
  echo
  echo "-1.0 1.0 xlo xhi"
  echo "-1.0 1.0 ylo yhi"
  echo "$ZLO $ZHI zlo zhi"
  echo
  echo "Atoms"
  echo
  awk -F, -v d="$DIAM" -v rho="$DENS" 'NR>1 && NF {
      printf "%d 1 %.17g %.17g %.17g %.17g %.17g\n", $1, d, rho, $2, $3, $4
  }' "$IN"
  echo
  echo "Velocities"
  echo
  awk -F, 'NR>1 && NF {
      vx = ($5 == "" ? 0 : $5); vy = ($6 == "" ? 0 : $6); vz = ($7 == "" ? 0 : $7);
      # granular velocities: translational then angular (not carried in the CSV)
      printf "%d %.17g %.17g %.17g 0 0 0\n", $1, vx, vy, vz
  }' "$IN"
} > "$OUT"

echo "wrote $OUT: $N atoms, d=$DIAM rho=$DENS z in [$ZLO,$ZHI]"
