/// Relative change between successive iterates, a scale-free convergence
/// criterion: `|new - old| / max(|new|, floor)`.
///
/// The `floor` guards against division by zero when the solution passes through
/// zero (pass a small positive number such as `1e-30`); it also caps the
/// relative change when `|new|` is smaller than `floor`. Use it as
/// `if relative_change(new, old, 1e-30) < tol { break; }`.
///
/// Generated by kovan-codegen (docs/kovan.md § "Engineering Pattern Library").
/// Deterministic template; depends only on `core`/`std` `f64`.
pub fn relative_change(new: f64, old: f64, floor: f64) -> f64 {
    let denom = new.abs().max(floor);
    (new - old).abs() / denom
}
