// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 OUTRAM PARK contributors
//
// This file is part of OUTRAM PARK.
//
// OUTRAM PARK is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// OUTRAM PARK is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with OUTRAM PARK.  If not, see <https://www.gnu.org/licenses/>.

//! **The k-vs-height record: a standalone matplotlib script, a markdown
//! results table, and a reconstruction block** (gh:#501).
//!
//! Like `outram_mc_libs::geometry::plot::ModelPlot` and
//! [`Htr10Plotter::script`](crate::htr10_rmc::plots::Htr10Plotter::script),
//! the figure is not drawn in Rust: [`plot_script`] writes a Python script
//! that needs only matplotlib, with **every number embedded**, so the figure
//! can be redrawn or restyled years later without the run.
//!
//! **Deterministic.** [`plot_script`] is a pure function of the points and
//! the [`SweepProvenance`]; every float is printed at a fixed precision, and
//! no timing goes into it. The same run gives a byte-identical script.
//! Timings live in [`results_table_md`], next to the hardware they were
//! measured on.
//!
//! **Style** (maintainer convention, 2026-10-01): published curves are THICK
//! SOLID lines; this project's calculation is markers with ±1σ bars joined by
//! a thin dotted line ("guesses"); horizontal guides (k = 1, 0 pcm, the
//! ±500/±1000 pcm band edges) are dashed. Every series names its source in
//! the legend, and the footer carries the key.

use std::fmt::Write as _;

use super::super::{MCNP_TABLE3_KEFF_VS_HEIGHT, MCNP_TABLE4_KEFF_VS_HEIGHT, RMC_KEFF_VS_HEIGHT};
use super::{HeightPoint, SweepStatistics, RINGS, TEMPERATURE_K};

/// Who ran what, where: everything the footer and the parameters block need
/// that is not a result. Supplied by the caller (an example reads the git
/// commit and the host); kept here as plain strings so the emitters stay
/// pure.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SweepProvenance {
    /// The example that produced the run, e.g. `htr10_endf8_kvsh_quick`.
    pub example: String,
    /// Library label, e.g. `ENDF/B-VIII.0`.
    pub library: String,
    /// The transport statistics.
    pub statistics: SweepStatistics,
    /// Pinned transport threads per run.
    pub threads: usize,
    /// Workspace commit the binary was built from (`-dirty` if the tracked
    /// tree differed from it).
    pub commit: String,
    /// Commit of the `reference-data/ace` submodule.
    pub ace_commit: String,
    /// Hardware headline (CPU model, cores, RAM, OS).
    pub host: String,
    /// CPUs the process was allowed to run on (`Cpus_allowed_list`).
    pub cpu_affinity: String,
    /// Model and data configuration, one line each, as the run printed it.
    pub model_notes: Vec<String>,
}

/// A Python string literal (double-quoted, escaped).
fn py_str(s: &str) -> String {
    let mut o = String::from("\"");
    for c in s.chars() {
        match c {
            '\\' => o.push_str("\\\\"),
            '"' => o.push_str("\\\""),
            '\n' => o.push_str("\\n"),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

/// A Python float or `None`, at `prec` decimals.
fn py_opt(v: Option<f64>, prec: usize) -> String {
    v.map_or_else(|| "None".to_string(), |x| format!("{x:.prec$}"))
}

fn py_curve(name: &str, c: &[(f64, f64)]) -> String {
    let mut s = format!("{name} = [\n");
    for (h, k) in c {
        let _ = writeln!(s, "    ({h:.3}, {k:.6}),");
    }
    s.push_str("]\n");
    s
}

/// The standalone matplotlib script. Usage of the result:
/// `python3 <script> [out.png]` (default: the script's own name with `.png`).
///
/// Draws three panels sharing the height axis: `k_eff` with RMC and both MCNP
/// columns; `k − RMC` \[pcm\]; `k − MCNP T3` and `k − MCNP T4` \[pcm\]; each
/// residual with this model's within-run 1σ (the references quote none).
#[must_use]
pub fn plot_script(points: &[HeightPoint], prov: &SweepProvenance) -> String {
    let st = &prov.statistics;
    let mut s = String::new();
    let w = &mut s;
    let _ = writeln!(w, "#!/usr/bin/env python3");
    let _ = writeln!(
        w,
        "\"\"\"HTR-10 k_eff against loading height, {lib}, {name} sweep.\n\n\
         Generated by nee_soon::htr10_rmc::keff_vs_height::script::plot_script\n\
         (example `{ex}`, gh:#501). Every number is embedded; nothing is read from\n\
         disk, so this file alone redraws the figure. Needs matplotlib only.\n\n\
         Usage: python3 <this script> [out.png]   (default: <this script>.png)\n\n\
         Reference curves are the constants RMC_KEFF_VS_HEIGHT,\n\
         MCNP_TABLE3_KEFF_VS_HEIGHT and MCNP_TABLE4_KEFF_VS_HEIGHT of\n\
         crates/nee_soon/src/htr10_rmc/mod.rs, written out by the emitter.\n\
         Each model point sits at the height where Seker & Colak (2003)'s model\n\
         holds as many balls as the built bed (gh:#472); every reference value\n\
         below is read there by linear interpolation.\n\"\"\"",
        lib = prov.library,
        name = st.name,
        ex = prov.example
    );
    let _ = writeln!(
        w,
        "import pathlib\nimport sys\nimport textwrap\n\nimport matplotlib\n\nmatplotlib.use(\"Agg\")\nimport matplotlib.pyplot as plt\n"
    );

    let _ = writeln!(
        w,
        "# ---- data (embedded by the emitter) --------------------------------------"
    );
    let _ = writeln!(w, "LIBRARY = {}", py_str(&prov.library));
    let _ = writeln!(w, "SWEEP = {}", py_str(st.name));
    let _ = writeln!(
        w,
        "# (N, balls, built height cm, reference height cm, k, sigma, RMC, MCNP T3, MCNP T4)"
    );
    let _ = writeln!(w, "POINTS = [");
    for p in points {
        let _ = writeln!(
            w,
            "    ({}, {}, {:.3}, {:.3}, {:.6}, {:.6}, {}, {}, {}),",
            p.layers,
            p.balls
                .map_or_else(|| "None".to_string(), |b| b.to_string()),
            p.built_height_cm(),
            p.reference_height_cm(),
            p.k,
            p.sigma,
            py_opt(p.rmc, 6),
            py_opt(p.mcnp_t3, 6),
            py_opt(p.mcnp_t4, 6),
        );
    }
    let _ = writeln!(w, "]");
    w.push_str(&py_curve("RMC", RMC_KEFF_VS_HEIGHT));
    w.push_str(&py_curve("MCNP_T3", MCNP_TABLE3_KEFF_VS_HEIGHT));
    w.push_str(&py_curve("MCNP_T4", MCNP_TABLE4_KEFF_VS_HEIGHT));
    let footer = [
        format!(
            "{} particles x [{} inactive + {} active], seed {}, one seed per point; \
             error bars are the within-run 1 sigma (the references quote none).",
            st.particles, st.inactive, st.active, st.seed
        ),
        format!(
            "{}, Seker 13-ball bed, {RINGS} rings, {TEMPERATURE_K} K; {}.",
            prov.library,
            prov.model_notes.join("; ")
        ),
        format!(
            "commit {}, reference-data/ace {}, example {}; {} transport threads per run, CPUs {}.",
            prov.commit, prov.ace_commit, prov.example, prov.threads, prov.cpu_affinity
        ),
        format!(
            "host: {} (shared machine; GPU, if listed, detected but not used).",
            prov.host
        ),
        "thick solid = published (Li, Yu & Wei 2014; Seker & Colak 2003); markers on a dotted \
         line = this project's calculation (not validated); dashed = guides."
            .to_string(),
    ];
    let _ = writeln!(w, "FOOTER = [");
    for l in &footer {
        let _ = writeln!(w, "    {},", py_str(l));
    }
    let _ = writeln!(w, "]\n");

    w.push_str(PLOT_BODY);
    s
}

/// The drawing code: independent of the data, so it is a constant.
const PLOT_BODY: &str = r##"# ---- style: dataviz reference palette, light mode ----------------------------
MODEL = "#2a78d6"   # categorical slot 1: this project's calculation
INK = "#0b0b0b"     # RMC, the reference
T3 = "#eb6834"      # categorical slot 2: MCNP Table 3 (vacuum), gauge
T4 = "#1baf7a"      # categorical slot 3: MCNP Table 4 (helium), gauge
MUTED = "#8a8985"
GRID = "#e4e3df"
SURFACE = "#fcfcfb"
TEXT2 = "#52514e"


def residuals(col):
    """(height, pcm, sigma pcm) of every point that has reference column col."""
    return [(p[3], (p[4] - p[col]) * 1e5, p[5] * 1e5) for p in POINTS if p[col] is not None]


def model_bars(ax, pts, color, marker, label, dx=0.0, filled=True):
    xs = [h + dx for h, _, _ in pts]
    ax.plot(xs, [v for _, v, _ in pts], color=color, lw=0.8, ls=":")
    ax.errorbar(xs, [v for _, v, _ in pts], yerr=[e for _, _, e in pts], color=color,
                marker=marker, ms=7, ls="none", elinewidth=1.5, capsize=3,
                mfc=color if filled else SURFACE, mec=color if not filled else SURFACE,
                mew=1.3, label=label)


def bands(ax):
    ax.axhspan(-1000, 1000, color=GRID, alpha=0.55, lw=0)
    ax.axhspan(-500, 500, color=GRID, lw=0)
    for y in (-1000, -500, 500, 1000):
        ax.axhline(y, color=MUTED, lw=0.6, ls="--")
    ax.axhline(0, color=INK, lw=0.9, ls="--")


def main():
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).with_suffix(".png")
    plt.rcParams.update({"font.size": 9.5, "axes.edgecolor": MUTED, "axes.labelcolor": TEXT2,
                         "xtick.color": TEXT2, "ytick.color": TEXT2})
    fig, (ax, ax_rmc, ax_mcnp) = plt.subplots(
        3, 1, figsize=(8.4, 10.6), sharex=True, facecolor=SURFACE,
        gridspec_kw={"height_ratios": [3, 1.7, 1.7]})
    for a in (ax, ax_rmc, ax_mcnp):
        a.set_facecolor(SURFACE)
        a.grid(True, color=GRID, lw=0.8)
        a.set_axisbelow(True)
        for sp in ("top", "right"):
            a.spines[sp].set_visible(False)

    # Panel 1: k against height. Published curves thick solid.
    ax.plot(*zip(*RMC), color=INK, lw=2.6, label="RMC, Li, Yu & Wei 2014, ENDF/B-VII.0 (reference)")
    ax.plot(*zip(*MCNP_T3), color=T3, lw=2.6, alpha=0.85,
            label="MCNP, Li Table 3 = Seker vacuum, ENDF/B-VI (gauge)")
    ax.plot(*zip(*MCNP_T4), color=T4, lw=2.6, alpha=0.85,
            label="MCNP, Li Table 4 = Seker helium, ENDF/B-VI (gauge)")
    ax.axhline(1.0, color=MUTED, lw=0.8, ls="--")
    model_bars(ax, [(p[3], p[4], p[5]) for p in POINTS], MODEL, "o",
               f"this model, {LIBRARY}, ±1σ (outram-mc, not validated)")
    ax.set_ylabel("k_eff")
    ax.set_title(f"HTR-10 k_eff vs loading height, {LIBRARY} ({SWEEP} sweep)",
                 loc="left", color=INK, fontsize=12)
    ax.legend(frameon=False, fontsize=8, loc="upper left")

    # Panel 2: k - RMC.
    bands(ax_rmc)
    model_bars(ax_rmc, residuals(6), INK, "o", "k − RMC (reference), ±1σ")
    ax_rmc.set_ylabel("k − RMC [pcm]")
    ax_rmc.legend(frameon=False, fontsize=8, loc="lower right", bbox_to_anchor=(1.0, 1.0))

    # Panel 3: k - MCNP, both columns, dodged so the bars do not overlap.
    bands(ax_mcnp)
    model_bars(ax_mcnp, residuals(7), T3, "s", "k − MCNP T3 (vacuum, gauge), ±1σ", dx=-0.6)
    model_bars(ax_mcnp, residuals(8), T4, "D", "k − MCNP T4 (helium, gauge), ±1σ", dx=0.6,
               filled=False)
    ax_mcnp.set_ylabel("k − MCNP [pcm]")
    ax_mcnp.set_xlabel("loading height at equal ball count with Seker's model [cm] (gh:#472)")
    ax_mcnp.legend(frameon=False, fontsize=8, loc="lower right", bbox_to_anchor=(1.0, 1.0), ncol=2)
    for a in (ax_rmc, ax_mcnp):
        a.text(0.005, 0.97, "bands: ±500, ±1000 pcm", transform=a.transAxes, va="top",
               fontsize=7.5, color=TEXT2)
    lim = max([1100.0] + [abs(v) + e + 100 for c in (6, 7, 8) for _, v, e in residuals(c)])
    for a in (ax_rmc, ax_mcnp):
        a.set_ylim(-lim, lim)
    ax_mcnp.set_xlim(90, 212)

    lines = [w for line in FOOTER for w in textwrap.wrap(line, 150)]
    fig.text(0.01, 0.004, "\n".join(lines), fontsize=6.6, color=TEXT2, va="bottom")
    fig.tight_layout(rect=(0, 0.012 * len(lines) + 0.01, 1, 1))
    fig.savefig(out, dpi=150, facecolor=SURFACE)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
"##;

fn opt_fmt(v: Option<f64>, f: impl Fn(f64) -> String) -> String {
    v.map_or_else(|| "n/a".to_string(), f)
}

/// The markdown results table: one row per height, then a summary of the
/// residuals against each reference, then a timing table with the hardware.
#[must_use]
pub fn results_table_md(points: &[HeightPoint], prov: &SweepProvenance) -> String {
    let mut s = String::new();
    let w = &mut s;
    let st = &prov.statistics;
    let _ = writeln!(
        w,
        "### {} — {} × [{} inactive + {} active], seed {}\n",
        prov.library, st.particles, st.inactive, st.active, st.seed
    );
    let _ = writeln!(
        w,
        "| N | balls | built [cm] | ref. height [cm] | k ± 1σ | RMC | MCNP T3 (vac) | MCNP T4 (He) \
         | k − RMC [pcm] | k − T3 [pcm] | k − T4 [pcm] | (k − RMC)/σ |"
    );
    let _ = writeln!(w, "|---|---|---|---|---|---|---|---|---|---|---|---|");
    for p in points {
        let sig = p.sigma * 1.0e5;
        let _ = writeln!(
            w,
            "| {} | {} | {:.3} | {:.3} | {:.6} ± {:.6} | {} | {} | {} | {} | {} | {} | {} |",
            p.layers,
            p.balls.map_or_else(|| "n/a".to_string(), |b| b.to_string()),
            p.built_height_cm(),
            p.reference_height_cm(),
            p.k,
            p.sigma,
            opt_fmt(p.rmc, |v| format!("{v:.6}")),
            opt_fmt(p.mcnp_t3, |v| format!("{v:.6}")),
            opt_fmt(p.mcnp_t4, |v| format!("{v:.6}")),
            opt_fmt(p.residual_pcm(p.rmc), |v| format!("{v:+.0} ± {sig:.0}")),
            opt_fmt(p.residual_pcm(p.mcnp_t3), |v| format!("{v:+.0} ± {sig:.0}")),
            opt_fmt(p.residual_pcm(p.mcnp_t4), |v| format!("{v:+.0} ± {sig:.0}")),
            opt_fmt(p.residual_pcm(p.rmc), |v| format!("{:+.2}", v / sig)),
        );
    }

    let _ = writeln!(
        w,
        "\nSummary over {} heights (residuals in pcm):\n",
        points.len()
    );
    let _ = writeln!(
        w,
        "| vs | mean | RMS | max abs | within ±1σ | within ±500 | within ±1000 | slope [pcm/cm] |"
    );
    let _ = writeln!(w, "|---|---|---|---|---|---|---|---|");
    let cols: [(&str, fn(&HeightPoint) -> Option<f64>); 3] = [
        ("RMC (reference)", |p| p.rmc),
        ("MCNP T3 (vacuum, gauge)", |p| p.mcnp_t3),
        ("MCNP T4 (helium, gauge)", |p| p.mcnp_t4),
    ];
    for (label, col) in cols {
        let r: Vec<(f64, f64, f64)> = points
            .iter()
            .filter_map(|p| {
                p.residual_pcm(col(p))
                    .map(|d| (p.reference_height_cm(), d, p.sigma * 1e5))
            })
            .collect();
        if r.is_empty() {
            let _ = writeln!(w, "| {label} | n/a | | | | | | |");
            continue;
        }
        let n = r.len() as f64;
        let mean = r.iter().map(|x| x.1).sum::<f64>() / n;
        let rms = (r.iter().map(|x| x.1 * x.1).sum::<f64>() / n).sqrt();
        let maxa = r.iter().map(|x| x.1.abs()).fold(0.0, f64::max);
        let in1s = r.iter().filter(|x| x.1.abs() <= x.2).count();
        let in500 = r.iter().filter(|x| x.1.abs() <= 500.0).count();
        let in1000 = r.iter().filter(|x| x.1.abs() <= 1000.0).count();
        // Unweighted least-squares slope of residual on height.
        let hm = r.iter().map(|x| x.0).sum::<f64>() / n;
        let sxx: f64 = r.iter().map(|x| (x.0 - hm).powi(2)).sum();
        let sxy: f64 = r.iter().map(|x| (x.0 - hm) * (x.1 - mean)).sum();
        let slope = if sxx > 0.0 { sxy / sxx } else { f64::NAN };
        let m = r.len();
        let _ = writeln!(
            w,
            "| {label} | {mean:+.0} | {rms:.0} | {maxa:.0} | {in1s}/{m} | {in500}/{m} | {in1000}/{m} | {slope:+.1} |"
        );
    }

    let _ = writeln!(
        w,
        "\nPer-height run record (timings depend on machine load):\n"
    );
    let _ = writeln!(
        w,
        "| N | histories (planned {}) | lost locates | entropy first → last [bits] | transport [s] |",
        st.planned_histories()
    );
    let _ = writeln!(w, "|---|---|---|---|---|");
    for p in points {
        let _ = writeln!(
            w,
            "| {} | {} | {} | {} | {:.1} |",
            p.layers,
            p.histories,
            p.lost_locate,
            p.entropy_first_last
                .map_or_else(|| "n/a".to_string(), |(a, b)| format!("{a:.4} → {b:.4}")),
            p.transport_time.get::<uom::si::time::second>()
        );
    }
    let _ = writeln!(
        w,
        "\nHardware: {}; {} transport threads per run, CPUs {} (shared machine). Commit {}.",
        prov.host, prov.threads, prov.cpu_affinity, prov.commit
    );
    s
}

/// The reconstruction block: everything needed to rebuild the run.
#[must_use]
pub fn run_parameters_md(prov: &SweepProvenance, layers: &[usize]) -> String {
    let st = &prov.statistics;
    let mut s = String::new();
    let w = &mut s;
    let _ = writeln!(
        w,
        "# Run parameters: `{}` ({} sweep)\n",
        prov.example, st.name
    );
    let _ = writeln!(
        w,
        "Generated by `nee_soon::htr10_rmc::keff_vs_height::script::run_parameters_md`.\n"
    );
    let _ = writeln!(w, "| Item | Value |\n|---|---|");
    let rows = [
        (
            "Example",
            format!("`crates/nee_soon/examples/{}.rs`", prov.example),
        ),
        ("Workspace commit", format!("`{}`", prov.commit)),
        (
            "`reference-data/ace` submodule",
            format!("`{}`", prov.ace_commit),
        ),
        ("Library", prov.library.clone()),
        ("Particles per cycle", st.particles.to_string()),
        (
            "Cycles",
            format!(
                "{} inactive + {} active = {}",
                st.inactive,
                st.active,
                st.cycles()
            ),
        ),
        (
            "Histories per height (planned)",
            st.planned_histories().to_string(),
        ),
        ("Seed", format!("{} (one seed per point)", st.seed)),
        ("Şeker layers N", format!("{layers:?}")),
        ("Rings", RINGS.to_string()),
        ("Temperature", format!("{TEMPERATURE_K} K, all materials")),
        (
            "Transport threads",
            format!("{} (pinned, `ThreadCount::Fixed`)", prov.threads),
        ),
        ("CPUs allowed", prov.cpu_affinity.clone()),
        ("Host", prov.host.clone()),
    ];
    for (k, v) in rows {
        let _ = writeln!(w, "| {k} | {v} |");
    }
    for n in &prov.model_notes {
        let _ = writeln!(w, "| Model | {n} |");
    }
    let _ = writeln!(
        w,
        "\n## Rebuild\n\n```bash\ngit checkout {c}{note}\n\
         git submodule update --init reference-data/ace\n\
         taskset -c 0-9 cargo build --release -j 8 -p nee_soon --example {ex}\n\
         taskset -c 0-9 ./target/release/examples/{ex} --threads {t} --out <dir>\n\
         python3 <dir>/keff_vs_height.py   # redraws the figure from the embedded data\n```\n",
        c = prov.commit.trim_end_matches("-dirty"),
        note = if prov.commit.ends_with("-dirty") {
            "   # the run's tree was dirty: its code is the commit that added this file"
        } else {
            ""
        },
        ex = prov.example,
        t = prov.threads
    );
    let _ = writeln!(
        w,
        "Nothing is read from the environment: the statistics, seed, library and model are \
         literals in the example and in `nee_soon::htr10_rmc::keff_vs_height`. The thread \
         count does not enter the eigenvalue (per-history seeding)."
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use uom::si::f64::{Length, Time};
    use uom::si::length::centimeter;
    use uom::si::time::second;

    fn prov() -> SweepProvenance {
        SweepProvenance {
            example: "htr10_endf8_kvsh_quick".into(),
            library: "ENDF/B-VIII.0".into(),
            statistics: SweepStatistics::QUICK,
            threads: 8,
            commit: "abc".into(),
            ace_commit: "def".into(),
            host: "test host".into(),
            cpu_affinity: "0-9".into(),
            model_notes: vec!["helium coolant".into()],
        }
    }

    fn point(secs: f64) -> HeightPoint {
        HeightPoint {
            layers: 12,
            balls: Some(16_681),
            built_height: Length::new::<centimeter>(123.576),
            reference_height: Length::new::<centimeter>(122.091),
            k: 0.995_663,
            sigma: 0.001_136,
            rmc: Some(0.999_419),
            mcnp_t3: Some(0.998_250),
            mcnp_t4: Some(0.999_476),
            histories: 200_000,
            lost_locate: 0,
            entropy_first_last: Some((5.1, 5.9)),
            transport_time: Time::new::<second>(secs),
        }
    }

    #[test]
    fn script_is_deterministic_and_carries_no_timing() {
        // Two runs differing only in wall clock give the same script.
        let a = plot_script(&[point(10.0)], &prov());
        let b = plot_script(&[point(99.0)], &prov());
        assert_eq!(a, b);
        assert!(a.contains(
            "(12, 16681, 123.576, 122.091, 0.995663, 0.001136, 0.999419, 0.998250, 0.999476),"
        ));
        // The reference curves are written from the constants.
        assert!(a.contains("    (123.576, 1.004288),"));
        assert!(a.contains("commit abc"));
    }

    #[test]
    fn table_reports_residual_with_sigma() {
        let t = results_table_md(&[point(1.0)], &prov());
        assert!(t.contains("| -376 ± 114 |"), "{t}");
    }
}
