//! Solar panel: photovoltaic array power from irradiance, area and efficiency.
//!
//! # Attribution
//!
//! - **Upstream project:** DWSIM — Open Source Process Simulator
//! - **Source file:** `DWSIM.UnitOperations/UnitOperations/CleanEnergies/SolarPanel.vb`
//! - **Upstream commit:** `1abf72d1b6b41d3e9a8cc770d3cc4e8fc76e5766` (branch `windows`)
//! - **Upstream copyright:** Daniel Wagner O. de Medeiros and the DWSIM contributors
//! - **Upstream licence:** GPL-3.0
//! - **This port:** GPL-3.0-only (OUTRAM PARK fork; not the official DWSIM software)
//!
//! # The model, in full
//!
//! DWSIM's photovoltaic model is a single multiplication
//! (`SolarPanel.vb:264`):
//!
//! `P = G * A * N * eta / 100`
//!
//! with `G` the plane-of-array irradiance in kW/m², `A` one panel's area in
//! m², `N` the number of panels, and `eta` the conversion efficiency **as a
//! percentage**. The result is in kW.
//!
//! That is the entire physics. There is **no** temperature derating, no
//! incidence-angle or soiling loss, no inverter/DC-AC conversion stage, no
//! I-V curve, no maximum-power-point tracking, and no shading model. Callers
//! should treat this as a first-order energy-yield estimate, not a PV
//! performance model. The [`SolarPanelTechnology`] selector exists in DWSIM's
//! metadata but changes nothing in the arithmetic.
//!
//! # An upstream unit inconsistency, reproduced
//!
//! When `UseUserDefinedWeather` is false DWSIM reads
//! `CurrentWeather.SolarIrradiation_kWh_m2` — an **energy density** in
//! kWh/m² — into the same `si` variable that otherwise holds
//! `SolarIrradiation_kW_m2`, a **power** density in kW/m²
//! (`SolarPanel.vb:254-262`). The two differ by a time factor. This port
//! sidesteps the confusion by taking irradiance as a `uom`-typed
//! [`HeatFluxDensity`] input (W/m²), so the caller cannot silently pass an
//! energy density; the weather-service read itself is excluded (see
//! [`crate::clean_energies`]).
//!
//! # Excluded DWSIM behaviour
//!
//! Beyond the module-wide exclusions in [`crate::clean_energies`], this file
//! drops the weather-service lookup at `SolarPanel.vb:256-260` (replaced by
//! the `irradiance` argument, per the note above) and the outlet
//! energy-stream write at `:266` (`esout.EnergyFlow = GeneratedPower`), which
//! is flowsheet plumbing — the value is [`SolarPanel::generated_power`].

use uom::si::area::square_meter;
use uom::si::f64::{Area, HeatFluxDensity, Power, Ratio};
use uom::si::heat_flux_density::watt_per_square_meter;
use uom::si::power::watt;
use uom::si::ratio::ratio;

use super::{CleanEnergyUnitOp, WeatherSource};

/// Photovoltaic cell technology — DWSIM's `EquipmentTypes` list
/// (`SolarPanel.vb:25-29`: `{"", "Monocrystalline", "Polycrystalline",
/// "Thin Film"}`).
///
/// **Descriptive only.** DWSIM's `Calculate` never branches on it; real
/// technology differences are expected to be folded into the efficiency the
/// user enters. Carried so the flowsheet metadata survives the port.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SolarPanelTechnology {
    /// DWSIM's empty first entry — no technology chosen.
    #[default]
    Unspecified,
    /// Monocrystalline silicon.
    Monocrystalline,
    /// Polycrystalline (multicrystalline) silicon.
    Polycrystalline,
    /// Thin-film (a-Si, CdTe, CIGS, …).
    ThinFilm,
}

/// Electrical power generated by a photovoltaic array —
/// `SolarPanel.vb:264`.
///
/// `P = G * A * N * eta`
///
/// # Inputs
///
/// - `irradiance` — plane-of-array irradiance `G` \[W/m²\]. Physically
///   `0` to about `1400` W/m² at the Earth's surface; the standard-test
///   reference is 1000 W/m². DWSIM stores it in kW/m² with a default of 1.0
///   (`:56`), i.e. 1000 W/m².
/// - `panel_area` — the area `A` of **one** panel \[m²\]. DWSIM default 1 m²
///   (`:48`).
/// - `number_of_panels` — how many identical panels `N` (`:52`, default 1).
/// - `efficiency` — DC conversion efficiency `eta`, dimensionless in `[0, 1]`.
///   DWSIM stores this as a **percentage** with default 15 (`:50`) and
///   divides by 100 at `:264`; this port takes the fraction directly, so pass
///   `0.15` where DWSIM's editor shows `15`. Typical values: 0.06-0.13
///   (thin film), 0.15-0.22 (crystalline silicon).
///
/// The relation is exactly linear in every argument — doubling irradiance,
/// area or panel count doubles the output. Returns watts.
pub fn generated_power(
    irradiance: HeatFluxDensity,
    panel_area: Area,
    number_of_panels: u32,
    efficiency: Ratio,
) -> Power {
    let g = irradiance.get::<watt_per_square_meter>();
    let a = panel_area.get::<square_meter>();
    let n = f64::from(number_of_panels);
    let eta = efficiency.get::<ratio>();
    Power::new::<watt>(g * a * n * eta)
}

/// Total active area of the array \[m²\] — `A * N`, the geometric factor in
/// [`generated_power`].
///
/// DWSIM never names this quantity, but it is the natural intermediate and is
/// exposed so callers can report array footprint without recomputing it.
pub fn total_array_area(panel_area: Area, number_of_panels: u32) -> Area {
    panel_area * f64::from(number_of_panels)
}

/// A configured solar-panel unit operation — the ported subset of DWSIM's
/// `SolarPanel` class state (`SolarPanel.vb:25-58`).
///
/// Owns everything by value. A default-constructed panel matches DWSIM's own
/// defaults (`:48-58`) except for the irradiance, which this port leaves at
/// zero because a meaningful value must come from the caller (see the module
/// note on the weather-service unit inconsistency): area 1 m², efficiency
/// 15 %, one panel.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SolarPanel {
    /// Cell technology (descriptive only — see [`SolarPanelTechnology`]).
    pub technology: SolarPanelTechnology,
    /// Where the caller says the irradiance came from
    /// (`CleanEnergyUnitOpBase.vb:12`). Changes no arithmetic.
    pub weather_source: WeatherSource,
    /// Plane-of-array irradiance `G` \[W/m²\] (`SolarPanel.vb:56-58`).
    pub irradiance: HeatFluxDensity,
    /// Area of one panel `A` \[m²\] (`:48`, DWSIM default 1 m²).
    pub panel_area: Area,
    /// Number of identical panels `N` (`:52`, DWSIM default 1).
    pub number_of_panels: u32,
    /// DC conversion efficiency `eta`, dimensionless `[0, 1]` (`:50`, DWSIM
    /// default 15 %, stored here as 0.15).
    pub efficiency: Ratio,
}

impl Default for SolarPanel {
    fn default() -> Self {
        Self {
            technology: SolarPanelTechnology::Unspecified,
            weather_source: WeatherSource::Global,
            irradiance: HeatFluxDensity::new::<watt_per_square_meter>(0.0),
            panel_area: Area::new::<square_meter>(1.0),
            number_of_panels: 1,
            efficiency: Ratio::new::<ratio>(0.15),
        }
    }
}

impl CleanEnergyUnitOp for SolarPanel {
    /// `"Solar Panel"` — `SolarPanel.vb:60-62`.
    fn display_name(&self) -> &'static str {
        "Solar Panel"
    }

    /// `"SP-"` — `SolarPanel.vb:46`.
    fn prefix(&self) -> &'static str {
        "SP-"
    }

    /// Array output \[W\] — `SolarPanel.vb:264`, evaluated from the struct's
    /// own fields via [`generated_power`]. Always `>= 0` for physical
    /// inputs.
    fn generated_power(&self) -> Power {
        generated_power(
            self.irradiance,
            self.panel_area,
            self.number_of_panels,
            self.efficiency,
        )
    }
}

#[cfg(test)]
mod tests {
    //! # Verification tests (methodology + measured results)
    //!
    //! **Verification, not validation** — these confirm the port reproduces
    //! `SolarPanel.vb:264` and its linearity. No comparison against measured
    //! PV output has been made, and the model is far too simple to support
    //! one. Measured 2026-08-11 with `cargo test --release`.
    use super::*;
    use approx::assert_relative_eq;

    /// Methodology: standard-test-condition irradiance 1000 W/m², a 20 m²
    /// array of one panel, 18 % efficiency. Hand calculation:
    /// `P = 1000 * 20 * 1 * 0.18 = 3600 W`.
    /// Result (2026-08-11): `3600.000000 W`.
    #[test]
    fn output_for_given_irradiance_matches_hand_calculation() {
        let p = generated_power(
            HeatFluxDensity::new::<watt_per_square_meter>(1000.0),
            Area::new::<square_meter>(20.0),
            1,
            Ratio::new::<ratio>(0.18),
        );
        assert_relative_eq!(p.get::<watt>(), 3600.0, epsilon = 1e-9);
    }

    /// Methodology: the model is exactly linear in each of its four factors
    /// (`:264`). Doubling irradiance, doubling area, and doubling panel count
    /// must each double the output; zero irradiance must give zero.
    /// Results (2026-08-11): base `3600 W`; double irradiance `7200 W`;
    /// double area `7200 W`; two panels `7200 W`; zero irradiance `0 W`.
    /// All ratios exactly 2.000000.
    #[test]
    fn output_is_linear_in_every_factor() {
        let g = HeatFluxDensity::new::<watt_per_square_meter>(1000.0);
        let a = Area::new::<square_meter>(20.0);
        let eta = Ratio::new::<ratio>(0.18);
        let base = generated_power(g, a, 1, eta).get::<watt>();

        let double_g = generated_power(
            HeatFluxDensity::new::<watt_per_square_meter>(2000.0),
            a,
            1,
            eta,
        )
        .get::<watt>();
        let double_a = generated_power(g, Area::new::<square_meter>(40.0), 1, eta).get::<watt>();
        let double_n = generated_power(g, a, 2, eta).get::<watt>();

        assert_relative_eq!(double_g / base, 2.0, epsilon = 1e-12);
        assert_relative_eq!(double_a / base, 2.0, epsilon = 1e-12);
        assert_relative_eq!(double_n / base, 2.0, epsilon = 1e-12);

        let dark = generated_power(
            HeatFluxDensity::new::<watt_per_square_meter>(0.0),
            a,
            1,
            eta,
        );
        assert_relative_eq!(dark.get::<watt>(), 0.0, epsilon = 1e-15);
    }

    /// Methodology: reproduce DWSIM's own defaults (`:48-56`) — 1 kW/m²,
    /// 1 m², 1 panel, 15 % — through the struct's
    /// [`CleanEnergyUnitOp::generated_power`]. Hand value:
    /// `1000 * 1 * 1 * 0.15 = 150 W`. Also checks the array-area helper for a
    /// 12-panel array of 1.6 m² panels: `19.2 m²`.
    /// Results (2026-08-11): `150.000000 W`; total area `19.200000 m²`.
    #[test]
    fn dwsim_default_configuration_reproduces_upstream_numbers() {
        let panel = SolarPanel {
            irradiance: HeatFluxDensity::new::<watt_per_square_meter>(1000.0),
            ..Default::default()
        };
        assert_eq!(panel.number_of_panels, 1);
        assert_relative_eq!(panel.efficiency.get::<ratio>(), 0.15, epsilon = 1e-12);
        assert_relative_eq!(panel.generated_power().get::<watt>(), 150.0, epsilon = 1e-9);

        let area = total_array_area(Area::new::<square_meter>(1.6), 12);
        assert_relative_eq!(area.get::<square_meter>(), 19.2, epsilon = 1e-12);
    }

    /// Methodology: an unsolved/dark default panel must report 0 W, and the
    /// display name and prefix must match `SolarPanel.vb:60-62` and `:46`.
    /// Result (2026-08-11): `0 W`, `"Solar Panel"`, `"SP-"`.
    #[test]
    fn default_panel_is_dark_and_names_match_upstream() {
        let panel = SolarPanel::default();
        assert_eq!(panel.generated_power().get::<watt>(), 0.0);
        assert_eq!(panel.display_name(), "Solar Panel");
        assert_eq!(panel.prefix(), "SP-");
    }
}
