//! **V&V — `petir::fast_exp::exp` against ARM optimized-routines, bit-for-bit.**
//!
//! # Methodology
//!
//! The claim under test is strong and easy to get wrong: `petir::fast_exp::exp`
//! is a *transcription* of ARM optimized-routines' `math/exp.c`, so it must
//! reproduce that code **bit for bit**, not merely to a tolerance.
//!
//! The oracle is therefore upstream's own C, compiled and run:
//! `reference-data/arm-optimized-routines/exp-arm-optimized-routines-reference.txt`
//! holds 8 345 probes as raw IEEE-754 bit patterns (`<x bits> <exp(x) bits>`,
//! hex64), generated by the committed `exp_reference_driver.c` in that
//! directory. Raw bits keep a decimal round-trip out of the comparison.
//!
//! The probe set crosses every branch of `exp_inline`: the ordinary
//! table-driven path over `[-700, 700]`, the tiny-`x` early return, and both
//! sides of `specialcase` at the overflow (709.78..) and underflow (-745.13..)
//! boundaries. Pass criterion: **every probe bit-identical**, and every
//! refusal (`PetirError`) matched by an upstream infinity or zero.
//!
//! # Results (2026-09-14)
//!
//! 8 345 probes, **8 345 bit-identical (100.000 %)**, 0 disagreements.
//! Against `libm::exp` (the independent musl-derived route) the worst relative
//! difference is 2.129e-16 — about 1 ulp — which is the expected spread
//! between two correctly-implemented `exp`s, and confirms neither has a
//! transcription error large enough to matter.
//!
//! # The platform `exp` is a 1-ulp check, not a bit-identity check
//!
//! An earlier revision of this file asserted bit-identity against `f64::exp`
//! on glibc hosts, on the reasoning that glibc *ships* ARM's implementation.
//! That assertion is **wrong on FMA-capable hardware** and it failed: 22 of
//! 40 001 probes (0.055 %) differed, every one by exactly 1 ulp.
//!
//! The cause is not a defect in either implementation. glibc's ifunc dispatch
//! selects an **FMA-compiled** build of that same source, and GCC contracts
//! `r2 * (C2 + r * C3)` into a fused multiply-add — one rounding instead of
//! two. Rebuilding ARM's C three ways settles it:
//!
//! | ARM build | differences vs this host's glibc |
//! |---|---|
//! | `gcc -O2` (no FMA) | 22 / 40001, each 1 ulp |
//! | `gcc -O2 -mfma -mavx2 -ffp-contract=fast` | **0 / 40001** |
//! | `gcc -O2 -mfma -mavx2 -ffp-contract=off` | 22 / 40001 (identical to no-FMA) |
//!
//! The third row is the control: hardware present, contraction off, bit
//! pattern back to the portable one. Rust never contracts floating-point
//! expressions, so the portable row is the one this port can hold *on every
//! target* — which is the property the module exists for. The platform check
//! below therefore asserts a 1-ulp bound, and reports the exact-match count
//! rather than requiring it.

use std::path::PathBuf;

/// `<repo root>/reference-data/arm-optimized-routines/…`, found by walking up
/// from this crate rather than hard-coding a depth.
fn reference_path() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        let p = dir
            .join("reference-data/arm-optimized-routines")
            .join("exp-arm-optimized-routines-reference.txt");
        if p.is_file() {
            return p;
        }
        assert!(
            dir.pop(),
            "reference-data/arm-optimized-routines/ not found above the crate"
        );
    }
}

/// The committed oracle, as `(x, exp(x))` pairs decoded from their bit patterns.
fn oracle() -> Vec<(f64, f64)> {
    let path = reference_path();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let mut it = l.split_whitespace();
            let x = u64::from_str_radix(it.next().expect("x column"), 16).expect("x hex");
            let y = u64::from_str_radix(it.next().expect("y column"), 16).expect("y hex");
            (f64::from_bits(x), f64::from_bits(y))
        })
        .collect()
}

#[test]
fn fast_exp_is_bit_identical_to_arm_optimized_routines() {
    let probes = oracle();
    assert!(
        probes.len() > 8_000,
        "only {} probes in the oracle file",
        probes.len()
    );

    let mut exact = 0usize;
    let mut compared = 0usize;
    let mut refused = 0usize;
    let mut first_bad: Option<(f64, u64, u64)> = None;

    for (x, theirs) in probes {
        match petir::fast_exp::exp(x) {
            Ok(ours) => {
                compared += 1;
                if ours.to_bits() == theirs.to_bits() {
                    exact += 1;
                } else if first_bad.is_none() {
                    first_bad = Some((x, ours.to_bits(), theirs.to_bits()));
                }
            }
            Err(_) => {
                // Upstream signals overflow/underflow through the IEEE flags
                // and still returns a value (`+inf` or `+0.0`). `exp` reports
                // that as an error; `exp_ieee` must reproduce the value
                // itself, bit for bit -- so the refusals are checked just as
                // strictly as the ordinary results, not merely sanity-checked.
                refused += 1;
                let ours = petir::fast_exp::exp_ieee(x);
                assert_eq!(
                    ours.to_bits(),
                    theirs.to_bits(),
                    "exp_ieee({x}) = {:016x}, upstream gives {:016x}",
                    ours.to_bits(),
                    theirs.to_bits()
                );
            }
        }
    }

    println!(
        "  fast_exp vs ARM optimized-routines: {compared} compared, \
         {exact} bit-identical ({:.3} %), {refused} refused at the range edges",
        100.0 * exact as f64 / compared as f64
    );
    if let Some((x, ours, theirs)) = first_bad {
        panic!(
            "not a faithful transcription: at x = {x} ({:016x}) this port gives \
             {ours:016x}, upstream gives {theirs:016x}; {} of {compared} probes differ",
            x.to_bits(),
            compared - exact
        );
    }
}

/// The platform `exp` must agree to within 1 ulp — but see the module docs:
/// bit-identity is *not* expected on FMA-capable hardware, because glibc
/// dispatches to an FMA-contracted build of the same source.
#[test]
fn fast_exp_is_within_one_ulp_of_the_platform_exp() {
    let mut compared = 0usize;
    let mut exact = 0usize;
    let mut worst = (0.0f64, 0.0f64);

    for (x, _) in oracle() {
        let theirs = x.exp();
        let Ok(ours) = petir::fast_exp::exp(x) else {
            continue;
        };
        compared += 1;
        if ours.to_bits() == theirs.to_bits() {
            exact += 1;
            continue;
        }
        let rel = if theirs.abs() > 0.0 {
            (ours - theirs).abs() / theirs.abs()
        } else {
            (ours - theirs).abs()
        };
        if rel > worst.0 {
            worst = (rel, x);
        }
    }

    println!(
        "  fast_exp vs platform exp: {compared} compared, {exact} bit-identical \
         ({:.3} %); worst rel {:.3e} at x = {}",
        100.0 * exact as f64 / compared as f64,
        worst.0,
        worst.1
    );
    assert!(
        worst.0 < 2.3e-16,
        "worst relative difference {:.3e} at x = {} exceeds 1 ulp — that is more \
         than FMA contraction can explain",
        worst.0,
        worst.1
    );
}

/// The fast path and the musl-derived `libm` path must agree to within a
/// couple of ulp — they are independent implementations of the same function,
/// so this catches a transcription error in either.
///
/// Note it calls `libm::exp` **by name**, not `petir::real::exp`:
/// `petir::real::exp` now routes here, so going through it would compare this
/// port with itself.
#[test]
fn the_two_backends_agree() {
    let mut worst = (0.0f64, 0.0f64);
    for k in -2000..=2000 {
        let x = f64::from(k) * 0.35;
        let Ok(fast) = petir::fast_exp::exp(x) else {
            continue;
        };
        let slow = libm::exp(x);
        if slow == 0.0 || !slow.is_finite() {
            continue;
        }
        let rel = (fast - slow).abs() / slow.abs();
        if rel > worst.0 {
            worst = (rel, x);
        }
    }
    println!(
        "  fast_exp vs libm::exp: worst rel {:.3e} at x = {}",
        worst.0, worst.1
    );
    assert!(
        worst.0 < 5.0e-16,
        "the two exp implementations disagree by {:.3e} at x = {} — more than a \
         couple of ulp, so one of them is wrong",
        worst.0,
        worst.1
    );
}
