//! **V&V — `petir::fast_pow::powf` against ARM optimized-routines, bit-for-bit.**
//!
//! # Methodology
//!
//! Same standard as the `fast_exp` and `fast_log` suites beside it:
//! `petir::fast_pow::powf` is a *transcription* of ARM optimized-routines'
//! `math/pow.c`, so it must reproduce that code **bit for bit**.
//!
//! The oracle is upstream's own C, compiled without FMA and run:
//! `reference-data/arm-optimized-routines/pow-arm-optimized-routines-reference.txt`
//! holds 43 435 probes as raw IEEE-754 bit patterns
//! (`<x bits> <y bits> <pow(x,y) bits>`, hex64), generated by the committed
//! `pow_reference_driver.c` beside it.
//!
//! The probe set is built to cross every branch, not to be large:
//!
//! - a 400 x 81 spread of positive bases against exponents of both signs —
//!   the ordinary `log_inline` -> `exp_inline` path, plus 120 negative bases
//!   against every integer exponent in [-25, 25] and three non-integer ones;
//! - bases within 3e-2 of 1.0 against exponents of ±1000, 1e6 and 0.5, which
//!   is the regime that makes `pow` hard and the reason `log_inline` carries
//!   ~15 extra bits;
//! - integer and half-integer exponents against positive and negative bases,
//!   exercising `checkint`'s odd/even/not-an-integer classification and the
//!   `SIGN_BIAS` path;
//! - bases across the full binade range at step 7, crossing subnormal
//!   normalisation and both the overflow and underflow edges of the result;
//! - the full IEEE special-case cross product (`±0`, `±1`, `±2`, `±inf`,
//!   against `±0`, `±1`, `±inf`, tiny and huge `y`) that `pow`'s prologue
//!   resolves before any polynomial runs.
//!
//! Pass criterion: **every probe bit-identical** (NaN compared by bit pattern,
//! so a NaN answer must be the *same* NaN), and every refusal (`PetirError`)
//! matched by an upstream infinity, zero or NaN.
//!
//! # Results (2026-09-14)
//!
//! 43 435 probes: **42 176 compared, 42 176 bit-identical (100.000 %)**, and
//! 1 259 refused — negative bases with a non-integer exponent, and results
//! that overflow or underflow the double range — each checked against
//! upstream's NaN, infinity or zero rather than skipped.
//!
//! Against the platform `powf` on this glibc host: 99.924 % bit-identical,
//! worst relative difference 2.145e-16 at `(49.95, 2.49)` — one FMA
//! contraction. Against `exp(y * ln x)` built from this crate's own
//! `fast_exp`/`fast_log`, worst 3.507e-15, which is the expected loss from
//! rounding `ln x` before multiplying by `y` — precisely what `pow`'s
//! extra-precision `log_inline` exists to avoid.
//!
//! # Known, deliberate divergence: `0^negative`
//!
//! Upstream guards its `__math_divzero` branch with `WANT_ERRNO`, which is
//! **0** in the baseline build — so its compiled code falls through to `1/x2`
//! and returns `±inf` without setting `errno`. PETIR reports an infinite
//! result as `PetirError::ZeroDivide` instead, as `fast_log` does at
//! `x == ±0` — both are genuine `__math_divzero` sites. (`fast_exp` no
//! longer appears in that list: its `__math_oflow`/`__math_uflow` paths
//! became `PetirError::Overflow`/`Underflow` on 2026-09-20, which is what
//! they always meant.) The divergence is in the reporting convention, not
//! the value, and the test below checks each refusal against upstream's
//! returned infinity rather than skipping it.

use std::path::PathBuf;

fn reference_path() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        let p = dir
            .join("reference-data/arm-optimized-routines")
            .join("pow-arm-optimized-routines-reference.txt");
        if p.is_file() {
            return p;
        }
        assert!(
            dir.pop(),
            "reference-data/arm-optimized-routines/ not found above the crate"
        );
    }
}

fn oracle() -> Vec<(f64, f64, f64)> {
    let path = reference_path();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let mut it = l.split_whitespace();
            let mut next = || u64::from_str_radix(it.next().expect("column"), 16).expect("hex");
            let (x, y, z) = (next(), next(), next());
            (f64::from_bits(x), f64::from_bits(y), f64::from_bits(z))
        })
        .collect()
}

#[test]
fn fast_pow_is_bit_identical_to_arm_optimized_routines() {
    let probes = oracle();
    assert!(
        probes.len() > 43_000,
        "only {} probes in the oracle file",
        probes.len()
    );

    let mut exact = 0usize;
    let mut compared = 0usize;
    let mut refused = 0usize;
    let mut bad: Vec<(f64, f64, u64, u64)> = Vec::new();

    for (x, y, theirs) in probes {
        match petir::fast_pow::powf(x, y) {
            Ok(ours) => {
                compared += 1;
                if ours.to_bits() == theirs.to_bits() {
                    exact += 1;
                } else if bad.len() < 8 {
                    bad.push((x, y, ours.to_bits(), theirs.to_bits()));
                }
            }
            Err(_) => {
                // `powf` reports upstream's overflow / underflow / invalid /
                // divide-by-zero returns as errors; `powf_ieee` must reproduce
                // the values bit for bit -- including the sign of an infinity
                // or a zero, which is what `SIGN_BIAS` exists to get right.
                // So the refusals are checked as strictly as the results.
                refused += 1;
                let ours = petir::fast_pow::powf_ieee(x, y);
                if theirs.is_nan() {
                    // See `fast_log`'s test: upstream's `__math_invalid` NaN
                    // is architecture-dependent in sign and payload, and this
                    // port deliberately returns the positive quiet NaN on
                    // every target. NaN-ness is checked, not the bits.
                    assert!(
                        ours.is_nan(),
                        "powf_ieee({x:e}, {y:e}) = {ours:e}, upstream gives NaN"
                    );
                } else {
                    assert_eq!(
                        ours.to_bits(),
                        theirs.to_bits(),
                        "powf_ieee({x:e}, {y:e}) = {:016x}, upstream gives {:016x}",
                        ours.to_bits(),
                        theirs.to_bits()
                    );
                }
            }
        }
    }

    println!(
        "  fast_pow vs ARM optimized-routines: {compared} compared, \
         {exact} bit-identical ({:.3} %), {refused} refused",
        100.0 * exact as f64 / compared as f64
    );
    assert!(
        bad.is_empty(),
        "not a faithful transcription: {} of {compared} probes differ; first few: {}",
        compared - exact,
        bad.iter()
            .map(|(x, y, o, t)| format!("pow({x:e}, {y:e}) = {o:016x} vs {t:016x}"))
            .collect::<Vec<_>>()
            .join("; ")
    );
}

/// The platform `powf` must agree to within a few ulp — but not bit for bit,
/// because glibc dispatches to the FMA build. See `petir::fast_exp`'s docs.
#[test]
fn fast_pow_is_close_to_the_platform_powf() {
    let mut compared = 0usize;
    let mut exact = 0usize;
    let mut worst = (0.0f64, 0.0f64, 0.0f64);

    for (x, y, _) in oracle() {
        let theirs = x.powf(y);
        let Ok(ours) = petir::fast_pow::powf(x, y) else {
            continue;
        };
        if !theirs.is_finite() || theirs == 0.0 {
            continue;
        }
        compared += 1;
        if ours.to_bits() == theirs.to_bits() {
            exact += 1;
            continue;
        }
        let rel = (ours - theirs).abs() / theirs.abs();
        if rel > worst.0 {
            worst = (rel, x, y);
        }
    }

    println!(
        "  fast_pow vs platform powf: {compared} compared, {exact} bit-identical \
         ({:.3} %); worst rel {:.3e} at ({:e}, {:e})",
        100.0 * exact as f64 / compared as f64,
        worst.0,
        worst.1,
        worst.2
    );
    assert!(
        worst.0 < 1.0e-15,
        "worst relative difference {:.3e} at ({:e}, {:e}) is more than FMA \
         contraction can explain",
        worst.0,
        worst.1,
        worst.2
    );
}

/// `x^y` built out of this crate's own `fast_log` and `fast_exp` must land
/// close to `fast_pow` — a cheap independent check that the shared tables and
/// the `log_inline`/`exp_inline` duplicates have not drifted apart.
#[test]
fn pow_agrees_with_exp_of_y_times_log_x() {
    let mut worst = (0.0f64, 0.0f64, 0.0f64);
    for i in 1..=400i64 {
        let x = i as f64 * 0.11;
        for j in -30..=30i64 {
            let y = j as f64 * 0.27;
            let (Ok(p), Ok(l)) = (petir::fast_pow::powf(x, y), petir::fast_log::ln(x)) else {
                continue;
            };
            let Ok(q) = petir::fast_exp::exp(y * l) else {
                continue;
            };
            if p == 0.0 || !p.is_finite() {
                continue;
            }
            let rel = (p - q).abs() / p.abs();
            if rel > worst.0 {
                worst = (rel, x, y);
            }
        }
    }
    println!(
        "  fast_pow vs exp(y*ln x): worst rel {:.3e} at ({}, {})",
        worst.0, worst.1, worst.2
    );
    // exp(y * ln x) loses accuracy by construction -- ln x is rounded before
    // being multiplied by y, which `pow`'s extra-precision `log_inline` exists
    // to avoid. The bound is therefore loose; it catches a wrong table or a
    // mis-transcribed branch, not a last-bit difference.
    assert!(
        worst.0 < 1.0e-10,
        "fast_pow and exp(y*ln x) disagree by {:.3e} at ({}, {}) — far more than \
         the rounding of ln x explains",
        worst.0,
        worst.1,
        worst.2
    );
}
