//! **V&V — `petir::fast_log::ln` against ARM optimized-routines, bit-for-bit.**
//!
//! # Methodology
//!
//! Same standard as `fast_exp_vs_arm_optimized_routines.rs`, and for the same
//! reason: `petir::fast_log::ln` is a *transcription* of ARM
//! optimized-routines' `math/log.c`, so it must reproduce that code **bit for
//! bit**, not merely to a tolerance.
//!
//! The oracle is upstream's own C, compiled without FMA and run:
//! `reference-data/arm-optimized-routines/log-arm-optimized-routines-reference.txt`
//! holds 16 751 probes as raw IEEE-754 bit patterns (`<x bits> <log(x) bits>`,
//! hex64), generated by the committed `log_reference_driver.c` beside it.
//!
//! The probe set crosses every branch of `log`: every binade from the
//! subnormal floor to the top of the range at six mantissas each; the near-1
//! window `[1 - 0x1p-4, 1 + 0x1.09p-4]` and both sides of its edges, which run
//! a different (`poly1`) polynomial; the subnormal renormalisation path; and
//! `+0.0`, `-0.0`, `-1.0`, `1.0`.
//!
//! Pass criterion: **every probe bit-identical**, and every refusal
//! (`PetirError`) matched by an upstream infinity or NaN.
//!
//! # Results (2026-09-14)
//!
//! 16 751 probes: **16 748 compared, 16 748 bit-identical (100.000 %)**, and
//! 3 refused — `+0.0` and `-0.0` (upstream `-inf`) and `-1.0` (upstream NaN),
//! each checked rather than skipped. Against the platform `ln` on this glibc
//! host, 99.994 % bit-identical with a worst relative difference of 1.713e-16
//! at `x = 0.92216` — one FMA contraction. Against the independent `libm`
//! route, worst 2.220e-16.
//!
//! # Why the oracle is not the platform `log`
//!
//! `HAVE_FAST_FMA` does more here than it does in `exp`: it selects a
//! different argument reduction (`fma(z, invc, -1)` against
//! `(z - chi - clo) * invc`, which needs the whole `tab2` table) *and* a
//! different near-1 branch. glibc's ifunc dispatch picks the FMA build on
//! capable hardware, so the platform `log` is a 1-ulp neighbour of this port,
//! not a bit-for-bit match. The second test below holds that bound; the
//! module docs of `petir::fast_exp` explain why tracking the portable form is
//! the deliberate choice.

use std::path::PathBuf;

fn reference_path() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        let p = dir
            .join("reference-data/arm-optimized-routines")
            .join("log-arm-optimized-routines-reference.txt");
        if p.is_file() {
            return p;
        }
        assert!(
            dir.pop(),
            "reference-data/arm-optimized-routines/ not found above the crate"
        );
    }
}

fn oracle() -> Vec<(f64, f64)> {
    let path = reference_path();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let mut it = l.split_whitespace();
            let x = u64::from_str_radix(it.next().expect("x column"), 16).expect("x hex");
            let y = u64::from_str_radix(it.next().expect("y column"), 16).expect("y hex");
            (f64::from_bits(x), f64::from_bits(y))
        })
        .collect()
}

#[test]
fn fast_log_is_bit_identical_to_arm_optimized_routines() {
    let probes = oracle();
    assert!(
        probes.len() > 16_000,
        "only {} probes in the oracle file",
        probes.len()
    );

    let mut exact = 0usize;
    let mut compared = 0usize;
    let mut refused = 0usize;
    let mut first_bad: Option<(f64, u64, u64)> = None;

    for (x, theirs) in probes {
        match petir::fast_log::ln(x) {
            Ok(ours) => {
                compared += 1;
                if ours.to_bits() == theirs.to_bits() {
                    exact += 1;
                } else if first_bad.is_none() {
                    first_bad = Some((x, ours.to_bits(), theirs.to_bits()));
                }
            }
            Err(_) => {
                // Upstream returns -inf (divide-by-zero) at x == 0 and a NaN
                // (invalid) for x < 0. `ln` reports those as errors; `ln_ieee`
                // must reproduce the values bit for bit, so the refusals are
                // held to the same standard as the ordinary results.
                refused += 1;
                let ours = petir::fast_log::ln_ieee(x);
                if theirs.is_nan() {
                    // The one deliberate divergence: upstream's
                    // `__math_invalid` is `(x - x) / (x - x)`, whose NaN sign
                    // and payload are architecture-dependent (0xfff8… on
                    // x86-64 SSE, 0x7ff8… on aarch64). This port returns the
                    // positive quiet NaN everywhere, on purpose, because a
                    // platform-dependent NaN would defeat the determinism the
                    // module exists for -- and a NaN payload carries no
                    // numerical meaning. So NaN-ness is checked, not the bits.
                    assert!(
                        ours.is_nan(),
                        "ln_ieee({x:e}) = {ours:e}, upstream gives NaN"
                    );
                } else {
                    assert_eq!(
                        ours.to_bits(),
                        theirs.to_bits(),
                        "ln_ieee({x:e}) = {:016x}, upstream gives {:016x}",
                        ours.to_bits(),
                        theirs.to_bits()
                    );
                }
            }
        }
    }

    println!(
        "  fast_log vs ARM optimized-routines: {compared} compared, \
         {exact} bit-identical ({:.3} %), {refused} refused",
        100.0 * exact as f64 / compared as f64
    );
    if let Some((x, ours, theirs)) = first_bad {
        panic!(
            "not a faithful transcription: at x = {x:e} ({:016x}) this port gives \
             {ours:016x}, upstream gives {theirs:016x}; {} of {compared} probes differ",
            x.to_bits(),
            compared - exact
        );
    }
}

/// The platform `ln` must agree to within a couple of ulp — but not bit for
/// bit, because glibc dispatches to the FMA build. See the module docs.
#[test]
fn fast_log_is_close_to_the_platform_ln() {
    let mut compared = 0usize;
    let mut exact = 0usize;
    let mut worst = (0.0f64, 0.0f64);

    for (x, _) in oracle() {
        let theirs = x.ln();
        let Ok(ours) = petir::fast_log::ln(x) else {
            continue;
        };
        if !theirs.is_finite() || theirs == 0.0 {
            continue;
        }
        compared += 1;
        if ours.to_bits() == theirs.to_bits() {
            exact += 1;
            continue;
        }
        let rel = (ours - theirs).abs() / theirs.abs();
        if rel > worst.0 {
            worst = (rel, x);
        }
    }

    println!(
        "  fast_log vs platform ln: {compared} compared, {exact} bit-identical \
         ({:.3} %); worst rel {:.3e} at x = {:e}",
        100.0 * exact as f64 / compared as f64,
        worst.0,
        worst.1
    );
    assert!(
        worst.0 < 5.0e-16,
        "worst relative difference {:.3e} at x = {:e} is more than FMA \
         contraction can explain",
        worst.0,
        worst.1
    );
}

/// The fast path and the musl-derived `libm` path are independent
/// implementations of the same function, so a large disagreement means one of
/// them has a transcription error.
///
/// It calls `libm::log` **by name**: `petir::real::ln` now routes here, so
/// going through it would compare this port with itself.
#[test]
fn the_two_backends_agree() {
    let mut worst = (0.0f64, 0.0f64);
    for k in 1..=200_000i64 {
        let x = k as f64 * 1.0e-3;
        let Ok(fast) = petir::fast_log::ln(x) else {
            continue;
        };
        let slow = libm::log(x);
        if slow == 0.0 || !slow.is_finite() {
            continue;
        }
        let rel = (fast - slow).abs() / slow.abs();
        if rel > worst.0 {
            worst = (rel, x);
        }
    }
    println!(
        "  fast_log vs libm::log: worst rel {:.3e} at x = {}",
        worst.0, worst.1
    );
    assert!(
        worst.0 < 5.0e-15,
        "the two ln implementations disagree by {:.3e} at x = {} — more than a \
         few ulp, so one of them is wrong",
        worst.0,
        worst.1
    );
}
