//! **Characterisation — `petir::real` against the platform C libm.**
//!
//! Three crates used to call `erf`/`erfc`/`tgamma`/`lgamma` through
//! `extern "C"`, i.e. the system libm. `bn:op-chyp.6` replaced those with
//! [`petir::real`], which is pure Rust. **Swapping an implementation changes
//! bits**, so this records by how much, rather than leaving it to be
//! discovered by a fixture that moves.
//!
//! The reference is glibc on x86-64, generated by
//! `reference-data/gsl/platform_libm_reference_driver.c` (committed beside the
//! data). On another platform the numbers will differ — that is the point:
//! **platform libms disagree with each other too**, and `petir::real` is the
//! one implementation that does not vary.
//!
//! # Result (2026-09-14, glibc / x86-64)
//!
//! ```text
//!   erf      801 pts,  793 bit-identical (99.0 %), worst rel 1.4e-16
//!   erfc     801 pts,  752 bit-identical (93.9 %), worst rel 3.6e-16
//!   lgamma   400 pts,  383 bit-identical (95.8 %), worst rel 4.2e-16
//!   tgamma   400 pts,  100 bit-identical (25.0 %), worst rel 9.1e-16
//! ```
//!
//! `tgamma` differs in the last bits three times out of four. Everything is
//! within a few ulp, and the three affected crates' suites (516 + 286 + the
//! steam tables) pass unchanged — but a future fixture asserting
//! `tgamma`-derived values to full `f64` precision is the thing that would
//! move.
//!
//! This test asserts the DIFFERENCE STAYS SMALL, not that it is zero. A
//! regression here means `libm` changed materially, which is worth knowing.

use std::collections::BTreeMap;
use std::path::PathBuf;

fn reference() -> Option<PathBuf> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../reference-data/gsl/platform-libm-glibc-reference.txt");
    p.exists().then_some(p)
}

#[test]
fn petir_real_agrees_with_the_platform_libm_to_a_few_ulp() {
    let Some(path) = reference() else {
        eprintln!("skipping: reference not present");
        return;
    };
    let text = std::fs::read_to_string(&path).expect("reference readable");

    let mut stats: BTreeMap<&str, (f64, f64, usize, usize)> = BTreeMap::new();
    for line in text.lines() {
        let mut it = line.split_whitespace();
        let name = it.next().unwrap_or("");
        let (x, c) = match (it.next(), it.next()) {
            (Some(a), Some(b)) => (
                a.parse::<f64>().expect("x"),
                b.parse::<f64>().expect("value"),
            ),
            _ => continue,
        };
        let (ours, key) = match name {
            "erf" => (petir::erf(x), "erf"),
            "erfc" => (petir::erfc(x), "erfc"),
            "tgamma" => (petir::tgamma(x), "tgamma"),
            "lgamma" => (petir::lgamma(x), "lgamma"),
            _ => continue,
        };
        let e = stats.entry(key).or_insert((0.0, 0.0, 0, 0));
        e.3 += 1;
        if ours.to_bits() == c.to_bits() {
            e.2 += 1;
        }
        let rel = if c.abs() > 1.0e-300 {
            (ours - c).abs() / c.abs()
        } else {
            (ours - c).abs()
        };
        if rel > e.0 {
            e.0 = rel;
            e.1 = x;
        }
    }

    assert!(!stats.is_empty(), "no comparable lines in the reference");
    for (name, (worst, at, exact, n)) in &stats {
        println!(
            "  {name:<7} {n:>4} pts, {exact:>4} bit-identical ({:>5.1} %), worst rel {worst:.3e} at x = {at:.4}",
            100.0 * *exact as f64 / *n as f64
        );
        assert!(
            *worst < 1.0e-14,
            "{name} differs from the platform libm by {worst:.3e} relative at x = {at} — \
             far more than the few-ulp difference recorded on 2026-09-14"
        );
    }
}
