//! The `kovan kloc` parity gate against the frozen Python output.
//!
//! # Why the full comparison is `#[ignore]`d
//!
//! It needs **six external repositories** — five pre-agentic ones plus this
//! workspace — and three of them are not on a typical machine without a network
//! clone. A test that silently passed when its inputs were absent would be
//! worse than no test; one that failed on every clean checkout would be noise.
//! So the full run is opt-in and its procedure is written down, while the parts
//! that *can* be checked anywhere are checked below and are not ignored.
//!
//! # Running the full comparison
//!
//! ```text
//! kovan kloc --out /tmp/kloc-check --clone --check
//! diff docs/kloc-parity-baseline/summary.txt               /tmp/kloc-check/summary.txt
//! diff docs/kloc-parity-baseline/baseline_repositories.csv /tmp/kloc-check/baseline_repositories.csv
//! diff docs/kloc-parity-baseline/agentic_crates.csv        /tmp/kloc-check/agentic_crates.csv
//! ```
//!
//! The three `.tex` files are identical **except the lines naming the tool**:
//! `kloc_accounting.py` became `kovan kloc` in the `% Generated by` header and
//! in each caption, deliberately, because the script no longer exists and a
//! caption pointing a reader at a deleted file is worse than a failed byte
//! comparison.
//!
//! # Result, 2026-08-14
//!
//! `summary.txt`, `baseline_repositories.csv` and `agentic_crates.csv` came out
//! **byte-identical**. The three `.tex` files showed **zero differing lines**
//! once the tool name was normalised. The same run reproduced all eight
//! manuscript drift-check deltas as `+0`.
//!
//! **A bug this gate caught that the unit tests could not.** The git object spec
//! for a prefixed subtree was being built as `<rev>:crates/foo:src/lib.rs`, with
//! two colons. git rejects that per object rather than loudly, so **every crate
//! counted zero** while the file listing above it still looked correct. The
//! baseline repositories could not expose it, because their prefix is empty and
//! their spec was well-formed. Only comparing real output against real output
//! found it.

use std::path::PathBuf;

/// The frozen fixture directory.
fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../docs/kloc-parity-baseline")
        .canonicalize()
        .expect("the parity fixture must be committed")
}

/// The fixture's presence is checkable everywhere, and a missing fixture would
/// silently disarm the gate.
#[test]
fn the_parity_fixture_is_present_and_complete() {
    let dir = fixture_dir();
    for name in [
        "summary.txt",
        "baseline_repositories.csv",
        "agentic_crates.csv",
        "baseline_table.tex",
        "rate_table.tex",
        "agentic_table.tex",
        "README.md",
    ] {
        assert!(dir.join(name).is_file(), "missing parity fixture: {name}");
    }
}

/// **The fixture is only a gate on the paper's numbers if it carries them.**
///
/// An earlier capture was taken with three repositories absent. It produced a
/// complete-looking set of files whose agentic total was inflated by very
/// nearly what the baseline lost, because an extension crate subtracts its
/// standalone pre-agentic original and a missing one moves those lines across.
/// This pins that the committed fixture is not that capture.
#[test]
fn the_fixture_records_the_published_figures() {
    let summary = std::fs::read_to_string(fixture_dir().join("summary.txt")).unwrap();
    assert!(
        !summary.contains("MISSING -- run with --clone"),
        "the fixture was captured with a repository missing, which moves \
         pre-agentic lines into the agentic total -- recapture it with --clone"
    );
    for figure in ["303,463", "181,298", "175,997"] {
        assert!(
            summary.contains(figure),
            "the fixture no longer carries the published figure {figure}"
        );
    }
}

/// The CSVs must keep Python's `excel` dialect line terminator.
///
/// A bare `\n` looks identical in an editor and fails the byte comparison, so
/// this is worth pinning on the fixture itself rather than only in the writer.
#[test]
fn the_fixture_csvs_are_crlf_terminated() {
    for name in ["baseline_repositories.csv", "agentic_crates.csv"] {
        let bytes = std::fs::read(fixture_dir().join(name)).unwrap();
        assert!(
            bytes.windows(2).any(|w| w == b"\r\n"),
            "{name} must be CRLF-terminated, matching Python's csv.writer"
        );
    }
}

#[test]
#[ignore = "needs six repositories and a network clone; run the procedure in this file's module docs"]
fn kovan_kloc_reproduces_the_python_output() {
    // Deliberately not a silent no-op: running it here would clone gigabytes
    // inside a test run. The procedure and its 2026-08-14 result are in the
    // module docs above.
    panic!("run the documented procedure instead of this placeholder");
}
