// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 OUTRAM PARK contributors
//
// Derived from GeN-Foam (Generalized Nuclear Foam)
//   Upstream: src/classes/thermalHydraulics/src/physicsModels/turbulenceModels/
//             {porousKEpsilon,porousKEpsilon2PhaseCorrected}/
//             {porousKEpsilon.C,porousKEpsilon.H,
//             porousKEpsilon2PhaseCorrected.C,porousKEpsilon2PhaseCorrected.H}
//   Upstream commit: 652b3da
//   Upstream copyright: (C) 2015-2022 EPFL; built on OpenFOAM v2506
//   Upstream author: Stefan Radman (EPFL)
//   Upstream license: GPL-3.0
//
// This file is part of OUTRAM PARK, distributed under GPL-3.0. See the crate
// root or <https://www.gnu.org/licenses/> for the full license text.

//! # `porous_k_epsilon` — porous-medium `k`/`epsilon` relaxation
//!
//! Port of GeN-Foam's `porousKEpsilon` and `porousKEpsilon2PhaseCorrected`.
//! Both force `k` and `epsilon` to relax toward an **equilibrium** value
//! inside porous zones (fuel-pin bundles, spacer grids — anywhere sub-mesh
//! structure exists), because the mesh is too coarse to resolve the actual
//! turbulence generated by that structure. The equilibrium values come from a
//! turbulence-intensity/length-scale correlation, not from solving a transport
//! equation. `porousKEpsilon2PhaseCorrected` differs only in adding a
//! void-fraction-dependent term to the turbulence-intensity correlation.
//!
//! GeN-Foam-original models (no external literature reference beyond the
//! standard turbulence-intensity/mixing-length correlation form
//! `I = A*Re^B`, `L = C*Dh`).
//!
//! ## What this module ports
//!
//! [`PorousKEpsilonClosure`] carries the porous-relaxation coefficients and
//! exposes:
//!
//! - [`PorousKEpsilonClosure::equilibrium_k`] — the turbulence-intensity
//!   correlation for the porous-zone equilibrium `k`.
//! - [`PorousKEpsilonClosure::equilibrium_epsilon`] — the mixing-length
//!   correlation for the porous-zone equilibrium `epsilon`.
//! - [`PorousKEpsilonClosure::relaxation_coefficient`] — the
//!   relaxation-toward-equilibrium coefficient `alphaRhoConv`.
//! - [`PorousKEpsilonClosure::nut_stabilization`] — the optional `nut`
//!   stabilisation addend (`DhStruct`/`laminarReStruct`).
//!
//! [`PorousKEpsilon2PhaseClosure`] wraps a [`PorousKEpsilonClosure`] (adding
//! the `turbulenceIntensityAlphaCoeff` term `D`) and overrides only
//! `equilibrium_k`; `equilibrium_epsilon`, `relaxation_coefficient`, and
//! `nut_stabilization` are identical between the two upstream classes, so
//! [`PorousKEpsilon2PhaseClosure`] delegates to its embedded base rather than
//! duplicating them (composition, not inheritance — no trait objects).
//!
//! **`kSource`/`epsilonSource` are not ported**: upstream, both are literally
//! empty placeholder `fvScalarMatrix`s (`new fvScalarMatrix(k_, <dims>)` with
//! no coefficients set) for *both* `porousKEpsilon` and
//! `porousKEpsilon2PhaseCorrected` — there is no algebra there to port. The
//! actual porous relaxation happens via `alphaRhoConv` directly inside
//! `correct()`'s `epsEqn`/`kEqn` assembly (`- fvm::Sp(alphaRhoConv, k) +
//! alphaRhoConv*equilibriumK`), which is
//! [`relaxation_coefficient`](PorousKEpsilonClosure::relaxation_coefficient)
//! plus [`equilibrium_k`](PorousKEpsilonClosure::equilibrium_k) — both ported
//! above.

use super::units::{
    volumetric_relaxation_coefficient, EddyViscosity, HydraulicDiameter, TurbulentDissipationRate,
    TurbulentKineticEnergy, VoidFraction, VolumetricRelaxationCoefficient,
};
use crate::genfoam::thermal_hydraulics::units::ReynoldsNumber;
use uom::si::available_energy::joule_per_kilogram;
use uom::si::f64::{MassDensity, Velocity};
use uom::si::kinematic_viscosity::square_meter_per_second;
use uom::si::length::meter;
use uom::si::mass_density::kilogram_per_cubic_meter;
use uom::si::ratio::ratio;
use uom::si::specific_power::watt_per_kilogram;
use uom::si::velocity::meter_per_second;

/// OpenFOAM's `SMALL` constant (`1e-15`), used upstream as the length-scale
/// floor in `equilibriumEpsilon_` (`max(turbulenceLengthScaleCoeff*Dh,
/// SMALL)`).
const SMALL_LENGTH: f64 = 1e-15;

/// Porous-medium `k`/`epsilon` relaxation-to-equilibrium closure
/// (`porousKEpsilon`).
///
/// Fields correspond to the upstream per-region dictionary entries
/// (`porousKEpsilonProperties.<region>`); upstream reads and paints these onto
/// cell zones at construction time (a mesh/structure concern — see the parent
/// module doc) — here they are plain already-resolved per-cell coefficients.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PorousKEpsilonClosure {
    /// Standard k-epsilon eddy-viscosity coefficient `Cmu` (dimensionless,
    /// upstream default `0.09`), used here only inside
    /// [`equilibrium_epsilon`](Self::equilibrium_epsilon) as `Cmu^0.75`.
    pub cmu: f64,
    /// Turbulence-intensity correlation coefficient `A` in `I_t =
    /// A*Re^B` (dimensionless).
    pub turbulence_intensity_coeff: f64,
    /// Turbulence-intensity correlation exponent `B` in `I_t = A*Re^B`
    /// (dimensionless, typically negative).
    pub turbulence_intensity_exp: f64,
    /// Turbulence length-scale correlation coefficient `C` in `L_t = C*Dh`
    /// (dimensionless).
    pub turbulence_length_scale_coeff: f64,
}

impl PorousKEpsilonClosure {
    /// Porous-zone equilibrium turbulent kinetic energy.
    ///
    /// Upstream `equilibriumK_ = 1.5*sqr(mag(U) * turbulenceIntensityCoeff *
    /// pow(Re, turbulenceIntensityExp))`, i.e. `k_eq = 1.5*(|U|*I_t)^2` with
    /// turbulence intensity `I_t = A*Re^B`.
    #[must_use]
    pub fn equilibrium_k(
        &self,
        speed: Velocity,
        reynolds_number: ReynoldsNumber,
    ) -> TurbulentKineticEnergy {
        let u = speed.get::<meter_per_second>();
        let re = reynolds_number.get::<ratio>();
        let turbulence_intensity =
            self.turbulence_intensity_coeff * re.powf(self.turbulence_intensity_exp);

        TurbulentKineticEnergy::new::<joule_per_kilogram>(1.5 * (u * turbulence_intensity).powi(2))
    }

    /// Porous-zone equilibrium turbulent dissipation rate.
    ///
    /// Upstream `equilibriumEpsilon_ = Cmu3by4 * pow(equilibriumK_, 1.5) /
    /// max(turbulenceLengthScaleCoeff*Dh, SMALL)`.
    #[must_use]
    pub fn equilibrium_epsilon(
        &self,
        equilibrium_k: TurbulentKineticEnergy,
        structure_dh: HydraulicDiameter,
    ) -> TurbulentDissipationRate {
        let k = equilibrium_k.get::<joule_per_kilogram>();
        let length_scale =
            (self.turbulence_length_scale_coeff * structure_dh.get::<meter>()).max(SMALL_LENGTH);

        TurbulentDissipationRate::new::<watt_per_kilogram>(
            self.cmu.powf(0.75) * k.powf(1.5) / length_scale,
        )
    }

    /// Relaxation-toward-equilibrium coefficient `alphaRhoConv`.
    ///
    /// Upstream `alphaRhoConv = alpha*rho*(mag(U)/convergenceLength) *
    /// yesStructure()`. The `yesStructure()` (`pos(structure)`) step-function
    /// gate is a mesh-zone concern — the caller applies this coefficient only
    /// inside porous cells, so it is not modelled here (equivalently: call
    /// this only where `alpha_structure > 0`).
    #[must_use]
    pub fn relaxation_coefficient(
        alpha: VoidFraction,
        rho: MassDensity,
        speed: Velocity,
        convergence_length: HydraulicDiameter,
    ) -> VolumetricRelaxationCoefficient {
        let a = alpha.get::<ratio>();
        let r = rho.get::<kilogram_per_cubic_meter>();
        let u = speed.get::<meter_per_second>();
        let l = convergence_length.get::<meter>();

        volumetric_relaxation_coefficient(a * r * (u / l))
    }

    /// Optional `nut` stabilisation addend, applied inside porous cells when
    /// `DhStruct` is configured for the region.
    ///
    /// Upstream (`correctNut()`, when `nutStabilization_`): `nut +=
    /// pos(structure) * magU * DhStruct / laminarReStruct`. As with
    /// [`relaxation_coefficient`](Self::relaxation_coefficient), the
    /// `pos(structure)` gate is the caller's responsibility (add this only
    /// inside porous cells with `DhStruct` configured).
    #[must_use]
    pub fn nut_stabilization(
        speed: Velocity,
        dh_struct: HydraulicDiameter,
        laminar_re_struct: f64,
    ) -> EddyViscosity {
        let u = speed.get::<meter_per_second>();
        let dh = dh_struct.get::<meter>();

        EddyViscosity::new::<square_meter_per_second>(u * dh / laminar_re_struct)
    }
}

/// Two-phase-corrected porous-medium `k`/`epsilon` relaxation closure
/// (`porousKEpsilon2PhaseCorrected`).
///
/// Identical to [`PorousKEpsilonClosure`] except the turbulence-intensity
/// correlation gains an additive void-fraction term `D*(1 - alpha_relative)`.
/// Wraps (rather than duplicates) a [`PorousKEpsilonClosure`] for the other
/// three methods.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PorousKEpsilon2PhaseClosure {
    /// The shared porous-relaxation coefficients and methods
    /// (`equilibrium_epsilon`, `relaxation_coefficient`,
    /// `nut_stabilization`, and the `A`/`B` turbulence-intensity terms).
    pub base: PorousKEpsilonClosure,
    /// Void-fraction turbulence-intensity coefficient `D` in `I_t =
    /// A*Re^B + D*(1 - alpha_relative)` (dimensionless).
    pub turbulence_intensity_alpha_coeff: f64,
}

impl PorousKEpsilon2PhaseClosure {
    /// Porous-zone equilibrium turbulent kinetic energy, two-phase-corrected.
    ///
    /// Upstream `equilibriumK_ = 1.5*sqr(mag(U) * (turbulenceIntensityCoeff *
    /// pow(Re, turbulenceIntensityExp) + turbulenceIntensityAlphaCoeff *
    /// (1 - alpha/(1-alpha_structure))))`.
    ///
    /// `relative_alpha` is the phase fraction already divided by
    /// `(1 - alpha_structure)` (upstream's own comment: "phase fraction must
    /// be divided by `(1-alpha.structure)` to get relative value") — a
    /// structure-field lookup out of scope for this closure, so the caller
    /// passes the ratio pre-computed.
    #[must_use]
    pub fn equilibrium_k(
        &self,
        speed: Velocity,
        reynolds_number: ReynoldsNumber,
        relative_alpha: VoidFraction,
    ) -> TurbulentKineticEnergy {
        let u = speed.get::<meter_per_second>();
        let re = reynolds_number.get::<ratio>();
        let ar = relative_alpha.get::<ratio>();

        let turbulence_intensity = self.base.turbulence_intensity_coeff
            * re.powf(self.base.turbulence_intensity_exp)
            + self.turbulence_intensity_alpha_coeff * (1.0 - ar);

        TurbulentKineticEnergy::new::<joule_per_kilogram>(1.5 * (u * turbulence_intensity).powi(2))
    }
}
