// SPDX-License-Identifier: GPL-3.0

//! **Code-to-code: `sembawang`'s accident release, with real normal-operation
//! pools (the #448 default), against upstream TRISO-ATOPS** (`de374c8`,
//! `trisoatops.py::main` = `normal_operation` then `accident_case`).
//!
//! # Methodology
//!
//! **The reference.** Upstream's final accident totals for Stoyer et al. 2026
//! Case A, one per Fig. 5 temperature curve, each applied uniformly to every
//! node. They were generated by `boon-lay/dev/mhtgr_stoyer_upstream.py` and
//! committed as
//! `boon-lay/verification_and_validation/mhtgr_stoyer/upstream_case_a{,_diagnostic_kplate_7p5e-4}_accident.csv`,
//! column `total_<p>` in Ci. `boon-lay`'s own `tests/mhtgr_stoyer_workflow.rs`
//! verifies its hand composition against them at 1e-9.
//!
//! **What is new here:** the same case driven through **`sembawang`'s public
//! API** (`accident_release_with_venting`), with the pools coming from
//! [`PrimaryCircuitPools::FromNormalOperation`]. The inputs:
//! - **nodes:** 3 rings × 14 axial;
//! - **normal-operation temperatures:** per node, from Table 7 (graphite =
//!   fuel, as the paper sets);
//! - **inventory:** Table 6, per ring, split axially by upstream's own
//!   distribution;
//! - **constants:** from `constants.csv` (Stoyer Tables 2–3);
//! - **HPS:** on;
//! - **pressure:** 101.325 kPa.
//!
//! The quantity compared is the **unfloored cumulative endpoint**,
//! [`sembawang::accident::release::AccidentRelease::cumulative_final`],
//! i.e. upstream's last total.
//!
//! **Pass criterion:** relative difference ≤ **1e-9**, the workspace's
//! code-to-code tolerance (the same gate as `mhtgr_stoyer_workflow.rs`), for
//! every nuclide of every curve whose venting mask is **contiguous**.
//!
//! **Gappy masks are not compared, by design.** There, upstream pairs a venting
//! *selection* with a temperature *prefix*, which is a documented upstream
//! defect that `sembawang` deliberately does not reproduce
//! (`sembawang::accident::venting`). They are counted and printed.
//!
//! # Results
//!
//! 2026-09-30, `cargo test --release -p sembawang --test
//! normal_operation_pools_code_to_code`: **186** nuclide-curve totals
//! compared, over both `k_plate` values (7.5e-5 and 7.5e-4) and the 5 % and
//! 25 % curves. The **worst relative difference is 3.84e-12** (the 25 % curve,
//! `k_plate` 7.5e-4, Sr-91). **PASS** at 1e-9.
//!
//! The 20 % and 50 % curves have gappy venting masks and are not compared,
//! as designed. This verifies `sembawang`'s whole orchestration against
//! upstream, including the #448 normal-operation pools:
//! - the per-node `normal_operation` and parent chaining;
//! - the drawdown `release_activity`;
//! - the circuit term `C + x_liftoff · P`;
//! - the atoms-to-curies conversions.

use sembawang::accident::release::{
    accident_release_with_venting, NodeTemperatures, NormalOperation, PlantParameters,
    PrimaryCircuitPools, Venting,
};
use sembawang::inventory::{CoreInventory, NuclideInventory};
use sembawang::scenario::TemperatureTransient;
use std::collections::HashMap;
use std::path::PathBuf;

use boon_lay::triso_atops_fork::accident::AccidentFractions;
use uom::si::f64::{Frequency, Length, Pressure, Radioactivity, ThermodynamicTemperature, Time};
use uom::si::frequency::hertz;
use uom::si::length::meter;
use uom::si::pressure::kilopascal;
use uom::si::radioactivity::curie;
use uom::si::thermodynamic_temperature::{degree_celsius, kelvin};
use uom::si::time::second;

const N_AXIAL: usize = 14;
const N_RADIAL: usize = 3;
const YEAR_S: f64 = 365.0 * 24.0 * 3600.0;
const CI_TO_BQ: f64 = 3.7e10;
const TOLERANCE: f64 = 1e-9;

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../boon-lay/verification_and_validation/mhtgr_stoyer")
        .join(name)
}

/// A cited CSV as header -> value maps, `#` lines skipped.
fn table(name: &str) -> Vec<HashMap<String, String>> {
    let text = std::fs::read_to_string(data(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
    let mut lines = text.lines().filter(|l| !l.starts_with('#') && !l.trim().is_empty());
    let header: Vec<String> = lines.next().unwrap().split(',').map(str::to_string).collect();
    lines
        .map(|l| header.iter().cloned().zip(l.split(',').map(str::to_string)).collect())
        .collect()
}

fn f(row: &HashMap<String, String>, key: &str) -> f64 {
    row[key].trim().parse().unwrap_or_else(|_| panic!("{key}: {}", row[key]))
}

fn rel(a: f64, b: f64) -> f64 {
    if a == b {
        0.0
    } else {
        (a - b).abs() / a.abs().max(b.abs())
    }
}

/// Fig. 5 curves as (percent, [(hours, °C)]), negative times clamped to 0,
/// exactly as `mhtgr_stoyer_workflow.rs::fig5` does.
fn fig5() -> Vec<(String, Vec<(f64, f64)>)> {
    let mut curves: Vec<(String, Vec<(f64, f64)>)> = Vec::new();
    for r in table("fig05_accident_temperature_c.csv") {
        let p = r["core_fraction_percent"].clone();
        let pt = (f(&r, "time_h").max(0.0), f(&r, "temperature_c"));
        match curves.iter_mut().find(|(q, _)| *q == p) {
            Some((_, v)) => v.push(pt),
            None => curves.push((p, vec![pt])),
        }
    }
    curves
}

fn plant(k_plate: Option<f64>) -> PlantParameters {
    let consts: HashMap<String, f64> = table("constants.csv")
        .iter()
        .map(|r| (r["key"].clone(), f(r, "case_a")))
        .collect();
    let c = |k: &str| consts[k];
    let temps = table("table07_core_temperature_k.csv");
    assert_eq!(temps.len(), N_AXIAL);
    // [ring][axial], graphite = fuel (the paper's choice).
    let per_node: Vec<Vec<ThermodynamicTemperature>> = (0..N_RADIAL)
        .map(|ring| {
            temps
                .iter()
                .map(|row| {
                    ThermodynamicTemperature::new::<kelvin>(f(row, &format!("ring{}_k", ring + 1)))
                })
                .collect()
        })
        .collect();
    PlantParameters {
        fractions: AccidentFractions {
            heavy_metal: c("f_hm"),
            sic: c("f_sic"),
            incremental: c("f_inc"),
            incremental_sic: c("f_inc_sic"),
            incremental_accident: c("f_inc_acc"),
            incremental_sic_accident: c("f_inc_sic_acc"),
        },
        graphite_thickness: Length::new::<meter>(c("a_graph")),
        kernel_radius: Length::new::<meter>(c("r_kernel")),
        sic_thickness: Length::new::<meter>(c("a_SiC")),
        coolant_pressure: Pressure::new::<kilopascal>(101.325),
        x_liftoff: c("x_liftoff"),
        clean_up_fitted: true,
        pools: PrimaryCircuitPools::FromNormalOperation(NormalOperation {
            k_plate: Frequency::new::<hertz>(k_plate.unwrap_or(c("k_plate"))),
            k_clean: Frequency::new::<hertz>(c("k_clean")),
            grain_size: Length::new::<meter>(c("a_grain")),
            run_time: Time::new::<second>(c("run_time") * YEAR_S),
            irradiation_time: Time::new::<second>(c("irradiation_time") * YEAR_S),
            temperatures: NodeTemperatures::PerNode {
                core: per_node.clone(),
                graphite: per_node,
            },
        }),
    }
}

fn inventory() -> CoreInventory {
    let nuclides = table("table06_case_a_inventory_ci.csv")
        .iter()
        .map(|r| NuclideInventory {
            name: r["nuclide"].clone(),
            per_ring: (1..=N_RADIAL)
                .map(|i| Radioactivity::new::<curie>(f(r, &format!("ring{i}_ci"))))
                .collect(),
        })
        .collect();
    CoreInventory::new(nuclides, N_RADIAL, N_AXIAL)
}

fn transient(curve: &[(f64, f64)]) -> TemperatureTransient {
    let times = curve.iter().map(|(t, _)| Time::new::<second>(t * 3600.0)).collect();
    let temps = (0..N_RADIAL)
        .map(|_| {
            curve
                .iter()
                .map(|(_, c)| vec![ThermodynamicTemperature::new::<degree_celsius>(*c); N_AXIAL])
                .collect()
        })
        .collect();
    TemperatureTransient::from_nodes(times, temps).expect("a Fig. 5 curve has enough samples")
}

#[test]
fn sembawang_with_real_pools_matches_upstream_accident_case_on_mhtgr_case_a() {
    let inv = inventory();
    let mut worst = (0.0_f64, String::new());
    let (mut compared, mut gappy) = (0usize, Vec::new());
    for (kp, suffix) in [(None, ""), (Some(7.5e-4), "_diagnostic_kplate_7p5e-4")] {
        let plant = plant(kp);
        let up: HashMap<String, HashMap<String, String>> =
            table(&format!("upstream_case_a{suffix}_accident.csv"))
                .into_iter()
                .map(|r| (r["nuclide"].clone(), r))
                .collect();
        for (pct, curve) in fig5() {
            let out = accident_release_with_venting(&inv, &transient(&curve), &plant, &Venting::Upstream)
                .expect("the chain runs");
            if !out.venting.is_contiguous() {
                gappy.push(format!("k_plate{suffix} {pct}%"));
                continue;
            }
            for (name, bq) in &out.cumulative_final {
                let u = f(&up[name], &format!("total_{pct}"));
                let r = rel(bq / CI_TO_BQ, u);
                compared += 1;
                if r > worst.0 {
                    worst = (r, format!("k_plate{suffix} {pct}% {name}: sembawang {} upstream {u} Ci", bq / CI_TO_BQ));
                }
            }
        }
    }
    println!(
        "sembawang (real pools) vs upstream accident_case: {compared} nuclide-curve totals compared, \
         worst relative difference {:.3e} ({}); gappy curves not compared: {gappy:?}",
        worst.0, worst.1
    );
    assert!(compared > 0, "nothing was compared");
    assert!(worst.0 <= TOLERANCE, "{worst:?}");
}

#[test]
fn every_constructor_starts_from_real_pools_and_empty_is_an_explicit_ablation() {
    // CLAUDE.md "correct physics is the default": pinned so it cannot drift off.
    let reference = PlantParameters::np_mhtgr_reference(1e-4, 1e-4, 0.0);
    assert!(matches!(reference.pools, PrimaryCircuitPools::FromNormalOperation(_)));
    let ablated = reference.without_normal_operation_pools();
    assert!(matches!(ablated.pools, PrimaryCircuitPools::EmptyAblation));
    let g = sembawang::htr10::Htr10Geometry {
        kernel_radius: Length::new::<meter>(2.5e-4),
        sic_thickness: Length::new::<meter>(3.5e-5),
        graphite_thickness: Length::new::<meter>(5e-3),
    };
    let htr10 = sembawang::htr10::plant_parameters(g, sembawang::htr10::np_mhtgr_normal_operation_fractions());
    assert!(matches!(htr10.pools, PrimaryCircuitPools::FromNormalOperation(_)));
}
