! SPDX-License-Identifier: GPL-3.0
!
! Code-to-code reference driver for the `changi::flexpart` port.
!
! Calls the UPSTREAM FLEXPART routines directly -- compiled verbatim from
! upstream_source/FLEXPART/src, not reimplemented here -- over a grid of inputs
! that straddles every branch in each routine, and writes one CSV row per case.
!
! Built TWICE by dev/build_reference.sh:
!   * as shipped        -> default `real` is real(4), which is what FLEXPART's
!                          own makefile produces (it passes no -fdefault-real-8)
!   * -fdefault-real-8  -> the same algorithm in real(8)
!
! Matching the double build to near machine precision isolates the TRANSLATION;
! the single build then measures FLEXPART's own precision. Every value is
! promoted with dble() before printing, so a real(4) result is written as its
! exact f64 expansion rather than a re-rounded decimal.
program flexpart_reference

  use par_mod
  use class_gribfile
  implicit none

  real :: ew, viscosity, psim, psih, scalev, obukhov, raerod
  external :: part0

  write(*,'(A)') '# FLEXPART code-to-code reference, generated by dev/flexpart_reference.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference.sh'
  write(*,'(A)') 'function,args,expected'

  call emit_ew()
  call emit_viscosity()
  call emit_psim()
  call emit_psih()
  call emit_scalev()
  call emit_obukhov()
  call emit_raerod()
  call emit_part0()

contains

  ! One CSV row: name, semicolon-joined args, value. Values promoted to real(8)
  ! so a single-precision build prints the EXACT f32 value, not a re-rounding.
  subroutine row1(name, a1, v)
    character(len=*), intent(in) :: name
    real, intent(in) :: a1, v
    write(*,'(A,A,ES25.17E3,A,ES25.17E3)') trim(name), ',', dble(a1), ',', dble(v)
  end subroutine row1

  subroutine row2(name, a1, a2, v)
    character(len=*), intent(in) :: name
    real, intent(in) :: a1, a2, v
    write(*,'(A,A,ES25.17E3,A,ES25.17E3,A,ES25.17E3)') &
         trim(name), ',', dble(a1), ';', dble(a2), ',', dble(v)
  end subroutine row2

  subroutine row3(name, a1, a2, a3, v)
    character(len=*), intent(in) :: name
    real, intent(in) :: a1, a2, a3, v
    write(*,'(A,A,ES25.17E3,A,ES25.17E3,A,ES25.17E3,A,ES25.17E3)') &
         trim(name), ',', dble(a1), ';', dble(a2), ';', dble(a3), ',', dble(v)
  end subroutine row3

  subroutine row4(name, a1, a2, a3, a4, v)
    character(len=*), intent(in) :: name
    real, intent(in) :: a1, a2, a3, a4, v
    write(*,'(A,A,ES25.17E3,3(A,ES25.17E3),A,ES25.17E3)') &
         trim(name), ',', dble(a1), ';', dble(a2), ';', dble(a3), ';', dble(a4), &
         ',', dble(v)
  end subroutine row4

  subroutine row8(name, a1, a2, a3, a4, a5, a6, a7, a8, v)
    character(len=*), intent(in) :: name
    real, intent(in) :: a1, a2, a3, a4, a5, a6, a7, a8, v
    write(*,'(A,A,ES25.17E3,7(A,ES25.17E3),A,ES25.17E3)') &
         trim(name), ',', dble(a1), ';', dble(a2), ';', dble(a3), ';', dble(a4), &
         ';', dble(a5), ';', dble(a6), ';', dble(a7), ';', dble(a8), ',', dble(v)
  end subroutine row8

  ! ---- saturation vapour pressure (ew.f90) --------------------------------
  ! Guard: ew halts on T <= 0, so the grid stays strictly positive.
  subroutine emit_ew()
    integer :: i
    real :: t
    do i = 1, 31
      t = 200.0 + real(i-1)*5.0        ! 200 .. 350 K
      call row1('ew', t, ew(t))
    end do
    ! Cold and hot extremes of the Goff-Gratch fit's useful range.
    call row1('ew', 173.15, ew(173.15))
    call row1('ew', 373.16, ew(373.16))
  end subroutine emit_ew

  ! ---- dynamic viscosity (dynamic_viscosity.f90) --------------------------
  subroutine emit_viscosity()
    integer :: i
    real :: t
    do i = 1, 31
      t = 200.0 + real(i-1)*5.0
      call row1('viscosity', t, viscosity(t))
    end do
  end subroutine emit_viscosity

  ! ---- Monin-Obukhov stability functions (psim.f90, psih.f90) -------------
  ! Grid straddles both branches (sign of zeta) and psih's far-field cutoff.
  subroutine emit_psim()
    integer :: i, j
    real :: z, l
    real :: zs(6), ls(12)
    zs = (/ 0.01, 0.1, 1.0, 10.0, 15.0, 100.0 /)
    ls = (/ -10000.0, -1000.0, -100.0, -30.0, -10.0, -1.0, &
              1.0, 10.0, 30.0, 100.0, 1000.0, 10000.0 /)
    do i = 1, 6
      z = zs(i)
      do j = 1, 12
        l = ls(j)
        call row2('psim', z, l, psim(z, l))
      end do
    end do
  end subroutine emit_psim

  subroutine emit_psih()
    integer :: i, j
    real :: z, l, lcopy
    real :: zs(6), ls(12)
    zs = (/ 0.01, 0.1, 1.0, 10.0, 15.0, 100.0 /)
    ls = (/ -10000.0, -1000.0, -100.0, -30.0, -10.0, -1.0, &
              1.0, 10.0, 30.0, 100.0, 1000.0, 10000.0 /)
    do i = 1, 6
      z = zs(i)
      do j = 1, 12
        ! psih MUTATES its l argument (near-zero nudge), so pass a copy and
        ! record the ORIGINAL l as the case's input -- otherwise the fixture
        ! would record an argument the caller never supplied.
        l = ls(j)
        lcopy = l
        call row2('psih', z, l, psih(z, lcopy))
      end do
    end do
  end subroutine emit_psih

  ! ---- friction velocity (scalev.f90) -------------------------------------
  subroutine emit_scalev()
    integer :: i, j, k, m
    real :: ps, t, td, st
    real :: pss(3), ts(3), tds(3), sts(4)
    pss = (/ 85000.0, 101325.0, 105000.0 /)
    ts  = (/ 253.15, 288.15, 313.15 /)
    tds = (/ 243.15, 278.15, 303.15 /)
    sts = (/ 0.0, 0.01, 0.1, 1.0 /)
    do i = 1, 3
      ps = pss(i)
      do j = 1, 3
        t = ts(j)
        do k = 1, 3
          td = tds(k)
          do m = 1, 4
            st = sts(m)
            call row4('scalev', ps, t, td, st, scalev(ps, t, td, st))
          end do
        end do
      end do
    end do
  end subroutine emit_scalev

  ! ---- Obukhov length (obukhov.f90) ---------------------------------------
  ! Covers both met formats, the ustar<=0 guard, the zero-heat-flux sentinel
  ! and the +/-9999 clamp.
  subroutine emit_obukhov()
    integer :: i, j, k
    real :: ps, tsurf, tdsurf, tlev, ustar, hf, plev, res
    real :: akm(nwzmax), bkm(nwzmax)
    real :: ustars(4), hfs(7)
    ustars = (/ -1.0, 0.0, 0.1, 0.5 /)
    hfs = (/ -200.0, -50.0, -1.0, 0.0, 1.0, 50.0, 300.0 /)
    akm = 0.0
    bkm = 0.0
    akm(1) = 0.0
    akm(2) = 20.0
    bkm(1) = 1.0
    bkm(2) = 0.997
    ps = 101325.0
    tsurf = 288.15
    tdsurf = 280.15
    tlev = 287.0
    do j = 1, 4
      do k = 1, 7
        ! NCEP path: plev is supplied by the caller and used as given.
        ustar = ustars(j)
        hf = hfs(k)
        plev = 100000.0
        res = obukhov(ps, tsurf, tdsurf, tlev, ustar, hf, akm, bkm, plev, &
                      GRIBFILE_CENTRE_NCEP)
        call row8('obukhov.ncep', ps, tsurf, tdsurf, tlev, ustars(j), hfs(k), &
                  100000.0, 0.0, res)
        ! ECMWF path: plev is REBUILT from akm/bkm and the passed value ignored.
        ustar = ustars(j)
        hf = hfs(k)
        plev = 100000.0
        res = obukhov(ps, tsurf, tdsurf, tlev, ustar, hf, akm, bkm, plev, &
                      GRIBFILE_CENTRE_ECMWF)
        call row8('obukhov.ecmwf', ps, tsurf, tdsurf, tlev, ustars(j), hfs(k), &
                  100000.0, 1.0, res)
      end do
    end do
  end subroutine emit_obukhov

  ! ---- aerodynamic resistance (raerod.f90) --------------------------------
  subroutine emit_raerod()
    integer :: i, j, k
    real :: l, ust, z0
    real :: ls(8), usts(4), z0s(5)
    ls   = (/ -1000.0, -100.0, -10.0, -1.0, 1.0, 10.0, 100.0, 1000.0 /)
    usts = (/ 0.05, 0.1, 0.3, 1.0 /)
    z0s  = (/ 0.0001, 0.001, 0.01, 0.1, 1.0 /)
    do i = 1, 8
      do j = 1, 4
        do k = 1, 5
          l = ls(i)
          ust = usts(j)
          z0 = z0s(k)
          call row3('raerod', l, ust, z0, raerod(l, ust, z0))
        end do
      end do
    end do
  end subroutine emit_raerod

  ! ---- lognormal aerosol bins (part0.f90) ---------------------------------
  ! part0 returns arrays, so each bin is emitted as its own row, tagged by
  ! quantity and bin index. Upstream's scalar `cun` is emitted separately.
  subroutine emit_part0()
    integer :: i, j, k, b
    real :: dquer, dsigma, density, cun
    real :: fract(ni), schmi(ni), vsh(ni)
    real :: dq(4), ds(3), rho(3)
    dq  = (/ 0.1, 0.4, 1.0, 10.0 /)      ! micrometres
    ds  = (/ 1.1, 1.3, 3.0 /)
    rho = (/ 1000.0, 1500.0, 2500.0 /)
    do i = 1, 4
      do j = 1, 3
        do k = 1, 3
          dquer = dq(i)
          dsigma = ds(j)
          density = rho(k)
          call part0(dquer, dsigma, density, fract, schmi, cun, vsh)
          do b = 1, ni
            call row4('part0.fract',   dq(i), ds(j), rho(k), real(b), fract(b))
            call row4('part0.schmi',   dq(i), ds(j), rho(k), real(b), schmi(b))
            call row4('part0.vsh',     dq(i), ds(j), rho(k), real(b), vsh(b))
          end do
          call row3('part0.cun_scalar', dq(i), ds(j), rho(k), cun)
        end do
      end do
    end do
  end subroutine emit_part0

end program flexpart_reference
