! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART code-to-code reference driver, stage `vert`: the vertical
! transformation of the raw model-level meteorology to FLEXPART's z grid,
! and the longitude shift of global fields.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) VERBATIM:
!   verttransform_ecmwf, verttransform_gfs, verttransform_nests,
!   shift_field, shift_field_0
! and what they call (cmapf_mod: cc2gll, stlmbr, stcm2p; ew; qvsat: f_qvsat)
! plus par_mod and com_mod. See dev/build_reference_vert.sh.
!
! NEST CONFIGURATION. The shipped par_mod.f90 sets maxnests=0, nxmaxn=0,
! nymaxn=0. par_mod.f90 is FLEXPART's user-edited configuration file; the
! build compiles a COPY with only that line changed, to maxnests=2,
! nxmaxn=12, nymaxn=12 (two nests, so the cloud-base carry-over from one nest
! to the next is exercised). The build checks the diff is exactly that line.
!
! STATE BETWEEN CALLS. The verttransform routines keep SAVEd state (`init`,
! and in GFS the static local `uvwzlev`) and read com_mod output arrays they
! only partly rewrite. Upstream semantics therefore depend on the whole
! sequence of calls in a process. The driver is run once per PROCESS SET
! (argument p1, p2, shift) so each set starts from fresh SAVE state, and the
! Rust test replays each set's calls in the same order. Every output array
! is prefilled with sentinels at process start (reals -7, clouds 7,
! cloudsh 3, nmixz 99) so stale values are visible.
!
! All meteorology is SYNTHETIC (no GRIB). Inputs are built in double precision
! and rounded ONCE to real(4) in both builds (function r4), so the two builds
! are fed identical values; every input is echoed as a setup row.
!
! Undefined upstream behaviour is avoided by construction and checked by the
! port, which refuses it: no precipitating cloud-free column before the first
! cloudy one with cloud water (cloudh_min), no cloudy nest level 1 with
! precipitation (height(0)), polar bands inside the grid.
!
! Row format, one row per record:  function,a1;a2;...,o1;o2;...
! The CSV goes to the file named by argument 2 (upstream prints progress
! messages on stdout).
program flexpart_reference_vert

  use par_mod
  use com_mod
  use cmapf_mod, only: stlmbr, stcm2p
  implicit none

  integer, parameter :: KZ = 8
  real, allocatable :: uuh(:,:,:), vvh(:,:,:), pvh(:,:,:), wwh(:,:,:)
  real, allocatable :: uuhn(:,:,:,:), vvhn(:,:,:,:), pvhn(:,:,:,:), wwhn(:,:,:,:)
  character(len=16) :: which
  character(len=512) :: outpath
  integer :: uo
  logical :: grid_echoed(20) = .false., set_echoed(30) = .false.

  call get_command_argument(1, which)
  call get_command_argument(2, outpath)
  open(newunit=uo, file=trim(outpath), status='replace', action='write')
  if (trim(which) == 'p1') then
    write(uo,'(A)') '# FLEXPART stage-vert reference, generated by dev/flexpart_reference_vert.f90'
    write(uo,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
    write(uo,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_vert.sh'
    write(uo,'(A)') 'function,args,outputs'
  end if

  allocate(uuh(0:nxmax-1,0:nymax-1,nuvzmax), vvh(0:nxmax-1,0:nymax-1,nuvzmax), &
           pvh(0:nxmax-1,0:nymax-1,nuvzmax), wwh(0:nxmax-1,0:nymax-1,nwzmax))
  allocate(uuhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests), &
           vvhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests), &
           pvhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests), &
           wwhn(0:nxmaxn-1,0:nymaxn-1,nwzmax,maxnests))
  uuh = 0.; vvh = 0.; pvh = 0.; wwh = 0.
  uuhn = 0.; vvhn = 0.; pvhn = 0.; wwhn = 0.
  numbnests = 2
  call com_mod_allocate_nests()

  select case (trim(which))
  case ('p1')
    call process1()
  case ('p2')
    call process2()
  case ('shift')
    call emit_shift()
  case default
    stop 'usage: flexpart_reference_vert p1|p2|shift out.csv'
  end select
  close(uo)

contains

  ! ------------------------------------------------------------------------
  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(uo,'(A)') trim(line)
  end subroutine rowv

  ! A double-precision value rounded once to real(4), returned as default real
  ! (so both builds hold the identical value).
  real function r4(x)
    double precision, intent(in) :: x
    r4 = real(real(x, 4))
  end function r4

  ! ------------------------------------------------------------------------
  ! Sentinels in every output array the routines may leave stale.
  subroutine prefill()
    uu(0:7,0:7,1:KZ,:) = -7.; vv(0:7,0:7,1:KZ,:) = -7.; ww(0:7,0:7,1:KZ,:) = -7.
    tt(0:7,0:7,1:KZ,:) = -7.; qv(0:7,0:7,1:KZ,:) = -7.; pv(0:7,0:7,1:KZ,:) = -7.
    rho(0:7,0:7,1:KZ,:) = -7.; drhodz(0:7,0:7,1:KZ,:) = -7.
    prs(0:7,0:7,1:KZ,:) = -7.; pplev(0:7,0:7,1:KZ,:) = -7.
    uupol(0:7,0:7,1:KZ,:) = -7.; vvpol(0:7,0:7,1:KZ,:) = -7.
    clwc(0:7,0:7,1:KZ,:) = -7.; ciwc(0:7,0:7,1:KZ,:) = -7.; clw(0:7,0:7,1:KZ,:) = -7.
    clouds(0:7,0:7,1:KZ,:) = 7; cloudsh(0:7,0:7,:) = 3; ctwc(0:7,0:7,:) = -7.
    uun = -7.; vvn = -7.; wwn = -7.; ttn = -7.; qvn = -7.; pvn = -7.
    rhon = -7.; drhodzn = -7.; clwcn = -7.; ciwcn = -7.; clwn = -7.
    cloudsn = 7; cloudshn = 3; ctwcn = -7.
    height = 0.
    nmixz = 99
  end subroutine prefill

  ! ------------------------------------------------------------------------
  ! Grids. kind: 1 = ECMWF hybrid H8 (to 50 hPa), 2 = GFS pressure P8,
  ! 3 = ECMWF low-top L8 (all heights < hmixmax), 4 = GFS low-top LP8.
  subroutine set_grid(gid)
    integer, intent(in) :: gid
    integer :: lev, k, glob
    double precision :: sw, sz
    double precision, parameter :: h8a(8) = (/ 0d0, 0d0, 2048d0, 8192d0, 16384d0, 18432d0, 6144d0, 5120d0 /)
    double precision, parameter :: h8b(8) = (/ 1d0, 0.96875d0, 0.8125d0, 0.5d0, 0.21875d0, 0d0, 0d0, 0d0 /)
    double precision, parameter :: p8(8) = (/ 100000d0, 92500d0, 85000d0, 70000d0, 50000d0, 18000d0, &
         6000d0, 5000d0 /)
    double precision, parameter :: l8a(8) = (/ 0d0, 0d0, 512d0, 1024d0, 2048d0, 3072d0, 4096d0, 4096d0 /)
    double precision, parameter :: l8b(8) = (/ 1d0, 0.96875d0, 0.9375d0, 0.875d0, 0.8125d0, 0.75d0, &
         0.6875d0, 0.625d0 /)
    double precision, parameter :: lp8(8) = (/ 100000d0, 97500d0, 95000d0, 92500d0, 90000d0, 85000d0, &
         80000d0, 75000d0 /)
    real :: a(200)
    integer :: na

    ! glob: 0 limited, 1 both poles, 2 south only, 3 north only
    select case (gid)
    case (1, 2)
      nx = 5; ny = 5; dx = 90.; dy = 45.; xlon0 = 0.; ylat0 = -90.; glob = 1
    case (3, 6)
      nx = 5; ny = 4; dx = 1.; dy = 1.; xlon0 = 10.; ylat0 = 40.; glob = 0
    case (4)
      nx = 5; ny = 4; dx = 90.; dy = 30.; xlon0 = 180.; ylat0 = -90.; glob = 2
    case (7)
      ! GFS south-pole-only grid at xlon0 = -270 (central column at -180),
      ! so the GFS south ddpol > 2 pi wrap is reachable.
      nx = 5; ny = 4; dx = 90.; dy = 30.; xlon0 = -270.; ylat0 = -90.; glob = 2
    case (5, 8)
      ! xlon0 = -270 is outside gridcheck's (-180,180]: chosen so the central
      ! column nx/2-1 sits at -180 and the ddpol > 2 pi wrap is exercised.
      nx = 5; ny = 4; dx = 90.; dy = 30.; xlon0 = -270.; ylat0 = 0.; glob = 3
    end select
    select case (gid)
    case (1, 4, 5); lev = 1
    case (2, 7, 8); lev = 2
    case (3); lev = 3
    case (6); lev = 4
    end select
    nxmin1 = nx - 1; nymin1 = ny - 1
    nuvz = 8; nz = 8; nwz = 8
    if (gid == 3) nwz = 7
    do k = 1, nuvz
      select case (lev)
      case (1); akz(k) = r4(h8a(k)); bkz(k) = r4(h8b(k))
      case (2); akz(k) = r4(p8(k)); bkz(k) = 0.
      case (3); akz(k) = r4(l8a(k)); bkz(k) = r4(l8b(k))
      case (4); akz(k) = r4(lp8(k)); bkz(k) = 0.
      end select
      aknew(k) = akz(k); bknew(k) = bkz(k)
    end do
    dxconst = r4(180d0/(dble(dx)*6.371d6*3.14159265d0))
    dyconst = r4(180d0/(dble(dy)*6.371d6*3.14159265d0))
    nglobal = (glob == 1 .or. glob == 3)
    sglobal = (glob == 1 .or. glob == 2)
    northpolemap = 0.; southpolemap = 0.
    switchnorthg = 999999.; switchsouthg = 999999.
    if (sglobal) then
      sw = -75d0
      sz = 6d0*(sw+90d0)/dble(dy)
      call stlmbr(southpolemap, -90., 0.)
      call stcm2p(southpolemap, 0., 0., real(sw), 0., real(sz), real(sz), real(sw), 180.)
      do k = 1, 9
        southpolemap(k) = r4(dble(southpolemap(k)))
      end do
      switchsouthg = r4((sw - dble(ylat0))/dble(dy))
    end if
    if (nglobal) then
      sw = 75d0
      sz = 6d0*(90d0-sw)/dble(dy)
      call stlmbr(northpolemap, 90., 0.)
      call stcm2p(northpolemap, 0., 0., real(sw), 0., real(sz), real(sz), real(sw), 180.)
      do k = 1, 9
        northpolemap(k) = r4(dble(northpolemap(k)))
      end do
      switchnorthg = r4((sw - dble(ylat0))/dble(dy))
    end if
    if (.not. grid_echoed(gid)) then
      grid_echoed(gid) = .true.
      a(1:15) = (/ real(nx), real(ny), real(nuvz), real(nwz), real(nz), dx, dy, xlon0, ylat0, &
           dxconst, dyconst, merge(1., 0., nglobal), merge(1., 0., sglobal), switchnorthg, switchsouthg /)
      a(16:24) = northpolemap
      a(25:33) = southpolemap
      na = 33
      a(na+1:na+nuvz) = akz(1:nuvz); na = na + nuvz
      a(na+1:na+nuvz) = bkz(1:nuvz); na = na + nuvz
      a(na+1:na+nz) = aknew(1:nz); na = na + nz
      a(na+1:na+nz) = bknew(1:nz); na = na + nz
      call rowv('vt.grid', (/ real(gid) /), 1, a, na)
    end if
  end subroutine set_grid

  ! ------------------------------------------------------------------------
  ! One synthetic column for data set `sid`. Pressure-dependent quantities use
  ! the level pressure akz + bkz*ps of the CURRENT com_mod coefficients.
  subroutine gen_column(sid, ix, jy, nxg, nyg, polar, c_ps, c_t2, c_td, c_lsp, c_cvp, &
       c_u, c_v, c_pv, c_t, c_q, c_cw, c_ci, c_w)
    integer, intent(in) :: sid, ix, jy, nxg, nyg
    logical, intent(in) :: polar
    real, intent(out) :: c_ps, c_t2, c_td, c_lsp, c_cvp
    real, intent(out) :: c_u(KZ), c_v(KZ), c_pv(KZ), c_t(KZ), c_q(KZ), c_cw(KZ), c_ci(KZ), c_w(KZ)
    double precision :: ps, p, dt, tcol
    integer :: h, k, c, pr
    double precision :: sgn_n, sgn_s

    h = mod(7*ix + 13*jy + 29*sid, 11)
    ps = 98000d0 + 400d0*h
    if (ix == 0 .and. jy == 0) ps = 99000d0
    if (sid == 1 .and. ix == 3 .and. jy == 2) ps = 48000d0
    if (sid == 2 .and. ix == 2 .and. jy == 3) ps = 70000d0
    if (sid == 3 .and. ix == 3 .and. jy == 2) ps = 48000d0
    if (sid == 4 .and. ix == 2 .and. jy == 2) ps = 48000d0
    if (sid == 5 .and. ix == 2 .and. jy == 1) ps = 85000d0
    if (sid == 8 .and. ix == 3 .and. jy == 1) ps = 78000d0
    if (sid == 11 .and. ix == 2 .and. jy == 1) ps = 70000d0
    if (polar .and. ix == nxg/2-1 .and. (jy == 0 .or. jy == nyg-1)) ps = 101000d0
    c_ps = r4(ps)
    ps = dble(c_ps)
    dt = 0.25d0*mod(3*ix + 5*jy + sid, 5) - 0.5d0
    tcol = max(216.5d0, 288.15d0*(ps/101325d0)**0.190263d0) + dt
    c_t2 = r4(tcol + 0.5d0)
    c_td = r4(dble(c_t2) - 3d0 - mod(ix + jy, 3))
    pr = mod(ix + jy + sid, 4)
    select case (pr)
    case (0); c_lsp = 0.; c_cvp = 0.
    case (1); c_lsp = 0.5; c_cvp = 0.125
    case (2); c_lsp = 0.125; c_cvp = 0.75
    case (3); c_lsp = 0.25; c_cvp = 0.25
    end select
    c = mod(2*ix + jy + sid, 3)
    ! Nest 2 of the second nest call starts with a precipitating, cloud-free
    ! column, so its cloud base is inherited from nest 1 (cloudh_min carry-over).
    if (sid == 14 .and. ix == 0 .and. jy == 0) c = 0
    sgn_n = merge(-1d0, 1d0, mod(sid, 2) == 1)
    sgn_s = -sgn_n
    if (sid == 6 .or. sid == 9) sgn_s = 1d0
    if (sid == 7 .or. sid == 10) sgn_n = 1d0
    do k = 1, KZ
      p = dble(akz(k)) + dble(bkz(k))*ps
      c_t(k) = r4(max(216.5d0, 288.15d0*(p/101325d0)**0.190263d0) + dt)
      if (k == 1) c_t(k) = r4(tcol)
      if (p < 20000d0) then
        c_q(k) = r4(2d-6)
      else if (mod(ix + 2*jy + k + sid, 4) == 0) then
        c_q(k) = r4(0.012d0*(p/101325d0)**2)
      else
        c_q(k) = r4(1d-4*(p/101325d0))
      end if
      c_u(k) = r4(4d0 + 0.5d0*k + 1.25d0*ix - 0.75d0*jy + 0.25d0*sid)
      c_v(k) = r4(-3d0 + 0.375d0*k + 0.5d0*ix + 1d0*jy - 0.5d0*sid)
      if (polar .and. ix == nxg/2-1 .and. jy == nyg-1) then
        c_v(k) = r4(sgn_n*(1d0 + 0.25d0*k))
        if (k == 1) c_v(k) = 0.
      end if
      if (polar .and. ix == nxg/2-1 .and. jy == 0) then
        c_v(k) = r4(sgn_s*(1d0 + 0.25d0*k))
        ! data set 9: v < 0 on levels 2-3, v > 0 above, so one GFS call takes
        ! both the ddpol < 0 and the ddpol > 2 pi wraps at the south pole
        if (sid == 9 .and. k <= 3) c_v(k) = -c_v(k)
        if (k == 1) c_v(k) = 0.
      end if
      c_pv(k) = r4(0.5d0*k + 0.125d0*ix - 0.25d0*jy)
      c_w(k) = r4(0.0625d0*(mod(ix + 3*jy + k + sid, 5) - 2))
      c_cw(k) = 0.; c_ci(k) = 0.
      if (c == 1) then
        if (k == 3 .or. k == 4) c_cw(k) = r4(1d-4)
        if (k == 5 .or. k == 6) c_ci(k) = r4(5d-5)
      else if (c == 2) then
        if (k >= 2 .and. k <= 5) c_cw(k) = r4(2d-4)
        if (k >= 7) c_cw(k) = r4(1d-5)
      end if
    end do
  end subroutine gen_column

  ! Fill the mother-grid raw fields of slot n with data set sid (and echo it
  ! once).
  subroutine gen_set(sid, n)
    integer, intent(in) :: sid, n
    integer :: ix, jy
    real :: c_ps, c_t2, c_td, c_lsp, c_cvp
    real :: c_u(KZ), c_v(KZ), c_pv(KZ), c_t(KZ), c_q(KZ), c_cw(KZ), c_ci(KZ), c_w(KZ)
    real :: o(5+8*KZ)
    logical :: polar
    polar = nglobal .or. sglobal
    do jy = 0, nymin1
      do ix = 0, nxmin1
        call gen_column(sid, ix, jy, nx, ny, polar, c_ps, c_t2, c_td, c_lsp, c_cvp, &
             c_u, c_v, c_pv, c_t, c_q, c_cw, c_ci, c_w)
        ps(ix,jy,1,n) = c_ps; tt2(ix,jy,1,n) = c_t2; td2(ix,jy,1,n) = c_td
        lsprec(ix,jy,1,n) = c_lsp; convprec(ix,jy,1,n) = c_cvp
        uuh(ix,jy,1:KZ) = c_u; vvh(ix,jy,1:KZ) = c_v; pvh(ix,jy,1:KZ) = c_pv
        tth(ix,jy,1:KZ,n) = c_t; qvh(ix,jy,1:KZ,n) = c_q
        clwch(ix,jy,1:KZ,n) = c_cw; ciwch(ix,jy,1:KZ,n) = c_ci
        wwh(ix,jy,1:KZ) = c_w
        if (.not. set_echoed(sid)) then
          o(1:5) = (/ c_ps, c_t2, c_td, c_lsp, c_cvp /)
          o(6:5+KZ) = c_u; o(6+KZ:5+2*KZ) = c_v; o(6+2*KZ:5+3*KZ) = c_pv
          o(6+3*KZ:5+4*KZ) = c_t; o(6+4*KZ:5+5*KZ) = c_q; o(6+5*KZ:5+6*KZ) = c_cw
          o(6+6*KZ:5+7*KZ) = c_ci; o(6+7*KZ:5+8*KZ) = c_w
          call rowv('vt.in', (/ real(sid), real(ix), real(jy) /), 3, o, 5+8*KZ)
        end if
      end do
    end do
    set_echoed(sid) = .true.
  end subroutine gen_set

  ! Nest l: grid and data set sid in slot n.
  subroutine gen_nest(l, sid, n)
    integer, intent(in) :: l, sid, n
    integer :: ix, jy
    real :: c_ps, c_t2, c_td, c_lsp, c_cvp
    real :: c_u(KZ), c_v(KZ), c_pv(KZ), c_t(KZ), c_q(KZ), c_cw(KZ), c_ci(KZ), c_w(KZ)
    real :: o(5+8*KZ)
    if (l == 1) then
      nxn(1) = 5; nyn(1) = 4; dxn(1) = 0.5; dyn(1) = 0.5; xlon0n(1) = 10.; ylat0n(1) = 40.
    else
      nxn(2) = 4; nyn(2) = 3; dxn(2) = 0.25; dyn(2) = 0.25; xlon0n(2) = 11.; ylat0n(2) = -30.
    end if
    xresoln(l) = r4(dble(dx)/dble(dxn(l)))
    yresoln(l) = r4(dble(dy)/dble(dyn(l)))
    do jy = 0, nyn(l)-1
      do ix = 0, nxn(l)-1
        call gen_column(sid, ix, jy, nxn(l), nyn(l), .false., c_ps, c_t2, c_td, c_lsp, c_cvp, &
             c_u, c_v, c_pv, c_t, c_q, c_cw, c_ci, c_w)
        psn(ix,jy,1,n,l) = c_ps; tt2n(ix,jy,1,n,l) = c_t2; td2n(ix,jy,1,n,l) = c_td
        lsprecn(ix,jy,1,n,l) = c_lsp; convprecn(ix,jy,1,n,l) = c_cvp
        uuhn(ix,jy,1:KZ,l) = c_u; vvhn(ix,jy,1:KZ,l) = c_v; pvhn(ix,jy,1:KZ,l) = c_pv
        tthn(ix,jy,1:KZ,n,l) = c_t; qvhn(ix,jy,1:KZ,n,l) = c_q
        clwchn(ix,jy,1:KZ,n,l) = c_cw; ciwchn(ix,jy,1:KZ,n,l) = c_ci
        wwhn(ix,jy,1:KZ,l) = c_w
        if (.not. set_echoed(sid)) then
          o(1:5) = (/ c_ps, c_t2, c_td, c_lsp, c_cvp /)
          o(6:5+KZ) = c_u; o(6+KZ:5+2*KZ) = c_v; o(6+2*KZ:5+3*KZ) = c_pv
          o(6+3*KZ:5+4*KZ) = c_t; o(6+4*KZ:5+5*KZ) = c_q; o(6+5*KZ:5+6*KZ) = c_cw
          o(6+6*KZ:5+7*KZ) = c_ci; o(6+7*KZ:5+8*KZ) = c_w
          call rowv('vt.in', (/ real(sid), real(ix), real(jy) /), 3, o, 5+8*KZ)
        end if
      end do
    end do
    if (.not. set_echoed(sid)) then
      call rowv('vt.nset', (/ real(sid), real(l) /), 2, &
           (/ real(nxn(l)), real(nyn(l)), dxn(l), dyn(l), xlon0n(l), ylat0n(l), &
              xresoln(l), yresoln(l) /), 8)
    end if
    set_echoed(sid) = .true.
  end subroutine gen_nest

  ! ------------------------------------------------------------------------
  subroutine call_row(proc, icall, routine, gid, sid, n, sid2, rc1, rc2, sc1, sc2)
    integer, intent(in) :: proc, icall, routine, gid, sid, n, sid2
    logical, intent(in) :: rc1, rc2, sc1, sc2
    call rowv('vt.call', (/ real(proc), real(icall), real(routine), real(gid), real(sid), real(n), &
         real(sid2), merge(1., 0., rc1), merge(1., 0., rc2), merge(1., 0., sc1), &
         merge(1., 0., sc2) /), 11, (/ 0. /), 0)
  end subroutine call_row

  subroutine emit_mother(proc, icall, n, pre)
    character(len=*), intent(in) :: pre
    integer, intent(in) :: proc, icall, n
    integer :: ix, jy
    real :: o(12*KZ), c(4*KZ+2)
    do jy = 0, nymin1
      do ix = 0, nxmin1
        o(1:KZ) = uu(ix,jy,1:KZ,n); o(KZ+1:2*KZ) = vv(ix,jy,1:KZ,n)
        o(2*KZ+1:3*KZ) = ww(ix,jy,1:KZ,n); o(3*KZ+1:4*KZ) = tt(ix,jy,1:KZ,n)
        o(4*KZ+1:5*KZ) = qv(ix,jy,1:KZ,n); o(5*KZ+1:6*KZ) = pv(ix,jy,1:KZ,n)
        o(6*KZ+1:7*KZ) = rho(ix,jy,1:KZ,n); o(7*KZ+1:8*KZ) = drhodz(ix,jy,1:KZ,n)
        o(8*KZ+1:9*KZ) = prs(ix,jy,1:KZ,n); o(9*KZ+1:10*KZ) = pplev(ix,jy,1:KZ,n)
        o(10*KZ+1:11*KZ) = uupol(ix,jy,1:KZ,n); o(11*KZ+1:12*KZ) = vvpol(ix,jy,1:KZ,n)
        call rowv(pre//'.out', (/ real(proc), real(icall), real(ix), real(jy) /), 4, o, 12*KZ)
        c(1:KZ) = clwc(ix,jy,1:KZ,n); c(KZ+1:2*KZ) = ciwc(ix,jy,1:KZ,n)
        c(2*KZ+1:3*KZ) = clw(ix,jy,1:KZ,n); c(3*KZ+1:4*KZ) = real(clouds(ix,jy,1:KZ,n))
        c(4*KZ+1) = real(cloudsh(ix,jy,n)); c(4*KZ+2) = ctwc(ix,jy,n)
        call rowv(pre//'.cloud', (/ real(proc), real(icall), real(ix), real(jy) /), 4, c, 4*KZ+2)
      end do
    end do
    call rowv(pre//'.zgrid', (/ real(proc), real(icall) /), 2, (/ height(1:KZ), real(nmixz) /), KZ+1)
  end subroutine emit_mother

  subroutine emit_nests(proc, icall, n)
    integer, intent(in) :: proc, icall, n
    integer :: ix, jy, l
    real :: o(8*KZ), c(4*KZ+2)
    do l = 1, numbnests
      do jy = 0, nyn(l)-1
        do ix = 0, nxn(l)-1
          o(1:KZ) = uun(ix,jy,1:KZ,n,l); o(KZ+1:2*KZ) = vvn(ix,jy,1:KZ,n,l)
          o(2*KZ+1:3*KZ) = wwn(ix,jy,1:KZ,n,l); o(3*KZ+1:4*KZ) = ttn(ix,jy,1:KZ,n,l)
          o(4*KZ+1:5*KZ) = qvn(ix,jy,1:KZ,n,l); o(5*KZ+1:6*KZ) = pvn(ix,jy,1:KZ,n,l)
          o(6*KZ+1:7*KZ) = rhon(ix,jy,1:KZ,n,l); o(7*KZ+1:8*KZ) = drhodzn(ix,jy,1:KZ,n,l)
          call rowv('nests.out', (/ real(proc), real(icall), real(l), real(ix), real(jy) /), 5, o, 8*KZ)
          c(1:KZ) = clwcn(ix,jy,1:KZ,n,l); c(KZ+1:2*KZ) = ciwcn(ix,jy,1:KZ,n,l)
          c(2*KZ+1:3*KZ) = clwn(ix,jy,1:KZ,n,l); c(3*KZ+1:4*KZ) = real(cloudsn(ix,jy,1:KZ,n,l))
          c(4*KZ+1) = real(cloudshn(ix,jy,n,l)); c(4*KZ+2) = ctwcn(ix,jy,n,l)
          call rowv('nests.cloud', (/ real(proc), real(icall), real(l), real(ix), real(jy) /), 5, c, 4*KZ+2)
        end do
      end do
    end do
  end subroutine emit_nests

  subroutine run_mother(proc, icall, routine, gid, sid, n, rc, sc)
    integer, intent(in) :: proc, icall, routine, gid, sid, n
    logical, intent(in) :: rc, sc
    call set_grid(gid)
    call gen_set(sid, n)
    readclouds = rc; sumclouds = sc
    call call_row(proc, icall, routine, gid, sid, n, 0, rc, .false., sc, .false.)
    if (routine == 1) then
      call verttransform_ecmwf(n, uuh, vvh, wwh, pvh)
    else
      call verttransform_gfs(n, uuh, vvh, wwh, pvh)
    end if
    if (routine == 1) then
      call emit_mother(proc, icall, n, 'ecmwf')
    else
      call emit_mother(proc, icall, n, 'gfs')
    end if
  end subroutine run_mother

  subroutine run_nests(proc, icall, gid, sid1, sid2, n, rc1, rc2, sc1, sc2)
    integer, intent(in) :: proc, icall, gid, sid1, sid2, n
    logical, intent(in) :: rc1, rc2, sc1, sc2
    call set_grid(gid)
    call gen_nest(1, sid1, n)
    call gen_nest(2, sid2, n)
    readclouds_nest(1) = rc1; readclouds_nest(2) = rc2
    sumclouds_nest(1) = sc1; sumclouds_nest(2) = sc2
    call call_row(proc, icall, 3, gid, sid1, n, sid2, rc1, rc2, sc1, sc2)
    call verttransform_nests(n, uuhn, vvhn, wwhn, pvhn)
    call emit_nests(proc, icall, n)
  end subroutine run_nests

  ! ------------------------------------------------------------------------
  ! Process 1: global grid (both poles). ECMWF x3 (old clouds; cloud water
  ! with ice separate; cloud water summed), GFS x3, nests x2.
  subroutine process1()
    call prefill()
    call rowv('vt.proc', (/ 1. /), 1, (/ -7., 7., 3., 99. /), 4)
    call run_mother(1, 1, 1, 1, 1, 1, .false., .false.)
    call run_mother(1, 2, 1, 1, 2, 2, .true., .false.)
    call run_mother(1, 3, 1, 1, 2, 1, .true., .true.)
    call run_mother(1, 4, 2, 2, 3, 1, .false., .false.)
    call run_mother(1, 5, 2, 2, 4, 2, .true., .false.)
    call run_mother(1, 6, 2, 2, 3, 2, .false., .false.)
    call run_nests(1, 7, 1, 11, 12, 1, .false., .true., .false., .false.)
    call run_nests(1, 8, 1, 13, 14, 2, .true., .true., .true., .false.)
  end subroutine process1

  ! Process 2: limited area (init with every level below hmixmax, nwz =
  ! nuvz-1), south-pole-only and north-pole-only grids, for both routines.
  subroutine process2()
    call prefill()
    call rowv('vt.proc', (/ 2. /), 1, (/ -7., 7., 3., 99. /), 4)
    call run_mother(2, 1, 1, 3, 5, 1, .false., .false.)
    call run_mother(2, 2, 1, 4, 6, 2, .false., .false.)
    call run_mother(2, 3, 1, 5, 7, 1, .true., .false.)
    call run_mother(2, 4, 2, 6, 8, 2, .false., .false.)
    call run_mother(2, 5, 2, 7, 9, 1, .false., .false.)
    call run_mother(2, 6, 2, 8, 10, 2, .true., .false.)
  end subroutine process2

  ! ------------------------------------------------------------------------
  ! shift_field_0 and shift_field on small fields, nxshift = 0, 1, 3, nxf-1,
  ! nxf (identity).
  subroutine emit_shift()
    real, allocatable :: f2(:,:), f4(:,:,:,:)
    integer, parameter :: NXF = 6, NYF = 3
    integer :: shifts(5) = (/ 0, 1, 3, 5, 6 /)
    integer :: is, ix, jy, kz, m
    real :: o(200)
    integer :: no
    allocate(f2(0:nxmax-1,0:nymax-1), f4(0:nxmax-1,0:nymax-1,3,2))
    do is = 1, 5
      nxshift = shifts(is)
      do jy = 0, NYF
        do ix = 0, NXF
          f2(ix,jy) = real(100*jy + ix)
        end do
      end do
      call shift_field_0(f2, NXF, NYF)
      no = 0
      do jy = 0, NYF
        do ix = 0, NXF
          no = no + 1; o(no) = f2(ix,jy)
        end do
      end do
      call rowv('shift_field_0', (/ real(nxshift), real(NXF), real(NYF) /), 3, o, no)

      do m = 1, 2
        do kz = 1, 3
          do jy = 0, NYF
            do ix = 0, NXF
              f4(ix,jy,kz,m) = real(1000*m + 100*kz + 10*jy + ix)
            end do
          end do
        end do
      end do
      call shift_field(f4, NXF, NYF, 3, 2, 2, 2)
      no = 0
      do m = 1, 2
        do kz = 1, 3
          do jy = 0, NYF
            do ix = 0, NXF
              no = no + 1; o(no) = f4(ix,jy,kz,m)
            end do
          end do
        end do
      end do
      call rowv('shift_field', (/ real(nxshift), real(NXF), real(NYF), 3., 2., 2., 2. /), 7, o, no)
    end do
  end subroutine emit_shift

end program flexpart_reference_vert
