! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART stochastic reference, stage 7: ensemble statistics of the particle
! step with FLEXPART's OWN random numbers.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) verbatim,
! INCLUDING random_mod.f90: here FLEXPART draws from its own generators
! exactly as in a real run. (random_mod is Numerical Recipes code; it is
! compiled from the upstream clone as a reference, never ported and never
! re-implemented, gh:#410.) `rannumb` is filled the way FLEXPART.f90 fills it
! at start-up (gasdev1 pairs, idummy = -320), and each advance/initialize call
! draws its starting index from ran3, as upstream.
!
! Everything else is the stage-4 set-up (dev/flexpart_reference_advance.f90):
! the same synthetic fields, echoed as `field` rows, on the shipped par_mod
! (no nests are used, so no configuration change is needed).
!
! For each scenario, NP particles are released at one point, initialised, and
! advanced NSTEP synchronisation intervals. The row records the ensemble
! moments of the final positions (double precision accumulation):
!   stoch,<scenario>;<NP>;<NSTEP>;<x0>;<y0>;<z0>;<tsw>;<cbf>;<oli>;<wst>;<replicate>,
!         <mean x,y,z>;<central m2 x,y,z>;<central m4 x,y,z>;<nstop count>;<nan_count>
! The Rust test (tests/flexpart_stochastic_advance.rs) runs the same scenarios
! with petir's LCG and RAFFLES' Box-Muller sampler as the random source and
! compares the moments within one standard error.
program flexpart_stochastic_advance
  use par_mod
  use com_mod
  use point_mod
  use interpol_mod
  use hanna_mod
  use random_mod, only: gasdev1
  implicit none

  integer, parameter :: NXP = 7, NYP = 7, NZP = 10
  integer, parameter :: NP = 20000, NSTEP = 8, NREP = 16
  integer :: idummy = -320, irep

  write(*,'(A)') '# FLEXPART stage-7 stochastic reference, generated by dev/flexpart_stochastic_advance.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference.sh'
  write(*,'(A)') 'function,args,outputs'

  call setup_fields()
  allocate(xmass(1, maxspec))
  xmass(1,1) = 1.0
  ! NREP independent FLEXPART runs: each refills rannumb from a different
  ! gasdev1 seed (FLEXPART.f90 uses idummy = -320; replicate r uses
  ! -320 - 1000*(r-1)), while ran3 continues its own stream. The spread of a
  ! statistic across replicates is FLEXPART's run-to-run uncertainty, which
  ! includes the effect of every particle sharing one finite rannumb array.
  do irep = 1, NREP
    idummy = -320 - 1000*(irep - 1)
    call fill_rannumb()
    ! scenario: id, turbswitch, cblflag, oli override, wstar override, x0, y0, z0
    call run(1, 1, 0, 0., 0., 2.625, 3.25, 50.)
    call run(2, 0, 0, 0., 0., 2.625, 3.25, 50.)
    call run(3, 1, 1, -0.02, 1.6, 2.625, 3.25, 100.)
    call run(4, 1, 0, 0., 0., 2.625, 3.25, 3000.)
    call run(5, 1, 0, 0., 0., 2.625, 3.25, 13000.)
  end do

contains

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowvd

  real function synth(id, i, j, k, m)
    integer, intent(in) :: id, i, j, k, m
    real :: x, y, z, t
    x = real(i); y = real(j); z = real(k); t = real(m - 1)
    select case (id)
    case (1)
      synth = 2.0 + 0.9*x - 0.35*y + 0.6*sin(0.7*x + 0.3*y + 0.2*z) + 0.5*t + 0.4*z
    case (2)
      synth = -1.5 + 0.25*x + 0.8*y + 0.5*cos(0.4*x - 0.9*y + 0.3*z) - 0.3*t + 0.2*z
    case (3)
      synth = 0.02*sin(0.5*x + 0.8*y - 0.6*z + t) - 0.003*z
    case (4)
      synth = -3.0 + 0.5*x + 0.7*y + 0.3*sin(x*y + z) + 0.2*t
    case (5)
      synth = 4.0 - 0.6*x + 0.2*y - 0.4*cos(x - y + z) - 0.1*t
    case (6)
      synth = 1.2*exp(-z*0.12) + 0.01*x - 0.005*y + 0.002*t
    case (7)
      synth = -1.1e-4*exp(-z*0.12) + 1.e-6*(x - y) + 1.e-6*t
    case (8)
      synth = 300. - 6.*z + 0.3*x - 0.2*y + 0.5*t
    case (11)
      synth = 0.2 + 0.05*x + 0.03*y + 0.04*t
    case (12)
      synth = 0.8 + 0.1*x - 0.05*y + 0.3*t
    case (13)
      synth = 0.002*(x - 3.)*(1. + 0.2*t)
    case (14)
      synth = 600. + 40.*x + 25.*y + 150.*t
    case (15)
      synth = 11000. + 100.*x - 50.*y + 200.*t
    case (16)
      synth = 2.e-3 + 3.e-4*x - 1.e-4*y + 5.e-4*t
    case default
      synth = 0.
    end select
  end function synth

  subroutine echo(grid, id, m, k)
    integer, intent(in) :: grid, id, m, k
    double precision :: vals(NXP*NYP)
    integer :: i, j, ish, jsh
    ish = 0; jsh = 0
    if (grid == 1) then
      ish = 2; jsh = 1
    end if
    do j = 0, NYP-1
      do i = 0, NXP-1
        vals(1 + i + NXP*j) = dble(synth(id, i+ish, j+jsh, k, m))
      end do
    end do
    call rowvd('field', (/ dble(grid), dble(id), dble(m), dble(k) /), 4, vals, NXP*NYP)
  end subroutine echo

  subroutine setup_fields()
    integer :: i, j, k, m, id
    double precision :: hd(NZP)
    nz = NZP
    height(1:NZP) = (/ 0., 25., 80., 180., 400., 900., 2000., 5000., 10000., 16000. /)
    hd = dble(height(1:NZP))
    call rowvd('height', hd, NZP, (/ 0.d0 /), 1)
    memtime(1) = 0; memtime(2) = 10800
    memind(1) = 1; memind(2) = 2
    numbnests = 0
    do m = 1, 2
      do k = 1, NZP
        do j = 0, NYP-1
          do i = 0, NXP-1
            uu(i,j,k,m) = synth(1, i, j, k, m)
            vv(i,j,k,m) = synth(2, i, j, k, m)
            ww(i,j,k,m) = synth(3, i, j, k, m)
            uupol(i,j,k,m) = synth(4, i, j, k, m)
            vvpol(i,j,k,m) = synth(5, i, j, k, m)
            rho(i,j,k,m) = synth(6, i, j, k, m)
            drhodz(i,j,k,m) = synth(7, i, j, k, m)
            tt(i,j,k,m) = synth(8, i, j, k, m)
          end do
        end do
        do id = 1, 8
          call echo(0, id, m, k)
        end do
      end do
      do j = 0, NYP-1
        do i = 0, NXP-1
          ustar(i,j,1,m) = synth(11, i, j, 1, m)
          wstar(i,j,1,m) = synth(12, i, j, 1, m)
          oli(i,j,1,m) = synth(13, i, j, 1, m)
          hmix(i,j,1,m) = synth(14, i, j, 1, m)
          tropopause(i,j,1,m) = synth(15, i, j, 1, m)
          vdep(i,j,1,m) = synth(16, i, j, 1, m)
        end do
      end do
      do id = 11, 16
        call echo(0, id, m, 1)
      end do
    end do
    nxmin1 = NXP - 1
    nymin1 = NYP - 1
  end subroutine setup_fields

  ! As FLEXPART.f90 does at start-up.
  subroutine fill_rannumb()
    integer :: i
    do i = 1, maxrand-1, 2
      call gasdev1(idummy, rannumb(i), rannumb(i+1))
    end do
    call gasdev1(idummy, rannumb(maxrand), rannumb(maxrand-1))
  end subroutine fill_rannumb

  subroutine run(isc, tsw, cbf, olic, wstc, x0, y0, z0)
    integer, intent(in) :: isc, tsw, cbf
    real, intent(in) :: olic, wstc, x0, y0, z0
    integer :: ip, n, itime, ldt, nstop, nstops, i, j, m
    integer(kind=2) :: icbt
    real :: up, vp, wp, us, vs, ws, zt, prob(maxspec)
    real(kind=dp) :: xt, yt
    double precision :: s1(3), s2(3), s3(3), s4(3), v(3), mean(3), m2(3), m4(3)
    ldirect = 1; lsynctime = 900; method = 1; ctl = 5.; ifine = 1
    fine = 1./real(ifine); mintime = 30
    turbswitch = (tsw == 1); cblflag = cbf
    DRYDEP = .false.; DRYDEPSPEC(1) = .false.
    lwindinterv = 10800; mdomainfill = 0; lsettling = .false.
    nspec = 1; density(1) = -1.
    do i = 1, nz
      if (height(i) > hmixmax) then
        nmixz = i
        exit
      end if
    end do
    xglobal = .false.; nglobal = .false.; sglobal = .false.
    switchnorthg = 999999.; switchsouthg = -999999.
    dx = 1.; dy = 1.; xlon0 = 10.; ylat0 = 1.
    dxconst = 180./(dx*r_earth*pi); dyconst = 180./(dy*r_earth*pi)
    do m = 1, 2
      do j = 0, NYP-1
        do i = 0, NXP-1
          if (olic /= 0.) then
            oli(i,j,1,m) = olic
          else
            oli(i,j,1,m) = synth(13, i, j, 1, m)
          end if
          if (wstc /= 0.) then
            wstar(i,j,1,m) = wstc
          else
            wstar(i,j,1,m) = synth(12, i, j, 1, m)
          end if
        end do
      end do
    end do
    s1 = 0.d0; s2 = 0.d0; s3 = 0.d0; s4 = 0.d0
    nstops = 0
    nan_count = 0
    do ip = 1, NP
      xt = dble(x0); yt = dble(y0); zt = z0
      itime = 0
      call initialize(itime, ldt, up, vp, wp, us, vs, ws, xt, yt, zt, icbt)
      prob = 0.
      do n = 1, NSTEP
        call advance(itime, 1, ldt, up, vp, wp, us, vs, ws, nstop, xt, yt, zt, prob, icbt)
        if (nstop /= 0) exit
        itime = itime + lsynctime
      end do
      if (nstop /= 0) then
        nstops = nstops + 1
        cycle
      end if
      ! power sums of the displacement from the release point (shifting
      ! keeps the double-precision accumulation well conditioned)
      v = (/ xt - dble(x0), yt - dble(y0), dble(zt) - dble(z0) /)
      s1 = s1 + v
      s2 = s2 + v*v
      s3 = s3 + v*v*v
      s4 = s4 + v*v*v*v
    end do
    n = NP - nstops
    mean = s1/dble(n)
    m2 = s2/dble(n) - mean*mean
    m4 = s4/dble(n) - 4.d0*mean*s3/dble(n) + 6.d0*mean*mean*s2/dble(n) - 3.d0*mean**4
    call rowvd('stoch', (/ dble(isc), dble(NP), dble(NSTEP), dble(x0), dble(y0), dble(z0), &
         dble(tsw), dble(cbf), dble(olic), dble(wstc), dble(irep) /), 11, &
         (/ mean, m2, m4, dble(nstops), dble(nan_count) /), 11)
  end subroutine run

end program flexpart_stochastic_advance
