! SPDX-License-Identifier: GPL-3.0
!
! Stage "outgrid" code-to-code reference driver for `changi::flexpart::
! {outgrid, fluxes, initial_condition}`: output-grid set-up (outgrid_init,
! outgrid_init_nest), gross mass fluxes (calcfluxes) and their output
! (fluxoutput), and the backward-run initial-condition sensitivity
! (initial_cond_calc).
!
! Every routine called here is UPSTREAM FLEXPART v10.4 @ 3d7eebf, compiled
! verbatim from upstream_source/FLEXPART/src by dev/build_reference_outgrid.sh.
! Nothing below reimplements physics: the driver writes synthetic grids,
! topography, densities and particles straight into com_mod / outg_mod /
! flux_mod / unc_mod (no GRIB, no NetCDF) and prints what upstream computes.
!
! par_mod.f90 is a CONFIGURATION copy (build script, diff-checked): exactly
! three parameter lines differ from upstream,
!   maxnests=2,nxmaxn=12,nymaxn=12   (two nests, to drive the nest selection
!                                     of the topography sampling)
!   maxspec=2                        (two species)
!   maxageclass=2                    (two age classes; fluxoutput's sparse
!                                     counters are dimensioned by it)
!
! fluxoutput WRITES A FILE. Its numbers are verified by READING THAT FILE
! BACK: after each call the driver opens path(2)//'grid_flux_<date><time>'
! (the name built from upstream's caldate, so the open also checks the name),
! reads every record in upstream's order and prints it. No arithmetic of
! fluxoutput is copied into the driver.
!
! outgrid_init and outgrid_init_nest print progress to stdout, so this driver
! writes its CSV to the file 'outgrid.csv' (unit 77) instead; the build script
! fails if upstream printed any 'ERROR'.
!
! Row format: function,a1;a2;...,o1;o2;...  real(4) builds print 9
! significant digits (parse as f32); rows carrying real(kind=dp) positions are
! printed with 17 digits (rowvd) and parsed as f64. Every synthetic value is a
! dyadic rational (or an f32-exact literal), so both builds receive identical
! inputs and the real(4)-vs-real(8) spread is upstream's arithmetic alone.
program flexpart_reference_outgrid

  use par_mod
  use com_mod
  use unc_mod
  use outg_mod
  use flux_mod
  implicit none

  integer, parameter :: ucsv = 77
  integer(8) :: lcg_state = 20261002_8   ! seed of the sweep generator

  open(ucsv, file='outgrid.csv', status='replace', action='write')
  write(ucsv,'(A)') '# FLEXPART stage "outgrid" reference, generated by dev/flexpart_reference_outgrid.f90'
  write(ucsv,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(ucsv,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_outgrid.sh'
  write(ucsv,'(A)') 'function,args,outputs'

  lroot = .true.
  mpi_mode = 0
  ipout = 0
  call com_mod_allocate_part(64)

  numzgrid = 4
  allocate(outheight(numzgrid), outheighthalf(numzgrid))

  call setup_orography()
  call emit_outgrid()
  call emit_calcfluxes()
  call emit_initial_cond()

  close(ucsv)

contains

  ! ------------------------------------------------------------------------
  ! Helpers copied from flexpart_reference_physics.f90 (writing to ucsv).
  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=8192) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(ucsv,'(A)') trim(line)
  end subroutine rowv

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=8192) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(ucsv,'(A)') trim(line)
  end subroutine rowvd

  ! Deterministic integer stream for the generated sweeps (not a physics
  ! input generator: the drawn values are echoed into the fixture).
  ! Lehmer / Park-Miller minimal standard (multiplier 48271, modulus
  ! 2^31-1), in integer(8) so the product cannot overflow.
  integer function draw(n)
    integer, intent(in) :: n
    lcg_state = mod(lcg_state * 48271_8, 2147483647_8)
    draw = int(mod(lcg_state, int(n, 8)))
  end function draw

  ! ------------------------------------------------------------------------
  ! Mother-grid placement, topography and two nests, read by the topography
  ! sampling of outgrid_init / outgrid_init_nest.
  subroutine setup_orography()
    integer :: ix, jy, n
    real :: epsv
    real :: o(1)
    xlon0 = -100.
    ylat0 = -90.
    dx = 0.5
    dy = 1.0
    do jy = 0, nymax-1
      do ix = 0, nxmax-1
        oro(ix,jy) = 8.*real(mod(29*ix + 43*jy, 89))
      end do
    end do
    numbnests = 2
    do n = 1, 2
      do jy = 0, nymaxn-1
        do ix = 0, nxmaxn-1
          oron(ix,jy,n) = 4.*real(mod(13*ix + 7*jy + 5*n, 61)) + 3.
        end do
      end do
    end do
    xln(1) = 30.; yln(1) = 40.; xrn(1) = 34.; yrn(1) = 44.
    xresoln(1) = 2.; yresoln(1) = 2.
    xln(2) = 32.; yln(2) = 41.; xrn(2) = 35.; yrn(2) = 43.
    xresoln(2) = 3.; yresoln(2) = 3.
    epsv = nxmax/3.e5          ! the same expression as upstream's parameter
    o(1) = 0.
    call rowv('setup.met', (/ xlon0, ylat0, dx, dy, epsv, real(nxmax), real(nymax), &
         real(nxmaxn), real(nymaxn), real(numbnests) /), 10, o, 1)
    do n = 1, 2
      call rowv('setup.nest', (/ real(n), xln(n), yln(n), xrn(n), yrn(n), &
           xresoln(n), yresoln(n) /), 7, o, 1)
    end do
    ! sample values so a formula mismatch on the Rust side is caught
    call rowv('setup.orocheck', (/ 0., 0., 0. /), 3, (/ oro(0,0) /), 1)
    call rowv('setup.orocheck', (/ 0., 360., 180. /), 3, (/ oro(360,180) /), 1)
    call rowv('setup.orocheck', (/ 0., 71., 43. /), 3, (/ oro(71,43) /), 1)
    call rowv('setup.orocheck', (/ 1., 11., 11. /), 3, (/ oron(11,11,1) /), 1)
    call rowv('setup.orocheck', (/ 2., 5., 3. /), 3, (/ oron(5,3,2) /), 1)
  end subroutine setup_orography

  ! ------------------------------------------------------------------------
  ! outgrid_init / outgrid_init_nest over eight grid placements (cfg 1-8) and
  ! the flux-test grid (cfg 9, called from emit_calcfluxes).
  !
  ! The sweep straddles: row boundaries exactly at 0 deg (the strict
  ! ylatm < 0 < ylatp test) and rows straddling the equator (cfg 2, 7); both
  ! hemispheres and the cosfactp < cosfactm switch; polar rows (cfg 1, 2, 8);
  ! near-equator rows where sqrt(1-cos^2) cancels (cfg 3); topography samples
  ! in the mother grid, nest 1, nest 2 and their overlap (nest 2 must win,
  ! cfg 4); samples within eps = nxmax/3e5 of a nest's lower-left (cfg 5) and
  ! upper-right (cfg 6) edges, which must fall back to the mother grid.
  subroutine emit_outgrid()
    call run_outgrid(1, -90., -90., 15., 15., 4, 12, .true.)
    call run_outgrid(2, -60.5, -88.75, 2.5, 2.5, 3, 71, .false.)
    call run_outgrid(3, -40., -1., 0.25, 0.25, 4, 8, .false.)
    call run_outgrid(4, -85.5, -50.5, 0.5, 0.5, 6, 10, .false.)
    call run_outgrid(5, -85.002825, -49.996625, 0.0625, 0.0625, 2, 2, .false.)
    call run_outgrid(6, -83.122125, -46.122375, 0.0625, 0.0625, 2, 2, .false.)
    call run_outgrid(7, -10., -0.75, 1., 0.5, 2, 4, .false.)
    call run_outgrid(8, -20., 80., 2., 2.5, 2, 4, .false.)
  end subroutine emit_outgrid

  subroutine set_outheights()
    outheight = (/ 100., 500., 1500., 10000. /)
    outheighthalf(1) = outheight(1)/2.
    outheighthalf(2:4) = (outheight(1:3) + outheight(2:4))/2.
  end subroutine set_outheights

  ! Release everything outgrid_init / outgrid_init_nest allocate, so the
  ! next configuration can call them again.
  subroutine free_outgrid()
    if (allocated(flux)) deallocate(flux)
    if (allocated(gridunc)) deallocate(gridunc)
    if (allocated(wetgridunc)) deallocate(wetgridunc)
    if (allocated(drygridunc)) deallocate(drygridunc)
    if (allocated(griduncn)) deallocate(griduncn)
    if (allocated(wetgriduncn)) deallocate(wetgriduncn)
    if (allocated(drygriduncn)) deallocate(drygriduncn)
    if (allocated(gridsigma)) deallocate(gridsigma)
    if (allocated(grid)) deallocate(grid)
    if (allocated(densityoutgrid)) deallocate(densityoutgrid)
    if (allocated(densitydrygrid)) deallocate(densitydrygrid)
    if (allocated(factor_drygrid)) deallocate(factor_drygrid)
    if (allocated(factor3d)) deallocate(factor3d)
    if (allocated(sparse_dump_r)) deallocate(sparse_dump_r)
    if (allocated(sparse_dump_u)) deallocate(sparse_dump_u)
    if (allocated(sparse_dump_i)) deallocate(sparse_dump_i)
    if (allocated(wetgridsigma)) deallocate(wetgridsigma)
    if (allocated(drygridsigma)) deallocate(drygridsigma)
    if (allocated(wetgrid)) deallocate(wetgrid)
    if (allocated(drygrid)) deallocate(drygrid)
    if (allocated(init_cond)) deallocate(init_cond)
    if (allocated(area)) deallocate(area)
    if (allocated(volume)) deallocate(volume)
    if (allocated(areaeast)) deallocate(areaeast)
    if (allocated(areanorth)) deallocate(areanorth)
    if (allocated(oroout)) deallocate(oroout)
    if (allocated(arean)) deallocate(arean)
    if (allocated(volumen)) deallocate(volumen)
    if (allocated(orooutn)) deallocate(orooutn)
  end subroutine free_outgrid

  ! keep_flux: leave the arrays allocated on return (cfg 9, the flux grid).
  subroutine run_outgrid(cfg, olon, olat, dxo, dyo, nxg, nyg, probe_flux6, keep)
    integer, intent(in) :: cfg, nxg, nyg
    real, intent(in) :: olon, olat, dxo, dyo
    logical, intent(in) :: probe_flux6
    logical, intent(in), optional :: keep
    real, allocatable :: dummy(:)
    real :: o(1)
    integer :: ix, jy, k, nsent, ntot, nfirst

    call free_outgrid()
    call set_outheights()
    outlon0 = olon; outlat0 = olat; dxout = dxo; dyout = dyo
    numxgrid = nxg; numygrid = nyg
    xoutshift = xlon0 - outlon0
    youtshift = ylat0 - outlat0
    outlon0n = olon; outlat0n = olat; dxoutn = dxo; dyoutn = dyo
    numxgridn = nxg; numygridn = nyg
    nspec = 2; maxpointspec_act = 2; nageclass = 2
    iflux = 1; ldirect = 1; linit_cond = 1; numreceptor = 0
    allocate(area(0:nxg-1,0:nyg-1), volume(0:nxg-1,0:nyg-1,numzgrid), &
         areaeast(0:nxg-1,0:nyg-1,numzgrid), areanorth(0:nxg-1,0:nyg-1,numzgrid), &
         oroout(0:nxg-1,0:nyg-1))
    allocate(arean(0:nxg-1,0:nyg-1), volumen(0:nxg-1,0:nyg-1,numzgrid), &
         orooutn(0:nxg-1,0:nyg-1))

    if (probe_flux6) then
      ! Diagnostic only (a comment line, not a test row): fill a block of
      ! the size outgrid_init's first allocation will request with a
      ! sentinel and free it, so the allocator is likely to hand it back as
      ! `flux`; then count which flux components outgrid_init zeroed.
      allocate(dummy(6*nxg*nyg*numzgrid*nspec*maxpointspec_act*nageclass))
      dummy = 7.
      deallocate(dummy)
    end if

    call outgrid_init
    call outgrid_init_nest

    if (probe_flux6) then
      nsent = count(flux(6,:,:,:,:,:,:) == 7.)
      nfirst = count(flux(1:5,:,:,:,:,:,:) /= 0.)
      ntot = size(flux(6,:,:,:,:,:,:))
      write(ucsv,'(A,I0,A,I0,A,I0,A)') '# diagnostic: after outgrid_init, ', nsent, ' of ', ntot, &
           ' flux(6,...) values still hold the allocator sentinel 7.0; ', nfirst, &
           ' nonzero values in flux(1:5,...)'
    end if

    o(1) = 0.
    call rowv('outgrid.config', (/ real(cfg), olon, olat, dxo, dyo, real(nxg), real(nyg), &
         real(numzgrid), outheight(1:numzgrid) /), 8 + numzgrid, o, 1)
    do jy = 0, nyg-1
      do k = 0, 1
        ix = k*(nxg-1)
        call rowv('outgrid_init.cell', (/ real(cfg), real(ix), real(jy) /), 3, &
             (/ area(ix,jy), volume(ix,jy,1:numzgrid), areaeast(ix,jy,1:numzgrid), &
                areanorth(ix,jy,1:numzgrid) /), 1 + 3*numzgrid)
        call rowv('outgrid_init_nest.cell', (/ real(cfg), real(ix), real(jy) /), 3, &
             (/ arean(ix,jy), volumen(ix,jy,1:numzgrid) /), 1 + numzgrid)
      end do
      do ix = 0, nxg-1
        call rowv('outgrid_init.oro', (/ real(cfg), real(ix), real(jy) /), 3, &
             (/ oroout(ix,jy) /), 1)
        call rowv('outgrid_init_nest.oro', (/ real(cfg), real(ix), real(jy) /), 3, &
             (/ orooutn(ix,jy) /), 1)
      end do
    end do
    if (.not. present(keep)) call free_outgrid()
  end subroutine run_outgrid

  ! ------------------------------------------------------------------------
  ! calcfluxes and fluxoutput.
  !
  ! The flux grid is cfg 9: 8 x 6 cells of 1.0 x 0.5 deg, 4 levels,
  ! xoutshift = -2, youtshift = -3, on a met grid with dx = 0.5, dy = 1.0 and
  ! nx = 20 (so a jump of >= 10 grid units takes the cyclic-boundary branch).
  ! Output position: xl = 0.5*x - 2, yl = 2*y - 6.
  !
  ! Every call is made on a ZEROED flux array and every non-zero cell printed
  ! (calcfluxes.cell); then the whole sequence is replayed without zeroing
  ! (accumulation) and the final non-zero cells printed (calcfluxes.total).
  ! fluxoutput is then called on that accumulated field (fluxoutput call 1)
  ! and on a synthetic field (call 2) chosen so that some (species, age class)
  ! blocks are dense, one only because the positive-cell count is summed over
  ! both release points, and some carry zeros and negative values.
  !
  ! The hand-picked steps cover: -1 < xl < 0 (int() truncation to column 0);
  ! xl = -1 exactly; the cyclic-boundary branch in both directions (upstream
  ! records nothing: its ixs uses real(nxmin1)-1.e5); a new height above the
  ! top level (horizontal skipped, vertical clamped); an old height above
  ! every mid-level; downward steps; exact half-cell ties of int(xl+0.5);
  ! crossings that start or end off the grid. The generated steps (dyadic
  ! positions) add volume, both switch settings and both age classes.
  subroutine emit_calcfluxes()
    integer, parameter :: nhand = 14, ngen = 160
    integer :: ncall, c, iofer(4), mdf(4)
    double precision :: st(11, nhand + ngen)
    double precision :: pa(13), po(1)
    real :: o(1)
    integer :: i, ix, jy, kz, k, kp, na, nnz

    iofer = (/ 0, 1, 1, 0 /)
    mdf = (/ 0, 0, 1, 1 /)
    ! cfg 9: outlon0 = xlon0 + 2 = -98, outlat0 = ylat0 + 3 = -87
    call run_outgrid(9, -98., -87., 1., 0.5, 8, 6, .false., keep=.true.)
    nx = 20
    nxmin1 = 19
    o(1) = 0.
    call rowv('setup.flux', (/ dx, dy, real(nx), real(nxmin1), xoutshift, youtshift, &
         dxout, dyout, real(numxgrid), real(numygrid), outheight(1:4), &
         outheighthalf(1:4) /), 18, o, 1)

    ! columns: xold, yold, zold, xnew, ynew, znew, xmass1, xmass2, nage, npoint, sw
    ! (sw = switch-combination index 1..4: ioutputforeachrelease, mdomainfill)
    st(:, 1) = (/ 3.d0, 4.25d0, 20.d0, 3.d0, 4.25d0, 2000.d0, 1.d0, 0.5d0, 1.d0, 1.d0, 1.d0 /)
    st(:, 2) = (/ 2.d0, 4.25d0, 20.d0, 2.d0, 4.25d0, 2000.d0, 1.d0, 0.5d0, 1.d0, 1.d0, 1.d0 /)
    st(:, 3) = (/ 19.d0, 4.25d0, 200.d0, 1.d0, 5.75d0, 200.d0, 2.d0, 0.25d0, 1.d0, 2.d0, 2.d0 /)
    st(:, 4) = (/ 1.d0, 5.75d0, 200.d0, 19.d0, 4.25d0, 200.d0, 2.d0, 0.25d0, 2.d0, 2.d0, 2.d0 /)
    st(:, 5) = (/ 6.d0, 4.d0, 200.d0, 10.d0, 5.d0, 12000.d0, 1.5d0, 3.d0, 1.d0, 1.d0, 1.d0 /)
    st(:, 6) = (/ 6.d0, 4.d0, 6000.d0, 10.d0, 5.d0, 12000.d0, 1.5d0, 3.d0, 2.d0, 2.d0, 2.d0 /)
    st(:, 7) = (/ 12.d0, 6.d0, 9000.d0, 8.d0, 3.5d0, 40.d0, 0.75d0, 1.25d0, 2.d0, 1.d0, 2.d0 /)
    st(:, 8) = (/ 5.d0, 3.25d0, 300.d0, 7.d0, 3.75d0, 300.d0, 1.d0, 1.d0, 1.d0, 2.d0, 2.d0 /)
    st(:, 9) = (/ -1.d0, 3.25d0, 120.d0, 6.d0, 4.5d0, 120.d0, 0.5d0, 2.d0, 1.d0, 1.d0, 1.d0 /)
    st(:,10) = (/ 22.d0, 4.5d0, 120.d0, 15.d0, 3.25d0, 120.d0, 0.5d0, 2.d0, 2.d0, 2.d0, 3.d0 /)
    st(:,11) = (/ 8.d0, 1.5d0, 450.d0, 9.d0, 6.5d0, 450.d0, 1.d0, 0.125d0, 1.d0, 1.d0, 4.d0 /)
    st(:,12) = (/ 9.d0, 6.5d0, 450.d0, 8.d0, 1.5d0, 1500.d0, 1.d0, 0.125d0, 1.d0, 2.d0, 2.d0 /)
    st(:,13) = (/ 3.5d0, 2.75d0, 50.d0, 4.5d0, 3.25d0, 49.d0, 4.d0, 4.d0, 2.d0, 2.d0, 1.d0 /)
    st(:,14) = (/ 20.d0, 7.d0, 6000.d0, 24.d0, 7.25d0, 5750.d0, 0.25d0, 8.d0, 1.d0, 1.d0, 2.d0 /)
    do c = nhand + 1, nhand + ngen
      st(1, c) = -4.d0 + dble(draw(449))/16.d0
      st(2, c) = 1.5d0 + dble(draw(89))/16.d0
      st(3, c) = 64.d0*dble(draw(193))
      if (draw(10) == 0) then
        st(4, c) = st(1, c) + sign(12.d0, 10.d0 - st(1, c))
      else
        st(4, c) = st(1, c) + dble(draw(161) - 80)/16.d0
      end if
      st(5, c) = st(2, c) + dble(draw(81) - 40)/16.d0
      st(6, c) = 64.d0*dble(draw(193))
      st(7, c) = 0.25d0*dble(1 + draw(15))
      st(8, c) = 0.125d0*dble(1 + draw(9))
      st(9, c) = dble(1 + draw(2))
      st(10, c) = dble(1 + draw(2))
      st(11, c) = dble(1 + draw(4))
    end do
    ncall = nhand + ngen

    ! single calls on a zeroed field
    do c = 1, ncall
      flux = 0.
      call one_flux_step(st(:, c), iofer, mdf)
      nnz = count(flux /= 0.)
      pa = (/ dble(c), dble(iofer(nint(st(11,c)))), dble(mdf(nint(st(11,c)))), st(9,c), &
           st(10,c), st(1:6,c), st(7,c), st(8,c) /)
      po(1) = dble(nnz)
      call rowvd('calcfluxes.call', pa, 13, po, 1)
      call print_flux('calcfluxes.cell', c)
    end do

    ! the whole sequence, accumulated
    flux = 0.
    do c = 1, ncall
      call one_flux_step(st(:, c), iofer, mdf)
    end do
    call print_flux('calcfluxes.total', 0)

    ! fluxoutput, call 1: the accumulated field
    bdate = 2459000.5d0
    pa(1) = bdate
    po(1) = 0.d0
    call rowvd('setup.bdate', pa(1:1), 1, po, 1)
    loutstep = 3600
    outstep = real(abs(loutstep))
    path(2) = './'
    length(2) = 2
    call emit_fluxoutput(1, 7200)

    ! fluxoutput, call 2: a synthetic field
    flux = 0.
    do na = 1, nageclass
      do kp = 1, maxpointspec_act
        do k = 1, nspec
          do kz = 1, numzgrid
            do jy = 0, numygrid-1
              do ix = 0, numxgrid-1
                do i = 1, 6
                  call synth_flux(i, ix, jy, kz, k, kp, na)
                end do
              end do
            end do
          end do
        end do
      end do
    end do
    ! The Rust test rebuilds this field from synth_flux's formula; these
    ! samples (one per (species, age class) branch, plus a negative value)
    ! catch a formula mismatch.
    call fluxcheck(3, 2, 1, 2, 1, 2, 1)
    call fluxcheck(1, 0, 0, 1, 2, 1, 1)
    call fluxcheck(5, 7, 5, 4, 1, 1, 2)
    call fluxcheck(2, 1, 3, 1, 2, 2, 2)
    call fluxcheck(1, 0, 0, 1, 2, 1, 2)
    o(1) = real(count(flux /= 0.))
    call rowv('setup.fluxcount', (/ 2. /), 1, o, 1)
    call emit_fluxoutput(2, 2*86400 + 3661)
    call free_outgrid()
  end subroutine emit_calcfluxes

  ! The synthetic flux field of fluxoutput call 2 (rebuilt by the Rust test).
  ! (k=1, nage=1): all cells positive -> dense; (k=2, nage=1): 30 positive
  ! cells in each release point -> 60 >= 48 summed -> dense although each
  ! release point alone would be sparse; (k=1, nage=2): 44 cells in release
  ! point 1 only -> sparse, but only just (4*44 = 176 < 192 <= 5*44);
  ! (k=2, nage=2): about half the cells, some
  ! negative (sparse lists skip them, dense dumps keep them) -> dense.
  subroutine synth_flux(i, ix, jy, kz, k, kp, na)
    integer, intent(in) :: i, ix, jy, kz, k, kp, na
    integer :: lin
    lin = ix + numxgrid*(jy + numygrid*(kz-1))      ! 0 .. 191
    if (k == 1 .and. na == 1) then
      flux(i,ix,jy,kz,k,kp,na) = 0.25*real(1 + mod(lin*7 + i + kp, 13))
    else if (k == 2 .and. na == 1) then
      if (mod(lin*5 + i, 192) < 30) flux(i,ix,jy,kz,k,kp,na) = 0.5*real(1 + mod(lin + i, 5))
    else if (k == 1 .and. na == 2) then
      if (kp == 1 .and. mod(lin*11 + i, 192) < 44) flux(i,ix,jy,kz,k,kp,na) = 2.*real(1 + mod(lin, 3))
    else
      if (mod(lin + i, 2) == 0) flux(i,ix,jy,kz,k,kp,na) = 0.125*real(mod(lin*3 + i, 9) - 2)
    end if
  end subroutine synth_flux

  subroutine fluxcheck(i, ix, jy, kz, k, kp, na)
    integer, intent(in) :: i, ix, jy, kz, k, kp, na
    call rowv('setup.fluxcheck', (/ real(i), real(ix), real(jy), real(kz), real(k), &
         real(kp), real(na) /), 7, (/ flux(i,ix,jy,kz,k,kp,na) /), 1)
  end subroutine fluxcheck

  subroutine one_flux_step(s, iofer, mdf)
    double precision, intent(in) :: s(11)
    integer, intent(in) :: iofer(4), mdf(4)
    integer :: sw
    real :: xold, yold, zold
    sw = nint(s(11))
    ioutputforeachrelease = iofer(sw)
    mdomainfill = mdf(sw)
    xold = real(s(1)); yold = real(s(2)); zold = real(s(3))
    xtra1(1) = s(4); ytra1(1) = s(5); ztra1(1) = real(s(6))
    xmass1(1,1) = real(s(7)); xmass1(1,2) = real(s(8))
    npoint(1) = nint(s(10))
    call calcfluxes(nint(s(9)), 1, xold, yold, zold)
  end subroutine one_flux_step

  subroutine print_flux(name, id)
    character(len=*), intent(in) :: name
    integer, intent(in) :: id
    integer :: i, ix, jy, kz, k, kp, na
    do na = 1, nageclass
      do kp = 1, maxpointspec_act
        do k = 1, nspec
          do kz = 1, numzgrid
            do jy = 0, numygrid-1
              do ix = 0, numxgrid-1
                do i = 1, 6
                  if (flux(i,ix,jy,kz,k,kp,na) /= 0.) then
                    call rowv(name, (/ real(id), real(i), real(ix), real(jy), real(kz), &
                         real(k), real(kp), real(na) /), 8, (/ flux(i,ix,jy,kz,k,kp,na) /), 1)
                  end if
                end do
              end do
            end do
          end do
        end do
      end do
    end do
  end subroutine print_flux

  ! Call upstream's fluxoutput, then read back the file it wrote.
  subroutine emit_fluxoutput(id, it)
    integer, intent(in) :: id, it
    real(kind=dp) :: jul
    integer :: jjjjmmdd, ihmmss, itr, iflag, idx, k, kp, na, d, kz, ix, jy, n, ios
    real :: val, vals(0:numygrid-1), o(1)
    character :: adate*8, atime*6
    character(len=200) :: fname

    call fluxoutput(it)

    jul = bdate + real(it, kind=dp)/86400._dp
    call caldate(jul, jjjjmmdd, ihmmss)
    write(adate,'(i8.8)') jjjjmmdd
    write(atime,'(i6.6)') ihmmss
    fname = path(2)(1:length(2))//'grid_flux_'//adate//atime
    open(91, file=trim(fname), form='unformatted', status='old', iostat=ios)
    if (ios /= 0) then
      write(*,*) 'ERROR: fluxoutput file not found: ', trim(fname)
      stop 1
    end if
    call rowv('fluxoutput.file', (/ real(id), real(it) /), 2, &
         (/ real(jjjjmmdd/10000), real(mod(jjjjmmdd,10000)), real(ihmmss) /), 3)
    read(91) itr
    o(1) = real(itr)
    call rowv('fluxoutput.itime', (/ real(id) /), 1, o, 1)
    do k = 1, nspec
      do kp = 1, maxpointspec_act
        do na = 1, nageclass
          do d = 1, 6
            read(91) iflag
            n = 0
            if (iflag == 1) then
              do
                read(91) idx, val
                if (idx == -999) exit
                n = n + 1
                call rowv('fluxoutput.sparse', (/ real(id), real(k), real(kp), real(na), &
                     real(d), real(idx) /), 6, (/ val /), 1)
              end do
            else
              do kz = 1, numzgrid
                do ix = 0, numxgrid-1
                  read(91) (vals(jy), jy=0,numygrid-1)
                  n = n + numygrid
                  call rowv('fluxoutput.dense', (/ real(id), real(k), real(kp), real(na), &
                       real(d), real(kz), real(ix) /), 7, vals, numygrid)
                end do
              end do
            end if
            call rowv('fluxoutput.block', (/ real(id), real(k), real(kp), real(na), real(d) /), &
                 5, (/ real(iflag), real(n) /), 2)
          end do
        end do
      end do
    end do
    read(91, iostat=ios) itr
    if (ios == 0) then
      write(*,*) 'ERROR: fluxoutput file has more records than expected'
      stop 1
    end if
    close(91, status='delete')
    o(1) = real(count(flux /= 0.))
    call rowv('fluxoutput.reset', (/ real(id) /), 1, o, 1)
  end subroutine emit_fluxoutput

  ! ------------------------------------------------------------------------
  ! initial_cond_calc.
  !
  ! Output grid: 7 x 5 cells of 1.0 x 0.5 deg, levels 100/500/1500/6000 m,
  ! xoutshift = -2, youtshift = -1, on a met grid with dx = 0.5, dy = 1.0:
  ! xl = 0.5*x - 2, yl = 2*y - 2. Density: the output stage's dyadic rho
  ! formula on 8 model levels up to 8000 m (setup.icmet echoes the heights;
  ! setup.rhocheck sample values).
  !
  ! Each particle is gridded on a zeroed init_cond (initial_cond_calc.cell,
  ! every non-zero cell), then the whole sequence is replayed without zeroing
  ! (initial_cond_calc.total). The sweep straddles: itra1 /= itime (no-op);
  ! linit_cond 1 (density) and 2 (rhoi = 1); memind(2) = 2 and 1; the
  ! ioutputforeachrelease / mdomainfill combinations; the half-cell edge
  ! strips on all four sides; -1 < xl < 0 and xl = -1 exactly (the int()-1
  ! floor correction); ddx, ddy exactly at 0.5 and at 0.5 -+ 1/64; kernel
  ! corners falling off the grid; heights in every level and between the top
  ! output level (6000 m) and the top model level (8000 m), which the density
  ! branch accepts but the output grid does not.
  subroutine emit_initial_cond()
    integer, parameter :: nhand = 14, ngen = 120
    double precision :: pt(12, nhand + ngen), pa(14), po(1)
    integer :: ix, jy, k, m, c, ncall, nnz, itime
    real :: o(1)
    integer :: iofer(4), mdf(4)

    iofer = (/ 0, 1, 1, 0 /)
    mdf = (/ 0, 0, 1, 1 /)
    nz = 8
    height(1:8) = (/ 0., 50., 150., 400., 900., 1800., 3500., 8000. /)
    do m = 1, 2
      do k = 1, nz
        do jy = 0, nymax-1
          do ix = 0, nxmax-1
            rho(ix,jy,k,m) = 1.25 - 0.0625*real(k) + real(mod(37*ix + 101*jy + 53*k + 17*m, 97))/256.
          end do
        end do
      end do
    end do
    o(1) = 0.
    call rowv('setup.icmet', (/ real(nz), height(1:8) /), 9, o, 1)
    call rowv('setup.rhocheck', (/ 0., 0., 1., 1. /), 4, (/ rho(0,0,1,1) /), 1)
    call rowv('setup.rhocheck', (/ 17., 3., 4., 2. /), 4, (/ rho(17,3,4,2) /), 1)
    call rowv('setup.rhocheck', (/ 360., 180., 8., 1. /), 4, (/ rho(360,180,8,1) /), 1)

    dx = 0.5; dy = 1.0
    numxgrid = 7; numygrid = 5; numzgrid = 4
    dxout = 1.0; dyout = 0.5; xoutshift = -2.; youtshift = -1.
    outheight = (/ 100., 500., 1500., 6000. /)
    nspec = 2; maxpointspec_act = 2
    allocate(init_cond(0:numxgrid-1,0:numygrid-1,numzgrid,maxspec,maxpointspec_act))
    call rowv('setup.ic', (/ dx, dy, real(numxgrid), real(numygrid), dxout, dyout, &
         xoutshift, youtshift, outheight(1:4) /), 12, o, 1)

    itime = 43200
    ! columns: x, y, z, xmass1, xmass2, linit_cond, memind(2), sw, npoint, itra1-itime
    !          (0 = at itime), (unused), (unused)
    pt(:, 1) = (/ 9.d0, 2.25d0, 75.d0, 1.d0, 2.d0, 1.d0, 2.d0, 1.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)    ! ddx=0.5 tie
    pt(:, 2) = (/ 9.5d0, 2.375d0, 75.d0, 1.d0, 2.d0, 1.d0, 1.d0, 2.d0, 2.d0, 0.d0, 0.d0, 0.d0 /)
    pt(:, 3) = (/ 4.5d0, 1.125d0, 300.d0, 1.d0, 0.5d0, 2.d0, 2.d0, 2.d0, 2.d0, 0.d0, 0.d0, 0.d0 /) ! xl<0.5
    pt(:, 4) = (/ 15.5d0, 3.125d0, 300.d0, 0.75d0, 0.5d0, 1.d0, 2.d0, 3.d0, 2.d0, 0.d0, 0.d0, 0.d0 /) ! east strip
    pt(:, 5) = (/ 3.d0, 2.d0, 1000.d0, 1.d0, 1.d0, 1.d0, 2.d0, 1.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)   ! xl=-0.5
    pt(:, 6) = (/ 2.d0, 2.d0, 1000.d0, 1.d0, 1.d0, 2.d0, 1.d0, 1.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)   ! xl=-1
    pt(:, 7) = (/ 5.d0, 1.25d0, 20.d0, 2.d0, 1.d0, 1.d0, 2.d0, 4.d0, 2.d0, 0.d0, 0.d0, 0.d0 /)   ! xl=yl=0.5: kernel, corners -1
    pt(:, 8) = (/ 9.d0, 3.375d0, 20.d0, 2.d0, 1.d0, 2.d0, 2.d0, 2.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)   ! north strip
    pt(:, 9) = (/ 11.25d0, 2.125d0, 7000.d0, 1.d0, 1.d0, 1.d0, 1.d0, 2.d0, 2.d0, 0.d0, 0.d0, 0.d0 /) ! above outgrid
    pt(:,10) = (/ 11.25d0, 2.125d0, 450.d0, 1.d0, 1.d0, 1.d0, 2.d0, 2.d0, 2.d0, 900.d0, 0.d0, 0.d0 /) ! not at itime
    pt(:,11) = (/ 6.25d0, 1.875d0, 1600.d0, 3.d0, 0.25d0, 1.d0, 2.d0, 2.d0, 2.d0, 0.d0, 0.d0, 0.d0 /)
    pt(:,12) = (/ 12.75d0, 2.625d0, 5999.d0, 0.5d0, 4.d0, 1.d0, 1.d0, 3.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)
    ! just either side of the kernel switch: ddx = 31/64, ddy = 33/64 and the reverse
    pt(:,13) = (/ 8.96875d0, 1.7578125d0, 700.d0, 1.d0, 2.d0, 1.d0, 2.d0, 1.d0, 1.d0, 0.d0, 0.d0, 0.d0 /)
    pt(:,14) = (/ 10.03125d0, 2.2421875d0, 200.d0, 2.d0, 1.d0, 2.d0, 1.d0, 2.d0, 2.d0, 0.d0, 0.d0, 0.d0 /)
    do c = nhand + 1, nhand + ngen
      pt(1, c) = 1.5d0 + dble(draw(481))/32.d0      ! xl in -1.25 .. 6.25
      pt(2, c) = 0.375d0 + dble(draw(113))/32.d0    ! yl in -1.25 .. 5.75
      pt(3, c) = 32.d0*dble(draw(240))              ! 0 .. 7648 m (< 8000)
      pt(4, c) = 0.125d0*dble(1 + draw(31))
      pt(5, c) = 0.25d0*dble(1 + draw(11))
      pt(6, c) = dble(1 + draw(2))
      pt(7, c) = dble(1 + draw(2))
      pt(8, c) = dble(1 + draw(4))
      pt(9, c) = dble(1 + draw(2))
      pt(10, c) = 0.d0
      if (draw(17) == 0) pt(10, c) = -600.d0
      pt(11:12, c) = 0.d0
    end do
    ncall = nhand + ngen

    do c = 1, ncall
      init_cond = 0.
      call one_ic(pt(:, c), itime, iofer, mdf)
      nnz = count(init_cond /= 0.)
      pa = (/ dble(c), dble(itime), dble(itime) + pt(10,c), pt(6,c), pt(7,c), &
           dble(iofer(nint(pt(8,c)))), dble(mdf(nint(pt(8,c)))), pt(1,c), pt(2,c), pt(3,c), &
           pt(9,c), pt(4,c), pt(5,c), 0.d0 /)
      po(1) = dble(nnz)
      call rowvd('initial_cond_calc.call', pa, 14, po, 1)
      call print_ic('initial_cond_calc.cell', c)
    end do
    init_cond = 0.
    do c = 1, ncall
      call one_ic(pt(:, c), itime, iofer, mdf)
    end do
    call print_ic('initial_cond_calc.total', 0)
    deallocate(init_cond)
  end subroutine emit_initial_cond

  subroutine one_ic(p, itime, iofer, mdf)
    double precision, intent(in) :: p(12)
    integer, intent(in) :: itime, iofer(4), mdf(4)
    integer :: sw
    sw = nint(p(8))
    ioutputforeachrelease = iofer(sw)
    mdomainfill = mdf(sw)
    linit_cond = nint(p(6))
    memind(1) = 3 - nint(p(7))
    memind(2) = nint(p(7))
    xtra1(1) = p(1); ytra1(1) = p(2); ztra1(1) = real(p(3))
    xmass1(1,1) = real(p(4)); xmass1(1,2) = real(p(5))
    npoint(1) = nint(p(9))
    itra1(1) = itime + nint(p(10))
    call initial_cond_calc(itime, 1)
  end subroutine one_ic

  subroutine print_ic(name, id)
    character(len=*), intent(in) :: name
    integer, intent(in) :: id
    integer :: ix, jy, kz, ks, kp
    do kp = 1, maxpointspec_act
      do ks = 1, nspec
        do kz = 1, numzgrid
          do jy = 0, numygrid-1
            do ix = 0, numxgrid-1
              if (init_cond(ix,jy,kz,ks,kp) /= 0.) then
                call rowv(name, (/ real(id), real(ix), real(jy), real(kz), real(ks), real(kp) /), &
                     6, (/ init_cond(ix,jy,kz,ks,kp) /), 1)
              end if
            end do
          end do
        end do
      end do
    end do
  end subroutine print_ic

end program flexpart_reference_outgrid
