! SPDX-License-Identifier: GPL-3.0
!
! Code-to-code reference driver for `changi::flexpart::convection` and
! `changi::flexpart::convmix`: Emanuel's convection scheme (convect43c.f90,
! CONVECT + TLIFT), the redistribution matrix (calcmatrix.f90), particle
! redistribution (redist.f90), the per-column driver (convmix.f90), and the
! permutation of Numerical Recipes' sort2.f90 (called, not ported).
!
! Every routine called here is UPSTREAM FLEXPART v10.4 @ 3d7eebf, compiled
! verbatim from upstream_source/FLEXPART/src by
! dev/build_reference_convection.sh. Nothing below reimplements physics: the
! driver writes SYNTHETIC soundings and fields straight into conv_mod/com_mod
! (no GRIB/NetCDF), calls upstream, and prints what upstream returns.
!
! Two substitutions, both outside the routines under test:
!   * par_mod.f90 is compiled from a COPY with `maxnests=1,nxmaxn=12,
!     nymaxn=12` (shipped: zeros), so convmix's nested-grid branch can run.
!     par_mod is FLEXPART's user-edited configuration file.
!   * random_mod is dev/random_mod_shim_convection.f90: `ran3` returns the next value of
!     a queue this driver fills (NR ran3 is not ported; the Rust port takes the
!     draws as input).
!
! Row format, one row per CALL (or setup echo):
!     function,a1;a2;...;an,o1;o2;...;om
! Values are promoted with dble() before printing, so the real(4) build writes
! the exact f32 value. `convmix.particle` rows are double precision at both
! precisions (xtra1/ytra1 are real(kind=dp) upstream).
program flexpart_reference_convection

  use par_mod
  use com_mod
  use conv_mod
  use random_mod
  use class_gribfile
  implicit none

  ! Half-level pressures (hPa) of the synthetic columns, surface first.
  real, parameter :: phlist(18) = (/ 1000., 985., 965., 935., 895., 845., &
       780., 705., 620., 530., 440., 355., 280., 215., 160., 115., 85., 60. /)
  ! The grid run_convect uses: phlist, or (alt_grid) phlist with its 4th
  ! half level moved to 919.6 hPa, which puts a full level at 0.9494 p(1),
  ! between upstream's 0.949 p(1) downdraft-ramp threshold and 0.95 p(1).
  logical :: alt_grid = .false.
  ! Levels of the calcmatrix / redist / convmix columns.
  integer, parameter :: nuvz_c = 17, nconvlev_c = 15

  write(*,'(A)') '# FLEXPART convection reference, generated by dev/flexpart_reference_convection.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_convection.sh'
  write(*,'(A)') 'function,args,outputs'

  call set_hybrid()
  call emit_sort2()
  call emit_convect()
  call emit_calcmatrix()
  call emit_redist()
  call emit_convmix()

contains

  ! ------------------------------------------------------------------------
  ! Copied from dev/flexpart_reference_physics.f90.
  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowv

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowvd

  ! ------------------------------------------------------------------------
  ! Every synthetic INPUT is rounded through real(4): identity in the shipped
  ! build, and in the real(8) build it makes the inputs bit-identical to the
  ! real(4) build's. The two fixtures then differ only by upstream's own
  ! arithmetic precision, which is what the real(4) attribution needs.
  real function r4(x)
    real, intent(in) :: x
    r4 = real(real(x, kind=4))
  end function r4

  ! ------------------------------------------------------------------------
  ! A synthetic sounding at pressures p(1..np) (hPa): temperature
  ! ts*(p/1000)^(Rd*gam/g) floored at 205 K, plus dtinv from level kinv up
  ! (an inversion), plus dt1 at level 1; RH rhlo below 700 hPa and rhhi above,
  ! rh1 at level 1 if >= 0; qs from Bolton's (1980) es over water,
  ! qs = 0.622 es/(p - 0.378 es); q = RH*qs.
  !
  ! The generator works in DOUBLE PRECISION from parameters first rounded to
  ! real(4), and rounds each result once to real(4): both builds therefore
  ! produce the identical inputs. (qs is a synthetic input here; calcmatrix
  ! computes its own qsconv with upstream f_qvsat.)
  subroutine make_column(np, p, ts, gam, rhlo, rhhi, kinv, dtinv, dt1, rh1, t, q, qs)
    integer, intent(in) :: np, kinv
    real, intent(in) :: p(np), ts, gam, rhlo, rhhi, dtinv, dt1, rh1
    real, intent(out) :: t(np), q(np), qs(np)
    integer :: k
    double precision :: td, rh, pd, es, qsd
    do k = 1, np
      pd = dble(r4(p(k)))
      td = dble(r4(ts))*(pd/1000d0)**(287d0*dble(r4(gam))/9.81d0)
      td = max(td, 205d0)
      if (kinv > 0 .and. k >= kinv) td = td + dble(r4(dtinv))
      if (k == 1) td = td + dble(r4(dt1))
      t(k) = r4(real(td))
      td = dble(t(k))
      rh = dble(r4(rhlo))
      if (pd < 700d0) rh = dble(r4(rhhi))
      if (k == 1 .and. rh1 >= 0.) rh = dble(r4(rh1))
      es = 6.112d0*exp(17.67d0*(td - 273.15d0)/(td - 29.65d0))
      qsd = 0.622d0*es/(pd - 0.378d0*es)
      qs(k) = r4(real(qsd))
      q(k) = r4(real(rh*dble(qs(k))))
    end do
  end subroutine make_column

  ! Exact-in-both-builds helpers: double-precision arithmetic on real(4)
  ! values, rounded once to real(4).
  real function lin(a, b, c, d)
    real, intent(in) :: a, b, c, d
    ! (a + b*c)/d
    lin = r4(real((dble(a) + dble(b)*dble(c))/dble(d)))
  end function lin

  real function add(a, b)
    real, intent(in) :: a, b
    add = r4(real(dble(a) + dble(b)))
  end function add

  ! ------------------------------------------------------------------------
  ! Hybrid coefficients for the ECMWF columns (com_mod akz/bkz/akm/bkm):
  ! half level k at sigma s = phlist(k)/1000 with b = s**2, a = (s - b)*101325;
  ! full level k (k >= 2) halfway between half levels k-1 and k; level 1 is the
  ! surface (a = 0, b = 1). Echoed as the `hybrid` setup row.
  subroutine set_hybrid()
    integer :: k
    real :: s, o(4*nuvz_c), a(1)
    do k = 1, nuvz_c
      s = r4(real(dble(phlist(k))/1000d0))
      bkm(k) = r4(real(dble(s)*dble(s)))
      akm(k) = r4(real((dble(s) - dble(bkm(k)))*101325d0))
    end do
    akz(1) = 0.
    bkz(1) = 1.
    do k = 2, nuvz_c
      akz(k) = r4(real(0.5d0*(dble(akm(k-1)) + dble(akm(k)))))
      bkz(k) = r4(real(0.5d0*(dble(bkm(k-1)) + dble(bkm(k)))))
    end do
    do k = 1, nuvz_c
      o(k) = akz(k)
      o(nuvz_c + k) = bkz(k)
      o(2*nuvz_c + k) = akm(k)
      o(3*nuvz_c + k) = bkm(k)
    end do
    a(1) = real(nuvz_c)
    call rowv('hybrid', a, 1, o, 4*nuvz_c)
  end subroutine set_hybrid

  ! ------------------------------------------------------------------------
  ! sort2 (Numerical Recipes, NOT ported): the permutation it produces, so the
  ! Rust test can measure where the port's stable sort agrees with it.
  ! args: n, keys(1..n); outputs: sorted keys, ipoint(1..n)
  subroutine emit_sort2()
    integer, parameter :: ncase = 10
    integer :: ns(ncase), modk(ncase), ic, i, n
    integer :: keys(200), ip(200)
    real :: a(201), o(400)
    ns   = (/ 1, 2, 6, 7, 8, 9, 15, 40, 100, 100 /)
    modk = (/ 3, 3, 3, 4, 5, 3, 1000, 7, 13, 100000 /)
    do ic = 1, ncase
      n = ns(ic)
      do i = 1, n
        ! pseudo-shuffled keys; -1 marks particles outside the grid
        keys(i) = mod(i*7919 + ic*104729, modk(ic)) + 1
        if (mod(i*31 + ic, 11) == 0) keys(i) = -1
        ip(i) = i
      end do
      a(1) = real(n)
      do i = 1, n
        a(1+i) = real(keys(i))
      end do
      call sort2(n, keys, ip)
      do i = 1, n
        o(i) = real(keys(i))
        o(n+i) = real(ip(i))
      end do
      call rowv('sort2', a, n+1, o, 2*n)
    end do
  end subroutine emit_sort2

  ! ------------------------------------------------------------------------
  ! convect (convect43c.f90) on soundings that straddle its branches.
  ! NCONVTOP is set to the sentinel 777 before every call: upstream leaves it
  ! unassigned on its early returns, and the row records that.
  !
  ! Rows:
  !   convect.sounding  id, nl            ; t, q, qs, p, ph (1..nl+1 each)
  !   convect           id, nl, delt, cbmf_in, nconvtop_before
  !                     ; iflag, cbmf, precip, wd, tprime, qprime, nconvtop,
  !                       ft(1..nl+1), fq(1..nl+1), sub(1..nl+1)
  !   convect.fmass     id, i             ; fmass(i, 1..nl+1)  [iflag 1 or 4]
  subroutine emit_convect()
    integer :: id, j
    real :: cb, g
    id = 0
    ! 1-3 deep tropical convection, cloud-base mass flux carried between calls
    cb = 0.
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 900., cb)
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 900., cb)
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 900., cb)
    ! 4 very moist deep column
    cb = 0.
    call run_convect(id, 14, 300., .0060, .95, .90, 0, 0., 0., -1., 900., cb)
    ! 5 shallow convection under an inversion near 810 hPa
    cb = 0.
    call run_convect(id, 14, 296., .0065, .80, .30, 6, 6., 0., -1., 900., cb)
    ! 6 strong low inversion: thin cloud
    cb = 0.
    call run_convect(id, 14, 295., .0065, .90, .20, 4, 8., 0., -1., 900., cb)
    cb = 0.002
    call run_convect(id, 14, 295., .0065, .90, .20, 4, 8., 0., -1., 900., cb)
    ! 8 isothermal: moist static energy increases upward -> IFLAG 0
    cb = 0.
    call run_convect(id, 14, 280., 0., .50, .50, 0, 0., 0., -1., 900., cb)
    ! 9 parcel origin colder than 250 K -> IFLAG 0
    cb = 0.
    call run_convect(id, 14, 245., .0065, .80, .50, 0, 0., 0., -1., 900., cb)
    ! 10 bone dry: Q(NK) <= 0 -> IFLAG 0
    cb = 0.
    call run_convect(id, 14, 300., .0065, 0., 0., 0, 0., 0., -1., 900., cb)
    ! 11 nearly dry: LCL above 200 hPa -> IFLAG 2
    cb = 0.
    call run_convect(id, 14, 300., .0065, 1.e-4, 1.e-4, 0, 0., 0., -1., 900., cb)
    ! 12 strongly supersaturated surface: LCL formula >= 2000 hPa -> IFLAG 2
    cb = 0.
    call run_convect(id, 14, 300., .0065, .80, .50, 0, 0., 0., 8., 900., cb)
    ! 13 cloud base above NL-1 (NL = 8) -> IFLAG 3
    cb = 0.
    call run_convect(id, 8, 300., .0065, .05, .05, 0, 0., 0., .3, 900., cb)
    ! 14 a long time step that still satisfies the CFL bound (IFLAG 1)
    cb = 0.
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 30000., cb)
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 30000., cb)
    ! 16 elevated convection: cold, dry lowest level, so NK > 1
    cb = 0.
    call run_convect(id, 14, 300., .0065, .90, .60, 0, 0., -6., .30, 900., cb)
    cb = 0.01
    call run_convect(id, 14, 300., .0065, .90, .60, 0, 0., -6., .30, 900., cb)
    ! 18 cold-based convection (ice branch of TLIFT, snow in the downdraft)
    cb = 0.
    call run_convect(id, 14, 268., .0065, .90, .70, 0, 0., 0., -1., 900., cb)
    ! 19.. a family around marginal stability: stable at cloud base, zero
    ! mass flux, weak convection; each with no prior flux and with a prior flux
    do j = 0, 11
      g = r4(real(.0040d0 + .0005d0*mod(j,4)))
      cb = 0.
      call run_convect(id, 14, 298., g, .75, .50, 0, 0., -.5 + .5*real(j/4), -1., 900., cb)
      cb = 0.003
      call run_convect(id, 14, 298., g, .75, .50, 0, 0., -.5 + .5*real(j/4), -1., 900., cb)
    end do
    ! 43.. dry lower troposphere over a moist surface layer
    do j = 0, 3
      cb = 0.
      call run_convect(id, 14, 303. - 2.*real(j), .0070, .30, .30, 0, 0., 0., .90, 900., cb)
    end do
    ! 47.. capped convection: cloud top below NL (INB < NL), from a thin
    ! cloud with no precipitating downdraft (EP(INB) < 1e-4: GOTO 405) to
    ! mid-level tops; then the same under a huge step (CFL flag, IFLAG 4)
    do j = 1, 2
      g = 900.
      if (j == 2) g = 1.e6
      cb = 0.
      call run_convect(id, 14, 295., .0065, .90, .40, 4, 15., 0., -1., g, cb)
      cb = 0.
      call run_convect(id, 14, 298., .0065, .90, .40, 4, 15., 0., -1., g, cb)
      cb = 0.
      call run_convect(id, 14, 295., .0065, .90, .40, 5, 12., 0., -1., g, cb)
      cb = 0.003
      call run_convect(id, 14, 302., .0065, .75, .40, 5, 12., 0., -1., g, cb)
      cb = 0.
      call run_convect(id, 14, 295., .0065, .90, .40, 7, 10., 0., -1., g, cb)
      cb = 0.
      call run_convect(id, 14, 298., .0065, .90, .40, 8, 8., 0., -1., g, cb)
      cb = 0.003
      call run_convect(id, 14, 302., .0065, .75, .40, 8, 8., 0., -1., g, cb)
    end do
    ! 61 parcel unstable at cloud base but zero mass-flux increment with no
    ! prior flux: convect returns IFLAG 1 with nothing computed (line 617)
    cb = 0.
    call run_convect(id, 14, 298., .0065, .75, .40, 4, 8., 0., -1., 900., cb)
    ! 62.. weakly unstable columns with shallow-to-mid tops
    do j = 0, 3
      cb = 0.
      call run_convect(id, 14, 298., r4(real(.0050d0 + .0004d0*j)), .90, .50, 0, 0., 1., -1., 900., cb)
    end do
    ! 66 NL = 3, the smallest NL the scheme accepts
    cb = 0.
    call run_convect(id, 3, 302., .0065, .85, .60, 0, 0., 0., -1., 900., cb)
    ! 67 cold (T(NK) < 250 K) but steep and moist: the 250 K guard alone
    ! stops convection here
    cb = 0.
    call run_convect(id, 14, 248., .0095, .95, .70, 0, 0., 0., -1., 900., cb)
    ! 68 dry superadiabatic column: NK = 1, LCL at ~210 hPa (between the
    ! 200 hPa guard and cloud base above NL-1) -> IFLAG 3
    cb = 0.
    call run_convect(id, 14, 302., .012, 1.2e-3, 1.2e-3, 0, 0., 0., -1., 900., cb)
    ! 69-70 a level at 0.9494 p(1): inside the downdraft ramp (0.949) only
    alt_grid = .true.
    cb = 0.
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 900., cb)
    cb = 0.
    call run_convect(id, 14, 300., .0065, .95, .60, 0, 0., 0., -1., 900., cb)
    alt_grid = .false.
    ! 71-72 time steps 2% below the CFL threshold of the level that sets it:
    ! level 1 (deep column) and a level above (elevated convection)
    cb = 0.
    call run_convect(id, 14, 302., .0065, .85, .60, 0, 0., 0., -1., 384754.40625, cb)
    cb = 0.
    call run_convect(id, 14, 300., .0065, .90, .60, 0, 0., -6., .30, 87071.765625, cb)
    ! 73 a remembered flux that almost cancels the (negative) increment:
    ! CBMF ~ 5e-10, so FMASS lies between 1e-20 and 1e-8 (NCONVTOP's EPSILON)
    cb = 6.4357016e-3
    call run_convect(id, 14, 298., .0045, .75, .50, 0, 0., -.5, -1., 900., cb)
  end subroutine emit_convect

  subroutine run_convect(id, nl, ts, gam, rhlo, rhhi, kinv, dtinv, dt1, rh1, delt, cb)
    integer, intent(inout) :: id
    integer, intent(in) :: nl, kinv
    real, intent(in) :: ts, gam, rhlo, rhhi, dtinv, dt1, rh1, delt
    real, intent(inout) :: cb
    integer :: k, n1, iflag, i, j
    real :: p(16), t(16), q(16), qs(16), cbin, dt, ph(18)
    real :: a(5), o(7 + 3*16), s(5*16)
    real :: precip, wd, tprime, qprime
    id = id + 1
    n1 = nl + 1
    ph = phlist
    if (alt_grid) ph(4) = 919.6
    do k = 1, n1
      p(k) = r4(0.5*(ph(k) + ph(k+1)))
    end do
    call make_column(n1, p, ts, gam, rhlo, rhhi, kinv, dtinv, dt1, rh1, t, q, qs)
    do k = 1, n1
      tconv(k) = t(k)
      qconv(k) = q(k)
      qsconv(k) = qs(k)
      pconv_hpa(k) = p(k)
      phconv_hpa(k) = r4(ph(k))
      s(k) = t(k)
      s(n1 + k) = q(k)
      s(2*n1 + k) = qs(k)
      s(3*n1 + k) = p(k)
      s(4*n1 + k) = r4(ph(k))
    end do
    a(1) = real(id)
    a(2) = real(nl)
    call rowv('convect.sounding', a, 2, s, 5*n1)
    cb = r4(cb)
    cbin = cb
    dt = r4(delt)
    nconvtop = 777
    a(3) = dt
    a(4) = cbin
    a(5) = real(nconvtop)
    call convect(nconvlevmax, nl, dt, iflag, precip, wd, tprime, qprime, cb)
    o(1) = real(iflag)
    o(2) = cb
    o(3) = precip
    o(4) = wd
    o(5) = tprime
    o(6) = qprime
    o(7) = real(nconvtop)
    do k = 1, n1
      o(7 + k) = ft(k)
      o(7 + n1 + k) = fq(k)
      o(7 + 2*n1 + k) = sub(k)
    end do
    call rowv('convect', a, 5, o, 7 + 3*n1)
    if (iflag == 1 .or. iflag == 4) then
      do i = 1, n1
        a(2) = real(i)
        do j = 1, n1
          o(j) = fmass(i, j)
        end do
        call rowv('convect.fmass', a, 2, o, n1)
      end do
    end if
  end subroutine run_convect

  ! ------------------------------------------------------------------------
  ! calcmatrix (calcmatrix.f90 -> convect) on nuvz = 17, nconvlev = 15
  ! columns, both met formats.
  !
  ! Rows:
  !   calcmatrix.column   id, format, psconv ; tconv(1..16), qconv(1..16),
  !                                            pconv(1..16) before the call
  !   calcmatrix          id, delt, cbmf_in
  !                       ; lconv, cbmf_out, nconvtop, pconv(1..16),
  !                         phconv(1..17), dpr(1..16), qsconv(1..16)
  !   calcmatrix.fmassfrac id, k ; fmassfrac(k, 1..nconvtop)   [lconv only]
  subroutine emit_calcmatrix()
    integer :: id, f, fmt
    real :: cb
    id = 0
    do f = 1, 2
      fmt = GRIBFILE_CENTRE_ECMWF
      if (f == 2) fmt = GRIBFILE_CENTRE_NCEP
      cb = 0.
      call run_calcmatrix(id, fmt, 100000., 302., .0065, .85, .60, 0, 0., 900., cb)
      ! the same column again, carrying the cloud-base mass flux
      call run_calcmatrix(id, fmt, 100000., 302., .0065, .85, .60, 0, 0., 900., cb)
      cb = 0.
      call run_calcmatrix(id, fmt, 98500., 296., .0065, .80, .30, 6, 6., 900., cb)
      ! stable column with a remembered flux: calcmatrix restores the flux
      cb = 0.05
      call run_calcmatrix(id, fmt, 101000., 280., 0., .50, .50, 0, 0., 900., cb)
      cb = 0.
      call run_calcmatrix(id, fmt, 101000., 280., 0., .50, .50, 0, 0., 900., cb)
      ! CFL-violating step (IFLAG 4 still updates the matrix)
      cb = 0.
      call run_calcmatrix(id, fmt, 100000., 302., .0065, .85, .60, 0, 0., 1.e6, cb)
      ! capped column (cloud top below nconvlev)
      cb = 0.
      call run_calcmatrix(id, fmt, 100000., 295., .0065, .90, .40, 5, 12., 900., cb)
      ! marginal column, prior flux decaying
      cb = 0.003
      call run_calcmatrix(id, fmt, 99000., 298., .0045, .75, .50, 0, 0., 900., cb)
      cb = 0.
      call run_calcmatrix(id, fmt, 99000., 298., .0045, .75, .50, 0, 0., 900., cb)
    end do
  end subroutine emit_calcmatrix

  ! Column at the ECMWF full-level pressures of psconv; for NCEP the same
  ! pressures are written into pconv(1..nuvz-1) as convmix would.
  subroutine fill_calc_column(fmt, ps_in, ts, gam, rhlo, rhhi, kinv, dtinv)
    integer, intent(in) :: fmt, kinv
    real, intent(in) :: ps_in, ts, gam, rhlo, rhhi, dtinv
    integer :: k
    real :: pk(16), t(16), q(16), qs(16)
    nuvz = nuvz_c
    nconvlev = nconvlev_c
    psconv = r4(ps_in)
    do k = 1, nuvz_c - 1
      pk(k) = lin(akz(k+1), bkz(k+1), psconv, 100.)
    end do
    call make_column(nuvz_c - 1, pk, ts, gam, rhlo, rhhi, kinv, dtinv, 0., -1., t, q, qs)
    do k = 1, nuvz_c - 1
      tconv(k) = t(k)
      qconv(k) = q(k)
      if (fmt /= GRIBFILE_CENTRE_ECMWF) pconv(k) = lin(0., pk(k), 100., 1.)
    end do
  end subroutine fill_calc_column

  subroutine run_calcmatrix(id, fmt, ps_in, ts, gam, rhlo, rhhi, kinv, dtinv, delt, cb)
    integer, intent(inout) :: id
    integer, intent(in) :: fmt, kinv
    real, intent(in) :: ps_in, ts, gam, rhlo, rhhi, dtinv, delt
    real, intent(inout) :: cb
    integer :: k, kk, m
    real :: a(3), o(100), cbin, dt
    logical :: lconv
    id = id + 1
    call fill_calc_column(fmt, ps_in, ts, gam, rhlo, rhhi, kinv, dtinv)
    m = nuvz_c - 1
    a(1) = real(id)
    a(2) = real(fmt)
    a(3) = psconv
    do k = 1, m
      o(k) = tconv(k)
      o(m + k) = qconv(k)
      o(2*m + k) = pconv(k)
    end do
    call rowv('calcmatrix.column', a, 3, o, 3*m)
    cb = r4(cb)
    cbin = cb
    dt = r4(delt)
    call calcmatrix(lconv, dt, cb, fmt)
    a(2) = dt
    a(3) = cbin
    o(1) = 0.
    if (lconv) o(1) = 1.
    o(2) = cb
    o(3) = real(nconvtop)
    do k = 1, m
      o(3 + k) = pconv(k)
      o(3 + m + nuvz_c + k) = dpr(k)
      o(3 + 2*m + nuvz_c + k) = qsconv(k)
    end do
    do k = 1, nuvz_c
      o(3 + m + k) = phconv(k)
    end do
    call rowv('calcmatrix', a, 3, o, 3 + 3*m + nuvz_c)
    if (lconv) then
      do k = 1, nconvtop
        a(2) = real(k)
        do kk = 1, nconvtop
          o(kk) = fmassfrac(k, kk)
        end do
        call rowv('calcmatrix.fmassfrac', a, 2, o, nconvtop)
      end do
    end if
  end subroutine run_calcmatrix

  ! ------------------------------------------------------------------------
  ! redist (redist.f90) for single particles on a convecting column set up by
  ! calcmatrix (the calcmatrix rows of these columns are emitted too, with
  ! ids continuing the calcmatrix group).
  !
  ! Each call gets a one-element draw queue, so `ndraws` (0 or 1) records
  ! whether redist drew. ktop_in = 2 reuses the SAVEd uvzlev of the previous
  ! call -- including, at the first call on column B, column A's (the SAVE is
  ! per process, not per column).
  !
  ! Row: redist  seq, colid, ktop_in, ldirect, lsynctime, height(nz),
  !              tt2conv, td2conv, z_in, rn
  !            ; z_out, ipconv, ktop_out, ndraws
  subroutine emit_redist()
    integer, parameter :: nz_s = 16, nr = 10
    real :: zs(nz_s), rns(nr), cb
    integer :: col, iz, ir, idir, seq, colid, ktop, ipconv, fmt
    real :: a(10), o(4)
    integer :: id
    zs = (/ 0., 3., 30., 150., 400., 800., 1500., 2500., 4000., 6000., &
            8500., 11000., 13500., 15500., 16500., 25000. /)
    rns = (/ 0., 1.e-6, .02, .15, .4, .6, .85, .97, .9999, 1. /)
    do ir = 1, nr
      rns(ir) = r4(rns(ir))
    end do
    nz = 20
    height(nz) = 16000.
    seq = 0
    id = 100
    do col = 1, 2
      cb = 0.
      if (col == 1) then
        fmt = GRIBFILE_CENTRE_ECMWF
        call run_calcmatrix(id, fmt, 100000., 302., .0065, .85, .60, 0, 0., 900., cb)
      else
        fmt = GRIBFILE_CENTRE_NCEP
        call run_calcmatrix(id, fmt, 98500., 296., .0065, .80, .30, 6, 6., 900., cb)
      end if
      colid = id
      tt2conv = add(tconv(1), 1.)
      td2conv = add(tt2conv, -3.)
      if (col == 2) then
        ! The first calls on column B pass ktop = 2, so redist reuses the
        ! uvzlev SAVEd from column A (the SAVE is per process, not per column).
        ldirect = 1
        lsynctime = 900
        seq = seq + 1
        call one_redist(seq, colid, 2, 400., .5)
        seq = seq + 1
        call one_redist(seq, colid, 2, 2500., .85)
        seq = seq + 1
        call one_redist(seq, colid, 2, 8500., .5)
      end if
      do idir = 1, 2
        ldirect = 1
        lsynctime = 900
        if (idir == 2) then
          ldirect = -1
          lsynctime = -900
        end if
        do iz = 1, nz_s
          do ir = 1, nr
            seq = seq + 1
            ktop = 0
            a(1) = real(seq)
            a(2) = real(colid)
            a(3) = real(ktop)
            a(4) = real(ldirect)
            a(5) = real(lsynctime)
            a(6) = height(nz)
            a(7) = tt2conv
            a(8) = td2conv
            a(9) = zs(iz)
            a(10) = rns(ir)
            shim_draws(1) = rns(ir)
            shim_n = 1
            shim_next = 0
            if (.not. allocated(ztra1)) then
              allocate(ztra1(1))
            end if
            ztra1(1) = zs(iz)
            call redist(1, ktop, ipconv)
            o(1) = ztra1(1)
            o(2) = real(ipconv)
            o(3) = real(ktop)
            o(4) = real(shim_next)
            call rowv('redist', a, 10, o, 4)
          end do
        end do
      end do
      if (col == 1) then
        ! Subsidence over a very long step pushes particles near the ground
        ! below zero (column A has NK = 1, so SUB(2) > 0): redist reflects them.
        ldirect = 1
        lsynctime = 3000000
        do iz = 2, 3
          do ir = 3, 5, 2
            seq = seq + 1
            call one_redist(seq, colid, 0, zs(iz), rns(ir))
          end do
        end do
      end if
    end do
    ! Column C: an inversion whose half-level virtual temperature steps are
    ! 0.028 K and 0.231 K, either side of redist's |dTv| > 0.2 switch.
    cb = 0.
    call run_calcmatrix(id, GRIBFILE_CENTRE_ECMWF, 98500., 296., .0065, .80, .30, 6, 6.9, 900., cb)
    colid = id
    ldirect = 1
    lsynctime = 900
    do iz = 1, nz_s
      do ir = 4, 7, 3
        seq = seq + 1
        tt2conv = add(tconv(1), 1.)
        td2conv = add(tt2conv, -3.)
        call one_redist(seq, colid, 0, zs(iz), rns(ir))
      end do
    end do
    ! The 2 m temperature offset, swept so that |Tv(half level 2) - Tv(2 m)|
    ! crosses 0.2 K (the first uvzlev step).
    do iz = 0, 40
      seq = seq + 1
      tt2conv = add(tconv(1), r4(real(-1d0 + 0.05d0*iz)))
      td2conv = add(tt2conv, -3.)
      call one_redist(seq, colid, 0, 2500., .5)
    end do
    tt2conv = add(tconv(1), 1.)
    td2conv = add(tt2conv, -3.)
    ! A longer synchronisation step (larger subsidence displacement).
    lsynctime = 3600
    ldirect = 1
    do iz = 1, nz_s
      seq = seq + 1
      ktop = 0
      a(1) = real(seq)
      a(2) = real(colid)
      a(3) = real(ktop)
      a(4) = real(ldirect)
      a(5) = real(lsynctime)
      a(6) = height(nz)
      a(7) = tt2conv
      a(8) = td2conv
      a(9) = zs(iz)
      a(10) = .5
      shim_draws(1) = .5
      shim_n = 1
      shim_next = 0
      ztra1(1) = zs(iz)
      call redist(1, ktop, ipconv)
      o(1) = ztra1(1)
      o(2) = real(ipconv)
      o(3) = real(ktop)
      o(4) = real(shim_next)
      call rowv('redist', a, 10, o, 4)
    end do
  end subroutine emit_redist

  ! One redist row (see emit_redist) with the current com_mod ldirect,
  ! lsynctime, height(nz) and conv_mod tt2conv/td2conv.
  subroutine one_redist(seq, colid, ktop_in, z, rn)
    integer, intent(in) :: seq, colid, ktop_in
    real, intent(in) :: z, rn
    integer :: ktop, ipconv
    real :: a(10), o(4)
    ktop = ktop_in
    a(1) = real(seq)
    a(2) = real(colid)
    a(3) = real(ktop)
    a(4) = real(ldirect)
    a(5) = real(lsynctime)
    a(6) = height(nz)
    a(7) = tt2conv
    a(8) = td2conv
    a(9) = z
    a(10) = rn
    shim_draws(1) = rn
    shim_n = 1
    shim_next = 0
    ztra1(1) = z
    call redist(1, ktop, ipconv)
    o(1) = ztra1(1)
    o(2) = real(ipconv)
    o(3) = real(ktop)
    o(4) = real(shim_next)
    call rowv('redist', a, 10, o, 4)
  end subroutine one_redist

  ! ------------------------------------------------------------------------
  ! convmix (convmix.f90) end to end on a 5 x 4 mother grid and one 5 x 5 nest
  ! (xln = 1, yln = .5, xrn = 3, yrn = 2.5, resolution factor 2), nuvz = 17,
  ! nconvlev = 15, 60 particles, four successive calls sharing cbaseflux and
  ! conv_mod state: ECMWF forward, ECMWF forward later (memind swapped),
  ! NCEP/GFS forward, ECMWF backward.
  !
  ! Rows:
  !   convmix.met       grid, slot, ix, jy ; ps, tt2, td2, t3(1..17),
  !                     q3(1..17), p3(1..17)
  !     grid 0 = mother: t3/q3 are BOTH tth/qvh(k) and tt/qv(k) (the driver
  !     fills the ECMWF and GFS arrays with the same values), p3 = pplev(k);
  !     grid 1 = nest: tthn/qvhn(k), p3 unused (0).
  !   convmix.particle  (double) call, ipart ; itra1, xtra1, ytra1, ztra1_in
  !   convmix.order     call, grid ; ipoint(1..numpart) from upstream sort2 on
  !                     the column keys, then the sorted keys
  !   convmix.draws     call, n ; the draw queue
  !   convmix           call, itime, memtime1, memtime2, memind1, memind2,
  !                     lsynctime, ldirect, format, height(nz)
  !                     ; ztra1_out(1..numpart), draws used,
  !                       cbaseflux(0:4,0:3) (ix fastest),
  !                       cbasefluxn(0:4,0:4,1)
  subroutine emit_convmix()
    integer, parameter :: np = 60, mx = 5, my = 4, nnx = 5, nny = 5
    integer :: ix, jy, m, k, ic, ip, i
    real :: pk(17), t(17), q(17), qs(17), ts, gam, rhlo, rhhi, psv
    real :: a(10), o(200)
    double precision :: ad(2), od(4)
    integer :: itimes(4), mi1(4), lsyncs(4), ldirs(4), fmts(4)
    integer :: keys(np), ipt(np), ngrid, j
    real :: eps
    double precision :: x, y

    nuvz = nuvz_c
    nconvlev = nconvlev_c
    nx = mx
    ny = my
    nz = 20
    height(nz) = 16000.
    iflux = 0
    numbnests = 1
    nxn(1) = nnx
    nyn(1) = nny
    xln(1) = 1.
    yln(1) = .5
    xrn(1) = 3.
    yrn(1) = 2.5
    xresoln(1) = 2.
    yresoln(1) = 2.
    if (.not. allocated(tthn)) then
      allocate(tthn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,numwfmem,numbnests))
      allocate(qvhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,numwfmem,numbnests))
    end if
    cbaseflux = 0.
    cbasefluxn = 0.

    ! Mother-grid fields: convective in the warm east, stable in the north row.
    do m = 1, 2
      do jy = 0, my - 1
        do ix = 0, mx - 1
          psv = r4(100000. - 400.*real(jy) + 150.*real(ix) - 100.*real(m-1))
          ts = r4(real(294d0 + 2d0*ix - 1.5d0*jy + .7d0*(m-1)))
          gam = .0065
          rhlo = r4(real(.80d0 + .03d0*ix - .05d0*jy))
          rhhi = .55
          if (jy == my - 1) gam = 0.
          do k = 1, 17
            pk(k) = lin(akz(k), bkz(k), psv, 100.)
          end do
          call make_column(17, pk, ts, gam, rhlo, rhhi, 0, 0., 0., -1., t, q, qs)
          ps(ix,jy,1,m) = psv
          tt2(ix,jy,1,m) = add(t(1), .5)
          td2(ix,jy,1,m) = add(t(1), -2.)
          do k = 1, 17
            tth(ix,jy,k,m) = t(k)
            qvh(ix,jy,k,m) = q(k)
            tt(ix,jy,k,m) = t(k)
            qv(ix,jy,k,m) = q(k)
            pplev(ix,jy,k,m) = lin(0., pk(k), 100., 1.)
          end do
          a(1) = 0.
          a(2) = real(m)
          a(3) = real(ix)
          a(4) = real(jy)
          o(1) = ps(ix,jy,1,m)
          o(2) = tt2(ix,jy,1,m)
          o(3) = td2(ix,jy,1,m)
          do k = 1, 17
            o(3 + k) = t(k)
            o(20 + k) = q(k)
            o(37 + k) = pplev(ix,jy,k,m)
          end do
          call rowv('convmix.met', a, 4, o, 54)
        end do
      end do
    end do
    ! Nest fields: a moister, warmer patch.
    do m = 1, 2
      do jy = 0, nny - 1
        do ix = 0, nnx - 1
          psv = r4(100500. - 100.*real(jy) + 60.*real(ix) - 80.*real(m-1))
          ts = r4(real(299d0 + .6d0*ix - .4d0*jy + .5d0*(m-1)))
          rhlo = r4(real(.86d0 + .01d0*ix))
          do k = 1, 17
            pk(k) = lin(akz(k), bkz(k), psv, 100.)
          end do
          call make_column(17, pk, ts, .0065, rhlo, .6, 0, 0., 0., -1., t, q, qs)
          psn(ix,jy,1,m,1) = psv
          tt2n(ix,jy,1,m,1) = add(t(1), .5)
          td2n(ix,jy,1,m,1) = add(t(1), -2.)
          do k = 1, 17
            tthn(ix,jy,k,m,1) = t(k)
            qvhn(ix,jy,k,m,1) = q(k)
          end do
          a(1) = 1.
          a(2) = real(m)
          a(3) = real(ix)
          a(4) = real(jy)
          o(1) = psv
          o(2) = tt2n(ix,jy,1,m,1)
          o(3) = td2n(ix,jy,1,m,1)
          do k = 1, 17
            o(3 + k) = t(k)
            o(20 + k) = q(k)
            o(37 + k) = 0.
          end do
          call rowv('convmix.met', a, 4, o, 54)
        end do
      end do
    end do

    if (allocated(ztra1)) deallocate(ztra1)
    allocate(itra1(np), xtra1(np), ytra1(np), ztra1(np), itramem(np))
    numpart = np
    memtime(1) = 0
    memtime(2) = 10800
    itimes = (/ 3600, 7200, 3600, 7200 /)
    mi1    = (/ 1, 2, 1, 2 /)
    lsyncs = (/ 900, 900, 900, -900 /)
    ldirs  = (/ 1, 1, 1, -1 /)
    fmts   = (/ GRIBFILE_CENTRE_ECMWF, GRIBFILE_CENTRE_ECMWF, &
               GRIBFILE_CENTRE_NCEP, GRIBFILE_CENTRE_ECMWF /)

    do ic = 1, 4
      memind(1) = mi1(ic)
      memind(2) = 3 - mi1(ic)
      lsynctime = lsyncs(ic)
      ldirect = ldirs(ic)
      ! Particles: several per column, a few not yet released, a few right at
      ! the nest margin (inside it for NCEP, outside for ECMWF's eps).
      do ip = 1, np
        itra1(ip) = itimes(ic)
        if (mod(ip, 13) == 0) itra1(ip) = itimes(ic) + 900
        xtra1(ip) = dble(mod(ip*7 + ic, 5)) + 0.25d0*dble(mod(ip, 3)) - 0.2d0
        ytra1(ip) = dble(mod(ip*3 + ic, 4)) + 0.2d0*dble(mod(ip, 2)) - 0.1d0
        if (xtra1(ip) < 0.d0) xtra1(ip) = 0.1d0
        if (ytra1(ip) < 0.d0) ytra1(ip) = 0.1d0
        if (mod(ip, 17) == 0) xtra1(ip) = 1.0005d0
        if (mod(ip, 19) == 0) ytra1(ip) = 2.4995d0
        ztra1(ip) = real(mod(ip*1237 + ic*311, 17500))
        ad(1) = dble(ic)
        ad(2) = dble(ip)
        od(1) = dble(itra1(ip))
        od(2) = xtra1(ip)
        od(3) = ytra1(ip)
        od(4) = dble(ztra1(ip))
        call rowvd('convmix.particle', ad, 2, od, 4)
      end do
      ! The permutation upstream sort2 produces for these columns. The keys are
      ! formed exactly as convmix.f90 lines 85-137 form them (this is the one
      ! piece of convmix logic the driver repeats, so that sort2 sees the same
      ! input; the Rust test checks the keys against the port's).
      eps = nxmax/3.e5
      do j = 0, 1
        do ip = 1, np
          keys(ip) = -1
          ipt(ip) = ip
          if (itra1(ip) /= itimes(ic)) cycle
          x = xtra1(ip)
          y = ytra1(ip)
          ngrid = 0
          if (fmts(ic) == GRIBFILE_CENTRE_ECMWF) then
            if (x > xln(1)+eps .and. x < xrn(1)-eps .and. &
                y > yln(1)+eps .and. y < yrn(1)-eps) ngrid = 1
          else
            if (x > xln(1) .and. x < xrn(1) .and. y > yln(1) .and. y < yrn(1)) ngrid = 1
          end if
          if (j == 0 .and. ngrid == 0) keys(ip) = 1 + nint(y)*nx + nint(x)
          if (j == 1 .and. ngrid == 1) keys(ip) = 1 + nint(real((y-yln(1))*yresoln(1)))*nxn(1) &
               + nint(real((x-xln(1))*xresoln(1)))
        end do
        call sort2(np, keys, ipt)
        a(1) = real(ic)
        a(2) = real(j)
        do ip = 1, np
          o(ip) = real(ipt(ip))
          o(np + ip) = real(keys(ip))
        end do
        call rowv('convmix.order', a, 2, o, 2*np)
      end do
      ! Distinct draws, enough for every particle.
      do i = 1, np
        shim_draws(i) = r4(real(mod(.37d0 + .6180339887d0*dble(i + 7*ic), 1d0)))
      end do
      shim_n = np
      shim_next = 0
      a(1) = real(ic)
      a(2) = real(np)
      call rowv('convmix.draws', a, 2, shim_draws, np)

      call convmix(itimes(ic), fmts(ic))

      a(1) = real(ic)
      a(2) = real(itimes(ic))
      a(3) = real(memtime(1))
      a(4) = real(memtime(2))
      a(5) = real(memind(1))
      a(6) = real(memind(2))
      a(7) = real(lsynctime)
      a(8) = real(ldirect)
      a(9) = real(fmts(ic))
      a(10) = height(nz)
      do ip = 1, np
        o(ip) = ztra1(ip)
      end do
      o(np + 1) = real(shim_next)
      do jy = 0, my - 1
        do ix = 0, mx - 1
          o(np + 2 + ix + mx*jy) = cbaseflux(ix, jy)
        end do
      end do
      do jy = 0, nny - 1
        do ix = 0, nnx - 1
          o(np + 2 + mx*my + ix + nnx*jy) = cbasefluxn(ix, jy, 1)
        end do
      end do
      call rowv('convmix', a, 10, o, np + 1 + mx*my + nnx*nny)
    end do
  end subroutine emit_convmix

end program flexpart_reference_convection
