! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART code-to-code reference driver, stage 4: the particle step.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) VERBATIM:
!   advance, initialize, initialize_cbl_vel, re_initialize_particle, cbl,
!   hanna, hanna1, hanna_short, windalign, get_settling, dynamic_viscosity,
!   interpol_all(_nests), interpol_misslev(_nests), interpol_wind(_nests),
!   interpol_wind_short(_nests), interpol_vdep(_nests), cmapf_mod
! plus par_mod, com_mod, point_mod, interpol_mod, hanna_mod.
!
! Two local files stand in for upstream ones, and neither changes a routine
! under test:
!   - par_mod.f90 is compiled from a copy with the nest dimensions set
!     (maxnests=1, nxmaxn=12, nymaxn=12): it is FLEXPART's user configuration
!     file, and the shipped zeros make nests impossible to drive;
!   - dev/random_mod_shim_advance.f90 replaces random_mod.f90 (Numerical Recipes,
!     neither ported nor re-implemented, gh:#410). It returns draws the driver
!     sets, so both codes consume the same numbers.
!
! rannumb(i) = (mod(mod(i,2001)*7919, 2001) - 1000) / 400., exactly
! reproducible at both precisions (one rounding).
!
! Rows (all in double precision via rowvd, so the dp particle position is
! exact at both precisions):
!   field       setup: <grid>;<id>;<slot>;<k>, 49 values (see interp driver;
!               id 8 = tt)
!   height      setup: level heights
!   domain      setup: nxmin1,nymin1,northpolemap(9),southpolemap(9),
!               xln,yln,xrn,yrn,xresoln,yresoln
!   case        setup: the run settings of the rows that follow
!   initialize  call:  seq,case,itime,xt,yt,zt,nrand0,ran3,gasdev ->
!               up,vp,wp,usigold,vsigold,wsigold,ldt,icbt
!   advance     call:  seq,case,itime,ldt,xt,yt,zt,up,vp,wp,usigold,vsigold,
!               wsigold,icbt,prob,nrand0 -> same state + ldt,nstop,
!               nan_count,nan_count2,u,v,w,h,ngrid
!   get_vdep_prob call: seq,case,itime,xt,yt,zt -> prob,ngrid,ix,jy (right
!               after an advance call, so the stale weights it uses are known)
program flexpart_reference_advance
  use par_mod
  use com_mod
  use point_mod
  use interpol_mod
  use hanna_mod
  use random_mod
  use cmapf_mod, only: stlmbr, stcm2p
  implicit none

  integer, parameter :: NXP = 7, NYP = 7, NZP = 10
  integer :: seq = 0
  real :: ctl_case = 5.

  write(*,'(A)') '# FLEXPART stage-4 particle-step reference, generated by dev/flexpart_reference_advance.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference.sh'
  write(*,'(A)') 'function,args,outputs'

  call setup_fields()
  call setup_domain()
  call fill_rannumb()
  call run_cases()

contains

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowvd

  real function synth(id, i, j, k, m)
    integer, intent(in) :: id, i, j, k, m
    real :: x, y, z, t
    x = real(i); y = real(j); z = real(k); t = real(m - 1)
    select case (id)
    case (1)
      synth = 2.0 + 0.9*x - 0.35*y + 0.6*sin(0.7*x + 0.3*y + 0.2*z) + 0.5*t + 0.4*z
    case (2)
      synth = -1.5 + 0.25*x + 0.8*y + 0.5*cos(0.4*x - 0.9*y + 0.3*z) - 0.3*t + 0.2*z
    case (3)
      synth = 0.02*sin(0.5*x + 0.8*y - 0.6*z + t) - 0.003*z
    case (4)
      synth = -3.0 + 0.5*x + 0.7*y + 0.3*sin(x*y + z) + 0.2*t
    case (5)
      synth = 4.0 - 0.6*x + 0.2*y - 0.4*cos(x - y + z) - 0.1*t
    case (6)
      synth = 1.2*exp(-z*0.12) + 0.01*x - 0.005*y + 0.002*t
    case (7)
      synth = -1.1e-4*exp(-z*0.12) + 1.e-6*(x - y) + 1.e-6*t
    case (8)
      synth = 300. - 6.*z + 0.3*x - 0.2*y + 0.5*t
    case (11)
      synth = 0.2 + 0.05*x + 0.03*y + 0.04*t
    case (12)
      synth = 0.8 + 0.1*x - 0.05*y + 0.3*t
    case (13)
      synth = 0.002*(x - 3.)*(1. + 0.2*t)
    case (14)
      synth = 600. + 40.*x + 25.*y + 150.*t
    case (15)
      synth = 11000. + 100.*x - 50.*y + 200.*t
    case (16)
      synth = 2.e-3 + 3.e-4*x - 1.e-4*y + 5.e-4*t
    case default
      synth = 0.
    end select
  end function synth

  subroutine echo(grid, id, m, k)
    integer, intent(in) :: grid, id, m, k
    double precision :: vals(NXP*NYP)
    integer :: i, j, ish, jsh
    ish = 0; jsh = 0
    if (grid == 1) then
      ish = 2; jsh = 1
    end if
    do j = 0, NYP-1
      do i = 0, NXP-1
        vals(1 + i + NXP*j) = dble(synth(id, i+ish, j+jsh, k, m))
      end do
    end do
    call rowvd('field', (/ dble(grid), dble(id), dble(m), dble(k) /), 4, vals, NXP*NYP)
  end subroutine echo

  subroutine setup_fields()
    integer :: i, j, k, m, id
    double precision :: hd(NZP)
    nz = NZP
    height(1:NZP) = (/ 0., 25., 80., 180., 400., 900., 2000., 5000., 10000., 16000. /)
    hd = dble(height(1:NZP))
    call rowvd('height', hd, NZP, (/ 0.d0 /), 1)
    memtime(1) = 0; memtime(2) = 10800
    memind(1) = 1; memind(2) = 2
    numbnests = 1
    call com_mod_allocate_nests()
    do m = 1, 2
      do k = 1, NZP
        do j = 0, NYP-1
          do i = 0, NXP-1
            uu(i,j,k,m) = synth(1, i, j, k, m)
            vv(i,j,k,m) = synth(2, i, j, k, m)
            ww(i,j,k,m) = synth(3, i, j, k, m)
            uupol(i,j,k,m) = synth(4, i, j, k, m)
            vvpol(i,j,k,m) = synth(5, i, j, k, m)
            rho(i,j,k,m) = synth(6, i, j, k, m)
            drhodz(i,j,k,m) = synth(7, i, j, k, m)
            tt(i,j,k,m) = synth(8, i, j, k, m)
            uun(i,j,k,m,1) = synth(1, i+2, j+1, k, m)
            vvn(i,j,k,m,1) = synth(2, i+2, j+1, k, m)
            wwn(i,j,k,m,1) = synth(3, i+2, j+1, k, m)
            rhon(i,j,k,m,1) = synth(6, i+2, j+1, k, m)
            drhodzn(i,j,k,m,1) = synth(7, i+2, j+1, k, m)
          end do
        end do
        do id = 1, 8
          call echo(0, id, m, k)
          if (id /= 4 .and. id /= 5 .and. id /= 8) call echo(1, id, m, k)
        end do
      end do
      do j = 0, NYP-1
        do i = 0, NXP-1
          ustar(i,j,1,m) = synth(11, i, j, 1, m)
          wstar(i,j,1,m) = synth(12, i, j, 1, m)
          oli(i,j,1,m) = synth(13, i, j, 1, m)
          hmix(i,j,1,m) = synth(14, i, j, 1, m)
          tropopause(i,j,1,m) = synth(15, i, j, 1, m)
          vdep(i,j,1,m) = synth(16, i, j, 1, m)
          ustarn(i,j,1,m,1) = synth(11, i+2, j+1, 1, m)
          wstarn(i,j,1,m,1) = synth(12, i+2, j+1, 1, m)
          olin(i,j,1,m,1) = synth(13, i+2, j+1, 1, m)
          hmixn(i,j,1,m,1) = synth(14, i+2, j+1, 1, m)
          tropopausen(i,j,1,m,1) = synth(15, i+2, j+1, 1, m)
          vdepn(i,j,1,m,1) = synth(16, i+2, j+1, 1, m)
        end do
      end do
      do id = 11, 16
        call echo(0, id, m, 1)
        call echo(1, id, m, 1)
      end do
    end do
  end subroutine setup_fields

  subroutine setup_domain()
    real :: sizenorth, sizesouth
    double precision :: d(26)
    integer :: i
    nxmin1 = NXP - 1
    nymin1 = NYP - 1
    sizenorth = 6.*(90. - switchnorth)/1.
    call stlmbr(northpolemap, 90., 0.)
    call stcm2p(northpolemap, 0., 0., switchnorth, 0., sizenorth, sizenorth, switchnorth, 180.)
    sizesouth = 6.*(switchsouth + 90.)/1.
    call stlmbr(southpolemap, -90., 0.)
    call stcm2p(southpolemap, 0., 0., switchsouth, 0., sizesouth, sizesouth, switchsouth, 180.)
    xln(1) = 1.; yln(1) = 1.; xrn(1) = 4.; yrn(1) = 4.
    xresoln(1) = 2.; yresoln(1) = 2.
    d(1) = dble(nxmin1); d(2) = dble(nymin1)
    do i = 1, 9
      d(2+i) = dble(northpolemap(i))
      d(11+i) = dble(southpolemap(i))
    end do
    d(21:26) = (/ dble(xln(1)), dble(yln(1)), dble(xrn(1)), dble(yrn(1)), &
                  dble(xresoln(1)), dble(yresoln(1)) /)
    call rowvd('domain', d, 26, (/ 0.d0 /), 1)
    allocate(xmass(2, maxspec))
    xmass(1,1) = 1.0
    xmass(2,1) = 0.0
  end subroutine setup_domain

  subroutine fill_rannumb()
    integer :: i
    do i = 1, maxrand
      rannumb(i) = real(mod(mod(i, 2001)*7919, 2001) - 1000)/400.
    end do
  end subroutine fill_rannumb

  ! The run settings of a case. Each setting is a com_mod variable.
  subroutine set_case(icase, ld, lsync, meth, ifn, tsw, cbf, ddep, lset, &
                      xg, ng, sg, swn, sws, olic, wstc, ylat0c, dyc, mt2, nb)
    integer, intent(in) :: icase, ld, lsync, meth, ifn, tsw, cbf, ddep, lset
    integer, intent(in) :: xg, ng, sg, mt2, nb
    real, intent(in) :: swn, sws, olic, wstc, ylat0c, dyc
    integer :: i, j, m
    double precision :: c(33)
    numbnests = nb
    ldirect = ld
    lsynctime = lsync
    method = meth
    ctl = ctl_case
    ifine = ifn
    fine = 1./real(ifine)
    mintime = 30
    turbswitch = (tsw == 1)
    cblflag = cbf
    DRYDEP = (ddep == 1)
    DRYDEPSPEC(1) = (ddep == 1)
    lwindinterv = 10800
    mdomainfill = 0
    lsettling = (lset == 1)
    ! nmixz as verttransform_ecmwf.f90 sets it: the first level above hmixmax.
    ! Case 1 instead uses a lower value, which upstream's verttransform never
    ! produces, to pin what advance does with levels above nmixz (their
    ! "already interpolated" flags are never reset, so their profiles are
    ! whatever interpol_all last left there).
    do i = 1, nz
      if (height(i) > hmixmax) then
        nmixz = i
        exit
      end if
    end do
    if (icase == 1) nmixz = 6
    nspec = 1
    density(1) = 2500.
    if (lset == 0) density(1) = -1.
    dquer(1) = 30.
    cunningham(1) = 1.005
    vsetaver(1) = -0.07
    xglobal = (xg == 1); nglobal = (ng == 1); sglobal = (sg == 1)
    switchnorthg = swn; switchsouthg = sws
    dx = 1.; dy = dyc; xlon0 = 10.; ylat0 = ylat0c
    dxconst = 180./(dx*r_earth*pi)
    dyconst = 180./(dy*r_earth*pi)
    memtime(1) = 0; memtime(2) = mt2
    ! optional uniform overrides of oli and wstar (0 = keep the synthetic field)
    do m = 1, 2
      do j = 0, NYP-1
        do i = 0, NXP-1
          if (olic /= 0.) then
            oli(i,j,1,m) = olic
          else
            oli(i,j,1,m) = synth(13, i, j, 1, m)
          end if
          if (wstc /= 0.) then
            wstar(i,j,1,m) = wstc
          else
            wstar(i,j,1,m) = synth(12, i, j, 1, m)
          end if
        end do
      end do
    end do
    c(1:33) = (/ dble(icase), dble(ldirect), dble(lsynctime), dble(method), dble(ctl), &
         dble(ifine), dble(fine), dble(mintime), dble(tsw), dble(cblflag), dble(ddep), &
         dble(d_trop), dble(d_strat), dble(lwindinterv), dble(turbmesoscale), &
         dble(mdomainfill), dble(lset), dble(nmixz), dble(density(1)), dble(dquer(1)), &
         dble(cunningham(1)), dble(vsetaver(1)), dble(xg), dble(ng), dble(sg), &
         dble(switchnorthg), dble(switchsouthg), dble(dx), dble(dy), dble(xlon0), &
         dble(ylat0), dble(memtime(2)), dble(numbnests) /)
    call rowvd('case', c, 33, (/ dble(dxconst), dble(dyconst), dble(olic), dble(wstc) /), 4)
  end subroutine set_case

  subroutine do_initialize(icase, itime, x, y, z, r3, gd)
    integer, intent(in) :: icase, itime
    real, intent(in) :: x, y, z, r3, gd
    integer :: ldt, nrand0
    integer(kind=2) :: icbt
    real :: up, vp, wp, us, vs, ws, zt
    real(kind=dp) :: xt, yt
    seq = seq + 1
    xt = dble(x); yt = dble(y); zt = z
    shim_ran3 = r3
    shim_gasdev = gd
    nrand0 = int(shim_ran3*real(maxrand-1)) + 1
    call initialize(itime, ldt, up, vp, wp, us, vs, ws, xt, yt, zt, icbt)
    call rowvd('initialize', (/ dble(seq), dble(icase), dble(itime), xt, yt, dble(z), &
         dble(nrand0), dble(r3), dble(gd) /), 9, &
         (/ dble(up), dble(vp), dble(wp), dble(us), dble(vs), dble(ws), dble(ldt), &
            dble(icbt) /), 8)
  end subroutine do_initialize

  ! nsteps successive advance calls of one particle, state carried.
  subroutine do_advance(icase, itime0, nsteps, ldt0, x, y, z, up0, vp0, wp0, r3)
    integer, intent(in) :: icase, itime0, nsteps, ldt0
    real, intent(in) :: x, y, z, up0, vp0, wp0, r3
    integer :: ldt, nstop, n, itime, nc1, nc2, nrand0
    integer(kind=2) :: icbt
    real :: up, vp, wp, us, vs, ws, zt, prob(maxspec)
    real(kind=dp) :: xt, yt
    double precision :: a(16), o(20)
    xt = dble(x); yt = dble(y); zt = z
    up = up0; vp = vp0; wp = wp0
    us = 0.125; vs = -0.125; ws = 0.015625
    icbt = 1
    prob = 0.
    ldt = ldt0
    itime = itime0
    do n = 1, nsteps
      seq = seq + 1
      shim_ran3 = r3
      nrand0 = int(shim_ran3*real(maxrand-1)) + 1
      nan_count = 0; nan_count2 = 0
      a = (/ dble(seq), dble(icase), dble(itime), dble(ldt), xt, yt, dble(zt), dble(up), &
             dble(vp), dble(wp), dble(us), dble(vs), dble(ws), dble(icbt), dble(prob(1)), &
             dble(nrand0) /)
      call advance(itime, 1, ldt, up, vp, wp, us, vs, ws, nstop, xt, yt, zt, prob, icbt)
      o = (/ xt, yt, dble(zt), dble(up), dble(vp), dble(wp), dble(us), dble(vs), &
             dble(ws), dble(icbt), dble(prob(1)), dble(ldt), dble(nstop), &
             dble(nan_count), dble(nan_count2), dble(u), dble(v), dble(w), dble(h), &
             dble(ngrid) /)
      call rowvd('advance', a, 16, o, 20)
      if (nstop /= 0) exit
      ! get_vdep_prob at the new position, with whatever weights advance left
      ! (at 5 m, below 2*href, so the deposition branch is taken)
      seq = seq + 1
      call get_vdep_prob(itime, xt, yt, 5., prob)
      call rowvd('get_vdep_prob', (/ dble(seq), dble(icase), dble(itime), xt, yt, 5.d0 /), 6, &
           (/ dble(prob(1)), dble(ngrid), dble(ix), dble(jy) /), 4)
      prob = 0.
      itime = itime + lsynctime
    end do
  end subroutine do_advance

  subroutine run_cases()
    real :: zs(7), r3s(3)
    integer :: iz, ir
    zs = (/ 3., 60., 350., 1500., 10500., 11400., 13000. /)
    r3s = (/ 0.37, 0.0, 0.9999995 /)

    ! 1: Gaussian turbulence, method 1, dry deposition, mother grid
    call set_case(1, 1, 900, 1, 1, 1, 0, 1, 0, 0, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, 10800, 0)
    do iz = 1, 7
      do ir = 1, 3
        call do_initialize(1, 0, 2.625, 3.25, zs(iz), r3s(ir), 0.4)
        call do_advance(1, 0, 3, 900, 2.625, 3.25, zs(iz), 0.25, -0.1875, 0.5, r3s(ir))
      end do
      call do_advance(1, 0, 2, 15, 2.625, 3.25, zs(iz), 0.25, -0.1875, 0.5, 0.37)
    end do
    ! 2: well-mixed scheme (hanna1), 3 sub-steps, method 0, settling on
    call set_case(2, 1, 900, 0, 3, 0, 0, 1, 1, 0, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, 10800, 0)
    do iz = 1, 7
      call do_initialize(2, 0, 3.75, 2.25, zs(iz), 0.37, 0.4)
      call do_advance(2, 0, 3, 900, 3.75, 2.25, zs(iz), -0.375, 0.125, 0.0625, 0.37)
      call do_advance(2, 0, 2, 15, 3.75, 2.25, zs(iz), -0.375, 0.125, 0.0625, 0.37)
    end do
    ! 3: skewed CBL, strongly unstable (-h/L >= 15), including a velocity far
    !    in the tails that triggers re_initialize_particle
    call set_case(3, 1, 900, 1, 2, 1, 1, 0, 0, 0, 0, 0, 999999., -999999., -0.02, 1.6, 1.0, 1.0, 10800, 0)
    do iz = 1, 3
      call do_initialize(3, 0, 2.25, 2.875, zs(iz), 0.2, -0.7)
      call do_initialize(3, 0, 2.25, 2.875, zs(iz), 0.95, 1.3)
      call do_advance(3, 0, 3, 20, 2.25, 2.875, zs(iz), 0.125, 0.1875, 0.3125, 0.37)
      call do_advance(3, 0, 2, 20, 2.25, 2.875, zs(iz), 0.125, 0.1875, 40.0, 0.37)
      call do_advance(3, 0, 2, 20, 2.25, 2.875, zs(iz), 0.125, 0.1875, -40.0, 0.37)
    end do
    ! 4: skewed CBL, moderately unstable (5 < -h/L < 15: the sine taper)
    call set_case(4, 1, 900, 1, 2, 1, 1, 0, 0, 0, 0, 0, 999999., -999999., -0.008, 1.1, 1.0, 1.0, 10800, 0)
    do iz = 1, 3
      call do_advance(4, 0, 3, 20, 3.125, 1.375, zs(iz), 0.125, 0.1875, 0.3125, 0.37)
    end do
    ! 5: CBL flag with weak instability (-h/L <= 5): the alternative drift
    call set_case(5, 1, 900, 1, 1, 1, 1, 0, 0, 0, 0, 0, 999999., -999999., -0.001, 0.5, 1.0, 1.0, 10800, 0)
    do iz = 1, 3
      call do_advance(5, 0, 3, 20, 3.125, 1.375, zs(iz), 0.125, 0.1875, 0.3125, 0.37)
    end do
    ! 6: backward in time
    call set_case(6, -1, -900, 1, 1, 1, 0, 1, 0, 0, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, -10800, 0)
    do iz = 1, 7
      call do_advance(6, 0, 3, 900, 2.625, 3.25, zs(iz), 0.25, -0.1875, 0.5, 0.37)
    end do
    ! just under h (970 m here): backward in time the mean w (< 0) lifts the
    ! particle through h inside the boundary-layer loop (the goto 700 exit)
    do ir = 1, 3
      call do_advance(6, 0, 2, 900, 2.625, 3.25, 969.875, 0.25, -0.1875, 0.0, r3s(ir))
      call do_advance(6, 0, 2, 40, 2.625, 3.25, 969.96875, 0.0, 0.0, 0.0, r3s(ir))
    end do
    ! ran3 = 0.0012795 selects nrand = 1280, so the vertical draw
    ! rannumb(nrand+3) is exactly 0: the particle stays just under h and the
    ! mean w carries it through h inside the boundary-layer loop
    call do_advance(6, 0, 2, 900, 2.625, 3.25, 969.875, 0.0, 0.0, 0.0, 0.0012795012)
    ! 7: nest (mother 1..4 x 1..4 at twice the resolution)
    call set_case(7, 1, 900, 1, 1, 1, 0, 1, 0, 0, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, 10800, 1)
    do iz = 1, 7
      call do_advance(7, 0, 3, 900, 2.25, 2.625, zs(iz), 0.25, -0.1875, 0.5, 0.37)
    end do
    ! 8: north-polar grid above grid y = 3.5, near the pole (lat 84..90)
    call set_case(8, 1, 900, 1, 1, 1, 0, 0, 0, 1, 1, 0, 3.5, -999999., 0., 0., 84.0, 1.0, 10800, 0)
    ! single steps from many starting points: each row then starts from the
    ! same decimal literal in both builds, so the real4-vs-real8 spread of a row
    ! measures one step of upstream's single precision, not two diverging
    ! trajectories
    do iz = 1, 7
      do ir = 1, 3
        call do_advance(8, 0, 1, 900, 0.875 + 1.375*real(ir), 3.75 + 0.625*real(ir), zs(iz), 0.25, -0.1875, 0.5, 0.37)
        call do_advance(8, 900, 1, 900, 1.25 + 1.25*real(ir), 4.125 + 0.5*real(ir), zs(iz), -0.375, 0.3125, -0.1875, 0.37)
      end do
    end do
    ! 9: south-polar grid below grid y = 2.5 (lat -90..-84)
    call set_case(9, 1, 900, 1, 1, 1, 0, 0, 0, 1, 0, 1, 999999., 2.5, 0., 0., -90.0, 1.0, 10800, 0)
    do iz = 1, 7
      do ir = 1, 3
        call do_advance(9, 0, 1, 900, 0.875 + 1.375*real(ir), 0.375 + 0.625*real(ir), zs(iz), 0.25, -0.1875, 0.5, 0.37)
        call do_advance(9, 900, 1, 900, 1.25 + 1.25*real(ir), 0.25 + 0.5*real(ir), zs(iz), -0.375, 0.3125, -0.1875, 0.37)
      end do
    end do
    ! 10: global in x: wrap at the east edge; and crossing the domain edges
    call set_case(10, 1, 900, 1, 1, 1, 0, 0, 0, 1, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, 10800, 0)
    do iz = 1, 7
      call do_advance(10, 0, 3, 900, 5.99951171875, 3.25, zs(iz), 0.25, -0.1875, 0.5, 0.37)
      call do_advance(10, 0, 2, 900, 2.625, 5.99969482421875, zs(iz), 0.25, -0.1875, 0.5, 0.37)
      call do_advance(10, 0, 2, 900, 2.625, 0.000396728515625, zs(iz), 0.25, -0.1875, 0.5, 0.37)
      ! southward wind at x = 0.3: crosses the south edge (pole crossing)
      call do_advance(10, 0, 2, 900, 0.3125, 0.000396728515625, zs(iz), 0.25, -0.1875, 0.5, 0.37)
    end do
    ! just below the model top: the zt >= height(nz) cap
    call do_advance(10, 0, 2, 900, 2.625, 3.25, 15999.9375, 0.25, -0.1875, 0.5, 0.37)
    ! ran3 = 0.0005645 selects nrand = 565, where rannumb = +2.5 (an upward kick)
    call do_advance(10, 0, 2, 900, 2.625, 3.25, 15999.9375, 0.25, -0.1875, 0.5, 0.0005645006)
    ! 11: non-global: leaving the domain sets nstop = 3
    call set_case(11, 1, 900, 1, 1, 1, 0, 0, 0, 0, 0, 0, 999999., -999999., 0., 0., 1.0, 1.0, 10800, 0)
    do iz = 1, 7
      call do_advance(11, 0, 2, 900, 5.99951171875, 3.25, zs(iz), 0.25, -0.1875, 0.5, 0.37)
    end do
    ! 12: skewed CBL with -h/L just above 5, and ctl small enough that the
    !     mintime floor on the time step binds
    ctl_case = 0.1
    call set_case(12, 1, 900, 1, 1, 1, 1, 0, 0, 0, 0, 0, 999999., -999999., -0.006, 1.1, 1.0, 1.0, 10800, 0)
    do iz = 1, 3
      call do_advance(12, 0, 3, 20, 3.125, 1.375, zs(iz), 0.125, 0.1875, 0.3125, 0.37)
    end do
    ctl_case = 5.
  end subroutine run_cases

end program flexpart_reference_advance
