! SPDX-License-Identifier: GPL-3.0
!
! Stage "output" code-to-code reference driver for `changi::flexpart`:
! concentration gridding (conccalc: uniform kernel on the output grids,
! parabolic kernel at receptors), the dry-deposition gridding kernel
! (drydepokernel, drydepokernel_nest), the plume-trajectory statistics
! (plumetraj with clustering, centerofmass and mean_mod's `mean`) and the
! particle-dump averaging (partpos_average).
!
! Every routine called here is UPSTREAM FLEXPART v10.4 @ 3d7eebf, compiled
! verbatim from upstream_source/FLEXPART/src by dev/build_reference_output.sh.
! Nothing below reimplements physics: the driver writes synthetic particles,
! output grids and meteorological fields straight into com_mod (no GRIB, no
! NetCDF) and prints what upstream returns.
!
! par_mod.f90 VARIANTS. par_mod.f90 is FLEXPART's user-edited configuration
! file, and three of its compile-time PARAMETERS gate branches of the routines
! under test: lusekerneloutput (kernel on/off), lparticlecountoutput (particle
! counts instead of mass) and the array bounds maxspec / maxageclass /
! nclassunc (the shipped values, 1/1/1, allow only one species, one age class
! and one uncertainty class). The build script therefore compiles this driver
! four times per precision:
!   V0  par_mod.f90 VERBATIM (as shipped);
!   V1  a COPY with maxspec=2, maxageclass=3, nclassunc=2 (kernel on);
!   V2  as V1 and lusekerneloutput=.false., lparticlecountoutput=.true.
!   V3  as V1 and lparticlecountoutput=.true. (kernel still on; conccalc only)
! Only those parameter lines differ (sed in the build script); every routine
! under test is the upstream file, untouched. The nested OUTPUT grids
! (griduncn, drygriduncn) are allocatable in unc_mod and sized by the run-time
! numxgridn/numygridn, so no maxnests change is needed for them.
!
! Synthetic meteorology: every field is an exact dyadic function of integer
! indices, value = base + scale * mod(a*ix + b*jy + c*k + d*m, q), so it is the
! same number in real(4), real(8) and the Rust test, which rebuilds it from the
! same formula (the `setup.met` row echoes nz and the level heights, and
! `setup.metcheck` rows echo sample values so a formula mismatch is caught).
!
! Row format, one row per CALL (or per non-zero grid cell for the gridding
! routines): function,a1;a2;...,o1;o2;...   real(4) builds print 9 significant
! digits (parse as f32); rows carrying real(kind=dp) particle positions are
! printed with 17 digits (rowvd) and are parsed as f64.
program flexpart_reference_output

  use par_mod
  use com_mod
  use unc_mod
  use outg_mod
  use point_mod
  use mean_mod
  implicit none

  integer :: variant

  if (maxspec == 1) then
    variant = 0
  else if (lusekerneloutput .and. .not. lparticlecountoutput) then
    variant = 1
  else if (.not. lusekerneloutput) then
    variant = 2
  else
    variant = 3
  end if

  write(*,'(A)') '# FLEXPART stage "output" reference, generated by dev/flexpart_reference_output.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_output.sh'
  write(*,'(A)') 'function,args,outputs'

  call rowi('setup.variant', (/ variant, maxspec, maxageclass, nclassunc, &
       merge(1,0,lusekerneloutput), merge(1,0,lparticlecountoutput) /), 6)

  ipout = 3          ! so com_mod_allocate_part also allocates part_av_*
  call com_mod_allocate_part(maxpart)
  allocate(xscav_frac1(maxpart, maxspec))
  call setup_met()

  call emit_conccalc(variant)
  if (variant /= 3) call emit_drydepokernel(variant)
  if (variant == 0) then
    call emit_mean()
    call emit_centerofmass()
    call emit_clustering()
    call emit_plumetraj()
    call emit_partpos_average()
  end if

contains

  ! ------------------------------------------------------------------------
  ! Helpers copied from flexpart_reference_physics.f90.
  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=8192) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowv

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=8192) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowvd

  ! Integer-only setup row (args only, one dummy output).
  subroutine rowi(name, iargs, nargs)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, iargs(nargs)
    real :: a(nargs), o(1)
    a = real(iargs)
    o(1) = 0.
    call rowv(name, a, nargs, o, 1)
  end subroutine rowi

  ! ------------------------------------------------------------------------
  ! Synthetic meteorology (see the header). Index conventions as upstream:
  ! ix 0:nxmax-1, jy 0:nymax-1, level k 1:nz, memory slot m 1:2.
  integer function nf(ix, jy, k, m, a, b, c, d, q)
    integer, intent(in) :: ix, jy, k, m, a, b, c, d, q
    nf = mod(a*ix + b*jy + c*k + d*m, q)
  end function nf

  subroutine setup_met()
    integer :: ix, jy, k, m
    real :: o(1)
    nz = 8
    height(1:8) = (/ 0., 50., 150., 400., 900., 1800., 3500., 8000. /)
    do m = 1, 2
      do k = 1, nz
        do jy = 0, nymax-1
          do ix = 0, nxmax-1
            rho(ix,jy,k,m) = 1.25 - 0.0625*real(k) + real(nf(ix,jy,k,m,37,101,53,17,97))/256.
            pv(ix,jy,k,m)  = -6.0 + real(nf(ix,jy,k,m,41,13,29,7,97))/8.
            qv(ix,jy,k,m)  = real(nf(ix,jy,k,m,11,61,3,23,89))/4096.
            tt(ix,jy,k,m)  = 300. - 4.*real(k) + real(nf(ix,jy,k,m,19,7,31,5,83))/32.
            uu(ix,jy,k,m)  = -8. + real(nf(ix,jy,k,m,23,17,11,3,101))/8.
            vv(ix,jy,k,m)  = 6. - real(nf(ix,jy,k,m,13,29,37,41,103))/16.
          end do
        end do
      end do
      do jy = 0, nymax-1
        do ix = 0, nxmax-1
          tropopause(ix,jy,1,m) = 2000. + 96.*real(nf(ix,jy,0,m,7,19,0,13,79))
          hmix(ix,jy,1,m) = 150. + 16.*real(nf(ix,jy,0,m,31,3,0,11,73))
        end do
      end do
    end do
    do jy = 0, nymax-1
      do ix = 0, nxmax-1
        oro(ix,jy) = 8.*real(nf(ix,jy,0,0,29,43,0,0,89))
      end do
    end do
    o(1) = 0.
    call rowv('setup.met', (/ real(nz), height(1:8) /), 9, o, 1)
    ! sample values: ix, jy, k, m -> rho, pv, qv, tt, uu, vv, tropopause, hmix, oro
    call metcheck(0, 0, 1, 1)
    call metcheck(17, 33, 4, 2)
    call metcheck(360, 180, 8, 1)
    call metcheck(123, 77, 6, 2)
  end subroutine setup_met

  subroutine metcheck(ix, jy, k, m)
    integer, intent(in) :: ix, jy, k, m
    call rowv('setup.metcheck', (/ real(ix), real(jy), real(k), real(m) /), 4, &
         (/ rho(ix,jy,k,m), pv(ix,jy,k,m), qv(ix,jy,k,m), tt(ix,jy,k,m), &
            uu(ix,jy,k,m), vv(ix,jy,k,m), tropopause(ix,jy,1,m), hmix(ix,jy,1,m), &
            oro(ix,jy) /), 9)
  end subroutine metcheck

  ! ------------------------------------------------------------------------
  ! conccalc.
  !
  ! One particle set (setup.particle rows) is gridded under several
  ! configurations of the com_mod switches (setup.conccalc rows). After each
  ! configuration every NON-ZERO cell of gridunc (conccalc.grid) and griduncn
  ! (conccalc.gridn) is printed, and every creceptor value (conccalc.receptor).
  ! The Rust test checks the cell values row by row AND that the port's set of
  ! non-zero cells is the fixture's set.
  !
  ! The sweep straddles: itra1 /= itime (skipped); every age class boundary
  ! (lage = 7200, 21600, 999999999 when maxageclass = 3); the 10800 s
  ! kernel threshold (10799/10800); backward ages (itramem > itra1, abs());
  ! positions west/south of the grid (negative xl, the int()-1 correction),
  ! inside the half-cell boundary strips, east/north of it, ddx above and below
  ! one half; heights in each of the 3 output levels and above the top;
  ! ind_samp 0 and -1 with memind(2) = 1 and 2 (upstream reads the first
  ! density corner from memind(2) and the other three from slot 2); the
  ! north-pole jyp >= nymax clamp (two particles at jy = 179, 180); the
  ! east/north half-cell strips (two particles); negative
  ! xscav_frac1 (max(.,0)); DRYBKDEP and WETBKDEP; ioutputforeachrelease 0/1;
  ! mdomainfill 1; nested_output 0/1; weights 1, 0.5 and 0.7 (0.7 makes the
  ! mother/nest product-order difference visible); a repeated call
  ! (accumulation); and, at the receptors, the hzmax / hxmax / hymax caps and
  ! each early exit (zd > 1, xd^2 > 1, yd^2 > 1, r2 >= 1).
  subroutine emit_conccalc(variant)
    integer, intent(in) :: variant
    integer, parameter :: np = 66, nptot = 70
    double precision :: xs(12), ys(11)
    real :: zs(8)
    integer :: ages(11), i, itime, n, ncfg, icfg, cid, age, ix, jy, kz, ks, kp, ncl, nag
    ! config: ind_samp, memind2, bk(0 none 1 dry 2 wet), foreach, domainfill,
    !         nested, weight*10, polar shift, repeat
    integer :: cfg(9, 8)
    real :: o(1)
    double precision :: pa(13), po(1)

    ! Positions are >= 0 in met grid units (the density interpolation of
    ! ind_samp = -1 indexes rho(int(xtra1),...), which would read outside the
    ! array for xtra1 <= -1); the negative shifts below put the westmost and
    ! southmost particles at negative output-grid coordinates instead.
    xs = (/ 0.13d0, 0.66d0, 1.43d0, 2.58d0, 3.91d0, 5.12d0, 6.74d0, 8.29d0, &
            10.63d0, 12.85d0, 14.47d0, 16.2d0 /)
    ys = (/ 0.21d0, 0.88d0, 1.71d0, 2.46d0, 3.33d0, 4.62d0, 5.9d0, 7.38d0, &
            9.12d0, 10.45d0, 11.8d0 /)
    zs = (/ 4., 22., 61., 140., 480., 1250., 2600., 6200. /)
    ages = (/ 0, 1800, 7199, 7200, 10799, 10800, 21599, 21600, 45000, 140000, 600000 /)

    itime = 86400
    dx = 0.5
    dy = 0.4
    nspec = maxspec
    maxpointspec_act = 3
    nageclass = maxageclass
    if (maxageclass == 3) then
      lage(1:3) = (/ 7200, 21600, 999999999 /)
    else
      lage(1) = 999999999
    end if
    numzgrid = 3
    allocate(outheight(numzgrid))
    outheight = (/ 100., 500., 2000. /)
    numxgrid = 9
    numygrid = 7
    numxgridn = 12
    numygridn = 10
    dxoutn = 0.3
    dyoutn = 0.25
    xoutshiftn = -0.4
    youtshiftn = 0.35
    allocate(gridunc(0:numxgrid-1,0:numygrid-1,numzgrid,maxspec, &
         maxpointspec_act,nclassunc,maxageclass))
    allocate(griduncn(0:numxgridn-1,0:numygridn-1,numzgrid,maxspec, &
         maxpointspec_act,nclassunc,maxageclass))

    numpart = nptot
    do i = 1, np
      xtra1(i) = xs(mod(i*5,12)+1)
      ytra1(i) = ys(mod(i*7,11)+1)
      ztra1(i) = zs(mod(i*3,8)+1)
      age = ages(mod(i*13,11)+1)
      itra1(i) = itime
      if (mod(i,13) == 0) itra1(i) = itime + 900
      if (mod(i,4) == 1) then
        itramem(i) = itime + age
      else
        itramem(i) = itime - age
      end if
      npoint(i) = mod(i,3) + 1
      nclass(i) = mod(i,nclassunc) + 1
      xmass1(i,1) = 0.5 + 0.13*real(i)
      xscav_frac1(i,1) = -0.2 + 0.05*real(mod(i,9))
      if (maxspec >= 2) then
        xmass1(i,2) = 2.0 - 0.017*real(i)
        xscav_frac1(i,2) = 0.3 + 0.01*real(i)
      end if
    end do
    ! two particles by the north pole (jy = 180 -> jyp clamped; jy = 179)
    xtra1(67) = 4.37d0
    ytra1(67) = 180.3d0
    xtra1(68) = 6.81d0
    ytra1(68) = 179.62d0
    ztra1(67) = 22.
    ztra1(68) = 140.
    do i = 67, 68
      itra1(i) = itime
      itramem(i) = itime - 45000
      npoint(i) = i - 65
      nclass(i) = mod(i,nclassunc) + 1
      xmass1(i,1) = 3.1 + 0.2*real(i-67)
      xscav_frac1(i,1) = 0.45
      if (maxspec >= 2) then
        xmass1(i,2) = 0.9
        xscav_frac1(i,2) = -0.1
      end if
    end do
    ! two particles inside the east / north half-cell boundary strips of the
    ! mother grid (xl = 7.55 > numxgrid-1.5; yl = 5.55 > numygrid-1.5)
    xtra1(69) = 13.28d0
    ytra1(69) = 4.4d0
    xtra1(70) = 6.1d0
    ytra1(70) = 9.2d0
    ztra1(69) = 61.
    ztra1(70) = 480.
    do i = 69, 70
      itra1(i) = itime
      itramem(i) = itime - 30000
      npoint(i) = 1
      nclass(i) = 1
      xmass1(i,1) = 1.7
      xscav_frac1(i,1) = 0.8
      if (maxspec >= 2) then
        xmass1(i,2) = 0.35
        xscav_frac1(i,2) = 0.6
      end if
    end do
    do i = 1, nptot
      pa(1) = dble(i)
      pa(2) = dble(itra1(i))
      pa(3) = dble(itramem(i))
      pa(4) = xtra1(i)
      pa(5) = ytra1(i)
      pa(6) = dble(ztra1(i))
      pa(7) = dble(npoint(i))
      pa(8) = dble(nclass(i))
      pa(9) = dble(xmass1(i,1))
      pa(10) = dble(xscav_frac1(i,1))
      pa(11) = dble(xmass1(i,min(2,maxspec)))
      pa(12) = dble(xscav_frac1(i,min(2,maxspec)))
      pa(13) = dble(itime)
      po(1) = 0d0
      call rowvd('setup.particle', pa, 13, po, 1)
    end do

    ! receptors: three next to low particles of different ages, one far away
    numreceptor = 4
    xreceptor(1:4) = (/ 2.61, 6.69, 10.9, 30.0 /)
    yreceptor(1:4) = (/ 1.66, 4.71, 7.6, 30.0 /)
    receptorarea(1:4) = (/ 1.1e9, 2.3e9, 0.7e9, 1.9e9 /)

    o(1) = 0.
    call rowv('setup.grid', (/ real(numxgrid), real(numygrid), real(numzgrid), &
         outheight(1:3), real(numxgridn), real(numygridn), dxoutn, dyoutn, &
         xoutshiftn, youtshiftn, dx, dy, real(nageclass), real(lage(1:nageclass)) /), &
         15 + nageclass, o, 1)
    do n = 1, numreceptor
      call rowv('setup.receptor', (/ real(n), xreceptor(n), yreceptor(n), &
           receptorarea(n) /), 4, o, 1)
    end do

    if (variant == 3) then
      ncfg = 2
      cfg(:,1) = (/  0, 2, 0, 1, 0, 1, 10, 0, 0 /)
      cfg(:,2) = (/ -1, 1, 0, 1, 0, 1,  5, 0, 0 /)
    else if (variant == 2) then
      ncfg = 3
      cfg(:,1) = (/  0, 2, 0, 1, 0, 1, 10, 0, 0 /)
      cfg(:,2) = (/ -1, 2, 1, 0, 0, 1,  7, 0, 0 /)
      cfg(:,3) = (/  0, 2, 0, 1, 0, 0,  5, 1, 0 /)
    else
      ncfg = 7
      cfg(:,1) = (/  0, 2, 0, 0, 0, 1, 10, 0, 0 /)
      cfg(:,2) = (/ -1, 2, 0, 1, 0, 1,  5, 0, 0 /)
      cfg(:,3) = (/ -1, 1, 1, 1, 1, 1,  7, 0, 0 /)
      cfg(:,4) = (/  0, 2, 2, 1, 0, 1,  7, 0, 0 /)
      cfg(:,5) = (/ -1, 1, 0, 1, 0, 0,  7, 1, 0 /)
      cfg(:,6) = (/  0, 2, 0, 1, 0, 1,  5, 0, 1 /)
      cfg(:,7) = (/ -1, 2, 1, 1, 0, 1, 10, 1, 0 /)
    end if

    memind(1) = 1
    memind(2) = 2
    do icfg = 1, ncfg
      ind_samp = cfg(1,icfg)
      memind(2) = cfg(2,icfg)
      memind(1) = 3 - memind(2)
      DRYBKDEP = (cfg(3,icfg) == 1)
      WETBKDEP = (cfg(3,icfg) == 2)
      ioutputforeachrelease = cfg(4,icfg)
      mdomainfill = cfg(5,icfg)
      nested_output = cfg(6,icfg)
      dxout = 0.8
      dyout = 0.6
      xoutshift = -0.6
      if (cfg(8,icfg) == 1) then
        youtshift = -71.5
      else
        youtshift = -0.35
      end if
      cid = 100*variant + icfg
      call rowv('setup.conccalc', (/ real(cid), real(ind_samp), real(memind(2)), &
           real(cfg(3,icfg)), real(ioutputforeachrelease), real(mdomainfill), &
           real(nested_output), real(cfg(7,icfg))/10., dxout, dyout, xoutshift, &
           youtshift, real(cfg(9,icfg)) /), 13, o, 1)
      gridunc = 0.
      griduncn = 0.
      creceptor = 0.
      call conccalc(itime, real(cfg(7,icfg))/10.)
      if (cfg(9,icfg) == 1) call conccalc(itime, 1.0)
      do nag = 1, nageclass
        do ncl = 1, nclassunc
          do kp = 1, maxpointspec_act
            do ks = 1, nspec
              do kz = 1, numzgrid
                do jy = 0, numygrid-1
                  do ix = 0, numxgrid-1
                    if (gridunc(ix,jy,kz,ks,kp,ncl,nag) /= 0.) then
                      call rowv('conccalc.grid', (/ real(cid), real(ix), real(jy), &
                           real(kz), real(ks), real(kp), real(ncl), real(nag) /), 8, &
                           (/ gridunc(ix,jy,kz,ks,kp,ncl,nag) /), 1)
                    end if
                  end do
                end do
                do jy = 0, numygridn-1
                  do ix = 0, numxgridn-1
                    if (griduncn(ix,jy,kz,ks,kp,ncl,nag) /= 0.) then
                      call rowv('conccalc.gridn', (/ real(cid), real(ix), real(jy), &
                           real(kz), real(ks), real(kp), real(ncl), real(nag) /), 8, &
                           (/ griduncn(ix,jy,kz,ks,kp,ncl,nag) /), 1)
                    end if
                  end do
                end do
              end do
            end do
          end do
        end do
      end do
      do n = 1, numreceptor
        do ks = 1, nspec
          call rowv('conccalc.receptor', (/ real(cid), real(n), real(ks) /), 3, &
               (/ creceptor(n,ks) /), 1)
        end do
      end do
    end do
    deallocate(gridunc, griduncn, outheight)
  end subroutine emit_conccalc

  ! ------------------------------------------------------------------------
  ! drydepokernel / drydepokernel_nest.
  !
  ! One call row per (position, deposit, geometry); both grids are zeroed before
  ! every call, so each printed cell is that call's contribution alone. Then
  ! every non-zero cell of drygridunc (drydepokernel.cell) and drygriduncn
  ! (drydepokernel_nest.cell).
  !
  ! Geometry 1 is a general one; geometry 2 makes xl = x exactly (dx = dxout,
  ! zero shift) so that ddx = 0.5 exactly (the tie takes the ELSE branch) and
  ! negative x in (-1, 0) (int() truncates toward zero, ix = 0) are hit
  ! exactly. The deposits include a zero, a negative and DRYDEPSPEC false.
  subroutine emit_drydepokernel(variant)
    integer, intent(in) :: variant
    real :: xg1(9), yg1(8), xg2(5), yg2(4), deps(2,4), x, y, o(1)
    logical :: specs(2,3)
    integer :: icall, cid, ig, ix, jy, ks, kp, nunc, nage, id, is, i, j, ni, nj
    real(dep_prec) :: deposit(maxspec)

    xg1 = (/ -2.13, -0.61, -0.29, 0.23, 1.37, 4.41, 7.96, 13.62, 15.27 /)
    yg1 = (/ -1.07, -0.33, 0.41, 2.29, 5.58, 9.17, 10.36, 11.9 /)
    xg2 = (/ -0.25, 0.25, 2.5, 3.0, 8.75 /)
    yg2 = (/ -0.75, 1.5, 4.25, 6.5 /)
    deps(:,1) = (/ 0.37, 1.4 /)
    deps(:,2) = (/ -0.12, 0.0 /)
    deps(:,3) = (/ 2.5e-3, 7.1 /)
    deps(:,4) = (/ 0.0, 0.0 /)
    specs(:,1) = (/ .true., .true. /)
    specs(:,2) = (/ .true., .false. /)
    specs(:,3) = (/ .false., .true. /)

    nspec = maxspec
    maxpointspec_act = 3
    numxgrid = 9
    numygrid = 7
    numxgridn = 12
    numygridn = 10
    allocate(drygridunc(0:numxgrid-1,0:numygrid-1,maxspec,maxpointspec_act, &
         nclassunc,maxageclass))
    allocate(drygriduncn(0:numxgridn-1,0:numygridn-1,maxspec,maxpointspec_act, &
         nclassunc,maxageclass))
    o(1) = 0.

    icall = 0
    do ig = 1, 2
      if (ig == 1) then
        dx = 0.5
        dy = 0.4
        dxout = 0.8
        dyout = 0.6
        xoutshift = 0.25
        youtshift = 0.1
        dxoutn = 0.3
        dyoutn = 0.25
        xoutshiftn = -0.4
        youtshiftn = 0.35
        ni = 9
        nj = 8
      else
        dx = 0.5
        dy = 0.5
        dxout = 0.5
        dyout = 0.5
        xoutshift = 0.
        youtshift = 0.
        dxoutn = 0.5
        dyoutn = 0.5
        xoutshiftn = 0.
        youtshiftn = 0.
        ni = 5
        nj = 4
      end if
      do i = 1, ni
        do j = 1, nj
          if (ig == 1) then
            x = xg1(i)
            y = yg1(j)
          else
            x = xg2(i)
            y = yg2(j)
          end if
          icall = icall + 1
          cid = 1000*variant + icall
          id = mod(icall,4) + 1
          is = mod(icall,3) + 1
          deposit(1) = deps(1,id)
          if (maxspec >= 2) deposit(2) = deps(2,id)
          DRYDEPSPEC(1) = specs(1,is)
          if (maxspec >= 2) DRYDEPSPEC(2) = specs(2,is)
          nunc = mod(icall,nclassunc) + 1
          nage = mod(icall,maxageclass) + 1
          kp = mod(icall,maxpointspec_act) + 1
          call rowv('setup.drydepokernel', (/ real(cid), x, y, &
               real(deposit(1)), real(deposit(min(2,maxspec))), merge(1.,0.,specs(1,is)), &
               merge(1.,0.,specs(2,is)), real(nunc), real(nage), real(kp), &
               dx, dy, dxout, dyout, xoutshift, youtshift, dxoutn, dyoutn, &
               xoutshiftn, youtshiftn, real(numxgrid), real(numygrid), &
               real(numxgridn), real(numygridn) /), 24, o, 1)
          drygridunc = 0.
          drygriduncn = 0.
          call drydepokernel(nunc, deposit, x, y, nage, kp)
          call drydepokernel_nest(nunc, deposit, x, y, nage, kp)
          do ks = 1, nspec
            do jy = 0, numygrid-1
              do ix = 0, numxgrid-1
                if (drygridunc(ix,jy,ks,kp,nunc,nage) /= 0.) then
                  call rowv('drydepokernel.cell', (/ real(cid), real(ix), real(jy), &
                       real(ks) /), 4, (/ real(drygridunc(ix,jy,ks,kp,nunc,nage)) /), 1)
                end if
              end do
            end do
            do jy = 0, numygridn-1
              do ix = 0, numxgridn-1
                if (drygriduncn(ix,jy,ks,kp,nunc,nage) /= 0.) then
                  call rowv('drydepokernel_nest.cell', (/ real(cid), real(ix), &
                       real(jy), real(ks) /), 4, &
                       (/ real(drygriduncn(ix,jy,ks,kp,nunc,nage)) /), 1)
                end if
              end do
            end do
          end do
        end do
      end do
    end do
    deallocate(drygridunc, drygriduncn)
  end subroutine emit_drydepokernel

  ! ------------------------------------------------------------------------
  ! mean_mod: mean (resolves to mean_sp in the real(4) build, mean_dp in the
  ! real(8) build -- the same algorithm). Sets include n = 1 (number-1 = 0,
  ! xaux exactly 0), a constant set (xaux at rounding level: the eps = 1e-30
  ! guard), and a large-offset set (cancellation in xq - xl^2/n).
  subroutine emit_mean()
    real :: v(12), xm, xs
    integer :: n, iset, i
    do iset = 1, 6
      select case (iset)
      case (1)
        n = 1
        v(1) = 123.4
      case (2)
        n = 2
        v(1:2) = (/ 3.5, -1.25 /)
      case (3)
        n = 7
        v(1:7) = (/ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 /)
      case (4)
        n = 12
        do i = 1, 12
          v(i) = 250. + 37.*real(mod(i*5,7)) - 1.3*real(i)
        end do
      case (5)
        n = 9
        do i = 1, 9
          v(i) = 5000. + 0.01*real(i)
        end do
      case (6)
        n = 4
        v(1:4) = (/ 0., 0., 0., 0. /)
      end select
      xm = -999.
      xs = -999.
      call mean(v(1:n), xm, xs, n)
      call rowv('mean', (/ real(n), v(1:n) /), n+1, (/ xm, xs /), 2)
    end do
  end subroutine emit_mean

  ! ------------------------------------------------------------------------
  ! centerofmass: lon/lat sets including n = 1, the date line, both
  ! hemispheres and a near-polar set.
  subroutine emit_centerofmass()
    real :: xl(8), yl(8), xc, yc
    integer :: n, iset
    do iset = 1, 5
      select case (iset)
      case (1)
        n = 1
        xl(1) = 12.5
        yl(1) = 47.25
      case (2)
        n = 4
        xl(1:4) = (/ -10.3, 4.7, 21.9, 8.2 /)
        yl(1:4) = (/ 51.2, 44.6, 60.1, 38.8 /)
      case (3)
        n = 5
        xl(1:5) = (/ 179.2, -179.6, 178.8, -178.9, 179.9 /)
        yl(1:5) = (/ -12.3, -10.9, -14.1, -11.7, -13.0 /)
      case (4)
        n = 6
        xl(1:6) = (/ -60.4, -58.1, -61.9, -59.3, -57.7, -60.0 /)
        yl(1:6) = (/ -3.2, 2.9, -0.4, 4.1, -5.6, 0.3 /)
      case (5)
        n = 8
        xl(1:8) = (/ 0., 45., 90., 135., 180., -135., -90., -45. /)
        yl(1:8) = (/ 88.9, 89.3, 88.7, 89.1, 89.6, 88.8, 89.0, 89.4 /)
      end select
      call centerofmass(xl(1:n), yl(1:n), n, xc, yc)
      call rowv('centerofmass', (/ real(n), xl(1:n), yl(1:n) /), 2*n+1, (/ xc, yc /), 2)
    end do
  end subroutine emit_centerofmass

  ! ------------------------------------------------------------------------
  ! clustering. Outputs: the caller's xl, yl AFTER the call (upstream converts
  ! them to radians and back in place), then xclust(5), yclust(5), zclust(5),
  ! fclust(5), rms, rmsclust(5), zrms. Outputs are preset to -999 so that the
  ! n < ncluster early return (outputs untouched) is visible.
  subroutine emit_clustering()
    real :: xl(40), yl(40), zl(40), xin(40), yin(40)
    real :: xclust(ncluster), yclust(ncluster), zclust(ncluster), fclust(ncluster)
    real :: rms, rmsclust(ncluster), zrms
    real :: o(2*40 + 6*ncluster + 2)
    integer :: n, iset, i, no
    do iset = 1, 7
      select case (iset)
      case (1)
        n = 3
        xl(1:3) = (/ 1., 2., 3. /)
        yl(1:3) = (/ 40., 41., 42. /)
        zl(1:3) = (/ 100., 200., 300. /)
      case (2)
        n = 5
        xl(1:5) = (/ -20.5, 3.3, 47.1, 12.9, -3.8 /)
        yl(1:5) = (/ 10.2, 55.5, -8.4, 31.7, 64.0 /)
        zl(1:5) = (/ 150., 2400., 75., 980., 3300. /)
      case (3)
        n = 12
        do i = 1, 12
          xl(i) = 10. + 4.*real(mod(i,3))
          yl(i) = 45. + 3.*real(mod(i,4))
          zl(i) = 100.*real(i)
        end do
      case (4)
        n = 40
        do i = 1, 40
          select case (mod(i,3))
          case (0)
            xl(i) = 178.6 + 0.37*real(mod(i*7,9))
            if (xl(i) > 180.) xl(i) = xl(i) - 360.
            yl(i) = -20. + 0.53*real(mod(i*5,7))
          case (1)
            xl(i) = 15. + 1.1*real(mod(i*3,8))
            yl(i) = 52. + 0.8*real(mod(i*2,5))
          case (2)
            xl(i) = -75. + 2.3*real(mod(i,6))
            yl(i) = 12. + 1.7*real(mod(i*4,7))
          end select
          zl(i) = 50. + 97.*real(mod(i*11,23))
        end do
      case (5)
        n = 20
        do i = 1, 20
          xl(i) = 7.25
          yl(i) = -33.5
          zl(i) = 200. + 10.*real(i)
        end do
      case (6)
        n = 25
        do i = 1, 25
          xl(i) = -5. + 0.9*real(i) + 3.*real(mod(i,2))
          yl(i) = 30. + 0.45*real(i) - 2.*real(mod(i,3))
          zl(i) = 1000.
        end do
      case (7)
        ! In real(8) four of these (15.14, 30.92, 31.33, 31.74) do not
        ! survive upstream's in-place x*pi180/pi180 round trip unchanged.
        n = 30
        do i = 1, 30
          xl(i) = -15. + 1.37*real(i)
          yl(i) = 20. + 0.91*real(i) - 0.5*real(mod(i,4))
          zl(i) = 300. + 50.*real(mod(i,5))
        end do
      end select
      xin(1:n) = xl(1:n)
      yin(1:n) = yl(1:n)
      xclust = -999.
      yclust = -999.
      zclust = -999.
      fclust = -999.
      rmsclust = -999.
      rms = -999.
      zrms = -999.
      call clustering(xl, yl, zl, n, xclust, yclust, zclust, fclust, rms, &
           rmsclust, zrms)
      no = 0
      o(no+1:no+n) = xl(1:n); no = no + n
      o(no+1:no+n) = yl(1:n); no = no + n
      o(no+1:no+ncluster) = xclust; no = no + ncluster
      o(no+1:no+ncluster) = yclust; no = no + ncluster
      o(no+1:no+ncluster) = zclust; no = no + ncluster
      o(no+1:no+ncluster) = fclust; no = no + ncluster
      o(no+1) = rms; no = no + 1
      o(no+1:no+ncluster) = rmsclust; no = no + ncluster
      o(no+1) = zrms; no = no + 1
      call rowv('clustering', (/ real(n), xin(1:n), yin(1:n), zl(1:n) /), 3*n+1, &
           o(1:no), no)
    end do
  end subroutine emit_clustering

  ! ------------------------------------------------------------------------
  ! plumetraj. Upstream's only output is the formatted record it writes to
  ! unit unitouttraj (96). The driver attaches that unit to a scratch file,
  ! reads each record back field by field with the SAME edit descriptors, and
  ! prints the values (plumetraj.out, double precision); a field upstream
  ! printed as asterisks is printed as NaN. These values are therefore exact
  ! only to the precision of upstream's own format (e.g. f8.1); the Rust test
  ! checks the port against them to half a unit of the last printed digit.
  !
  ! Release points: 1 -- 40 particles in three blobs; 2 -- 3 particles
  ! (n < ncluster: clustering returns at once and upstream writes cluster
  ! fields it never assigned); 3 -- released too long ago (|ireleasestart -
  ! itime| > lage(nageclass): skipped); 4 -- exactly ncluster particles;
  ! 5 -- no particles (no record); 6 -- |ireleasestart - itime| equal to
  ! lage(nageclass) exactly (kept: the test is a strict >). (start+end)/2 is integer division of a
  ! negative odd sum for point 4. Particles straddle both hemispheres (the
  ! PV sign test), pvi = +-2, the tropopause and the mixing height.
  subroutine emit_plumetraj()
    integer, parameter :: npl = 67
    real :: zs2(7)
    integer :: i, k, ic, itime, ios, ifield, ipos, w(41), d(41)
    double precision :: pa(13), po(1), vals(41)
    character(len=400) :: line
    character(len=16) :: fmtf
    real :: o(1)

    zs2 = (/ 12., 85., 340., 760., 1500., 2900., 5200. /)
    xlon0 = -12.0
    ylat0 = -6.0
    dx = 0.5
    dy = 0.4
    nageclass = maxageclass
    lage(nageclass) = 200000
    numpoint = 6
    allocate(ireleasestart(numpoint), ireleaseend(numpoint))
    memtime(1) = 0
    memtime(2) = 10800

    ! field widths / decimals of the record:
    ! i5,i8,2f9.4,4f8.1,f8.2,4f8.1,3f6.1,5(2f8.3,f7.0,f6.1,f8.1)
    w(1) = 5;  d(1) = -1
    w(2) = 8;  d(2) = -1
    w(3:4) = 9;   d(3:4) = 4
    w(5:8) = 8;   d(5:8) = 1
    w(9) = 8;     d(9) = 2
    w(10:13) = 8; d(10:13) = 1
    w(14:16) = 6; d(14:16) = 1
    do k = 0, 4
      w(17+5*k) = 8; d(17+5*k) = 3
      w(18+5*k) = 8; d(18+5*k) = 3
      w(19+5*k) = 7; d(19+5*k) = 0
      w(20+5*k) = 6; d(20+5*k) = 1
      w(21+5*k) = 8; d(21+5*k) = 1
    end do

    open(unitouttraj, status='scratch', form='formatted')
    do ic = 1, 2
      if (ic == 1) then
        itime = 3600
        memind(1) = 1
        memind(2) = 2
      else
        itime = 9000
        memind(1) = 2
        memind(2) = 1
      end if
      ireleasestart(1:6) = (/ itime-7200, itime-3600, itime-300000, itime-10800, itime-100, &
           itime-200000 /)
      ireleaseend(1:6) = ireleasestart(1:6) + (/ 3600, 0, 3600, 7201, 0, 50 /)
      numpart = npl
      do i = 1, npl
        if (i <= 40) then
          npoint(i) = 1
          select case (mod(i,3))
          case (0)
            xtra1(i) = 10.d0 + 0.37d0*dble(mod(i*7,9))
            ytra1(i) = 8.d0 + 0.53d0*dble(mod(i*5,7))
          case (1)
            xtra1(i) = 30.d0 + 0.61d0*dble(mod(i*3,8))
            ytra1(i) = 22.d0 + 0.29d0*dble(mod(i*2,5))
          case (2)
            xtra1(i) = 55.d0 + 0.83d0*dble(mod(i,6))
            ytra1(i) = 14.d0 + 0.47d0*dble(mod(i*4,7))
          end select
        else if (i <= 43) then
          npoint(i) = 2
          xtra1(i) = 20.3d0 + 1.7d0*dble(i-41)
          ytra1(i) = 3.1d0 + 2.3d0*dble(i-41)
        else if (i <= 49) then
          npoint(i) = 3
          xtra1(i) = 40.1d0 + 0.5d0*dble(i-44)
          ytra1(i) = 18.2d0
        else if (i <= 54) then
          npoint(i) = 4
          xtra1(i) = 5.4d0 + 6.1d0*dble(i-50)
          ytra1(i) = 2.2d0 + 5.3d0*dble(mod((i-50)*3,5))
        else if (i <= 60) then
          npoint(i) = 1        ! these six are at another time step
          xtra1(i) = 33.3d0
          ytra1(i) = 9.9d0
        else if (i <= 66) then
          npoint(i) = 6
          xtra1(i) = 70.2d0 + 0.9d0*dble(i-61)
          ytra1(i) = 25.4d0 - 1.3d0*dble(i-61)
        else
          ! On grid point (75, 17) = (25.5 E, 0.8 N) and on level 2 (50 m):
          ! pv(75,17,2,m) = -6 + (63 + 7m mod 97)/8, so the time-interpolated
          ! pvi is 2.17 (call 1) and 2.02 (call 2) -- just north of the
          ! equator and just above the 2 pvu threshold.
          npoint(i) = 1
          xtra1(i) = 75.d0
          ytra1(i) = 17.d0
        end if
        ztra1(i) = zs2(mod(i*3,7)+1)
        if (i == 67) ztra1(i) = 50.
        itra1(i) = itime
        if (i > 54 .and. i <= 60) itra1(i) = itime + 300
      end do
      do i = 1, npl
        pa(1) = dble(ic)
        pa(2) = dble(i)
        pa(3) = dble(itra1(i))
        pa(4) = xtra1(i)
        pa(5) = ytra1(i)
        pa(6) = dble(ztra1(i))
        pa(7) = dble(npoint(i))
        pa(8) = dble(itime)
        pa(9) = dble(memind(1))
        pa(10) = dble(memind(2))
        pa(11) = dble(memtime(1))
        pa(12) = dble(memtime(2))
        pa(13) = dble(lage(nageclass))
        po(1) = 0d0
        call rowvd('setup.plume_particle', pa, 13, po, 1)
      end do
      do k = 1, numpoint
        call rowi('setup.release', (/ ic, k, ireleasestart(k), ireleaseend(k) /), 4)
      end do
      call plumetraj(itime)
    end do
    o(1) = 0.
    call rowv('setup.plume_grid', (/ xlon0, ylat0, dx, dy /), 4, o, 1)

    rewind(unitouttraj)
    ic = 0
    do
      read(unitouttraj, '(A)', iostat=ios) line
      if (ios /= 0) exit
      ic = ic + 1
      ipos = 1
      do ifield = 1, 41
        if (ifield <= 2) then
          read(line(ipos:ipos+w(ifield)-1), *, iostat=ios) vals(ifield)
        else
          write(fmtf, '(A,I0,A,I0,A)') '(F', w(ifield), '.', d(ifield), ')'
          read(line(ipos:ipos+w(ifield)-1), fmtf, iostat=ios) vals(ifield)
        end if
        if (ios /= 0 .or. index(line(ipos:ipos+w(ifield)-1), '*') > 0) &
             vals(ifield) = transfer(-2251799813685248_8, 1d0)   ! a quiet NaN
        ipos = ipos + w(ifield)
      end do
      call rowvd('plumetraj.out', (/ dble(ic), vals(1), vals(2) /), 3, vals(3:41), 39)
    end do
    close(unitouttraj)
    deallocate(ireleasestart, ireleaseend)
  end subroutine emit_plumetraj

  ! ------------------------------------------------------------------------
  ! partpos_average. For each particle the part_av_* accumulators are zeroed,
  ! then the routine is called twice (itime 3600 with memind = (1,2), itime 9000
  ! with memind = (2,1)) and the accumulators are printed after each call.
  ! Positions include the north-pole clamp (jy = 180), a height exactly on a
  ! model level (dz1 = 0) and one just below the top level.
  subroutine emit_partpos_average()
    integer, parameter :: npp = 7
    double precision :: xp(npp), yp(npp), pa(9)
    real :: zp(npp)
    integer :: j, ic, itime
    double precision :: po(15)
    xp = (/ 3.27d0, 41.6d0, 120.05d0, 250.9d0, 7.5d0, 359.4d0, 64.81d0 /)
    yp = (/ 2.71d0, 30.33d0, 95.2d0, 180.4d0, 179.5d0, 12.6d0, 44.0d0 /)
    zp = (/ 3., 150., 777., 2400., 7999., 41., 3500.5 /)
    xlon0 = -179.5
    ylat0 = -89.75
    dx = 1.0
    dy = 0.996
    memtime(1) = 0
    memtime(2) = 10800
    do j = 1, npp
      xtra1(j) = xp(j)
      ytra1(j) = yp(j)
      ztra1(j) = zp(j)
      npart_av(j) = 0
      part_av_cartx(j) = 0.
      part_av_carty(j) = 0.
      part_av_cartz(j) = 0.
      part_av_z(j) = 0.
      part_av_topo(j) = 0.
      part_av_pv(j) = 0.
      part_av_qv(j) = 0.
      part_av_tt(j) = 0.
      part_av_uu(j) = 0.
      part_av_vv(j) = 0.
      part_av_rho(j) = 0.
      part_av_tro(j) = 0.
      part_av_hmix(j) = 0.
      part_av_energy(j) = 0.
      do ic = 1, 2
        if (ic == 1) then
          itime = 3600
          memind(1) = 1
          memind(2) = 2
        else
          itime = 9000
          memind(1) = 2
          memind(2) = 1
        end if
        call partpos_average(itime, j)
        pa = (/ dble(j), dble(ic), dble(itime), xtra1(j), ytra1(j), dble(ztra1(j)), &
             dble(xlon0), dble(ylat0), dble(dy) /)
        po = (/ dble(npart_av(j)), dble(part_av_cartx(j)), dble(part_av_carty(j)), &
             dble(part_av_cartz(j)), dble(part_av_z(j)), dble(part_av_topo(j)), &
             dble(part_av_pv(j)), dble(part_av_qv(j)), dble(part_av_tt(j)), &
             dble(part_av_uu(j)), dble(part_av_vv(j)), dble(part_av_rho(j)), &
             dble(part_av_tro(j)), dble(part_av_hmix(j)), dble(part_av_energy(j)) /)
        call rowvd('partpos_average', pa, 9, po, 15)
      end do
    end do
  end subroutine emit_partpos_average

end program flexpart_reference_output
