! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART code-to-code reference driver, stage `release`: particle release
! and domain filling.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) VERBATIM:
!   releaseparticles.f90, init_domainfill.f90, boundcond_domainfill.f90,
!   juldate.f90, caldate.f90 (called by releaseparticles)
! plus com_mod, point_mod, xmass_mod.
!
! Two local files stand in for upstream ones, and neither changes a routine
! under test:
!   - par_mod.f90 is compiled from a copy with THREE configuration lines
!     changed (checked by dev/build_reference_release.sh, diff count 6):
!       maxnests=1,nxmaxn=12,nymaxn=12   (shipped zeros make nests impossible)
!       maxspec=2                        (shipped 1 hides the species average)
!       nclassunc=5                      (shipped 1 makes nclass constant)
!   - dev/random_mod_shim_release.f90 replaces random_mod.f90 (Numerical
!     Recipes, neither ported nor re-implemented, gh:#410). ran1 returns the
!     driver's sequence shim_seq in order; every call's consumed draws are
!     echoed, so the port is fed exactly the same numbers.
!
! Draws: shim_seq(i) = (2*mod(i*7919,4096)+1)/8192, dyadic, exact in both
! precisions, strictly inside (0,1) like Numerical Recipes' ran1.
!
! Synthetic fields are computed in double and rounded ONCE to real(4) in both
! builds, so real4-vs-real8 differences are upstream arithmetic only. When the
! grid changes, every static field is zeroed first: the port's model of a read
! past the filled grid is "zero" (see release.rs, StaticExtents).
!
! init_domainfill writes three list-directed lines to stdout ('Atm. mass:',
! ...); they start with a blank and build_reference_release.sh drops them.
!
! Rows (all double precision, via rowvd; integral values print as integers):
!   grid        setup: gid;nx;ny;nz;dx;dy;xlon0;ylat0;dyconst;xglobal;sglobal;
!               nglobal;numbnests;height(1:nz)
!   fld         setup: gid;id;slot;k, nx*ny values (id 1 uu,2 vv,6 rho,8 tt,9 pv)
!   oro         setup: gid, nx*ny values
!   nest        setup: xln;yln;xrn;yrn;xresoln;yresoln;nxn;nyn
!   nfld        setup: id;k, nxn*nyn values of memory slot 2 (id 6 rho, 8 tt)
!   noro        setup: nxn*nyn values
!   profile     setup: k, area_hour(24),point_hour(24),area_dow(7),point_dow(7)
!   reset       setup: particle store emptied (itra1=-999999999, rest 0) and
!               the draw sequence restarted
!   pset        driver change of one particle slot: seq;i -> 13 slot values
!   clock       driver rule applied to every live particle (see
!               advance_clocks, advance_clocks_df): seq;itime;rule;
!               nx_we(1:2);ny_sn(1:2)
!   rel_cfg     setup: ldirect;lsynctime;mintime;itsplit;nclassunc;mquasilag;
!               ind_rel;drybkdep;wetbkdep;bdate;nspec;numpoint;nxmax
!   rel_point   setup: i;start;end;npart;kindz;x1;x2;y1;y2;z1;z2;xmass(1:2)
!   rel_call    call: seq;itime;pos0;numpart;numparticlecount;
!               xmasssave(1:n);rho_rel(1:n)
!   rel_slot    result: seq;i -> itra1,npoint,nclass,idt,itramem,itrasplit,
!               xtra1,ytra1,ztra1,xmass1(1:2),xscav_frac1(1:2)
!   rel_after   result: seq -> numpart,numparticlecount,ndraws,xmasssave(1:n),
!               rho_rel(1:n)
!   draws       seq;n -> the n draws the call consumed
!   df_fill     state set: ncol;z;acc;imax;jmax (arrays (:,0:imax,1:jmax))
!   df_set      state change: seq;id;k;i;j0 -> values at j0, j0+1, ... (id 1
!               numcolumn_we, 2 numcolumn_sn, 3 zcolumn_we, 4 zcolumn_sn,
!               5 acc_mass_we, 6 acc_mass_sn; j0=0 and one value for the
!               numcolumn arrays)
!   df_cfg      setup: mdomainfill;ipin;ipout;pvcrit;ozonescale;nclassunc;
!               mintime;ldirect;itsplit;lsynctime;x1;x2;y1;y2;npart1
!   df_init_call call: seq;pos0;numpart;numparticlecount;gdomainfill;numcolumn
!   df_bc_call  call: seq;itime;pos0;numpart;numparticlecount;xmassperparticle;
!               nx_we(1:2);ny_sn(1:2);gdomainfill;numcolumn;memtime(1:2)
!   df_slot     result, as rel_slot
!   df_cell     result, as df_set
!   df_after    result: seq -> nx_we(1:2),ny_sn(1:2),numcolumn,gdomainfill,
!               xmassperparticle,numpart,numparticlecount,ndraws
program flexpart_reference_release
  use par_mod
  use com_mod
  use point_mod
  use xmass_mod
  use random_mod
  implicit none

  integer, parameter :: NZP = 8
  integer :: seq = 0
  integer :: i
  real(kind=dp) :: juldate

  integer, allocatable :: s_it(:), s_np(:), s_nc(:), s_idt(:), s_im(:), s_is(:)
  real(kind=dp), allocatable :: s_x(:), s_y(:)
  real, allocatable :: s_z(:), s_m(:,:), s_sc(:,:)
  integer :: s_ncwe(2,0:nymax-1), s_ncsn(2,0:nxmax-1)
  real, allocatable :: s_zwe(:,:,:), s_zsn(:,:,:), s_awe(:,:,:), s_asn(:,:,:)

  write(*,'(A)') '# FLEXPART release/domain-filling reference, generated by dev/flexpart_reference_release.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_release.sh'
  write(*,'(A)') 'function,args,outputs'

  do i = 1, shim_n
    shim_seq(i) = real(2*mod(i*7919, 4096) + 1)/8192.
  end do

  call com_mod_allocate_part(maxpart)
  allocate(xscav_frac1(maxpart, maxspec))
  allocate(s_it(maxpart), s_np(maxpart), s_nc(maxpart), s_idt(maxpart), s_im(maxpart), &
       s_is(maxpart), s_x(maxpart), s_y(maxpart), s_z(maxpart), s_m(maxpart, maxspec), &
       s_sc(maxpart, maxspec))
  allocate(s_zwe(2,0:nymax-1,maxcolumn), s_zsn(2,0:nxmax-1,maxcolumn), &
       s_awe(2,0:nymax-1,maxcolumn), s_asn(2,0:nxmax-1,maxcolumn))
  numbnests = 1
  call com_mod_allocate_nests()
  call snap_state()

  call set_profiles()
  call setup_grid(1)
  call release_grid_a()
  call domainfill_grid_a()
  call setup_grid(2)
  call release_grid_g()
  call domainfill_grid_g()

contains

  ! ---------------------------------------------------------------- output
  subroutine putnum(x)
    double precision, intent(in) :: x
    character(len=32) :: buf
    ! Integral values (counters, indices, times) print as integers to keep
    ! the fixture small; every other value as ES25.17E3 (exact for real(8)).
    if (x == aint(x) .and. abs(x) < 1d15) then
      write(buf,'(I0)') int(x, 8)
    else
      write(buf,'(ES25.17E3)') x
    end if
    write(*,'(A)',advance='no') trim(adjustl(buf))
  end subroutine putnum

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(*), outs(*)
    integer :: k
    write(*,'(A)',advance='no') trim(name)//','
    do k = 1, nargs
      call putnum(args(k))
      if (k < nargs) write(*,'(A)',advance='no') ';'
    end do
    write(*,'(A)',advance='no') ','
    do k = 1, nouts
      call putnum(outs(k))
      if (k < nouts) write(*,'(A)',advance='no') ';'
    end do
    write(*,'(A)') ''
  end subroutine rowvd

  double precision function lg(b)
    logical, intent(in) :: b
    lg = 0d0
    if (b) lg = 1d0
  end function lg

  ! ------------------------------------------------------------ the fields
  double precision function fval(id, x, y, h, m)
    integer, intent(in) :: id, m
    double precision, intent(in) :: x, y, h
    select case (id)
    case (1)
      fval = 6d0 - 2.4d0*y + 1.5d-3*h + 1.5d0*(m-1) - 0.5d0*x
    case (2)
      fval = -5d0 + 1.8d0*x - 8d-4*h + 1d0*(m-1) + 0.3d0*y
    case (6)
      fval = 1.22d0*9000d0/(9000d0 + h)*(1d0 + 0.08d0*x - 0.05d0*y + 0.01d0*(m-1))
    case (8)
      fval = 290d0 - 6.5d-3*min(h, 11000d0) + 0.5d0*x - 0.3d0*y + 0.4d0*(m-1)
    case (9)
      fval = 0.25d0 + h/2000d0*(1d0 + 0.1d0*x) + 0.2d0*y - 0.3d0*(m-1)
    case default
      fval = 0d0
    end select
  end function fval

  double precision function foro(x, y)
    double precision, intent(in) :: x, y
    foro = 50d0 + 30d0*x + 20d0*y
  end function foro

  subroutine setup_grid(gid)
    integer, intent(in) :: gid
    integer :: ii, j, k, m, id, nxn, nyn
    integer :: ids(5) = (/ 1, 2, 6, 8, 9 /)
    double precision :: vals(400), hd(NZP), xx, yy
    uu = 0.; vv = 0.; rho = 0.; tt = 0.; pv = 0.; oro = 0.
    nz = NZP
    height(1:NZP) = (/ 10., 60., 250., 700., 1600., 3200., 6400., 12800. /)
    if (gid == 1) then
      nx = 8; ny = 7; dx = 2.; dy = 1.5; xlon0 = -7.; ylat0 = -4.5
      xglobal = .false.; sglobal = .false.; nglobal = .false.
      numbnests = 1
    else
      nx = 9; ny = 7; dx = 45.; dy = 30.; xlon0 = -180.; ylat0 = -90.
      xglobal = .true.; sglobal = .true.; nglobal = .true.
      numbnests = 0
    end if
    nxmin1 = nx - 1; nymin1 = ny - 1
    dyconst = real(180d0/(dble(dy)*6.371d6*3.14159265d0), 4)
    memtime(1) = 0; memtime(2) = 10800
    memind(1) = 1; memind(2) = 2
    hd = dble(height(1:NZP))
    call rowvd('grid', (/ dble(gid), dble(nx), dble(ny), dble(nz), dble(dx), dble(dy), &
         dble(xlon0), dble(ylat0), dble(dyconst), lg(xglobal), lg(sglobal), lg(nglobal), &
         dble(numbnests), hd /), 13 + NZP, (/ 0d0 /), 0)
    do m = 1, 2
      do k = 1, nz
        do j = 0, ny-1
          do ii = 0, nx-1
            xx = dble(ii); yy = dble(j)
            uu(ii,j,k,m) = real(fval(1, xx, yy, dble(height(k)), m), 4)
            vv(ii,j,k,m) = real(fval(2, xx, yy, dble(height(k)), m), 4)
            rho(ii,j,k,m) = real(fval(6, xx, yy, dble(height(k)), m), 4)
            tt(ii,j,k,m) = real(fval(8, xx, yy, dble(height(k)), m), 4)
            pv(ii,j,k,m) = real(fval(9, xx, yy, dble(height(k)), m), 4)
          end do
        end do
        do id = 1, 5
          do j = 0, ny-1
            do ii = 0, nx-1
              select case (ids(id))
              case (1); vals(1 + ii + nx*j) = dble(uu(ii,j,k,m))
              case (2); vals(1 + ii + nx*j) = dble(vv(ii,j,k,m))
              case (6); vals(1 + ii + nx*j) = dble(rho(ii,j,k,m))
              case (8); vals(1 + ii + nx*j) = dble(tt(ii,j,k,m))
              case (9); vals(1 + ii + nx*j) = dble(pv(ii,j,k,m))
              end select
            end do
          end do
          call rowvd('fld', (/ dble(gid), dble(ids(id)), dble(m), dble(k) /), 4, vals, nx*ny)
        end do
      end do
    end do
    do j = 0, ny-1
      do ii = 0, nx-1
        oro(ii,j) = real(foro(dble(ii), dble(j)), 4)
        vals(1 + ii + nx*j) = dble(oro(ii,j))
      end do
    end do
    call rowvd('oro', (/ dble(gid) /), 1, vals, nx*ny)

    if (gid == 1) then
      xln(1) = 2.; yln(1) = 1.; xrn(1) = 5.; yrn(1) = 4.
      xresoln(1) = 2.; yresoln(1) = 2.
      nxn = 7; nyn = 7
      call rowvd('nest', (/ dble(xln(1)), dble(yln(1)), dble(xrn(1)), dble(yrn(1)), &
           dble(xresoln(1)), dble(yresoln(1)), dble(nxn), dble(nyn) /), 8, (/ 0d0 /), 0)
      rhon = 0.; ttn = 0.; oron = 0.
      do k = 1, nz
        do j = 0, nyn-1
          do ii = 0, nxn-1
            xx = 2d0 + 0.5d0*ii; yy = 1d0 + 0.5d0*j
            rhon(ii,j,k,2,1) = real(1.03d0*fval(6, xx, yy, dble(height(k)), 2), 4)
            ttn(ii,j,k,2,1) = real(fval(8, xx, yy, dble(height(k)), 2) + 0.7d0, 4)
          end do
        end do
        do j = 0, nyn-1
          do ii = 0, nxn-1
            vals(1 + ii + nxn*j) = dble(rhon(ii,j,k,2,1))
          end do
        end do
        call rowvd('nfld', (/ 6d0, dble(k) /), 2, vals, nxn*nyn)
        do j = 0, nyn-1
          do ii = 0, nxn-1
            vals(1 + ii + nxn*j) = dble(ttn(ii,j,k,2,1))
          end do
        end do
        call rowvd('nfld', (/ 8d0, dble(k) /), 2, vals, nxn*nyn)
      end do
      do j = 0, nyn-1
        do ii = 0, nxn-1
          oron(ii,j,1) = real(foro(2d0 + 0.5d0*ii, 1d0 + 0.5d0*j) + 7d0, 4)
          vals(1 + ii + nxn*j) = dble(oron(ii,j,1))
        end do
      end do
      call rowvd('noro', (/ 0d0 /), 1, vals, nxn*nyn)
    end if
  end subroutine setup_grid

  subroutine set_profiles()
    integer :: k, h
    double precision :: v(62)
    do k = 1, 2
      do h = 1, 24
        area_hour(k,h) = 0.5 + real(h)/32. + 0.25*real(k-1)
        point_hour(k,h) = 1.5 - real(h)/64. + 0.125*real(k-1)
        v(h) = dble(area_hour(k,h)); v(24+h) = dble(point_hour(k,h))
      end do
      do h = 1, 7
        area_dow(k,h) = 0.75 + real(h)/16.
        point_dow(k,h) = 1.25 - real(h)/32. + 0.0625*real(k-1)
        v(48+h) = dble(area_dow(k,h)); v(55+h) = dble(point_dow(k,h))
      end do
      call rowvd('profile', (/ dble(k) /), 1, v, 62)
    end do
  end subroutine set_profiles

  ! ------------------------------------------------------ particle store
  subroutine snap_parts()
    s_it = itra1; s_np = npoint; s_nc = nclass; s_idt = idt; s_im = itramem
    s_is = itrasplit; s_x = xtra1; s_y = ytra1; s_z = ztra1; s_m = xmass1
    s_sc = xscav_frac1
  end subroutine snap_parts

  subroutine dump_parts(tag)
    character(len=*), intent(in) :: tag
    integer :: ip
    do ip = 1, maxpart
      if (itra1(ip) /= s_it(ip) .or. npoint(ip) /= s_np(ip) .or. nclass(ip) /= s_nc(ip) &
           .or. idt(ip) /= s_idt(ip) .or. itramem(ip) /= s_im(ip) &
           .or. itrasplit(ip) /= s_is(ip) .or. xtra1(ip) /= s_x(ip) &
           .or. ytra1(ip) /= s_y(ip) .or. ztra1(ip) /= s_z(ip) &
           .or. any(xmass1(ip,:) /= s_m(ip,:)) .or. any(xscav_frac1(ip,:) /= s_sc(ip,:))) then
        call rowvd(tag, (/ dble(seq), dble(ip) /), 2, (/ dble(itra1(ip)), dble(npoint(ip)), &
             dble(nclass(ip)), dble(idt(ip)), dble(itramem(ip)), dble(itrasplit(ip)), &
             dble(xtra1(ip)), dble(ytra1(ip)), dble(ztra1(ip)), dble(xmass1(ip,1)), &
             dble(xmass1(ip,2)), dble(xscav_frac1(ip,1)), dble(xscav_frac1(ip,2)) /), 13)
      end if
    end do
    call snap_parts()
  end subroutine dump_parts

  ! Also restarts the draw sequence, so that every case sees the same draws
  ! in both builds (a real(4) build that consumed a different number of draws
  ! in an earlier case would otherwise shift every later case's draws).
  subroutine reset_parts()
    shim_pos = 0
    itra1 = -999999999; npoint = 0; nclass = 0; idt = 0; itramem = 0; itrasplit = 0
    xtra1 = 0.; ytra1 = 0.; ztra1 = 0.; xmass1 = 0.; xscav_frac1 = 0.
    numpart = 0; numparticlecount = 0
    call rowvd('reset', (/ dble(seq) /), 1, (/ 0d0 /), 0)
    call snap_parts()
  end subroutine reset_parts

  ! Synchronise live particles to itime, terminating every 7th (offset 3).
  ! The rule is echoed as one `clock` row (seq;itime;1) and replayed by the
  ! test; it is not dumped slot by slot.
  subroutine advance_clocks(itime)
    integer, intent(in) :: itime
    integer :: ip
    do ip = 1, numpart
      if (itra1(ip) /= -999999999) then
        itra1(ip) = itime
        if (mod(ip, 7) == 3) itra1(ip) = -999999999
      end if
    end do
    seq = seq + 1
    call rowvd('clock', (/ dble(seq), dble(itime), 1d0, 0d0, 0d0, 0d0, 0d0 /), 7, (/ 0d0 /), 0)
    call snap_parts()
  end subroutine advance_clocks

  ! As advance_clocks without terminations, and move some particles across
  ! the box boundaries (later rules override earlier ones). Echoed as
  ! `clock` (seq;itime;2;nx_we(1:2);ny_sn(1:2)).
  subroutine advance_clocks_df(itime)
    integer, intent(in) :: itime
    integer :: ip
    do ip = 1, numpart
      if (itra1(ip) /= -999999999) then
        itra1(ip) = itime
        if (mod(ip, 11) == 4) xtra1(ip) = real(nx_we(1)) - 0.25
        if (mod(ip, 13) == 6) ytra1(ip) = real(ny_sn(2)) + 0.25
        if (mod(ip, 17) == 2) xtra1(ip) = real(nx_we(2)) + 0.5
        if (mod(ip, 19) == 1) xtra1(ip) = real(nx_we(1))
        if (mod(ip, 23) == 5) ytra1(ip) = real(ny_sn(1)) - 0.125
      end if
    end do
    seq = seq + 1
    call rowvd('clock', (/ dble(seq), dble(itime), 2d0, dble(nx_we(1)), dble(nx_we(2)), &
         dble(ny_sn(1)), dble(ny_sn(2)) /), 7, (/ 0d0 /), 0)
    call snap_parts()
  end subroutine advance_clocks_df

  subroutine echo_draws(pos0)
    integer, intent(in) :: pos0
    integer :: n, k
    double precision, allocatable :: v(:)
    n = shim_pos - pos0
    allocate(v(max(n, 1)))
    do k = 1, n
      v(k) = dble(shim_seq(pos0 + k))
    end do
    call rowvd('draws', (/ dble(seq), dble(n) /), 2, v, n)
  end subroutine echo_draws

  ! -------------------------------------------------------------- releases
  subroutine alloc_points(n)
    integer, intent(in) :: n
    if (allocated(ireleasestart)) then
      deallocate(ireleasestart, ireleaseend, npart, kindz, xpoint1, xpoint2, ypoint1, &
           ypoint2, zpoint1, zpoint2, xmass, rho_rel, xmasssave)
    end if
    allocate(ireleasestart(n), ireleaseend(n), npart(n), kindz(n), xpoint1(n), xpoint2(n), &
         ypoint1(n), ypoint2(n), zpoint1(n), zpoint2(n), xmass(n, maxspec), rho_rel(n), &
         xmasssave(n))
    numpoint = n
    xmasssave = 0.; rho_rel = 0.
  end subroutine alloc_points

  subroutine set_point(ip, t1, t2, np, kz, x1, x2, y1, y2, z1, z2, m1, m2)
    integer, intent(in) :: ip, t1, t2, np, kz
    real, intent(in) :: x1, x2, y1, y2, z1, z2, m1, m2
    ireleasestart(ip) = t1; ireleaseend(ip) = t2; npart(ip) = np; kindz(ip) = int(kz, 2)
    xpoint1(ip) = x1; xpoint2(ip) = x2; ypoint1(ip) = y1; ypoint2(ip) = y2
    zpoint1(ip) = z1; zpoint2(ip) = z2; xmass(ip,1) = m1; xmass(ip,2) = m2
    call rowvd('rel_point', (/ dble(ip), dble(t1), dble(t2), dble(np), dble(kz), &
         dble(xpoint1(ip)), dble(xpoint2(ip)), dble(ypoint1(ip)), dble(ypoint2(ip)), &
         dble(zpoint1(ip)), dble(zpoint2(ip)), dble(xmass(ip,1)), dble(xmass(ip,2)) /), 13, &
         (/ 0d0 /), 0)
  end subroutine set_point

  subroutine echo_rel_cfg()
    call rowvd('rel_cfg', (/ dble(ldirect), dble(lsynctime), dble(mintime), dble(itsplit), &
         dble(nclassunc), dble(mquasilag), dble(ind_rel), lg(DRYBKDEP), lg(WETBKDEP), &
         dble(bdate), dble(nspec), dble(numpoint), dble(nxmax) /), 13, (/ 0d0 /), 0)
  end subroutine echo_rel_cfg

  subroutine call_release(itime)
    integer, intent(in) :: itime
    integer :: pos0
    double precision :: a(5 + 2*numpoint), o(3 + 2*numpoint)
    seq = seq + 1
    pos0 = shim_pos
    a(1:5) = (/ dble(seq), dble(itime), dble(pos0), dble(numpart), dble(numparticlecount) /)
    a(6:5+numpoint) = dble(xmasssave(1:numpoint))
    a(6+numpoint:5+2*numpoint) = dble(rho_rel(1:numpoint))
    call rowvd('rel_call', a, 5 + 2*numpoint, (/ 0d0 /), 0)
    call snap_parts()
    call releaseparticles(itime)
    call dump_parts('rel_slot')
    o(1:3) = (/ dble(numpart), dble(numparticlecount), dble(shim_pos - pos0) /)
    o(4:3+numpoint) = dble(xmasssave(1:numpoint))
    o(4+numpoint:3+2*numpoint) = dble(rho_rel(1:numpoint))
    call rowvd('rel_after', (/ dble(seq) /), 1, o, 3 + 2*numpoint)
    call echo_draws(pos0)
  end subroutine call_release

  subroutine release_grid_a()
    integer :: it
    ! R1: forward, January (no summer time), point / area / instantaneous
    ! sources, kindz 1 and 2, a nest, no density weighting.
    call reset_parts()
    ldirect = 1; lsynctime = 900; mintime = 10; itsplit = 43200; mquasilag = 0; ind_rel = 0
    DRYBKDEP = .false.; WETBKDEP = .false.; nspec = 2
    bdate = juldate(20240101, 60000)
    call alloc_points(3)
    call set_point(1, 0, 3600, 37, 1, 3.25, 3.25, 2.5, 2.5, 40., 120., 2.0, 3.0)
    call set_point(2, 900, 2700, 20, 1, 1.0, 2.5, 4.5, 5.75, -20., 400., 1.5, 0.5)
    call set_point(3, 1800, 1800, 6, 2, 2.5, 4.5, 1.5, 3.5, 0., 300., 4., 1.)
    call echo_rel_cfg()
    do it = 0, 4500, 900
      call advance_clocks(it)
      call call_release(it)
    end do

    ! R2: backward, July (summer time), kindz 3 (all three outcomes of the
    ! pressure search), clamp at the top, density weighting (ind_rel=1),
    ! mquasilag, DRYBKDEP.
    call reset_parts()
    ldirect = -1; lsynctime = 900; mquasilag = 1; ind_rel = 1
    DRYBKDEP = .true.; WETBKDEP = .false.
    bdate = juldate(20240715, 220000)
    call alloc_points(4)
    call set_point(1, -2700, 0, 25, 3, 0.5, 1.0, 4.0, 5.0, 1100., 1150., 1., 2.)
    call set_point(2, -2700, -900, 18, 3, 2.25, 4.5, 1.25, 3.75, 600., 950., 3., 0.25)
    call set_point(3, -1800, -1800, 7, 3, 5.0, 6.5, 4.0, 5.5, 50., 150., 0.5, 0.5)
    call set_point(4, -2700, 0, 12, 1, 0.5, 6.5, 0.5, 5.5, 12000., 14000., 2., 2.)
    call echo_rel_cfg()
    do it = 0, -3600, -900
      call advance_clocks(it)
      call call_release(it)
    end do

    ! R4: the summer-time month boundaries (March/April, September/October):
    ! one instantaneous area release per start date; the hour shift changes
    ! the time-profile factors and therefore the masses.
    call reset_parts()
    ldirect = 1; lsynctime = 900; mquasilag = 0; ind_rel = 0
    DRYBKDEP = .false.; WETBKDEP = .false.
    call alloc_points(1)
    call set_point(1, 0, 0, 2, 1, 1.5, 2.5, 1.5, 2.5, 10., 90., 1., 1.)
    bdate = juldate(20240331, 233000)
    call echo_rel_cfg()
    call call_release(0)
    bdate = juldate(20240401, 3000)
    call echo_rel_cfg()
    call call_release(0)
    bdate = juldate(20240930, 233000)
    call echo_rel_cfg()
    call call_release(0)
    bdate = juldate(20241001, 3000)
    call echo_rel_cfg()
    call call_release(0)
  end subroutine release_grid_a

  subroutine release_grid_g()
    integer :: it
    ! R3: global grid: east-west wrap both ways, xlonav wrap both ways,
    ! Monday-midnight local time (nhour 0 -> 24, day 0 -> 7), reads at
    ! x == nxmin1 and y == nymin1, ind_rel=3, WETBKDEP.
    call reset_parts()
    ldirect = 1; lsynctime = 900; mquasilag = 0; ind_rel = 3
    DRYBKDEP = .false.; WETBKDEP = .true.
    bdate = juldate(20240101, 0)
    call alloc_points(4)
    call set_point(1, 0, 1800, 30, 1, -0.75, 0.25, 1.0, 5.0, 100., 900., 1., 1.)
    call set_point(2, 0, 1800, 30, 1, 7.75, 8.75, 2.0, 4.0, 0., 2000., 2., 1.)
    call set_point(3, 0, 0, 5, 1, 4.0, 4.0, 3.0, 3.0, 50., 50., 1., 3.)
    call set_point(4, 0, 900, 8, 2, 8.0, 8.0, 6.0, 6.0, 500., 900., 5., 1.)
    call echo_rel_cfg()
    do it = 0, 1800, 900
      call advance_clocks(it)
      call call_release(it)
    end do
  end subroutine release_grid_g

  ! --------------------------------------------------------- domain filling
  subroutine snap_state()
    s_ncwe = numcolumn_we; s_ncsn = numcolumn_sn
    s_zwe = zcolumn_we; s_zsn = zcolumn_sn; s_awe = acc_mass_we; s_asn = acc_mass_sn
  end subroutine snap_state

  ! Emit the changed entries of one (id,k,i) line over j as runs:
  ! tag: seq;id;k;i;jfirst -> values of j = jfirst, jfirst+1, ...
  subroutine dump_runs(tag, id, k, ii, cur, old)
    character(len=*), intent(in) :: tag
    integer, intent(in) :: id, k, ii
    real, intent(in) :: cur(:), old(:)
    integer :: j, j0
    j = 1
    do while (j <= size(cur))
      if (cur(j) /= old(j)) then
        j0 = j
        do while (j <= size(cur))
          if (cur(j) == old(j)) exit
          j = j + 1
        end do
        call rowvd(tag, (/ dble(seq), dble(id), dble(k), dble(ii), dble(j0) /), 5, &
             dble(cur(j0:j-1)), j - j0)
      else
        j = j + 1
      end if
    end do
  end subroutine dump_runs

  subroutine dump_state(tag)
    character(len=*), intent(in) :: tag
    integer :: k, ii
    do ii = 0, nymax-1
      do k = 1, 2
        if (numcolumn_we(k,ii) /= s_ncwe(k,ii)) call rowvd(tag, (/ dble(seq), 1d0, dble(k), &
             dble(ii), 0d0 /), 5, (/ dble(numcolumn_we(k,ii)) /), 1)
      end do
    end do
    do ii = 0, nxmax-1
      do k = 1, 2
        if (numcolumn_sn(k,ii) /= s_ncsn(k,ii)) call rowvd(tag, (/ dble(seq), 2d0, dble(k), &
             dble(ii), 0d0 /), 5, (/ dble(numcolumn_sn(k,ii)) /), 1)
      end do
    end do
    do ii = 0, nymax-1
      do k = 1, 2
        call dump_runs(tag, 3, k, ii, zcolumn_we(k,ii,:), s_zwe(k,ii,:))
        call dump_runs(tag, 5, k, ii, acc_mass_we(k,ii,:), s_awe(k,ii,:))
      end do
    end do
    do ii = 0, nxmax-1
      do k = 1, 2
        call dump_runs(tag, 4, k, ii, zcolumn_sn(k,ii,:), s_zsn(k,ii,:))
        call dump_runs(tag, 6, k, ii, acc_mass_sn(k,ii,:), s_asn(k,ii,:))
      end do
    end do
    call snap_state()
  end subroutine dump_state

  ! Sentinel fill of the boundary arrays over (:, 0:imax, 1:jmax).
  subroutine fill_state(ncol, z, acc)
    integer, intent(in) :: ncol
    real, intent(in) :: z, acc
    integer, parameter :: imax = 15, jmax = 40
    numcolumn_we(:, 0:imax) = ncol; numcolumn_sn(:, 0:imax) = ncol
    zcolumn_we(:, 0:imax, 1:jmax) = z; zcolumn_sn(:, 0:imax, 1:jmax) = z
    acc_mass_we(:, 0:imax, 1:jmax) = acc; acc_mass_sn(:, 0:imax, 1:jmax) = acc
    call rowvd('df_fill', (/ dble(ncol), dble(z), dble(acc), dble(imax), dble(jmax) /), 5, &
         (/ 0d0 /), 0)
    call snap_state()
  end subroutine fill_state

  subroutine df_config(md, ip, ls, x1, x2, y1, y2, np)
    integer, intent(in) :: md, ip, ls, np
    real, intent(in) :: x1, x2, y1, y2
    mdomainfill = md; ipin = ip; ipout = 0; lsynctime = ls
    ldirect = 1; mintime = 10; itsplit = 43200
    call alloc_points(1)
    xpoint1(1) = x1; xpoint2(1) = x2; ypoint1(1) = y1; ypoint2(1) = y2; npart(1) = np
    call rowvd('df_cfg', (/ dble(mdomainfill), dble(ipin), dble(ipout), dble(pvcrit), &
         dble(ozonescale), dble(nclassunc), dble(mintime), dble(ldirect), dble(itsplit), &
         dble(lsynctime), dble(xpoint1(1)), dble(xpoint2(1)), dble(ypoint1(1)), &
         dble(ypoint2(1)), dble(npart(1)) /), 15, (/ 0d0 /), 0)
  end subroutine df_config

  subroutine df_after(pos0)
    integer, intent(in) :: pos0
    call rowvd('df_after', (/ dble(seq) /), 1, (/ dble(nx_we(1)), dble(nx_we(2)), &
         dble(ny_sn(1)), dble(ny_sn(2)), dble(numcolumn), lg(gdomainfill), &
         dble(xmassperparticle), dble(numpart), dble(numparticlecount), &
         dble(shim_pos - pos0) /), 10)
    call echo_draws(pos0)
  end subroutine df_after

  subroutine call_init()
    integer :: pos0
    seq = seq + 1
    pos0 = shim_pos
    call rowvd('df_init_call', (/ dble(seq), dble(pos0), dble(numpart), &
         dble(numparticlecount), lg(gdomainfill), dble(numcolumn) /), 6, (/ 0d0 /), 0)
    call snap_parts(); call snap_state()
    call init_domainfill()
    call dump_parts('df_slot'); call dump_state('df_cell')
    call df_after(pos0)
  end subroutine call_init

  subroutine call_bc(itime)
    integer, intent(in) :: itime
    integer :: pos0
    seq = seq + 1
    pos0 = shim_pos
    call rowvd('df_bc_call', (/ dble(seq), dble(itime), dble(pos0), dble(numpart), &
         dble(numparticlecount), dble(xmassperparticle), dble(nx_we(1)), dble(nx_we(2)), &
         dble(ny_sn(1)), dble(ny_sn(2)), lg(gdomainfill), dble(numcolumn), &
         dble(memtime(1)), dble(memtime(2)) /), 14, (/ 0d0 /), 0)
    call snap_parts(); call snap_state()
    call boundcond_domainfill(itime, -1)
    call dump_parts('df_slot'); call dump_state('df_cell')
    call df_after(pos0)
  end subroutine call_bc

  subroutine domainfill_grid_a()
    integer :: it, k, ii, j
    integer :: nwe(2,5), nsn(2,6)
    ! D1: limited box, air tracer, then boundary injection over four steps.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    gdomainfill = .false.
    call df_config(1, 0, 10800, 1.3, 5.6, 1.2, 4.7, 500)
    call call_init()
    do it = 2700, 10800, 2700
      call advance_clocks_df(it)
      call call_bc(it)
    end do

    ! D2: ozone tracer; box reaching the east and north edges of the grid
    ! (extra x draw at ix == nxmin1, PV read from row ny), across the equator.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    gdomainfill = .false.
    call df_config(2, 0, 10800, 1.3, 7.0, 1.2, 6.0, 300)
    call call_init()
    do it = 3600, 7200, 3600
      call advance_clocks_df(it)
      call call_bc(it)
    end do

    ! D3: resume (ipin = 2: non-zero, no file read): positions not assigned,
    ! pre-existing particles outside the domain terminated, numpart trimmed.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    call snap_parts()
    itra1(1:6) = 0
    xtra1(1:6) = (/ 2d0, -1d0, 3d0, 4d0, 2.5d0, 7.5d0 /)
    ytra1(1:6) = (/ 2d0, 2d0, 3d0, 9d0, 2.5d0, 1d0 /)
    numpart = 6
    seq = seq + 1
    call dump_parts('pset')
    gdomainfill = .false.
    call df_config(1, 2, 10800, 0.0, 3.0, 0.0, 2.5, 200)
    call call_init()

    ! D7: boundary conditions on a synthetic state: release-height counts
    ! 0, 1, 3, 4, 5 (never 2: upstream reads outside zcolumn), accumulators
    ! preset, several particles per step.
    call reset_parts()
    call fill_state(0, 0., 0.)
    call df_config(1, 0, 10800, 1.3, 5.6, 1.2, 4.7, 500)
    nx_we = (/ 1, 6 /); ny_sn = (/ 1, 5 /); gdomainfill = .false.
    xmassperparticle = 2.**42
    nwe(1,:) = (/ 1, 3, 4, 0, 5 /); nwe(2,:) = (/ 3, 1, 5, 4, 3 /)
    nsn(1,:) = (/ 3, 4, 1, 5, 3, 0 /); nsn(2,:) = (/ 4, 3, 3, 1, 5, 4 /)
    call snap_state()
    do k = 1, 2
      do ii = 1, 5
        numcolumn_we(k,ii) = nwe(k,ii)
        do j = 1, 6
          zcolumn_we(k,ii,j) = real(150*j + 37*ii + 11*k)
          acc_mass_we(k,ii,j) = real(mod(ii + j + k, 5))*2.**40
        end do
      end do
      do ii = 1, 6
        numcolumn_sn(k,ii) = nsn(k,ii)
        do j = 1, 6
          zcolumn_sn(k,ii,j) = real(160*j + 29*ii + 13*k)
          acc_mass_sn(k,ii,j) = real(mod(2*ii + j + k, 5))*2.**40
        end do
      end do
    end do
    seq = seq + 1
    call dump_state('df_set')
    do it = 5400, 8100, 2700
      call advance_clocks_df(it)
      call call_bc(it)
    end do
  end subroutine domainfill_grid_a

  subroutine domainfill_grid_g()
    ! D4: global box -> gdomainfill; ozone tracer; boundary call returns.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    gdomainfill = .false.
    call df_config(2, 0, 10800, 0.0, 8.0, 0.0, 6.0, 500)
    call call_init()
    call advance_clocks_df(3600)
    call call_bc(3600)

    ! D5: global box resumed (ipin = 1): early return.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    gdomainfill = .false.
    call df_config(1, 1, 10800, 0.0, 8.0, 0.0, 6.0, 500)
    call call_init()

    ! D6: global wind fields, box short of the poles: gdomainfill reset to
    ! false; east-west boundaries still inject; no x termination.
    call reset_parts()
    call fill_state(-5, -1., 7.)
    gdomainfill = .true.
    call df_config(1, 0, 10800, 0.0, 8.0, 1.5, 4.5, 300)
    call call_init()
    ! The cells of this grid are so large that one step's inflow is ~1/70 of
    ! a particle's mass: preset every boundary accumulator to exactly half a
    ! particle, so inflow releases and outflow resets on the first step.
    call snap_state()
    acc_mass_we(:, ny_sn(1):ny_sn(2), 1:40) = 0.5*xmassperparticle
    acc_mass_sn(:, nx_we(1):nx_we(2), 1:40) = 0.5*xmassperparticle
    seq = seq + 1
    call dump_state('df_set')
    call advance_clocks_df(3600)
    call call_bc(3600)
    call advance_clocks_df(7200)
    call call_bc(7200)
  end subroutine domainfill_grid_g

end program flexpart_reference_release
