! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART stochastic reference, stage 7b: convective redistribution with
! FLEXPART's OWN random numbers.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) verbatim,
! INCLUDING random_mod.f90, so redist.f90 draws from upstream's ran3 exactly as
! in a real run (its saved iseed = -88, one continuing stream). random_mod is
! Numerical Recipes code, compiled here as a reference only: never ported,
! never re-implemented (gh:#410). The shipped par_mod is used.
!
! The convecting column uses the helpers of dev/flexpart_reference_convection.f90
! (copied): ECMWF hybrid levels, ps = 100000 Pa, Ts = 308 K, lapse 0.0065 K/m,
! RH 0.92/0.75, spun up for NSPIN = 200 calcmatrix steps of 900 s so the
! cloud-base flux builds up as convmix builds it (8.6e-3 kg m-2 s-1). The
! column and calcmatrix's result are echoed so the Rust test rebuilds the same
! matrix with the port's calcmatrix (and checks it is the same).
!
! For each of NREP replicates (consecutive blocks of the one ran3 stream),
! NP particles start on a fixed height grid from 0 to 14 km (computed in
! double precision and rounded once to real(4), so both builds use the same
! heights) and are redistributed once. Row:
!   redist.stats,<replicate>;<NP>,
!     <mean, var of the final z for starts in [0,1.5) km, [1.5,6) km, [6,14) km>;
!     <fraction moved by the matrix (ipconv = -1)>
program flexpart_stochastic_redist
  use par_mod
  use com_mod
  use conv_mod
  use random_mod
  use class_gribfile
  implicit none

  real, parameter :: phlist(18) = (/ 1000., 985., 965., 935., 895., 845., &
       780., 705., 620., 530., 440., 355., 280., 215., 160., 115., 85., 60. /)
  integer, parameter :: nuvz_c = 17, nconvlev_c = 15
  integer, parameter :: NP = 20000, NREP = 16, NSPIN = 200

  write(*,'(A)') '# FLEXPART stage-7b stochastic redist reference, generated by dev/flexpart_stochastic_redist.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference.sh'
  write(*,'(A)') 'function,args,outputs'

  call set_hybrid()
  call run()

contains

  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=16384) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowv

  real function r4(x)
    real, intent(in) :: x
    r4 = real(real(x, kind=4))
  end function r4

  subroutine make_column(np, p, ts, gam, rhlo, rhhi, kinv, dtinv, dt1, rh1, t, q, qs)
    integer, intent(in) :: np, kinv
    real, intent(in) :: p(np), ts, gam, rhlo, rhhi, dtinv, dt1, rh1
    real, intent(out) :: t(np), q(np), qs(np)
    integer :: k
    double precision :: td, rh, pd, es, qsd
    do k = 1, np
      pd = dble(r4(p(k)))
      td = dble(r4(ts))*(pd/1000d0)**(287d0*dble(r4(gam))/9.81d0)
      td = max(td, 205d0)
      if (kinv > 0 .and. k >= kinv) td = td + dble(r4(dtinv))
      if (k == 1) td = td + dble(r4(dt1))
      t(k) = r4(real(td))
      td = dble(t(k))
      rh = dble(r4(rhlo))
      if (pd < 700d0) rh = dble(r4(rhhi))
      if (k == 1 .and. rh1 >= 0.) rh = dble(r4(rh1))
      es = 6.112d0*exp(17.67d0*(td - 273.15d0)/(td - 29.65d0))
      qsd = 0.622d0*es/(pd - 0.378d0*es)
      qs(k) = r4(real(qsd))
      q(k) = r4(real(rh*dble(qs(k))))
    end do
  end subroutine make_column

  real function lin(a, b, c, d)
    real, intent(in) :: a, b, c, d
    ! (a + b*c)/d
    lin = r4(real((dble(a) + dble(b)*dble(c))/dble(d)))
  end function lin

  real function add(a, b)
    real, intent(in) :: a, b
    add = r4(real(dble(a) + dble(b)))
  end function add

  subroutine set_hybrid()
    integer :: k
    real :: s, o(4*nuvz_c), a(1)
    do k = 1, nuvz_c
      s = r4(real(dble(phlist(k))/1000d0))
      bkm(k) = r4(real(dble(s)*dble(s)))
      akm(k) = r4(real((dble(s) - dble(bkm(k)))*101325d0))
    end do
    akz(1) = 0.
    bkz(1) = 1.
    do k = 2, nuvz_c
      akz(k) = r4(real(0.5d0*(dble(akm(k-1)) + dble(akm(k)))))
      bkz(k) = r4(real(0.5d0*(dble(bkm(k-1)) + dble(bkm(k)))))
    end do
    do k = 1, nuvz_c
      o(k) = akz(k)
      o(nuvz_c + k) = bkz(k)
      o(2*nuvz_c + k) = akm(k)
      o(3*nuvz_c + k) = bkm(k)
    end do
    a(1) = real(nuvz_c)
    call rowv('hybrid', a, 1, o, 4*nuvz_c)
  end subroutine set_hybrid

  subroutine fill_calc_column(fmt, ps_in, ts, gam, rhlo, rhhi, kinv, dtinv)
    integer, intent(in) :: fmt, kinv
    real, intent(in) :: ps_in, ts, gam, rhlo, rhhi, dtinv
    integer :: k
    real :: pk(16), t(16), q(16), qs(16)
    nuvz = nuvz_c
    nconvlev = nconvlev_c
    psconv = r4(ps_in)
    do k = 1, nuvz_c - 1
      pk(k) = lin(akz(k+1), bkz(k+1), psconv, 100.)
    end do
    call make_column(nuvz_c - 1, pk, ts, gam, rhlo, rhhi, kinv, dtinv, 0., -1., t, q, qs)
    do k = 1, nuvz_c - 1
      tconv(k) = t(k)
      qconv(k) = q(k)
      if (fmt /= GRIBFILE_CENTRE_ECMWF) pconv(k) = lin(0., pk(k), 100., 1.)
    end do
  end subroutine fill_calc_column

  subroutine run()
    integer :: k, kk, m, i, irep, ktop, ipconv, b, nb(3)
    real :: cb, dt, a(3), o(100), z0
    double precision :: s1(3), s2(3), moved, zf
    logical :: lconv
    call fill_calc_column(GRIBFILE_CENTRE_ECMWF, 100000., 308., .0065, .92, .75, 0, 0.)
    m = nuvz_c - 1
    a(1) = 1.; a(2) = real(GRIBFILE_CENTRE_ECMWF); a(3) = psconv
    do k = 1, m
      o(k) = tconv(k); o(m + k) = qconv(k); o(2*m + k) = pconv(k)
    end do
    call rowv('redist.column', a, 3, o, 3*m)
    ! FLEXPART's convmix carries the column's cloud-base flux from one step to
    ! the next (cbaseflux); starting from 0 it builds up over steps. NSPIN
    ! steps on the same column bring it to a convecting state.
    cb = 0.
    dt = 900.
    do i = 1, NSPIN
      call calcmatrix(lconv, dt, cb, GRIBFILE_CENTRE_ECMWF)
    end do
    a(1) = merge(1., 0., lconv); a(2) = cb; a(3) = real(nconvtop)
    o(1) = real(NSPIN)
    call rowv('redist.calcmatrix', a, 3, o, 1)
    do k = 1, nconvtop
      do kk = 1, nconvtop
        o(kk) = fmassfrac(k, kk)
      end do
      call rowv('redist.fmassfrac', (/ real(k) /), 1, o, nconvtop)
    end do
    nz = 20
    height(nz) = 16000.
    tt2conv = add(tconv(1), 1.)
    td2conv = add(tt2conv, -3.)
    call rowv('redist.surface', (/ tt2conv, td2conv, height(nz) /), 3, (/ 0. /), 1)
    ldirect = 1
    lsynctime = 900
    allocate(ztra1(1))
    do irep = 1, NREP
      s1 = 0.d0; s2 = 0.d0; nb = 0; moved = 0.d0
      ktop = 0
      do i = 1, NP
        z0 = r4(real((dble(i) - 0.5d0)*14000.d0/dble(NP)))
        ztra1(1) = z0
        call redist(1, ktop, ipconv)
        zf = dble(ztra1(1))
        if (z0 < 1500.) then
          b = 1
        else if (z0 < 6000.) then
          b = 2
        else
          b = 3
        end if
        nb(b) = nb(b) + 1
        s1(b) = s1(b) + zf
        s2(b) = s2(b) + zf*zf
        if (ipconv == -1) moved = moved + 1.d0
      end do
      do b = 1, 3
        s1(b) = s1(b)/dble(nb(b))
        s2(b) = s2(b)/dble(nb(b)) - s1(b)*s1(b)
      end do
      call rowv('redist.stats', (/ real(irep), real(NP) /), 2, &
           (/ real(s1(1)), real(s2(1)), real(s1(2)), real(s2(2)), real(s1(3)), real(s2(3)), &
              real(moved/dble(NP)) /), 7)
    end do
  end subroutine run

end program flexpart_stochastic_redist
