! SPDX-License-Identifier: GPL-3.0
!
! FLEXPART code-to-code reference driver, stage `met`: boundary-layer
! parameters and potential vorticity, wet deposition, OH chemistry, landuse.
!
! Links upstream FLEXPART v10.4 (3d7eebf, GPL-3.0-or-later) VERBATIM:
!   calcpar, calcpar_nests, calcpv, calcpv_nests,
!   interpol_rain, interpol_rain_nests, get_wetscav, wetdepo,
!   wetdepokernel, wetdepokernel_nest, ohreaction, gethourlyOH, assignland
! and what they call (scalev, obukhov, richardson, qvsat, getvdep,
! getvdep_nests, getrb, getrc, raerod, psih, partdep, ew, caldate,
! zenithangle, photo_O1D) plus the modules they read (par_mod, com_mod,
! point_mod, unc_mod, oh_mod). See dev/build_reference_met.sh.
!
! NEST CONFIGURATION. The shipped par_mod.f90 sets maxnests=0, nxmaxn=0,
! nymaxn=0, so nest arrays are zero-sized and the *_nests routines cannot be
! driven. par_mod.f90 is FLEXPART's user-edited configuration file; the build
! compiles a COPY with only that line changed to maxnests=1, nxmaxn=12,
! nymaxn=12. Every other upstream file, and every routine under test, is
! verbatim.
!
! All meteorology is SYNTHETIC, written straight into com_mod / oh_mod (no
! GRIB, no NetCDF, no OH_variables.bin, no IGBP_int1.dat). Every input the
! Rust port needs is echoed as a setup row, except two tables generated by an
! INTEGER formula that the test reproduces exactly (the 360x180x12
! jrate_average and the 1200x600 landuse inventory); each of those is
! cross-checked by a sample row.
!
! Row format, one row per call or setup record:
!     function,a1;a2;...;an,o1;o2;...;om
! real values print with 9 significant digits in the real(4) build and 17 in
! the real(8) build (fmtnum); double precision values always with 17 (rowvd).
!
! Sentinels: -7 marks an output upstream leaves unassigned (tropopause,
! grfraction, vdep with DRYDEP off).
program flexpart_reference_met

  use par_mod
  use com_mod
  use point_mod
  use unc_mod
  use oh_mod
  use class_gribfile
  implicit none

  integer, parameter :: NUVZE = 24, NUVZN = 14
  real, allocatable :: uuh(:,:,:), vvh(:,:,:), pvh(:,:,:)
  real, allocatable :: uuhn(:,:,:,:), vvhn(:,:,:,:), pvhn(:,:,:,:)

  write(*,'(A)') '# FLEXPART stage-met reference, generated by dev/flexpart_reference_met.f90'
  write(*,'(A)') '# upstream: github.com/flexpart/flexpart v10.4 @ 3d7eebf (GPL-3.0-or-later)'
  write(*,'(A)') '# DO NOT EDIT BY HAND -- regenerate with dev/build_reference_met.sh'
  write(*,'(A)') 'function,args,outputs'

  allocate(uuh(0:nxmax-1,0:nymax-1,nuvzmax), vvh(0:nxmax-1,0:nymax-1,nuvzmax), &
           pvh(0:nxmax-1,0:nymax-1,nuvzmax))
  allocate(uuhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests), &
           vvhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests), &
           pvhn(0:nxmaxn-1,0:nymaxn-1,nuvzmax,maxnests))
  numbnests = 1
  call com_mod_allocate_nests()
  call com_mod_allocate_part(40)
  nspec = 1

  call emit_calcpar()
  call emit_calcpv_global()
  call setup_wet()
  call emit_interpol_rain()
  call emit_get_wetscav()
  call emit_wetdepokernel()
  call emit_wetdepo()
  call emit_oh()
  call emit_assignland()

contains

  ! ------------------------------------------------------------------------
  subroutine fmtnum(x, buf)
    double precision, intent(in) :: x
    character(len=32), intent(out) :: buf
    if (kind(1.0) == 4) then
      write(buf,'(ES16.8E3)') x
    else
      write(buf,'(ES25.17E3)') x
    end if
    buf = adjustl(buf)
  end subroutine fmtnum

  subroutine rowv(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    real, intent(in) :: args(nargs), outs(nouts)
    character(len=32768) :: line
    character(len=32) :: buf
    integer :: i, l
    line = trim(name) // ','
    l = len_trim(line)
    do i = 1, nargs
      call fmtnum(dble(args(i)), buf)
      line(l+1:) = trim(adjustl(buf)); l = len_trim(line)
      if (i < nargs) then
        line(l+1:l+1) = ';'; l = l + 1
      end if
    end do
    line(l+1:l+1) = ','; l = l + 1
    do i = 1, nouts
      call fmtnum(dble(outs(i)), buf)
      line(l+1:) = trim(adjustl(buf)); l = len_trim(line)
      if (i < nouts) then
        line(l+1:l+1) = ';'; l = l + 1
      end if
    end do
    write(*,'(A)') line(1:l)
  end subroutine rowv

  subroutine rowvd(name, args, nargs, outs, nouts)
    character(len=*), intent(in) :: name
    integer, intent(in) :: nargs, nouts
    double precision, intent(in) :: args(nargs), outs(nouts)
    character(len=8192) :: line
    character(len=32) :: buf
    integer :: i
    line = trim(name) // ','
    do i = 1, nargs
      write(buf,'(ES25.17E3)') args(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nargs) line = trim(line) // ';'
    end do
    line = trim(line) // ','
    do i = 1, nouts
      write(buf,'(ES25.17E3)') outs(i)
      line = trim(line) // trim(adjustl(buf))
      if (i < nouts) line = trim(line) // ';'
    end do
    write(*,'(A)') trim(line)
  end subroutine rowvd

  ! ------------------------------------------------------------------------
  ! INPUT GENERATION FOR calcpar / calcpv. The synthetic inputs are computed
  ! in DOUBLE PRECISION in both builds and rounded once to real(4) (r4d). The
  ! real(8) build is therefore fed exactly the values the real(4) build (and
  ! the Rust port, which parses the real(4) fixture as f32) is fed, and the
  ! real(4)-vs-real(8) distance of these groups is upstream's single-precision
  ! ARITHMETIC alone, not input rounding. (Evaluating the generator in default
  ! real would give the two builds different inputs.)
  real function r4d(x)
    double precision, intent(in) :: x
    r4d = real(real(x, 4), kind(1.0))
  end function r4d

  ! ------------------------------------------------------------------------
  ! Wesely tables, z0 and the particle size bins (same synthetic pattern as
  ! dev/flexpart_reference_physics.f90), echoed once.
  subroutine fill_wesely()
    integer :: i, j
    do i = 1, 5
      do j = 1, numclass
        ri(i,j)  = 60. + 37.*real(i) + 11.*real(j)
        rac(i,j) = 10. * real(mod(i*j, 7)) * real(j)
        rcl(1,i,j) = 500. + 83.*real(i+j)
        rgs(1,i,j) = 100. + 41.*real(mod(3*i+j, 11))
        rlu(1,i,j) = 1000. + 125.*real(j) - 30.*real(i)
      end do
    end do
    ri(:,1) = 9999.; rac(:,1) = 0.; rlu(1,:,1) = r4d(1.d25)
    ri(:,12) = 9999.; rcl(1,:,12) = r4d(1.d25)
    do j = 1, numclass
      z0(j) = r4d(1.d-4 * 10.d0**(dble(j)*0.27d0))
    end do
    do i = 1, 5
      do j = 1, numclass
        call rowv('wesely', (/ real(i), real(j), ri(i,j), rac(i,j), rcl(1,i,j), &
             rgs(1,i,j), rlu(1,i,j), z0(j) /), 8, (/ 0. /), 1)
      end do
    end do
  end subroutine fill_wesely

  subroutine particle_bins()
    integer :: j
    real :: b(3*ni)
    double precision :: s, fr(ni)
    s = 0.d0
    do j = 1, ni
      vset(1,j)  = r4d(1.d-5 * dble(j)**2.3d0)
      schmi(1,j) = r4d((0.9d0 / dble(j))**0.66667d0)
      fr(j) = dble(j) * exp(-0.35d0 * dble(j))
      s = s + fr(j)
    end do
    do j = 1, ni
      fract(1,j) = r4d(fr(j) / s)
    end do
    do j = 1, ni
      b(j) = vset(1,j); b(ni+j) = schmi(1,j); b(2*ni+j) = fract(1,j)
    end do
    call rowv('particle_bins', b, 3*ni, (/ 0. /), 1)
  end subroutine particle_bins

  ! species kinds for getvdep: 1 gas O3-like, 2 particle, 3 prescribed,
  ! 4 gas HNO3-like
  subroutine set_drydep_species(kind)
    integer, intent(in) :: kind
    reldiff(1) = -1.; density(1) = -1.; dryvel(1) = -1.
    henry(1) = 0.; f0(1) = 0.; rm(1) = 0.
    if (kind == 1) then
      reldiff(1) = r4d(1.6d0); henry(1) = r4d(1.d-2); f0(1) = 1.
    else if (kind == 2) then
      density(1) = 2300.
    else if (kind == 3) then
      dryvel(1) = r4d(4.d-3)
    else
      reldiff(1) = r4d(1.9d0); henry(1) = r4d(1.d14); f0(1) = 0.
    end if
    call rowv('cp.species', (/ real(kind), reldiff(1), henry(1), f0(1), rm(1), &
         density(1), dryvel(1) /), 7, (/ 0. /), 1)
  end subroutine set_drydep_species

  ! ------------------------------------------------------------------------
  ! Hybrid levels of the ECMWF scenarios: level 1 at the surface, pure
  ! pressure aloft. `dup` makes level 11 a copy of level 10.
  subroutine ecmwf_levels(dup)
    logical, intent(in) :: dup
    integer :: k
    double precision :: zk, pref, bd(NUVZE), ad(NUVZE)
    nuvz = NUVZE
    do k = 1, NUVZE
      zk = 40.d0 * dble(k-1)**1.95d0
      pref = 101325.d0 * exp(-zk / 7400.d0)
      bd(k) = (pref / 101325.d0)**2.2d0
      ad(k) = pref - bd(k) * 101325.d0
    end do
    ad(1) = 0.d0; bd(1) = 1.d0
    do k = 1, NUVZE
      akz(k) = r4d(ad(k)); bkz(k) = r4d(bd(k))
    end do
    if (dup) then
      akz(11) = akz(10); bkz(11) = bkz(10)
    end if
    akm(1) = 0.; bkm(1) = 1.
    akm(2) = r4d(0.5d0 * ad(2)); bkm(2) = r4d(0.5d0 * (1.d0 + bd(2)))
  end subroutine ecmwf_levels

  subroutine ncep_levels()
    nuvz = NUVZN
    akz(1:NUVZN) = (/ 105000., 100000., 97500., 95000., 92500., 90000., 85000., &
                      80000., 76000., 73000., 68000., 64000., 60000., 56500. /)
    bkz(1:NUVZN) = 0.
    akm(1:2) = 0.; bkm(1:2) = 0.
  end subroutine ncep_levels

  subroutine echo_levels(sc)
    integer, intent(in) :: sc
    real :: a(2+2*nuvzmax+4)
    integer :: n
    n = nuvz
    a(1) = real(sc); a(2) = real(n)
    a(3:2+n) = akz(1:n); a(3+n:2+2*n) = bkz(1:n)
    a(3+2*n:6+2*n) = (/ akm(1), akm(2), bkm(1), bkm(2) /)
    call rowv('cp.levels', a, 6+2*n, (/ 0. /), 1)
  end subroutine echo_levels

  ! Synthetic column. Returns surface fields and the level profiles for a
  ! point at latitude `latr` (exactly representable in real(4)), column-kind
  ! selectors ix, jy. Computed in double precision, rounded once (r4d).
  subroutine make_column(ix, jy, latr, ps_, tt2_, td2_, sst_, sshf_, ssr_, lsp_, cp_, &
                         sd_, exo_, hmx_, tl, ql, ul, vl)
    integer, intent(in) :: ix, jy
    real, intent(in) :: latr
    real, intent(out) :: ps_, tt2_, td2_, sst_, sshf_, ssr_, lsp_, cp_, sd_, exo_, hmx_
    real, intent(out) :: tl(nuvzmax), ql(nuvzmax), ul(nuvzmax), vl(nuvzmax)
    integer :: k
    double precision :: lat, p, zap, ztr, zs, tsurf, psd, t2d, t, sdd
    double precision, parameter :: d2r = 3.14159265358979d0 / 180.d0
    lat = dble(latr)
    psd = 101300.d0 - 450.d0*dble(ix) - 120.d0*dble(jy)
    if (ix == 2 .and. jy == 4) psd = 78000.d0
    t2d = 300.d0 - 0.35d0*abs(lat) - 0.8d0*dble(ix) + 0.1d0*dble(jy)
    ps_ = r4d(psd); tt2_ = r4d(t2d)
    td2_ = r4d(t2d - 1.5d0 - 1.3d0*dble(mod(ix+jy,4)))
    sst_ = r4d(0.03d0 + 0.07d0*dble(mod(ix*3+jy,5)))
    if (ix == 0 .and. jy == 3) sst_ = 0.
    sshf_ = r4d(-220.d0 + 55.d0*dble(mod(ix+2*jy,7)))
    ssr_ = r4d(40.d0*dble(mod(ix+jy,9)))
    lsp_ = r4d(0.4d0*dble(mod(ix+jy,3)))
    cp_ = r4d(0.3d0*dble(mod(ix*jy,4)))
    sdd = 0.d0
    if (mod(ix+jy,5) == 0) sdd = 0.02d0
    sd_ = r4d(sdd)
    exo_ = r4d(60.d0*dble(mod(ix+3*jy,6)))
    hmx_ = r4d(50.d0 + 700.d0*dble(mod(ix+jy,8)))
    ztr = 15000.d0 - 90.d0*abs(lat)
    zs = -7400.d0 * log(psd / 101325.d0)
    tsurf = t2d + 0.5d0
    do k = 1, nuvz
      p = dble(akz(k)) + dble(bkz(k))*psd
      zap = -7400.d0 * log(p / 101325.d0) - zs
      if (mod(ix+jy, 5) == 3 .or. zap < ztr) then
        t = tsurf - 0.0065d0*zap
      else
        t = tsurf - 0.0065d0*ztr + 0.0015d0*(zap - ztr)
      end if
      if (ix == 1 .and. zap > 500.d0 .and. zap < 1200.d0) t = t + 4.d0
      if (ix == 2 .and. jy == 6) t = t + 18.d0
      tl(k) = r4d(t)
      ql(k) = r4d(0.014d0 * exp(-max(zap,0.d0) / 2500.d0) * (1.d0 - 0.1d0*dble(ix)))
      ul(k) = r4d(3.d0 + 0.0012d0*zap*(1.d0 + 0.2d0*dble(jy)) - 0.5d0*dble(ix))
      vl(k) = r4d(-2.d0 + 0.0007d0*zap*cos(lat*d2r) + 0.3d0*dble(ix*jy) - 0.1d0*dble(k))
    end do
  end subroutine make_column

  subroutine echo_column(sc, ix, jy, s, tl, ql, ul, vl, lu)
    integer, intent(in) :: sc, ix, jy
    real, intent(in) :: s(11), tl(nuvzmax), ql(nuvzmax), ul(nuvzmax), vl(nuvzmax), lu(numclass)
    real :: a(3+11+4*nuvzmax+numclass)
    integer :: n, m
    n = nuvz
    a(1:3) = (/ real(sc), real(ix), real(jy) /)
    a(4:14) = s
    a(15:14+n) = tl(1:n); a(15+n:14+2*n) = ql(1:n)
    a(15+2*n:14+3*n) = ul(1:n); a(15+3*n:14+4*n) = vl(1:n)
    m = 14+4*n
    a(m+1:m+numclass) = lu
    call rowv('cp.column', a, m+numclass, (/ 0. /), 1)
  end subroutine echo_column

  subroutine make_landuse(ix, jy, lu)
    integer, intent(in) :: ix, jy
    real, intent(out) :: lu(numclass)
    integer :: k, iv(numclass)
    do k = 1, numclass
      iv(k) = mod(k*(ix+1) + 2*jy, 5)
      if (k == 3) iv(k) = iv(k) + 1
    end do
    do k = 1, numclass
      lu(k) = r4d(dble(iv(k)) / dble(sum(iv)))
    end do
  end subroutine make_landuse

  ! ------------------------------------------------------------------------
  ! calcpar / calcpar_nests scenarios:
  !   1 mother ECMWF 3 x 13 (60S..60N), gas O3-like, lsubgrid=1, n=2
  !   2 mother NCEP (14 pressure levels up to 565 hPa, a column top just under
  !     the 5000 m tropical altmin), rows 50S, 10S, 30N, 70N, particle,
  !     lsubgrid=0, n=1. The tropical row 10S never reaches altmin, so upstream
  !     searches from the kzmin left by the last column of row 50S: the stale
  !     kzmin is observable there (odd rows carry a near-isothermal layer
  !     above 1800 m, so a tropopause is found from it).
  !   3 nest ECMWF (calcpar_nests -> getvdep_nests, calcpv_nests), gas HNO3-like
  !   4 = fields of 1, prescribed dryvel, lsubgrid=0
  !   5 = fields of 1, DRYDEP false
  ! cp.grid args: sc, kind(0 mother,1 nest), format, nx, ny, dx, dy, xlon0,
  !   ylat0, lsubgrid, drydep(0/1), species kind, mother dy, mother ylat0, n
  ! cp.time (dp): sc, bdate, wftime(n)
  subroutine emit_calcpar()
    integer :: sc, ix, jy, n, fmt, kindsp, i
    real :: s(11), tl(nuvzmax), ql(nuvzmax), ul(nuvzmax), vl(nuvzmax), lu(numclass)
    real :: lat, o(6)
    double precision :: zd, td
    logical :: nest

    call fill_wesely()
    call particle_bins()
    do sc = 1, 5
      nest = (sc == 3)
      lsubgrid = 0
      if (sc == 1 .or. sc == 3) lsubgrid = 1
      DRYDEP = (sc /= 5)
      if (sc == 2) then
        call ncep_levels(); fmt = GRIBFILE_CENTRE_NCEP; n = 1
        nx = 4; ny = 4; dx = 7.5; dy = 40.; xlon0 = 10.; ylat0 = -50.
        bdate = 2459229.5d0; wftime(n) = 21600
        kindsp = 2
      else
        call ecmwf_levels(.false.); fmt = GRIBFILE_CENTRE_ECMWF; n = 2
        nx = 3; ny = 13; dx = 7.5; dy = 10.; xlon0 = 10.; ylat0 = -60.
        bdate = 2459410.5d0; wftime(n) = 10800
        kindsp = 1
        if (sc == 3) kindsp = 4
        if (sc == 4) kindsp = 3
      end if
      nxmin1 = nx - 1; nymin1 = ny - 1
      xglobal = .false.; sglobal = .false.; nglobal = .false.
      if (nest) then
        nxn(1) = 6; nyn(1) = 5; dxn(1) = 0.25; dyn(1) = 0.5
        xlon0n(1) = 12.; ylat0n(1) = 30.
      end if
      call echo_levels(sc)
      call set_drydep_species(kindsp)
      if (nest) then
        call rowv('cp.grid', (/ real(sc), 1., real(fmt), real(nxn(1)), real(nyn(1)), &
             dxn(1), dyn(1), xlon0n(1), ylat0n(1), real(lsubgrid), 1., real(kindsp), &
             dy, ylat0, real(n) /), 15, (/ 0. /), 1)
      else
        call rowv('cp.grid', (/ real(sc), 0., real(fmt), real(nx), real(ny), dx, dy, &
             xlon0, ylat0, real(lsubgrid), merge(1., 0., DRYDEP), real(kindsp), dy, ylat0, &
             real(n) /), 15, (/ 0. /), 1)
      end if
      call rowvd('cp.time', (/ dble(sc), bdate, dble(wftime(n)) /), 3, (/ 0.d0 /), 1)

      if (nest) then
        do jy = 0, nyn(1)-1
          do ix = 0, nxn(1)-1
            lat = ylat0n(1) + real(jy)*dyn(1)
            call make_column(ix, jy, lat, s(1), s(2), s(3), s(4), s(5), s(6), s(7), &
                 s(8), s(9), s(10), s(11), tl, ql, ul, vl)
            call make_landuse(ix, jy, lu)
            psn(ix,jy,1,n,1) = s(1); tt2n(ix,jy,1,n,1) = s(2); td2n(ix,jy,1,n,1) = s(3)
            surfstrn(ix,jy,1,n,1) = s(4); sshfn(ix,jy,1,n,1) = s(5)
            ssrn(ix,jy,1,n,1) = s(6); lsprecn(ix,jy,1,n,1) = s(7)
            convprecn(ix,jy,1,n,1) = s(8); sdn(ix,jy,1,n,1) = s(9)
            excessoron(ix,jy,1) = s(10)
            tthn(ix,jy,1:nuvz,n,1) = tl(1:nuvz); qvhn(ix,jy,1:nuvz,n,1) = ql(1:nuvz)
            uuhn(ix,jy,1:nuvz,1) = ul(1:nuvz); vvhn(ix,jy,1:nuvz,1) = vl(1:nuvz)
            xlandusen(ix,jy,:,1) = lu
            tropopausen(ix,jy,1,n,1) = -7.
            call echo_column(sc, ix, jy, s, tl, ql, ul, vl, lu)
          end do
        end do
        call calcpar_nests(n, uuhn, vvhn, pvhn, fmt)
        do jy = 0, nyn(1)-1
          do ix = 0, nxn(1)-1
            o = (/ ustarn(ix,jy,1,n,1), olin(ix,jy,1,n,1), hmixn(ix,jy,1,n,1), &
                   wstarn(ix,jy,1,n,1), vdepn(ix,jy,1,n,1), tropopausen(ix,jy,1,n,1) /)
            call rowv('calcpar', (/ real(sc), real(ix), real(jy) /), 3, o, 6)
            call rowv('calcpv', (/ real(sc), real(ix), real(jy) /), 3, &
                 pvhn(ix,jy,1:nuvz,1), nuvz)
          end do
        end do
      else
        do jy = 0, ny-1
          do ix = 0, nx-1
            lat = ylat0 + real(jy)*dy
            call make_column(ix, jy, lat, s(1), s(2), s(3), s(4), s(5), s(6), s(7), &
                 s(8), s(9), s(10), s(11), tl, ql, ul, vl)
            if (sc == 2 .and. ix == 1 .and. jy == 2) s(1) = 72000.
            if (sc == 2 .and. ix == 3 .and. jy == 3) s(1) = 50000.
            if (sc == 2) then
              ! NCEP levels: recompute the profile on the pressure levels with
              ! a shallow isothermal layer in odd rows
              do i = 1, nuvz
                zd = -7400.d0 * log(dble(akz(i)) / dble(s(1)))
                td = dble(s(2)) + 0.5d0 - 0.0065d0*zd
                if (mod(jy,2) == 1 .and. zd > 1800.d0) td = dble(s(2)) + 0.5d0 &
                     - 0.0065d0*1800.d0 + 0.0005d0*(zd - 1800.d0)
                tl(i) = r4d(td)
              end do
            end if
            call make_landuse(ix, jy, lu)
            ps(ix,jy,1,n) = s(1); tt2(ix,jy,1,n) = s(2); td2(ix,jy,1,n) = s(3)
            surfstr(ix,jy,1,n) = s(4); sshf(ix,jy,1,n) = s(5); ssr(ix,jy,1,n) = s(6)
            lsprec(ix,jy,1,n) = s(7); convprec(ix,jy,1,n) = s(8); sd(ix,jy,1,n) = s(9)
            excessoro(ix,jy) = s(10); hmix(ix,jy,1,n) = s(11)
            tth(ix,jy,1:nuvz,n) = tl(1:nuvz); qvh(ix,jy,1:nuvz,n) = ql(1:nuvz)
            uuh(ix,jy,1:nuvz) = ul(1:nuvz); vvh(ix,jy,1:nuvz) = vl(1:nuvz)
            xlanduse(ix,jy,:) = lu
            tropopause(ix,jy,1,n) = -7.
            vdep(ix,jy,1,n) = -7.
            if (sc <= 3) call echo_column(sc, ix, jy, s, tl, ql, ul, vl, lu)
          end do
        end do
        call calcpar(n, uuh, vvh, pvh, fmt)
        do jy = 0, ny-1
          do ix = 0, nx-1
            o = (/ ustar(ix,jy,1,n), oli(ix,jy,1,n), hmix(ix,jy,1,n), &
                   wstar(ix,jy,1,n), vdep(ix,jy,1,n), tropopause(ix,jy,1,n) /)
            call rowv('calcpar', (/ real(sc), real(ix), real(jy) /), 3, o, 6)
            call rowv('calcpv', (/ real(sc), real(ix), real(jy) /), 3, pvh(ix,jy,1:nuvz), nuvz)
          end do
        end do
      end if
      call rowv('calcpar.z0water', (/ real(sc) /), 1, (/ z0(7) /), 1)
      ! restore the table entry calcpar overwrote
      z0(7) = r4d(1.d-4 * 10.d0**(7.d0*0.27d0))
    end do
  end subroutine emit_calcpar

  ! ------------------------------------------------------------------------
  ! calcpv on global grids (calcpv called directly):
  !   6 xglobal + sglobal + nglobal: 5 x 7 points, 90 x 30 degrees, poles at
  !     rows 0 and 6, column 4 a copy of column 0; level 11 duplicates level
  !     10; row 2 uniform in x; a +20 K anomaly at (2,4)
  !   7 xglobal only, 5 x 5 points, 45S..45N
  subroutine emit_calcpv_global()
    integer :: sc, ix, jy, k, ixs
    real :: s(11), tl(nuvzmax), ql(nuvzmax), ul(nuvzmax), vl(nuvzmax), lu(numclass), lat
    integer :: n
    n = 1
    do sc = 6, 7
      call ecmwf_levels(.true.)
      nx = 5; dx = 90.; xlon0 = 0.
      if (sc == 6) then
        ny = 7; dy = 30.; ylat0 = -90.
        xglobal = .true.; sglobal = .true.; nglobal = .true.
      else
        ny = 5; dy = 22.5; ylat0 = -45.
        xglobal = .true.; sglobal = .false.; nglobal = .false.
      end if
      nxmin1 = nx - 1; nymin1 = ny - 1
      call echo_levels(sc)
      call rowv('cp.grid', (/ real(sc), 0., real(GRIBFILE_CENTRE_ECMWF), real(nx), real(ny), &
           dx, dy, xlon0, ylat0, 0., 0., 0., dy, ylat0, real(n) /), 15, (/ 0. /), 1)
      call rowv('cp.global', (/ real(sc), merge(1.,0.,xglobal), merge(1.,0.,sglobal), &
           merge(1.,0.,nglobal) /), 4, (/ 0. /), 1)
      lu = 0.
      do jy = 0, ny-1
        do ix = 0, nx-1
          ixs = ix
          if (ix == nx-1) ixs = 0          ! cyclic copy
          if (jy == 2) ixs = 0             ! uniform row
          lat = ylat0 + real(jy)*dy
          call make_column(ixs, jy, lat, s(1), s(2), s(3), s(4), s(5), s(6), s(7), &
               s(8), s(9), s(10), s(11), tl, ql, ul, vl)
          tl(11) = tl(10)
          do k = 1, nuvz
            if (ixs == 2 .and. jy == 4) tl(k) = r4d(dble(tl(k)) + 20.d0)
            ul(k) = r4d(dble(ul(k)) + 2.d0*sin(dble(ixs)) * dble(k) / 10.d0)
          end do
          ps(ix,jy,1,n) = s(1)
          tth(ix,jy,1:nuvz,n) = tl(1:nuvz)
          uuh(ix,jy,1:nuvz) = ul(1:nuvz); vvh(ix,jy,1:nuvz) = vl(1:nuvz)
          call echo_column(sc, ix, jy, s, tl, ql, ul, vl, lu)
        end do
      end do
      pvh = -7.
      call calcpv(n, uuh, vvh, pvh)
      do jy = 0, ny-1
        do ix = 0, nx-1
          call rowv('calcpv', (/ real(sc), real(ix), real(jy) /), 3, pvh(ix,jy,1:nuvz), nuvz)
        end do
      end do
    end do
    xglobal = .false.; sglobal = .false.; nglobal = .false.
  end subroutine emit_calcpv_global

  ! ------------------------------------------------------------------------
  ! Wet-deposition met: mother 6 x 5, one nest 6 x 6 at x in (1.5, 4),
  ! y in (1, 3.5), resolution 2; 6 levels; two memory slots.
  ! wet.field: grid(0/1), slot, id (1 lsprec 2 convprec 3 tcc 4 ctwc) ; values
  ! wet.clouds: grid, slot, k ; values      wet.tt: grid, slot, k ; values
  subroutine setup_wet()
    integer :: g, m, ix, jy, k, nxg, nyg, typ
    real :: v(144), lsv(10), cpv(8), t0
    integer(kind=1) :: pat(6,6)
    lsv = (/ 0., 0.005, 1., 3., 8., 20., 25., 0.5, 5., 12. /)
    cpv = (/ 0., 1., 3.5, 8., 21., 0.009, 0.3, 2. /)
    ! cloud code patterns by level (k = 1..6)
    pat(:,1) = (/ 5, 5, 2, 2, 1, 0 /)
    pat(:,2) = (/ 4, 4, 3, 3, 0, 0 /)
    pat(:,3) = (/ 0, 0, 0, 0, 0, 0 /)
    pat(:,4) = (/ 1, 1, 1, 0, 0, 0 /)
    pat(:,5) = (/ 5, 2, 3, 0, 0, 0 /)
    pat(:,6) = (/ 4, 5, 4, 2, 3, 1 /)
    nz = 6
    height(1:6) = (/ 0., 300., 900., 1800., 3200., 5000. /)
    call rowv('wet.height', height(1:6), 6, (/ 0. /), 1)
    nx = 6; ny = 5; nxmin1 = 5; nymin1 = 4
    dx = 0.5; dy = 0.5; xlon0 = 0.; ylat0 = 0.
    xln(1) = 1.5; xrn(1) = 4.0; yln(1) = 1.0; yrn(1) = 3.5
    xresoln(1) = 2.; yresoln(1) = 2.
    nxn(1) = 6; nyn(1) = 6
    call rowv('wet.nest', (/ xln(1), xrn(1), yln(1), yrn(1), xresoln(1), yresoln(1), &
         real(nxn(1)), real(nyn(1)) /), 8, (/ 0. /), 1)
    do g = 0, 1
      if (g == 0) then
        nxg = nx; nyg = ny
      else
        nxg = nxn(1); nyg = nyn(1)
      end if
      do m = 1, 2
        do jy = 0, nyg-1
          do ix = 0, nxg-1
            k = 1 + mod(ix + 2*jy + 3*m + 5*g, 10)
            if (g == 0) then
              lsprec(ix,jy,1,m) = lsv(k)
              convprec(ix,jy,1,m) = cpv(1 + mod(ix*3 + jy + m + g, 8))
              tcc(ix,jy,1,m) = 0.25 * real(mod(ix + jy + m, 5))
              ctwc(ix,jy,m) = 1.e-4 * real(1 + mod(ix + 4*jy, 6))
            else
              lsprecn(ix,jy,1,m,1) = lsv(k)
              convprecn(ix,jy,1,m,1) = cpv(1 + mod(ix*3 + jy + m + g, 8))
              tccn(ix,jy,1,m,1) = 0.25 * real(mod(ix + jy + m + 1, 5))
              ctwcn(ix,jy,m,1) = 2.e-4 * real(1 + mod(ix + 3*jy, 5))
            end if
          end do
        end do
        ! echo the four 2-d fields
        do k = 1, 4
          do jy = 0, nyg-1
            do ix = 0, nxg-1
              if (g == 0) then
                select case (k)
                case (1); v(1+ix+nxg*jy) = lsprec(ix,jy,1,m)
                case (2); v(1+ix+nxg*jy) = convprec(ix,jy,1,m)
                case (3); v(1+ix+nxg*jy) = tcc(ix,jy,1,m)
                case (4); v(1+ix+nxg*jy) = ctwc(ix,jy,m)
                end select
              else
                select case (k)
                case (1); v(1+ix+nxg*jy) = lsprecn(ix,jy,1,m,1)
                case (2); v(1+ix+nxg*jy) = convprecn(ix,jy,1,m,1)
                case (3); v(1+ix+nxg*jy) = tccn(ix,jy,1,m,1)
                case (4); v(1+ix+nxg*jy) = ctwcn(ix,jy,m,1)
                end select
              end if
            end do
          end do
          call rowv('wet.field', (/ real(g), real(m), real(k) /), 3, v, nxg*nyg)
        end do
        ! clouds and temperature per level
        do k = 1, nz
          do jy = 0, nyg-1
            do ix = 0, nxg-1
              typ = 1 + mod(ix + jy*2 + m + g, 6)
              t0 = 262. + 4.*real(mod(ix + 3*jy + g, 7))
              if (g == 0) then
                clouds(ix,jy,k,m) = pat(k,typ)
                cloudsh(ix,jy,m) = 1000
                tt(ix,jy,k,m) = t0 - 0.0065*height(k)
                if (ix == 2 .and. jy == 1) tt(ix,jy,k,m) = 273.
                if (ix == 3 .and. jy == 3) tt(ix,jy,k,m) = 253.
              else
                cloudsn(ix,jy,k,m,1) = pat(k,typ)
                cloudshn(ix,jy,m,1) = 1000
                ttn(ix,jy,k,m,1) = t0 - 0.0065*height(k) - 3.
              end if
            end do
          end do
          do jy = 0, nyg-1
            do ix = 0, nxg-1
              if (g == 0) then
                v(1+ix+nxg*jy) = real(clouds(ix,jy,k,m))
              else
                v(1+ix+nxg*jy) = real(cloudsn(ix,jy,k,m,1))
              end if
            end do
          end do
          call rowv('wet.clouds', (/ real(g), real(m), real(k) /), 3, v, nxg*nyg)
          do jy = 0, nyg-1
            do ix = 0, nxg-1
              if (g == 0) then
                v(1+ix+nxg*jy) = tt(ix,jy,k,m)
              else
                v(1+ix+nxg*jy) = ttn(ix,jy,k,m,1)
              end if
            end do
          end do
          call rowv('wet.tt', (/ real(g), real(m), real(k) /), 3, v, nxg*nyg)
        end do
      end do
    end do
  end subroutine setup_wet

  ! ------------------------------------------------------------------------
  ! interpol_rain / interpol_rain_nests at points on nodes, inside cells,
  ! on and beyond the last grid line (moved in place) and in (-1, 0).
  ! args: grid, slot, xt, yt ; outs: lsp, convp, cc, xt after, yt after
  subroutine emit_interpol_rain()
    real :: xs(8), ys(6), xt, yt, y1, y2, y3
    integer :: g, m, i, j
    xs = (/ 0., 0.5, 2.25, 3., 4.9999, 5., 5.7, -0.3 /)
    ys = (/ 0., 1.75, 3.5, 4., 4.2, -0.6 /)
    do g = 0, 1
      do m = 1, 2
        do i = 1, 8
          do j = 1, 6
            xt = xs(i); yt = ys(j)
            if (g == 0) then
              call interpol_rain(lsprec, convprec, tcc, nxmax, nymax, 1, nx, ny, m, &
                   xt, yt, 1, 0, 0, 0, y1, y2, y3)
            else
              call interpol_rain_nests(lsprecn, convprecn, tccn, nxmaxn, nymaxn, 1, &
                   maxnests, 1, nxn, nyn, m, xt, yt, 1, 0, 0, 0, y1, y2, y3)
            end if
            call rowv('interpol_rain', (/ real(g), real(m), xs(i), ys(j) /), 4, &
                 (/ y1, y2, y3, xt, yt /), 5)
          end do
        end do
      end do
    end do
  end subroutine emit_interpol_rain

  ! ------------------------------------------------------------------------
  ! Species table for the wet-deposition sweeps:
  ! dquer, weta_gas, wetb_gas, crain_aero, csnow_aero, ccn_aero, in_aero, henry
  subroutine wet_species(isp, sp)
    integer, intent(in) :: isp
    real, intent(out) :: sp(8)
    select case (isp)
    case (1); sp = (/ -1., 1.e-4, 0.62, 0., 0., -1., -1., 1.e5 /)      ! gas, below + Henry
    case (2); sp = (/ -1., 0., 0., 0., 0., -1., -1., 0. /)             ! gas, nothing
    case (3); sp = (/ 0.4, 0., 0., 1., 1., 0.9, 0.1, 0. /)             ! aerosol
    case (4); sp = (/ 25., 0., 0., 0.5, 0., -1., 0.2, 0. /)            ! coarse, rain only, ccn<0
    case (5); sp = (/ 2., 0., 0., 0., 0.8, -1., -1., 0. /)             ! snow only, in-cloud off
    case (6); sp = (/ -1., 0., 0.5, 0., 0., -1., -1., 1.e14 /)         ! gas B only, very soluble
    end select
  end subroutine wet_species

  subroutine set_species(sp)
    real, intent(in) :: sp(8)
    dquer(1) = sp(1); weta_gas(1) = sp(2); wetb_gas(1) = sp(3)
    crain_aero(1) = sp(4); csnow_aero(1) = sp(5); ccn_aero(1) = sp(6)
    in_aero(1) = sp(7); henry(1) = sp(8)
  end subroutine set_species

  ! get_wetscav over species x positions x times x readclouds (readclouds
  ! only with memind = (1,2)).
  ! wet.species: id ; dquer, weta, wetb, crain, csnow, ccn, in, henry
  ! args: itime, ltsample, memind(1), readclouds (= readclouds_nest), x, y, z,
  !       species id
  ! outs: wetscav, grfraction(1) (-7 if unassigned), d blc_count, d inc_count,
  !       ccn_aero after, in_aero after
  subroutine emit_get_wetscav()
    real :: px(14), py(14), pz(14), sp(8), grf(3), ws, a(8)
    integer :: itimes(3), lts(3), ip, isp, it, im, irc
    integer(selected_int_kind(16)) :: blc(1), inc(1), b0, i0
    ! positions: nodes, cell interiors, last line, nest interior
    px = (/ 0., 1., 2., 3., 4., 5., 2.5, 0.75, 1., 4.5, 2.0, 2.75, 3.25, 1.75 /)
    py = (/ 0., 1., 1., 3., 2., 4., 0.5, 3.75, 4., 0.25, 2.0, 1.25, 3.0, 1.5 /)
    pz = (/ 100., 650., 299.99, 300., 1500., 4999., 50., 2500., 900., 4000., 1200., 350., &
            2000., 800. /)
    itimes = (/ 3600, 9000, 5850 /)
    lts = (/ 900, 900, 899 /)
    memtime(1) = 0; memtime(2) = 10801
    do isp = 1, 6
      call wet_species(isp, sp)
      call rowv('wet.species', (/ real(isp) /), 1, sp, 8)
    end do
    do irc = 0, 1
      readclouds = (irc == 1); readclouds_nest(1) = (irc == 1)
      do im = 1, 2 - irc
        memind(1) = im; memind(2) = 3 - im
        do it = 1, 3
          do isp = 1, 6
            do ip = 1, 14
              call wet_species(isp, sp)
              call set_species(sp)
              xtra1(1) = dble(px(ip)); ytra1(1) = dble(py(ip)); ztra1(1) = pz(ip)
              grf = -7.
              blc = 0; inc = 0
              call get_wetscav(itimes(it), lts(it), 0, 1, 1, grf, inc, blc, ws)
              a = (/ real(itimes(it)), real(lts(it)), real(im), real(irc), &
                     px(ip), py(ip), pz(ip), real(isp) /)
              call rowv('get_wetscav', a, 8, (/ ws, grf(1), real(blc(1)), real(inc(1)), &
                   ccn_aero(1), in_aero(1) /), 6)
            end do
          end do
        end do
      end do
    end do
    readclouds = .false.; readclouds_nest(1) = .false.
    memind(1) = 1; memind(2) = 2
  end subroutine emit_get_wetscav

  ! ------------------------------------------------------------------------
  ! Output grids: mother 8 x 6 (xoutshift 0.25, youtshift -0.4, 1.0 x 0.75),
  ! nest 7 x 5; 2 release-point slots.
  subroutine setup_outgrids()
    numxgrid = 8; numygrid = 6
    xoutshift = 0.25; youtshift = -0.4; dxout = 1.0; dyout = 0.75
    numxgridn = 7; numygridn = 5
    xoutshiftn = -0.6; youtshiftn = -0.45; dxoutn = 0.5; dyoutn = 0.5
    maxpointspec_act = 2
    nageclass = 1
    if (.not. allocated(wetgridunc)) then
      allocate(wetgridunc(0:numxgrid-1,0:numygrid-1,maxspec,maxpointspec_act,nclassunc,maxageclass))
      allocate(wetgriduncn(0:numxgridn-1,0:numygridn-1,maxspec,maxpointspec_act,nclassunc,maxageclass))
    end if
    wetgridunc = 0.; wetgriduncn = 0.
    call rowv('out.grid', (/ dx, dy, xoutshift, youtshift, dxout, dyout, real(numxgrid), &
         real(numygrid), xoutshiftn, youtshiftn, dxoutn, dyoutn, real(numxgridn), &
         real(numygridn) /), 14, (/ 0. /), 1)
  end subroutine setup_outgrids

  subroutine dump_grids(tag, run)
    character(len=*), intent(in) :: tag
    integer, intent(in) :: run
    real :: v(48)
    integer :: kp, ix, jy
    do kp = 1, maxpointspec_act
      do jy = 0, numygrid-1
        do ix = 0, numxgrid-1
          v(1+ix+numxgrid*jy) = real(wetgridunc(ix,jy,1,kp,1,1))
        end do
      end do
      call rowv(tag, (/ real(run), 0., real(kp) /), 3, v, numxgrid*numygrid)
      do jy = 0, numygridn-1
        do ix = 0, numxgridn-1
          v(1+ix+numxgridn*jy) = real(wetgriduncn(ix,jy,1,kp,1,1))
        end do
      end do
      call rowv(tag, (/ real(run), 1., real(kp) /), 3, v, numxgridn*numygridn)
    end do
  end subroutine dump_grids

  ! wetdepokernel (mother) and wetdepokernel_nest at positions straddling the
  ! 0.5 switch, the grid edges and the (-1,-0.5] band where int() truncation
  ! gives a negative weight. lusekerneloutput is a par_mod PARAMETER (.true.
  ! as shipped), so the mother routine's direct-attribution branch cannot be
  ! driven without a second configuration change and is not swept.
  ! args: variant (0 mother, 2 nest), x, y, deposit, kp
  ! outs: the grid slice (ks=1, kp) after the call, grid zeroed before
  subroutine emit_wetdepokernel()
    real :: xs(12), ys(12), dep(maxspec)
    integer :: iv, i, j, kp
    ! xl = (0.5 x + 0.25)/1, yl = (0.5 y - 0.4)/0.75
    xs = (/ 4.5, 4.6, 0.1, -1.3, -2.2, 14.9, 15.6, -0.5, 7.25, 3.3, -1.0, 8.0 /)
    ys = (/ 2.0, 1.5, -0.2, 9.3, 10.1, 4.85, -1.1, 0.8, 3.05, -1.7, 6.3, 0.55 /)
    dx = 0.5; dy = 0.5
    call setup_outgrids()
    do iv = 0, 2, 2
      do i = 1, 12
        do j = i, i
          kp = 1 + mod(i, 2)
          dep(1) = 1.5 + 0.25*real(i) - 0.125*real(j)
          wetgridunc = 0.; wetgriduncn = 0.
          if (iv < 2) then
            call wetdepokernel(1, dep, xs(i), ys(j), 1, kp)
            call rowv('wetdepokernel', (/ real(iv), xs(i), ys(j), dep(1), real(kp) /), 5, &
                 real(wetgridunc(:,:,1,kp,1,1)), numxgrid*numygrid)
          else
            call wetdepokernel_nest(1, dep, xs(i), ys(j), 1, kp)
            call rowv('wetdepokernel', (/ real(iv), xs(i), ys(j), dep(1), real(kp) /), 5, &
                 real(wetgriduncn(:,:,1,kp,1,1)), numxgridn*numygridn)
          end if
        end do
      end do
    end do
  end subroutine emit_wetdepokernel

  ! ------------------------------------------------------------------------
  ! wetdepo over 14 particles, four runs:
  !   1 forward, itime <= loutnext, nested output, per-release output,
  !     aerosol species 3, decay 1e-5
  !   2 forward, itime > loutnext, no nested output, gas species 1
  !   3 backward, WETDEPSPEC false
  !   4 backward, aerosol species 3 (masses only; no gridding backward)
  ! wd.particle: run, jpart, itra1, itramem, x, y, z, npoint, nclass, mass
  ! wd.run: run, itime, ltsample, loutnext, loutstep, ldirect, kernel, nested,
  !         per-release, decay, wetdepspec, species id, memind(1)
  ! outs: wetdepo.mass (run, jpart ; mass), wetdepo.grid (run, grid, kp ; values),
  !       wetdepo.counts (run ; tot_blc, tot_inc)
  subroutine emit_wetdepo()
    real :: px(14), py(14), pz(14), sp(8)
    integer :: it1(14), run, j, isp
    integer :: itime, ltsample, loutnext
    px = (/ 0.5, 1.2, 2.25, 3.0, 4.6, 1.8, 2.6, 3.4, 0.2, 4.95, 2.1, 1.1, 3.9, 2.9 /)
    py = (/ 0.5, 2.3, 1.75, 3.1, 0.4, 1.3, 2.2, 1.6, 3.9, 3.3, 2.9, 0.9, 1.1, 3.4 /)
    pz = (/ 120., 640., 299., 1700., 2800., 450., 1000., 2100., 60., 4500., 880., 310., &
            3300., 1500. /)
    it1 = (/ 0, 600, 1200, -999999999, 5400, 7200, 9000, 100, 2000, 4000, 5000, &
             6000, 5400, 7000 /)
    dx = 0.5; dy = 0.5
    call setup_outgrids()
    memtime(1) = 0; memtime(2) = 10801
    memind(1) = 2; memind(2) = 1
    loutstep = 10800
    lage(1) = 86400
    numpart = 14
    do run = 1, 4
      if (run == 1) then
        ldirect = 1; itime = 7200; ltsample = 900; loutnext = 10800
        nested_output = 1; ioutputforeachrelease = 1
        decay(1) = 1.e-5; WETDEPSPEC(1) = .true.; isp = 3
      else if (run == 2) then
        ldirect = 1; itime = 14400; ltsample = 900; loutnext = 10800
        nested_output = 0; ioutputforeachrelease = 0
        decay(1) = 0.; WETDEPSPEC(1) = .true.; isp = 1
      else if (run == 3) then
        ldirect = -1; itime = 3600; ltsample = 900; loutnext = 0
        nested_output = 0; ioutputforeachrelease = 0
        decay(1) = 0.; WETDEPSPEC(1) = .false.; isp = 3
      else
        ldirect = -1; itime = 3600; ltsample = 900; loutnext = 0
        nested_output = 0; ioutputforeachrelease = 0
        decay(1) = 2.e-6; WETDEPSPEC(1) = .true.; isp = 3
      end if
      call wet_species(isp, sp)
      call set_species(sp)
      wetgridunc = 0.; wetgriduncn = 0.
      tot_blc_count = 0; tot_inc_count = 0
      call rowv('wd.run', (/ real(run), real(itime), real(ltsample), real(loutnext), &
           real(loutstep), real(ldirect), 1., real(nested_output), &
           real(ioutputforeachrelease), decay(1), merge(1.,0.,WETDEPSPEC(1)), real(isp), &
           real(memind(1)) /), 13, (/ 0. /), 1)
      do j = 1, 14
        itra1(j) = it1(j)
        if (ldirect == -1 .and. it1(j) /= -999999999) itra1(j) = 9000 - it1(j)
        itramem(j) = 0
        xtra1(j) = dble(px(j)); ytra1(j) = dble(py(j)); ztra1(j) = pz(j)
        npoint(j) = 1 + mod(j, 2); nclass(j) = 1
        xmass1(j,1) = 1.0 + 0.1*real(j)
        call rowv('wd.particle', (/ real(run), real(j), real(itra1(j)), real(itramem(j)), &
             px(j), py(j), pz(j), real(npoint(j)), real(nclass(j)), xmass1(j,1) /), 10, &
             (/ 0. /), 1)
      end do
      call wetdepo(itime, ltsample, loutnext)
      do j = 1, 14
        call rowv('wetdepo.mass', (/ real(run), real(j) /), 2, (/ xmass1(j,1) /), 1)
      end do
      call dump_grids('wetdepo.grid', run)
      call rowv('wetdepo.counts', (/ real(run) /), 1, &
           (/ real(tot_blc_count(1)), real(tot_inc_count(1)) /), 2)
    end do
    ldirect = 1
    memind(1) = 1; memind(2) = 2
  end subroutine emit_wetdepo

  ! ------------------------------------------------------------------------
  ! OH: an 8 x 6 x 4 climatology; jrate_average from an integer formula
  ! (exact in f32), checked by oh.jrcheck rows.
  real function jr_formula(i, j, m)
    integer, intent(in) :: i, j, m
    jr_formula = real(mod(i*7 + j*13 + m*5, 11)) / 1048576.
  end function jr_formula

  subroutine dump_oh_state(tag, a1, a2)
    character(len=*), intent(in) :: tag
    real, intent(in) :: a1, a2
    real :: v(2 + 2*8*6*4)
    integer :: ix, jy, kz, h, c
    v(1) = memOHtime(1); v(2) = memOHtime(2)
    c = 2
    do h = 1, 2
      do kz = 1, nzOH
        do jy = 1, nyOH
          do ix = 1, nxOH
            c = c + 1
            v(c) = OH_hourly(ix,jy,kz,h)
          end do
        end do
      end do
    end do
    call rowv(tag, (/ a1, a2 /), 2, v, c)
  end subroutine dump_oh_state

  subroutine emit_oh()
    integer :: i, j, m, kz, ix, jy, k, run, its(10), itsb(4)
    real :: v(120), lt
    real :: px(10), py(10), pz(10)
    integer :: it1(10)
    nxOH = 8; nyOH = 6; nzOH = 4
    allocate(lonOH(nxOH), latOH(nyOH), altOH(nzOH), OH_field(nxOH,nyOH,nzOH,12), &
             OH_hourly(nxOH,nyOH,nzOH,2))
    lonOH = (/ -158., -112.5, -67.5, -22.5, 22.5, 67.5, 112.5, 157.3 /)
    latOH = (/ -75., -45., -15., 15., 45., 75. /)
    altOH = (/ 500., 1500., 3500., 7000. /)
    do i = 1, 360
      lonjr(i) = -179.5 + real(i-1)
    end do
    do j = 1, 180
      latjr(j) = -89.5 + real(j-1)
    end do
    do m = 1, 12
      do j = 1, 180
        do i = 1, 360
          jrate_average(i,j,m) = jr_formula(i, j, m)
        end do
      end do
    end do
    do m = 1, 12
      do kz = 1, nzOH
        do jy = 1, nyOH
          do ix = 1, nxOH
            OH_field(ix,jy,kz,m) = 1.e5 * real(1 + mod(ix + 2*jy + 3*kz + m, 7)) &
                 * (1. + 0.1*real(m))
          end do
        end do
      end do
    end do
    call rowv('oh.coords', (/ lonOH, latOH, altOH /), nxOH+nyOH+nzOH, (/ 0. /), 1)
    do m = 1, 12
      do kz = 1, nzOH
        call rowv('oh.field', (/ real(m), real(kz) /), 2, &
             reshape(OH_field(:,:,kz,m), (/ nxOH*nyOH /)), nxOH*nyOH)
      end do
    end do
    call rowv('oh.lonjr', lonjr, 360, (/ 0. /), 1)
    call rowv('oh.latjr', latjr, 180, (/ 0. /), 1)
    do k = 1, 40
      i = 1 + mod(k*37, 360); j = 1 + mod(k*53, 180); m = 1 + mod(k, 12)
      call rowv('oh.jrcheck', (/ real(i), real(j), real(m) /), 3, &
           (/ jrate_average(i,j,m) /), 1)
    end do

    ! gethourlyOH sequences
    bdate = 2459246.1666666665d0   ! 2021-01-31 16:00 (juldate)
    call rowvd('oh.bdate', (/ bdate /), 1, (/ 0.d0 /), 1)
    ! hourly steps up to 32400 s cross into February (m2 = 2); 60000 is a
    ! jump of more than an hour (only one step is taken); -100 re-initialises
    its = (/ 0, 1800, 3600, 7200, 14400, 21600, 28800, 32400, 60000, -100 /)
    memOHtime = 0.; OH_hourly = 0.
    ldirect = 1
    do i = 1, 10
      call gethourlyOH(its(i))
      call dump_oh_state('gethourlyOH', real(ldirect), real(its(i)))
    end do
    itsb = (/ 0, -1800, -3600, -7200 /)
    memOHtime = 0.; OH_hourly = 0.
    ldirect = -1
    do i = 1, 4
      call gethourlyOH(itsb(i))
      call dump_oh_state('gethourlyOH', real(ldirect), real(itsb(i)))
    end do

    ! ohreaction: state after the initial forward call (fields at 0 and 3600 s)
    ldirect = 1
    memOHtime = 0.; OH_hourly = 0.
    call gethourlyOH(0)
    call dump_oh_state('oh.state', 0., 0.)
    nx = 10; ny = 12; nxmin1 = 9; nymin1 = 11
    dx = 10.; dy = 5.; xlon0 = 100.; ylat0 = -40.
    nz = 6
    height(1:6) = (/ 0., 250., 800., 2000., 4500., 9000. /)
    memtime(1) = 0; memtime(2) = 10801
    xln(1) = 2.5; xrn(1) = 5.0; yln(1) = 3.0; yrn(1) = 6.0
    xresoln(1) = 2.; yresoln(1) = 2.
    call rowv('oh.met', (/ dx, dy, xlon0, ylat0, real(nx), real(ny), height(1:6), &
         xln(1), xrn(1), yln(1), yrn(1), xresoln(1), yresoln(1) /), 18, (/ 0. /), 1)
    do m = 1, 2
      do k = 1, 6
        do jy = 0, ny-1
          do ix = 0, nx-1
            tt(ix,jy,k,m) = 285. + 1.5*real(ix) - 0.8*real(jy) - 0.006*height(k) &
                 + 7.*real(m-1)
            v(1+ix+nx*jy) = tt(ix,jy,k,m)
          end do
        end do
        call rowv('oh.tt', (/ real(m), real(k) /), 2, v, nx*ny)
      end do
    end do
    px = (/ 0.5, 3.2, 8.9, 4.0, 6.3, 1.1, 9.5, 2.0, 7.7, 3.6 /)
    py = (/ 0.5, 4.4, 2.1, 5.2, 10.6, 7.3, 11.2, 0.2, 6.6, 3.5 /)
    pz = (/ 100., 900., 2600., 30., 4400., 1999., 6000., 5000., 1000., 260. /)
    it1 = (/ 0, 600, -999999999, 99999, 1800, 2400, 3000, 0, 100, 200 /)
    numpart = 10
    do run = 1, 4
      ! 1: moderate rate, itime inside the OH interval, earlier met field
      ! 2: itime beyond the OH interval (extrapolation), later met field
      ! 3: no reaction (ohcconst = 0)
      ! 4: rate so large the mass underflows to 0 in both precisions
      ohcconst(1) = 1.e-17; ohdconst(1) = 1500.; ohnconst(1) = 2.
      lt = 900.
      k = 1800
      if (run == 2) k = 9000
      if (run == 3) ohcconst(1) = 0.
      if (run == 4) then
        ohcconst(1) = 1.e-6; lt = 3600.
      end if
      call rowv('oh.run', (/ real(run), real(k), lt, ohcconst(1), ohdconst(1), &
           ohnconst(1) /), 6, (/ 0. /), 1)
      do j = 1, 10
        itra1(j) = it1(j)
        xtra1(j) = dble(px(j)); ytra1(j) = dble(py(j)); ztra1(j) = pz(j)
        xmass1(j,1) = 2.0 - 0.05*real(j)
        call rowv('oh.particle', (/ real(run), real(j), real(itra1(j)), px(j), py(j), &
             pz(j), xmass1(j,1) /), 7, (/ 0. /), 1)
      end do
      call ohreaction(k, nint(lt), 0)
      do j = 1, 10
        call rowv('ohreaction', (/ real(run), real(j) /), 2, (/ xmass1(j,1) /), 1)
      end do
    end do
  end subroutine emit_oh

  ! ------------------------------------------------------------------------
  ! assignland: landinvent from an integer formula (zero weights for
  ! inventory columns 1..25, i.e. 180W..172.5W), two calls:
  !   A: mother 6 x 5 at 179W.., 40.1N.., plus a nest 8 x 5 crossing 180E
  !   B: mother 6 x 4 from 150E (crossing 180), top row 89.99N whose samples
  !      reach 93.6N (wrapped to the South Pole rows), no nest
  ! The origins and spacings are chosen so that no sample falls exactly on an
  ! inventory cell boundary, where the cell would be decided by rounding.
  ! lu.grid: call, grid(0/1), nx, ny, dx, dy, xlon0, ylat0
  ! lu.lsm: call, grid ; values      assignland: call, grid, ix, jy ; 13 fractions
  subroutine fill_landinvent()
    integer :: i, j
    do j = 1, 600
      do i = 1, 1200
        landinvent(i,j,1) = int(1 + mod(i*7 + j*3, 13), 1)
        landinvent(i,j,2) = int(1 + mod(i*5 + j*11 + 4, 13), 1)
        landinvent(i,j,3) = int(1 + mod(i + j*2 + 9, 13), 1)
        if (i <= 25) then
          landinvent(i,j,4:6) = 0_1
        else
          landinvent(i,j,4) = int(mod(i + 2*j, 16), 1)
          landinvent(i,j,5) = int(mod(3*i + j, 11), 1)
          landinvent(i,j,6) = int(mod(i*j, 7), 1)
        end if
      end do
    end do
  end subroutine fill_landinvent

  subroutine emit_assignland()
    integer :: c, ix, jy, k, g, i, j
    real :: v(60)
    call fill_landinvent()
    do k = 1, 30
      i = 1 + mod(k*97, 1200); j = 1 + mod(k*41, 600)
      if (k == 1) i = 10
      call rowv('lu.check', (/ real(i), real(j) /), 2, real(landinvent(i,j,1:6)), 6)
    end do
    do c = 1, 2
      if (c == 1) then
        nx = 6; ny = 5; dx = 1.5; dy = 1.27; xlon0 = -179.; ylat0 = 40.1
        numbnests = 1
        nxn(1) = 8; nyn(1) = 5; dxn(1) = 0.41; dyn(1) = 0.353
        xlon0n(1) = 178.23; ylat0n(1) = -12.37
      else
        nx = 6; ny = 4; dx = 7.53; dy = 3.98; xlon0 = 150.07; ylat0 = 78.05
        numbnests = 0
      end if
      nxmin1 = nx - 1; nymin1 = ny - 1
      do jy = 0, ny-1
        do ix = 0, nx-1
          lsm(ix,jy) = 0.05 + 0.05*real(mod(ix + jy, 3))
          if (mod(ix+jy,3) == 2) lsm(ix,jy) = 0.6
          v(1+ix+nx*jy) = lsm(ix,jy)
        end do
      end do
      call rowv('lu.grid', (/ real(c), 0., real(nx), real(ny), dx, dy, xlon0, ylat0 /), 8, &
           (/ 0. /), 1)
      call rowv('lu.lsm', (/ real(c), 0. /), 2, v, nx*ny)
      if (numbnests == 1) then
        do jy = 0, nyn(1)-1
          do ix = 0, nxn(1)-1
            lsmn(ix,jy,1) = 0.05 + 0.05*real(mod(ix + 2*jy, 3))
            v(1+ix+nxn(1)*jy) = lsmn(ix,jy,1)
          end do
        end do
        call rowv('lu.grid', (/ real(c), 1., real(nxn(1)), real(nyn(1)), dxn(1), dyn(1), &
             xlon0n(1), ylat0n(1) /), 8, (/ 0. /), 1)
        call rowv('lu.lsm', (/ real(c), 1. /), 2, v, nxn(1)*nyn(1))
      end if
      call assignland()
      do jy = 0, ny-1
        do ix = 0, nx-1
          call rowv('assignland', (/ real(c), 0., real(ix), real(jy) /), 4, &
               xlanduse(ix,jy,:), numclass)
        end do
      end do
      do g = 1, numbnests
        do jy = 0, nyn(1)-1
          do ix = 0, nxn(1)-1
            call rowv('assignland', (/ real(c), 1., real(ix), real(jy) /), 4, &
                 xlandusen(ix,jy,:,1), numclass)
          end do
        end do
      end do
    end do
  end subroutine emit_assignland

end program flexpart_reference_met
