// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's Air.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `Air` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `Air` (pure), `T ∈ [198.14999999999998, 523.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/Air.json`.
pub const AIR_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "Air",
    kind: IncompressibleKind::Pure,
    t_range: (198.14999999999998, 523.15),
    x_range: (0.0, 0.0),
    t_base: 360.65,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.9731377204938464], &[-0.002673260039587141], &[9.363176076421318e-06], &[-2.7779101420879868e-08]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1010.1381836670001], &[0.08724844745590299], &[0.00040064968051053973], &[-8.867789581359177e-08]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.030754271682824127], &[6.98795213954844e-05], &[-3.35034769348712e-08], &[3.7728711330538117e-11]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::Exponential, coeffs: &[&[-700.879168909965, 216.13711261844045, 9.538652479388192]] }),
};
