// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's AL.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `AL` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `AL` (volume), `T ∈ [233.15, 353.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/AL.json`.
pub const AL_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "AL",
    kind: IncompressibleKind::VolumeBased,
    t_range: (233.15, 353.15),
    x_range: (0.1, 0.6),
    t_base: 293.15,
    x_base: 0.35,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[
                1034.271, 99.25415, -29.29743, -80.70544, -55.18701, -135.7672,
            ],
            &[
                -0.5256492,
                -0.6915636,
                -0.09581055,
                0.5222622,
                1.307315,
                0.0,
            ],
            &[-0.00286157, 0.00215927, 0.001173771, 0.001726857, 0.0, 0.0],
            &[1.260193e-05, 3.896622e-06, 3.788361e-06, 0.0, 0.0, 0.0],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[3807.565, -1529.162, -1264.555, 131.1929, 629.246, -430.131],
            &[2.199624, 8.684643, 1.968051, -10.60771, -6.665057, 0.0],
            &[0.003015936, -0.02836171, 0.003902559, 0.08058901, 0.0, 0.0],
            &[1.986856e-07, 0.0001828594, 3.746526e-05, 0.0, 0.0, 0.0],
        ],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[
                0.4393085, -0.4182483, 0.2079417, 0.02440718, -0.3870481, 0.4482925,
            ],
            &[
                0.0002439168,
                -0.003647236,
                0.001993104,
                0.004336741,
                -0.002145605,
                0.0,
            ],
            &[
                -9.437478e-07,
                7.250457e-06,
                -2.156441e-05,
                1.415195e-05,
                0.0,
                0.0,
            ],
            &[2.097847e-08, 3.808457e-08, -9.687437e-08, 0.0, 0.0, 0.0],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[
                -5.493307, 4.285853, -0.8099077, 1.397681, -14.79558, -40.40993,
            ],
            &[
                -0.03876554,
                -0.03415291,
                -0.01098128,
                0.09445676,
                -0.06682453,
                0.0,
            ],
            &[
                0.0002979889,
                -3.176006e-05,
                0.001613925,
                0.001441194,
                0.0,
                0.0,
            ],
            &[-1.283308e-06, -3.704857e-06, -2.996075e-05, 0.0, 0.0, 0.0],
        ],
    }),
    t_freeze: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[&[
            5.543667,
            -0.334518,
            -0.4959651,
            -0.2031848,
            -0.07774264,
            0.06739851,
        ]],
    }),
    p_sat: None,
    t_min_psat: f64::NAN,
};
