// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's DSF.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `DSF` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `DSF` (pure), `T ∈ [273.15, 588.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/DSF.json`.
pub const DSF_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "DSF",
    kind: IncompressibleKind::Pure,
    t_range: (273.15, 588.15),
    x_range: (0.0, 0.0),
    t_base: 430.65,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[785.4409], &[-0.6916519], &[-0.0002639398], &[2.502503e-06]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[2469.301], &[3.6541], &[2.637238e-06], &[4.220296e-08]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.1242271], &[-8.007266e-05], &[-2.820274e-08], &[5.359448e-12]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::LogExponential, coeffs: &[&[-253.8312, 2.073714, 4.23785]] }),
};
