// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's ExampleDigitalPure.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `ExampleDigitalPure` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `ExampleDigitalPure` (pure), `T ∈ [280.0, 500.0] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/ExampleDigitalPure.json`.
pub const EXAMPLEDIGITALPURE_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "ExampleDigitalPure",
    kind: IncompressibleKind::Pure,
    t_range: (280.0, 500.0),
    x_range: (0.0, 0.0),
    t_base: 390.0,
    x_base: 0.0,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[1192.776],
            &[-0.4853294],
            &[7.545341e-05],
            &[-6.339948e-07],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[3688.015], &[-1.95593], &[-0.004093648], &[0.000164408]],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[1.054674],
            &[0.001726354],
            &[-7.47401e-06],
            &[3.456054e-09],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::Exponential,
        coeffs: &[&[365.5034, -173.6257, 9.288918]],
    }),
    t_freeze: None,
    p_sat: Some(PropertyFit {
        form: PropertyForm::Exponential,
        coeffs: &[&[-3854.484, -44.25504, -23.24501]],
    }),
    t_min_psat: 280.0,
};
