// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's FoodCarbohydrate.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `FoodCarbohydrate` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `FoodCarbohydrate` (pure), `T ∈ [233.14999999999998, 423.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/FoodCarbohydrate.json`.
pub const FOODCARBOHYDRATE_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "FoodCarbohydrate",
    kind: IncompressibleKind::Pure,
    t_range: (233.14999999999998, 423.15),
    x_range: (0.0, 0.0),
    t_base: 273.15,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1599.1], &[-0.31046]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1548.8], &[1.9625], &[-0.0059399]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.20141], &[0.0013874], &[-4.3312e-06]] }),
    viscosity: None,
};
