// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's FoodAsh.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `FoodAsh` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `FoodAsh` (pure), `T ∈ [233.14999999999998, 423.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/FoodAsh.json`.
pub const FOODASH_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "FoodAsh",
    kind: IncompressibleKind::Pure,
    t_range: (233.14999999999998, 423.15),
    x_range: (0.0, 0.0),
    t_base: 273.15,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[2423.8], &[-0.28063]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1092.6], &[1.8896], &[-0.0036817]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.32962], &[0.0014011], &[-2.9069e-06]] }),
    viscosity: None,
};
