// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's FRE.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `FRE` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `FRE` (mass), `T ∈ [233.0, 313.0] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/FRE.json`.
pub const FRE_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "FRE",
    kind: IncompressibleKind::MassBased,
    t_range: (233.0, 313.0),
    x_range: (0.19, 0.5),
    t_base: 273.15,
    x_base: 0.0,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[1015.0, 462.0, 406.0], &[-0.4, 0.0, 0.0]],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[
                4150.105, -3736.729, 1691.779, -538.0408, 162.7239, -46.17142,
            ],
            &[
                0.000133061,
                6.297478,
                0.01571376,
                -0.03782187,
                0.03044803,
                0.0,
            ],
            &[
                1.086657e-05,
                -0.0001090631,
                0.0003488723,
                -0.0003600093,
                0.0,
                0.0,
            ],
            &[-6.379526e-08, 3.363858e-07, -3.132405e-07, 0.0, 0.0, 0.0],
        ],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[0.55, -0.15], &[0.0018, -0.0016]],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[
                -6.155988,
                -1.157552,
                5.506667,
                -0.1734136,
                0.03517942,
                -0.001484328,
            ],
            &[
                -0.02940677,
                0.0001802979,
                7.301947e-05,
                -0.0001058426,
                3.461983e-05,
                0.0,
            ],
            &[
                0.0002578126,
                6.494245e-08,
                2.356801e-08,
                -4.428143e-08,
                0.0,
                0.0,
            ],
            &[-2.058502e-06, -3.918904e-11, 6.411042e-11, 0.0, 0.0, 0.0],
        ],
    }),
    t_freeze: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[
            305.3914, -572.5104, 3526.758, -12337.79, 20948.09, -14511.82,
        ]],
    }),
    p_sat: None,
    t_min_psat: f64::NAN,
};
