// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's HC30.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `HC30` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `HC30` (pure), `T ∈ [243.15, 483.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/HC30.json`.
pub const HC30_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "HC30",
    kind: IncompressibleKind::Pure,
    t_range: (243.15, 483.15),
    x_range: (0.0, 0.0),
    t_base: 363.15,
    x_base: 0.0,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[1239.436],
            &[-0.5102214],
            &[-2.991453e-05],
            &[1.142979e-07],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[3238.461], &[2.3073], &[-4.0877e-06], &[3.220612e-07]],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[0.589], &[0.001], &[0.0], &[-9.225935e-20]],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::Exponential,
        coeffs: &[&[1479.132, 4.336454, 10.94097]],
    }),
    t_freeze: None,
    p_sat: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[10.73982],
            &[0.03952906],
            &[-0.0001214467],
            &[1.919922e-07],
        ],
    }),
    t_min_psat: 293.15,
};
