// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's HY20.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `HY20` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `HY20` (pure), `T ∈ [253.15, 323.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/HY20.json`.
pub const HY20_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "HY20",
    kind: IncompressibleKind::Pure,
    t_range: (253.15, 323.15),
    x_range: (0.0, 0.0),
    t_base: 273.15,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1202.2], &[-0.42918]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[2955.0], &[2.3]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.5181167], &[0.001966495], &[-7.108434e-06], &[-1.079438e-07]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::Exponential, coeffs: &[&[642.8081, -117.2883, 9.971345]] }),
};
