// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's IceEA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `IceEA` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `IceEA` (mass), `T ∈ [240.0, 265.0] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/IceEA.json`.
pub const ICEEA_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "IceEA",
    kind: IncompressibleKind::MassBased,
    t_range: (240.0, 265.0),
    x_range: (0.05, 0.35),
    t_base: 252.5,
    x_base: 0.2,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[960.495, -61.23692, 2.608225, -8.564815, 30.30303, 222.2222],
            &[0.4441443, -0.422037, 0.007287157, 0.8888889, -1.038961, 0.0],
            &[-0.007370748, 0.007896825, 0.005442177, 0.07936508, 0.0, 0.0],
            &[0.0005597884, -0.0007407407, 0.0006349206, 0.0, 0.0, 0.0],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[
                81940.79, 409816.9, -10627.62, -70532.18, -71505.05, -61777.78,
            ],
            &[-284.2661, -2371.855, -5436.087, -2193.397, 3987.186, 0.0],
            &[-25.19892, -136.7578, 13.39728, 379.7937, 0.0, 0.0],
            &[-1.041161, -3.099122, 11.72889, 0.0, 0.0, 0.0],
        ],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[
                0.5582565, 0.99627, 0.6859591, 0.4615741, 0.2727273, 0.2222222,
            ],
            &[
                0.006360627,
                0.005938113,
                -0.0007701339,
                -0.004698413,
                -0.01281385,
                0.0,
            ],
            &[
                3.218367e-05,
                -4.019841e-05,
                -7.653061e-05,
                3.174603e-05,
                0.0,
                0.0,
            ],
            &[2.070547e-06, 1.687831e-06, -3.56261e-06, 0.0, 0.0, 0.0],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[
                -3.087316, 2.175017, -2.512979, 3.880552, -6.779982, 6.900146,
            ],
            &[
                -0.08462508,
                0.0002759457,
                -0.0005590346,
                -0.0007503359,
                0.01707366,
                0.0,
            ],
            &[
                -0.001128967,
                7.081811e-06,
                0.0001120295,
                -0.0002472949,
                0.0,
                0.0,
            ],
            &[6.656644e-07, 5.862205e-07, -1.080759e-05, 0.0, 0.0, 0.0],
        ],
    }),
    t_freeze: None,
    p_sat: None,
    t_min_psat: f64::NAN,
};
