// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's IceNA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `IceNA` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `IceNA` (mass), `T ∈ [255.0, 270.0] K`.
/// `reference/CoolProp/dev/incompressible_liquids/json/IceNA.json`.
pub const ICENA_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "IceNA",
    kind: IncompressibleKind::MassBased,
    t_range: (255.0, 270.0),
    x_range: (0.05, 0.35),
    t_base: 262.5,
    x_base: 0.2,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1070.914, -227.0867, 54.55087, -63.88889, -242.4242, 1333.333], &[-5.978032, 10.29397, -3.416883, 0.8888889, -19.39394, 0.0], &[-0.1148095, 0.1265079, 0.00952381, 0.4444444, 0.0, 0.0], &[-0.005695238, 0.007619048, -0.003809524, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[72906.71, 360863.4, -15333.7, 6622.222, -45.45455, -1666.667], &[-751.2994, -3270.198, 3139.012, -1236.0, -35.15152, 0.0], &[12.29471, 51.16825, -124.9857, 52.22222, 0.0, 0.0], &[-0.05866032, 2.457048, -4.446349, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.759808, 1.235272, 0.5741071, 0.2444444, -4.264085e-13, 0.6666667], &[0.001030686, -0.005864524, 0.001136797, 0.002666667, -0.00969697, 0.0], &[2.142857e-06, -0.0001334921, 2.857143e-05, 0.0004444444, 0.0, 0.0], &[-1.504762e-06, -6.285714e-06, 7.619048e-06, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-5.111147, 2.155306, -2.7633, 4.413803, -9.40312, 18.50344], &[-0.06971797, -0.003012097, 0.02247915, -0.07050899, 0.2885255, 0.0], &[0.0005078165, -4.930767e-05, 0.0004912011, -0.003552178, 0.0, 0.0], &[2.321852e-05, -4.989919e-06, 2.733134e-05, 0.0, 0.0, 0.0]] }),
};
