// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's LiBr.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `LiBr` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `LiBr` (mass), `T ∈ [273.0, 500.0] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/LiBr.json`.
pub const LIBR_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "LiBr",
    kind: IncompressibleKind::MassBased,
    t_range: (273.0, 500.0),
    x_range: (0.0, 0.75),
    t_base: 386.5,
    x_base: 0.375,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1300.435, 1277.503, 1188.416, 1079.937, 1348.022, 1191.868], &[-0.817504, 0.04808491, 1.134731, 5.492054, 9.087468, 0.0], &[-0.002093536, 0.00334591, 0.01634225, 0.03010252, 0.0, 0.0], &[7.368593e-06, 2.864456e-05, 5.365247e-05, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[2641.343, -3426.99, 3324.197, -1540.026, -11798.67, 2486.313], &[0.5857653, -1.308166, 2.465627, 1.232915, 11.03372, 0.0], &[-8.168738e-05, -0.03525622, 0.01711573, -0.008650137, 0.0, 0.0], &[0.0001468639, 0.000154841, -0.0004128601, 0.0, 0.0, 0.0]] },
    conductivity: None,
    viscosity: None,
};
