// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's MEA2.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `MEA2` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `MEA2` (mass), `T ∈ [229.15, 293.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/MEA2.json`.
pub const MEA2_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "MEA2",
    kind: IncompressibleKind::MassBased,
    t_range: (229.15, 293.15),
    x_range: (0.11, 0.6),
    t_base: 261.15,
    x_base: 0.355,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[963.9157, -138.5271, -314.7226, 427.5957, 1620.709, -6412.0], &[-0.5188234, -2.659211, 4.932398, 14.79174, -41.41, 0.0], &[-0.003985602, 0.03261505, 0.01650197, -0.346, 0.0, 0.0], &[1.915331e-05, -4.455626e-05, -0.0002874999, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[3996.428, -2846.249, -1531.426, 9307.371, -14318.73, 2235.001], &[3.218122, 20.65606, -43.68677, 0.9481275, 254.5, 0.0], &[0.0002617675, -0.01772782, 0.2819403, -0.9149, 0.0, 0.0], &[3.312448e-06, 0.000277743, 0.0003365996, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.3659957, -0.4351228, 0.1945179, 0.7669444, 0.4684235, -10.12], &[0.0005182845, -0.00229438, 0.004147783, 0.001777048, -0.03486, 0.0], &[-4.279159e-09, -1.966452e-06, 1.310795e-05, -1.438998e-05, 0.0, 0.0], &[-1.225384e-08, 3.473761e-08, -7.324987e-08, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-4.268143, 0.3631931, -7.445959, -1.350047, -14.88443, 76.54], &[-0.06533397, 0.04100097, -0.0298502, 0.3814608, 0.8582, 0.0], &[0.0005436594, -0.001568477, 0.00657019, -0.01234, 0.0, 0.0], &[-2.036115e-06, 2.388365e-05, -0.0001329, 0.0, 0.0, 0.0]] }),
};
