// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's MGL.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `MGL` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `MGL` (mass), `T ∈ [173.15, 313.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/MGL.json`.
pub const MGL_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "MGL",
    kind: IncompressibleKind::MassBased,
    t_range: (173.15, 313.15),
    x_range: (0.0, 0.6),
    t_base: 282.061,
    x_base: 0.361905,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1093.0, 274.0, 40.81, -47.44, -141.5, -60.97], &[-0.3624, -0.8373, 0.1808, 1.833, 1.863, 0.0], &[-0.002451, 0.009596, -0.008516, -0.03077, 0.0, 0.0], &[1.547e-05, -6.999e-05, 0.0001441, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[3486.0, -2250.0, -325.8, 2922.0, 2238.0, -5944.0], &[3.766, 18.11, 7.249, -53.46, -53.83, 0.0], &[-0.0001222, 0.03766, -0.2133, 0.23, 0.0, 0.0], &[3.219e-05, -0.00173, 0.004907, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.4532, -0.3223, 0.05539, -0.2073, 0.3, 2.221], &[0.0009782, -0.001951, -0.0006878, -0.0002235, 0.01604, 0.0], &[-1.196e-07, 1.178e-05, -2.587e-05, -1.421e-05, 0.0, 0.0], &[-8.778e-09, 1.048e-08, 2.262e-07, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-5.387755, 4.45, 3.633, 1.069, 5.729, 21.16], &[-0.03729, -0.02688, -0.04088, -0.1248, -0.178, 0.0], &[0.0003572, 8.876e-05, 0.0006219, 0.003019, 0.0, 0.0], &[-3.648e-06, -2.209e-06, 6.331e-06, 0.0, 0.0, 0.0]] }),
};
