// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's MKA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `MKA` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `MKA` (mass), `T ∈ [173.15, 313.15] K`.
/// `reference/CoolProp/dev/incompressible_liquids/json/MKA.json`.
pub const MKA_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "MKA",
    kind: IncompressibleKind::MassBased,
    t_range: (173.15, 313.15),
    x_range: (0.0, 0.45),
    t_base: 279.9257,
    x_base: 0.256757,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1138.0, 579.6, 130.6, -1427.0, 935.3, 22850.0], &[-0.3565, -0.79, 0.6845, 0.8304, 2.322, 0.0], &[-0.00202, 0.002753, -0.0113, 0.01303, 0.0, 0.0], &[4.205e-06, 5.14e-06, 0.0002433, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[3327.0, -2895.0, 466.3, -1249.0, 16590.0, -4612.0], &[1.806, 4.131, 7.775, 51.15, -519.3, 0.0], &[-0.001766, 0.04429, 0.3463, -2.987, 0.0, 0.0], &[4.357e-05, 0.001125, -0.007261, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.4958, -0.2931, 0.1032, -0.2024, -0.2371, 5.515], &[0.00134, -0.001477, -0.002396, -0.005541, 0.05573, 0.0], &[6.837e-08, 4.659e-06, -4.352e-05, 8.984e-05, 0.0, 0.0], &[2.637e-09, 2.886e-08, -2.23e-07, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-5.865755, 3.405, 5.017, 5.637, -29.22, -79.6], &[-0.03071, -0.01511, -0.07779, 0.02534, 0.4601, 0.0], &[0.0002819, 0.0001172, 0.0009125, 0.001596, 0.0, 0.0], &[-2.19e-06, -2.379e-06, -1.888e-05, 0.0, 0.0, 0.0]] }),
};
