// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's MKC.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `MKC` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `MKC` (mass), `T ∈ [173.15, 313.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/MKC.json`.
pub const MKC_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "MKC",
    kind: IncompressibleKind::MassBased,
    t_range: (173.15, 313.15),
    x_range: (0.0, 0.4),
    t_base: 284.3922,
    x_base: 0.220833,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1216.0, 1064.0, 441.3, -133.3, -1246.0, 2035.0], &[-0.4114, -0.7614, 0.7806, -2.381, 27.08, 0.0], &[-0.003383, 0.005214, -0.01173, 0.1696, 0.0, 0.0], &[2.99e-05, -8.087e-05, 0.0005658, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[3217.0, -3733.0, 2023.0, 19710.0, 34050.0, -348800.0], &[1.492, -1.775, 45.53, 136.7, -1676.0, 0.0], &[-0.001539, 0.05416, 0.3587, -3.667, 0.0, 0.0], &[-3.546e-05, 0.000659, -0.003707, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.5622, -0.0892, -0.005233, -0.9283, -1.011, 13.11], &[0.001656, 0.0002031, -0.002962, -0.01814, 0.08471, 0.0], &[2.108e-06, -2.616e-05, -9.174e-05, 0.0008767, 0.0, 0.0], &[-4.482e-08, 7.965e-08, 1.027e-06, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-6.101455, 3.624, 6.659, 10.77, -10.97, -84.53], &[-0.02362, -0.001262, -0.1611, -0.09796, 0.7825, 0.0], &[0.0001851, -3.022e-05, 0.00153, 0.00307, 0.0, 0.0], &[-2.372e-06, -7.761e-07, 1.061e-05, 0.0, 0.0, 0.0]] }),
};
