// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's MMA.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `MMA` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `MMA` (mass), `T ∈ [173.15, 313.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/MMA.json`.
pub const MMA_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "MMA",
    kind: IncompressibleKind::MassBased,
    t_range: (173.15, 313.15),
    x_range: (0.0, 0.6),
    t_base: 276.6859,
    x_base: 0.305128,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[958.1, -139.1, -110.5, -120.8, 492.7, -772.7],
            &[-0.4151, -1.51, 1.828, 2.992, -13.25, 0.0],
            &[-0.002261, 0.01113, -0.01641, 0.001455, 0.0, 0.0],
            &[2.998e-07, -3.264e-05, 0.000151, 0.0, 0.0, 0.0],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[3887.0, -1850.0, -376.9, -3776.0, -15040.0, 64330.0],
            &[7.201, 29.84, -119.6, -56.11, 737.3, 0.0],
            &[-0.08979, -0.1865, 0.9801, -0.7811, 0.0, 0.0],
            &[-0.000439, -0.001718, 0.00666, 0.0, 0.0, 0.0],
        ],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[0.4175, -0.4421, 0.2044, 0.2943, -0.08666, -2.033],
            &[0.0007271, -0.002952, 0.003413, -0.0009646, -4.573e-05, 0.0],
            &[2.823e-07, 7.336e-06, -3.665e-05, 3.174e-05, 0.0, 0.0],
            &[9.718e-09, 4.328e-08, -2.791e-07, 0.0, 0.0, 0.0],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[-5.754755, 0.5448, -5.552, 3.038, 6.669, -8.472],
            &[-0.03866, 0.01008, 0.08384, -0.07435, -0.09105, 0.0],
            &[0.0002779, -0.0002809, -0.0003997, 0.0007442, 0.0, 0.0],
            &[-1.543e-06, 9.811e-07, -3.466e-06, 0.0, 0.0, 0.0],
        ],
    }),
    t_freeze: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[246.86, -118.7, -121.8, -68.23, 12.97, 236.3]],
    }),
    p_sat: None,
    t_min_psat: f64::NAN,
};
