// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's PCR.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `PCR` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `PCR` (pure), `T ∈ [173.15, 493.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/PCR.json`.
pub const PCR_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "PCR",
    kind: IncompressibleKind::Pure,
    t_range: (173.15, 493.15),
    x_range: (0.0, 0.0),
    t_base: 333.15,
    x_base: 0.0,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[787.6979], &[-1.00844], &[1.305365e-05], &[6.240201e-08]],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[2065.827], &[3.657941], &[-0.0001561304], &[2.864835e-06]],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[0.1366907],
            &[-8.029757e-05],
            &[9.982291e-11],
            &[9.384425e-12],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::Exponential,
        coeffs: &[&[508.2283, -91.38133, 9.633635]],
    }),
    t_freeze: None,
    p_sat: Some(PropertyFit {
        form: PropertyForm::LogExponential,
        coeffs: &[&[-350.0387, -1.263655, 5.63327]],
    }),
    t_min_psat: 358.15,
};
