// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's PMS2.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `PMS2` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `PMS2` (pure), `T ∈ [193.15, 373.15] K`.
/// `reference/CoolProp/dev/incompressible_liquids/json/PMS2.json`.
pub const PMS2_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "PMS2",
    kind: IncompressibleKind::Pure,
    t_range: (193.15, 373.15),
    x_range: (0.0, 0.0),
    t_base: 0.0,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1155.94], &[-1.02576]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1153.55], &[2.10788]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.172305], &[-0.000211212]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[5.66926], &[-0.065582], &[8.09988e-05]] }),
};
