// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's SAB.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `SAB` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `SAB` (pure), `T ∈ [193.15, 373.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/SAB.json`.
pub const SAB_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "SAB",
    kind: IncompressibleKind::Pure,
    t_range: (193.15, 373.15),
    x_range: (0.0, 0.0),
    t_base: 0.0,
    x_base: 0.0,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[1102.34], &[-0.801667]],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[1360.94], &[1.51667]],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[&[0.208374], &[-0.000261667]],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[&[5.21288], &[-0.0665792], &[8.5066e-05]],
    }),
    t_freeze: None,
    p_sat: None,
    t_min_psat: f64::NAN,
};
