// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's TCO.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `TCO` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `TCO` (pure), `T ∈ [193.15, 373.15] K`.
/// `reference/CoolProp/dev/incompressible_liquids/json/TCO.json`.
pub const TCO_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "TCO",
    kind: IncompressibleKind::Pure,
    t_range: (193.15, 373.15),
    x_range: (0.0, 0.0),
    t_base: 0.0,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1071.02], &[-0.778166]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[223.775], &[5.2159]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.174156], &[-0.000185052]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-3.47971], &[-0.0107031], &[1.14086e-06]] }),
};
