// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's TVP1869.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `TVP1869` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `TVP1869` (pure), `T ∈ [193.15, 293.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/TVP1869.json`.
pub const TVP1869_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "TVP1869",
    kind: IncompressibleKind::Pure,
    t_range: (193.15, 293.15),
    x_range: (0.0, 0.0),
    t_base: 273.15,
    x_base: 0.0,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[945.5455], &[-1.054545]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[2322.218], &[3.843636]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.15], &[-0.000154545]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-5.651331], &[-0.03572436], &[0.0001071302], &[-5.102013e-06]] }),
};
