// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's ZFC.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `ZFC` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `ZFC` (volume), `T ∈ [233.15, 373.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/ZFC.json`.
pub const ZFC_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "ZFC",
    kind: IncompressibleKind::VolumeBased,
    t_range: (233.15, 373.15),
    x_range: (0.3, 0.6),
    t_base: 303.15,
    x_base: 0.45,
    density: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[1036.776, 64.96479, -103.8651, -22.17783], &[-0.5537355, -0.4680781, 0.550171, 0.0], &[-0.002986744, 0.002143295, 0.0, 0.0], &[1.931875e-06, 0.0, 0.0, 0.0]] },
    heat_capacity: PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[3673.274, -1730.901, -1160.812, 2165.065], &[3.0695, 9.07294, -0.09407745, 0.0], &[0.001975833, -0.0256522, 0.0, 0.0], &[4.820618e-08, 0.0, 0.0, 0.0]] },
    conductivity: Some(PropertyFit { form: PropertyForm::Polynomial, coeffs: &[&[0.3990549, -0.4101994, 0.1800441, 0.01724997], &[-9.525483e-05, -0.002928935, 0.0023867, 0.0], &[-2.598059e-08, 4.408053e-06, 0.0, 0.0], &[2.434114e-08, 0.0, 0.0, 0.0]] }),
    viscosity: Some(PropertyFit { form: PropertyForm::ExpPolynomial, coeffs: &[&[-5.627093, 2.542102, 2.006041, 54.52566], &[-0.03607463, -0.04895733, -0.03202809, 0.0], &[0.0003340331, 0.0005712186, 0.0, 0.0], &[-1.935545e-06, 0.0, 0.0, 0.0]] }),
};
