// SPDX-License-Identifier: MIT
// GENERATED by dev/gen_incompressible.py from CoolProp's ZMC.json (MIT).
// Do not edit by hand — re-run the generator. See dev/gen_incompressible.py.
//! CoolProp `ZMC` incompressible-fluid fit, as hardcoded `const` data.

use crate::incompressibles::{IncompressibleFluid, IncompressibleKind, PropertyFit, PropertyForm};

/// CoolProp `ZMC` (volume), `T ∈ [223.15, 383.15] K`.
/// `upstream_source/CoolProp/dev/incompressible_liquids/json/ZMC.json`.
pub const ZMC_INCOMP: IncompressibleFluid = IncompressibleFluid {
    name: "ZMC",
    kind: IncompressibleKind::VolumeBased,
    t_range: (223.15, 383.15),
    x_range: (0.3, 0.7),
    t_base: 303.15,
    x_base: 0.5,
    density: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[1062.722, 117.153, -60.88266, 2.395204, 106.6566],
            &[-0.6003263, -0.4401289, 0.6018167, -0.3768314, 0.0],
            &[-0.001393452, 0.003479068, -0.004378448, 0.0, 0.0],
            &[5.814755e-09, -2.691843e-07, 0.0, 0.0, 0.0],
        ],
    },
    heat_capacity: PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[3371.054, -1939.998, 5401.769, -4349.569, -79796.45],
            &[5.477711, 4.806029, -30.24999, 43.67695, 0.0],
            &[-0.02344346, 0.01458622, 0.07429804, 0.0, 0.0],
            &[-1.939051e-05, 6.113134e-05, 0.0, 0.0, 0.0],
        ],
    },
    conductivity: Some(PropertyFit {
        form: PropertyForm::Polynomial,
        coeffs: &[
            &[0.4137041, -0.2828833, 0.002073991, -0.3173044, 4.202929],
            &[-0.0002738015, -0.002643358, 0.004068416, 0.002454691, 0.0],
            &[-3.557609e-07, 4.990185e-06, 7.750234e-06, 0.0, 0.0],
            &[7.704093e-11, -2.547468e-10, 0.0, 0.0, 0.0],
        ],
    }),
    viscosity: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[
            &[-5.72494, 2.925573, 1.135288, 0.7891747, -24.19532],
            &[-0.03440952, -0.03984102, -0.008431789, 0.04516405, 0.0],
            &[0.0001685851, 8.61505e-05, 0.0001448975, 0.0, 0.0],
            &[5.240165e-07, 3.070892e-06, 0.0, 0.0, 0.0],
        ],
    }),
    t_freeze: Some(PropertyFit {
        form: PropertyForm::ExpPolynomial,
        coeffs: &[&[5.464044, -0.5105012, -0.5363333, -0.249623, 0.1538631]],
    }),
    p_sat: None,
    t_min_psat: f64::NAN,
};
