// Part of the kovan port of citeproc-js (GitHub #790, #792).
//
// Upstream:    citeproc-js, https://github.com/juris-m/citeproc-js
// Source:      src/load.js
// Version:     2.4.63, commit 73bc1b44bc7d54d0bfec4e070fd27f5efe024ff9
// Copyright:   (c) 2009-2019 Frank Bennett
// Licence:     AGPL-3.0, taken from upstream's "CPAL-1.0 or AGPL-3.0-or-later"
//              (LICENSE at the commit above; see this crate's NOTICE).
// Modified:    2026-10-08, by the OUTRAM PARK contributors. This file is a
//              Rust translation (port) of the file named above, modified
//              from the original.
// No warranty: this program is distributed in the hope that it will be
//              useful, but WITHOUT ANY WARRANTY; without even the implied
//              warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//              PURPOSE. See the GNU Affero General Public License.

//! The `CSL` object of citeproc-js (src/load.js): its constants (term lists,
//! regular expressions, the lookup tables) and the helper functions that
//! hang off it (`CSL.parseLocator`, `CSL.parseNoteFieldHacks`,
//! `CSL.checkNestedBrace`, `CSL.normalizeLocaleStr`, the punctuation-spacing
//! checks, `CSL.TITLE_SPLIT`, `CSL.SET_COURT_CLASSES`, ...).
//!
//! **Names.** `CSL.NAME_VARIABLES` is [`NAME_VARIABLES`], `CSL.Foo()` is
//! `load::foo()`. Constant tables that upstream keeps in an object keyed by
//! string are `&[(&str, &str)]` slices with a lookup function next to them
//! (their order is upstream's insertion order); the tables themselves are
//! generated from the bundled citeproc-js by `scripts/csl-units/load_tables.cjs`.
//!
//! **Regular expressions** are `LazyLock<Regex>` statics. JS `\s` is
//! [`WS_CLASS`], JS `.` is [`DOT`], and `\d` is written `[0-9]` (PORTING.md §5).
//! `tests/data/csl/units/load.json` (generated by `scripts/csl-units/load.cjs`
//! from citeproc-js) holds what each does on a battery of strings.
//!
//! **What is not here.** `CSL.Engine.*` (build.rs, util_locale.rs, ...) and
//! `CSL.Util`/`CSL.Output`/`CSL.Node` live in their own files.
//! `CSL.error` is `Err(EngineError::Csl(..))`; `CSL.debug` is dropped.

use std::sync::LazyLock;

use regex::Regex;
use serde_json::Value;

use super::js::{self, Obj};
use super::obj_token::Token;
use super::state::State;
use super::xmljson::{NodeId, XmlJson};
use super::{CslResult, EngineError};

/// `CSL.PROCESSOR_VERSION`.
pub const PROCESSOR_VERSION: &str = "1.4.61";

// Numeric constants (`CSL.START` ... `CSL.TOLERANT`). `TokenType` is the
// typed form of the first three.
/// `CSL.ERROR_NO_RENDERED_FORM`.
pub const ERROR_NO_RENDERED_FORM: i64 = 1;
/// `CSL.PREVIEW`.
pub const PREVIEW: &str = "Just for laughs.";
/// `CSL.ASSUME_ALL_ITEMS_REGISTERED`.
pub const ASSUME_ALL_ITEMS_REGISTERED: i64 = 2;
/// `CSL.START`.
pub const START: i64 = 0;
/// `CSL.END`.
pub const END: i64 = 1;
/// `CSL.SINGLETON`.
pub const SINGLETON: i64 = 2;
/// `CSL.SEEN`.
pub const SEEN: i64 = 6;
/// `CSL.SUCCESSOR`.
pub const SUCCESSOR: i64 = 3;
/// `CSL.SUCCESSOR_OF_SUCCESSOR`.
pub const SUCCESSOR_OF_SUCCESSOR: i64 = 4;
/// `CSL.SUPPRESS`.
pub const SUPPRESS: i64 = 5;
/// `CSL.SINGULAR`.
pub const SINGULAR: i64 = 0;
/// `CSL.PLURAL`.
pub const PLURAL: i64 = 1;
/// `CSL.BEFORE`.
pub const BEFORE: i64 = 1;
/// `CSL.AFTER`.
pub const AFTER: i64 = 2;
/// `CSL.DESCENDING`.
pub const DESCENDING: i64 = 1;
/// `CSL.ASCENDING`.
pub const ASCENDING: i64 = 2;
/// `CSL.PRIMARY`.
pub const PRIMARY: i64 = 1;
/// `CSL.SECONDARY`.
pub const SECONDARY: i64 = 2;
/// `CSL.POSITION_FIRST`.
pub const POSITION_FIRST: i64 = 0;
/// `CSL.POSITION_SUBSEQUENT`.
pub const POSITION_SUBSEQUENT: i64 = 1;
/// `CSL.POSITION_IBID`.
pub const POSITION_IBID: i64 = 2;
/// `CSL.POSITION_IBID_WITH_LOCATOR`.
pub const POSITION_IBID_WITH_LOCATOR: i64 = 3;
/// `CSL.POSITION_CONTAINER_SUBSEQUENT`.
pub const POSITION_CONTAINER_SUBSEQUENT: i64 = 4;
/// `CSL.NONE` (an update mode).
pub const NONE: i64 = 0;
/// `CSL.NUMERIC` (an update mode).
pub const NUMERIC: i64 = 1;
/// `CSL.POSITION` (an update mode).
pub const POSITION: i64 = 2;
/// `CSL.TRIGRAPH` (an update mode).
pub const TRIGRAPH: i64 = 3;
/// `CSL.LOOSE`.
pub const LOOSE: i64 = 0;
/// `CSL.STRICT`.
pub const STRICT: i64 = 1;
/// `CSL.TOLERANT`.
pub const TOLERANT: i64 = 2;

/// `CSL.POSITION_MAP`: `{"0": 0, "4": 1, "1": 2, "2": 3, "3": 4}`.
pub fn position_map(key: i64) -> Option<i64> {
    match key {
        0 => Some(0),
        4 => Some(1),
        1 => Some(2),
        2 => Some(3),
        3 => Some(4),
        _ => None,
    }
}

/// JS `\s` as a regex class (the `\s` of Rust plus U+FEFF; PORTING.md §5).
pub const WS_CLASS: &str = r"[\s\x{feff}]";

/// JS `.` as a regex class: anything but `\n`, `\r`, U+2028, U+2029.
pub const DOT: &str = r"[^\n\r\x{2028}\x{2029}]";

/// The statute-subdivision abbreviations shared by three regexes.
const SUBDIV_ABBREVS: &str = "vrs|sv|subpara|op|subch|add|amend|annot|app|art|bibliog|bk|ch|cl|col|cmt|dec|dept|div|ex|fig|fld|fol|n|hypo|illus|intro|l|no|p|pp|para|pt|pmbl|princ|pub|r|rn|sched|sec|ser|subdiv|subsec|supp|tbl|tit|vol";

/// The Latin/Greek/Cyrillic/... letter ranges the "romanesque" regexes share
/// (without digits or hyphen), as the inside of a character class.
const ROMANESQUE_RANGES: &str = r"a-zA-Z\u0e01-\u0e5b\u00c0-\u017f\u0370-\u03ff\u0400-\u052f\u0590-\u05d4\u05d6-\u05ff\u1f00-\u1fff\u0600-\u06ff\u200c\u200d\u200e\u0218\u0219\u021a\u021b\u202a-\u202e";

macro_rules! static_re {
    ($(#[$m:meta])* $name:ident, $pat:expr) => {
        $(#[$m])*
        pub static $name: LazyLock<Regex> =
            LazyLock::new(|| Regex::new(&$pat).expect("static citeproc regex"));
    };
}

static_re!(
    /// `CSL.LOCATOR_LABELS_REGEXP`: `^((vrs|...)\.)\s+(.*)`.
    LOCATOR_LABELS_REGEXP,
    format!(r"^(({SUBDIV_ABBREVS})\.){WS_CLASS}+({DOT}*)")
);
static_re!(
    /// `CSL.STATUTE_SUBDIV_PLAIN_REGEX`.
    STATUTE_SUBDIV_PLAIN_REGEX,
    format!(r"(?:(?:^| )(?:{SUBDIV_ABBREVS})\. *)")
);
static_re!(
    /// `CSL.STATUTE_SUBDIV_PLAIN_REGEX_FRONT`.
    STATUTE_SUBDIV_PLAIN_REGEX_FRONT,
    format!(r"(?:^{WS_CLASS}*[.,;]*{WS_CLASS}*(?:{SUBDIV_ABBREVS})\. *)")
);
static_re!(
    /// `CSL.PREFIX_PUNCTUATION`: `/[.;:]\s*$/`.
    PREFIX_PUNCTUATION,
    format!(r"[.;:]{WS_CLASS}*$")
);
static_re!(
    /// `CSL.SUFFIX_PUNCTUATION`: `/^\s*[.;:,\(\)]/`.
    SUFFIX_PUNCTUATION,
    format!(r"^{WS_CLASS}*[.;:,()]")
);
static_re!(
    /// `CSL.NUMBER_REGEXP`: `/(?:^\d+|\d+$)/`.
    NUMBER_REGEXP,
    r"(?:^[0-9]+|[0-9]+$)".to_string()
);
static_re!(
    /// `CSL.NAME_INITIAL_REGEXP`: a capital, the rest of the word, and any dots.
    NAME_INITIAL_REGEXP,
    r"^([A-Z\u0e01-\u0e5b\u00c0-\u017f\u0400-\u042f\u0590-\u05d4\u05d6-\u05ff\u0600-\u06ff\u0370\u0372\u0376\u0386\u0388-\u03ab\u03e2\u03e4\u03e6\u03e8\u03ea\u03ec\u03ee\u03f4\u03f7\u03fd-\u03ff])([a-zA-Z\u0e01-\u0e5b\u00c0-\u017f\u0400-\u052f\u0600-\u06ff\u0370-\u03ff\u1f00-\u1fff]*|)(\.)*".to_string()
);
static_re!(
    /// `CSL.ROMANESQUE_REGEXP`: one romanesque character (or `-`, or a digit).
    ROMANESQUE_REGEXP,
    format!("[-0-9{ROMANESQUE_RANGES}]")
);
static_re!(
    /// `CSL.ROMANESQUE_NOT_REGEXP` (global in JS): one non-romanesque character.
    ROMANESQUE_NOT_REGEXP,
    format!("[^{ROMANESQUE_RANGES}]")
);
static_re!(
    /// `CSL.STARTSWITH_ROMANESQUE_REGEXP`.
    STARTSWITH_ROMANESQUE_REGEXP,
    format!("^[&{ROMANESQUE_RANGES}]")
);
static_re!(
    /// `CSL.ENDSWITH_ROMANESQUE_REGEXP`.
    ENDSWITH_ROMANESQUE_REGEXP,
    format!("[.;:&{ROMANESQUE_RANGES}]$")
);
static_re!(
    /// `CSL.ALL_ROMANESQUE_REGEXP`.
    ALL_ROMANESQUE_REGEXP,
    format!("^[{ROMANESQUE_RANGES}]+$")
);
static_re!(
    /// `CSL.VIETNAMESE_SPECIALS`.
    VIETNAMESE_SPECIALS,
    r"[\u00c0-\u00c3\u00c8-\u00ca\u00cc\u00cd\u00d2-\u00d5\u00d9\u00da\u00dd\u00e0-\u00e3\u00e8-\u00ea\u00ec\u00ed\u00f2-\u00f5\u00f9\u00fa\u00fd\u0101\u0103\u0110\u0111\u0128\u0129\u0168\u0169\u01a0\u01a1\u01af\u01b0\u1ea0-\u1ef9]".to_string()
);
static_re!(
    /// `CSL.VIETNAMESE_NAMES`.
    VIETNAMESE_NAMES,
    format!(r"^(?:(?:[.AaBbCcDdEeGgHhIiKkLlMmNnOoPpQqRrSsTtUuVvXxYy \u00c0-\u00c3\u00c8-\u00ca\u00cc\u00cd\u00d2-\u00d5\u00d9\u00da\u00dd\u00e0-\u00e3\u00e8-\u00ea\u00ec\u00ed\u00f2-\u00f5\u00f9\u00fa\u00fd\u0101\u0103\u0110\u0111\u0128\u0129\u0168\u0169\u01a0\u01a1\u01af\u01b0\u1ea0-\u1ef9]{{2,6}})({WS_CLASS}+|$))+$")
);
static_re!(
    /// `CSL.NOTE_FIELDS_REGEXP` (global in JS): a `{{:key:value}}` field in a note.
    NOTE_FIELDS_REGEXP,
    r"\{:(?:[\-_a-z]+|[A-Z]+):[^\}]+\}".to_string()
);
static_re!(
    /// `CSL.NOTE_FIELD_REGEXP`: a `key: value` line of a note.
    NOTE_FIELD_REGEXP,
    format!(r"^([\-_a-z]+|[A-Z]+):{WS_CLASS}*([^\}}]+)$")
);
static_re!(
    /// `CSL.PARTICLE_GIVEN_REGEXP`.
    PARTICLE_GIVEN_REGEXP,
    format!(r"^([^ ]+(?:\u02bb |\u2019 | |' ) *)({DOT}+)$")
);
static_re!(
    /// `CSL.PARTICLE_FAMILY_REGEXP`.
    PARTICLE_FAMILY_REGEXP,
    format!(r"^([^ ]+(?:\-|\u02bb|\u2019| |') *)({DOT}+)$")
);
static_re!(
    /// `CSL.SUPERSCRIPTS_REGEXP` (global in JS): one of the [`SUPERSCRIPTS`] characters.
    SUPERSCRIPTS_REGEXP,
    {
        let mut class = String::from("[");
        for (c, _) in SUPERSCRIPTS {
            class.push_str(&format!("\\x{{{:x}}}", *c as u32));
        }
        class.push(']');
        class
    }
);

/// `CSL.TITLE_SPLIT_REGEXP`: the three regexes built from one alternation.
#[derive(Debug)]
pub struct TitleSplitRegexp {
    /// `match`: global match of a split point (capturing).
    pub match_: Regex,
    /// `matchfirst`: a split point at the start of the string.
    pub matchfirst: Regex,
    /// `split`: the non-capturing form, for `String.prototype.split`.
    pub split: Regex,
}

/// `CSL.TITLE_SPLIT_REGEXP`.
pub static TITLE_SPLIT_REGEXP: LazyLock<TitleSplitRegexp> = LazyLock::new(|| {
    let splits = [
        format!(r"\.{WS_CLASS}+"),
        format!(r"!{WS_CLASS}+"),
        format!(r"\?{WS_CLASS}+"),
        format!(r"{WS_CLASS}*::*{WS_CLASS}+"),
        format!(r"{WS_CLASS}*\u2014{WS_CLASS}*"),
        format!(r"{WS_CLASS}+-{WS_CLASS}+"),
        format!(r"{WS_CLASS}*---*{WS_CLASS}*"),
    ]
    .join("|");
    TitleSplitRegexp {
        match_: Regex::new(&format!("({splits})")).expect("static citeproc regex"),
        matchfirst: Regex::new(&format!("^({splits})")).expect("static citeproc regex"),
        split: Regex::new(&format!("(?:{splits})")).expect("static citeproc regex"),
    }
});

/// `CSL.VARIABLE_WRAPPER_PREPUNCT_REX`: `^([ .!?:,]*)(.*)`, built by
/// `CSL.Engine` when `sys.variableWrapper` is set (build.js:23-25) from
/// `[" "].concat(CSL.SWAPPING_PUNCTUATION)`.
pub fn variable_wrapper_prepunct_rex() -> &'static Regex {
    static RE: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(&format!(r"^([ .!?:,]*)({DOT}*)")).expect("static citeproc regex")
    });
    &RE
}

/// `CSL.STATUTE_SUBDIV_STRINGS`.
pub const STATUTE_SUBDIV_STRINGS: &[(&str, &str)] = &[
    ("vrs.", "verse"),
    ("sv.", "sub-verbo"),
    ("subpara.", "subparagraph"),
    ("op.", "opus"),
    ("subch.", "subchapter"),
    ("add.", "addendum"),
    ("amend.", "amendment"),
    ("annot.", "annotation"),
    ("app.", "appendix"),
    ("art.", "article"),
    ("bibliog.", "bibliography"),
    ("bk.", "book"),
    ("ch.", "chapter"),
    ("cl.", "clause"),
    ("col.", "column"),
    ("cmt.", "comment"),
    ("dec.", "decision"),
    ("dept.", "department"),
    ("ex.", "example"),
    ("fig.", "figure"),
    ("fld.", "field"),
    ("fol.", "folio"),
    ("n.", "note"),
    ("hypo.", "hypothetical"),
    ("illus.", "illustration"),
    ("intro.", "introduction"),
    ("l.", "line"),
    ("no.", "issue"),
    ("p.", "page"),
    ("pp.", "page"),
    ("para.", "paragraph"),
    ("pt.", "part"),
    ("pmbl.", "preamble"),
    ("princ.", "principle"),
    ("pub.", "publication"),
    ("r.", "rule"),
    ("rn.", "randnummer"),
    ("sched.", "schedule"),
    ("sec.", "section"),
    ("ser.", "series,"),
    ("subdiv.", "subdivision"),
    ("subsec.", "subsection"),
    ("supp.", "supplement"),
    ("tbl.", "table"),
    ("tit.", "title"),
    ("vol.", "volume"),
];

/// `CSL.STATUTE_SUBDIV_STRINGS_REVERSE`.
pub const STATUTE_SUBDIV_STRINGS_REVERSE: &[(&str, &str)] = &[
    ("verse", "vrs."),
    ("sub-verbo", "sv."),
    ("sub verbo", "sv."),
    ("subparagraph", "subpara."),
    ("opus", "op."),
    ("subchapter", "subch."),
    ("addendum", "add."),
    ("amendment", "amend."),
    ("annotation", "annot."),
    ("appendix", "app."),
    ("article", "art."),
    ("bibliography", "bibliog."),
    ("book", "bk."),
    ("chapter", "ch."),
    ("clause", "cl."),
    ("column", "col."),
    ("comment", "cmt."),
    ("decision", "dec."),
    ("department", "dept."),
    ("example", "ex."),
    ("figure", "fig."),
    ("field", "fld."),
    ("folio", "fol."),
    ("note", "n."),
    ("hypothetical", "hypo."),
    ("illustration", "illus."),
    ("introduction", "intro."),
    ("line", "l."),
    ("issue", "no."),
    ("page", "p."),
    ("paragraph", "para."),
    ("part", "pt."),
    ("preamble", "pmbl."),
    ("principle", "princ."),
    ("publication", "pub."),
    ("rule", "r."),
    ("randnummer", "rn."),
    ("schedule", "sched."),
    ("section", "sec."),
    ("series,", "ser."),
    ("subdivision", "subdiv."),
    ("subsection", "subsec."),
    ("supplement", "supp."),
    ("table", "tbl."),
    ("title", "tit."),
    ("volume", "vol."),
];

/// `CSL.LOCATOR_LABELS_MAP`.
pub const LOCATOR_LABELS_MAP: &[(&str, &str)] = &[
    ("vrs", "verse"),
    ("sv", "sub-verbo"),
    ("subpara", "subparagraph"),
    ("op", "opus"),
    ("subch", "subchapter"),
    ("add", "addendum"),
    ("amend", "amendment"),
    ("annot", "annotation"),
    ("app", "appendix"),
    ("art", "article"),
    ("bibliog", "bibliography"),
    ("bk", "book"),
    ("ch", "chapter"),
    ("cl", "clause"),
    ("col", "column"),
    ("cmt", "comment"),
    ("dec", "decision"),
    ("dept", "department"),
    ("ex", "example"),
    ("fig", "figure"),
    ("fld", "field"),
    ("fol", "folio"),
    ("n", "note"),
    ("hypo", "hypothetical"),
    ("illus", "illustration"),
    ("intro", "introduction"),
    ("l", "line"),
    ("no", "issue"),
    ("p", "page"),
    ("pp", "page"),
    ("para", "paragraph"),
    ("pt", "part"),
    ("pmbl", "preamble"),
    ("princ", "principle"),
    ("pub", "publication"),
    ("r", "rule"),
    ("rn", "randnummer"),
    ("sched", "schedule"),
    ("sec", "section"),
    ("ser", "series,"),
    ("subdiv", "subdivision"),
    ("subsec", "subsection"),
    ("supp", "supplement"),
    ("tbl", "table"),
    ("tit", "title"),
    ("vol", "volume"),
];

/// `CSL.MODULE_MACROS` (the keys; every value is `true`).
pub const MODULE_MACROS: &[&str] = &[
    "juris-pretitle",
    "juris-title",
    "juris-pretitle-short",
    "juris-title-short",
    "juris-main",
    "juris-main-short",
    "juris-tail",
    "juris-tail-short",
    "juris-locator",
];

/// `CSL.MODULE_TYPES` (the keys; every value is `true`).
pub const MODULE_TYPES: &[&str] = &[
    "legal_case",
    "legislation",
    "bill",
    "hearing",
    "gazette",
    "report",
    "regulation",
    "standard",
    "patent",
    "locator",
];

/// `CSL.MULTI_FIELDS`.
pub const MULTI_FIELDS: &[&str] = &[
    "event",
    "publisher",
    "publisher-place",
    "event-place",
    "title",
    "container-title",
    "collection-title",
    "authority",
    "genre",
    "title-short",
    "medium",
    "country",
    "jurisdiction",
    "archive",
    "archive-place",
];

/// `CSL.LangPrefsMap`.
pub const LANG_PREFS_MAP: &[(&str, &str)] = &[
    ("title", "titles"),
    ("title-short", "titles"),
    ("event", "titles"),
    ("genre", "titles"),
    ("medium", "titles"),
    ("container-title", "journals"),
    ("collection-title", "titles"),
    ("archive", "journals"),
    ("publisher", "publishers"),
    ("authority", "publishers"),
    ("publisher-place", "places"),
    ("event-place", "places"),
    ("archive-place", "places"),
    ("jurisdiction", "places"),
    ("number", "places"),
    ("edition", "places"),
    ("issue", "places"),
    ("volume", "places"),
];

/// `CSL.FIELD_CATEGORY_REMAP`.
pub const FIELD_CATEGORY_REMAP: &[(&str, &str)] = &[
    ("title", "title"),
    ("container-title", "container-title"),
    ("collection-title", "collection-title"),
    ("country", "place"),
    ("number", "number"),
    ("place", "place"),
    ("archive", "container-title"),
    ("title-short", "title"),
    ("genre", "title"),
    ("event", "title"),
    ("medium", "title"),
    ("archive-place", "place"),
    ("publisher-place", "place"),
    ("event-place", "place"),
    ("jurisdiction", "place"),
    ("language-name", "place"),
    ("language-name-original", "place"),
    ("call-number", "number"),
    ("chapter-number", "number"),
    ("collection-number", "number"),
    ("edition", "number"),
    ("page", "number"),
    ("issue", "number"),
    ("locator", "number"),
    ("locator-extra", "number"),
    ("number-of-pages", "number"),
    ("number-of-volumes", "number"),
    ("volume", "number"),
    ("citation-number", "number"),
    ("publisher", "institution-part"),
];

/// `CSL.GENDERS`.
pub const GENDERS: &[&str] = &[
    "masculine",
    "feminine",
];

/// `CSL.POSITION_TEST_VARS`.
pub const POSITION_TEST_VARS: &[&str] = &[
    "position",
    "first-reference-note-number",
    "near-note",
];

/// `CSL.AREAS`.
pub const AREAS: &[&str] = &[
    "citation",
    "citation_sort",
    "bibliography",
    "bibliography_sort",
    "intext",
];

/// `CSL.CITE_FIELDS`.
pub const CITE_FIELDS: &[&str] = &[
    "first-reference-note-number",
    "first-container-reference-note-number",
    "locator",
    "locator-extra",
];

/// `CSL.SWAPPING_PUNCTUATION`.
pub const SWAPPING_PUNCTUATION: &[&str] = &[
    ".",
    "!",
    "?",
    ":",
    ",",
];

/// `CSL.TERMINAL_PUNCTUATION`.
pub const TERMINAL_PUNCTUATION: &[&str] = &[
    ":",
    ".",
    ";",
    "!",
    "?",
    " ",
];

/// `CSL.DATE_PARTS`.
pub const DATE_PARTS: &[&str] = &[
    "year",
    "month",
    "day",
];

/// `CSL.DATE_PARTS_ALL`.
pub const DATE_PARTS_ALL: &[&str] = &[
    "year",
    "month",
    "day",
    "season",
];

/// `CSL.DATE_PARTS_INTERNAL`.
pub const DATE_PARTS_INTERNAL: &[&str] = &[
    "year",
    "month",
    "day",
    "year_end",
    "month_end",
    "day_end",
];

/// `CSL.NAME_PARTS`.
pub const NAME_PARTS: &[&str] = &[
    "non-dropping-particle",
    "family",
    "given",
    "dropping-particle",
    "suffix",
    "literal",
];

/// `CSL.DISAMBIGUATE_OPTIONS`.
pub const DISAMBIGUATE_OPTIONS: &[&str] = &[
    "disambiguate-add-names",
    "disambiguate-add-givenname",
    "disambiguate-add-year-suffix",
];

/// `CSL.GIVENNAME_DISAMBIGUATION_RULES`.
pub const GIVENNAME_DISAMBIGUATION_RULES: &[&str] = &[
    "all-names",
    "all-names-with-initials",
    "primary-name",
    "primary-name-with-initials",
    "by-cite",
];

/// `CSL.NAME_ATTRIBUTES`.
pub const NAME_ATTRIBUTES: &[&str] = &[
    "and",
    "delimiter-precedes-last",
    "delimiter-precedes-et-al",
    "initialize-with",
    "initialize",
    "name-as-sort-order",
    "sort-separator",
    "et-al-min",
    "et-al-use-first",
    "et-al-subsequent-min",
    "et-al-subsequent-use-first",
    "form",
    "prefix",
    "suffix",
    "delimiter",
];

/// `CSL.DISPLAY_CLASSES`.
pub const DISPLAY_CLASSES: &[&str] = &[
    "block",
    "left-margin",
    "right-inline",
    "indent",
];

/// `CSL.NAME_VARIABLES`.
pub const NAME_VARIABLES: &[&str] = &[
    "author",
    "chair",
    "collection-editor",
    "compiler",
    "composer",
    "container-author",
    "contributor",
    "curator",
    "director",
    "editor",
    "editor-translator",
    "editorial-director",
    "executive-producer",
    "guest",
    "host",
    "illustrator",
    "interviewer",
    "narrator",
    "organizer",
    "original-author",
    "performer",
    "producer",
    "recipient",
    "reviewed-author",
    "script-writer",
    "series-creator",
    "translator",
    "commenter",
];

/// `CSL.CREATORS`.
pub const CREATORS: &[&str] = &[
    "author",
    "chair",
    "collection-editor",
    "compiler",
    "composer",
    "container-author",
    "contributor",
    "curator",
    "director",
    "editor",
    "editor-translator",
    "editorial-director",
    "executive-producer",
    "guest",
    "host",
    "illustrator",
    "interviewer",
    "narrator",
    "organizer",
    "original-author",
    "performer",
    "producer",
    "recipient",
    "reviewed-author",
    "script-writer",
    "series-creator",
    "translator",
    "commenter",
];

/// `CSL.NUMERIC_VARIABLES`.
pub const NUMERIC_VARIABLES: &[&str] = &[
    "call-number",
    "chapter-number",
    "collection-number",
    "division",
    "edition",
    "page",
    "issue",
    "locator",
    "locator-extra",
    "number",
    "number-of-pages",
    "number-of-volumes",
    "part-number",
    "printing-number",
    "section",
    "supplement-number",
    "version",
    "volume",
    "supplement",
    "citation-number",
];

/// `CSL.DATE_VARIABLES`.
pub const DATE_VARIABLES: &[&str] = &[
    "locator-date",
    "issued",
    "event-date",
    "accessed",
    "original-date",
    "publication-date",
    "available-date",
    "submitted",
    "alt-issued",
    "alt-event",
];

/// `CSL.VARIABLES_WITH_SHORT_FORM`.
pub const VARIABLES_WITH_SHORT_FORM: &[&str] = &[
    "title",
    "container-title",
];

/// `CSL.SKIP_WORDS`: the default `skip-words` of a locale's `opts`.
pub const SKIP_WORDS: &[&str] = &[
    "about",
    "above",
    "across",
    "afore",
    "after",
    "against",
    "al",
    "along",
    "alongside",
    "amid",
    "amidst",
    "among",
    "amongst",
    "anenst",
    "apropos",
    "apud",
    "around",
    "as",
    "aside",
    "astride",
    "at",
    "athwart",
    "atop",
    "barring",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "but",
    "by",
    "circa",
    "despite",
    "down",
    "during",
    "et",
    "except",
    "for",
    "forenenst",
    "from",
    "given",
    "in",
    "inside",
    "into",
    "lest",
    "like",
    "modulo",
    "near",
    "next",
    "notwithstanding",
    "of",
    "off",
    "on",
    "onto",
    "out",
    "over",
    "per",
    "plus",
    "pro",
    "qua",
    "sans",
    "since",
    "than",
    "through",
    " thru",
    "throughout",
    "thruout",
    "till",
    "to",
    "toward",
    "towards",
    "under",
    "underneath",
    "until",
    "unto",
    "up",
    "upon",
    "versus",
    "vs.",
    "v.",
    "vs",
    "v",
    "via",
    "vis-à-vis",
    "with",
    "within",
    "without",
    "according to",
    "ahead of",
    "apart from",
    "as for",
    "as of",
    "as per",
    "as regards",
    "aside from",
    "back to",
    "because of",
    "close to",
    "due to",
    "except for",
    "far from",
    "inside of",
    "instead of",
    "near to",
    "next to",
    "on to",
    "out from",
    "out of",
    "outside of",
    "prior to",
    "pursuant to",
    "rather than",
    "regardless of",
    "such as",
    "that of",
    "up to",
    "where as",
    "or",
    "yet",
    "so",
    "for",
    "and",
    "nor",
    "a",
    "an",
    "the",
    "de",
    "d'",
    "von",
    "van",
    "c",
    "ca",
];

/// `CSL.FORMAT_KEY_SEQUENCE`: the order decorations are applied in.
pub const FORMAT_KEY_SEQUENCE: &[&str] = &[
    "@strip-periods",
    "@font-style",
    "@font-variant",
    "@font-weight",
    "@text-decoration",
    "@vertical-align",
    "@quotes",
];

/// `CSL.INSTITUTION_KEYS`.
pub const INSTITUTION_KEYS: &[&str] = &[
    "font-style",
    "font-variant",
    "font-weight",
    "text-decoration",
    "text-case",
];

/// `CSL.SYS_OPTIONS`.
pub const SYS_OPTIONS: &[&str] = &[
    "prioritize_disambiguate_condition",
    "csl_reverse_lookup_support",
    "main_title_from_short_title",
    "uppercase_subtitles",
    "force_short_title_casing_alignment",
    "implicit_short_title",
    "split_container_title",
];

/// `CSL.ROMAN_NUMERALS`.
pub const ROMAN_NUMERALS: [&[&str]; 4] = [
    &["", "i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix"],
    &["", "x", "xx", "xxx", "xl", "l", "lx", "lxx", "lxxx", "xc"],
    &["", "c", "cc", "ccc", "cd", "d", "dc", "dcc", "dccc", "cm"],
    &["", "m", "mm", "mmm", "mmmm", "mmmmm"],
];

/// `CSL.LANGS`.
pub const LANGS: &[(&str, &str)] = &[
    ("af-ZA", "Afrikaans"),
    ("ar", "Arabic"),
    ("bg-BG", "Bulgarian"),
    ("ca-AD", "Catalan"),
    ("cs-CZ", "Czech"),
    ("da-DK", "Danish"),
    ("de-AT", "Austrian"),
    ("de-CH", "German (CH)"),
    ("de-DE", "German (DE)"),
    ("el-GR", "Greek"),
    ("en-GB", "English (GB)"),
    ("en-US", "English (US)"),
    ("es-ES", "Spanish"),
    ("et-EE", "Estonian"),
    ("eu", "European"),
    ("fa-IR", "Persian"),
    ("fi-FI", "Finnish"),
    ("fr-CA", "French (CA)"),
    ("fr-FR", "French (FR)"),
    ("he-IL", "Hebrew"),
    ("hr-HR", "Croatian"),
    ("hu-HU", "Hungarian"),
    ("is-IS", "Icelandic"),
    ("it-IT", "Italian"),
    ("ja-JP", "Japanese"),
    ("km-KH", "Khmer"),
    ("ko-KR", "Korean"),
    ("lt-LT", "Lithuanian"),
    ("lv-LV", "Latvian"),
    ("mn-MN", "Mongolian"),
    ("nb-NO", "Norwegian (Bokmål)"),
    ("nl-NL", "Dutch"),
    ("nn-NO", "Norwegian (Nynorsk)"),
    ("pl-PL", "Polish"),
    ("pt-BR", "Portuguese (BR)"),
    ("pt-PT", "Portuguese (PT)"),
    ("ro-RO", "Romanian"),
    ("ru-RU", "Russian"),
    ("sk-SK", "Slovak"),
    ("sl-SI", "Slovenian"),
    ("sr-RS", "Serbian"),
    ("sv-SE", "Swedish"),
    ("th-TH", "Thai"),
    ("tr-TR", "Turkish"),
    ("uk-UA", "Ukrainian"),
    ("vi-VN", "Vietnamese"),
    ("zh-CN", "Chinese (CN)"),
    ("zh-TW", "Chinese (TW)"),
];

/// `CSL.LANG_BASES` (underscores as upstream has them).
pub const LANG_BASES: &[(&str, &str)] = &[
    ("af", "af_ZA"),
    ("ar", "ar"),
    ("bg", "bg_BG"),
    ("ca", "ca_AD"),
    ("cs", "cs_CZ"),
    ("da", "da_DK"),
    ("de", "de_DE"),
    ("el", "el_GR"),
    ("en", "en_US"),
    ("es", "es_ES"),
    ("et", "et_EE"),
    ("eu", "eu"),
    ("fa", "fa_IR"),
    ("fi", "fi_FI"),
    ("fr", "fr_FR"),
    ("he", "he_IL"),
    ("hr", "hr-HR"),
    ("hu", "hu_HU"),
    ("is", "is_IS"),
    ("it", "it_IT"),
    ("ja", "ja_JP"),
    ("km", "km_KH"),
    ("ko", "ko_KR"),
    ("lt", "lt_LT"),
    ("lv", "lv-LV"),
    ("mn", "mn_MN"),
    ("nb", "nb_NO"),
    ("nl", "nl_NL"),
    ("nn", "nn-NO"),
    ("pl", "pl_PL"),
    ("pt", "pt_PT"),
    ("ro", "ro_RO"),
    ("ru", "ru_RU"),
    ("sk", "sk_SK"),
    ("sl", "sl_SI"),
    ("sr", "sr_RS"),
    ("sv", "sv_SE"),
    ("th", "th_TH"),
    ("tr", "tr_TR"),
    ("uk", "uk_UA"),
    ("vi", "vi_VN"),
    ("zh", "zh_CN"),
];

/// `CSL.SUPERSCRIPTS`: superscript character to its plain form.
pub const SUPERSCRIPTS: &[(char, &str)] = &[
    ('\u{00AA}', "a"),
    ('\u{00B2}', "2"),
    ('\u{00B3}', "3"),
    ('\u{00B9}', "1"),
    ('\u{00BA}', "o"),
    ('\u{02B0}', "h"),
    ('\u{02B1}', "ɦ"),
    ('\u{02B2}', "j"),
    ('\u{02B3}', "r"),
    ('\u{02B4}', "ɹ"),
    ('\u{02B5}', "ɻ"),
    ('\u{02B6}', "ʁ"),
    ('\u{02B7}', "w"),
    ('\u{02B8}', "y"),
    ('\u{02E0}', "ɣ"),
    ('\u{02E1}', "l"),
    ('\u{02E2}', "s"),
    ('\u{02E3}', "x"),
    ('\u{02E4}', "ʕ"),
    ('\u{1D2C}', "A"),
    ('\u{1D2D}', "Æ"),
    ('\u{1D2E}', "B"),
    ('\u{1D30}', "D"),
    ('\u{1D31}', "E"),
    ('\u{1D32}', "Ǝ"),
    ('\u{1D33}', "G"),
    ('\u{1D34}', "H"),
    ('\u{1D35}', "I"),
    ('\u{1D36}', "J"),
    ('\u{1D37}', "K"),
    ('\u{1D38}', "L"),
    ('\u{1D39}', "M"),
    ('\u{1D3A}', "N"),
    ('\u{1D3C}', "O"),
    ('\u{1D3D}', "Ȣ"),
    ('\u{1D3E}', "P"),
    ('\u{1D3F}', "R"),
    ('\u{1D40}', "T"),
    ('\u{1D41}', "U"),
    ('\u{1D42}', "W"),
    ('\u{1D43}', "a"),
    ('\u{1D44}', "ɐ"),
    ('\u{1D45}', "ɑ"),
    ('\u{1D46}', "ᴂ"),
    ('\u{1D47}', "b"),
    ('\u{1D48}', "d"),
    ('\u{1D49}', "e"),
    ('\u{1D4A}', "ə"),
    ('\u{1D4B}', "ɛ"),
    ('\u{1D4C}', "ɜ"),
    ('\u{1D4D}', "g"),
    ('\u{1D4F}', "k"),
    ('\u{1D50}', "m"),
    ('\u{1D51}', "ŋ"),
    ('\u{1D52}', "o"),
    ('\u{1D53}', "ɔ"),
    ('\u{1D54}', "ᴖ"),
    ('\u{1D55}', "ᴗ"),
    ('\u{1D56}', "p"),
    ('\u{1D57}', "t"),
    ('\u{1D58}', "u"),
    ('\u{1D59}', "ᴝ"),
    ('\u{1D5A}', "ɯ"),
    ('\u{1D5B}', "v"),
    ('\u{1D5C}', "ᴥ"),
    ('\u{1D5D}', "β"),
    ('\u{1D5E}', "γ"),
    ('\u{1D5F}', "δ"),
    ('\u{1D60}', "φ"),
    ('\u{1D61}', "χ"),
    ('\u{2070}', "0"),
    ('\u{2071}', "i"),
    ('\u{2074}', "4"),
    ('\u{2075}', "5"),
    ('\u{2076}', "6"),
    ('\u{2077}', "7"),
    ('\u{2078}', "8"),
    ('\u{2079}', "9"),
    ('\u{207A}', "+"),
    ('\u{207B}', "−"),
    ('\u{207C}', "="),
    ('\u{207D}', "("),
    ('\u{207E}', ")"),
    ('\u{207F}', "n"),
    ('\u{2120}', "SM"),
    ('\u{2122}', "TM"),
    ('\u{3192}', "一"),
    ('\u{3193}', "二"),
    ('\u{3194}', "三"),
    ('\u{3195}', "四"),
    ('\u{3196}', "上"),
    ('\u{3197}', "中"),
    ('\u{3198}', "下"),
    ('\u{3199}', "甲"),
    ('\u{319A}', "乙"),
    ('\u{319B}', "丙"),
    ('\u{319C}', "丁"),
    ('\u{319D}', "天"),
    ('\u{319E}', "地"),
    ('\u{319F}', "人"),
    ('\u{02C0}', "ʔ"),
    ('\u{02C1}', "ʕ"),
    ('\u{06E5}', "و"),
    ('\u{06E6}', "ي"),
];

// ----------------------------------------------------------------------
// Lookups over the tables above.

fn pair_lookup(table: &'static [(&'static str, &'static str)], key: &str) -> Option<&'static str> {
    table.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}

/// `CSL.STATUTE_SUBDIV_STRINGS[key]`.
pub fn statute_subdiv_string(key: &str) -> Option<&'static str> {
    pair_lookup(STATUTE_SUBDIV_STRINGS, key)
}

/// `CSL.STATUTE_SUBDIV_STRINGS_REVERSE[key]`.
pub fn statute_subdiv_string_reverse(key: &str) -> Option<&'static str> {
    pair_lookup(STATUTE_SUBDIV_STRINGS_REVERSE, key)
}

/// `CSL.LOCATOR_LABELS_MAP[key]`.
pub fn locator_labels_map(key: &str) -> Option<&'static str> {
    pair_lookup(LOCATOR_LABELS_MAP, key)
}

/// `CSL.MODULE_MACROS[name]` (truthy for the listed names).
pub fn is_module_macro(name: &str) -> bool {
    MODULE_MACROS.contains(&name)
}

/// `CSL.MODULE_TYPES[name]` (truthy for the listed types).
pub fn is_module_type(name: &str) -> bool {
    MODULE_TYPES.contains(&name)
}

/// `CSL.LangPrefsMap[field]`.
pub fn lang_prefs_map(field: &str) -> Option<&'static str> {
    pair_lookup(LANG_PREFS_MAP, field)
}

/// `CSL.FIELD_CATEGORY_REMAP[field]`.
pub fn field_category_remap(field: &str) -> Option<&'static str> {
    pair_lookup(FIELD_CATEGORY_REMAP, field)
}

/// `CSL.LANG_BASES[lang]` (e.g. `"en"` to `"en_US"`).
pub fn lang_base(lang: &str) -> Option<&'static str> {
    pair_lookup(LANG_BASES, lang)
}

/// `CSL.LANGS[tag]`.
pub fn lang_name(tag: &str) -> Option<&'static str> {
    pair_lookup(LANGS, tag)
}

/// `CSL.SUPERSCRIPTS[c]`.
pub fn superscript(c: char) -> Option<&'static str> {
    SUPERSCRIPTS.iter().find(|(k, _)| *k == c).map(|(_, v)| *v)
}

/// `CSL.AbbreviationSegments`: the twelve empty abbreviation tables of one
/// jurisdiction.
pub fn abbreviation_segments() -> Obj {
    let mut o = Obj::new();
    for k in [
        "container-title",
        "collection-title",
        "institution-entire",
        "institution-part",
        "nickname",
        "number",
        "title",
        "place",
        "hereinafter",
        "classic",
        "container-phrase",
        "title-phrase",
    ] {
        o.insert(k.to_string(), Value::Object(Obj::new()));
    }
    o
}

/// `CSL.TITLE_FIELD_SPLITS(seg)`: the field names of a title and its parts.
#[derive(Debug, Clone, PartialEq)]
pub struct TitleFieldSplits {
    /// `title`: `seg + "title"`.
    pub title: String,
    /// `short`: `seg + "title-short"`.
    pub short: String,
    /// `main`: `seg + "title-main"`.
    pub main: String,
    /// `sub`: `seg + "title-sub"`.
    pub sub: String,
    /// `subjoin`: `seg + "title-subjoin"`.
    pub subjoin: String,
}

/// `CSL.TITLE_FIELD_SPLITS(seg)`; `seg` is `""` or `"container-"`.
pub fn title_field_splits(seg: &str) -> TitleFieldSplits {
    TitleFieldSplits {
        title: format!("{seg}title"),
        short: format!("{seg}title-short"),
        main: format!("{seg}title-main"),
        sub: format!("{seg}title-sub"),
        subjoin: format!("{seg}title-subjoin"),
    }
}

// ----------------------------------------------------------------------
// Case conversion.

/// Whether the first language tag of `arr` selects Turkic casing.
fn turkic(arr: &[String]) -> bool {
    arr.first()
        .map(|t| {
            let p = t.split(['-', '_']).next().unwrap_or("").to_lowercase();
            p == "tr" || p == "az"
        })
        .unwrap_or(false)
}

/// `CSL.toLocaleUpperCase.call(state, str)`: `str.toLocaleUpperCase(
/// state.tmp.lang_array)`. Locale-sensitive casing is implemented for the
/// Turkic languages (`i` to `İ`); other tags use the root mapping, which is
/// what ICU does for them except Lithuanian and Greek (not ported).
pub fn to_locale_upper_case(state: &State, s: &str) -> String {
    if turkic(&state.tmp.lang_array) {
        let mut out = String::new();
        for c in s.chars() {
            match c {
                'i' => out.push('\u{130}'),
                'ı' => out.push('I'),
                c => out.extend(c.to_uppercase()),
            }
        }
        out
    } else {
        s.to_uppercase()
    }
}

/// `CSL.toLocaleLowerCase.call(state, str)`; see [`to_locale_upper_case`]
/// (Turkic: `I` to `ı`, `İ` to `i`).
pub fn to_locale_lower_case(state: &State, s: &str) -> String {
    if turkic(&state.tmp.lang_array) {
        let mut out = String::new();
        for c in s.chars() {
            match c {
                'I' => out.push('\u{131}'),
                '\u{130}' => out.push('i'),
                c => out.extend(c.to_lowercase()),
            }
        }
        out
    } else {
        s.to_lowercase()
    }
}

// ----------------------------------------------------------------------
// Brace nesting.

/// `new CSL.checkNestedBrace(state)`: flips the parentheses of nested
/// affixes in a note style (`(a (b))` to `(a [b])`).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct CheckNestedBrace {
    /// `depth`.
    pub depth: i64,
    /// Whether `state.opt.xclass === "note"` (otherwise `update` is the identity).
    note: bool,
}

impl CheckNestedBrace {
    /// `new CSL.checkNestedBrace(state)`.
    pub fn new(state: &State) -> CheckNestedBrace {
        CheckNestedBrace {
            depth: 0,
            note: js::get_str(&state.opt, "xclass") == Some("note"),
        }
    }

    /// `this.update(str)`: receives an affix string, returns it with
    /// parentheses flipped to brackets at odd nesting depths.
    pub fn update(&mut self, s: &str) -> String {
        if !self.note {
            return s.to_string();
        }
        let mut out = String::with_capacity(s.len());
        for c in s.chars() {
            match c {
                '(' => {
                    out.push(if self.depth % 2 == 1 { '[' } else { '(' });
                    self.depth += 1;
                }
                ')' => {
                    out.push(if self.depth % 2 == 0 { ']' } else { ')' });
                    self.depth -= 1;
                }
                c => out.push(c),
            }
        }
        out
    }
}

// ----------------------------------------------------------------------
// Locale strings.

/// `CSL.normalizeLocaleStr(str)`: language lower-case, region upper-case
/// (`en-us` to `en-US`). `None` is JS `undefined` (empty input).
pub fn normalize_locale_str(s: &str) -> Option<String> {
    if s.is_empty() {
        return None;
    }
    let mut lst: Vec<String> = s.split('-').map(str::to_string).collect();
    lst[0] = lst[0].to_lowercase();
    if lst.len() > 1 && !lst[1].is_empty() {
        lst[1] = lst[1].to_uppercase();
    }
    Some(lst.join("-"))
}

/// `CSL.getAbbrevsDomain(state, country, lang)`: the jurisdiction domain
/// whose abbreviations apply, from the item's locale's and the engine's
/// `jurisdiction-preference` (last preferred first).
pub fn get_abbrevs_domain(state: &State, country: &str, lang: &str) -> Option<String> {
    let available = state.opt.get("availableAbbrevDomains");
    if js::truthy_opt(available) && !country.is_empty() && country != "default" {
        let pref_of = |tag: &str| -> Option<Vec<Value>> {
            match state
                .locale
                .get(tag)
                .and_then(|l| l.opts.get("jurisdiction-preference"))
            {
                Some(Value::Array(a)) => Some(a.clone()),
                _ => None,
            }
        };
        let global = pref_of(js::get_str(&state.opt, "lang").unwrap_or(""));
        let item = pref_of(lang);
        let domains: Vec<Value> = match available.and_then(|a| a.get(country)) {
            Some(Value::Array(a)) => a.clone(),
            _ => Vec::new(),
        };
        for pref in [item, global].into_iter().flatten() {
            for j in (0..pref.len()).rev() {
                if domains.contains(&pref[j]) {
                    return pref[j].as_str().map(str::to_string);
                }
            }
        }
    }
    None
}

// ----------------------------------------------------------------------
// Locators and note fields.

/// A date-parser seam. `CSL.DateParser.parseDateToObject` (src/util_dateparser.js,
/// wave1-input) is not ported yet: this returns `null`.
///
/// PORT-LATER(util_dateparser): replace with
/// `state.fun.dateparser.parse_date_to_object(raw)`.
fn parse_date_to_object(_state: &State, _raw: &str) -> Value {
    Value::Null
}

/// A date-parser seam: `CSL.DateParser.parseDateToArray(str)` (the engine
/// singleton). PORT-LATER(util_dateparser): returns `null` until ported.
fn parse_date_to_array(_raw: &str) -> Value {
    Value::Null
}

/// A name-particle seam: `CSL.parseParticles(name)` (src/util_name_particles.js,
/// wave1-input). PORT-LATER(util_name_particles): leaves `name` unchanged.
fn parse_particles(_name: &mut Obj) {}

/// `CSL.parseLocator.call(state, item)`: splits `locator|date extra` into
/// `locator`, `locator-date` and `locator-extra` when
/// `locator_date_and_revision` is on, and trims trailing space of `locator`.
pub fn parse_locator(state: &State, item: &mut Obj) {
    let ext_on = state
        .opt
        .get("development_extensions")
        .and_then(|d| d.get("locator_date_and_revision"))
        .map(js::truthy)
        .unwrap_or(false);
    if ext_on && js::get_truthy(item, "locator") {
        let loc = js::get_string(item, "locator").unwrap_or_default();
        item.insert("locator".into(), Value::String(loc.clone()));
        let idx = js::index_of(&loc, "|", 0);
        if idx > -1 {
            let mut raw_locator = loc.clone();
            item.insert(
                "locator".into(),
                Value::String(js::slice(&raw_locator, 0, Some(idx))),
            );
            raw_locator = js::slice(&raw_locator, idx + 1, None);
            static DATE: LazyLock<Regex> =
                LazyLock::new(|| Regex::new(r"^([0-9]{4}-[0-9]{2}-[0-9]{2})").expect("static"));
            if let Some(m) = DATE.captures(&raw_locator) {
                let m1 = m[1].to_string();
                item.insert("locator-date".into(), parse_date_to_object(state, &m1));
                raw_locator = js::slice(&raw_locator, js::len(&m1) as i64, None);
            }
            item.insert(
                "locator-extra".into(),
                Value::String(js::trim(&raw_locator).to_string()),
            );
        }
    }
    if js::get_truthy(item, "locator") {
        static TRAILING: LazyLock<Regex> =
            LazyLock::new(|| Regex::new(&format!("{WS_CLASS}+$")).expect("static"));
        let loc = js::get_string(item, "locator").unwrap_or_default();
        item.insert(
            "locator".into(),
            Value::String(TRAILING.replace(&loc, "").into_owned()),
        );
    }
}

/// `CSL.parseNoteFieldHacks(Item, validFieldsForType, allowDateOverride)`:
/// lift `{:key:value}` and `key: value` lines of the `note` field into the
/// item. The engine calls it with `validFieldsForType = false`; a non-`None`
/// set reaches `this.isDateString`, which does not exist on `CSL`, so a date
/// field with one throws, as upstream.
pub fn parse_note_field_hacks(
    item: &mut Obj,
    valid_fields_for_type: Option<&Obj>,
    allow_date_override: bool,
) -> CslResult<()> {
    let note = match item.get("note") {
        Some(Value::String(s)) => s.clone(),
        _ => return Ok(()),
    };
    let mut lines: Vec<String> = note.split('\n').map(str::to_string).collect();
    // Normalize entries
    for i in 0..lines.len() {
        let line = lines[i].clone();
        let m: Vec<String> = NOTE_FIELDS_REGEXP
            .find_iter(&line)
            .map(|m| m.as_str().to_string())
            .collect();
        if !m.is_empty() {
            let splt = js::split(&NOTE_FIELDS_REGEXP, &line);
            let mut elems: Vec<String> = Vec::new();
            for j in 0..splt.len() - 1 {
                elems.push(splt[j].clone());
                elems.push(m.get(j).cloned().unwrap_or_else(|| "undefined".to_string()));
            }
            elems.push(splt[splt.len() - 1].clone());
            let mut j = 1;
            while j < elems.len() {
                // Abort conversions if preceded by unparseable text
                if !js::trim(&elems[j - 1]).is_empty()
                    && (i > 0 || j > 1)
                    && !NOTE_FIELD_REGEXP.is_match(&elems[j - 1])
                {
                    break;
                } else {
                    let inner = js::slice(&elems[j], 2, Some(-1));
                    elems[j] = format!("\n{}\n", js::trim(&inner));
                }
                j += 2;
            }
            lines[i] = elems.concat();
        }
    }
    // Resplit
    let joined = lines.join("\n");
    let mut lines: Vec<String> = joined.split('\n').map(str::to_string).collect();
    let mut names: Vec<(String, Vec<Value>)> = Vec::new();
    for i in 0..lines.len() {
        let line = lines[i].clone();
        let mm = NOTE_FIELD_REGEXP.captures(&line);
        if js::trim(&line).is_empty() {
            continue;
        }
        let Some(mm) = mm else {
            if i == 0 {
                continue;
            } else {
                break;
            }
        };
        let key = mm[1].to_string();
        let val = js::trim(&mm[2]).to_string();
        let bare = key.strip_prefix("alt-").unwrap_or(&key);
        if key == "type" {
            item.insert("type".into(), Value::String(val));
            lines[i] = String::new();
        } else if DATE_VARIABLES.contains(&bare) {
            if !js::get_truthy(item, &key) || allow_date_override {
                item.insert(key.clone(), parse_date_to_array(&val));
                let ok = match valid_fields_for_type {
                    None => true,
                    Some(v) => {
                        if js::get_truthy(v, &key) {
                            return Err(EngineError::Csl(
                                "TypeError: this.isDateString is not a function".to_string(),
                            ));
                        }
                        false
                    }
                };
                if ok {
                    lines[i] = String::new();
                }
            }
        } else if !js::get_truthy(item, &key) {
            if NAME_VARIABLES.contains(&bare) {
                if !names.iter().any(|(k, _)| *k == key) {
                    names.push((key.clone(), Vec::new()));
                }
                static SPLIT: LazyLock<Regex> = LazyLock::new(|| {
                    Regex::new(&format!(r"{WS_CLASS}*\|\|{WS_CLASS}*")).expect("static")
                });
                let lst = js::split(&SPLIT, &val);
                let slot = names.iter_mut().find(|(k, _)| *k == key).map(|(_, v)| v);
                if let Some(slot) = slot {
                    if lst.len() == 1 {
                        let mut o = Obj::new();
                        o.insert("literal".into(), Value::String(lst[0].clone()));
                        slot.push(Value::Object(o));
                    } else if lst.len() == 2 {
                        let mut name = Obj::new();
                        name.insert("family".into(), Value::String(lst[0].clone()));
                        name.insert("given".into(), Value::String(lst[1].clone()));
                        parse_particles(&mut name);
                        slot.push(Value::Object(name));
                    }
                }
            } else {
                item.insert(key.clone(), Value::String(val));
            }
            if valid_fields_for_type.map(|v| js::get_truthy(v, &key)).unwrap_or(true) {
                lines[i] = String::new();
            }
        }
    }
    for (key, v) in names {
        item.insert(key, Value::Array(v));
    }
    // (The "final cleanup for validCslFields only" block runs only when
    // validFieldsForType is truthy; the engine never passes one.)
    item.insert(
        "note".into(),
        Value::String(js::trim(&lines.join("\n")).to_string()),
    );
    Ok(())
}

// ----------------------------------------------------------------------
// Punctuation spacing.

fn strip_tags_and_trailing_space(prefix: &str) -> String {
    static TAGS: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"<[^>]+>").expect("static"));
    static TRAIL: LazyLock<Regex> =
        LazyLock::new(|| Regex::new("[\"'\u{201d}\u{2019}\u{00bb}\u{202f}\u{00a0} ]+$").expect("static"));
    let s = TAGS.replace_all(prefix, "");
    TRAIL.replace_all(&s, "").into_owned()
}

/// `CSL.checkPrefixSpaceAppend(state, prefix)`: `prefix` with a space
/// appended when it ends in a letter, terminal punctuation, `)`, `]`, `,` or
/// a digit (after stripping markup and trailing quotes), and runs of white
/// space collapsed.
pub fn check_prefix_space_append(_state: &State, prefix: &str) -> String {
    let mut sp = "";
    let test_prefix = strip_tags_and_trailing_space(prefix);
    let test_char = js::slice(&test_prefix, -1, None);
    static BRACKET_DIGIT: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(r"[\)\],0-9]").expect("static"));
    if ENDSWITH_ROMANESQUE_REGEXP.is_match(&test_prefix) {
        sp = " ";
    } else if TERMINAL_PUNCTUATION[..TERMINAL_PUNCTUATION.len() - 1].contains(&test_char.as_str()) {
        sp = " ";
    } else if BRACKET_DIGIT.is_match(&test_char) {
        sp = " ";
    }
    // Protect against double spaces, which would trigger an extra,
    // explicit, non-breaking space.
    static RUNS: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(&format!("{WS_CLASS}+")).expect("static"));
    RUNS.replace_all(&format!("{prefix}{sp}"), " ").into_owned()
}

/// `CSL.checkIgnorePredecessor(state, prefix)`: true (and
/// `state.tmp.term_predecessor = false`) when the prefix ends in terminal
/// punctuation and holds a space.
pub fn check_ignore_predecessor(state: &mut State, prefix: &str) -> bool {
    let test_prefix = strip_tags_and_trailing_space(prefix);
    let test_char = js::slice(&test_prefix, -1, None);
    if TERMINAL_PUNCTUATION[..TERMINAL_PUNCTUATION.len() - 1].contains(&test_char.as_str())
        && js::index_of(js::trim(prefix), " ", 0) > -1
    {
        state.tmp.term_predecessor = false;
        return true;
    }
    false
}

/// `CSL.checkSuffixSpacePrepend(state, suffix)`: a space before a suffix
/// that starts with a letter, `&`, `[` or `(`.
pub fn check_suffix_space_prepend(_state: &State, suffix: &str) -> String {
    if suffix.is_empty() {
        return String::new();
    }
    let first = js::slice(suffix, 0, Some(1));
    if STARTSWITH_ROMANESQUE_REGEXP.is_match(suffix) || first == "[" || first == "(" {
        return format!(" {suffix}");
    }
    suffix.to_string()
}

// ----------------------------------------------------------------------
// Titles.

/// `CSL.demoteNoiseWords(state, fld, drop_or_demote)`: drop, or move to the
/// end after a comma, the leading noise words of a name or title.
///
/// For a `drop_or_demote` that is neither `"drop"` nor `"demote"` upstream
/// returns the (reversed-twice, noise-trimmed) *array*; here its
/// comma-joined string, which is what JS string coercion gives.
pub fn demote_noise_words(state: &State, fld: &str, drop_or_demote: &str) -> String {
    if fld.is_empty() || drop_or_demote.is_empty() {
        return fld.to_string();
    }
    let skip: Vec<String> = state
        .locale
        .get(js::get_str(&state.opt, "lang").unwrap_or(""))
        .and_then(|l| l.opts.get("leading-noise-words"))
        .and_then(Value::as_array)
        .map(|a| a.iter().map(js::to_js_string).collect())
        .unwrap_or_default();
    static WS_RUN: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(&format!("{WS_CLASS}+")).expect("static"));
    let mut words = js::split(&WS_RUN, fld);
    words.reverse();
    let mut to_end: Vec<String> = Vec::new();
    let mut j = words.len() as i64 - 1;
    while j > -1 {
        let w = words[j as usize].to_lowercase();
        if skip.contains(&w) {
            if let Some(popped) = words.pop() {
                to_end.push(popped);
            }
        } else {
            break;
        }
        j -= 1;
    }
    words.reverse();
    let start = words.join(" ");
    let end = to_end.join(" ");
    if drop_or_demote == "drop" || end.is_empty() {
        start
    } else if drop_or_demote == "demote" {
        [start, end].join(", ")
    } else {
        words.join(",")
    }
}

/// `CSL.TITLE_SPLIT(str)`: split a title at its sub-title joins, returning
/// `[main, join, sub, join, sub, ...]`. A split point preceded by a word
/// that ends in a capital is recombined into the preceding text, so
/// "U.S. Foo" is not split.
pub fn title_split(s: &str) -> Vec<String> {
    if s.is_empty() {
        return Vec::new();
    }
    let m: Vec<String> = TITLE_SPLIT_REGEXP
        .match_
        .find_iter(s)
        .map(|m| m.as_str().to_string())
        .collect();
    let mut lst = js::split(&TITLE_SPLIT_REGEXP.split, s);
    let mut i = lst.len() as i64 - 2;
    while i > -1 {
        let iu = i as usize;
        lst[iu] = js::trim(&lst[iu]).to_string();
        let last = js::slice(&lst[iu], -1, None);
        let m_i = m.get(iu).cloned().unwrap_or_else(|| "undefined".to_string());
        if !lst[iu].is_empty() && last.to_lowercase() != last {
            // recombine
            let next = lst.remove(iu + 1);
            lst[iu] = format!("{}{}{}", lst[iu], m_i, next);
        } else {
            // merge
            lst.insert(iu + 1, m_i);
        }
        i -= 1;
    }
    lst
}

/// A formatter seam. `CSL.Output.Formatters.sentence(state, str)`
/// (src/formatters.js, wave1-output). PORT-LATER(formatters): identity.
fn formatter_sentence(_state: &State, s: &str) -> String {
    s.to_string()
}

/// A formatter seam. `CSL.Output.Formatters["capitalize-first"](state, str)`
/// (src/formatters.js, wave1-output). PORT-LATER(formatters): identity.
fn formatter_capitalize_first(_state: &State, s: &str) -> String {
    s.to_string()
}

fn js_type_error(what: &str) -> EngineError {
    EngineError::Csl(format!("TypeError: {what}"))
}

/// A value of an item field as the string JS methods would be called on;
/// `Err` (a TypeError upstream) for a non-string.
fn text_of(v: &Value) -> CslResult<&str> {
    v.as_str()
        .ok_or_else(|| js_type_error("toLowerCase is not a function"))
}

impl State {
    /// `CSL.extractTitleAndSubtitle.call(state, Item, narrowSpaceLocale)`:
    /// split each title (and, with `split_container_title`, container
    /// title) into `title-main`, `title-sub` and `title-subjoin`, and
    /// possibly a short title, on the item and its `multi._keys` languages.
    ///
    /// Follows upstream's rules: an exactly matching short title makes the
    /// whole title the main title; a short title that is a prefix of the
    /// title, followed by a split point, splits there; otherwise
    /// [`title_split`] must find exactly one join. Joins containing `?`/`!`
    /// move that mark into the main title; `:` becomes ": " and `-`/`—`
    /// becomes an em dash.
    pub fn extract_title_and_subtitle(
        &self,
        item: &mut Obj,
        narrow_space_locale: bool,
    ) -> CslResult<()> {
        let narrow_space = if narrow_space_locale { "\u{202f}" } else { "" };
        let dev = |k: &str| {
            self.opt
                .get("development_extensions")
                .and_then(|d| d.get(k))
                .map(js::truthy)
                .unwrap_or(false)
        };
        let mut segments = vec![""];
        if dev("split_container_title") {
            segments.push("container-");
        }
        for seg in segments {
            let title = title_field_splits(seg);
            let mut langs: Vec<Option<String>> = vec![None];
            if js::get_truthy(item, "multi") {
                let keys = item.get("multi").and_then(|m| m.get("_keys"));
                match keys {
                    None => {
                        return Err(js_type_error(&format!(
                            "Cannot read properties of undefined (reading '{}')",
                            title.short
                        )))
                    }
                    Some(k) => {
                        if let Some(Value::Object(m)) = k.get(&title.short) {
                            for lang in m.keys() {
                                langs.push(Some(lang.clone()));
                            }
                        }
                    }
                }
            }
            for lang in langs {
                // vals: key -> Option<Value>; None is JS undefined.
                let mut vals: Vec<(String, Option<Value>)> = Vec::new();
                fn set(vals: &mut Vec<(String, Option<Value>)>, k: &str, v: Option<Value>) {
                    if let Some(s) = vals.iter_mut().find(|(a, _)| a == k) {
                        s.1 = v;
                    } else {
                        vals.push((k.to_string(), v));
                    }
                }
                fn get(vals: &[(String, Option<Value>)], k: &str) -> Option<Value> {
                    vals.iter().find(|(a, _)| a == k).and_then(|(_, v)| v.clone())
                }
                if let Some(lang) = &lang {
                    let keys = item
                        .get("multi")
                        .and_then(|m| m.get("_keys"))
                        .cloned()
                        .unwrap_or(Value::Null);
                    if js::truthy_opt(keys.get(&title.title)) {
                        set(&mut vals, &title.title, keys[&title.title].get(lang).cloned());
                    }
                    if js::truthy_opt(keys.get(&title.short)) {
                        set(&mut vals, &title.short, keys[&title.short].get(lang).cloned());
                    }
                } else {
                    set(&mut vals, &title.title, item.get(&title.title).cloned());
                    set(&mut vals, &title.short, item.get(&title.short).cloned());
                }
                let t = get(&vals, &title.title);
                set(&mut vals, &title.main, t.clone());
                set(&mut vals, &title.sub, Some(Value::Bool(false)));
                let short_title = get(&vals, &title.short);
                if js::truthy_opt(t.as_ref()) {
                    let t = t.clone().unwrap_or(Value::Null);
                    let title_text = text_of(&t)?.to_string();
                    // Rules
                    // TITLE_SPLIT eliminates split-points of period-space
                    // preceded by a capital letter. If short title exists and
                    // matches exactly to a split-point, use that split-point
                    // only. Otherwise if there is just one split-point, use
                    // that as main/sub split.
                    let set_str = |vals: &mut Vec<(String, Option<Value>)>, k: &str, v: &str| {
                        set(vals, k, Some(Value::String(v.to_string())))
                    };
                    if js::truthy_opt(short_title.as_ref())
                        && text_of(short_title.as_ref().unwrap_or(&Value::Null))?.to_lowercase()
                            == title_text.to_lowercase()
                    {
                        set_str(&mut vals, &title.main, &title_text);
                        set_str(&mut vals, &title.subjoin, "");
                        set_str(&mut vals, &title.sub, "");
                    } else if js::truthy_opt(short_title.as_ref()) {
                        let short_text = text_of(short_title.as_ref().unwrap_or(&Value::Null))?
                            .to_string();
                        static QE_END: LazyLock<Regex> =
                            LazyLock::new(|| Regex::new(r"[?!]+$").expect("static"));
                        static QE_START: LazyLock<Regex> =
                            LazyLock::new(|| Regex::new(r"^[?!]+").expect("static"));
                        // check for valid match to shortTitle
                        let short_trim = QE_END.replace(&short_text, "").into_owned();
                        let tail = js::slice(&title_text, js::len(&short_trim) as i64, None);
                        let tail_stripped = QE_START.replace(&tail, "").into_owned();
                        let top = js::trim(&title_text.replacen(&tail_stripped, "", 1)).to_string();
                        let m = TITLE_SPLIT_REGEXP.matchfirst.captures(&tail);
                        if m.is_some() && top.to_lowercase() == short_text.to_lowercase() {
                            let m1 = m.as_ref().map(|c| c[1].to_string()).unwrap_or_default();
                            static QE_WS: LazyLock<Regex> = LazyLock::new(|| {
                                Regex::new(&format!("[?!]+({WS_CLASS}*)$")).expect("static")
                            });
                            set_str(&mut vals, &title.main, &top);
                            set_str(
                                &mut vals,
                                &title.subjoin,
                                &QE_WS.replace(&m1, "${1}"),
                            );
                            set_str(
                                &mut vals,
                                &title.sub,
                                &TITLE_SPLIT_REGEXP.matchfirst.replace(&tail, ""),
                            );
                            if dev("force_short_title_casing_alignment") {
                                let main = get(&vals, &title.main);
                                set(&mut vals, &title.short, main);
                            }
                        } else {
                            let split_title = title_split(&title_text);
                            if split_title.len() == 3 {
                                set_str(&mut vals, &title.main, &split_title[0]);
                                set_str(&mut vals, &title.subjoin, &split_title[1]);
                                set_str(&mut vals, &title.sub, &split_title[2]);
                            } else {
                                set_str(&mut vals, &title.main, &title_text);
                                set_str(&mut vals, &title.subjoin, "");
                                set_str(&mut vals, &title.sub, "");
                            }
                        }
                    } else {
                        let split_title = title_split(&title_text);
                        if split_title.len() == 3 {
                            set_str(&mut vals, &title.main, &split_title[0]);
                            set_str(&mut vals, &title.subjoin, &split_title[1]);
                            set_str(&mut vals, &title.sub, &split_title[2]);
                            if dev("implicit_short_title")
                                && js::get_str(item, "type") != Some("legal_case")
                            {
                                static NUMERIC_MAIN: LazyLock<Regex> = LazyLock::new(|| {
                                    Regex::new(r"^[\-.\[0-9]+$").expect("static")
                                });
                                if !js::get_truthy(item, &title.short)
                                    && !NUMERIC_MAIN.is_match(&split_title[0])
                                {
                                    let mut punct = js::trim(&split_title[1]).to_string();
                                    if punct != "?" && punct != "!" {
                                        punct = String::new();
                                    }
                                    set_str(
                                        &mut vals,
                                        &title.short,
                                        &format!("{}{}", split_title[0], punct),
                                    );
                                }
                            }
                        } else {
                            set_str(&mut vals, &title.main, &title_text);
                            set_str(&mut vals, &title.subjoin, "");
                            set_str(&mut vals, &title.sub, "");
                        }
                    }
                    let subjoin = get(&vals, &title.subjoin);
                    if js::truthy_opt(subjoin.as_ref()) {
                        let sj = text_of(subjoin.as_ref().unwrap_or(&Value::Null))?.to_string();
                        if sj.contains('?') || sj.contains('!') {
                            static TRAIL_WS: LazyLock<Regex> = LazyLock::new(|| {
                                Regex::new(&format!("({WS_CLASS}*)$")).expect("static")
                            });
                            let m1 = TRAIL_WS
                                .captures(&sj)
                                .map(|c| c[1].to_string())
                                .unwrap_or_default();
                            let main = get(&vals, &title.main)
                                .map(|v| js::to_js_string(&v))
                                .unwrap_or_else(|| "undefined".to_string());
                            set_str(
                                &mut vals,
                                &title.main,
                                &format!("{main}{narrow_space}{}", js::trim(&sj)),
                            );
                            set_str(&mut vals, &title.subjoin, &m1);
                        }
                    }
                }
                let subjoin = get(&vals, &title.subjoin);
                if js::truthy_opt(subjoin.as_ref()) {
                    let mut sj = js::to_js_string(subjoin.as_ref().unwrap_or(&Value::Null));
                    if sj.contains(':') {
                        sj = format!("{narrow_space}: ");
                    }
                    if sj.contains('-') || sj.contains('\u{2014}') {
                        sj = "\u{2014}".to_string();
                    }
                    set(&mut vals, &title.subjoin, Some(Value::String(sj)));
                }
                if let Some(lang) = &lang {
                    let multi = item
                        .entry("multi".to_string())
                        .or_insert_with(|| Value::Object(Obj::new()));
                    let keys = match multi.get_mut("_keys") {
                        Some(k) if k.is_object() => k,
                        _ => {
                            return Err(js_type_error(
                                "Cannot read properties of undefined (reading '_keys')",
                            ))
                        }
                    };
                    for (key, v) in vals {
                        let slot = keys
                            .as_object_mut()
                            .map(|o| o.entry(key).or_insert_with(|| Value::Object(Obj::new())));
                        if let Some(Value::Object(o)) = slot {
                            match v {
                                Some(v) => {
                                    o.insert(lang.clone(), v);
                                }
                                None => {
                                    o.remove(lang);
                                }
                            }
                        }
                    }
                } else {
                    for (key, v) in vals {
                        match v {
                            Some(v) => {
                                item.insert(key, v);
                            }
                            None => {
                                item.remove(&key);
                            }
                        }
                    }
                }
            }
        }
        Ok(())
    }

    /// `CSL.titlecaseSentenceOrNormal(state, Item, seg, lang, sentenceCase)`:
    /// the title, optionally sentence-cased, rebuilt from its main/sub parts
    /// (or, for `uppercase_subtitles`, with each part capitalised). Always the
    /// full title, never the short one (upstream's comment).
    ///
    /// PORT-LATER(formatters): `CSL.Output.Formatters.sentence` and
    /// `["capitalize-first"]` are src/formatters.js (wave1-output); they are
    /// identity stand-ins in this file.
    pub fn titlecase_sentence_or_normal(
        &self,
        item: &Obj,
        seg: &str,
        lang: Option<&str>,
        sentence_case: bool,
    ) -> CslResult<String> {
        let title = title_field_splits(seg);
        let mut vals: Vec<(String, Option<Value>)> = Vec::new();
        let multi = item.get("multi").filter(|m| js::truthy(m));
        if let (Some(lang), Some(multi)) = (lang.filter(|l| !l.is_empty()), multi) {
            let keys = multi.get("_keys").cloned().unwrap_or(Value::Null);
            for k in [&title.title, &title.main, &title.sub, &title.subjoin] {
                if js::truthy_opt(keys.get(k)) {
                    vals.push((k.clone(), keys[k].get(lang).cloned()));
                }
            }
        } else {
            for k in [&title.title, &title.main, &title.sub, &title.subjoin] {
                vals.push((k.clone(), item.get(k).cloned()));
            }
        }
        let get = |k: &str| {
            vals.iter()
                .find(|(a, _)| a == k)
                .and_then(|(_, v)| v.clone())
        };
        let s = |v: Option<Value>| v.map(|v| js::to_js_string(&v)).unwrap_or_default();
        if js::truthy_opt(get(&title.main).as_ref()) && js::truthy_opt(get(&title.sub).as_ref()) {
            let mut main_title = s(get(&title.main));
            let sub_join = s(get(&title.subjoin));
            let mut sub_title = s(get(&title.sub));
            if sentence_case {
                main_title = formatter_sentence(self, &main_title);
                sub_title = formatter_sentence(self, &sub_title);
            } else if self
                .opt
                .get("development_extensions")
                .and_then(|d| d.get("uppercase_subtitles"))
                .map(js::truthy)
                .unwrap_or(false)
            {
                sub_title = formatter_capitalize_first(self, &sub_title);
            }
            Ok(format!("{main_title}{sub_join}{sub_title}"))
        } else if js::truthy_opt(get(&title.title).as_ref()) {
            let whole = s(get(&title.title));
            if sentence_case {
                Ok(formatter_sentence(self, &whole))
            } else if self
                .opt
                .get("development_extensions")
                .and_then(|d| d.get("uppercase_subtitles"))
                .map(js::truthy)
                .unwrap_or(false)
            {
                // Split and apply everywhere.
                let mut splits = title_split(&whole);
                let mut i = 0;
                while i < splits.len() {
                    splits[i] = formatter_capitalize_first(self, &splits[i]);
                    i += 2;
                }
                let mut i = 1;
                while i + 1 < splits.len() {
                    static QSEP: LazyLock<Regex> =
                        LazyLock::new(|| Regex::new(r"([:?!] )").expect("static"));
                    if let Some(m) = QSEP.captures(&splits[i]) {
                        let fr = js::get_str(&self.opt, "default-locale").is_some()
                            || self
                                .opt
                                .get("default-locale")
                                .and_then(|d| d.get(0))
                                .and_then(Value::as_str)
                                .map(|d| js::slice(d, 0, Some(2)).to_lowercase() == "fr")
                                .unwrap_or(false);
                        let narrow = if self
                            .opt
                            .get("default-locale")
                            .and_then(|d| d.get(0))
                            .and_then(Value::as_str)
                            .map(|d| js::slice(d, 0, Some(2)).to_lowercase() == "fr")
                            .unwrap_or(false)
                        {
                            "\u{202f}"
                        } else {
                            ""
                        };
                        let _ = fr;
                        splits[i] = format!("{narrow}{}", &m[1]);
                    }
                    if splits[i].contains('-') || splits[i].contains('\u{2014}') {
                        splits[i] = "\u{2014}".to_string();
                    }
                    i += 2;
                }
                Ok(splits.concat())
            } else {
                Ok(whole)
            }
        } else {
            Ok(String::new())
        }
    }
}

/// What `CSL.getSafeEscape(state)` returns: the text escaper for the area.
#[derive(Debug, Clone, PartialEq)]
pub enum SafeEscape {
    /// `function (txt) { return txt; }`: outside citations and bibliographies.
    Identity,
    /// `CSL.Output.Formats[mode].text_escape`, optionally after the thin
    /// space hack.
    Format {
        /// `state.opt.mode`.
        mode: String,
        /// Whether `thin_non_breaking_space_html_hack` applies
        /// (HTML mode only).
        thin_space_hack: bool,
    },
}

impl SafeEscape {
    /// Apply the escaper to `txt`.
    ///
    /// PORT-LATER(formats): `CSL.Output.Formats[mode].text_escape` is
    /// src/formats.js (wave1-output); until then the format's escaping is the
    /// identity here and only the thin-space callback is applied.
    pub fn apply(&self, txt: &str) -> String {
        match self {
            SafeEscape::Identity => txt.to_string(),
            SafeEscape::Format { thin_space_hack, .. } => {
                let mut t = txt.to_string();
                if *thin_space_hack {
                    t = t.replace(
                        '\u{202f}',
                        "<span style=\"white-space:nowrap\">&thinsp;</span>",
                    );
                }
                t
            }
        }
    }
}

/// `CSL.getSafeEscape(state)`.
pub fn get_safe_escape(state: &State) -> SafeEscape {
    if state.tmp.area == "bibliography" || state.tmp.area == "citation" {
        let hack = state
            .opt
            .get("development_extensions")
            .and_then(|d| d.get("thin_non_breaking_space_html_hack"))
            .map(js::truthy)
            .unwrap_or(false)
            && js::get_str(&state.opt, "mode") == Some("html");
        SafeEscape::Format {
            mode: js::get_str(&state.opt, "mode").unwrap_or("html").to_string(),
            thin_space_hack: hack,
        }
    } else {
        SafeEscape::Identity
    }
}

// ----------------------------------------------------------------------
// Group context conditions (comma-safe, empty-label, ...).

/// `CSL.UPDATE_GROUP_CONTEXT_CONDITION(state, str, valueTerm, token, value)`.
pub fn update_group_context_condition(
    state: &mut State,
    s: Option<&str>,
    value_term: bool,
    token: Option<&Token>,
    value: Option<&str>,
) {
    if !js::get_truthy(&state.opt, "use_context_condition") {
        return;
    }
    let has_condition = state
        .tmp
        .group_context
        .tip()
        .map(|f| f.condition.is_some())
        .unwrap_or(false);
    if has_condition {
        if let Some(flags) = state.tmp.group_context.tip_mut() {
            let mut numbers_only_value_seen = false;
            if let Some(cond) = flags.condition.as_mut() {
                if cond.termtxt.as_deref().map(str::is_empty).unwrap_or(true) {
                    cond.termtxt = s.map(str::to_string);
                    cond.value_term = value_term;
                }
                numbers_only_value_seen =
                    !flags.value_seen && cond.test == "comma-safe-numbers-only";
            }
            if numbers_only_value_seen {
                if let Some(v) = value.filter(|v| !v.is_empty()) {
                    flags.value_seen = true;
                    if !v.starts_with(|c: char| c.is_ascii_digit()) {
                        state.tmp.just_did_number = false;
                    }
                }
            }
        }
    } else {
        // If not inside a conditional group, raise numeric flag
        // if and only if the current term string ends in a number.
        if token
            .map(|t| t.decorations.iter().any(|d| d.name == "@vertical-align"))
            .unwrap_or(false)
        {
            state.tmp.just_did_number = false;
        } else if token.map(|t| js::truthy_opt(t.strings.get("suffix"))).unwrap_or(false) {
            state.tmp.just_did_number = false;
        } else if let Some(s) = s.filter(|s| !s.is_empty()) {
            state.tmp.just_did_number = s.ends_with(|c: char| c.is_ascii_digit());
        }
    }
}

/// `CSL.EVALUATE_GROUP_CONDITION(state, flags)`: `force_suppress` for a
/// conditional group once its content is known. `None` is upstream's early
/// `return;` (the context condition is not enabled).
pub fn evaluate_group_condition(
    state: &State,
    flags: &super::state::GroupContext,
) -> Option<bool> {
    if !js::get_truthy(&state.opt, "use_context_condition") {
        return None;
    }
    let cond = flags.condition.as_ref()?;
    let numbers_only = cond.test == "comma-safe-numbers-only";
    let termtxt = cond.termtxt.as_deref().unwrap_or("");
    let mut testres = false;
    if cond.test == "empty-label" {
        testres = termtxt.is_empty();
    } else if cond.test == "empty-label-no-decor" {
        testres = termtxt.is_empty() || termtxt.contains("%s");
    } else if cond.test == "comma-safe" || cond.test == "comma-safe-numbers-only" {
        let locale_term = !termtxt.is_empty();
        let term_start_alpha = locale_term && ALL_ROMANESQUE_REGEXP.is_match(&js::slice(termtxt, 0, Some(1)));
        let require = js::get_str(&state.opt, "require_comma_on_symbol");
        if state.tmp.just_did_number {
            if cond.value_term {
                testres = !numbers_only;
            } else if !locale_term {
                testres = true;
            } else if term_start_alpha {
                testres = !numbers_only;
            } else {
                testres = matches!(require, Some("always") | Some("after-number"));
            }
        } else if cond.value_term {
            testres = false;
        } else if !locale_term {
            testres = false;
        } else if term_start_alpha {
            testres = !numbers_only;
        } else {
            testres = require == Some("always");
        }
    }
    let mut force_suppress = !testres;
    if cond.not {
        force_suppress = !force_suppress;
    }
    Some(force_suppress)
}

// ----------------------------------------------------------------------
// Court classes and jurisdiction modules.

/// `CSL.GET_COURT_CLASS.call(token, state, Item, sortKey)`: the class a
/// court belongs to, looked up in the token's locale (`lang`, the `this.lang`
/// of the attribute handler) and then in the default locale. `""` when none.
pub fn get_court_class(state: &State, lang: Option<&str>, item: &Value, sort_key: bool) -> String {
    let jurisdiction = item.get("jurisdiction").and_then(Value::as_str);
    let country = jurisdiction
        .filter(|j| !j.is_empty())
        .map(|j| j.split(':').next().unwrap_or("").to_string());
    let class_type = if sort_key {
        "court_key_classes"
    } else {
        "court_condition_classes"
    };
    let mut authority: Option<String> = None;
    if country.is_some() && js::truthy_opt(item.get("authority")) {
        match item.get("authority") {
            Some(Value::String(a)) => authority = Some(a.clone()),
            Some(a) => {
                if let Some(lit) = a.get(0).and_then(|f| f.get("literal")) {
                    if js::truthy(lit) {
                        authority = Some(js::to_js_string(lit));
                    }
                }
            }
            None => {}
        }
    }
    if let (Some(authority), Some(country)) = (authority, country) {
        let find = |tag: &str| -> Option<String> {
            state
                .locale
                .get(tag)
                .and_then(|l| l.opts.get(class_type))
                .and_then(|c| c.get(&country))
                .and_then(|c| c.get(&authority))
                .filter(|v| js::truthy(v))
                .map(js::to_js_string)
        };
        if let Some(l) = lang.filter(|l| !l.is_empty()) {
            if let Some(c) = find(l) {
                return c;
            }
        }
        let default_locale = state
            .opt
            .get("default-locale")
            .and_then(|d| d.get(0))
            .and_then(Value::as_str)
            .unwrap_or("");
        if let Some(c) = find(default_locale) {
            return c;
        }
    }
    String::new()
}

/// `CSL.SET_COURT_CLASSES(state, lang, myxml, dataObj)`: record the
/// `court-class` nodes of `data_obj` in `state.locale[lang].opts`, under
/// `court_key_classes` (in-style declarations, before the registry exists) or
/// `court_condition_classes` (in-module).
pub fn set_court_classes(
    state: &mut State,
    lang: &str,
    myxml: &XmlJson,
    data_obj: Option<NodeId>,
) -> CslResult<()> {
    let nodes = myxml.get_nodes_by_name(data_obj, "court-class", "");
    for node in nodes {
        let attributes = myxml.attributes(node);
        let attr = |k: &str| {
            attributes
                .iter()
                .find(|(a, _)| a == k)
                .map(|(_, v)| js::to_js_string(v))
        };
        let cls = attr("@name");
        let country = attr("@country");
        let courts = attr("@courts");

        // Okay, this is a hack.
        // If state.registry IS NOT yet defined, this is an in-style declaration.
        // If state.registry IS defined, this is an in-module declaration.
        let class_type = if state.has_registry {
            "court_condition_classes"
        } else {
            "court_key_classes"
        };
        if let (Some(cls), Some(country), Some(courts)) = (
            cls.filter(|s| !s.is_empty()),
            country.filter(|s| !s.is_empty()),
            courts.filter(|s| !s.is_empty()),
        ) {
            static WS_RUN: LazyLock<Regex> =
                LazyLock::new(|| Regex::new(&format!("{WS_CLASS}+")).expect("static"));
            let courts = js::split(&WS_RUN, js::trim(&courts));
            let locale = state.locale.get_mut(lang).ok_or_else(|| {
                js_type_error("Cannot read properties of undefined (reading 'opts')")
            })?;
            let by_type = locale
                .opts
                .entry(class_type.to_string())
                .or_insert_with(|| Value::Object(Obj::new()));
            let by_country = by_type
                .as_object_mut()
                .map(|o| o.entry(country).or_insert_with(|| Value::Object(Obj::new())));
            if let Some(Value::Object(by_country)) = by_country {
                for court in courts {
                    by_country.insert(court, Value::String(cls.clone()));
                }
            }
        }
    }
    Ok(())
}

/// `CSL.INIT_JURISDICTION_MACROS(state, Item, item, macroName)`: load the
/// style modules for the item's jurisdiction and record the best one in
/// `Item["best-jurisdiction"]`; true when the item's type is covered.
///
/// With no `sys.retrieveStyleModule` hook (`Sys::has_retrieve_style_module`
/// is false) this returns false right after the `best-jurisdiction` check,
/// as upstream does.
pub fn init_jurisdiction_macros(
    state: &mut State,
    item_full: &mut Value,
    cite_item: Option<&Value>,
    macro_name: &str,
) -> CslResult<bool> {
    if js::truthy_opt(item_full.get("best-jurisdiction")) {
        return Ok(true);
    }
    let jurisdiction = item_full
        .get("jurisdiction")
        .filter(|j| js::truthy(j))
        .map(js::to_js_string);
    let Some(jurisdiction) = jurisdiction else {
        return Ok(false);
    };
    if !state.sys.has_retrieve_style_module() || !is_module_macro(macro_name) {
        return Ok(false);
    }
    let jurisdiction_list = state.get_jurisdiction_list(&jurisdiction);
    let seen = state
        .opt
        .get("jurisdictions_seen")
        .and_then(|s| s.get(&jurisdiction_list[0]))
        .map(js::truthy)
        .unwrap_or(false);
    if !seen {
        let mut res = state.retrieve_all_style_modules(&jurisdiction_list);
        // Okay. We have code for each of the novel modules in the
        // hierarchy. Load them all into the processor.
        let keys: Vec<String> = res.iter().map(|(k, _)| k.clone()).collect();
        for j in keys {
            let src = res.iter().find(|(k, _)| *k == j).map(|(_, v)| v.clone());
            let fallback = state.load_style_module(&j, src.as_deref().unwrap_or(""), false)?;
            if let Some(fallback) = fallback {
                if !res.iter().any(|(k, _)| *k == fallback) {
                    for (k, v) in state.retrieve_all_style_modules(&[fallback.clone()]) {
                        if let Some(s) = res.iter_mut().find(|(a, _)| *a == k) {
                            s.1 = v;
                        } else {
                            res.push((k, v));
                        }
                    }
                    let src = res
                        .iter()
                        .find(|(k, _)| *k == fallback)
                        .map(|(_, v)| v.clone());
                    state.load_style_module(&fallback, src.as_deref().unwrap_or(""), true)?;
                }
            }
        }
    }
    let jurisdiction_list = state.get_jurisdiction_list(&jurisdiction);
    if state
        .opt
        .get("parallel")
        .and_then(|p| p.get("enable"))
        .map(js::truthy)
        .unwrap_or(false)
        && state.parallel.is_none()
    {
        state.parallel = Some(Default::default());
    }
    // Identify the best jurisdiction for the item and return true, otherwise return false
    let item_type = item_full
        .get("type")
        .map(js::to_js_string)
        .unwrap_or_default();
    for j in jurisdiction_list {
        if let Some(juris) = state.juris.get(&j) {
            if cite_item.is_some()
                && !js::truthy_opt(cite_item.and_then(|c| c.get("best-jurisdiction")))
                && juris.types.contains("locator")
            {
                if let Some(o) = item_full.as_object_mut() {
                    o.insert("best-jurisdiction".into(), Value::String(j.clone()));
                }
            }
            if juris.types.contains(item_type.as_str()) {
                if let Some(o) = item_full.as_object_mut() {
                    o.insert("best-jurisdiction".into(), Value::String(j.clone()));
                }
                return Ok(true);
            }
        }
    }
    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locale_strings_normalise() {
        assert_eq!(normalize_locale_str("en-us").as_deref(), Some("en-US"));
        assert_eq!(normalize_locale_str("DE").as_deref(), Some("de"));
        assert_eq!(normalize_locale_str(""), None);
        assert_eq!(normalize_locale_str("zh-tw-x").as_deref(), Some("zh-TW-x"));
    }

    #[test]
    fn nested_braces_flip_in_notes_only() {
        let mut st = State::default();
        st.opt.insert("xclass".into(), Value::String("note".into()));
        let mut c = CheckNestedBrace::new(&st);
        assert_eq!(c.update("(a (b))"), "(a [b])");
        assert_eq!(c.depth, 0);
        let mut plain = CheckNestedBrace::new(&State::default());
        assert_eq!(plain.update("(a (b))"), "(a (b))");
    }

    #[test]
    fn tables_have_upstream_sizes() {
        assert_eq!(NAME_VARIABLES.len(), 28);
        assert_eq!(DATE_VARIABLES.len(), 10);
        assert_eq!(SKIP_WORDS.len(), 133);
        assert_eq!(statute_subdiv_string("vol."), Some("volume"));
        assert_eq!(lang_base("en"), Some("en_US"));
        assert_eq!(superscript('\u{2122}'), Some("TM"));
        assert_eq!(position_map(4), Some(1));
    }

    #[test]
    fn title_split_recombines_after_capitals() {
        assert_eq!(
            title_split("Foo: bar baz"),
            vec!["Foo", ": ", "bar baz"]
        );
        // "U.S. Foo" does not split at ". " after a capital letter.
        assert_eq!(title_split("The U.S. Constitution"), vec!["The U.S. Constitution"]);
    }

    #[test]
    fn spacing_checks() {
        let st = State::default();
        assert_eq!(check_prefix_space_append(&st, "see"), "see ");
        assert_eq!(check_prefix_space_append(&st, "p."), "p. ");
        assert_eq!(check_prefix_space_append(&st, "("), "(");
        assert_eq!(check_suffix_space_prepend(&st, "abc"), " abc");
        assert_eq!(check_suffix_space_prepend(&st, ", abc"), ", abc");
    }
}
