//! Builds a [`CallGraph`] by asking rust-analyzer where every call-shaped
//! token in a function body resolves, breadth-first from an entry point.
//!
//! Port of kopitiam's `collect_callees` (`apps/cli/src/semq.rs`, commit
//! `dfdf1c4`), reworked in three ways:
//!
//! - **breadth-first with a global node set**, not depth-first with a
//!   `(path, line)` visited set shared across branches — kopitiam's visited
//!   set silently drops a callee from every branch after the first, and its
//!   depth-first order cannot give shortest chains;
//! - **recursion re-finds the callee from source text** (`super::source`),
//!   because this workspace's rust-analyzer answers `documentSymbol` with the
//!   flat shape kopitiam's `symbol_at` cannot match — the reason its second
//!   hop came back sparse (#523);
//! - **every token that does not resolve to a workspace function body is
//!   classified**: external (std or a dependency, filtered and counted),
//!   a constructor (ignored — not code), or a [`Gap`] that the output marks
//!   `UNRESOLVED(...)`.
//!
//! Definitions come from a [`Resolver`]: rust-analyzer's LSP (one query per
//! token, through the keep-warm daemon), or (GitHub #757) a SCIP index that
//! one `rust-analyzer scip` run wrote, looked up in memory. The SCIP
//! resolver answers the same positions the LSP is asked, so every
//! classification below is shared; it also reports the references the text
//! scanner cannot see (operators, functions passed as paths), which
//! [`Workspace::expand`] adds as [`EdgeKind::Operator`] and
//! [`EdgeKind::FnValue`] edges.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use kopitiam_semantic::RustAnalyzerSession;

use super::graph::{CallGraph, Edge, EdgeKind, FnNode, Gap, GapKind, NodeId};
use super::source::{is_known_macro, CandidateKind, Container, FileIndex, FnDecl};
use crate::commands::{lsp_daemon, semq};

/// Where definitions come from: the keep-warm daemon (`commands::lsp_daemon`,
/// preferred — its index survives across invocations), a session spawned
/// for this one run when no daemon can be reached (non-Unix targets), or a
/// SCIP index read from disk (#757).
pub(crate) enum Resolver {
    Daemon(PathBuf),
    Session(RustAnalyzerSession),
    Scip(ScipResolver),
}

/// A definition site: absolute path, 0-based line and char column.
type Site = (PathBuf, u32, u32);

/// The site the SCIP resolver gives a symbol defined outside the index (std
/// or a dependency): a relative path, so [`Workspace::relative`] places it
/// outside the workspace exactly as it does an LSP answer into the sysroot.
const EXTERNAL_SITE: &str = "<outside the SCIP index>";

/// The site the SCIP resolver gives a workspace symbol with no definition in
/// the index: one a derive or macro generated (`#[derive(Default)]`'s
/// `default`). The LSP answers such a query with the attribute's location,
/// which [`Workspace::expand`] reports as `UNRESOLVED(other)`; this marker
/// gives the same gap.
const GENERATED_SITE: &str = "<generated by a derive or macro>";

/// Answers definition queries from a SCIP index (#757). Columns are
/// converted between the scanner's char columns and the index's encoding on
/// the source line itself, so a non-ASCII character earlier on the line does
/// not shift the match.
pub(crate) struct ScipResolver {
    root: PathBuf,
    index: crate::scip::ScipIndex,
    lines: HashMap<String, Vec<String>>,
    /// 0-based body lines of the function being expanded: a same-file
    /// collision prefers the definition nested inside it.
    body: Option<(u32, u32)>,
}

/// A reference in a body that no call-shaped token covers: an operator or a
/// function named as a path (`.map(T::f)`), with where it is defined.
pub(crate) struct ExtraRef {
    /// 0-based line.
    pub(crate) line: u32,
    /// The token as written (`+`, `[`, `f`).
    pub(crate) token: String,
    /// An identifier (a path to a function) rather than an operator.
    pub(crate) ident: bool,
    pub(crate) site: Site,
}

/// Line `n` (0-based) of workspace file `rel`, read once and cached; empty
/// when the file or line is missing.
fn cached_line(lines: &mut HashMap<String, Vec<String>>, root: &Path, rel: &str, n: u32) -> String {
    let v = lines.entry(rel.to_string()).or_insert_with(|| {
        std::fs::read_to_string(root.join(rel))
            .map(|t| t.lines().map(str::to_string).collect())
            .unwrap_or_default()
    });
    v.get(n as usize).cloned().unwrap_or_default()
}

fn is_ident_token(t: &str) -> bool {
    !t.is_empty() && t.chars().all(|c| c == '_' || c.is_alphanumeric())
}

/// The first segment of the `a::b::` path written before char column `col`
/// of `line` (`a`), or `None` when the token at `col` is not qualified.
fn path_head(line: &str, col: u32) -> Option<String> {
    let chars: Vec<char> = line.chars().collect();
    let mut i = (col as usize).min(chars.len());
    let mut head = None;
    loop {
        let mut j = i;
        while j > 0 && chars[j - 1] == ' ' {
            j -= 1;
        }
        if j < 2 || chars[j - 1] != ':' || chars[j - 2] != ':' {
            return head;
        }
        let mut k = j - 2;
        while k > 0 && chars[k - 1] == ' ' {
            k -= 1;
        }
        let end = k;
        while k > 0 && (chars[k - 1] == '_' || chars[k - 1].is_alphanumeric()) {
            k -= 1;
        }
        if k == end {
            return head;
        }
        head = Some(chars[k..end].iter().collect());
        i = k;
    }
}

impl ScipResolver {
    pub(crate) fn new(root: &Path, index: crate::scip::ScipIndex) -> ScipResolver {
        ScipResolver {
            root: root.to_path_buf(),
            index,
            lines: HashMap::new(),
            body: None,
        }
    }

    fn rel(&self, abs: &Path) -> Option<String> {
        let r = abs.strip_prefix(&self.root).ok()?;
        Some(
            r.components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/"),
        )
    }

    /// Where `sym`, referenced at 0-based `line` of `rel` through a path
    /// starting `lead`, is defined, as an LSP answer would give it.
    fn site_of(
        &mut self,
        rel: &str,
        line: u32,
        sym: crate::scip::Sym,
        lead: Option<&str>,
    ) -> Option<Site> {
        use crate::scip::Sym;
        let ix = &self.index;
        match sym {
            Sym::Local(n) => {
                let doc = ix.document(rel)?;
                let d = doc.local_definition(n)?;
                let text = cached_line(&mut self.lines, &self.root, rel, d.line);
                Some((self.root.join(rel), d.line, doc.encoding.char_col_of_units(&text, d.start)))
            }
            Sym::Global(_) => match ix.nearest_definition(sym, rel, line, self.body, lead) {
                Some(d) => {
                    let doc = &ix.documents[d.doc as usize];
                    let text = cached_line(&mut self.lines, &self.root, &doc.path, d.line);
                    Some((self.root.join(&doc.path), d.line, doc.encoding.char_col_of_units(&text, d.start)))
                }
                None if ix.is_generated(sym) => Some((PathBuf::from(GENERATED_SITE), 0, 0)),
                None => Some((PathBuf::from(EXTERNAL_SITE), 0, 0)),
            },
        }
    }

    /// The definition of the identifier starting at each `[line, char]` of
    /// `file`: every single-line occurrence that starts exactly there and
    /// covers an identifier.
    fn definitions(&mut self, file: &Path, positions: &[[u32; 2]]) -> Vec<Vec<Site>> {
        let Some(rel) = self.rel(file) else {
            return vec![Vec::new(); positions.len()];
        };
        let mut out = Vec::with_capacity(positions.len());
        for &[l, c] in positions {
            let text = cached_line(&mut self.lines, &self.root, &rel, l);
            let mut syms = Vec::new();
            let mut own = None;
            if let Some(doc) = self.index.document(&rel) {
                let enc = doc.encoding;
                let u = enc.units_of_char_col(&text, c);
                for o in doc.at(l, u).filter(|o| o.end_line == o.line) {
                    // A definition answers with itself, as the LSP does (a
                    // nested `fn helper(` the scanner took for a call).
                    if o.is_definition() {
                        own = Some((self.root.join(&rel), l, c));
                        continue;
                    }
                    let ec = enc.char_col_of_units(&text, o.end);
                    let tok: String = text
                        .chars()
                        .skip(c as usize)
                        .take(ec.saturating_sub(c) as usize)
                        .collect();
                    if is_ident_token(&tok) {
                        syms.push(o.symbol);
                    }
                }
            }
            let lead = path_head(&text, c);
            let mut sites: Vec<Site> = own.into_iter().collect();
            for s in syms {
                if let Some(site) = self.site_of(&rel, l, s, lead.as_deref()) {
                    if !sites.contains(&site) {
                        sites.push(site);
                    }
                }
            }
            out.push(sites);
        }
        out
    }

    /// The references in a body that resolve inside the index but sit at no
    /// call-shaped token: operators and functions named as paths. `body` is
    /// [`FileIndex::body_code`]'s blanked text with the source line beside
    /// it; a token blank in the former (a comment, literal or `use`) is
    /// skipped, as is a definition, a local, a symbol with no definition in
    /// the index (std, dependencies), and anything at `skip` (the scanner's
    /// candidate positions, already asked).
    pub(crate) fn extra_references(
        &mut self,
        rel: &str,
        body: &[(u32, String, String)],
        skip: &HashSet<(u32, u32)>,
    ) -> Vec<ExtraRef> {
        let mut found = Vec::new();
        {
            let Some(doc) = self.index.document(rel) else {
                return Vec::new();
            };
            let enc = doc.encoding;
            for (ln, code, orig) in body {
                for o in doc.on_line(*ln) {
                    if o.end_line != o.line
                        || o.is_definition()
                        || matches!(o.symbol, crate::scip::Sym::Local(_))
                    {
                        continue;
                    }
                    let sc = enc.char_col_of_units(orig, o.start);
                    let ec = enc.char_col_of_units(orig, o.end);
                    if skip.contains(&(*ln, sc)) {
                        continue;
                    }
                    let tok: String = code
                        .chars()
                        .skip(sc as usize)
                        .take(ec.saturating_sub(sc) as usize)
                        .collect();
                    let tok = tok.trim().to_string();
                    if tok.is_empty() || self.index.definitions(o.symbol).is_empty() {
                        continue;
                    }
                    found.push((*ln, tok, o.symbol, path_head(orig, sc)));
                }
            }
        }
        let mut out = Vec::new();
        for (line, token, sym, lead) in found {
            if let Some(site) = self.site_of(rel, line, sym, lead.as_deref()) {
                out.push(ExtraRef {
                    line,
                    ident: is_ident_token(&token),
                    token,
                    site,
                });
            }
        }
        out
    }
}

impl Resolver {
    /// Connects to (or starts) the daemon for `root`, falling back to a
    /// one-shot session.
    pub(crate) fn connect(root: &Path) -> Result<Resolver, String> {
        let probe = lsp_daemon::Request::Definitions {
            file: root.join("Cargo.toml"),
            positions: Vec::new(),
        };
        match lsp_daemon::query(root, &probe) {
            Some(resp) if resp.ok => Ok(Resolver::Daemon(root.to_path_buf())),
            Some(resp) => Err(resp
                .error
                .unwrap_or_else(|| "lsp-daemon failed to become ready".to_string())),
            None => Ok(Resolver::Session(semq::connect(root)?)),
        }
    }

    fn definitions(&mut self, file: &Path, positions: &[[u32; 2]]) -> Result<Vec<Vec<Site>>, String> {
        match self {
            Resolver::Daemon(root) => {
                let req = lsp_daemon::Request::Definitions {
                    file: file.to_path_buf(),
                    positions: positions.to_vec(),
                };
                let resp = lsp_daemon::query(root, &req)
                    .ok_or_else(|| "lost connection to the lsp-daemon".to_string())?;
                if !resp.ok {
                    return Err(resp.error.unwrap_or_else(|| "definition query failed".into()));
                }
                Ok(resp
                    .definitions
                    .unwrap_or_default()
                    .into_iter()
                    .map(|v| {
                        v.into_iter()
                            .map(|c| (PathBuf::from(c.file), c.line, c.character))
                            .collect()
                    })
                    .collect())
            }
            Resolver::Session(session) => positions
                .iter()
                .map(|[l, c]| {
                    semq::retry_content_modified(|| {
                        session.definition(file, *l, *c).map_err(|e| e.to_string())
                    })
                    .map(|locs| {
                        locs.iter()
                            .map(|x| (x.path.clone(), x.range.start.line, x.range.start.character))
                            .collect()
                    })
                })
                .collect(),
            Resolver::Scip(s) => Ok(s.definitions(file, positions)),
        }
    }

    /// Shuts a one-shot session down; the daemon is left warm on purpose.
    pub(crate) fn finish(self) {
        if let Resolver::Session(s) = self {
            let _ = s.shutdown();
        }
    }
}

/// A hop filled in by hand: `from -> to`, both `file.rs::qualname`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct HandHop {
    pub(crate) from: String,
    pub(crate) to: String,
    pub(crate) note: String,
}

/// Reads and indexes workspace files and resolves calls through a
/// [`Resolver`]. One per workspace root; shared by every walk in a run.
pub(crate) struct Workspace {
    pub(crate) root: PathBuf,
    resolver: Resolver,
    files: HashMap<String, FileIndex>,
    /// Definition queries sent so far (progress reporting).
    pub(crate) queries: usize,
}

/// A graph under construction for one walk.
pub(crate) struct Walk {
    pub(crate) graph: CallGraph,
    hand: Vec<(NodeId, NodeId, String)>,
    /// Hand-filled hops the tool now resolves by itself.
    pub(crate) redundant_hand: Vec<String>,
    /// Calls into std or dependencies, filtered out.
    pub(crate) external_calls: usize,
    /// Set when the node cap stopped the search early.
    pub(crate) truncated: bool,
    /// Every resolved call site, one entry per site (`graph.edges` keeps
    /// only the first site per pair). `kovan-cli call-graph` (#737) reads
    /// these for its per-edge line lists and call counts.
    pub(crate) sites: Vec<Edge>,
}

impl Workspace {
    pub(crate) fn open(root: &Path) -> Result<Workspace, String> {
        let root = std::fs::canonicalize(root)
            .map_err(|e| format!("resolving workspace root {}: {e}", root.display()))?;
        let resolver = Resolver::connect(&root)?;
        Ok(Workspace {
            root,
            resolver,
            files: HashMap::new(),
            queries: 0,
        })
    }

    /// A workspace whose definitions come from a SCIP index (#757) instead
    /// of rust-analyzer's LSP. No rust-analyzer process is started.
    pub(crate) fn open_scip(root: &Path, index: crate::scip::ScipIndex) -> Result<Workspace, String> {
        let root = std::fs::canonicalize(root)
            .map_err(|e| format!("resolving workspace root {}: {e}", root.display()))?;
        Ok(Workspace {
            resolver: Resolver::Scip(ScipResolver::new(&root, index)),
            root,
            files: HashMap::new(),
            queries: 0,
        })
    }

    pub(crate) fn close(self) {
        self.resolver.finish();
    }

    pub(crate) fn index(&mut self, rel: &str) -> Result<&FileIndex, String> {
        if !self.files.contains_key(rel) {
            let text = std::fs::read_to_string(self.root.join(rel))
                .map_err(|e| format!("cannot read {rel}: {e}"))?;
            self.files.insert(rel.to_string(), FileIndex::parse(&text));
        }
        Ok(&self.files[rel])
    }

    /// The 1-based span of the declaration whose identifier is on `line`
    /// (1-based) of `rel`, for inline snippets; `None` when the file cannot
    /// be read or holds no `fn` there.
    pub(crate) fn span(&mut self, rel: &str, line: u32) -> Option<super::render::Span> {
        let idx = self.index(rel).ok()?;
        let d = idx.fn_at_line(line.checked_sub(1)?)?;
        let decl = d.line + 1;
        Some(match d.body {
            Some((open, end)) => super::render::Span {
                decl,
                open: open + 1,
                end: end + 1,
            },
            None => super::render::Span {
                decl,
                open: decl,
                end: decl,
            },
        })
    }

    /// Workspace-relative `/` path for an absolute one, or `None` when it is
    /// outside the workspace (std, the cargo registry) or in a build tree.
    fn relative(&self, abs: &Path) -> Option<String> {
        let canon = std::fs::canonicalize(abs).unwrap_or_else(|_| abs.to_path_buf());
        let rel = canon.strip_prefix(&self.root).ok()?;
        let s = rel
            .components()
            .map(|c| c.as_os_str().to_string_lossy())
            .collect::<Vec<_>>()
            .join("/");
        if s.starts_with("target/") || s.contains("/target/") || s.starts_with("vendor/") {
            return None;
        }
        Some(s)
    }

    pub(crate) fn node(rel: &str, d: &FnDecl) -> FnNode {
        FnNode {
            file: rel.to_string(),
            qualname: d.qualname(),
            line: d.line + 1,
            signature: d.signature.clone(),
            doc: d.doc.clone(),
        }
    }

    /// Resolves `crates/x/src/a.rs::name` or `...::Type::name` to the
    /// declaration it names.
    pub(crate) fn locate(&mut self, spec: &str) -> Result<FnNode, String> {
        let (file, qual) = split_spec(spec)?;
        let idx = self.index(&file)?;
        let found = idx.find(&qual);
        match found.as_slice() {
            [one] => Ok(Self::node(&file, one)),
            [] => Err(format!("no `fn` matching `{qual}` in {file}")),
            many => Err(format!(
                "`{qual}` is ambiguous in {file}: {} — qualify it as Type::name",
                many.iter()
                    .map(|d| format!("{} (line {})", d.qualname(), d.line + 1))
                    .collect::<Vec<_>>()
                    .join(", ")
            )),
        }
    }

    /// Starts a walk, resolving its hand-filled hops. A hop whose endpoint
    /// no longer exists is an error: the check mode must fail on it.
    pub(crate) fn start(&mut self, hand: &[HandHop]) -> Result<Walk, String> {
        let mut walk = Walk {
            graph: CallGraph::default(),
            hand: Vec::new(),
            redundant_hand: Vec::new(),
            external_calls: 0,
            truncated: false,
            sites: Vec::new(),
        };
        for h in hand {
            let a = self
                .locate(&h.from)
                .map_err(|e| format!("hand-filled hop `{} -> {}`: {e}", h.from, h.to))?;
            let b = self
                .locate(&h.to)
                .map_err(|e| format!("hand-filled hop `{} -> {}`: {e}", h.from, h.to))?;
            let (a, b) = (walk.graph.intern(a), walk.graph.intern(b));
            walk.hand.push((a, b, h.note.clone()));
        }
        Ok(walk)
    }

    /// Scans `id`'s body and records every edge and gap out of it.
    pub(crate) fn expand(&mut self, walk: &mut Walk, id: NodeId) -> Result<(), String> {
        if walk.graph.expanded[id.0] {
            return Ok(());
        }
        walk.graph.expanded[id.0] = true;
        let (file, line) = {
            let n = walk.graph.node(id);
            (n.file.clone(), n.line - 1)
        };
        let idx = self.index(&file)?;
        let Some(decl) = idx.fn_at_line(line).cloned() else {
            return Err(format!("{file}:{}: no fn declaration here any more", line + 1));
        };
        let cands: Vec<_> = idx
            .candidates(&decl)
            .into_iter()
            .filter(|c| !(c.kind == CandidateKind::Macro && is_known_macro(&c.name)))
            .collect();
        let ask: Vec<usize> = (0..cands.len())
            .filter(|&i| cands[i].kind != CandidateKind::IndirectCall)
            .collect();
        let positions: Vec<[u32; 2]> = ask.iter().map(|&i| [cands[i].line, cands[i].character]).collect();
        let abs = self.root.join(&file);
        self.queries += positions.len();
        if let Resolver::Scip(s) = &mut self.resolver {
            s.body = decl.body;
        }
        let answers = if positions.is_empty() {
            Vec::new()
        } else {
            self.resolver.definitions(&abs, &positions)?
        };
        let mut defs: Vec<Vec<Site>> = vec![Vec::new(); cands.len()];
        for (k, &i) in ask.iter().enumerate() {
            defs[i] = answers.get(k).cloned().unwrap_or_default();
        }

        for (cand, sites) in cands.iter().zip(defs) {
            let call_line = cand.line + 1;
            let gap = |kind: GapKind, target: Option<(String, u32)>, detail: String| Gap {
                from: id,
                call_line,
                kind,
                callee: match cand.kind {
                    CandidateKind::Macro => format!("{}!", cand.name),
                    _ => cand.name.clone(),
                },
                target,
                detail,
            };
            if cand.kind == CandidateKind::IndirectCall {
                push_gap(walk, gap(
                    GapKind::Closure,
                    None,
                    "call through a parenthesised expression (a closure or fn pointer)".into(),
                ));
                continue;
            }
            if sites.is_empty() {
                match cand.kind {
                    CandidateKind::Call => push_gap(walk, gap(
                        GapKind::NoDefinition,
                        None,
                        "rust-analyzer returned no definition".into(),
                    )),
                    CandidateKind::Macro => push_gap(walk, gap(
                        GapKind::Macro,
                        None,
                        "macro not resolved by rust-analyzer; its expansion is not followed".into(),
                    )),
                    _ => {}
                }
                continue;
            }
            for (path, dline, dchar) in sites {
                if path.as_os_str() == GENERATED_SITE {
                    if cand.kind == CandidateKind::Call {
                        push_gap(walk, gap(
                            GapKind::Other,
                            None,
                            "resolves to a workspace item a derive or macro generated; it has no body in the source".into(),
                        ));
                    }
                    continue;
                }
                let Some(rel) = self.relative(&path) else {
                    if cand.kind != CandidateKind::FnValue {
                        walk.external_calls += 1;
                    }
                    continue;
                };
                let tidx = self.index(&rel)?;
                let target_text = tidx.line_text(dline).to_string();
                if cand.kind == CandidateKind::Macro {
                    push_gap(walk, gap(
                        GapKind::Macro,
                        Some((rel.clone(), dline + 1)),
                        "workspace macro; its expansion is not followed".into(),
                    ));
                    continue;
                }
                // The fallback to "the fn declared on that line" must not
                // take a site to the RIGHT of the fn's name: that is one of
                // its parameters (`fn f(g: impl Fn())`), and calling `g` is
                // not a recursive call to `f` (#757 found 7 such false
                // self-edges in the LSP-built graph).
                if let Some(d) = tidx
                    .fns
                    .iter()
                    .find(|f| f.line == dline && f.character == dchar)
                    .or_else(|| tidx.fn_at_line(dline).filter(|f| dchar <= f.character))
                    .cloned()
                {
                    if let Container::Trait { name } = &d.container {
                        push_gap(walk, gap(
                            GapKind::Trait,
                            Some((rel.clone(), dline + 1)),
                            format!(
                                "trait method `{name}::{}`; the implementor is chosen by type, not followed",
                                d.name
                            ),
                        ));
                        continue;
                    }
                    let to = walk.graph.intern(Self::node(&rel, &d));
                    let edge = Edge {
                        from: id,
                        to,
                        call_line,
                        kind: match cand.kind {
                            CandidateKind::FnValue => EdgeKind::FnValue,
                            _ => EdgeKind::Call,
                        },
                    };
                    walk.sites.push(edge.clone());
                    walk.graph.add_edge(edge);
                    continue;
                }
                if cand.kind == CandidateKind::FnValue || is_constructor(&target_text, &cand.name) {
                    continue; // a variable, or a tuple-struct / variant constructor
                }
                let binding = target_text.starts_with("let ")
                    || target_text.contains('|')
                    || (rel == file && dline >= decl.line && dline <= decl.body.map_or(dline, |b| b.0));
                if binding {
                    push_gap(walk, gap(
                        GapKind::Closure,
                        Some((rel.clone(), dline + 1)),
                        format!("call through a closure or fn-typed binding `{}`", cand.name),
                    ));
                } else {
                    push_gap(walk, gap(
                        GapKind::Other,
                        Some((rel.clone(), dline + 1)),
                        format!("resolves to `{}`, not a function body", truncate(&target_text, 80)),
                    ));
                }
            }
        }

        // SCIP only (#757): operators and functions named as paths.
        if let Resolver::Scip(s) = &mut self.resolver {
            let skip: HashSet<(u32, u32)> = cands.iter().map(|c| (c.line, c.character)).collect();
            let idx = self.files.get(&file).ok_or_else(|| format!("{file}: not indexed"))?;
            let body: Vec<(u32, String, String)> = idx
                .body_code(&decl)
                .into_iter()
                .map(|(ln, code)| {
                    let orig = idx.lines.get(ln as usize).cloned().unwrap_or_default();
                    (ln, code, orig)
                })
                .collect();
            let extra = s.extra_references(&file, &body, &skip);
            for x in extra {
                let Some(rel) = self.relative(&x.site.0) else {
                    continue;
                };
                let (dline, dchar) = (x.site.1, x.site.2);
                let Some(d) = self
                    .index(&rel)?
                    .fns
                    .iter()
                    .find(|f| f.line == dline && f.character == dchar)
                    .cloned()
                else {
                    continue; // a constant, a type, a field: not a call
                };
                let call_line = x.line + 1;
                if let Container::Trait { name } = &d.container {
                    push_gap(walk, Gap {
                        from: id,
                        call_line,
                        kind: GapKind::Trait,
                        callee: x.token.clone(),
                        target: Some((rel.clone(), dline + 1)),
                        detail: format!(
                            "trait method `{name}::{}`; the implementor is chosen by type, not followed",
                            d.name
                        ),
                    });
                    continue;
                }
                let to = walk.graph.intern(Self::node(&rel, &d));
                let edge = Edge {
                    from: id,
                    to,
                    call_line,
                    kind: if x.ident { EdgeKind::FnValue } else { EdgeKind::Operator },
                };
                walk.sites.push(edge.clone());
                walk.graph.add_edge(edge);
            }
        }

        let hand: Vec<(NodeId, NodeId, String)> =
            walk.hand.iter().filter(|h| h.0 == id).cloned().collect();
        for (a, b, note) in hand {
            if walk.graph.edge(a, b).is_some() {
                walk.redundant_hand.push(format!(
                    "{} -> {}",
                    walk.graph.node(a).key(),
                    walk.graph.node(b).key()
                ));
                continue;
            }
            let call_line = walk.graph.node(a).line;
            walk.graph.add_edge(Edge {
                from: a,
                to: b,
                call_line,
                kind: EdgeKind::Hand { note },
            });
        }
        Ok(())
    }

    /// Breadth-first expansion from `from`, one layer at a time, stopping
    /// after the layer in which `target` is first reached (so every shortest
    /// chain to it is present), at `max_depth` layers, or once more than
    /// `max_nodes` functions are known.
    pub(crate) fn bfs(
        &mut self,
        walk: &mut Walk,
        from: NodeId,
        target: Option<NodeId>,
        max_depth: usize,
        max_nodes: usize,
    ) -> Result<(), String> {
        let mut seen = vec![false; walk.graph.nodes.len()];
        seen[from.0] = true;
        let mut layer = vec![from];
        for depth in 0..max_depth {
            if layer.is_empty() || target.is_some_and(|t| t != from && seen[t.0]) {
                break;
            }
            let mut next = Vec::new();
            for &u in &layer {
                self.expand(walk, u)?;
                seen.resize(walk.graph.nodes.len(), false);
                for e in walk.graph.out_edges(u) {
                    if !seen[e.to.0] {
                        seen[e.to.0] = true;
                        next.push(e.to);
                    }
                }
            }
            eprintln!(
                "kovan-cli code-walk: depth {} done — {} functions, {} definition queries",
                depth + 1,
                walk.graph.nodes.len(),
                self.queries
            );
            if walk.graph.nodes.len() > max_nodes {
                walk.truncated = true;
                break;
            }
            layer = next;
        }
        Ok(())
    }
}

/// Methodology: the head of the path before a token, across `::` and
/// spaces, and none for an unqualified token or a method call.
///
/// Result (2026-10-07): passes.
#[cfg(test)]
#[test]
fn path_heads_are_read() {
    let line = "    my_crate::prelude::run(x) + Self::f + g(y.h())";
    let col = |t: &str| line.find(t).unwrap() as u32;
    assert_eq!(path_head(line, col("run")).as_deref(), Some("my_crate"));
    assert_eq!(path_head(line, col("f +")).as_deref(), Some("Self"));
    assert_eq!(path_head(line, col("g(")), None);
    assert_eq!(path_head(line, col("h()")), None);
    assert_eq!(path_head(line, 0), None);
}

fn push_gap(walk: &mut Walk, g: Gap) {
    if !walk
        .graph
        .gaps
        .iter()
        .any(|x| x.from == g.from && x.call_line == g.call_line && x.callee == g.callee)
    {
        walk.graph.gaps.push(g);
    }
}

/// A tuple struct or enum variant: `struct Name(`, or a variant line
/// `Name(...)` / `Name {` / `Name,`.
fn is_constructor(target_text: &str, name: &str) -> bool {
    let t = target_text
        .trim_start_matches("pub(crate) ")
        .trim_start_matches("pub ");
    if t.starts_with("struct ") || t.starts_with("enum ") {
        return true;
    }
    t.strip_prefix(name)
        .and_then(|r| r.trim_start().chars().next())
        .is_some_and(|c| matches!(c, '(' | '{' | ','))
        && name.chars().next().is_some_and(char::is_uppercase)
}

fn truncate(s: &str, n: usize) -> String {
    if s.chars().count() <= n {
        s.to_string()
    } else {
        format!("{}…", s.chars().take(n).collect::<String>())
    }
}

/// Splits `crates/x/src/a.rs::Type::name` into the file and the qualified
/// name.
pub(crate) fn split_spec(spec: &str) -> Result<(String, String), String> {
    let Some(i) = spec.find(".rs::") else {
        return Err(format!(
            "`{spec}` is not of the form <path/to/file.rs>::<fn> (or ::<Type>::<fn>)"
        ));
    };
    let file = spec[..i + 3].trim_start_matches("./").to_string();
    let qual = spec[i + 5..].to_string();
    if qual.is_empty() {
        return Err(format!("`{spec}` names no function after `::`"));
    }
    Ok((file, qual))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Methodology: the spec form, with and without a type qualifier, and
    /// two malformed specs.
    ///
    /// Result (2026-10-04): passes.
    #[test]
    fn split_spec_parses_file_and_qualified_name() {
        assert_eq!(
            split_spec("crates/a/src/geom.rs::Sphere::distance").unwrap(),
            ("crates/a/src/geom.rs".into(), "Sphere::distance".into())
        );
        assert_eq!(
            split_spec("./x.rs::main").unwrap(),
            ("x.rs".into(), "main".into())
        );
        assert!(split_spec("transport_history").is_err());
        assert!(split_spec("a.rs::").is_err());
    }

    /// Methodology: constructor lines (tuple struct, variant) must be
    /// recognised so they are not reported as gaps; a `let` binding and a
    /// lowercase name must not be.
    ///
    /// Result (2026-10-04): passes.
    #[test]
    fn constructors_are_recognised() {
        assert!(is_constructor("pub struct Coord(u32, u32);", "Coord"));
        assert!(is_constructor("Sphere(SphereData),", "Sphere"));
        assert!(is_constructor("Absorb { weight: f64 },", "Absorb"));
        assert!(!is_constructor("let f = |x| x + 1;", "f"));
        assert!(!is_constructor("static F: fn() = g;", "F"));
    }
}
