#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0
"""PROCESSING of the maintainer's digitised Stoyer Fig. 5 (gh:#413 check (b)):
dense, shape-preserving resampling for upstream TRISO-ATOPS's grid-sensitive
`coolant_release` (cumulative-trapezoid integral of dn/dt over the supplied
time points).

- Input: `verification_and_validation/mhtgr_stoyer/fig05_accident_temperature_c.csv`
  (kovan 066e691, as digitised). t < 0 clamped to 0, as everywhere else.
- Interpolant: PCHIP -- the Fritsch-Carlson monotone piecewise-cubic Hermite
  scheme with the derivative rule of scipy.interpolate.PchipInterpolator
  (weighted harmonic mean of the adjacent secants at interior points, zero
  where the secants change sign; the three-point one-sided formula at the
  ends, with the same shape clamps). Implemented here in numpy because scipy
  is not installed; `self_test()` checks monotonicity and interpolation.
- Grid: every 0.1 h from 0 to each curve's last digitised time (rounded down
  to the grid), plus that last point itself.
- Output: `fig05_accident_temperature_c_pchip_0p1h.csv`.
"""
import csv
from pathlib import Path
import numpy as np

DATA = Path(__file__).resolve().parent.parent / "verification_and_validation" / "mhtgr_stoyer"

def pchip_slopes(x, y):
    h = np.diff(x); d = np.diff(y) / h
    n = len(x); m = np.zeros(n)
    for k in range(1, n - 1):
        if d[k - 1] * d[k] > 0:
            w1 = 2 * h[k] + h[k - 1]; w2 = h[k] + 2 * h[k - 1]
            m[k] = (w1 + w2) / (w1 / d[k - 1] + w2 / d[k])
    def end(h0, h1, d0, d1):
        s = ((2 * h0 + h1) * d0 - h0 * d1) / (h0 + h1)
        if np.sign(s) != np.sign(d0):
            return 0.0
        if np.sign(d0) != np.sign(d1) and abs(s) > abs(3 * d0):
            return 3 * d0
        return s
    m[0] = end(h[0], h[1], d[0], d[1])
    m[-1] = end(h[-1], h[-2], d[-1], d[-2])
    return m

def pchip(x, y, xs):
    m = pchip_slopes(x, y)
    i = np.clip(np.searchsorted(x, xs, side="right") - 1, 0, len(x) - 2)
    h = x[i + 1] - x[i]; t = (xs - x[i]) / h
    h00 = 2 * t**3 - 3 * t**2 + 1; h10 = t**3 - 2 * t**2 + t
    h01 = -2 * t**3 + 3 * t**2; h11 = t**3 - t**2
    return h00 * y[i] + h10 * h * m[i] + h01 * y[i + 1] + h11 * h * m[i + 1]

def self_test():
    x = np.array([0.0, 1.0, 2.0, 3.0, 4.0]); y = np.array([0.0, 1.0, 1.0, 3.0, 2.0])
    assert np.allclose(pchip(x, y, x), y)
    xs = np.linspace(1, 2, 101); ys = pchip(x, y, xs)
    assert np.allclose(ys, 1.0), "flat interval must stay flat (no overshoot)"
    xs = np.linspace(2, 3, 101); ys = pchip(x, y, xs)
    assert np.all(np.diff(ys) >= -1e-12), "monotone data must give a monotone interpolant"

def main():
    self_test()
    curves = {}
    with open(DATA / "fig05_accident_temperature_c.csv") as f:
        for r in csv.DictReader(l for l in f if not l.startswith("#")):
            curves.setdefault((r["core_fraction_percent"], r["marker"]), []).append(
                (max(0.0, float(r["time_h"])), float(r["temperature_c"])))
    out = ["# PROCESSING of the maintainer's digitised Fig. 5 (kovan 066e691; fig05_accident_temperature_c.csv), gh:#413 check (b):\n",
           "# t < 0 clamped to 0; PCHIP (Fritsch-Carlson, scipy PchipInterpolator rule) resampled every 0.1 h to each curve's last point.\n",
           "# Generated by dev/mhtgr_stoyer_fig5_pchip.py. These are interpolated values, not digitised points.\n",
           "core_fraction_percent,time_h,temperature_c\n"]
    for (pct, _), pts in curves.items():
        x = np.array([t for t, _ in pts]); y = np.array([T for _, T in pts])
        grid = np.arange(0.0, x[-1], 0.1)
        grid = np.append(grid[grid < x[-1] - 1e-9], x[-1])
        ys = pchip(x, y, grid)
        for t, T in zip(grid, ys):
            out.append(f"{pct},{t:.6f},{T:.6f}\n")
        print(f"{pct} %: {len(pts)} digitised -> {len(grid)} samples, peak {ys.max():.2f} C (digitised {y.max():.2f})")
    (DATA / "fig05_accident_temperature_c_pchip_0p1h.csv").write_text("".join(out))

if __name__ == "__main__":
    main()
