//! SVG backend.
//!
//! Issue #26 lists SVG as "optional if easy". It is easy — it is the same draw
//! list the PDF and PNG backends consume, serialised as `<polyline>` and
//! `<polygon>` elements — so it is here.
//!
//! The output references no external font, no CSS and no image: every glyph is
//! already a path, so the file renders identically in a browser, in Inkscape and
//! in a LaTeX `\includegraphics` pipeline.

use super::layout::{DrawOp, PageSize};
use super::{FigurePalette, Rgb, Scene};

/// Renders a scene to a standalone SVG document, in `palette`'s colours.
pub fn render(scene: &Scene, page: PageSize, palette: FigurePalette) -> String {
    let ops = super::layout::to_draw_ops(scene, page, palette);
    render_ops(&ops, page)
}

/// Serialises an already-laid-out draw list.
pub fn render_ops(ops: &[DrawOp], page: PageSize) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{w}pt\" height=\"{h}pt\" \
         viewBox=\"0 0 {w} {h}\">\n",
        w = trim(page.width_pt),
        h = trim(page.height_pt),
    ));
    out.push_str(
        "<!-- Generated by the tampines-steam-tables-gui example \
         (GitHub issue #26). All curves computed live from IAPWS-IF97; all \
         scattered points are cited reference data. -->\n",
    );
    for op in ops {
        match op {
            DrawOp::Polygon { points, colour } => {
                out.push_str(&format!(
                    "<polygon points=\"{}\" fill=\"{}\" stroke=\"none\"/>\n",
                    point_list(points),
                    colour.as_hex()
                ));
            }
            DrawOp::Polyline {
                points,
                width,
                colour,
                dash,
            } => {
                let dash_attr = match dash {
                    Some((on, off)) => {
                        format!(" stroke-dasharray=\"{} {}\"", trim(*on), trim(*off))
                    }
                    None => String::new(),
                };
                out.push_str(&format!(
                    "<polyline points=\"{}\" fill=\"none\" stroke=\"{}\" \
                     stroke-width=\"{}\" stroke-linecap=\"round\" \
                     stroke-linejoin=\"round\"{}/>\n",
                    point_list(points),
                    colour.as_hex(),
                    trim(*width),
                    dash_attr
                ));
            }
        }
    }
    out.push_str("</svg>\n");
    out
}

/// `x,y x,y ...` as SVG wants it.
fn point_list(points: &[[f64; 2]]) -> String {
    let mut s = String::with_capacity(points.len() * 14);
    for (i, p) in points.iter().enumerate() {
        if i > 0 {
            s.push(' ');
        }
        s.push_str(&format!("{},{}", trim(p[0]), trim(p[1])));
    }
    s
}

/// Formats a coordinate to 0.01 pt and strips trailing zeros, which keeps the
/// file small and, more importantly, keeps it **byte-reproducible**: the same
/// scene always serialises to the same bytes.
fn trim(v: f64) -> String {
    let s = format!("{v:.2}");
    let s = s.trim_end_matches('0').trim_end_matches('.').to_string();
    if s == "-0" {
        "0".to_string()
    } else {
        s
    }
}

/// Unused-import guard: `Rgb` is referenced only through `DrawOp`.
#[allow(dead_code)]
fn _rgb_is_used(_: Rgb) {}

/// Checks that SVG serialisation is deterministic and structurally complete.
///
/// # Methodology
///
/// Renders the same scene twice and asserts the two strings are byte-identical
/// (the reproducibility issue #26 asks for), then asserts the document opens and
/// closes its root element and contains at least one `<polyline>`.
///
/// # Result
///
/// Passes as of 2026-08-20.
#[cfg(test)]
#[test]
fn svg_output_is_byte_reproducible() {
    use super::{Series, SeriesStyle, INK};
    let mut scene = Scene::new("Repro", "x", "y");
    scene.series.push(Series {
        name: "s".into(),
        style: SeriesStyle::Line {
            width: 1.0,
            dash: None,
        },
        colour: INK,
        points: vec![[0.1, 0.1], [0.9, 0.9]],
        show_in_legend: true,
    });
    let a = render(&scene, PageSize::DEFAULT, FigurePalette::LIGHT_PUBLICATION);
    let b = render(&scene, PageSize::DEFAULT, FigurePalette::LIGHT_PUBLICATION);
    assert_eq!(a, b, "SVG export must be byte-reproducible");
    assert!(a.starts_with("<svg"));
    assert!(a.trim_end().ends_with("</svg>"));
    assert!(a.contains("<polyline"));
}
